### ISSUE TITLE
Dendron commands stopped working 

### ISSUE THREAD

**Issue by komoda102** [dendronhq/dendron#100]
**Describe the bug**
Hi,
After updating VS Code to 1.48 all dendron commands just stopped working.
For example for lookup message says "Command 'Dendron: Lookup' resulted in an error (command 'dendron.lookup' not found)"

I have found out that when I start VS Code without any workspace, dendron commands are working. I can initialize new dendron workspace and in this new workspace commands are working. I can add new notes using lookup and so on. But after VS Code restart I all commands "cannot be found". Also I noticed that Markdown Preview is not working at all, even just after new workspace initialization.

**To Reproduce**
1. Try to use any command

**Expected behavior**
Dendron commands are working again

**Screenshots**
![image](https://user-images.githubusercontent.com/21131710/90595937-307a2a00-e1ee-11ea-9f06-c6a6a621ffef.png)

**Desktop (please complete the following information):**
 - VS Code 1.48
 - Dendron 0.7.4

**Comment by komoda102** [comment]
I have created new workspace and in new one everything works fine. Any ideas what to do to fix my workspace?

**Comment by kevinslin** [comment]
Can you tell me the following information: 

- Dendron Markdown Preview Enhanced version?
- Operating system?

Also, if you open up a new or existing workspace, use `Dendron: Open Logs` and send the output here: https://www.dropbox.com/request/6PuqQuZKAYli0tR95aVc

**Comment by komoda102** [comment]
* Dendron Markdown Preview Enhanced 0.5.17
* Operating system: Windows 10 Pro Version 1909

I have sent you two logs: dendron1.log after commands worked and dendron2.log after VSC restart after commands stopped working

**Comment by kevinslin** [comment]
glad to hear it. we had an issue involving file paths with the previous version of "Dendron Markdown Preview Enhanced". it seems you were affected by it but moving forward, this will no longer be an issue! closing the issue but feel free to re-open if anything comes up again
