### ISSUE TITLE
Footnotes in host and referenced notes clash counterintuitively

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#1001]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When one note is referenced within another and has footnotes, the incoming footnotes appear outside of the text box at the bottom of the note text as if they belong to the host note. This seems incorrect and if one adds references to the host note that has an embedded reference note with footnotes, the host note's footnotes override the incoming footnotes causing havoc. Needs fixing, I think.

## To Reproduce

1. Make a note A. Type some text.
2. Make another note B with some footnotes.
3. Reference note A in note B.
4. Add some footnotes to note B.
5. The new footnotes override the footnotes embedded from note A.

## Expected behavior

Note A footnotes should apprear within the embedded box.
Note B footnotes should be independent from the embedded footnotes.

**Comment by SR--** [comment]
By the way, this is in Dendrone Preview Enhanced. I now see that in v51 in Preview v2 the footnotes are in the box but they are bunched into a paragraph and have empty square brackets rendered instead of numbers.

**Comment by SR--** [comment]
on footnotes. in Preview v2 in v52 the superscript numbers and and the numbers in footnotes render correctly. however, in embedded/referenced notes the footnotes are now outside of the embedded box as it used to be in Preview v1. still needs fixing, please. Also, a minor issue, can the return link be rendered in a less prominent way? a pale arrow on white before was better, it is not an important piece of information and is distracting.

**Comment by SR--** [comment]
Can the footnote number not act as a return link the same way the superscript number is a link to the footnote?

**Comment by SeriousBug** [comment]
The return arrow is too prominent because of the symbol that's used for it. Some fonts seem to render it more prominently with the blue rectangle. We can replace it with some other symbol to fix it. Any thoughts?

I found this list of arrow symbols, but I'm not sure what to use: https://unicode-table.com/en/sets/arrow-symbols/#harpoon-arrows

It could also be any other unicode symbol.

**Comment by SR--** [comment]
Hm... In this case, should not footnotes use the same format as their inline references?

**Footnotes**

one
other

![image](https://user-images.githubusercontent.com/1008059/137308008-586153a3-0a43-40fc-8caf-a6a78a2e6ca5.png)

**Comment by SeriousBug** [comment]
This issue has been fixed in Dendron 64, footnotes will now be displayed inside the reference. Please let us know if you are having any problems with the feature, this issue will otherwise close in a few days.

**Comment by SeriousBug** [comment]
As a reminder to myself, need to fix a bug with rendering when there are multiple things in the footnote definition (e.g. a link followed by some text).

**Comment by kevinslin** [comment]
@SR-- this should be fixed in 0.69 - can you confirm if you're still seeing issues?

**Comment by SR--** [comment]
This seems to be working well now. Thanks. You could argue that the gap betweent the end of the text of the footnote and the up arrow is a bit large but one can live with that if this if this is low priority.
![image](https://user-images.githubusercontent.com/1008059/142955605-f7e3fc97-67d6-43b0-8141-fa9c4ecc40aa.png)
