### ISSUE TITLE
Creat New one output error

### ISSUE THREAD

**Issue by bonnebulle** [dendronhq/dendron#1013]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [X] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When I want to creat a text-note I have this error notification : "Cannot read property 'name' of undefined" and an other saying to go here on github for help_debug)

## To Reproduce

1. Open Lookup (with shortcut, from an empty_new or old file)
2. Select a file name ("Creat New" one)
3. have the error notification "Cannot read property 'name' of undefined" 

## Expected behavior
I just cant creat new notes

## Screenshots
No one, sorry

## Desktop (please complete the following information)

- OS: Linux Debian
- Vscodium, last version 1.48 (idem for dendron 0.48.0)

## Additional context
I was not working on it for a long time and dendron just upgraded

## Dendron Log file
`{"level":30,"time":1626968058358,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"u:run","msg":"pre-execute"}
{"level":30,"time":1626968058359,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupCommand:execute","opts":{"flavor":"note"},"msg":"enter"}
{"level":30,"time":1626968058361,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupCommand:execute","profile":2,"msg":"postCreateController"}
{"level":30,"time":1626968058363,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupCommand:execute","profile":3,"msg":"post:extractRange"}
{"level":30,"time":1626968058363,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupControllerV2:show","msg":"enter","cleanOpts":{"ignoreFocusOut":true}}
{"level":30,"time":1626968058370,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupControllerV2:show","profile":6,"msg":"post:createQuickPick"}
{"level":30,"time":1626968058371,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupControllerV2:show","profile":7,"msg":"post:createProvider"}
{"level":30,"time":1626968058373,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerBehavior","activeButtons":[{"iconPathNormal":{"id":"find-selection"},"iconPathPressed":{"id":"menu-selection"},"type":"selectionExtract","pressed":true,"title":"Selection Extract","canToggle":true,"opts":{"title":"Selection Extract","iconOff":"find-selection","iconOn":"menu-selection","type":"selectionExtract"}}]}
{"level":30,"time":1626968058385,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupCommand:execute","profile":15,"msg":"post:show"}
{"level":30,"time":1626968058389,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"dendron.log","source":"updatePickerBehavior:normal"}
{"level":30,"time":1626968058391,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968058403,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupControllerV2:show","profile":7,"msg":"post:updatePickerBehavior"}
{"level":30,"time":1626968058404,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupControllerV2:show","profile":7,"msg":"post:provide"}
{"level":30,"time":1626968058405,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupControllerV2:show","profile":7,"msg":"exit"}
{"level":30,"time":1626968058405,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968058420,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968058421,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968058465,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"u:run","msg":"post-execute"}
{"level":30,"time":1626968058465,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":74}
{"level":30,"time":1626968058466,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"dendron.log","source":"updatePickerBehavior:normal","profile":77,"cancelled":false}
{"level":30,"time":1626968058616,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"dendron.log","source":"onValueChange"}
{"level":30,"time":1626968058658,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968058664,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968058675,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968058686,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968058710,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":51}
{"level":30,"time":1626968058712,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"dendron.log","source":"onValueChange","profile":95,"cancelled":false}
{"level":30,"time":1626968075027,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"t","source":"onValueChange"}
{"level":30,"time":1626968075028,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968075036,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968075056,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968075058,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968075060,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":32}
{"level":30,"time":1626968075061,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"t","source":"onValueChange","profile":34,"cancelled":true}
{"level":30,"time":1626968075096,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"te","source":"onValueChange"}
{"level":30,"time":1626968075096,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968075126,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968075131,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968075132,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968075252,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":155}
{"level":30,"time":1626968075260,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"te","source":"onValueChange","profile":164,"cancelled":false}
{"level":30,"time":1626968075271,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"tes","source":"onValueChange"}
{"level":30,"time":1626968075272,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968075279,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968075288,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968075288,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968075347,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":74}
{"level":30,"time":1626968075349,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"tes","source":"onValueChange","profile":77,"cancelled":false}
{"level":30,"time":1626968075428,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test","source":"onValueChange"}
{"level":30,"time":1626968075428,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968075431,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968075436,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968075436,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968075552,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":123}
{"level":30,"time":1626968075554,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test","source":"onValueChange","profile":126,"cancelled":false}
{"level":30,"time":1626968081171,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.","source":"onValueChange"}
{"level":30,"time":1626968081172,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968081185,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968081197,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968081198,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968081259,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":86}
{"level":30,"time":1626968081260,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.","source":"onValueChange","profile":88,"cancelled":false}
{"level":30,"time":1626968082325,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.e","source":"onValueChange"}
{"level":30,"time":1626968082326,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968082330,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968082334,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968082334,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968082385,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":58}
{"level":30,"time":1626968082386,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.e","source":"onValueChange","profile":61,"cancelled":false}
{"level":30,"time":1626968082587,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.er","source":"onValueChange"}
{"level":30,"time":1626968082588,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968082592,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968082597,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968082598,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968082609,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":21}
{"level":30,"time":1626968082611,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.er","source":"onValueChange","profile":24,"cancelled":false}
{"level":30,"time":1626968082745,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.err","source":"onValueChange"}
{"level":30,"time":1626968082746,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968082752,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968082758,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968082758,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968082782,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":36}
{"level":30,"time":1626968082783,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.err","source":"onValueChange","profile":38,"cancelled":false}
{"level":30,"time":1626968082996,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.erro","source":"onValueChange"}
{"level":30,"time":1626968082996,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968083002,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968083008,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968083008,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968083035,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":38}
{"level":30,"time":1626968083036,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.erro","source":"onValueChange","profile":40,"cancelled":false}
{"level":30,"time":1626968083485,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.error","source":"onValueChange"}
{"level":30,"time":1626968083486,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626968083494,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626968083498,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1626968083498,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626968083519,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":33}
{"level":30,"time":1626968083522,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.error","source":"onValueChange","profile":37,"cancelled":false}
{"level":50,"time":1626968084629,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"onDidAcceptSingle","error":{"stack":"TypeError: Cannot read property 'name' of undefined\n\tat E.lc (/home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:562519)\n\tat t.LookupProviderV2.onDidAcceptForSingle (/home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:562668)\n\tat t.LookupProviderV2.onDidAccept (/home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:562068)\n\tat /home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:566261\n\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n\tat t._fireDidAccept (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:6375)\n\tat w.$onDidAccept (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:3968)\n\tat u._doInvokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12744)\n\tat u._invokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12436)\n\tat u._receiveRequest (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11098)\n\tat u._receiveOneMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9901)\n\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8005\n\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n\tat h.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\n\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29793\n\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n\tat h.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\n\tat r._receiveMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21035)\n\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17921\n\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n\tat c.acceptChunk (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13138)\n\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12486\n\tat Socket._ (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13106)\n\tat Socket.emit (events.js:315:20)\n\tat addChunk (internal/streams/readable.js:309:12)\n\tat readableAddChunk (internal/streams/readable.js:284:9)\n\tat Socket.Readable.push (internal/streams/readable.js:223:10)\n\tat Pipe.onStreamRead (internal/stream_base_commons.js:188:23)","message":"Cannot read property 'name' of undefined"}}
{"level":50,"time":1626968084633,"pid":15830,"hostname":"raspberrypi","name":"dendron","ctx":"LookupProvider:onAccept","error":{"stack":"Error: something went wrong. please submit a bug report to https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= with the output of `Dendron: Open Log`\n\tat /home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:566359\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)","message":"something went wrong. please submit a bug report to https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= with the output of `Dendron: Open Log`","isComposite":false,"status":"unknown","payload":"{\"msg\":\"Cannot read property 'name' of undefined\",\"stack\":\"TypeError: Cannot read property 'name' of undefined\\n\\tat E.lc (/home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:562519)\\n\\tat t.LookupProviderV2.onDidAcceptForSingle (/home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:562668)\\n\\tat t.LookupProviderV2.onDidAccept (/home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:562068)\\n\\tat /home/pi/.vscode-oss/extensions/dendron.dendron-0.48.0/dist/extension.js:297:566261\\n\\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n\\tat t._fireDidAccept (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:6375)\\n\\tat w.$onDidAccept (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:3968)\\n\\tat u._doInvokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12744)\\n\\tat u._invokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12436)\\n\\tat u._receiveRequest (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11098)\\n\\tat u._receiveOneMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9901)\\n\\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8005\\n\\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n\\tat h.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\\n\\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29793\\n\\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n\\tat h.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\\n\\tat r._receiveMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21035)\\n\\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17921\\n\\tat d.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n\\tat c.acceptChunk (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13138)\\n\\tat /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12486\\n\\tat Socket._ (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13106)\\n\\tat Socket.emit (events.js:315:20)\\n\\tat addChunk (internal/streams/readable.js:309:12)\\n\\tat readableAddChunk (internal/streams/readable.js:284:9)\\n\\tat Socket.Readable.push (internal/streams/readable.js:223:10)\\n\\tat Pipe.onStreamRead (internal/stream_base_commons.js:188:23)\"}"}}
`

**Comment by bonnebulle** [comment]
Hello
It looks like the problem is not persistant with Vscode official. 
So, the problem not looking to be from Dendron ...

**Comment by hikchoi** [comment]
Hey, thanks for the bug report.
I'm glad changing VSCode to the official build fixed this issue, but I'll leave you with some things to check in case you ever run into this again:

We have added a config auto-migration process for daily journal configs but this may be not worked properly.
You should see something like this in your config:

```
journal:
    dailyDomain: daily
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfDomainNamespace
    firstDayOfWeek: 1
```

If the problem happens again, try adding this to `dendron.yml` and see if the problem goes away.

I'll close this issue for now but feel free to re-open it if the problem persists.

**Comment by bonnebulle** [comment]
Just for notice... 
I upgrade Codium, all working fine now. 
Thanks for the details.
