### ISSUE TITLE
Wiki links point to invalid URLs in published notes

### ISSUE THREAD

**Issue by ric03uec** [dendronhq/dendron#103]
**Describe the bug**
When I try to create a wiki link using `[[my.other.note]]` syntax, the published note does not point the URL to the correct target note. In this case, it'll point to `localhost:4000/notes/my.other.note` which gives a 404 page.

**To Reproduce**
1. Create a note `foo.note1.md`
2. Create a note `foo.note2.md`
3. in `foo.note1.md`, add a line `this is a link to [[foo.note2.md]]`. The link can also be `[[foo.note2]]`. Save and exit
4. Rebuild index and build pod
5. Navigate to `localhost:4000` and go to `foo.note1` webpage
6. Click on the link `foo.note2`
7. The webpage shows following error
![image](https://user-images.githubusercontent.com/1110988/90675557-7eebf080-e20f-11ea-909e-b0d53a8f0626.png)

**Expected behavior**
The link to note2 should open up the page for note2

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by kevinslin** [comment]
thanks for the report. fixed!
