### ISSUE TITLE
Full note reference breaks previewv2

### ISSUE THREAD

**Issue by unamusedmon** [dendronhq/dendron#1035]
## Please select the area your Bug applys to. (Multiple selections are Possible)
- [ x] Misc (Choose this if your not sure)

## Describe the bug

Full note reference seems to break preview v2  making it so it doesn't update on new text addition

## To Reproduce

1. Go to ' a note and insert a full note reference' 
2. have previewv2 open
3. the note reference doesn't show up
4.  preview2 freezes without updating

## Expected behavior
show note preview

## Screenshots
![after](https://user-images.githubusercontent.com/65274123/126925865-0b32bf92-7d8c-476d-852a-68d354d6dd22.png)

## Desktop (please complete the following information)

- OS: Manjaro
- Browser : Vivaldi
- Version: 0.51.0

## Dendron Log file
[log.txt](https://github.com/dendronhq/dendron/files/6875188/log.txt)

**Comment by kevinslin** [comment]
@unamusedmon  wasn't able to reproduce. can you confirm if this still happens in 0.53?

**Comment by unamusedmon** [comment]
Yes i can no lone reproduce either

**Comment by kevinslin** [comment]
Awesome. Will close this ticket then :)
