### ISSUE TITLE
Remnants of syntax highlighting persisting in editor

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#1039]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug
I'm intermittently seeing italicized text in the editor while editing text in a plain paragraph where it normally shouldn't be italicized.

## To Reproduce
I am suspecting syntax highlighting for wikilinks is left there after undo or something but I can't seem to reliably reproduce this.

These are a few places I've seen it happen:
1. After `Insert Note Link`, remove the brackets to make it not a wikilink.
2. Undo after Lookup with `selection2link` modifier
3. In a new note after lookup with `selectionExtract` modifier

## Expected behavior
Syntax highlighting isn't applied in places where it shouldn't. Syntax highlighting is removed when it is no longer applicable.

## Desktop (please complete the following information)

- OS: MacOS Big Sur 11.3.1 (Mac mini, M1, 2020)
- Version [0.51.2]

**Comment by SeriousBug** [comment]
VSCode doesn't always regenerate the syntax highlighting, in some cases it just expands or shrinks the existing highlighted regions. I'll see if there's anything we can do in these cases.

**Comment by SeriousBug** [comment]
I re-checked the API. VSCode has a `rangeBehavior` that allows us to tell VSCode when the highlighted range should expand (for example, wikilinks don't expand because if you type after the brackets that's outside the wikilink now). There is no way to tell VSCode that it also shouldn't shrink.

We can't really work around this issue in an efficient manner, so I'll place this in our backlog for now. I'll create an issue with VSCode to see if this is something they are planning to fix.

**Comment by hikchoi** [comment]
I see. Usually a reload will fix this issue so it's not really bothersome. Thanks for looking into this!

**Comment by SeriousBug** [comment]
Nevermind that, it had nothing to do with VSCode. The issue was slightly different, it only happens if you have just one valid wikilink and you erase part of it. I have a bug fix for it now!

**Comment by SeriousBug** [comment]
This has now been fixed in version 0.53.
