### ISSUE TITLE
Notes created with 'doctor' from '#' (tags), include punctuation chars that follow them in the name

### ISSUE THREAD

**Issue by MaDDmin** [dendronhq/dendron#1048]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Notes created with 'doctor' from '#' (tags), include punctuation chars that follow them in the name.

## To Reproduce

1. Create a note with some text like, for example: 
"I just love #Dendron."
2. Run "Dendron:Doctor" command with the 'createMissingLinkedNotes' option.

## Expected behavior
The note I would expect to be created would be 'tags.Dendron' . Instead, it creates 'tags.Dendron."' .
Please note the dot and the double quote characters.

**Comment by SeriousBug** [comment]
Thanks for the report, I'll create a fix for this. As a workaround for now, please feel free to use a wikilink like `[[#Dendron|tags.Dendron]]`.

**Comment by SeriousBug** [comment]
This has now been fixed in version 0.53. Please let us know if there are any further issues.
