### ISSUE TITLE
cli vault creation is added to dendron.yml but not dendron.code-workspace

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#1070]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Creating a vault via CLI is added to `dendron.yml` but not `dendron.code-workspace`. This means that the vault won't show up in the VSCode workspace/editor unless added properly.

This looks like some changes would need to happen potentially in:

- [packages/dendron-cli/src/commands/vaultCLICommand.ts](https://github.com/dendronhq/dendron/blob/master/packages/dendron-cli/src/commands/vaultCLICommand.ts)
- [packages/engine-server/src/workspace/service.ts: async createVault](https://github.com/dendronhq/dendron/blob/8afa5bf07853d98f3c9939e3b8490c45cf2a5e1a/packages/engine-server/src/workspace/service.ts#L241)
- [packages/engine-server/src/workspace/service.ts: async addVault](https://github.com/dendronhq/dendron/blob/8afa5bf07853d98f3c9939e3b8490c45cf2a5e1a/packages/engine-server/src/workspace/service.ts#L193)

## To Reproduce

```bash
# Create vault via CLI
# npx dendron-cli vault --vault my-new-vault --vaultPath 'repos/my-new-vault'
dendron-cli vault --vault my-new-vault --vaultPath 'repos/my-new-vault'
```

The above command creates a vault, and adds it properly to `dendron.yml`, but does not add it to `dendron.code-workspace` as a listed vault. Opening the workspace in VSCode will now show the vault, unless manually adding it to `dendron.code-workspace`.

## Expected behavior

The new vault should be added also to the `dendron.code-workspace` file:

### Example before creating vault

```json
...
  "folders": [
      {
          "path": "repos/my-old-vault",
          "name": "my-old-vault"
      }
  ],
...
```

### Example after creating vault

```json
...
  "folders": [
      {
          "path": "repos/my-new-vault",
          "name": "my-new-vault"
      },
      {
          "path": "repos/my-old-vault",
          "name": "my-old-vault"
      }
  ],
...
```

## Desktop (please complete the following information)

- OS: Pop!_OS 21.04
- IDE: Codium `v1.56.0`
- Dendron VSCode extension version: `0.52.0`
- `dendron-cli` version: `0.52.1`

**Comment by hikchoi** [comment]
Thank you for the detailed bug report. We'll investigate and come up with a fix!

**Comment by kevinslin** [comment]
this should be fixed in v54 of Dendron. please post here if not, otherwise this issue will auto close in 3 days
