### ISSUE TITLE
`copy note ref` command ignores `noXVaultWikiLink` setting

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1072]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

The [copy note ref](https://wiki.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#copy-note-ref) command ignores the [noXVaultWikiLink](https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#noxvaultwikilink) setting and all refs contain `dendron://vault/` in a multi-vault workspace.

## To Reproduce

1. Trigger the `copy note ref` command
2. Examine the generated link--it will have `dendron://vault/` in it.

## Expected behavior

The `copy note ref` command should respect the `noXVaultWikiLink` settings, same to the `copy note link` command.

## Desktop (please complete the following information)

- OS: Windows 10
- Version 0.52

## Additional context

I'm not sure if the `copy note ref` ignores this setting by design or not. If be design, then this should be a feature request.

**Comment by SeriousBug** [comment]
Thanks for reporting this issue, I have a fix which should be available with the next version.

**Comment by kevinslin** [comment]
this should be fixed in v54 of Dendron. please post here if not, otherwise this issue will auto close in 3 days

**Comment by aleksey-rowan** [comment]
Works as expected now, thank you!
