### ISSUE TITLE
Dendron Paste Image: command is not aware of wayland CLI tools for interacting with clipboard

### ISSUE THREAD

**Issue by craSH** [dendronhq/dendron#1095]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

Using the *Paste Image* command from a Linux machine running Wayland instead of X11 fails due to the attempt to use the `xlip
` command, which is not utilized for Wayland compositing environments. `wl-copy` and `wl-paste` are the appropriate standard commands to perform similar actions in Wayland based environments. These are commonly contained in a package called `wl-clipboard` for many Linux distributions.

## To Reproduce

1. Use Dendron on a Linux machine using the Wayland display system, not X11/Xorg.
2. Open any note in the editor.
3. Copy an image to your Wayland clipboard, e.g. from a web browser.
4. In the Dendron editor for a note, use the `Paste Image` command
5. Observe the error from VS Code indicating that "You need to install xlip command first." from "Source: Dendron Paste Image (Extension)"

## Expected behavior

The `Paste Image` command should detect what type of display environment is in use, and attempt to use supported tools based on what environment is in use. I believe a suitable check for Wayland is the presence of a value in the environment variable `WAYLAND_DISPLAY`, though there may be a more appropriate check for this. 

## Screenshots

_Not applicable/useful._

## Desktop (please complete the following information)

- OS: Arch Linux, current (Linux 5.13.7-arch1-1)
- VS Code Version: vscodium-bin 1.58.2
- Version: dendron v0.53.0
- Version: dendron.dendron-paste-image v1.0.4

## Additional context

N/A

## Dendron Log file

_No relevant log entries found for this issue in the main dendron log file_

**Comment by craSH** [comment]
Relevant code in the Paste Image extension fork:
* https://github.com/dendronhq/dendron-paste-image/blob/ff46f339e15eae84d7995f332a1fafe5fefbd45f/src/extension.ts#L354
* https://github.com/dendronhq/dendron-paste-image/blob/ff46f339e15eae84d7995f332a1fafe5fefbd45f/res/linux.sh#L4

I think this should be a pretty easy fix/feature to just try more clipboard commands in linux.sh

**Comment by kevinslin** [comment]
Thanks for both the issue and the explanation of the fix. Added it to our community roadmap. This will show up as an upcoming [CROP](https://wiki.dendron.so/notes/tayowNP4tMvcqH7AraoQ4.html) issue
