### ISSUE TITLE
Extension doesn't start, Code Helper (Renderer) 99%+ cpu

### ISSUE THREAD

**Issue by christiand** [dendronhq/dendron#1107]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x ] Misc (Choose this if your not sure)

## Describe the bug

This process "Code Helper (Renderer)" has my CPU pegged at 99%+ when Dendron workspace is open in VSCode. 
I've upgraded VSCode and Dendron to the latest.
If I close the dendron workspace, and open my own coding project workspace - all is fine.

Extension doesn't seem to fully load, and hangs at the progress indicator (see screenshot).
Even if cancelling the extension load, that process still pegs one of my cores.
Dendron shortcuts don't work.

## To Reproduce

1. Open my Dendron workspace in VSCode
2. Do nothing (idle)

## Expected behavior

Extension starts.
One core not maxed out.

## Screenshots
Hangs here:
![image](https://user-images.githubusercontent.com/22415/128579709-8c7d9990-b666-4395-9d26-1312cff16dc3.png)

![image](https://user-images.githubusercontent.com/22415/128577187-04269eb2-c577-4bb1-8100-a179dead800e.png)

## Desktop (please complete the following information)

- OS: Mac OS 10.15.7 (19H1323)
- VSCode:
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (1 day ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0

- Dendron v0.53.0
- Dendron Markdown Preview v0.10.57
- Dendron Snippet Maker v0.1.6

## Dendron Log file

{"level":30,"time":1628291832488,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1628291832584,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logPath":"/Users/damichr/Library/Application Support/Code/logs/20210806T191708/exthost1/dendron.dendron","logLevel":"info","extensionPath":"/Users/damichr/.vscode/extensions/dendron.dendron-0.53.0","extensionUri":{"$mid":1,"fsPath":"/Users/damichr/.vscode/extensions/dendron.dendron-0.53.0","path":"/Users/damichr/.vscode/extensions/dendron.dendron-0.53.0","scheme":"file"},"storagePath":"/Users/damichr/Library/Application Support/Code/User/workspaceStorage/632949ce17db80bb0a0e12290810bb40/dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"/Users/damichr/Dendron/dendron.code-workspace","external":"file:///Users/damichr/Dendron/dendron.code-workspace","path":"/Users/damichr/Dendron/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"/Users/damichr/Dendron/vault","external":"file:///Users/damichr/Dendron/vault","path":"/Users/damichr/Dendron/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1628291832586,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1628291832675,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"SegmentClient","msg":"user telemetry setting: enabled by migration"}
{"level":30,"time":1628291832676,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1628291832676,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1628291832676,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1628291832678,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"_activate","config":{"site":{"noteRoot":"dendron","siteRoot":"docs"},"vaults":[{"fsPath":"vault"}],"version":0,"initializeRemoteVaults":true,"journal":{"dailyDomain":"daily","name":"journal","dateFormat":"y.MM.dd","addBehavior":"childOfDomain","firstDayOfWeek":1},"dendronVersion":"0.49.0"},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1628291832684,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"_activate","installStatus":"NO_CHANGE","currentVersion":"0.53.0","previousWorkspaceVersion":"0.53.0","previousGlobalVersion":"0.53.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.57","active":false}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1628291832686,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"execServer","state":"enter"}
{"level":30,"time":1628291832689,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1628291834455,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"execServer","state":"message","message":"50016"}
{"level":30,"time":1628291834455,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":26403}
{"level":30,"time":1628291834456,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"_activate","msg":"post-start-server","port":50016,"durationStartServer":1869}
{"level":30,"time":1628291834458,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"logger","ctx":"FileStorageV2","wsRoot":"/Users/damichr/Dendron","vaults":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1628291834459,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1628291834459,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1628291834488,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"connector","ctx":"EngineConnector:init","msg":"enter","opts":{}}
{"level":30,"time":1628291834488,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"connector","ctx":"EngineConnector:createServerWatcher","msg":"enter","opts":{}}
{"level":30,"time":1628291837491,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"connector","ctx":"EngineConnector:_connect","portCreated":1628291834459,"wsActivation":1628291832678}
{"level":30,"time":1628291837491,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"connector","ctx":"EngineConnector:_connect","msg":"initFromExistingFile","port":50016}
{"level":30,"time":1628291837491,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"connector","ctx":"EngineConnector:tryToConnect","port":50016,"msg":"enter"}
{"level":30,"time":1628291860653,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1628291860653,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1628291860672,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1628292204334,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1628292204334,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1628292204346,"pid":26243,"hostname":"3c22fb0e9ff2.ant.amazon.com","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}

**Comment by kevinslin** [comment]
hmm, there's a few things I can think of. 

First make sure that its an issue with dendron vs your particular workspace setup. see [launching a new workspace](https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#launch-a-new-workspace)

If you still see the issue, try the following
- check that localhost isn't blocked? see [docs](https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#whitelisting-localhost)
- check for large notes. [docs](https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#look-for-large-files)

**Comment by christiand** [comment]
I initialized a new workspace and copied all my notes over. That seems to have resolved my issue for now. 
Let me know if you want to look any deeper. 
Thanks Kevin!

**Comment by christiand** [comment]
Ah, it reproduces with new workspace when I open a particular size-able note.
That process spikes to 99% cpu and cmd-L no longer works.

File is 293K

**Comment by kevinslin** [comment]
got it. depending on the contents, some notes might take longer to process
then others. we have a backlog item to check for these “note bombs” which
we’ll implement later this month.

if the note is something you can share for a repro, that would be great,
otherwise - if you can keep the file with you until the end of the month,
 would be great if you could tell us if the fix worked!

**Comment by kevinslin** [comment]
this should be fixed in v56 of Dendron. please post here if not, otherwise this issue will auto close in 3 days
