### ISSUE TITLE
[RFC] Integrated Space Repetition

### ISSUE THREAD

**Issue by imalightbulb** [dendronhq/dendron#1109]
## Introduction
- **[Space Reptition](https://en.wikipedia.org/wiki/Spaced_repetition)** (SR) is a learning method that encourages one to separate knowledge into different types of cards and **memorize effectively through daily practise**. 

## Why? 
- Among the large mass of notes, there must be some you want to memorize over the long term. 
- It is not ideal to rely on external extensions for SR. 
- attract more users from the academia

### Phase I  
- From my observation (see the section below for additional info), the most ideal choice to implement space reptition features in dendron in my opnion is through an overall structure similar to [Recall](https://marketplace.visualstudio.com/items?itemName=frenya.vscode-recall):
  - cards by `::` 
  - cloze by `{{}}` 
  - open a new window for review 

### Phase II 
- Furthermore, the addition of **reviewing cards in published websites** using dendron opens more possibilities because **one can share his cards easily through the site**. 
- and despite basic front-back and cloze cards, features like [image occlusion](https://ankiweb.net/shared/info/1374772155) can be considered once the basic features are mature. 

### RemNote 
- seperate front and back side with `::`
- cloze by `{{}}`

### Logseq 
- workflowy-like bullets, parent and children block to separate front and back 
- cloze by `{{cloze }}` 

#### [Recall](https://marketplace.visualstudio.com/items?itemName=frenya.vscode-recall)
- cards by `::`
- cannot do cloze 
- card review in vsc 

#### [Anki for VSC](https://marketplace.visualstudio.com/items?itemName=jasew.anki)
- cards by `##` as front, word under the header as back 
- cloze by `{{c1::cloze}}` followed by the header 
- sync with anki

**Comment by namjul** [comment]
Other solutions to look into that I collected:
- https://notes.andymatuschak.org/z4mAF1uBV96r72e4NjLcDaujEyTPGiUQJEj8C?stackedNotes=z5ARNXtS5VxteskEW91S1yYTgAcLABNXsZuJE
- https://github.com/Pseudonium/Obsidian_to_Anki
- https://github.com/Pradhyo/anki-markdown-notes

**Comment by kevinslin** [comment]
Appreciate the RFC. 

Before we proceed, can you use the template [here](https://wiki.dendron.so/notes/eb60689e-66e2-490c-9f40-6c9c42a783a2.html) for creating the RFC? don't forget to include the frontmatter at the top of the note. Easiest way to do this is to add the site as a seed to your existing workspace. See instructions [here](https://wiki.dendron.so/notes/7XlJ3dRf_3z2GMP9_MC7q.html#adding-a-seed-to-an-existing-workspace)

**Comment by kevinslin** [comment]
Merged this into dendron-site. Further comments should go into [github discussion](https://github.com/dendronhq/dendron/discussions/1133)
