### ISSUE TITLE
Clicking on local file link does not open within Preview V2; does work in other previewers.

### ISSUE THREAD

**Issue by belesiu** [dendronhq/dendron#1124]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ X] Misc (Choose this if your not sure)

## Describe the bug

Clicking on markdown links to local files from Preview V2 do not open. ?  I know I can select the link and use Dendron: open link; I was just looking for something easier to use.

## To Reproduce

1. Place a PDF in a local file directory:  ../docs/assets/pdf/zim.pdf
2. Ctlr-Shift-P:  Dendron:  Show Preview V2
3. Attempt to open link from preview.
4. Note that it doesn't work.
5. Close preview window.

## Expected behavior

Clicking on link to PDF should open the PDF file in the default viewer.

## Desktop (please complete the following information)

- OS: [Win10]
- Browser [Chrome, Edge]

## Dendron Log file

N/A

**Comment by kevinslin** [comment]
Thanks for reporting the issue. Added it to our backlog!

**Comment by kevinslin** [comment]
this should have been fixed in v72
