### ISSUE TITLE
References: Support reference to an explicit single block

### ISSUE THREAD

**Issue by craSH** [dendronhq/dendron#1131]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

There is currently no way to use a [header reference](https://wiki.dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c.html#header-references) in a way that only includes the contents of a single header section. Either all content from that header onward can be included, or all content from that header onward to a specific next header.

## Describe the solution you'd like ##

It should be simple to include a specific section of a note, based on headers, in another note. Similar to `^` anchors, but for cases which they can not be utilized (e.g. code blocks within a section.)

## Describe alternatives you've considered ##

* Anchors (don't work in all situations such as code blocks)
* Dummy-anchors to trick the range operator
* Forcing blocks of such interest to be at the end of a target note (not good/generic UX)

## Additional context ##

* [Conversation in Discord](https://discord.com/channels/717965437182410783/735365126227493004/875176394248835082)

**Comment by kevinslin** [comment]
Thanks for the issue. This will most likely come up in an upcoming [CROP](https://wiki.dendron.so/notes/tayowNP4tMvcqH7AraoQ4.html) vote!

**Comment by kevinslin** [comment]
this should be fixed in v56 of Dendron. please post here if not, otherwise this issue will auto close in 3 days
