### ISSUE TITLE
No backlink from frontmatter tags

### ISSUE THREAD

**Issue by denisdifazio** [dendronhq/dendron#1143]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

A note doesn't create a backlink from a tag that is created on the frontmatter.
This doesn't happen if the tag is created via the `#` operator

## To Reproduce

1. Create a new note
2. Include `tags: test` inside frontmatter block
3. CTRL+Click the tag to go to the newly created tag note
4. Verify that there is no backlink connection to the previous note

## Expected behavior

The tag note should create a backlink to the previous tagged note.

If I redo the previous steps and replace the second step with an outside-frontmatter tag (i.e #test) the new note will have a backlink

## Desktop (please complete the following information)

- OS: Windows 10
- Dendron: v0.54.0

**Comment by kevinslin** [comment]
Your right, thanks for the report. Will add this to our backlog!

**Comment by SeriousBug** [comment]
This issue should be fixed in Dendron v57. Please let us know if you are still having problems, otherwise this issue will close in a few days.

**Comment by denisdifazio** [comment]
I've tested it now and it's working perfectly. Thank you guys!
