### ISSUE TITLE
Sitemap generation for published site

### ISSUE THREAD

**Issue by LukeCarrier** [dendronhq/dendron#1144]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

My publicly published notes can take a while to show up in search engines, as they have to crawl the entire site in order to find the newly published and changed content.

## Describe the solution you'd like ##

A sitemap would give search engines a reference point for new and changed content, likely reducing indexing time.

## Describe alternatives you've considered ##

I could generate a sitemap externally (e.g. via Netlify plugins), but I'm not sure I could accurately convey the modification times. Given that Dendron keeps track of these in the frontmatter I think it makes sense for Dendron to generate the sitemap.

**Comment by kevinslin** [comment]
Thanks for the issue. You're right, sitemap is something that Dendron can and should generate. We're currently working on Dendron's [nextjs publishing](https://wiki.dendron.so/notes/nB75cmdPhL7CTOATG6wpT.html) which we aim to release by end of the month. For now, I would recommend generating this using a script. 

If you run the [Nextjs Pod](https://wiki.dendron.so/notes/5fGMHyXmErIV9odz01BBH.html#summary), it will create a file called `notes.json`. This contains the ids of every note that will be published. Your sitemap should be `{siteUrl}/notes/{id}.html`.

I'm also adding this issue to our community roadmap which means it will show up as an upcoming [CROP](https://wiki.dendron.so/notes/tayowNP4tMvcqH7AraoQ4.html).

**Comment by kevinslin** [comment]
heads up that this was shipped in v71. see https://wiki.dendron.so/notes/yQVhJtdQ40n3SLHJKAeeU.html#options
