### ISSUE TITLE
Faulty CSS Classes Disabling Reference Links

### ISSUE THREAD

**Issue by r-neal-kelly** [dendronhq/dendron#1148]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [X ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The "height" style in CSS classes ".portal-parent-fader-top" and ".portal-parent-fader-bottom" inhibit user from clicking on top and bottom links of a reference.

## To Reproduce

1. create a note with 4 items in a list, each linking to another note.
2. create a note to reference the note from step 1.
3. when viewing the reference in the note from step 2, in both the preview in VS Code and in a published site, you cannot click on the first or the last link in the list

## Expected behavior

I'm new to Dendron and I honestly thought that links inside of references were intentionally being disabled until I looked at the html. Clearly, the user should be able to click any links in a referenced note and these classes need to be fixed or the two seemingly useless divs removed from the HTML.

I'm currently just commenting out the "height: 36px" in both CSS classes in "/assests/css/just-the-docs-default.css" whenever I publish the site.

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: Brave
- Version: Version 1.27.111

**Comment by kevinslin** [comment]
Thanks for pointing this out. We'll address this in our upcoming sprint!
