### ISSUE TITLE
Exclude tags from included reference

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#1149]
## Please Select if your Request is Either something new or an Enhancement ##

- [+] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

When using an atomic approach to notes a lot of notes get included in other notes, which in case get included again. Each time (when using frontmatter tags) even if only one section is referenced, a section with tags is included into the reference widget. This leads to long and cluttered notes higher up in the hierarchy. 

## Describe the solution you'd like ##

I'd like to have an option to exclude tags in the reference view.

**Comment by SeriousBug** [comment]
Thanks for the feedback. I'll try to add an option for this within this month.

**Comment by SeriousBug** [comment]
Hi, this issue should be fixed in version 0.56. The "Tags" section should not appear for references.

Please let us know if you are still experiencing it, otherwise this issue will automatically close in a few days.
