### ISSUE TITLE
Consolidate configurations into separate namespaces

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#1154]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [x] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##
- With the recent feature additions, a lot of new configurations in `dendron.yml` has been added.
- New configurations have been given their own namespaces (e.g. `config.journal`, `config.scratch`, and so on), but there are some old configurations that are at the top level of yaml.
- This can cause confusion to users.

## Describe the solution you'd like ##
- Consolidate old configurations to their respective namespaces.

## Additional context ##
- Ideally this should be done so that each plugin command has their own config namespace, and only expose configs that span across multiple commands or configs that are general to be on the top level namespace.
- A guideline / SOP for adding new configs should be added for future reference.
- Migration should be done for users who are still using old configs once the change has been made.

**Comment by kevinslin** [comment]
this has been done
