### ISSUE TITLE
Title hint when creating scratch note 

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#117]
When creating a scratch note, it would be nice to have a hint in the note name that relates to the title. 

## Currently

Creating a scratch note with the title of foo

- scratch.2020.08.23.071502.md
```md
---
title: foo
---

```

Creating scratch note with title hint

- scratch.2020.08.23.foo.md
```md
---
title: foo
---

```

## Questions

1. This works for short titles but is problematic with long titles (eg. `foo bar this is a really long title`). Uncertain what the proper behavior is

**Comment by kpathakota** [comment]
I think you still need a uniqueness breadcrumb and you can always truncate longer titles. So creating a scratch note with  title hint should (I think) look like: 

* scratch.2020.08.23.nnnn-foo

Longer titles "foo bar is a good bar"
* scratch.2020.08.23.nnnn-foo-bar (assuming we decide to truncate the titles to 12 chars).

**Comment by kevinslin** [comment]
this was shipped in 0.13.4 :)
