### ISSUE TITLE
The calendar panel expands automatically when the last editor is closed

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1185]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

If you have Dendron's new Calendar view panel added to the VSCode's UI and it's currently collapsed, it will auto-expand if all open editors are closed.

## To Reproduce

1. Collapse the Calendar panel
2. Open any note (if you don't have anything open)
3. Close that note (or close all notes with (`Ctrl + K W`)
4. The Calendar panel should auto-expand

## Expected behavior

The Calendar panel should not auto-expand at all. 

## Desktop (please complete the following information)

- Version 0.55.1

**Comment by kevinslin** [comment]
You're right, this is an issue on our side. Will take this on next sprint!

**Comment by nickolay-kondratyev** [comment]
https://github.com/dendronhq/dendron/pull/1299

**Comment by aleksey-rowan** [comment]
Fixed now. Thank you!
