### ISSUE TITLE
When initializing an empty remote vault, Dendron should create a .gitignore file with, at least, a .dendron.cache.json entry

### ISSUE THREAD

**Issue by djradon** [dendronhq/dendron#1186]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [x] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Every time I start a new vault, I have to manually create a .gitignore file with a line for .dendron.cache.json

## Describe the solution you'd like ##

A .gitignore file should be created automatically if it doesn't exist yet. Then an entry should be added for .dendron.cache.json

## Describe alternatives you've considered ##

none

**Comment by kevinslin** [comment]
Thanks for the issue. We'll make sure to get this in for next week's sprint (unless a community member picks it up before hand). 

for any interested bystanders, this is the relevant part of the code  -> https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/commands/VaultAddCommand.ts#L208:L208

dendron development docs here -> https://wiki.dendron.so/notes/81da87be-2d4e-47b5-a1d6-c0d647e1ab00.html

**Comment by maxtrem271991** [comment]
Clôture

**Comment by kevinslin** [comment]
this should be fixed in v0.57 of Dendron. please post here if not, otherwise this issue will auto close in 4 days

**Comment by maxtrem271991** [comment]
robot
