### ISSUE TITLE
lebel

### ISSUE THREAD

**Issue by Maxblinder** [dendronhq/dendron#1187]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
If you have a specific issue, please submit a ticket. Closing this
