### ISSUE TITLE
Support PDF Export in Preview V2

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#1204]

**Comment by viztor** [comment]
The easiest way is obviously to use a headless chrome.
I would prefer export to LaTeX, and then compile it to PDF, it would look so much better.

**Comment by simkimsia** [comment]
i like the way markdown-preview-enhanced (MD-P-E) does it.

you right click on the preview and then choose how to export.

very happy just to have that. the v2 enhancement for this is to have commands specific to each export.

which even MD-P-E doesn't have.

Also good to have a settings way to set default export.

you know how u have a paste image and auto you sent to /assets folder? would be good to have somethign similar for `/exports` then .gitignore that folder.

**Comment by kevinslin** [comment]
closing in favor of https://github.com/dendronhq/dendron/issues/1204
