### ISSUE TITLE
tutorial.2-taking-notes.md says use cmd-tab on mac to get back to past note

### ISSUE THREAD

**Issue by bs** [dendronhq/dendron#1230]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Onboard. Initial vault setup and import/export pods 

## Describe the bug

- tutorial.2-taking-notes.md says use cmd-tab on mac to get back to previous part of the tutorial.
- cmd-tab in mac is the WM switcher.

Is this supposed to be ctrl-tab?

## Desktop (please complete the following information)

- OS: macOS
- Browser firefox

**Comment by hikchoi** [comment]
Thanks for the report. Yes that is right. it should be ctrl-tab. Good catch! We'll get this fixed ASAP 🙏🏼

**Comment by hikchoi** [comment]
pinging @jonathanyeung for onboarding issue.
