### ISSUE TITLE
New note stuck in with "stub: true"

### ISSUE THREAD

**Issue by HopperTech** [dendronhq/dendron#1231]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

I have noticed the effects of this error before, but it has been so random I just never took the time to dig into it before now. Today I was able to regularly reproduce the error on the specific note that was created.

I created a new note that is associated with a template and made edits to that note. Later in the day I tried calling up that again and noticed that it was replaced by the template, effectively losing all my previous edits. This occurred several times during that day. Thankfully I started using git after having lost data in the past.

While troubleshooting I noticed that the frontmatter had the 'stub: true' entry. Removing that solved the overwrite issue.  Though I do not know why that entry was stuck on my note to begin with. The template does not have this value, not sure how else to troubleshoot why these get created this way. 

## To Reproduce

I am not sure the steps to reproduce the initial issue of 'stub: true' being added to my note. It does not occur every time I create notes with this template, but I have experienced similar issues in the past, just didn't realize it was related to that 'stub: true' entry

## Expected behavior

To not lose edits to notes that I make

## Screenshots

![dendron-error](https://user-images.githubusercontent.com/35973180/131263610-69fad0e9-833a-475e-92d7-cbb84dbf4527.jpg)
![dendron-error-stub](https://user-images.githubusercontent.com/35973180/131263611-0bd098d2-7645-442b-893e-c30f51a9a3e7.jpg)

## Desktop (please complete the following information)

- OS: Windows
- Browser N/A
- Version 0.56.0

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here
[dendron.server.log](https://github.com/dendronhq/dendron/files/7073149/dendron.server.log)
[dendron.log](https://github.com/dendronhq/dendron/files/7073151/dendron.log)

**Comment by hikchoi** [comment]
Thank you for the report!
I can indeed reproduce this when creating a note with lookup that is already internally classified as a stub (usually happens with scratch and journal notes that have deep hierarchies but doesn't necessarily have actual note for every level).
We'll track this issue and let you know once it is fixed!

**Comment by HopperTech** [comment]
Thank you Mark,  that makes sense. Thinking about this issue, I did create
the lower level note first.

**Comment by SeriousBug** [comment]
This has been fixed (I'm not exactly sure when,  I think it's Dendron 0.93). Dendron will now avoid writing `stub: true` into notes. Please let us know if this problem keeps happening, otherwise this issue will close in a few days.
