### ISSUE TITLE
References to list items include sub-items when rendered in Preview v2

### ISSUE THREAD

**Issue by djradon** [dendronhq/dendron#1233]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When block-referencing IDs for transclusion of list items (ordered or unordered), the v2 preview shows the item and all "sub-items". Given that you could specify the sub-items using a range selector, but there's no obvious way to specify just a single list item, it seems to me like a single block reference should only include a single list item.

## To Reproduce

```
## testing with ordered list

1. first ^nPm286FpKzGj
   1. first-a  ^0NFOQ4Hi4frn
      1. first-a-1
1. second
   1.  second-a ^AKRCeAVwwIX2

![[:#^0NFOQ4Hi4frn]]
```

results in:

```
1. first-a
  a. first-a-1
```

## Expected behavior

```
1. first-a
```

## Desktop (please complete the following information)

- Windows, VSCode v0.56.0

**Comment by hikchoi** [comment]
Thank you for the report and detailed repro case. I can reproduce this.

We'll track this issue and let you know when it gets fixed.

**Comment by hikchoi** [comment]
pinging @SeriousBug for block reference issue.
will also look into preview rendering myself.

**Comment by SeriousBug** [comment]
This is an intentional feature, but it would be a good idea to support the use case of not including the child items. I'll work on coming up with a format to reference only a single block. Any feedback is welcome.

**Comment by SeriousBug** [comment]
I can't test this right now, but could you try `![[#^0NFOQ4Hi4frn:#^0NFOQ4Hi4frn]]` to see if that works in the meantime?

**Comment by djradon** [comment]
@SeriousBug -- using your suggested "range" reference has the same effect for me.

**Comment by SeriousBug** [comment]
Dendron 0.58 now adds support for referring to a single item without it's children using `![[#^0NFOQ4Hi4frn:#^0NFOQ4Hi4frn]]` (same anchor repeated). Please let us know if you have any additional concerns or issues, otherwise this issue will close in a few days automatically.
