### ISSUE TITLE
Dendron doesn't work at all, even new install / Initial Workspace etc

### ISSUE THREAD

**Issue by herop** [dendronhq/dendron#124]
**Describe the bug**
After an install of dendron 0.8.0 or previous versions each call of Dendron command result is <command.name> not found
![Dendron-Issue](https://user-images.githubusercontent.com/658323/91168632-3f714880-e6d6-11ea-8374-392fe7d60963.png)

**To Reproduce**
1. Open VSCode
2. do - something
3. (All necessary Dendron extensions are active)

**Expected behavior**
No errors? Dendron stuff working?

**Screenshots**
![Dendron-Extensions](https://user-images.githubusercontent.com/658323/91169134-12716580-e6d7-11ea-83d4-da79283d9234.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version 0.8.0
**Additional context**
I tried everything low of totally uninstall VSCode to fix this 

** Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/5123449/dendron.log)

**Comment by kevinslin** [comment]
this looks like the same issue another one of our users had. 

there was a bug with one of the earlier versions of dendron that would mis-set the path in an env variable that later dendron's would pick up on. it 

can you go into your vscode extensions folder `~/.vscode/extensions/` and delete all folders that start with `dendron*` , reinstall dendron and tell me if you still see the issue?

**Comment by kevinslin** [comment]
think we resolved this now. closing :)
