### ISSUE TITLE
Dendron should ignore lookupConfirmVaultOnCreate when dailyVault is set

### ISSUE THREAD

**Issue by djradon** [dendronhq/dendron#1256]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

If a user has set a default vault with `dailyVault` for Daily Journal Notes, they should be created there without prompt. But if `lookupConfirmVaultOnCreate` is true, then `dailyVault` is ignored and the user is prompted for a vault.

## To Reproduce

1. specify a default vault with `journal: dailyVault` in dendron.yml
2. ensure `lookupConfirmVaultOnCreate: true`
3. trigger "Dendron: Create Daily Journal Note"
4. vault prompt appears 

## Expected behavior

Note should be created in specified vault without a prompt

## Desktop (please complete the following information)

- Windows VSCode
- Dendron0.58.0

## Additional context

https://discord.com/channels/717965437182410783/735365126227493004/882141048019746847

**Comment by Harshita-mindfire** [comment]
This should be fixed in v59 of Dendron. Please post here if not, otherwise this issue will auto close in 4 days
