### ISSUE TITLE
Show graphs and charts in published notes

### ISSUE THREAD

**Issue by ric03uec** [dendronhq/dendron#126]
**Is your feature request related to a problem? Please describe.**
Currently, when a graph or chart is added using syntax mentioned [here](https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams?id=graphviz), they are parsed correctly by Markdown Preview Enhanced. Although, when the note is published using `build pod` command, the resulting webpage shows the original markdown text for graph instead of showing the graph.

**Describe the solution you'd like**
The published note(s) should show parsed graphs correctly

**Describe alternatives you've considered**
n/a

**Comment by aleksey-rowan** [comment]
Hi, @ric03uec, Dendron has switched away from MPE and now uses [its own preview mode](https://wiki.dendron.so/notes/Tf4vuVLV3rSdpzD8la9FP/#preview-v2-enhancements). Could you please check if this issue still exists? Thanks!
