### ISSUE TITLE
Buildsite with dendron-cli broken

### ISSUE THREAD

**Issue by another-techie** [dendronhq/dendron#1262]
When I try to use this command: `npx dendron buildSite  --stage dev --serve` I'm unable to build the site and receive an error. I followed all instructions on this [site ](https://wiki.dendron.so/notes/1399b5d2-28fb-4077-aa5f-c8edbe52bc5d.html) and so far it hasn't worked. Based on the attached stdout and stderr log it seems like it might be related to the eleventy-plugin-seo tags. My goal is to create a script which will pull my latest Dendron notes, build them (using the prod version of the above command), and push the files to a web server. My OS is Ubuntu based.
[log.txt](https://github.com/dendronhq/dendron/files/7088747/log.txt)

Side note, Dendron is a great idea. Thanks for taking the time to develop it.

**Comment by jonathanyeung** [comment]
Hi @another-techie, thanks for trying publishing out and reporting this issue. 

One common problem is to make sure that you're running the cli commands from the workspace root.  The workspace root is the same directory where `dendron.yml` and `dendron.code-workspace` reside.  Is that the case when you were running the command? 

We realize publishing is a bit too difficult right now - we're in the process of trying to streamline the process and make it less error prone.  Thanks for the patience!

**Comment by another-techie** [comment]
Hi @jonathanyeung. 
I was running the commands in the workspace root. After troubleshooting this morning, I was able to fix the problem by upgrading to node 16 from version 12.22.6. I'm now able to run the commands and build my site. I haven't tested it, but it's possible this could be fixed by upgrading to node 13, 14, or 15 too.

Thanks for your quick response!
