### ISSUE TITLE
Allowing for Multiple Parents 

### ISSUE THREAD

**Issue by nixsee** [dendronhq/dendron#127]
Forgive me if this is already possible, but one main thing holding me back from even trying Dendron is that it seems to limit your notes to a strict folder-like hierarchy. I agree that a hierarchy-less system, such as with using only tags or standard links, is limiting, but a strict hierarchy is equally limiting. What we need is to allow for a file to be in _multiple_ hierarchies at the same time.  

I realize that this probably goes against the core function/philosophy of Dendron, but I'd rather have zero defined parents than only one, in which case I'm likely to use another tool where I'm not fighting the design.

I suspect this functionality will never happen, but I really like a lot of what Dendron has so I'm wondering if there is a workaround - is it possible to use Dendron without the "."-delimited hierarchies (everything in one folder/vault) but the front matter allows for multiple parents to be listed, which can be used in your neat graph modes and some other features?

**Comment by kpathakota** [comment]
While you can't have multiple parents (Dendron's a tad opinionated that way) you CAN use backlinks to the "multiple parents to be listed". See this for more details on backlinks: https://youtu.be/vrhBNGMJQwE?t=398. 

I myself have a many pages that are under the "projects" directory but also map to an area so use this feature extensively.

**Comment by kevinslin** [comment]
just to elaborate on this a bit more, while we don't plan on supporting multiple parents, we are considering adding support for note aliases which will allow you to take the same note and have it aliased under multiple hierarchies. would this be good for your use case?

https://github.com/dendronhq/dendron/issues/128

**Comment by nixsee** [comment]
I don't think aliases will work for me, its an entirely different thing. What I'm talking about would be a fundamentally different framework - a network diagram rather than a hierarchical one. If interested, you can check out [The Brain](http://thebrain.com/) to see the best implementation of this way of organizing and thinking.

**Comment by djradon** [comment]
A little late to the game on this one, but in case it helps @nixsee or anyone else out there...
* Dendron does not enforce a "strict hierarchy". It supports hierarchy, and very flexibly in my opinion, but you can just as easily keep all your notes "at the top level", i.e. no hierarchy at all
* between links+backlinks (as @kpathakota mentions) and tagging (now natively supported), Dendron does support multiple hierarchies pretty well. The hopefully-forthcoming aliasing that @kevinslin mentioned could help too.
