### ISSUE TITLE
[Bug/Feature] HTML-images

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#1273]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When including screeenshots in my notes they usually are pretty large images pixel wise. This leads to the following situation: 
The inserted image gets blown up by a huge factor compared to text depending on the window size. Especially for smaller sections I previously used HTML sections to limit the image width to make it somewhat similar to the text like that: 

```html
<img src="/assets/images/2021-07-04-14-35-50.png" alt="" width="450" />
```
With the new preview module HTML images are not rendered anymore. 

Is there a plan to include this in the future? Are there tools to convert the HTML-images to markdown images (and limit their size)?

**Comment by jonathanyeung** [comment]
Thanks @funnym0nk3y - seems like a good one for us to pickup as it's likely a common scenario for users.

**Comment by SeriousBug** [comment]
Dendron 0.59 now has a feature called "Extended Images" that makes this possible, please see this page for usage: https://wiki.dendron.so/notes/a91fd8da-6895-49fe-8164-a17acd8d9a17.html#extended-images

In this case, you could do `![](/assets/images/2021-07-04-14-35-50.png){width: 450px}` to set the width of the image.

Let us know if you're having any problems with this feature, otherwise this issue will automatically close in a few days.

**Comment by funnym0nk3y** [comment]
I really like that feature, especially the relative scaling! Is there an option to translate all HTML image to the new format?

**Comment by SeriousBug** [comment]
Unfortunately not. Please feel free to send in a feature request for it though!

**Comment by funnym0nk3y** [comment]
One thing I forgot to mention: Thanks! 

So a normal feature request to this repo? Or a pull request?

**Comment by SeriousBug** [comment]
Yes I meant a feature request issue: https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=feature_request.md&title=

I'm not sure what you mean by "cursor positions". Can you explain that a bit more?

**Comment by kevinslin** [comment]
closing this ticket since feature has been shipped
