### ISSUE TITLE
Error initializing dendron

### ISSUE THREAD

**Issue by ric03uec** [dendronhq/dendron#1281]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

After upgrading (and reloading window), ui throws an error `issue Initializing Dendron`

## To Reproduce

1. Run "Reload Window" command

## Expected behavior

Dendron should initialize successfully

## Screenshots

![image](https://user-images.githubusercontent.com/1110988/132050851-febb51f3-628b-4f37-8f71-b0e5734748c6.png)

## Desktop (please complete the following information)

- OS: [e.g. Xubuntu]

## Dendron Log file

```
"name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":1409}
{"level":50,"time":1630693431026,"pid":153919,"hostname":"crossbow","name":"dendron","line":97,"column":4,"stack":"SyntaxError: Unexpected token {\n    at F (/home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:280:120415)\n    at z (/home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:280:120782)\n    at /home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:280:121553\n    at X (/home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:280:121662)\n    at Object.parse (/home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:280:121884)\n    at Object.t.readJSONWithCommentsSync (/home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:106:96574)\n    at Function.checkAndMigrateLookupKeybindingIfExists (/home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:9:127272)\n    at R (/home/devashish/.vscode/extensions/dendron.dendron-0.57.0/dist/extension.js:520:216068)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","type":"Error","msg":"Unexpected token {"}
{"level":50,"time":1630693431027,"pid":153919,"hostname":"crossbow","name":"dendron","ctx":"showInitProgress","msg":"issue initializing Dendron"
```

**Comment by hikchoi** [comment]
Thanks for reporting this issue. 
Could you check if your `keybindings.json` is valid? The error message suggests that it hit an unexpected token while reading your keybinding setup.

I apologize for the cryptic error message. I'll make sure this error gets some proper handling interally.

**Comment by ric03uec** [comment]
thanks @hikchoi . it was an error in keybindings after all!
