### ISSUE TITLE
Dendron stuck in "starting up"

### ISSUE THREAD

**Issue by denisdifazio** [dendronhq/dendron#129]
**Describe the bug**
After the last update, every time I open VSCode, Dendron gets stuck in "Dendron is starting up: Loading index..."

**To Reproduce**
1. Open VSCode
2. Enter a workspace other than Dendron's

**Expected behavior**
No stuck in starting up

**Screenshots**
![image](https://user-images.githubusercontent.com/11673757/91439828-09ea6d80-e844-11ea-8d98-a0599fd04db1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Dendron version: 0.8.9

**Comment by kevinslin** [comment]
are you able to run 'open logs'? if so, can you send me the output of that?

**Comment by kevinslin** [comment]
actually, nvm, the issue is when you open up dendron outside of a non-dendron workspace, you'll see the prompt come up erroneously. will fix that later today!

**Comment by denisdifazio** [comment]
exactly, thank you Kevin!

**Comment by kevinslin** [comment]
the issue has been fixed in the latest release (v0.8.10). please confirm when you get a chance :)

**Comment by denisdifazio** [comment]
all good 👍
