### ISSUE TITLE
V2 Tree View Improvements

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1305]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I'm a bit frustrated with the V2 Tree View and how its behaviour is different from the standard VSCode tree, but I understand that this replacement is necessary to overcome VSCode's limitations when working with the tree viewer. 

## Describe the solution you'd like ##

- allow to expand more than a single tree branch at a time (right now it just works as an accordion)
- allow to disable the tree animation on branch expand/collapse (the transition delay is annoying, to me at least),
- allow to toggle off wrapping of note titles (and truncate them with `...` as it's done in the V1 tree),
- allow to display file names in the tree view instead of note titles (as in V1 tree)

## Describe alternatives you've considered ##

I keep using V1 Tree View.

**Comment by kevinslin** [comment]
Thanks for the issue. I think you have a fair point with all issues mentioned. Don't have an immediate ETA on this right now - this will probably come up as a CROP. In the meanwhile, the V1 tree view will be available for as long as these issues are still present

**Comment by aleksey-rowan** [comment]
V2 tree is being discontinued and the only valid item on my wish list of improvement now is an option to display either file names or note tiles, but since it's not covered by https://github.com/dendronhq/dendron/issues/2739, I'm going to close this.
