### ISSUE TITLE
'Extension host terminated unexpectedly' - Argdown

### ISSUE THREAD

**Issue by kzilla-git** [dendronhq/dendron#1312]
## Please select the area your Bug applys to. (Multiple selections are Possible)
- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug
Getting 'Extension host terminated unexpectedly' error upon starting Dendron in VSCode no matter how many times I reloaded/restarted and rebooted my computer. 

## To Reproduce
1. Have the Argdown extension already installed.
2. Open Dendron in VSCode and either open the Calendar or the Dendron Preview V2.

## Expected behavior
'Extension host terminated unexpectedly' error appears.

## Desktop (please complete the following information)
- OS: MS Windows 10
- Browser: Chrome

## Additional context
After uninstalling Argdown extension, the problem was resolved.

**Comment by kevinslin** [comment]
Thanks for the issue. We'll be investigating this separately when we have some more bandwidth 😅

**Comment by lnicola** [comment]
I'm also seeing this. It appears to run out of memory:

![image](https://user-images.githubusercontent.com/308347/144711119-040c0ac3-21a0-4fa2-b16c-02cee0e0db7a.png)

Note that it's happening outside of Dendron workspaces (CC #1540).

**Comment by lnicola** [comment]
This might have gotten worse recently, but disabling `dendron.watchForNativeWorkspace` seems to fix it for me.

**Comment by SeriousBug** [comment]
Dendron 0.74 disables `dendron.watchForNativeWorkspace` by default now, and this crash should not occur anymore. If it continues to happen, please let us know. Otherwise this issue will close automatically in a few days.

**Comment by lnicola** [comment]
Shouldn't this be kept open for tracking, since people might still enable that preference?
