### ISSUE TITLE
In-line hashtags should render the same as frontmatter hashtags when previewing.

### ISSUE THREAD

**Issue by belesiu** [dendronhq/dendron#1316]
## Please Select if your Request is Either something new or an Enhancement ##

- [x ] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I've tried using #tags in both the frontmatter area and inline hastags and I get different rendering from the V2 preview.  Tags from the frontmatter don't show up with the hashtag # prefix when previewed whereas inline hashtags do.

## Describe the solution you'd like ##

Hashtags from the frontmatter should include the # hashtag prefix.

See example image here:

![](https://media.discordapp.net/attachments/735365126227493004/884898965970100284/unknown.png)

## Describe alternatives you've considered ##

Since inline hashtags get color coded, you could auto-magically remove the hashtage # so that it looks the same as frontmatter hashtags.

## Additional context ##

N/A.

**Comment by SeriousBug** [comment]
Hi! In Dendron 0.61, we now have an option to add `#` symbols for the frontmatter tags. Please see this configuration: https://wiki.dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#usehashesforfmtags

By adding `useHashesForFMTags: true` under `site` in your `dendron.yml`, you can add the symbol in Preview V2 and in published sites.
