### ISSUE TITLE
Frontmatter Variable Substitution doesn't work in V2 Preview/Publishing

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1322]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

[Frontmatter variable substitution](https://wiki.dendron.so/notes/ba97866b-889f-4ac6-86e7-bb2d97f6e376.html#frontmatter-variable-substitution) doesn't work in V2 preview; it seems it hasn't been carried over from V1.

## To Reproduce

1. Add a new variable to the frontmatter (`mood: ambivalent`)
2. Use the variable in the note (`{{fm.mood}}`)
3. Open V2 preview
4. Observe that the variable value is not interpolated into the text and the note simply shows `{{fm.mood}}`

## Expected behavior

Frontmatter variable substitution should work in V2 the same it does in V1.

## Desktop (please complete the following information)

- Version 0.58.1

**Comment by hikchoi** [comment]
As of v68 we have removed the Nunjucks dependency and frontmatter variable substitution will work out of the box.

We've also added `created`, `updated`, and `id` to the exposed frontmatter object.

**Comment by aleksey-rowan** [comment]
Seems to work without Nunjucks. Thank you! 👍 Does it mean that the `useNunjucks` option is deprecated?

Also, any reason for leaving `{{ fm.desc }}` out?

**Comment by hikchoi** [comment]
`useNunjucks` is not yet removed from the configuration but has no effect now.
No particular reason `desc` was left out. I just missed it 😅  I'll add that in real quick.
