### ISSUE TITLE
Add borders to table cells in Preview V2

### ISSUE THREAD

**Issue by JohnStefanko** [dendronhq/dendron#1326]
## Please Select if your Request is Either something new or an Enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

It is difficult to read data in tables in Preview V2.

## Describe the solution you'd like ##

Add cell borders to tables in Preview V2.

## Additional context ##

The type of or use of cell borders could be made configurable.

**Comment by kevinslin** [comment]
Thanks for the issue. Will have this slotted up for our upcoming [crop issue](https://wiki.dendron.so/notes/tayowNP4tMvcqH7AraoQ4.html)
