### ISSUE TITLE
Unable to lookup notes using CTRL+L while Vim Emulation extension is installed.

### ISSUE THREAD

**Issue by psiryan** [dendronhq/dendron#1343]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X ] Misc (Choose this if your not sure)

## Describe the bug

Having Dendron installed beside the Vim Emulation extension prevents the ability to use the Dendron default keybinding for note lookup: Ctrl+l. The keybinding is not functioning regardless of the input mode (tried Normal and Insert modes)

## To Reproduce

1. Install Dendron extension
2. Install Vim Emulation extension
3. Open Dendron Workspace
4. Try note lookup using `Ctrl+l` keybinding
    Test in different Vim modes: `Normal` is default; press `i` for `Insert` mode
5. Check keybindings.json file for override block
>  {
      key: `ctrl+l`,
      command: "-expandLineSelection",
      when: "textInputFocus",
    }
6. If block isn't present, add it.
7. repeat step 4

## Expected behavior

The expectation is that in at least Insert mode a user would be able to use the Dendron keybinding for looking up a note.

## Screenshots

N/A

## Desktop (please complete the following information)

- OS: [Linux]
- Browser [Chromium, Chrome, Firefox]
- Version [v0.59.0]

## Additional context

An [post](https://discord.com/channels/717965437182410783/735365126227493004/886911807913082880) in the Questions channel of the Dendron Official Discord suggested that a keybinding override would fix the issue, however the one which was provided didn't seem to work.

Apparently the keybinding might automatically be inserted into the Keybindings.json file if certain installation conditions are met (install Dendron before Vim Extension perhaps?). Otherwise the keybinding would need to be applied manually. This is significant only for checking for the availability of the keybinding in the aforementioned json file.

## Dendron Log file

{"level":30,"time":1631721998897,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1631721999028,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/home/archfae/.config/Code/logs/20210914T120022/exthost1/dendron.dendron","extensionPath":"/home/archfae/.vscode/extensions/dendron.dendron-0.58.3","extensionUri":"/home/archfae/.vscode/extensions/dendron.dendron-0.58.3","workspaceFile":"/home/archfae/Documents/notes/dendron.code-workspace","workspaceFolders":["/home/archfae/Documents/notes/programming","/home/archfae/Documents/notes/seeds","/home/archfae/Documents/notes"]}
{"level":30,"time":1631721999031,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1631721999031,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.58.3","previousWorkspaceVersion":"0.58.3","previousGlobalVersion":"0.58.3","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1631721999170,"pid":103827,"hostname":"Lilith","name":"SegmentClient","msg":"user telemetry setting: enabled by migration"}
{"level":30,"time":1631721999170,"pid":103827,"hostname":"Lilith","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1631721999170,"pid":103827,"hostname":"Lilith","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1631721999170,"pid":103827,"hostname":"Lilith","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1631721999176,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"_activate","config":{"version":1,"maxPreviewsCached":10,"vaults":[{"fsPath":"programming","name":"Programming"},{"fsPath":"seeds","name":"Seeds"},{"fsPath":""}],"useFMTitle":true,"useNoteTitleForLink":true,"noAutoCreateOnDefinition":true,"noLegacyNoteRef":true,"noXVaultWikiLink":true,"lookupConfirmVaultOnCreate":false,"mermaid":true,"useKatex":true,"autoFoldFrontmatter":true,"usePrettyRefs":true,"dev":{"enablePreviewV2":true},"lookup":{"note":{"selectionType":"selectionExtract"}},"journal":{"dailyDomain":"daily","name":"journal","dateFormat":"y.MM.dd","addBehavior":"childOfDomain","firstDayOfWeek":1},"scratch":{"name":"scratch","dateFormat":"y.MM.dd.HHmmss","addBehavior":"asOwnDomain"},"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","usePrettyRefs":true,"title":"Dendron","description":"Personal knowledge space","duplicateNoteBehavior":{"action":"useVault","payload":["Seeds","","Programming"]}},"initializeRemoteVaults":true,"seeds":{"dendron.templates":{}}},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1631721999179,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"_activate","installStatus":"NO_CHANGE","currentVersion":"0.58.3","previousWorkspaceVersion":"0.58.3","previousGlobalVersion":"0.58.3","platform":"linux","extensions":[{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"redhat.vscode-yaml","version":"0.22.0","active":true}],"vaults":[{"fsPath":"programming","name":"Programming"},{"fsPath":"seeds","name":"Seeds"},{"fsPath":""}]}
{"level":30,"time":1631721999183,"pid":103827,"hostname":"Lilith","name":"execServer","state":"enter"}
{"level":30,"time":1631721999256,"pid":103827,"hostname":"Lilith","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1631721999953,"pid":103827,"hostname":"Lilith","name":"execServer","state":"message","message":"35541"}
{"level":30,"time":1631721999953,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":103982}
{"level":30,"time":1631721999953,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"_activate","msg":"post-start-server","port":35541,"durationStartServer":921}
{"level":30,"time":1631721999959,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1631721999960,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1631722000278,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"concepts","root":{"fsPath":"programming","name":"Programming"},"imports":["notes"]}
{"level":30,"time":1631722000287,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"lang","root":{"fsPath":"programming","name":"Programming"}}
{"level":30,"time":1631722000287,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"notes","root":{"fsPath":"programming","name":"Programming"},"imports":[]}
{"level":30,"time":1631722000287,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"patterns","root":{"fsPath":"programming","name":"Programming"},"imports":[]}
{"level":30,"time":1631722000288,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"root","root":{"fsPath":"programming","name":"Programming"},"imports":[]}
{"level":30,"time":1631722000289,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"root","root":{"fsPath":"seeds","name":"Seeds"},"imports":[]}
{"level":30,"time":1631722000290,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"concepts","root":{"fsPath":""},"imports":["notes"]}
{"level":30,"time":1631722000290,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"notes","root":{"fsPath":""},"imports":[]}
{"level":30,"time":1631722000291,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"root","root":{"fsPath":""},"imports":["notes"]}
{"level":30,"time":1631722000320,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"notes","root":{"fsPath":"/home/archfae/Documents/notes"},"imports":[]}
{"level":30,"time":1631722000321,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"notes","root":{"fsPath":"/home/archfae/Documents/notes/programming"},"imports":[]}
{"level":30,"time":1631722000322,"pid":103982,"hostname":"Lilith","name":"logger","ctx":"parseSchemaModuleOpts","fname":"notes","root":{"fsPath":"/home/archfae/Documents/notes"},"imports":[]}
{"level":30,"time":1631722000463,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":447}
{"level":30,"time":1631722000463,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1631722000463,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1631722000466,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1631722000467,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1631722000467,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1631722000467,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1631722000468,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1631722000471,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1631722000473,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1631722000476,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1631722000479,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1631722000479,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":1442}
{"level":30,"time":1631722000479,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.58.3","previousExtensionVersion":"0.58.3"}
{"level":30,"time":1631722270137,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/archfae/Documents/notes/programming/notes.schema.yml"]}
{"level":30,"time":1631722270139,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1631722270175,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/archfae/Documents/notes/programming/notes.schema.yml","/keybindings.json"]}
{"level":30,"time":1631722270177,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/keybindings.json"}
{"level":30,"time":1631722270189,"pid":103827,"hostname":"Lilith","name":"dendron","msg":"First open of note","fname":"keybindings.json"}
{"level":30,"time":1631727710350,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1631727710350,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1631727710373,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1631727710454,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/archfae/Documents/notes/programming/notes.schema.yml"]}
{"level":30,"time":1631727710454,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1631727710459,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/archfae/Documents/notes/programming/notes.schema.yml","/home/archfae/.config/Code/logs/20210914T120022/exthost1/dendron.dendron/dendron.log"]}
{"level":30,"time":1631727710459,"pid":103827,"hostname":"Lilith","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/home/archfae/.config/Code/logs/20210914T120022/exthost1/dendron.dendron/dendron.log"}
{"level":30,"time":1631727710470,"pid":103827,"hostname":"Lilith","name":"dendron","msg":"First open of note","fname":"dendron.log"}

**Comment by psiryan** [comment]
After playing around with the keybindings, I landed on this as a potential fix:
```json
{
    "key": "ctrl+l",
    "command": "dendron.lookupNote",
    "when": "dendron:pluginActive && editorTextFocus && vim.active" 
}
```

This allowed me to use the Dendron lookup note binding in any mode while using Vim Emulation.

**Comment by kevinslin** [comment]
Thanks for the report. We're looking into this and should have a fix in an upcoming release

**Comment by kevinslin** [comment]
We fixed this in v61. thanks again for reporting this issue!

**Comment by emarthinsen** [comment]
I'm on Dendron v63 and this appears to still be an issue. I'm able to launch the lookup dialog from within a note in either edit or normal mode. If I focus the explorer, then it works fine. I'm using VSCode 1.60.1.
