### ISSUE TITLE
Option to disable colored squares next to tags in editor and Dendron Preview 

### ISSUE THREAD

**Issue by lenamio** [dendronhq/dendron#1351]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I use emodjis for tags and with squares it looks too "busy" for me... (See example on screenshot below)

## Describe the solution you'd like ##

An option that makes colored squares for tags not appear in editor and Dendron Preview 

## Describe alternatives you've considered ##

I wouldn't mind an ability to style tags appearence myself with css. But I couldn't find this feature either (except a "hackish" way of editing Dendron's extention source and even then it only affected the preview)

## Additional context ##

![image](https://user-images.githubusercontent.com/20296489/133865967-611a6fb0-a20b-4eeb-bff0-bd04bf881e25.png)

**Comment by SeriousBug** [comment]
Hi! In Dendron 0.61, we have options to disable these colored squares now:
- In the editor: https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#norandomlycoloredtags
- In the preview & publishing: https://wiki.dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#norandomlycoloredtags

By setting `noRandomlyColoredTags` in the top level of your `dendron.yml`, and under `site` the colored squared will only appear for tags where you manually set colors. Other tags will not have colors.
