### ISSUE TITLE
Tag autocomplete suggestion only appears if # symbol is first in line

### ISSUE THREAD

**Issue by lenamio** [dendronhq/dendron#1352]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Tag autocomplete suggestion only appears if # symbol is first in line. It doesn't in any other position on the line

## To Reproduce

1. Focus editor
2. Type some text then space
3. Type # symbol
4. Press Ctrl+Space to launch autocomplete suggestions

## Expected behavior

Tags created earlier appear as suggestions (exactly like it does when # is first in line).

Also, suggestions for tags don't appear automatically like they do with wikilinks. Maybe it will be a nice improvement as well (though not sure how it will affect typing headings)

## Screenshots

![image](https://user-images.githubusercontent.com/20296489/133866329-0f7ee178-5f8b-483f-bee3-1b2b22336b7d.png)
![image](https://user-images.githubusercontent.com/20296489/133866330-07b65910-1917-41cb-992b-1f8fbba07e2e.png)

## Desktop (please complete the following information)

- OS: Windows
- Browser Chrome
- Version 93

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7188928/dendron.log)

**Comment by SeriousBug** [comment]
Thanks for reporting this issue, I can reproduce it as well. This seems to be a regression, we'll be fixing it soon.
