### ISSUE TITLE
New note from selection on `Ctrl+L` (Dendron: Lookup Note)

### ISSUE THREAD

**Issue by harvastum** [dendronhq/dendron#1361]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Creating new notes from text in the note is pretty awkward right now.
## Describe the solution you'd like ##

Change behavior of `Ctrl+L` shortcut, so that, if text is selected, the selected text will be copied into the search field. Right now, it has the current note's name in it, which is not particularly helpful - if you press `Ctrl+L` and `Enter` afterwards, you end up in the same state you started from.

**Comment by kevinslin** [comment]
Thanks for the issue. Currently, the recommended way to create a note using the selected text is using a [scratch note](https://wiki.dendron.so/notes/5c213aa6-e4ba-49e8-85c5-1bdcb33ce202.html#scratch-note). Does that work for your use case?
