### ISSUE TITLE
Dendron Preview looses its link to source editor after changing editor layout

### ISSUE THREAD

**Issue by lenamio** [dendronhq/dendron#1362]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## To Reproduce

1. Close all files in Workspace
2. Open .md file in Dendron Workspace
2. Run "Dendron: Show Preview V2" command
3. Window layout is split and preview appears in right half
4. Drag Preview editor from right half to the left of the source editor
5. Now window layout is split and preview appears in **left** half
6. Click on link to another md file in preview
7. Another source editor is opened in the save (left) editor group as preview and keyboard focus moves to it

## Expected behavior

On navigation through links in preview, source opens in the editor preview was original opened from, no matter what current window layout is (Unless it's "unlink preview" mode, which might be implemented in the future)

## Screenshots

![image](https://user-images.githubusercontent.com/20296489/133923065-88d0cf69-bb75-44ce-bf78-c8f03f0456b9.png)
![image](https://user-images.githubusercontent.com/20296489/133923069-c6ed3216-2ac2-4a96-9dc3-b4bccdd2bcc0.png)
![image](https://user-images.githubusercontent.com/20296489/133923071-c5194b89-a5b7-469f-ac7a-4d1e0913383b.png)

## Desktop (please complete the following information)

- OS: Windows
- Browser Chrome
- Version 93

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7191696/dendron.log)

**Comment by kevinslin** [comment]
Thanks for the issue. This is definitely a UX issue that we could do better on. This is a little more complicated because VSCode APIs don't make it easy to see the current active editor of a given webview. Adding this to our backlog

**Comment by lenamio** [comment]
As an alternative, would it be possible to show preview in the same editor as source, through a "mode switch" command? For example, like in Obsidian.

When I am browsing notes to get info, it's far more convinient to look at and navigate in preview mode. And in case I need to make edit, switch to edit mode in same editor, make an edit and then switch to preview back again.

**Comment by aleksey-rowan** [comment]
@lenamio this was most likely an issue with the V1 Preview and should have been fixed with [V2 Preview](https://wiki.dendron.so/notes/Lnp1URddmWEWweyf/#uninstall-dendron-markdown-preview-enhanced) (which should now be the default option). 

```yml
# dendron.yml
dev:
    enablePreviewV2: true
```

Could you please check if this issue is resolved for you with the V2 Preview?
