### ISSUE TITLE
VSCode markdown preview from "Dendron: Show Preview" does not match color theme

### ISSUE THREAD

**Issue by Jacobinski** [dendronhq/dendron#1366]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The theme of `Dendron: Show Preview` and `Dendron: Show Preview v2` does not match my selected color theme ([Atom One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)). Instead, the rendered theme appears to be the default dark theme.

<img width="1552" alt="Screen Shot 2021-09-19 at 2 25 52 PM" src="https://user-images.githubusercontent.com/14207293/133944031-70321fac-7ce3-4161-b147-33d7c430ddea.png">

## To Reproduce

1. Enable a non-standard color theme in VSCode.
2. Preview Dendron using `Dendron: Show Preview` and `Dendron: Show Preview v2` and observe the inconsistent colors.

## Expected behavior

The preview to match the selected theme, similar to how the normal Markdown preview works.

<img width="1552" alt="Screen Shot 2021-09-19 at 2 34 33 PM" src="https://user-images.githubusercontent.com/14207293/133944298-3bccf9bb-a573-427f-8bf4-d6cd1cb831f2.png">

## Screenshots

See above.

## Desktop (please complete the following information)

- OS: MacOS version 11.5.2
- VSCode: version 1.60.1
- Dendron: version v0.59.1
- Browser: Chrome, Version 93.0.4577.82 (Official Build) (x86_64)

**Comment by Jacobinski** [comment]
This issue also appears with other themes, and on my second computer, so I don't think it is related to my particular setup.

**Comment by aleksey-rowan** [comment]
> Dendron currently does not allow for custom theming of either the preview or the published site. This is one of our highest request features in regards to preview and publishing.

from https://wiki.dendron.so/notes/PjXL1NKL7yHV0ExHnROBl.html#context

**Comment by Jacobinski** [comment]
Good to know. Thanks!
