### ISSUE TITLE
Creating a new note with `Ctrl+click` does not generate frontmatter for the new file

### ISSUE THREAD

**Issue by harvastum** [dendronhq/dendron#1367]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Creating a new note with `Ctrl+click` does not generate frontmatter for the new file.
## To Reproduce

1. Type [[filename-that-is-not-taken yet]]
2. Press `Ctrl` and click on the newly created wikilink
3. New file only has a heading

## Expected behavior
New file has frontmatter header in it.

## Desktop (please complete the following information)

- OS: Windows
- Version: 0.59.1

**Comment by aleksey-rowan** [comment]
`Ctrl + Click` shouldn't even create a new file as this functionality was removed: https://github.com/dendronhq/dendron/issues/564#issuecomment-883669252.

If you have `noAutoCreateOnDefinition` set to `true`, then Dendron will also not create a missing file on hover. Maybe you have some other extension that understands wiki links and will try to create a file when the link is clicked. That would explain why there is no frontmatter in the new file.

**Comment by kevinslin** [comment]
@harvastum to follow from what @aleksey-rowan has said, this is most likely a different extension. do you have markdown-notes installed?

**Comment by kevinslin** [comment]
Thanks for the issue. We do plan on supporting this use case long term but currently don't have the bandwidth to work on this. Meanwhile, you can see existing functionality that can be explored using our CLI [here](https://wiki.dendron.so/notes/23a1b942-99af-45c8-8116-4f4bb7dccd21.html)
