### ISSUE TITLE
.html remains at end of reference note card links (in NextJS) and breaks links

### ISSUE THREAD

**Issue by nz-john** [dendronhq/dendron#1400]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

- the ![] type reference links, on the published cards, the "Go to text ->" link retains .html at the end, breaking the link
- this is happening on https://wiki-next.dendron.so/ also

## To Reproduce

- go to a `![]` type reference card link (in NextJS)
- click the "go to text" link
- see that it has `.html` at the end of it

## Expected behavior

- no `.html` at the end of the link

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
this has been fixed in 0.60.2-alpha.0. run the following to get the latest CLI

```sh
$ npm install @dendronhq/dendron-cli@latest

$ npx dendron --version
0.60.2-alpha.0
```
