### ISSUE TITLE
make the `code` inline+block published output nicer (NextJS)

### ISSUE THREAD

**Issue by nz-john** [dendronhq/dendron#1415]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

- cannot differentiate code blocks easily

## Describe the solution you'd like ##

- with the light gray background like on 11ty
- and the standard light red colour (works well on light/dark themes)

**Comment by ScriptAutomate** [comment]
This is a good point. The same can be said about both in-line code and code blocks. Here is a screenshot that includes a mixture of:
- Headers
- Normal text
- In-line code (text wrapped in backticks such as `this example`)
- Code blocks, such as

```bash
# This example
echo "Hello world" | grep Hello
```
![image](https://user-images.githubusercontent.com/5951023/134751834-87528bfb-536c-4361-a698-6d982f0d47b1.png)

Looks like code syntax flavor isn't present, either, so could be a few separate issues if wanting to break down into smaller tasks.

**Comment by hikchoi** [comment]
Can't recall exactly on top of my head but I remember we had some blockers with `prismjs` (what we are using to do syntax highlighting for code blocks). Regardless. Thanks for submitting the issue :) We'll let you know when this gets resolved

**Comment by kevinslin** [comment]
this should be fixed in v70 of Dendron. please post here if not, otherwise this issue will auto close in 4 days
