### ISSUE TITLE
Create a keyboard shortcut to close Preview.

### ISSUE THREAD

**Issue by apastuszak** [dendronhq/dendron#1438]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [X ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [X] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Provide keyboard shortcuts to allow open and closing of HTML Markdown previews. Right now, I can type CTRL+K V, and the preview window will pop up. But if you then type CTRL+W it will close the note and not the preview window, unless you click on the preview window first.

## Describe the solution you'd like ##

A keyboard shortcut that will always close the preview windows, regardless of where the cursor focus is.

## Describe alternatives you've considered ##

I was trying to find  if I could set another keybinding and did not see one. Dendron: Show Preview  exists, but there is no Dendron: Hide Preview

## Additional context ##

As I edit notes, I would like to pop open the Preview, see how it looks, and then close it and keep working without needing to take my hands off the keyboard.

**Comment by jonathanyeung** [comment]
Thanks @apastuszak for the suggestion - this seems like a useful command to add.  We'll prioritize against our backlog.

**Comment by aleksey-rowan** [comment]
A dedicated Dendron keybinding to always close the preview regardless of what's focused would be great, but there are other ways to do it right now without taking your hands off the keyboard (maybe not as quick as a single shortcut though):

- if you have just a single editor group, you can close the preview by `Ctrl + 2 Ctrl + W`; where `Ctrl + 2` switches to the second editor group with the preview, and when the preview is closed, the focus goes back to the first editor group with your open note;
- if you have just a single editor group, you can add a shortcut to the `@command:workbench.action.closeEditorsInOtherGroups` command to close the preview;
- alternatively, you can do `Ctrl + K Ctrl + Right Arrow Ctrl + W`; where `Ctrl + K Ctrl + Right Arrow` focuses on the editor group to the right of the current one, which should be a preview. This is a bit longer than the first two sequences though;

**Comment by memeplex** [comment]
IMO having toggle show/hide command is the most intuitive and convenient interface.

**Comment by aleksey-rowan** [comment]
> IMO having toggle show/hide command is the most intuitive and convenient interface.

I think the easiest way would be to have `Dendron: Show Preview` close the preview when called again. Maybe change the name to `Dendron: Toggle Preview` as well.

**Comment by aleksey-rowan** [comment]
This issue is featured in [this week's round](https://discord.com/channels/717965437182410783/739186036495876126/991747955742740650) of [CROP](https://wiki.dendron.so/notes/tayowNP4tMvcqH7AraoQ4/) voting on Dendron's Discord server.

**Comment by aleksey-rowan** [comment]
This just got shipped in the [0.104 release](https://wiki.dendron.so/notes/9bc92432-a24c-492b-b831-4d5378c1692b/#features).
