### ISSUE TITLE
Display animated GIF images in Preview v2

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#1444]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

GIF images display in preview v1 but not v2

## Describe the solution you'd like ##

Display GIF images with animations

## Additional context ##

Related to https://github.com/dendronhq/dendron/issues/941

**Comment by jonathanyeung** [comment]
Ack'd - thanks @SR-- for reporting!

**Comment by jonathanyeung** [comment]
Actually - I'm noticing that this works for some .gif's

A few follow up questions - which gifs are causing issues - are these locally stored .gif's or links from a website? 

I tested a few gif's:

![](https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif)

![](https://tenor.com/81wj.gif)

Top one works in Preview V2/V1/VS Code Preview.  Bottom one doesn't work on any (including VS Code's built in), as it appears it's trying to run some JS: 

```
Refused to load the script 'https://tenor.com/assets/dist/main.min.js?ca0e711b0eb1e358427156fa128feb71' because it violates the following Content Security Policy directive: "script-src 'nonce-9h4dWYladFPLwEw3uZJUVArFJoYxHckC9sdUYHsMzkpDZaoh8vS5lZMChGrTmfdk'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by SR--** [comment]
It was from the local assets folder. The GIF I tried was from the web. Let me find it. Ah, there.
![giphy](https://user-images.githubusercontent.com/1008059/135794277-9eef3cf6-85a6-4aca-83fa-f4ef60deb993.gif)

Well, I just tried it and it is rendering in v2, not sure what changed since last time I tried.

**Comment by jonathanyeung** [comment]
> Well, I just tried it and it is rendering in v2, not sure what changed since last time I tried.

It could be a performance problem - we're observing that sometimes the content in the preview pane takes a while to render properly (and in some cases it seems to not render at all). I don't think this issue is strictly related to .gif's, we're investigating.  Thanks!

**Comment by jonathanyeung** [comment]
Closing for now, as it appears to be no-repro.
