### ISSUE TITLE
block references and block range references no longer work since 9.0

### ISSUE THREAD

**Issue by mebu83** [dendronhq/dendron#146]
### Description
Since the update to Dendron 0.9.0 & 0.9.1 I no longer can include block references or block range references, as soon as I am trying to supply the header or a header range it stops rendering and only displays the reference text instead of the note content. 

### Steps to reproduce the behavior:

1. Create note daily.tasks.md (contains headings Tasks and Backlog)

2. Create note daily.journal.2020.09.01.md

3. Try to reference ((ref:[[daily.tasks]]#Tasks))

#### Works
((ref:[[daily.tasks]]))

#### No longer works
((ref:[[daily.tasks]]#Tasks))
((ref:[[daily.tasks]]#Tasks:#Backlog))

### Screenshot
![reference-block](https://user-images.githubusercontent.com/5990498/91841588-eadc4900-ec52-11ea-994b-3bfe0055ce53.PNG)

### Desktop 
Windows 10 - 1809; 
Visual Studio Code 
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by kevinslin** [comment]
Took a look. this is currently a bug in how we parse headings

if the heading you want happens to also be the first heading in the file, Dendron will return the link. You can fix this temporarily by adding a dummy header ahead of `Tasks`. meanwhile, will push a fix that should be out later this week!

**Comment by kevinslin** [comment]
this should be fixed in markdown-preview-enhanced 0.9.2. will put this ticket into pending for user confirmation

**Comment by mebu83** [comment]
Thanks @kevinslin awesome work, can't wait to try it :)
