### ISSUE TITLE
Select vault smart status/always prompt config option

### ISSUE THREAD

**Issue by Tycholiz** [dendronhq/dendron#1462]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##
As a user, we should be able to always be prompted on which vault to add to, without having to explicitly specify that each time I open the lookup tool.

This problem is especially pronounced in my workflow, where I use multiple vaults and constantly swap between them. Often I am using vaultA, but want to add a note to vaultB. I don't want to have to click the `Select vault` button to switch it to `always prompt` each time I create a new note with the lookup tool.

## Describe the solution you'd like ##

The solution we were discussing in Discord was to introduce a boolean option in yml config for smart status on creating new notes with lookup tool.

## Additional context ##
[Discord chat with Kevin, prompting the feature request](https://discord.com/channels/717965437182410783/783027389919658025/894232159093665832)

**Comment by jonathanyeung** [comment]
Thanks for the suggestion @Tycholiz. 

I think the desired behavior is that lookup from Ctrl/Cmd+L always has the 'Select Vault Mode' button available - but if `lookupConfirmVaultOnCreate` is set to true, then each time the user does Ctr/Cmd+L, this should be set to 'alwaysPrompt`, whereas if `lookupConfirmVaultOnCreate` is set to false or not set, then this should be set to `smart`. 

Are there any use cases for us _not_ to show the Select Vault Mode button when lookup is invoked from Ctrl/Cmd+L?

@hikchoi could you take a look at this one?

**Comment by Tycholiz** [comment]
Yes I agree that is sensible behaviour. A value of true for `lookupConfirmVaultOnCreate` would lead me to expect that I am always prompted by default.

**Comment by hikchoi** [comment]
We recently introduced `vaultSelectionModeOnCreate`, which will let users choose what vault selection mode should be selected when `lookupConfirmVaultOnCreate` is set.
Please let us know if this sufficiently resolves your issue @Tycholiz 

This issue will automatically close in 3 days if there are no further comments.

**Comment by Tycholiz** [comment]
looks great! Thanks for taking a look at this one, appreciate all of the hard work!
