### ISSUE TITLE
Preview is not updated when editing the front matter

### ISSUE THREAD

**Issue by lnicola** [dendronhq/dendron#1477]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Neither of the two preview panes update if I change the title in the front matter.

## Screenshots

![image](https://user-images.githubusercontent.com/308347/136250821-106c90ea-c5d4-4c78-afe9-f02435953f72.png)

![image](https://user-images.githubusercontent.com/308347/136250837-4f684933-7cba-42f3-9f11-ae1fd156dc25.png)

## Desktop

- OS: Linux
- Browser: N/A
- Version: 0.62.0

**Comment by nickolay-kondratyev** [comment]
Noted.

**Comment by lnicola** [comment]
Seems to be working, thanks!
