### ISSUE TITLE
Use note title in tree view

### ISSUE THREAD

**Issue by emarthinsen** [dendronhq/dendron#1496]
## Please Select if your Request is Either something new or an Enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I'm using dates as the leaf name of some of my notes. In the tree view, this makes the notes not very scannable.

## Describe the solution you'd like ##

I'd like the tree view to show the note title instead of the last segment of its filename

## Describe alternatives you've considered ##

I've considered longer filenames with slugified titles, but it adds additional keystrokes.

**Comment by aleksey-rowan** [comment]
Sounds like you are using the V1 tree view. V2 tree view uses note titles by default, and to enable it, you need to turn on the [`enableWebUI`](https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#enablewebui) setting in the dendron.yml.
