### ISSUE TITLE
Apostrophes are not allowed in link labels

### ISSUE THREAD

**Issue by emarthinsen** [dendronhq/dendron#1498]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [X] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Having an apostrophe in a link's label breaks the link.

## To Reproduce

This is a sample of the markdown that fails:

```
In this equation, $k_e$ is [[Coulomb's Constant|kb.note.20211011124050]]. $q_1$ and $q_2$ are the signed magnitude of the charges. $r$ is the distance between the two charges.
```

The text "Coulomb's Constant" breaks the link. Using "Coulombs Constant", by comparison, works just fine.

## Expected behavior

I'd expect the label to allow apostrophes or to have a mechanism for quoting the label or escaping the punctuation.

## Desktop (please complete the following information)

- OS: Ubuntu 18.05
- Browser Chrome
- Version 93.0.4577.63

I imagine the Dendron version might be more useful. I'm on version `0.62.1` and VS Code version `1.60.1`.

**Comment by kevinslin** [comment]
Hey @emarthinsen  - from the screenshots, it looks like you're using our legacy preview. Can you run `Dendron: Show Preview` in the latest dendron (0.68.1) and see if the link issue is still there?

**Comment by emarthinsen** [comment]
@kevinslin It works in the new preview. Oddly enough, it seems to be working in the old preview today. I'm not sure if something changed in the old preview or if the issue only appears under certain conditions.

**Comment by SeriousBug** [comment]
Glad to hear it works now. I'll go ahead and close this issue, but please feel free to submit a new issue if you experience any further problems.
