### ISSUE TITLE
Feature Request: Option to Disable @ User Automation

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#1503]
## Please Select if your Request is Either something new or an Enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [X] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

As of [Dendron 0.57](https://wiki.dendron.so/notes/W5mqxShkKlwHarz90flG2.html), using the @ symbol automatically appends "user." to the following text. 

@example will be treated as [[@example|user.example]], while example@gmail.com will be treated as [[example@gmail.com|user.gmail.com]].

This quickly becomes frustrating whether or not the a "user" hierarchy is part of the vault, as every instance of @ will be recognized as such regardless.

## Describe the solution you'd like ##

That there be an option in Dendron's settings to turn the automatic assignation of "user." to the @ symbol off. 

Ideally, the choice of symbol associated with the "user" hierarchy can be made a setting choice, and each individual can select whichever works best for their vault. I expect this would be much more labor intensive to implement however, so I believe an on/off switch is a more practical solution for the time being.

## Describe alternatives you've considered ##

The issue could be addressed by going through the vault and replacing every instance of @ not associated with the "user" hierarchy with `@` instead. Unless a vault is being very specifically managed however, in most cases there would most likely be more instances of regular use of @ than those as a part of  the "user" hierarchy.

## Additional context ##

Much of what I have noted above could also apply to Dendron's automatic assignation of "tags." to the # symbol. However, as # is more widely used in the context of tags, this seems to be less of a priority. One day perhaps, the symbol associated with the "tags" hierarchy can also be a setting choice.

**Comment by jonathanyeung** [comment]
@Dendron Team - we should add to one of our design principles that we should try to be as unopinionated as possible when it comes to how a user arranges the notes within their vaults.

**Comment by SeriousBug** [comment]
Thanks for reporting this issue. The biggest problem seems to be that user@email is being recognized as a user tag which is wrong. This is certainly a bug and I'll fix that.

It also makes sense that some users may want to disable user tags entirely. I'll add an option to disable user tags.

**Comment by micharris42** [comment]
The release notes for [version 0.66](https://wiki.dendron.so/notes/4q0nOxVnDvAMD18zyNebk/) include the line:

"fix(workspace): hover & goto note should respect enableUser/HashTags"

Unfortunately, the enableUserTags setting is still not fully functional.

The behavior of Dendron in regards to `@example` remains unchanged. Hovering over the text brings the popup:

"Note user.example is missing, use "Dendron: Goto Note" command to create it."

And when I run the Dendron Doctor command, createMissingLikedNotes, "user.example" still shows up in the list of missing notes.

**Comment by SeriousBug** [comment]
@micharris42 Sorry! I can recreate the issue. I'm fairly certain this was fixed in the development version, I'll investigate and figure out why the fix is not working.

**Comment by micharris42** [comment]
No mention of this issue in the release notes for [version 0.68](https://wiki.dendron.so/notes/EjPEcAkZIDgzHaVMk4teA/), but the behavior has changed once more. 

Hovering over the text for `@example` no longer brings the popup:

"Note user.example is missing, use "Dendron: Goto Note" command to create it."

However, hovering over the text does bring up the Show Code Actions light bulb. Clicking brings up the option to "Add missing note for wikilink declaration". 

Additionally, when running the Dendron Doctor command, createMissingLikedNotes, "user.example" still shows up in the list of missing notes.

**Comment by SeriousBug** [comment]
On the change logs, I think there was some miscommunication so the fixes were held back to 68 while the change logs were included in 67. Sorry for the confusion on that.

I can see the "add missing note" code action. I'll make a fix for it before next release.

I can't

**Comment by SeriousBug** [comment]
I figured out why Dendron Doctor was trying to create missing notes. You can follow these instructions to fix the issue for now (you just need to do this once), and a permanent solution should be published in a few weeks.

1. Make sure the `enableUserTags` config option is set to false.
2. Close Dendron
2. Delete any `.dendron.cache.json` files in your workspace or vaults
3. Restart Dendron

It will take a while for Dendron to restart since the cache was deleted, but the Doctor should stop trying to create these notes.

**Comment by SeriousBug** [comment]
The code actions lightbulb shouldn't show up now when user tags are disabled. Please see my previous message for fixing the issue with Dendron Doctor. Please let us know if we missed anywhere else where user tags continue being active despite the config. Otherwise this issue will close in a few days.

**Comment by micharris42** [comment]
Held off on responding until the new version was released. 

Replacing the `.dendron.cache.json` as outlined above has successfully removed "user.example" from the list of missing notes when running the Dendron Doctor command, createMissingLikedNotes.

Additionally, as of version 0.69, hovering over the text for `@example` no longer brings up the Show Code Actions light bulb. 

As best I can determine, the automatic assignation of "user." to the @ symbol has been turned off.

Marking this issue as Closed.
