### ISSUE TITLE
Error initialising Dendron; tree view and most commands don't work

### ISSUE THREAD

**Issue by neuroplastic** [dendronhq/dendron#151]
**Describe the bug**
Dendron throws an initialisation error. Restarting a new workspace reproduces the error after a few minutes. 
- The Dendron tree view window becomes empty.
- Dendron commands such as Lookup and Schema Lookup open the search bar, but do not work (no autocomplete; only offers to create new for any existing filename). 
- Dendron: Reload Index results in an error: (Cannot destructure property 'imports' of 'e' as it is null.)
- Dendron Doctor throws an error: (Cannot destructure property 'imports' of 'e' as it is null.)
- Note that Dendron:Open Logs works

**To Reproduce**
1. Open VSCode with dendron installed
2. Dendron throws errors (see below)
3. Try Dendron commands

**Error messages**:

error initializing dendron: {}

{"ctx":"query","err":"{\"message\":\"Cannot destructure property 'imports' of 'e' as it is null.\",\"stack\":\"TypeError: Cannot destructure property 'imports' of 'e' as it is null.\\n\\tat Function.parseSchemaVersion1 (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:47837)\\n\\tat Function.parseSchemaFile (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:48387)\\n\\tat /Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:49458\\n\\tat Array.map (<anonymous>)\\n\\tat t.FileParser.parseSchema (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:49449)\\n\\tat l._getSchemaAll (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:45548)\\n\\tat l.query (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:46025)\\n\\tat h.query (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:310:102560)\\n\\tat h.init (/Users/mb...

**Expected behavior**
Dendron commands and tree view work

**Desktop (please complete the following information):**
 - OS: Mac OS Yosemite 10.10.5
 
** Dendron Log file**
{"level":30,"time":1599139094964,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","stage":"dev","isDebug":false,"logPath":"/Users/mbyrne/Library/Application Support/Code/logs/20200903T161804/exthost1/dendron.dendron","extensionPath":"/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4","extensionUri":{"$mid":1,"fsPath":"/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4","path":"/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4","scheme":"file"},"storagePath":"/Users/mbyrne/Library/Application Support/Code/User/workspaceStorage/64e59435a955318877dfe287677ab6c7/dendron.dendron"}
{"level":30,"time":1599139094965,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1599139094966,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","installedGlobalVersion":"0.9.4","migratedGlobalVersion":"0.9.4","previousGlobalVersion":"0.9.0","previousWsVersion":"0.9.4","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"equinusocio.vsc-material-theme","version":"32.8.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":false},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.9.2","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.8","active":false},{"id":"dendron.dendron-markdown-notes","version":"0.0.17","active":false},{"id":"github.github-vscode-theme","version":"1.1.3","active":false}],"workspace":"/Users/mbyrne/Desktop/workgraphs/ds2/vault"}
{"level":30,"time":1599139094966,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","msg":"isActive:reloadWorkspace:pre"}
{"level":30,"time":1599139094966,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"createWorkspaceWatcher"}
{"level":30,"time":1599139094967,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","msg":"same wsVersion"}
{"level":30,"time":1599139094967,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","msg":"exit"}
{"level":30,"time":1599139094967,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.9.4","previousVersion":"0.9.4"}
{"level":30,"time":1599139094967,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1599139094977,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1599139094978,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"getOrCreateEngine","msg":"create new engine"}
{"level":20,"time":1599139094978,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:queryAll:pre","mode":"schema"}
{"level":50,"time":1599139094990,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query","err":"{\"message\":\"Cannot destructure property 'imports' of 'e' as it is null.\",\"stack\":\"TypeError: Cannot destructure property 'imports' of 'e' as it is null.\\n\\tat Function.parseSchemaVersion1 (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:47837)\\n\\tat Function.parseSchemaFile (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:48387)\\n\\tat /Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:49458\\n\\tat Array.map (<anonymous>)\\n\\tat t.FileParser.parseSchema (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:49449)\\n\\tat l._getSchemaAll (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:45548)\\n\\tat l.query (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:46025)\\n\\tat h.query (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:310:102560)\\n\\tat h.init (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:310:99899)\\n\\tat a.execute (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:17:73863)\\n\\tat /Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:11:80121\\n\\tat _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:374)\\n\\tat _doExecuteCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:561)\\n\\tat _.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:467)\\n\\tat Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:937:820)\\n\\tat $.reloadWorkspace (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:11:84883)\\n\\tat processTicksAndRejections (internal/process/task_queues.js:85:5)\"}"}
{"level":30,"time":1599139094991,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","msg":"dendron ready"}
{"level":20,"time":1599139094991,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"TreeView:getChildren"}
{"level":30,"time":1599139094992,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","msg":"finish reloadWorkspace"}
{"level":30,"time":1599139095018,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"activate","msg":"gotConfig","config":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","editor.minimap.enabled":false,"files.autoSave":"onFocusChange","workbench.colorTheme":"GitHub Light","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","vscodeMarkdownNotes.noteCompletionConvention":"noExtension","vscodeMarkdownNotes.slugifyCharacter":"NONE","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on"},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","dendron.dendron-markdown-notes","github.github-vscode-theme"],"unwantedRecommendations":["shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}}}
{"level":30,"time":1599139178431,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1599139178432,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"getOrCreateEngine","msg":"create new engine"}
{"level":20,"time":1599139178432,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:queryAll:pre","mode":"schema"}
{"level":50,"time":1599139178434,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query","err":"{\"message\":\"Cannot destructure property 'imports' of 'e' as it is null.\",\"stack\":\"TypeError: Cannot destructure property 'imports' of 'e' as it is null.\\n\\tat Function.parseSchemaVersion1 (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:47837)\\n\\tat Function.parseSchemaFile (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:48387)\\n\\tat /Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:49458\\n\\tat Array.map (<anonymous>)\\n\\tat t.FileParser.parseSchema (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:49449)\\n\\tat l._getSchemaAll (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:45548)\\n\\tat l.query (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:283:46025)\\n\\tat h.query (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:310:102560)\\n\\tat h.init (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:310:99899)\\n\\tat a.execute (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:17:73863)\\n\\tat h.execute (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:352:5726)\\n\\tat h.run (/Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:11:86846)\\n\\tat processTicksAndRejections (internal/process/task_queues.js:85:5)\\n\\tat async /Users/mbyrne/.vscode/extensions/dendron.dendron-0.9.4/dist/extension.js:11:80945\"}"}
{"level":30,"time":1599139385545,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"[object Object]:LookupController:pre"}
{"level":30,"time":1599139385546,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"[object Object]:LookupController:post"}
{"level":30,"time":1599139385547,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show"}
{"level":30,"time":1599139385547,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:getOrInstantiateProvider:post"}
{"level":30,"time":1599139385547,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:createQuickPick:post"}
{"level":30,"time":1599139385547,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"p.schema.","opts":{"flavor":"note"},"msg":"enter"}
{"level":20,"time":1599139385548,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:note"}
{"level":30,"time":1599139385548,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:provide:post"}
{"level":30,"time":1599139385548,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:show:post"}
{"level":30,"time":1599139385548,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"p.schema.","opts":{"flavor":"note"},"msg":"engine.query","profile":0}
{"level":30,"time":1599139385549,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"p.schema.","opts":{"flavor":"note"},"msg":"genSchemaSuggestions","profile":1}
{"level":30,"time":1599139385549,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"p.schema.","opts":{"flavor":"note"},"msg":"no matches"}
{"level":30,"time":1599139385550,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"p.schema.","opts":{"flavor":"note"},"msg":"exit","profile":2}
{"level":30,"time":1599139387647,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"","opts":{"flavor":"note"},"msg":"no qs"}
{"level":30,"time":1599139387647,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"","opts":{"flavor":"note"},"msg":"exit","profile":0}
{"level":30,"time":1599139389596,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"a","opts":{"flavor":"note"},"msg":"enter"}
{"level":20,"time":1599139389596,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:note"}
{"level":30,"time":1599139389597,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"a","opts":{"flavor":"note"},"msg":"engine.query","profile":0}
{"level":30,"time":1599139389597,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"a","opts":{"flavor":"note"},"msg":"exit","profile":1}
{"level":30,"time":1599139390683,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"ar","opts":{"flavor":"note"},"msg":"enter"}
{"level":20,"time":1599139390683,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:note"}
{"level":30,"time":1599139390683,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"ar","opts":{"flavor":"note"},"msg":"engine.query","profile":0}
{"level":30,"time":1599139390684,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"ar","opts":{"flavor":"note"},"msg":"genSchemaSuggestions","profile":1}
{"level":20,"time":1599139390684,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"ar","opts":{"flavor":"note"},"msg":"active != qs"}
{"level":30,"time":1599139390684,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"ar","opts":{"flavor":"note"},"msg":"exit"}
{"level":30,"time":1599139390684,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"ar","opts":{"flavor":"note"},"msg":"exit","profile":1}
{"level":30,"time":1599139390775,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"are","opts":{"flavor":"note"},"msg":"enter"}
{"level":20,"time":1599139390775,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:note"}
{"level":30,"time":1599139390775,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"are","opts":{"flavor":"note"},"msg":"engine.query","profile":0}
{"level":30,"time":1599139390775,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"are","opts":{"flavor":"note"},"msg":"genSchemaSuggestions","profile":1}
{"level":20,"time":1599139390775,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"are","opts":{"flavor":"note"},"msg":"active != qs"}
{"level":30,"time":1599139390776,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"are","opts":{"flavor":"note"},"msg":"exit"}
{"level":30,"time":1599139390776,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"are","opts":{"flavor":"note"},"msg":"exit","profile":1}
{"level":30,"time":1599139391125,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"area","opts":{"flavor":"note"},"msg":"enter"}
{"level":20,"time":1599139391126,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:note"}
{"level":30,"time":1599139391126,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"area","opts":{"flavor":"note"},"msg":"engine.query","profile":0}
{"level":30,"time":1599139391126,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"area","opts":{"flavor":"note"},"msg":"genSchemaSuggestions","profile":0}
{"level":20,"time":1599139391126,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"area","opts":{"flavor":"note"},"msg":"active != qs"}
{"level":30,"time":1599139391127,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"area","opts":{"flavor":"note"},"msg":"exit"}
{"level":30,"time":1599139391128,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"area","opts":{"flavor":"note"},"msg":"exit","profile":2}
{"level":30,"time":1599139391383,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"areas","opts":{"flavor":"note"},"msg":"enter"}
{"level":20,"time":1599139391384,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:note"}
{"level":30,"time":1599139391384,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"areas","opts":{"flavor":"note"},"msg":"engine.query","profile":0}
{"level":30,"time":1599139391384,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"areas","opts":{"flavor":"note"},"msg":"genSchemaSuggestions","profile":0}
{"level":20,"time":1599139391384,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"areas","opts":{"flavor":"note"},"msg":"active != qs"}
{"level":30,"time":1599139391384,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"areas","opts":{"flavor":"note"},"msg":"exit"}
{"level":30,"time":1599139391384,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"areas","opts":{"flavor":"note"},"msg":"exit","profile":1}
{"level":30,"time":1599139600414,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show"}
{"level":30,"time":1599139600415,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:getOrInstantiateProvider:post"}
{"level":30,"time":1599139600415,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:createQuickPick:post"}
{"level":30,"time":1599139600415,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"","opts":{"flavor":"schema"},"msg":"no qs"}
{"level":30,"time":1599139600415,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"","opts":{"flavor":"schema"},"msg":"exit","profile":0}
{"level":30,"time":1599139600415,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:provide:post"}
{"level":30,"time":1599139600415,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"show:show:post"}
{"level":30,"time":1599139603316,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"D","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139603317,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139603317,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"D","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":30,"time":1599139603317,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"D","opts":{"flavor":"schema"},"msg":"exit","profile":1}
{"level":30,"time":1599139603514,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"De","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139603514,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139603514,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"De","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":20,"time":1599139603514,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"De","opts":{"flavor":"schema"},"msg":"active != qs"}
{"level":30,"time":1599139603514,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"De","opts":{"flavor":"schema"},"msg":"exit"}
{"level":30,"time":1599139603515,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"De","opts":{"flavor":"schema"},"msg":"exit","profile":1}
{"level":30,"time":1599139603657,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Den","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139603657,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139603657,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Den","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":20,"time":1599139603657,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Den","opts":{"flavor":"schema"},"msg":"active != qs"}
{"level":30,"time":1599139603657,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Den","opts":{"flavor":"schema"},"msg":"exit"}
{"level":30,"time":1599139603659,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Den","opts":{"flavor":"schema"},"msg":"exit","profile":2}
{"level":30,"time":1599139604155,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dend","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139604155,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139604156,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dend","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":20,"time":1599139604156,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dend","opts":{"flavor":"schema"},"msg":"active != qs"}
{"level":30,"time":1599139604156,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dend","opts":{"flavor":"schema"},"msg":"exit"}
{"level":30,"time":1599139604156,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dend","opts":{"flavor":"schema"},"msg":"exit","profile":0}
{"level":30,"time":1599139604339,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendr","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139604340,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139604340,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendr","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":20,"time":1599139604340,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendr","opts":{"flavor":"schema"},"msg":"active != qs"}
{"level":30,"time":1599139604340,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendr","opts":{"flavor":"schema"},"msg":"exit"}
{"level":30,"time":1599139604340,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendr","opts":{"flavor":"schema"},"msg":"exit","profile":0}
{"level":30,"time":1599139604453,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendro","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139604453,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139604453,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendro","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":20,"time":1599139604454,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendro","opts":{"flavor":"schema"},"msg":"active != qs"}
{"level":30,"time":1599139604454,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendro","opts":{"flavor":"schema"},"msg":"exit"}
{"level":30,"time":1599139604454,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendro","opts":{"flavor":"schema"},"msg":"exit","profile":1}
{"level":30,"time":1599139604651,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139604652,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139604652,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":20,"time":1599139604652,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron","opts":{"flavor":"schema"},"msg":"active != qs"}
{"level":30,"time":1599139604652,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron","opts":{"flavor":"schema"},"msg":"exit"}
{"level":30,"time":1599139604652,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron","opts":{"flavor":"schema"},"msg":"exit","profile":1}
{"level":30,"time":1599139605251,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron:","opts":{"flavor":"schema"},"msg":"enter"}
{"level":20,"time":1599139605252,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"query:exit:schema","items":[]}
{"level":30,"time":1599139605252,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron:","opts":{"flavor":"schema"},"msg":"engine.query","profile":0}
{"level":20,"time":1599139605252,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron:","opts":{"flavor":"schema"},"msg":"active != qs"}
{"level":30,"time":1599139605252,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron:","opts":{"flavor":"schema"},"msg":"exit"}
{"level":30,"time":1599139605252,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"updatePickerItems","querystring":"Dendron:","opts":{"flavor":"schema"},"msg":"exit","profile":0}
{"level":30,"time":1599139610112,"pid":55048,"hostname":"MacBook-Pro-3.local","name":"dendron","ctx":"execute","opts":{}}

**Comment by neuroplastic** [comment]
P.S: In a new workspace, with Dendron tutorial vault loaded, i am working with no errors, by *not* creating any new schema. The problem reported above may be because i am generating new yaml schema.

**Comment by kevinslin** [comment]
took a look. you're getting this because a schema file in your vault is malformed. 
i was able to reproduce it by creating the following schema

- foo.schema.yml
```
version: 1
```

you can see the schema syntax here: https://www.dendron.so/notes/c5e5adde-5459-409b-b34d-a0d75cbb1052.html#schema-anatomy

we have a backlog item to validate schemas before saving. that should be out by end of this week so that this sort of issue gets caught earlier!

**Comment by kevinslin** [comment]
related to https://github.com/dendronhq/dendron/issues/154

**Comment by neuroplastic** [comment]
Thank you, @kevinslin. I thought i had validated all my schemas, because the Red Hat YAML vscode extension does a great job of showing YAML errors. But sure enough, one schema.yml file was empty.

Red Hat's YAML extension might be enough validation for dendron users for now?

**Comment by neuroplastic** [comment]
Sorry, meant to add: 

Because i had an invalid schema, and as noted VSCode has excellent YAML linting, this wasn't a valid bug report (i should have checked my schema better),
