### ISSUE TITLE
Selecting a search result navigates to explorer view (from search)

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#153]
**Describe the bug**
I used to be able to search for a tag and then click on each result sequentially, with the main edit window cycling through. 

**To Reproduce**
1. Search for a tag. 
2. Click on a search result
3. See that the sidebar has switched to explorer view (so I have to go back to search to get the next result). 

**Expected behavior**
I should continue to see search results in the side-bar. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 0.9.4

**Additional context**

** Dendron Log file**
{"level":30,"time":1599164102990,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","stage":"dev","isDebug":false,"logPath":"/Users/kpats/Library/Application Support/Code/logs/20200903T131459/exthost1/dendron.dendron","extensionPath":"/Users/kpats/.vscode/extensions/dendron.dendron-0.9.2","extensionUri":{"$mid":1,"fsPath":"/Users/kpats/.vscode/extensions/dendron.dendron-0.9.2","path":"/Users/kpats/.vscode/extensions/dendron.dendron-0.9.2","scheme":"file"},"storagePath":"/Users/kpats/Library/Application Support/Code/User/workspaceStorage/e6325386ee84c9177b5bd10c68e6ffb0/dendron.dendron"}
{"level":30,"time":1599164102991,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","installedGlobalVersion":"0.9.2","migratedGlobalVersion":"0.9.0","previousGlobalVersion":"0.8.10","previousWsVersion":"0.9.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image"},{"id":"equinusocio.vsc-material-theme","version":"32.8.0","active":false},{"id":"dendron.dendron-markdown-shortcuts"},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.9.2","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.8","active":false},{"id":"dendron.dendron-markdown-notes","version":"0.0.17","active":false},{"id":"github.github-vscode-theme"}]}
{"level":30,"time":1599164102991,"pid":68228,"hostname":"kpats-mbp","name":"dendron","msg":"reloadWorkspace:pre"}
{"level":30,"time":1599164102992,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"createWorkspaceWatcher"}
{"level":30,"time":1599164102992,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","msg":"preUpgrade: new wsVersion"}
{"level":30,"time":1599164102995,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"execute","badExtensions":[]}
{"level":30,"time":1599164102995,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","msg":"exit"}
{"level":30,"time":1599164102995,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.9.2","previousVersion":"0.9.0"}
{"level":30,"time":1599164102995,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1599164102995,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"new version","version":"0.9.2","previousVersion":"0.9.0"}
{"level":30,"time":1599164103002,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1599164103003,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"getOrCreateEngine","msg":"create new engine"}
{"level":20,"time":1599164103004,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"query:queryAll:pre","mode":"schema"}
{"level":20,"time":1599164103029,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"query:exit:pre"}
{"level":30,"time":1599164103029,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","msg":"postUpgrade: new wsVersion"}
{"level":20,"time":1599164103030,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"query:queryAll:pre","mode":"note"}
{"level":20,"time":1599164103310,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"query:exit:pre"}
{"level":30,"time":1599164103335,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1599164103466,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","msg":"dendron ready"}
{"level":20,"time":1599164103467,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"TreeView:getChildren"}
{"level":30,"time":1599164103467,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1599164103482,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","msg":"finish reloadWorkspace"}
{"level":30,"time":1599164103701,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"activate","msg":"gotConfig","config":{"folders":[{"path":"/Users/kpats/Dropbox (Facebook)/vault.main"}],"settings":{"spellright.language":["en"],"spellright.documentTypes":["markdown","latex","plaintext"],"editor.minimap.enabled":false,"files.autoSave":"onFocusChange","materialTheme.accent":"Red","workbench.colorTheme":"Material Theme Darker","pasteImage.path":"${currentFileDir}/assets","vscodeMarkdownNotes.slugifyCharacter":"NONE","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","dendron.rootDir":"/Users/kpats/Dropbox (Facebook)","editor.formatOnSave":true,"editor.quickSuggestions":true,"[markdown]":{"editor.quickSuggestions":true,"editor.fontFamily":"\"IA Writer Duo S\", monospace","editor.fontLigatures":true,"editor.fontSize":16,"editor.lineHeight":26,"editor.wordWrap":"wordWrapColumn","editor.wordWrapColumn":64,"zenMode.centerLayout":true,"editor.lineNumbers":"off"},"vscodeMarkdownNotes.noteCompletionConvention":"noExtension","pasteImage.prefix":"/","markdown.links.openLocation":"beside","markdown.preview.openMarkdownLinks":"inEditor","markdown-links.openColumn":"two","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on","markdown-links.showColumn":"two","workbench.editor.enablePreview":false,"workbench.editor.enablePreviewFromQuickOpen":false,"workbench.editor.showTabs":false,"dendron.defaultJournalDateFormat":"Y.MM.DD"},"extensions":{"recommendations":["ban.spellright","equinusocio.vsc-material-theme","mdickin.markdown-shortcuts","dendron.dendron-markdown-links","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-notes","dendron.dendron-paste-image","github.github-vscode-theme"],"unwantedRecommendations":["shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}}}
{"level":20,"time":1599164103730,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"TreeView:getChildren"}
{"level":30,"time":1599164103730,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":20,"time":1599164110612,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"TreeView:getChildren","id":"e9aecc3c-6dd8-4bfb-a829-91dc1180ab52"}
{"level":20,"time":1599164110613,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"TreeView:getChildren","id":"b6b389a4-5057-4f4f-94ba-c66ef744ccdd"}
{"level":30,"time":1599164234532,"pid":68228,"hostname":"kpats-mbp","name":"dendron","ctx":"execute","opts":{}}

**Comment by kpathakota** [comment]
There's a *small* chance that this never worked...but I could've sworn it used to.

**Comment by kevinslin** [comment]
this could be related to https://github.com/dendronhq/dendron/issues/150

can you confirm whether you still see this on version 0.9.5?

**Comment by kpathakota** [comment]
It's fixed.
