### ISSUE TITLE
"Vault Add" will add duplicate .dendron.cache.* line to .gitignore

### ISSUE THREAD

**Issue by djradon** [dendronhq/dendron#1533]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

"Vault Add" will add duplicate .dendron.cache.* line to .gitignore

## To Reproduce

1. create a new, empty remote Git repository
2. "Vault Add" to add it to a multi-vault workspace
3. notice that ".dendron.cache.*" gets added to .gitignore (possibly with an extraneous blank line at the start)
4. commit the "Vault Add"-related changes
5. "Vault Add" the repo to a different workspace (or the same one after removing it?)
6. notice an addition  ".dendron.cache.*"  line gets added

## Expected behavior

If .gitignore already contains  ".dendron.cache.*", no additional one gets added

**Comment by djradon** [comment]
Also noticed that, when adding vaults to the workspace's .gitignore:
* there's an extraneous blank line added as well when new vaults are added
* if you remove and re-add a vault, a duplicate line gets added. (expected behaviour is to not add duplicates lines or blank lines)

**Comment by djradon** [comment]
You could also argue that "Vault Remove" should cleanup the workspace's .gitignore vault reference, but since "Vault Remove" doesn't remove the folder from the filesystem, probably leaving the .gitignore line is safer.

**Comment by kevinslin** [comment]
Good catch. Will get this fixed in the coming release!

**Comment by SeriousBug** [comment]
Dendron will now avoid adding duplicate lines to gitignore with version 0.69. Let us know if you are having any trouble with this feature, otherwise this issue will close in a few days.
