### ISSUE TITLE
Lookup tool shows `+` sign on already existing notes

### ISSUE THREAD

**Issue by Tycholiz** [dendronhq/dendron#1558]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug
I have a note `javascript.lang.array.method.reduce`. When I enter `reduce` in the lookup tool, the note appears properly in the results; yet has a plus symbol next to it. The note already exists.

## Screenshots
![image](https://user-images.githubusercontent.com/39745457/138207456-b533b06a-1f6e-4e61-bedb-9343fcb4e817.png)

## Desktop (please complete the following information)

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Chrome
- Version 0.63.0

**Comment by hikchoi** [comment]
pinging @Harshita-mindfire for possible enhancement to code action provider. (detecting note in file system that are marked stub: true and also has content, and providing suggestions to remove the stub property)

**Comment by Harshita-mindfire** [comment]
This should now work on the latest version(v0.68) of Dendron. As a part of this fix, The note's frontmatter will have a warning to remove the stub property, if the note has content. Please let us know if you have any other questions, otherwise this issue will close automatically in a few days.
