### ISSUE TITLE
Issues with \ in Dendron Markdown 

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#156]
Dendron comes with a forked version of [mpe](https://shd101wyy.github.io/markdown-preview-enhanced/#/) to support dendron specific functionality like note references. We do this by modifying the markdown before mpe processes it. 

There are issues with how we handle `\` that causes them to be rendered as newlines in certain situations.

**Comment by rhaynes74** [comment]
If possible to address the issue with the single line delimiters conflicting with "I would rather $200 than $100", that would be great!

**Comment by kevinslin** [comment]
yes, this should also address that issue with the caveat that you will still have to escape the `$` signs.

the following would preview normally after the fix
```
\$100 and \$200
```

**Comment by rhaynes74** [comment]
that would be excellent, many thanks!

**Comment by kevinslin** [comment]
fixed in 0.9.3 of dendron markdown preview enhanced
