### ISSUE TITLE
Refactor Hierarchy does not obey stubs with content

### ISSUE THREAD

**Issue by Tycholiz** [dendronhq/dendron#1563]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug
I have some notes that are marked stub, but now have content in them (I'm unsure how this situation organically arose, but it's a common occurrence for me). When I want to refactor the hierarchy, every note in the hierarchy correctly has its name changed, but the notes marked as `stub: true` remain as they were before.

## To Reproduce

1. create a hierarchy
2. despite having some content, mark one of the notes as `stub: true`
3. attempt to refactor hierarchy, and notice if the `stub` note remains unchanged

## Expected behavior

All patterns matching the hierarchy should be changed, regardless of `stub` status.

## Desktop (please complete the following information)

- OS: [e.g. iOS] MacOs
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 0.64.0

**Comment by hikchoi** [comment]
[This PR](https://github.com/dendronhq/dendron/pull/1910) doesn't directly address this issue, but when I tested it seems to have resolved what you are experiencing here.

@Tycholiz can you give it a try and let us know if it works?

In the very near future I am planning to introduce some convenience features to detect notes that are created and exists in the file system but still has the `stub` frontmatter property set to true (there is no practical reason for a note that exists in the file system to be a stub note; especially if the note has a body.)

This will allow us to introduce a doctor command that bulk removes all stub properties in the workspace, or suggest code actions to users when those notes are open.
