### ISSUE TITLE
.gitignore should include seeds by default

### ISSUE THREAD

**Issue by idan** [dendronhq/dendron#1576]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [X] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Default setup does not exclude the seeds dir from git revision control.

## To Reproduce

1. Initialize a blank dendron workspace in an empty directory
2. `git init` then `git add -A`
3. Get a warning about `seeds/dendron.templates` being a git repo, and are you quite certain you meant to include it in your newly-minted git repo?

## Expected behavior

I [follow the instructions](https://wiki.dendron.so/notes/8d3c8142-7481-40da-9a5c-69a3d4bab697/#synchronizing-everything-in-one-repo) on how to synchronize dendron with git, and do not encounter any errors.

## Desktop (please complete the following information)

- OS: MacOS
- Browser: irrelevant
- Version: 0.64

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by hikchoi** [comment]
This has been resolved with v66 by #1629
Thank you for pointing this out.

Please do let us know if you have any outstanding concerns with this issue. Otherwise this issue is marked to be auto-closed in 4 days.
