### ISSUE TITLE
Goto Note to create a tag makes no sense

### ISSUE THREAD

**Issue by simkimsia** [dendronhq/dendron#1581]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

![image](https://user-images.githubusercontent.com/245021/138799069-897773a4-9f47-4077-83db-d1551c69037d.png)

## To Reproduce

Copy paste markdown content and `#maintenance` prompts a Goto NOte because tag does not exist. Confuses beginnerrs

## Expected behavior

SHould work?

## Screenshots

See above

## Desktop (please complete the following information)

erm is there a simpler way for me to copy paste this and send to you in a block? Is it from vscode About?

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z (6 days ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment]
> I think I prefer a link that when click will auto create the note as a tab.

Sorry for replying so late! I think this configuration option does what you want: https://wiki.dendron.so/notes/3i4ABJutl7NGeXRHTnUEC/#enableautocreateondefinition

With this option set to `true` in your `dendron.yml`, the tag note would be created when you `Ctrl+click` on the tag.

**Comment by aleksey-rowan** [comment]
> With this option set to `true` in your `dendron.yml`, the tag note would be created when you `Ctrl+click` on the tag.

Enabling `enableAutoCreateOnDefinition` will create a missing note on `hover` and it's really annoying (see https://github.com/dendronhq/dendron/issues/564). It's not possible to create a missing note with `Ctrl + click` right now (there is a feature request for that https://github.com/dendronhq/dendron/issues/1014), only `Ctrl + Enter` works.

**Comment by simkimsia** [comment]
i will close this as i realized that using my keybinding for goto note when i hover over the hashtag to auto generate the tag makes a lot more sense to my brain.

Thank you
