### ISSUE TITLE
Katex and Mermaid Not Rendering on dendron-site

### ISSUE THREAD

**Issue by jonathanyeung** [dendronhq/dendron#1599]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Katex and Mermaid are not rendering properly on dendron.tutorial.rich-formatting.

## To Reproduce

https://wiki.dendron.so/notes/8DCgctK-RMD4EeHjC5_hI/

Mermaid is rendering ok within Dendron Preview, but Katex does not appear to be working properly in Dendron Preview either.

Some More Examples:
- https://wiki.dendron.so/notes/fdf615f9-5292-467d-8d77-f136ecc8e109/
- [Here](https://wiki.dendron.so/notes/b1919663-cc48-4054-b0cf-4b26fe444907/), it appears that `f(x) = sin(x)` gets duplicated.

## Expected behavior

Renders Properly.

## Screenshots

![image](https://user-images.githubusercontent.com/3203268/139059153-d04f884d-05ba-4499-a159-9e8f0c74f299.png)

**Comment by kevinslin** [comment]
this should be fixed in v70 of Dendron. please post here if not, otherwise this issue will auto close in 4 days
