### ISSUE TITLE
`Move Header` does not create a note if it does not already exists

### ISSUE THREAD

**Issue by mhijazi1** [dendronhq/dendron#1606]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When using the `Move Header` command, if a note that does not already exist is specified, the note is not created, but the header is still deleted from the current note.

## To Reproduce

1. Go to a note and place your cursor over a header you would like to move
2. Select `Dendron: Move Header` from the command pallet
3. Specify a note that does not already exist as the destination

Two things should happen:
1. The header you had selected will be deleted from the file
2. No new note is created.

## Expected behavior

A new note should be created and my selected header should be moved there

Additionally, if a new note cannot be created for any reason (say a permissions issue or some other failure), then my selected header should not be deleted and should fail as a no-op.

## Desktop (please complete the following information)

- OS: Verified on Windows and MacOS
- Version: 0.65.0

## Additional Context

This is a multi-vault workspace with two remote vaults. Not sure if that has an impact as I have not verified this with a fresh single vault workspace.

**Comment by hikchoi** [comment]
@mhijazi1 

This has been shipped with v68 🎉 
Please try it out and let us know if there are still outstanding concerns regarding this issue. If there are no more comments in this thread after this point, this issue will automatically close in 4 days. Feel free to manually close this issue if you wish to do so.
