### ISSUE TITLE
Import Pod Markdown is modified my own notes body content

### ISSUE THREAD

**Issue by voothi** [dendronhq/dendron#1608]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [x] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

Is it possible to make import pod markdown without changing my note's body?
Found that after imports changed
  - `__Tag__` на `**Tag**` if this is not [[wikilink]]
  - add `\` before `_` 
  - `\\`
  - `<>` wrap links
  - `&lt;` in begin some lines
This all сreates difficulties in using the note with the code. The code is not everywhere goes to ```

## To Reproduce

I. Prepare
1. Create $dir1 (Source files)
`./Dendron/Import/Src/20211028102351-import-changing-body `
2. Copy file 
from
[20211028102351_Test-Import_Pod_Markdown.md](https://github.com/dendronhq/dendron/files/7432350/20211028102351_Test-Import_Pod_Markdown.md)
to 
$dir1
3. Create $dir2 (Destination files)
`./Dendron/Import/Dst`
4. Open VSCode
5. Copy $dir2 path to clipboard
6. Run Dendron Initialize Workspace
7. Paste $dir2 path
8. Copy 20211028102351-import-changing-body to clipboard
9. Run Dendron Add Vault
10. Paste $name

II. Import Pod Markdown
1. Edit config.import.yml
src: $dir1 
vaultName: $name
2. Run Dendron Import Pod Markdown

III. Compare files
1. src file from $dir1/20211028102351_Test-Import_Pod_Markdown.md
2. dst file from $dir2/20211028102351_test-import_pod_markdown.md

This steps shown in video 
Look links to ## Screenshots below

## Expected behavior

After complete Dendron Import Pod Markdown in each my imported markdown notes will have
- filename in only lower case (as well as now) - OK
- Dendron added frontmatter unique section  - OK
- my own content is not modefied in no way! - Fail

## Screenshots

https://www.youtube.com/watch?v=g5e993KDLx4&ab_channel=Voothi
or
https://youtu.be/g5e993KDLx4

## Desktop (please complete the following information)

- OS: 
```
OS Name:                   Microsoft Windows Server 2012 R2 Standard
OS Version:                6.3.9600 N/A Build 9600
```
- VSCode
```
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 6.3.9600
```
```
dendron.dendron
v0.65.0
```

## Additional context

https://discord.com/channels/717965437182410783/902297993477251082

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by voothi** [comment]
@kevinslin @jonathanyeung @Harshita-mindfire 
Hi! 
I tested this issue, but I don't see change. If it is important.
Thanks. 
![image](https://user-images.githubusercontent.com/9587340/142050468-1b927cff-63cf-4ded-a8f0-6eb418fa267d.png)

**Comment by Harshita-mindfire** [comment]
Hey @voothi , this issue is still OPEN. The reason behind your note's body getting modified is that the remark parser parses a note according to its syntax tree, and hence updates the `_` to `*` to imply emphasis and strong, escapes `_` etc. 
Keeping this issue in backlog so that we can track it and see if there are quick solutions to prevent parsing.

**Comment by voothi** [comment]
@Harshita-mindfire 
Hi!
I came thought how to solve this problem.
I propose in the process of imports
put the body notes in to markdown codeblock
via
wrap all body note in  ````
example:
````
body
````
or 
shift of all text on 4 space to right. 

After importing we have
- original file (src) with no change
- imported files with frontmatter and body without codeblock (original and imported body is equal).

Both options I showed in video
20211125025639;Dendron;Import Pod Proposal to resolve
https://www.youtube.com/watch?v=eoe6cefxGZo&ab_channel=Voothi

**Comment by voothi** [comment]
There is only a problem that
wikilinks in codeblock do not changed after import. 
We can decide it (I can start separate issue)?
I have such notes wikilinks in codeblock and this worked in Markdown Notes VSCode extension. 

[20210719130303_cs.20211028102351_test-import_pod_markdown.md](https://github.com/dendronhq/dendron/files/7599365/20210719130303_cs.20211028102351_test-import_pod_markdown.md)
[20210719130303_cs.20210719130303_cs.md](https://github.com/dendronhq/dendron/files/7599366/20210719130303_cs.20210719130303_cs.md)

**Comment by voothi** [comment]
Hi!
Are there any plans on this issue?
For me, imports are now broken.

**Comment by voothi** [comment]
Hi! 
Can I help something in this issue?
@kevinslin

**Comment by voothi** [comment]
Hi!
I tested - in the version of dendron.dendron v0.73.1 did not decide.

I am worried that my notes can be changed when working in Dendron in the board the moment. Part of my new notes suffered without import.

Please explore the problem with the parsing.
Thanks.

![image](https://user-images.githubusercontent.com/9587340/146510587-6324120f-073f-476d-8cee-7b5ab3be09e0.png)
@jonathanyeung
