### ISSUE TITLE
Refactor Hierarchy has complete regex (with replacement values) for robust rename many notes and change their wikilinks in vault

### ISSUE THREAD

**Issue by voothi** [dendronhq/dendron#1609]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are possible) ##

- [x] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

After imported my notes with Dendron Import Pod Markdown I have flat structure of notes in my vault without any prefix. 
All notes located in one heap (vault). The structure of links between them is stored in certain root notes in this vault. 
For prefixes (typing) my leaf notes with robust change ref wikilinks I should have tool for it. 
It seems well fit Refactor Hierarchy for this, but his don't work for some cases.
For example
Compose regexp replace string for correct renaming notes in vault. Now i get not correct strings when entering arguments 
link to examples on regex101: https://regex101.com/r/3i2s4j/1/

regex: `journal.(\d{4})(\d{2})(\d{2})`
replacement: `$1.$2.$3`
test data in:
```
veles.daily.journal.20211013
veles.daily.journal.20211014
veles.daily.journal.20211015
veles.daily.journal.20211016
veles.daily.journal.20211017
veles.daily.journal.20211018
veles.daily.journal.20211019
```
test data out:
```
veles.daily.2021.10.13
veles.daily.2021.10.14
veles.daily.2021.10.15
veles.daily.2021.10.16
veles.daily.2021.10.17
veles.daily.2021.10.18
veles.daily.2021.10.19
```

In Dendron I now have
![image](https://user-images.githubusercontent.com/9587340/139229508-4131cf07-6118-466e-b97f-31a13a7d26a3.png)

## Describe the solution you'd like ##

In Dendron Refactor Hierarchy I have worked regex replacement such as `$1.$2.$3` in example above.

## Describe alternatives you've considered ##

As a more universal solution I have in Dendron Doctor command for 
run over all notes in around all connected vault in workspace 
and fix wikilinks to new wikilinks with added prexifex.
Then I can perform rename with regex tool out of Dendron without fear what my wikilinks is corrupt.

## Additional context ##

https://discord.com/channels/717965437182410783/735365126227493004/899671538180173904
https://discord.com/channels/717965437182410783/735365126227493004/899672059129520180
https://discord.com/channels/717965437182410783/735365126227493004/902284553970937887
https://discord.com/channels/717965437182410783/735365126227493004/902283927069274202

**Comment by aleksey-rowan** [comment]
There is also an old issue about adding full regex support to the refactor command: https://github.com/dendronhq/dendron/issues/116#issuecomment-814885447

**Comment by jonathanyeung** [comment]
We have had an outstanding backlog item that @aleksey-rowan pointed out around improving the capabilities around hierarchy refactor, but we haven't had a chance to address it yet. 

@hikchoi has also been thinking on this area.

**Comment by voothi** [comment]
Hi!
@hikchoi Thanks for the implementation!
In v0.72.0 this case works fine!
I am gladly closing this issue.
