### ISSUE TITLE
Provide and/or explain functionality to modify the acknowledgements in the footer when publishing

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#1613]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are possible) ##

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Would like to be able to modify or remove the acknowledgements in the footer.

![image](https://user-images.githubusercontent.com/1008059/139357128-b5ffe631-d4bf-4aff-a3d4-0364ad3ae1e2.png)

## Describe the solution you'd like ##

Failed to find this in the docs.

**Comment by kevinslin** [comment]
Currently this is part of every  site. It helps spread awareness about Dendron. We've talked about opening it up for modification but currently have no plans on doing so
