### ISSUE TITLE
error while running command: noteVault vault should exist

### ISSUE THREAD

**Issue by Sameep1234** [dendronhq/dendron#1630]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [X] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

error while running command: noteVault vault should exist.

## To Reproduce

1. Dendron: Site Build

## Expected behavior
Site is built at x location

## Screenshots

![Capture](https://user-images.githubusercontent.com/57989899/139631661-e1861e64-a1b6-4a08-ada3-585d8a427172.PNG)

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: chrome

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` her
[dendron.log](https://github.com/dendronhq/dendron/files/7451160/dendron.log)

**Comment by jonathanyeung** [comment]
Hi @Sameep1234, can you try the resolution here? https://github.com/dendronhq/dendron/issues/1600#issuecomment-954618991

**Comment by Sameep1234** [comment]
> Hi @Sameep1234, can you try the resolution here? [#1600 (comment)](https://github.com/dendronhq/dendron/issues/1600#issuecomment-954618991)

Yes, I tried that but the error still persists. Any alternate solutions?

**Comment by Sameep1234** [comment]
> Hi @Sameep1234, can you try the resolution here? [#1600 (comment)](https://github.com/dendronhq/dendron/issues/1600#issuecomment-954618991)

Sorry for the inconvenience but it worked. I was installing it in the wrong directory. Thank you for helping out.
