### ISSUE TITLE
Fuzzy search in Lookup (note) has stopped working

### ISSUE THREAD

**Issue by HopperTech** [dendronhq/dendron#1634]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The fuzzy search feature of the Lookup (note) is not working as expected. 

## To Reproduce

1. Create new note with hierarchy - test.level.find
2. Open Lookup (note) and search for 'testf'
3. The test.level.find note is listed
4. Add an 'i' to the Lookup (note) search so it is now 'testfi'
5. The test.level.find note is no longer listed

## Expected behavior

The fuzzy search should find all matching notes

## Screenshots

![fuzzysearch-good](https://user-images.githubusercontent.com/35973180/139721545-5fb05e5e-7805-4e04-b9f7-9a29b73c83f2.jpg)
![fuzzysearch-miss](https://user-images.githubusercontent.com/35973180/139721548-9cbf7b6a-59bc-48b2-bea3-92b655a7beaf.jpg)

## Desktop (please complete the following information)

- OS: Windows
- Browser: VS Code 1.61.2
- Version: 0.65.0

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/7455390/dendron.log)

**Comment by jonathanyeung** [comment]
Thanks @HopperTech for the issue.  We've been doing some tweaks on the lookup algorithm, which has led to some intentional and unintentional changes in behavior.  @nickolay-kondratyev

**Comment by nickolay-kondratyev** [comment]
Probably best to expose the fuzziness threshold as a configuration value.

**Comment by HopperTech** [comment]
I did discover the ability to use an * which did provide the expected
result.

**Comment by nickolay-kondratyev** [comment]
Also, just adding a space between the keywords that you are looking for should get you your results.

**Comment by nickolay-kondratyev** [comment]
Waiting on migration of note lookup configuration prior to adding config for fuzzy searching as mentioned before, adding spaces ` ` between the search tokens will lead to finding notes currently.

**Comment by nickolay-kondratyev** [comment]
Pull request for adding fuzzy configuration https://github.com/dendronhq/dendron/pull/1811

**Comment by nickolay-kondratyev** [comment]
Added look up fuzziness configuration in v0.72 of Dendron, which should resolve fuzz search not being fuzzy enough for certain workspaces please post here if not, otherwise this issue will auto close in 4 days.

Docs: https://wiki.dendron.so/notes/F9LWJEjscrGkxnYi2JNby/#fuzzthreshold
