### ISSUE TITLE
Publishing should correct links to properly point to documents under the assets folder

### ISSUE THREAD

**Issue by mhijazi1** [dendronhq/dendron#1638]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are possible) ##

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##
 
When I publish my notes on a github pages branch, if I have a link to a file in my vault's `assets` directory, the published website fails to properly link to the doc. This is because while in my vault the file would be under `./assets/docs/my_doc.pdf`, on the published site the page I'm viewing is now under `./vault/<some-hash>/index.html`, however the link still points to `./assets/docs/my_doc.pdf` which is now a few folders up.

## Describe the solution you'd like ##

When publishing, it would be nice if my links are updated to be able to access the docs they are pointed to correctly. An easy way to do this in my mind would be to have links prepend the `siteUrl` and `assetsPrefix` to published links.

## Additional context ##
* Using a multi-vault repo setup
* Using github actions to publish notes to a `pages` branch
* `pages` branch is used to host a github pages website

**Comment by Harshita-mindfire** [comment]
Hi @mhijazi1, we can add assetsPrefix while publishing to github pages. Here's an example [config](https://wiki.dendron.so/notes/FnK2ws6w1uaS1YzBUY3BR.html)

**Comment by mhijazi1** [comment]
Hey @Harshita-mindfire thank you for your response. If my understanding is correct, `assetPrefix` add the provided value to ALL notes and links in my published page. 

What i'm specifically asking for here is that if I have a link to an `asset` in one of my vaults say in my note I point to a PDF of a bill using `[My Bill](./assets/docs/important_bill.pdf)` (so the file is located under `dendron-workspace/vault/assets/docs/important_bill.pdf`), when I publish that doc is moved to `<root-dir>/assets/docs/important_bill.pdf` and my note is moved to `<root-dir>/vault/<some-hash>/index.html` but the link to that document is still pointing at `./assets/docs/important_bill.pdf`, assuming that the assets folder is still at the same directory level as note itself.
