### ISSUE TITLE
Engine read metadata from JSON file

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#165]
### common-all
- src/types.ts

- [ ] modify `DEngineOpts` to take a `loadMetadataFrom` option
    - `loadMetadataFrom: "fm|json"`

### engine-server

- src/engine.ts
    - [ ] modify `getOrCreateEngine` to set new default for `loadMetadataFrom` (default to fm)

- src/drivers/file/store.ts

- [ ] modify `files2Notes` 
    - [ ] pass in `loadMetaDataFrom` to `FileParser`

- src/drivers/file/parser.ts
    - [ ] `FileParser` should take `loadMetaDataFrom` inside opts
    - [ ] modify `toNode`
        - [ ] if `loadMetaDataFrom` is `json`, load metadata from `{store.root}/meta.json`
        - [ ] modify `mdFile2NodeProps` to take an optional `metaDict` opt and pass in results of above as `metaDict`
        - [ ] `mdFile2NodeProps` should use `metaDict` to get metadata if it is passed in
        - [ ] inside `mdFile2NodeProps`, `DNodeRaw.createProps` should use metadata from `metaDict` if available

### tests

- engine-server/src/__tests__/engine.spec.ts

- [ ] add test that uses json instead of fm to load metadata

**Comment by kpathakota** [comment]
Is this still valid @kevinslin? Does this basically allow Dendron to operate on json metadata in addition to frontmatter? Do we still want to do this?

**Comment by kevinslin** [comment]
Yeah, this is to store metadata separately from the note frontmatter. We had a request back in the day but hasn't been followed up one. I'm okay with closing this for now

**Comment by kpathakota** [comment]
Sounds good
