### ISSUE TITLE
lookup (without spaces) should be case-insensitive

### ISSUE THREAD

**Issue by djradon** [dendronhq/dendron#1654]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Unless I use a space (which triggers a different modality), lookup is case-sensitive. I.e., if I don't match the file's casing, the note isn't included in the result.

## To Reproduce

1. Look up any note (without using a space) where the query doesn't match the note's case.

## Expected behavior

Lookup should be case-insensitive, or at least have the option of being case-insensitive.

**Comment by Harshita-mindfire** [comment]
Hello @djradon, thanks for reporting the issue. I can repro this one.
Pinging @nickolay-kondratyev for lookup related fix.

**Comment by Harshita-mindfire** [comment]
This should be fixed in v0.87 of Dendron. Feel free to comment here if not the same.
