### ISSUE TITLE
Mardown Preview Enhanced does not open

### ISSUE THREAD

**Issue by guilhermesfc** [dendronhq/dendron#1657]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug
Mardown Preview Enhanced does not open.
The extension reports several uncaught exceptions (please see screenshot). I have tried re-installing the extension.

## Screenshots
![image](https://user-images.githubusercontent.com/10503773/140292033-124b703c-948b-4b88-b36c-c167fd4683ee.png)

## Desktop (please complete the following information)

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Hello @guilhermesfc , Thanks for reporting the issue. I am unable to repro, Could you please share your dendron.yml file.
Also, a quick update: We've now deprecated `Dendron Markdown Preview Enhanced`. The current Show Preview V2 is included in Dendron and you don't need another extension to preview.

**Comment by guilhermesfc** [comment]
Hi @Harshita-mindfire. Here it goes
[dendron.yml.txt](https://github.com/dendronhq/dendron/files/7477468/dendron.yml.txt)

**Comment by hikchoi** [comment]
hey @guilhermesfc 
I've spent some time trying to reproduce this, but I can't seem to make it happen.

The error `no workspace` suggests that the engine had a problem connecting.
Are you in a Dendron workspace?
It would also help diagnose this problem if you could share the following:

1. Current Dendron version
2. Current VSCode version
3. VSCode build (insider, official, vscodium, etc)
