### ISSUE TITLE
Next letter after non-ascii character capitalized

### ISSUE THREAD

**Issue by cconrad** [dendronhq/dendron#1668]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When you create a note with a path/filename that contains non-ascii characters, the next character after those is capitalized in the autogenerated title.

## To Reproduce

1. Open lookup (e.g. Ctrl+L)
2. Enter/Paste "meetings.2021.11.07.birgit.forhandlingsmøde"

## Actual behavior

The title is set to "ForhandlingsmøDe" (capitalized D).

## Expected behavior

Only the first character is capitalized. 

Ideally, there would be a way to disable the automatic capitalization or to set a default language and use language-specific capitalization rules.

## Screenshots

![screenshot](https://i.imgur.com/4okW1po.png)

## Desktop (please complete the following information)

- OS: Windows 11
- Browser: Edge
- Version: 0.67.1

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7492094/dendron.log)

**Comment by Harshita-mindfire** [comment]
Hi @cconrad, Thanks for reporting the issue. I can repro this one.

**Comment by SeriousBug** [comment]
Looks like it's related to this: https://github.com/vercel/title/issues/33

Which was actually reported before too: https://github.com/dendronhq/dendron/issues/610

I'll contact the author and see if I can contribute a fix to them. Otherwise we can fork the project.

**Comment by SeriousBug** [comment]
Sorry for the delay, but this bug finally should be fixed with Dendron 0.71.0. Let us know if you have any further issues with non-ascii characters, otherwise this issue will close in a few days.

**Comment by cconrad** [comment]
I can confirm that it no longer happens after upgrading to 0.71.0
