### ISSUE TITLE
HTML tables in NextJS is not formatted and ugly - basic formatting would help

### ISSUE THREAD

**Issue by nz-john** [dendronhq/dendron#1674]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## To Reproduce

1. make tables in markdown
2. publish with NextJS
2. see that ugly HTML tables are ugly

## Expected behavior

- some basic formatting on HTML tables

## Desktop (please complete the following information)

n/a

**Comment by Harshita-mindfire** [comment]
Hi @nz-john, Thanks for reporting the issue.

**Comment by l2dy** [comment]
Fixed with https://github.com/dendronhq/dendron/pull/1737?

**Comment by Harshita-mindfire** [comment]
This should be fixed in v0.70 of Dendron. Please post here if not, otherwise this issue will auto close in 4 days
