### ISSUE TITLE
Schema note template overrides selection extract

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1675]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

When creating a new note using the `selection extract` lookup modifier, the schema note template overrides the extracted block.

## To Reproduce

1. Select a block of text in any note
2. `Ctrl + L` and tick the `selection extract` modifier
3. Create a new note in a hierarchy that has schema templates
4. Observe that selected extract was not inserted into the newly created note (the template was)

## Expected behavior

The selected extract should be prepended or appended to the note template. I think placing the extract at the beginning of the file is slightly better.

## Desktop (please complete the following information)

- Version: 0.66

**Comment by Harshita-mindfire** [comment]
Thanks @aleksey-rowan for reporting the issue. I can repro this one and I agree placing the extract at the beginning of the file sounds better.

**Comment by kevinslin** [comment]
this should be fixed in v72

**Comment by aleksey-rowan** [comment]
Can confirm it's fixed. Thank you!
