### ISSUE TITLE
Wikilinks with aliases inside tables are broken

### ISSUE THREAD

**Issue by SeriousBug** [dendronhq/dendron#1691]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Tables containing wikilinks with aliases are not recognized as wikilinks.

## To Reproduce

Paste following lines into a markdown file:
```
| Field       | Attributes | Description                                                         |
| ----------: | :--------: | ------------------------------------------------------------------- |
| `workspaceType`|`_string_| The [[dendron.topic.workspace]] of Dendron workspace.                                      |
| `workspaceType`|`_string_| The [[type|dendron.topic.workspace]] of Dendron workspace.                                      |
```

The first line will be highlighted and will work correctly in preview, the second one won't.

## Expected behavior

Both should be correctly highlighted, and should be rendered in preview.

## Screenshots

![](https://i.imgur.com/bS1AH0f.png)

## Desktop (please complete the following information)

- Version: 0.68

**Comment by aleksey-rowan** [comment]
There was an old issue about this problem: https://github.com/dendronhq/dendron/issues/110

**Comment by SeriousBug** [comment]
> There was an old issue about this problem: #110

Thanks! I'll close this issue and thumbs up that one to keep track.
