### ISSUE TITLE
Feature Request: Enable cdr/code-server compatibility

### ISSUE THREAD

**Issue by issmirnov** [dendronhq/dendron#170]
**Is your feature request related to a problem? Please describe.**
I am unable to use Dendron with the [cdr/code-server](https://github.com/cdr/code-server) project.

**Describe the solution you'd like**
I would like Dendron to be compatible with code-server.

**Describe alternatives you've considered**
I opened https://github.com/cdr/code-server/issues/2066, but even after setting the registry URL to a shared one, Dendron appears to be still incompatible with the code-server VS Code version 1.45.1

**Additional context**
code-server is a very popular project that is self-hosted by many people. Given the overlap of self-hosting + large knowledge base collectors, this is a target audience that will be especially useful and eager to help with the project.

See https://github.com/cdr/code-server/issues/2066 for potentially useful notes.

**Comment by issmirnov** [comment]
Per https://github.com/cdr/code-server/issues/2066#issuecomment-687957823, the feature request is to include the `.vsix` artifact in the Github Releases.

**Comment by kevinslin** [comment]
built a version that relaxes the vscode engine requirements. can you see try installing this version and letting me know if that works?

https://www.dropbox.com/s/v4utf9obrty1wn9/dendron-0.10.3-alpha.1.vsix?dl=0

**Comment by issmirnov** [comment]
Oooh, it worked! Thank you.

Once this makes it into an official release, could you cross post on the cdr/code-server#2066  issue to let them know?

**Comment by kevinslin** [comment]
yep, that should be later today. will do 👍

**Comment by kevinslin** [comment]
update issue on all sides. closing :)
