### ISSUE TITLE
Preview copied and pasted should not include background colors

### ISSUE THREAD

**Issue by JeffTeter** [dendronhq/dendron#1703]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

When viewing a preview of a Dendron note, a Ctrl+A followed by a Ctrl+C will copy the contents of the preview to the clipboard. If it is then pasted into another application (Gmail, etc.), in some situations, it will carry with it the background coloring. It would be preferred that background coloring would not come with it or would be an option. 

## To Reproduce

1. Go to a Dendron note and open a preview of the note.
2. Click in the preview and do Ctrl-A to select the whole preview.
3. Do Ctrl+C to copy the preview to the clipboard.
4. Go to Gmail and create a new email.
5. Press Ctrl-V to paste the clipboard into the new email.
6. The email will contain the html interpretation of the preview, including the background coloring of the section(s) copied.

## Expected behavior

When pasting into another application, it would be preferable to not include the background coloring. This would then allow the formatted text to be pasted in without the background.

## Screenshots

![dendron_1](https://user-images.githubusercontent.com/13050714/141489455-511ea8d2-fd5f-4646-9d35-a1ae0fe08563.JPG)
![dendron_2](https://user-images.githubusercontent.com/13050714/141489471-ad7299c5-7fcb-40bc-b1b1-7bd276f8b6d2.JPG)
![dendron_3](https://user-images.githubusercontent.com/13050714/141489492-8868f5b4-c694-493d-8460-00736aec7363.JPG)

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: Chrome
- Version:  95.0.4638.69

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` her
[dendron.log](https://github.com/dendronhq/dendron/files/7528574/dendron.log)
e

**Comment by kevinslin** [comment]
Thanks for the issue. We'll pick this up in our next sprint!

**Comment by nickolay-kondratyev** [comment]
This should be fixed in v{VERSION_NUM} of Dendron. please post here if not, otherwise this issue will auto close in 4 days.
