### ISSUE TITLE
forEach of undefined bug when using native workspace

### ISSUE THREAD

**Issue by simkimsia** [dendronhq/dendron#1705]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

using native workspace on existing project see https://wiki.dendron.so/notes/lamzybrD6SgQlJ9BpwkQk/
about native workspace

## To Reproduce

- Create a folder in your project for the notes. For example, a folder named notes.
- Use the command "Dendron: Initialize Workspace", and type the path to the notes folder.
- Initialize a blank workspace at this folder.
- Use the "Open Recent" command to go back to your project.
- Move the dendron.yml file from the notes folder to the root of the project.
- Open dendron.yml, and edit the vaults section so it looks like the following:
```
vaults:
    -
        fsPath: notes/vault
```
- Save the file.
- Use the command "Reload Window". Dendron should now start up, and you should be able to use all Dendron features.
- Don't commit the `dendron.code-workspace`

Now that native workspace is done, create new note using Cmd + L you will now get the error

## Expected behavior

the new note should work

## Screenshots

![image](https://user-images.githubusercontent.com/245021/141612340-d6a323dc-a92c-4092-bd07-6e3bcbe2bea9.png)

## Desktop (please complete the following information)

Last tested on: 2021-11-13

Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:59:05.913Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Name: dendron
Id: dendron.dendron
Description: Dendron is a hierarchal note taking tool that grows as you do.
Version: 0.68.1
Publisher: dendron
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dendron.dendron

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

{"level":30,"time":1636792966005,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1636792966063,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/Users/kim/Library/Application Support/Code/logs/20211113T142041/exthost5/dendron.dendron","extensionPath":"/Users/kim/.vscode/extensions/dendron.dendron-0.68.1","extensionUri":"/Users/kim/.vscode/extensions/dendron.dendron-0.68.1","workspaceFile":"/Users/kim/Projects/django-green/django-green.code-workspace","workspaceFolders":["/Users/kim/Projects/django-green"]}
{"level":30,"time":1636792966064,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1636792966064,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636792966064,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636792966064,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636792966073,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1636792966074,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"NATIVE","currentVersion":"0.68.1","previousWorkspaceVersion":"0.68.0","previousGlobalVersion":"0.68.1","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1636792966080,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1636792966080,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636792966080,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636792966080,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636792966080,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1636792966080,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Segment Residual Cache Path is at undefined"}
{"level":30,"time":1636792966276,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"migration","migrations":[]}
{"level":30,"time":1636792966311,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636792966312,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636792966312,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636792966312,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1636792966312,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Segment Residual Cache Path is at /Users/kim/Library/Application Support/Code/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
{"level":30,"time":1636792966312,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1636792966321,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","workspaceInstallStatus":"UPGRADED","currentVersion":"0.68.1","previousWorkspaceVersion":"0.68.0","previousGlobalVersion":"0.68.1","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"redhat.vscode-yaml","version":"1.2.0","active":true}],"vaults":[{"fsPath":"docs/vault"}]}
{"level":30,"time":1636792966329,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"execServer","state":"enter"}
{"level":30,"time":1636792966410,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1636792966550,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","msg":"Segment Residual Cache flush attempted. {\"successCount\":0,\"nonRetryableErrorCount\":0,\"retryableErrorCount\":0}"}
{"level":30,"time":1636792970110,"pid":13621,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1636792970111,"pid":13621,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1636792970112,"pid":13621,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1636792970112,"pid":13621,"hostname":"kimsia-mbp-2014.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1636792970252,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"execServer","state":"message","message":"55477"}
{"level":30,"time":1636792970258,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":13621}
{"level":30,"time":1636792970259,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","msg":"post-start-server","port":55477,"durationStartServer":4184}
{"level":30,"time":1636792970297,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"FileStorageV2","wsRoot":"/Users/kim/Projects/django-green","vaults":[{"fsPath":"docs/vault"}],"level":"info"}
{"level":30,"time":1636792970299,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1636792970299,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1636792970501,"pid":13621,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"daily","root":{"fsPath":"docs/vault"}}
{"level":30,"time":1636792970504,"pid":13621,"hostname":"kimsia-mbp-2014.local","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":"docs/vault"},"imports":[]}
{"level":30,"time":1636792971055,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":729}
{"level":30,"time":1636792971055,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1636792971055,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1636792971064,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1636792971064,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1636792971065,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"postReloadWorkspace","msg":"preUpgrade: new wsVersion"}
{"level":30,"time":1636792971065,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.upgradeSettings:run","msg":"pre-execute"}
{"level":30,"time":1636792971065,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"UpgradeSettingsCommand","ctx":"Upgrade:execute"}
{"level":30,"time":1636792971169,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WorkspaceConfig:update","vscodeDir":"/Users/kim/Projects/django-green/docs/vault/.vscode","snippetChanges":{}}
{"level":30,"time":1636792971169,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"Upgrade:execute","newConfig":{"extensions":{},"settings":{"add":{"markdown-preview-enhanced.enableWikiLinkSyntax":true},"errors":{}},"snippetChanges":{}}}
{"level":30,"time":1636792971169,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"Upgrade:execute","badExtensions":[]}
{"level":30,"time":1636792971169,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.upgradeSettings:run","msg":"post-execute"}
{"level":30,"time":1636792971171,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"postReloadWorkspace","msg":"postUpgrade: new wsVersion","previousWsVersion":"0.68.0","newVersion":"0.68.1"}
{"level":30,"time":1636792973755,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1636792973757,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1636792973758,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1636792973759,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1636792973763,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1636792973774,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1636792973774,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":7685}
{"level":30,"time":1636792973775,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.68.1","previousExtensionVersion":"0.68.0"}
{"level":30,"time":1636792973804,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1636792975079,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"NoteLookupCommand:gatherInput","opts":{"selectionType":"selection2link","multiSelect":false,"filterMiddleware":[],"initialValue":"dendron.yml"},"msg":"enter"}
{"level":30,"time":1636792975083,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"LookupControllerV3:new","msg":"enter"}
{"level":30,"time":1636792975084,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"prepareQuickPick","msg":"enter"}
{"level":30,"time":1636792975095,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"prepareQuickPick","msg":"exit"}
{"level":30,"time":1636792975096,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"showQuickPick","msg":"enter"}
{"level":30,"time":1636792975097,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:pre"}
{"level":30,"time":1636792975097,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"dendron.yml","justActivated":true}
{"level":30,"time":1636792975103,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792975103,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":5}
{"level":30,"time":1636792975107,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"dendron.yml","profile":9,"cancelled":false}
{"level":30,"time":1636792975108,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:post"}
{"level":30,"time":1636792975108,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"enter"}
{"level":30,"time":1636792975109,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"exit"}
{"level":30,"time":1636792975109,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"showQuickPick","msg":"exit"}
{"level":30,"time":1636792975454,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"dendron.yml","justActivated":false,"prevQuickpickValue":"dendron.yml"}
{"level":30,"time":1636792975455,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"dendron.yml","profile":0,"cancelled":false}
{"level":30,"time":1636792975641,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/kim/Projects/django-green/django-green.code-workspace","reason":"Manual","msg":"enter"}
{"level":30,"time":1636792978209,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"i","justActivated":false,"prevQuickpickValue":"dendron.yml"}
{"level":30,"time":1636792978215,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792978217,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":8}
{"level":30,"time":1636792978220,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"i","profile":11,"cancelled":false}
{"level":30,"time":1636792978536,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"is","justActivated":false,"prevQuickpickValue":"i"}
{"level":30,"time":1636792978540,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792978540,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1636792978541,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"is","profile":5,"cancelled":false}
{"level":30,"time":1636792978640,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"issues","justActivated":false,"prevQuickpickValue":"issues"}
{"level":30,"time":1636792978641,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"issues","profile":0,"cancelled":false}
{"level":30,"time":1636792978914,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"issues.","justActivated":false,"prevQuickpickValue":"issues"}
{"level":30,"time":1636792978946,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792978946,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":31}
{"level":30,"time":1636792978946,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"issues.","profile":32,"cancelled":false}
{"level":30,"time":1636792979742,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"issues.t","justActivated":false,"prevQuickpickValue":"issues."}
{"level":30,"time":1636792979744,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792979744,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":2}
{"level":30,"time":1636792979750,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"issues.t","profile":8,"cancelled":false}
{"level":30,"time":1636792979882,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"issues.te","justActivated":false,"prevQuickpickValue":"issues.t"}
{"level":30,"time":1636792979884,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792979884,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1636792979885,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"issues.te","profile":2,"cancelled":false}
{"level":30,"time":1636792980091,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"issues.tes","justActivated":false,"prevQuickpickValue":"issues.te"}
{"level":30,"time":1636792980096,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792980097,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1636792980098,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"issues.tes","profile":6,"cancelled":false}
{"level":30,"time":1636792980256,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"issues.test","justActivated":false,"prevQuickpickValue":"issues.tes"}
{"level":30,"time":1636792980273,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792980273,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":16}
{"level":30,"time":1636792980274,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"issues.test","profile":17,"cancelled":false}
{"level":30,"time":1636792980743,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"issues.test1","justActivated":false,"prevQuickpickValue":"issues.test"}
{"level":30,"time":1636792980746,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1636792980746,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":2}
{"level":30,"time":1636792980747,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"issues.test1","profile":3,"cancelled":false}
{"level":30,"time":1636792981518,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"NoteLookupProvider:onDidAccept","quickpick":"issues.test1"}
{"level":30,"time":1636792981520,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.lookupNote:run","msg":"pre-execute"}
{"level":30,"time":1636792981521,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"enter"}
{"level":30,"time":1636792981524,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1636792981524,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"docs/vault"}}
{"level":30,"time":1636792981648,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"LookupControllerV3:onHide","msg":"exit"}
{"level":30,"time":1636792981648,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"exit"}
{"level":50,"time":1636792981648,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.lookupNote:run","error":{"stack":"TypeError: Cannot read property 'forEach' of undefined\n\tat k.refreshNotesV2 (/Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/extension.js:2:346187)\n\tat k.writeNote (/Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/extension.js:2:347874)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async Se.acceptNewItem (/Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/extension.js:8:3452816)\n\tat async Promise.all (index 0)\n\tat async Se.execute (/Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/extension.js:8:3451174)\n\tat async Se.run (/Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/extension.js:8:3325983)\n\tat async /Users/kim/.vscode/extensions/dendron.dendron-0.68.1/dist/extension.js:8:3571634\n\tat async o._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111743)","message":"error while running command: Cannot read property 'forEach' of undefined","name":"DendronError","status":"unknown","payload":"{}","innerError":{}}}
{"level":30,"time":1636793205723,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1636793205725,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1636793205752,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1636793206150,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/kim/Projects/django-green/requirements/base.txt","/Users/kim/Library/Application Support/Code/logs/20211113T142041/exthost5/dendron.dendron/dendron.log"]}
{"level":30,"time":1636793206152,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kim/Library/Application Support/Code/logs/20211113T142041/exthost5/dendron.dendron/dendron.log"}
{"level":30,"time":1636793206154,"pid":13593,"hostname":"kimsia-mbp-2014.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","uri":"/Users/kim/Library/Application Support/Code/logs/20211113T142041/exthost5/dendron.dendron/dendron.log","msg":"not in workspace"}

**Comment by josephgarnier** [comment]
I can confirm this bug. For me, it appeared in the last update, before dendron was working.

**Comment by SeriousBug** [comment]
I'm having trouble replicating this issue. Could you please retry with Dendron 0.69?

You can also simplify the instructions in 0.69 as follows:

- Use the command "Dendron: Initialize Workspace", and type the path to the notes folder.
- Initialize a workspace at this folder.
- Use the "Open Recent" command to go back to your project.

**Comment by simkimsia** [comment]
Yes it's solved in 0.69 and your instructions work just as well

One small nitpick I think u meant initialize a **blank** workspace

**Comment by SeriousBug** [comment]
You can actually initialize any type of workspace now with 0.69, and upcoming 0.70 will let you use the initialize workspace command to create a native workspace.

Glad it's working!
