### ISSUE TITLE
Tree view doesn't get updated after rename Note

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#1734]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

After a rename of a note or refactoring of notes the tree view isn't updated. Clicking on the old entry opens the new one but the new hierarchy isn't shown.

## To Reproduce

1. Select a note in the tree view
2. Rename it with 'Dendron: Rename Note' to a different hierarchy (new or existing)
3. The new hierarchy isn't shown in the treev view and the note isn't shown under an existing hierarchy
4. It is still shown in the old place but clicking leads to the correct note

## Expected behavior

The tree view should be updated with the new hierarchy or show the note under the new hierarchy.

**Comment by hikchoi** [comment]
Thanks for the report.

Currently the tree view updates when there is an active editor open with a markdown file and the tree view panel is visible.
Can you see if it updates correctly if you have a markdown file open and the tree view is visible?

Nevertheless, this is a bug since we do have a file watcher that refreshes the tree view when files change. The confirmation is for further narrowing down the problem.

**Comment by Bassmann** [comment]
This is weird. I created a new workspace and it worked as expected. First I thought it may be due to the local vault but in the new workspace it also works with my remote vaults added. I can't even pinpoint any diff in the dendron.yml files that could affect it. Maybe the updates and changes to dendron.yml during migration have some strange influence. Anyway with the new workspace the problem is solved for me. Feel free to close the bug. TIL: always try to reproduce a bug in a new empty workspace before rasing an issue

**Comment by hikchoi** [comment]
Thanks for confirming. 

> Maybe the updates and changes to dendron.yml during migration have some strange influence. Anyway with the new workspace the problem is solved for me. Feel free to close the bug. 

This could probably mean we're doing something wrong with the config migration then 😅  

> TIL: always try to reproduce a bug in a new empty workspace before rasing an issue.

This would be great to pinpoint the problem after the fact but not something we would ask users to do before raising an issue. If something breaks during the day to day usage, it's fair to raise an issue.

Regardless, I would keep this in mind for the future. I'll mark this issue to auto-close in 4 days unless there are further comments.
