### ISSUE TITLE
Marcro name in [[xxxx]] can't be seen in editor under VSC "Highly Contrast" color scheme

### ISSUE THREAD

**Issue by immartian** [dendronhq/dendron#1738]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

I'm under the "High Contrast" color scheme. 

## To Reproduce

1. Go to any note pod
2. Click on the editing panel
3. Type [[ around a word to create an internal link to another note
4. The link is seen in the preview window next but displayed as blank in the editing window. 

## Screenshots

![image](https://user-images.githubusercontent.com/81030/142336901-625a5d88-b63c-4ad9-b192-54bf6d9eb21a.png)

## Desktop (please complete the following information)

- OS: Ubuntu 21.10
- Browser: Chrome
- Version: 96.0.4664.45 (Official Build) (64-bit)

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment]
Hi, I'm, not able to recreate this issue. The invisible text is just a link like this right?

![Screenshot_20211118_041241](https://user-images.githubusercontent.com/1008124/142385698-7eb7a0e2-4d1b-453b-ba53-bdd0d73052dc.png)

The wikilinks are colored based on your theme. Do you have any customizations you made to the default high contrast theme? Specifically, we use the `editorLink.activeForeground` color for wikilinks.

**Comment by immartian** [comment]
Ya, it only happens to "High Contrast" which I normally use. But never mind, I can switch to another scheme close to my visibility. I will revisit this issue once it occurs in other configurations. Thanks.
