### ISSUE TITLE
Make note references more salient and interactive

### ISSUE THREAD

**Issue by zhanghanduo** [dendronhq/dendron#174]
**Is your feature request related to a problem? Please describe.**
I really like the note linking and reference function. But the note reference looks exactly the same as other content, losing the "knowledge linking" idea because sometimes I want to refer back to the original note.

**Describe the solution you'd like**

So I suggest you could make the block background of the note reference slightly darker (according to the theme of VSCode) or draw a frame around the block. Plus, when you hover the mouse above the block, you could see a tip of the referring note name.
Then you could click the block to open the original note, just like it is a bidirectional link.

**Describe alternatives you've considered**
I currently have to add the link of the note reference before that reference to illustrate.

**Comment by kevinslin** [comment]
thanks for the issue. we'll probably implement this as part of either this week's release or the next week by the latest. out of curiosity, do you navigate primary using the markdown preview or via the editor?

**Comment by zhanghanduo** [comment]
> thanks for the issue. we'll probably implement this as part of either this week's release or the next week by the latest. out of curiosity, do you navigate primary using the markdown preview or via the editor?
Thanks for the feedback! Does the "primary" refer to the 1st class header? 
I am currently building my knowledge system, so most of the time I directly scroll up and down in the director to navigate primary headers. But when I am reviewing my notes, I will navigate them using the outline pane in the markdown preview page.

**Comment by kevinslin** [comment]
we just shipped pretty note refs with 0.10.6: https://github.com/dendronhq/dendron-template/blob/master/vault/dendron.topic.refs.md#note-reference

Take a look and let me know if there's anything missing from this. 

and by primary i meant your typical way of navigating your results :)

**Comment by zhanghanduo** [comment]
> we just shipped pretty note refs with 0.10.6: https://github.com/dendronhq/dendron-template/blob/master/vault/dendron.topic.refs.md#note-reference
> 
> Take a look and let me know if there's anything missing from this.
> 
> and by primary i meant your typical way of navigating your results :)

This is what I have been waiting for! Thanks for the speedy action. Maybe I am used to programming in the editor, I always navigate with the editor, only turn my sight to the preview when I am reading the notes.
