### ISSUE TITLE
Wiki - Search bar is on top of navigation and hidden a portion of it (Safari 15+)

### ISSUE THREAD

**Issue by davidpp** [dendronhq/dendron#1740]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [X ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

On Safari 15+ search bar appear on top on left menu.  Do not have the same issue on Chrome.

## To Reproduce

1. Using Safari 15+, go to https://wiki.dendron.so and compare to another browser

## Screenshots

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/30426/142419018-9b43f564-51f5-4faa-997b-ca071e410fb9.png">

## Desktop (please complete the following information)

- OS: Mac OS Monterey 
- Browser: Safari
- Version: 15

## Dendron Log file

Not Applicable
Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by hikchoi** [comment]
Thanks for the report. I can reproduce this in safari. We'll let you know once we get to the fix 🙏🏼

**Comment by aleksey-rowan** [comment]
Same behaviour on **Vivaldi** 3.6.

**Comment by kevinslin** [comment]
This has been fixed in the latest version of the nextjs template. Please let me know if that's not the case
