### ISSUE TITLE
Strip whitespace when using `Paste Link` command

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1741]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are possible) ##

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

When pasting some links with the `Paste Link` command, some page titles have whitespace  in them which makes the link look ugly or even breaks it:

```md
[

    Squibler: Where writers get serious



](https://www.squibler.io/)
```

Try pasting `https://www.squibler.io/` to check.

## Describe the solution you'd like ##

The `Paste Link` command strips whitespace from both ends of the page title and removes any line breaks that are in the middle of the title.

## Describe alternatives you've considered ##

Manually removing whitespace is an option, but it's annoying and takes time.

**Comment by hikchoi** [comment]
Thanks for the issue. I can reproduce this. We'll track this in our backlog and also mark it as a good first task for newcomers.
