### ISSUE TITLE
Math rendering broken

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#1747]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

In one of the last versions the redndering of math section changed and now math rendering in the preview does not work properly anymore. The equations are still displayed, but look broken compared to the KaTeX reference. 

## Screenshots

KaTeX: 

![grafik](https://user-images.githubusercontent.com/41870754/142621395-8cb89666-1374-41da-b5c6-551989fc7935.png)
![grafik](https://user-images.githubusercontent.com/41870754/142621558-cbe825ae-9dc9-4cae-ae16-7520f3d6a498.png)

dendron:

![grafik](https://user-images.githubusercontent.com/41870754/142621432-505af7ca-756b-479e-8315-f9cbc4bfcfc8.png)
![grafik](https://user-images.githubusercontent.com/41870754/142621587-b64e007c-85a9-4bf6-8bf3-3361f4ed683f.png)

**Comment by hikchoi** [comment]
Thank you for the report. Could you provide us the plaintext used to render your examples?

**Comment by funnym0nk3y** [comment]
Sure!

```latex
(\mathcal F^{\gamma} x)(\tau, f) = \left\langle x(t), \gamma(t-\tau) \mathrm e^{\mathrm j 2\pi ft}\right\rangle = \left\langle X(\nu), \Gamma(\nu-f) \mathrm e^{-\mathrm j 2\pi (\nu - f)\tau}\right\rangle
```

```tex
\begin{aligned}
    S\left(t\right) &= \sum_{n=-\infty}^{\infty} A_n g\left(t-nT\right) \\
    R\left(t\right) &= \sum_{n=-\infty}^{\infty} A_n \tilde{h}\left(t-nT\right) +  Z\left(t\right) , & \tilde{h}\left(t\right) &:= g\left(t\right) \ast h\left(t\right)\\
    Y\left(t\right) &= \sum_{n=-\infty}^{\infty} A_n x\left(t-nT\right) +  W\left(t\right) , & x\left(t\right) &= \tilde{h}\left(t\right) \ast \tilde{h}\left(t\right), & W\left(t\right) = Z\left(t\right) \ast \tilde{h}\left(t\right)\\
    Y\left[k\right] &= \sum_{n=-\infty}^{\infty} A_n x\left[k-n\right] +  W\left[k\right]\\
\end{aligned}
```

**Comment by kevinslin** [comment]
this should be fixed in v70 of Dendron. please post here if not, otherwise this issue will auto close in 4 days

**Comment by jakesnell** [comment]
v70 didn't fix this for me.

**Comment by funnym0nk3y** [comment]
> v70 didn't fix this for me.

+1

**Comment by kevinslin** [comment]
@funnym0nk3y when you say the equations look broken, do you mean that the font is different than what katex displays?

**Comment by funnym0nk3y** [comment]
@kevinslin no, I don't. The are issues with the size of integral and sum symbols. With the bounds of sums and integrals, with the size of all kinds of brackets (they don't scale how they should), with symbols above and below of letters (they are offset). Those are the issues I'm aware of.

**Comment by jakesnell** [comment]
Another issue is that \mathcal and \mathbb don't render properly. See e.g. @funnym0nk3y's example above where $\mathcal{F}$ is rendered as an ordinary F.

**Comment by kevinslin** [comment]
hmm, keeping this open to address styling issues

**Comment by HippieRocket** [comment]
> @funnym0nk3y when you say the equations look broken, do you mean that the font is different than what katex displays?

I am facing the font problem from the very beginning and it is always a problem for me. The equation in my preview looks terrible as in the picture (take a look at the broken \neq).

![image](https://user-images.githubusercontent.com/56949546/146501680-220c2342-4980-4a6a-a6de-de7b86e1be66.png)

I am using Windows 11 and the native preview works well. I tried build a workspace in WSL but it looked the same.

**Comment by CollinsPeriodLee** [comment]
I had a even worse math rendering for the latex code:
```
$$
\begin{cases}u_{t}(x, t)-L u(x, t)=f(x, t) & (x, t) \in D \times(0, \infty) \\ \left.u\right|_{\partial D}=0 &  \\ u(x, 0)=0 & x \in D\end{cases}
$$
```
In dendron:
![image](https://user-images.githubusercontent.com/22069889/149376949-c7e1e122-a387-4541-bee2-7e8fc426ce18.png)
In Markdown preview enhanced:
![image](https://user-images.githubusercontent.com/22069889/149377053-c3a0de56-1bf5-4da0-82aa-119b1b5260d8.png)

**Comment by funnym0nk3y** [comment]
In my case it seems to work again with v0.85.0

**Comment by HippieRocket** [comment]
> In my case it seems to work again with v0.85.0

Same for me. That's pretty cool.

**Comment by hikchoi** [comment]
This issue has been resolved with v85. I will mark this to automatically close in 4 days if there are not further comments.
