### ISSUE TITLE
Autocomplete note reference heading names

### ISSUE THREAD

**Issue by zhanghanduo** [dendronhq/dendron#175]
**Is your feature request related to a problem? Please describe.**
When you copy the note reference, you will switch to the target note page to paste it. Then you might forget the exact heading name to narrow down the reference scope (maybe the heading is too long or you need to know the next heading name) then you have to switch back to that page and copy the heading name. This makes the note reference less efficient. As shown in the figure below.

**Describe the solution you'd like**
I wish that when you are editing the reference there could pop up a sub-window illustrating the outline of the original note and you could locate it by clicking the corresponding headings to easily narrow down the reference you want. Or at least when you type the heading names, there could be IntelliSense autocomplete.

**Additional context**
![test1](https://user-images.githubusercontent.com/8006682/92359260-8c650e00-f11d-11ea-9248-f9c4b0e6b299.gif)

**Comment by kevinslin** [comment]
thanks for the request. 

something else we were considering is to let you copy a note ref that includes the currently selected header. auto complete is also coming but might be further down the backlog. would the former work for your use case in the meanwhile?

**Comment by zhanghanduo** [comment]
Yes, definitely! No hurry for the auto-complete one. Actually I just expect either one so I don't need to switch back and forth 😜.

**Comment by kevinslin** [comment]
fyi, we just implemented `add selection as anchor when copying note ref` functionality (that's a mouthful) to dendron: https://www.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#dendron-copy-note-ref

will create a separate tasks for auto completing. let me know if the above feature solves your problem since the auto complete will be low priority in that case :)

**Comment by zhanghanduo** [comment]
> fyi, we just implemented `add selection as anchor when copying note ref` functionality (that's a mouthful) to dendron: https://www.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#dendron-copy-note-ref
> 
> will create a separate tasks for auto completing. let me know if the above feature solves your problem since the auto complete will be low priority in that case :)

Sorry for the late reply. Somehow I just directly updated from 0.10.4 to 0.10.6 yesterday and couldn't see the new functionality until then. I will test it and give further feedbacks.

**Comment by kevinslin** [comment]
all good. have you had a chance to play around with the new functionality?

**Comment by zhanghanduo** [comment]
> all good. have you had a chance to play around with the new functionality?

Yeah, I tried and found two small problems:

1) When you select and copy the final heading as note ref, the generated reference still has the ":#*" sign and thus generated an empty reference because it cannot find the next ref.
2) I sometimes double click the heading line to select the heading instead of using mouse to manually select heading (it is quicker). But in this way dendron does not recognize I am selecting an anchor, so it just copies the whole note as a note ref.
I know this is not a bug, but I think there are other guys who are used to double-clicking to select a line.

Thanks!

**Comment by kevinslin** [comment]
We just released 0.12.1. This should fix 1) - we no longer add the next header if you are selecting the last header in the page.

As for 2), have you tried triple clicking the header? That selects the whole line and is compatible with note refs. Would that solve your use case?

**Comment by zhanghanduo** [comment]
> We just released 0.12.1. This should fix 1) - we no longer add the next header if you are selecting the last header in the page.
> 
> As for 2), have you tried triple clicking the header? That selects the whole line and is compatible with note refs. Would that solve your use case?

Thanks for the fix! I am still waiting for the new version of dendron to be upgraded on my machine. As for 2), I will show you a screenshot showing that triple-clicking cannot work on my machine.

<img src="https://raw.githubusercontent.com/zhanghanduo/Images/master/blogtriple%20click.gif" width="650">

**Comment by kevinslin** [comment]
Okay, this took a while but the latest 0.12.4 update will create refs based on selecting any part of the header. how's that for your use case?

**Comment by zhanghanduo** [comment]
> Okay, this took a while but the latest 0.12.4 update will create refs based on selecting any part of the header. how's that for your use case?

Thanks for the update. I just tried and now ref selection is indeed much easier. :)

**Comment by kevinslin** [comment]
Great! Going to keep this ticket open because I think auto completing headings will be useful regardless of this. It'll have to wait until have our [server migration](https://dendron.so/notes/725d99be-fadd-4464-88c3-0a5fcc7292c7.html) which means we're most likely looking at a november ship date for that

**Comment by zhanghanduo** [comment]
> Great! Going to keep this ticket open because I think auto completing headings will be useful regardless of this. It'll have to wait until have our [server migration](https://dendron.so/notes/725d99be-fadd-4464-88c3-0a5fcc7292c7.html) which means we're most likely looking at a november ship date for that

Sure. Actually, my initial thought was: just copy the ref of heading where my current cursor lies inside because commonly people only want to cite one section, namely no need to do anything else. Unless I want to cite multiple sections, I simply replace the * with the ending section. 
But the current solution is also great because it is more flexible and does not take more than 1 second. I really appreciate your effort! (Now the only issue for me is latex rendering in github page. I can try to provide a case study with my note with some latex equations in the future.)

**Comment by kevinslin** [comment]
I think there's value in having autocomplete since we already offer it on
links. Plus we'll be doing something similar for block references as well

**Comment by aleksey-rowan** [comment]
This is done.
