### ISSUE TITLE
No Site Build/Show Preview/Site Preview option available

### ISSUE THREAD

**Issue by Sameep1234** [dendronhq/dendron#1757]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug
No option available to built the site, to show preview or to view site on localhost

## To Reproduce

1. Open dendron workspace
2. Open command palette
3. Search for options like dendron: site build
4. You will not find any

## Expected behavior
When searched, the options should be available.

## Screenshots
![image](https://user-images.githubusercontent.com/57989899/142727504-21e497df-dd3e-4053-849c-172de4eab32f.png)

## Desktop (please complete the following information)

- OS: Windows 11
- Browser: Google Chrome

## Dendron Log file
[dendron.log](https://github.com/dendronhq/dendron/files/7574583/dendron.log)

**Comment by hikchoi** [comment]
Since v66, we renamed `Dendron: Site Build` and `Dendron Site Preview` to `Dendron: Publish Export` and `Dendron: Publish Dev`. Also note that these commands will use NextJS instead of 11ty. Please let us know if these command resolve your issues. 

relevant changelog: https://wiki.dendron.so/notes/4q0nOxVnDvAMD18zyNebk/

**Comment by Sameep1234** [comment]
> Since v66, we renamed `Dendron: Site Build` and `Dendron Site Preview` to `Dendron: Publish Export` and `Dendron: Publish Dev`. Also note that these commands will use NextJS instead of 11ty. Please let us know if these command resolve your issues.
> 
> relevant changelog: https://wiki.dendron.so/notes/4q0nOxVnDvAMD18zyNebk/

Publish dev option works perfectly find but during publish export, there is an error. Below is the screenshot for it.
![Capture](https://user-images.githubusercontent.com/57989899/142970683-9d57a935-b520-4de8-b567-c94994e5226c.png)

**Comment by kevinslin** [comment]
Are you still seeing the issue in the latest version (0.78)?

**Comment by Sameep1234** [comment]
Nope. Thanks for solving it.
