### ISSUE TITLE
interactive checkmarks

### ISSUE THREAD

**Issue by shitrip** [dendronhq/dendron#1758]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

Checkmarks are not interactive in the Dendron Preview in vscode

## To Reproduce

1. Open an MD file with `- [ ]` checkmark(s)
2. Open the Dendron Preview
3. Click the checkmark(s) in the preview..

## Expected behavior

Checkmarks state should be toggled

## Desktop (please complete the following information)

- OS: Win10 21H1
- VSCodium: 1.62.3

**Comment by hikchoi** [comment]
Thank you for the issue. There is a [duplicate issue](https://github.com/dendronhq/dendron/issues/1571) that goes over this.
Interactive checkboxes are something that were supported with our legacy preview but haven't been ported over to our current preview.

We are currently working on the stability of the preview command, and once we get to a stable point we can consider porting this feature into the current preview.

I'll mark this as a duplicate. Please upvote #1571 and continue any further discussions there if you have any more outstanding concerns.
