### ISSUE TITLE
auto dropdown of double links

### ISSUE THREAD

**Issue by simkimsia** [dendronhq/dendron#1763]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are possible) ##

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I'm frustrated when i type `[[` which shows possible suggestions. then i move my cursor away then go back inside and type the auto suggestions no longer appears.

## Describe the solution you'd like ##

let me select the content between `[[` and `]]` and remove it so it's now empty then when i retype the auto suggestion comes back.

or when i add a new chracter or remove a character the auto suggestion comes up again. but this may be too much.

## Describe alternatives you've considered ##

the alternative is to remove the entire `[[` and `]]`  and redo. which is fine but not ideal.

**Comment by hikchoi** [comment]
Thank you for the issue. This has been brought up a few times in the past, and we've made a convenience command called `Insert Note LInk` that lets you insert links without relying on VSCode's Intellisense. 

Please take a look at https://wiki.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47/#insert-note-link and let us know if this is sufficient for your use case.

**Comment by simkimsia** [comment]
Oh i just discover multilinks and setting prompt for the aliasmode. This is way more powerful. Good enough for me. Can close
