### ISSUE TITLE
External http(s):// links have a / added in front of them when doing Dendron: Export Pod

### ISSUE THREAD

**Issue by Ch41r05** [dendronhq/dendron#1823]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [X] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When doing a Dendron: Export Pod with notes containing external url links in the form of [link](https://www.google.com) the produced .md files have the link in the form of [link](/https://www.google.com). This problem is happening with dendron v0.71.0.

## To Reproduce

1. Write [link](https://www.google.com) in a note, root.md would do.
2. Execute CTRL+SHIFT+P -> Dendron: Export Pod (markup)
3. Check the produced file, root.md in this example, to see that a / was appended in front of the url

## Expected behavior

When exporting pod to markup, it should correctly keep the url.

## Desktop (please complete the following information)

- OS: Win10

**Comment by kevinslin** [comment]
@Harshita-mindfire can you confirm whether this is the case? if so, can you create a task note and add it to the backlog?

**Comment by Harshita-mindfire** [comment]
I am unable to reproduce the bug. @Ch41r05 Can you confirm if you are still experiencing this bug?

**Comment by Ch41r05** [comment]
Hello @Harshita-mindfire , the issue seems fixed now, not sure why. Thanks for the feedback.
