### ISSUE TITLE
`nav_order` should define order of nodes in tree view index

### ISSUE THREAD

**Issue by hrmnjt** [dendronhq/dendron#1830]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

As of now, `nav_order` provides a way to sort nodes while publishing but not on the tree view. Not having an order on the tree view creates a need to run the NextJS server to check if `nav_order` would work as intended.

## Describe the solution you'd like ##

It would be amazing if `nav_order` property which when defined could order the nodes in tree view to give a consistent experience.

## Describe alternatives you've considered ##

None possible alternatives to order nodes as of now.

## Additional context ##

Link to possibly related issue #440 and discussion on Discord - https://discord.com/channels/717965437182410783/735365126227493004/916094980878123011

**Comment by kevinslin** [comment]
This should come out in today's v72 release :)

**Comment by hrmnjt** [comment]
Hi @kevinslin,

I see this is not working well in v0.72 release. Sharing details here.

Dendron Version
![image](https://user-images.githubusercontent.com/10371494/145705099-7707de8d-5c1a-4749-9dbd-e207153c32f3.png)

`nav_order: 1` shows up first in tree view index
![image](https://user-images.githubusercontent.com/10371494/145705123-dc1d1e55-05c5-4c54-9c1a-1572ac2bb1bf.png)

`nav_order: 2` shows up last (4th) in tree view index
![image](https://user-images.githubusercontent.com/10371494/145705150-70b41dfb-8fd6-4650-bfc5-1604b0675977.png)

`nav_order: 99` shows up 3rd in tree view index
![image](https://user-images.githubusercontent.com/10371494/145705179-4691bdd8-9257-4524-83b9-ff5fe2137d8e.png)

This problem doesn't happen on the publishing but only on VSCode while editing. Let me know if there is a configuration that needs to be edited for this.

**Comment by kevinslin** [comment]
ah got it. we have two versions of the tree view, one that comes up when web view is enabled, the other the native dendron preview. we have not yet updated the native dendron preview tree view (that's a mouthful). will keep this open

**Comment by SeriousBug** [comment]
Hi, this seems to be functioning correctly now. although restarting Dendron seems to be required to update the order. I'll look into getting it to automatically update when the note is changed.

**Comment by hrmnjt** [comment]
Hi @SeriousBug, what do you mean by restarting dendron? Is it - `Reload Index`, `Reload Window`. For me situation is not changed much as showed in https://github.com/dendronhq/dendron/issues/1830#issuecomment-991852835

**Comment by SeriousBug** [comment]
Hey @hrmnjt , I meant "reload window", but we have a fix for this that shipped with Dendron 0.76 so it should just work now. Would you mind checking if it works for you?

**Comment by hrmnjt** [comment]
Hi @SeriousBug this is still not working for me on Dendron `v0.76`

**Comment by SeriousBug** [comment]
Could you try upgrading to the new tree view? To do so, simply add `enableWebUI: true` under `dev` in your `dendron.yml`. It will look like this:

```
dev:
    enablePreviewV2: true
    enableWebUI: true
```

The old tree view doesn't support `nav_order`, and I don't think we'll be adding support since the old tree view is being phased out.

**Comment by hrmnjt** [comment]
Tried the new tree view and `nav_order` logic works. Thanks. We may close this issue.
