### ISSUE TITLE
Autocomplete clears the line after if the closing `]]` pair is missing

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1834]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Autocomplete clears the line after the cursor if the closing `]]` pair is missing. Observe:

![evil-autocomplete](https://user-images.githubusercontent.com/79934725/144654340-04a33cba-c5d5-47cc-9c9d-a768e804b17b.gif)
![evil-autocomplete2](https://user-images.githubusercontent.com/79934725/144654341-e31220b7-b598-4668-b3d6-e110085deec7.gif)

## To Reproduce

1. Type `[[` and remove the closing pair (or start typing next to a word so there is no space between the cursor and the next character)
2. Pick something from the autocomplete dropdown
3. Observe the rest of the line disappearing into the void

## Expected behavior

Autocomplete should not modify the rest of the line.

## Desktop (please complete the following information)

- Version: 0.71.0

**Comment by SeriousBug** [comment]
I can recreate the issue. Thanks for reporting it!

**Comment by SeriousBug** [comment]
This issue has been fixed with Dendron 0.74. Please let us know if it continues to happen, otherwise this issue will automatically close in a few days.

**Comment by aleksey-rowan** [comment]
Yeap, this is fixed. Thank you! 🚀
