### ISSUE TITLE
In the Lookup deleteWordLeft does not work as in the editor

### ISSUE THREAD

**Issue by mardukbp** [dendronhq/dendron#1837]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When `editor.wordSeparators` includes period `.`, but does not include dash `-`, and the cursor is positioned after `dev.python.libs.some-awesome-lib`, in the editor deleteWordLeft deletes all characters after the last period. Whereas
in the Lookup deleteWordLeft deletes all characters after the last dash. That is, it considers the dash to be a word separator.

## To Reproduce

1. Create the note `dev.python.libs.some-awesome-lib`
2. Press Ctrl + L to lookup a note
3. Press the right arrow to move the cursor after the last character
4. Press Ctrl + Backspace to execute deleteWordLeft
5. Notice which characters were deleted

## Expected behavior

The input field of the lookup contains the characters `dev.python.libs.`

## Desktop (please complete the following information)

- OS: Windows 10
- VS Code 1.62.3
- Dendron 0.71.0

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
So this is part of the `QuickInput` widget default which is unfortunately not something we control. Could you see if VSCode has a ticket already addressing this and if not, submit it there? https://github.com/microsoft/vscode/issues

**Comment by mardukbp** [comment]
https://github.com/microsoft/vscode/issues/110057#issuecomment-723284582

> Those inputs use simple HTML `<input>` elements, and those do not support these commands.

**Comment by mardukbp** [comment]
Good news! A feature request to add this functionality to QuickInput has been added to the backlog:

https://github.com/microsoft/vscode/issues/64694

**Comment by kevinslin** [comment]
awesome! thanks for the update
