### ISSUE TITLE
Link is opening twice in browser.

### ISSUE THREAD

**Issue by tolikkostin** [dendronhq/dendron#1851]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [X] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
Bug is related for links which direct to external site (example http://example.com)
Clicking on the link in Markdown Preview mode opens 2 identical tabs in the browser.

## To Reproduce

1. Open note with link.
2. Open preview (I use built-in markdown preview)
3. Click on link into preview mode
4. See 2 tabs in your browser

## Expected behavior

Link should open one tab in browser.

## Desktop (please complete the following information)

- OS: Fedora release 33
- Browser: Chrome (Version 96.0.4664.93 ), Firefox
- Version: v0.71.0

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
{"level":30,"time":1638886567182,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1638886570247,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/home/tolik/dendron/My-Tech-Notes/bia.work_stuff.otils.md"}
{"level":30,"time":1638886570359,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"updateDecorations","msg":"Displaying 0 warnings and 1 decorations"}
{"level":30,"time":1638886570889,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1638886575615,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"dendron.openLink:run","msg":"pre-execute"}
{"level":30,"time":1638886575616,"pid":2792,"hostname":"laptop","name":"dendron","ctx":{"key":"dendron.openLink","title":"Dendron: Open Link","group":"navigation","desc":"Open link to external file (eg. pdf, .mov, etc) use system default","docLink":"dendron.topic.links.md","docPreview":"<a href=\"https://www.loom.com/share/01250485e20a4cdca2a053dd6047ac68\"><img src=\"https://cdn.loom.com/sessions/thumbnails/01250485e20a4cdca2a053dd6047ac68-with-play.gif\"> </a>"}}
{"level":50,"time":1638886575616,"pid":2792,"hostname":"laptop","name":"dendron","error":{"stack":"DendronError: no valid path or URL selected\n\tat Function.createFromStatus (/home/tolik/.vscode/extensions/dendron.dendron-0.71.0/dist/extension.js:2:102594)\n\tat Dt.execute (/home/tolik/.vscode/extensions/dendron.dendron-0.71.0/dist/extension.js:8:3247397)\n\tat Dt.run (/home/tolik/.vscode/extensions/dendron.dendron-0.71.0/dist/extension.js:8:3066561)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async /home/tolik/.vscode/extensions/dendron.dendron-0.71.0/dist/extension.js:8:3342838\n\tat async o._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111743)","message":"no valid path or URL selected","name":"DendronError","status":"invalid_state","payload":"{}"}}
{"level":30,"time":1638886575685,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"dendron.openLink:run","msg":"post-execute"}
{"level":30,"time":1638886581296,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeTextEditorVisibleRanges","editor":"/home/tolik/dendron/My-Tech-Notes/bia.work_stuff.otils.md"}
{"level":30,"time":1638886581353,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeTextEditorVisibleRanges","editor":"/home/tolik/dendron/My-Tech-Notes/bia.work_stuff.otils.md"}
{"level":30,"time":1638886581414,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeTextEditorVisibleRanges","editor":"/home/tolik/dendron/My-Tech-Notes/bia.work_stuff.otils.md"}
{"level":30,"time":1638886581478,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeTextEditorVisibleRanges","editor":"/home/tolik/dendron/My-Tech-Notes/bia.work_stuff.otils.md"}
{"level":30,"time":1638886581599,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"updateDecorations","msg":"Displaying 0 warnings and 1 decorations"}
{"level":30,"time":1638888299049,"pid":2792,"hostname":"laptop","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1638888299078,"pid":2792,"hostname":"laptop","name":"dendron","msg":"Segment Residual Cache flush attempted. {\"successCount\":0,\"nonRetryableErrorCount\":0,\"retryableErrorCount\":0}"}
{"level":30,"time":1638888654563,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1638888654564,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1638888654600,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1638888654681,"pid":2792,"hostname":"laptop","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/tolik/dendron/My-Tech-Notes/bia.work_stuff.otils.md","/home/tolik/.config/Code/logs/20211207T164454/exthost1/dendron.dendron/dendron.log"]}

**Comment by kevinslin** [comment]
Thanks for the issue. Can reproduce. We'll start working on this in our upcoming sprint!

**Comment by nickolay-kondratyev** [comment]
This should be fixed in v73 of Dendron. please post here if not, otherwise this issue will auto close in 4 days.

**Comment by tolikkostin** [comment]
Thank you Nickolay. v73 works as expected.
