### ISSUE TITLE
Broken developer doc links

### ISSUE THREAD

**Issue by jquesada2016** [dendronhq/dendron#1912]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features
- [X] Documentation

## Describe the bug

Both developer and user guide links are broken [here](https://github.com/dendronhq/dendron/blob/master/docs/README.md).

## To Reproduce

1. Go to this link: https://github.com/dendronhq/dendron/blob/master/docs/README.md
2. Click on either `User Guide` or `Developer Guide`.
3. Witness the glory of the broken link.

## Expected behavior

The respective documentation to show.

**Comment by hikchoi** [comment]
Thanks for letting us know. We'll fix this right away :)

**Comment by hikchoi** [comment]
@kevinslin I see a few changes to this file recently from you but can't figure out what you were trying to do here. looks like you were trying to link it to `root.md` on both vaults but both those files don't contain useful information for the repo.

**Comment by Binly42** [comment]
Could please fix the dev doc link as soon as possible?
Currently the cost is a bit high for me to understand Dendron ...

**Comment by kevinslin** [comment]
fixed!
