### ISSUE TITLE
Create new note in separate 'editor file' instead of the existing one.

### ISSUE THREAD

**Issue by dnyand33p** [dendronhq/dendron#1928]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

- Create New Note (Ctrl + L > 'nameOfNewNote')
- This new note file opens inside an existing editor, so have to reopen the old one.

## Describe the solution you'd like ##

Upon creating new file, it should open in new editor, instead of the existing one.

**Comment by hikchoi** [comment]
hey @dnyand33p, this can be configured. See [splitType](https://wiki.dendron.so/notes/ad270a7d-2aed-4273-8319-eb6536e38b29/#splittype)

Please try it out and let us know if it doesn't resolve your concerns.

**Comment by dnyand33p** [comment]
Resolved
