### ISSUE TITLE
Dendron extension: {"errno":-2,"code":"ENOENT","syscall":"open","path":"1639930573907","vslsStack":[]}

### ISSUE THREAD

**Issue by ChiliDogDaddyO** [dendronhq/dendron#1929]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

VS Code Dendron extension on Macbook Air M1 gives following error in a pop-up box:
{"errno":-2,"code":"ENOENT","syscall":"open","path":"1639930573907","vslsStack":[]}

First noticed when trying to invoke the Cmd+L command.

## To Reproduce

1. Go to VS Code
2. Press Cmd+L
3. See error: {"errno":-2,"code":"ENOENT","syscall":"open","path":"1639930573907","vslsStack":[]}

## Screenshots
![image](https://user-images.githubusercontent.com/10589655/146683580-be510130-03f5-4622-9b17-699b939772aa.png)

## Desktop (please complete the following information)

- OS: MacOS 12.1
- Browser: Chrome
- Version: 96.0.4664.110

## Additional context

I've also tried the following:
. restarting computer
. restarting VS Code
. uninstalling Dendron and re-installing
. ensured no VS Code keyboard shortcut conflicts with Dendron's Cmd+L command

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

{"level":30,"time":1639932479361,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1639932479393,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/Users/qt02537/Library/Application Support/Code/logs/20211219T114757/exthost1/dendron.dendron","extensionPath":"/Users/qt02537/.vscode/extensions/dendron.dendron-0.73.1","extensionUri":"/Users/qt02537/.vscode/extensions/dendron.dendron-0.73.1","workspaceFile":"1639930573907","workspaceFolders":["/Users/qt02537/local/repos/learn/21Q4/UD/python-oop-10-real-world-programs","/Users/qt02537/Dendron"]}
{"level":30,"time":1639932479393,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1639932479393,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1639932479393,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1639932479393,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1639932479394,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1639932479424,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"NATIVE","currentVersion":"0.73.1","previousWorkspaceVersion":"0.0.0","previousGlobalVersion":"0.73.1","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1639932479438,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1639932479438,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1639932479438,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1639932479438,"pid":2703,"hostname":"MacBook-Air.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1639932479438,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1639932479438,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","msg":"Segment Residual Cache Path is at undefined"}
{"level":50,"time":1639932479441,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","errno":-2,"code":"ENOENT","syscall":"open","path":"1639930573907","vslsStack":[],"stack":"Error: ENOENT: no such file or directory, open '1639930573907'","type":"Error","msg":"ENOENT: no such file or directory, open '1639930573907'"}
{"level":30,"time":1639933072427,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1639933072429,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1639933072451,"pid":2703,"hostname":"MacBook-Air.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}

**Comment by hikchoi** [comment]
Hey @ChiliDogDaddyO thank you for the report. I cannot reproduce this exact case but we'll try to diagnose this with the error logs and get back to you. 🙏🏼

**Comment by hikchoi** [comment]
pinging @SeriousBug for potential extension activation issue with native workspace

**Comment by SeriousBug** [comment]
I have access to an M1 MacBook, I'll try later today to see if I am able to reproduce the error.

**Comment by SeriousBug** [comment]
I can't reproduce the error either, but I see something weird in the logs: `"workspaceFile":"1639930573907"`

That should look like `"workspaceFile": "dendron.code-workspace"`. Could you please make sure that you are opening the workspace correctly? You can either:
- initialize a new workspace
- or use the "File: Open File" command, select the `dendron.code-workspace` file, and then click on "Open Workspace" button on the bottom right
- or, use "Dendron: Change Workspace" command, and type the path to the workspace folder

**Comment by ChiliDogDaddyO** [comment]
Hi, thank you @SeriousBug for the suggestion; it seems I was opening the Dendron folder as a workspace without opening the actual "dendron.code-workspace" file.  Newbie error--it seems to be working fine now, thanks.  I'm looking forward to exploring all the potential of Dendron!
