### ISSUE TITLE
Is it possible to link mermaids?

### ISSUE THREAD

**Issue by naveenatmit** [dendronhq/dendron#1938]
## Please select if your request is either something new or an enhancement ##

- [ x ] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ x ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Comment by hikchoi** [comment]
Hi. Could you please elaborate on what your issue is?

**Comment by naveenatmit** [comment]
I was requesting a feature to be able to click "mermaid graph nodes" and navigate "to other mermaid graphs" from "Note Preview"

**Comment by hikchoi** [comment]
Is this a standard feature for mermaid? If so, could you point me to where mermaid is describing this behavior?

We rely on mermaidjs to render mermaid syntax so extending mermaid beyond what it is capable of is out of scope for us.

It's possible to add click events to a node in standard mermaid but as of right now there is no way to do this within the preview as there is no way to provide a javascript callback to the node in preview.

**Comment by naveenatmit** [comment]
thanks for your feedback, I hope, we will find a way later on..
