### ISSUE TITLE
Publish commands still generate package.json for @dendronhq/dendron-11ty-legacy

### ISSUE THREAD

**Issue by l2dy** [dendronhq/dendron#1946]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

https://github.com/dendronhq/dendron/blob/1f0b25a112e3da630d38cfcf7966003cd8520984/packages/plugin-core/src/utils/site.ts#L67

https://github.com/dendronhq/dendron/blob/1f0b25a112e3da630d38cfcf7966003cd8520984/packages/plugin-core/src/utils/site.ts#L29-L31

## To Reproduce

1. Run `Dendron: Publish Dev` in VS Code
2. See `package.json` generated in workspace root

## Expected behavior

Publishing happens in `.next` and does not generate `package.json` in workspace root.

## Desktop (please complete the following information)

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by jonathanyeung** [comment]
Thanks for filing @l2dy  - we will take care of this one shortly.

**Comment by kevinslin** [comment]
this should be fixed now
