### ISSUE TITLE
Latex in github pages (by Dendron)

### ISSUE THREAD

**Issue by JackQAQ-byte** [dendronhq/dendron#195]
**Is your feature request related to a problem? Please describe.**
I use latex all the time, but the LaTex codes are not shown in the github page.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/66677431/92997814-aac97000-f548-11ea-88da-00742ee63f54.png)
LaTex code won't show in Github Pages

**Describe alternatives you've considered**
I looked up Stack Exchange and found this, but I've no idea how to use them.
https://stackoverflow.com/questions/26275645/how-to-support-latex-in-github-pages/55024889#55024889

**Additional context**
Thanks!

**Comment by kevinslin** [comment]
Hmm, thanks for the so link. Will take a look at it this week and see if this is something we can implement

**Comment by kevinslin** [comment]
shipped in 0.12.6
