### ISSUE TITLE
Images don't work in Github Pages by Dendron

### ISSUE THREAD

**Issue by JackQAQ-byte** [dendronhq/dendron#196]
**Describe the bug**
Images don't work in Github pages by Dendron. 

**To Reproduce**
1. Go to Dendron workspace 
2. Copy an image to clipboard
3. Ctrl + Shift + P, choose `Paste Image`
4. Push to github 
5. Go to github pages 
6. Images don't work

**Expected behavior**
Images show

**Screenshots**
As an example:
![image](https://user-images.githubusercontent.com/66677431/93013232-0e02e300-f5d9-11ea-8848-e8037e5c6c46.png)
![image](https://user-images.githubusercontent.com/66677431/93013233-12c79700-f5d9-11ea-9e48-d632493300cf.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]
 - Version [not sure]

**Additional context**
I tried changing `(/assets/images/image.png)` to `(assets/images.image.png)` (without the `/`) but didn't work

** Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
did we end up working this out?

**Comment by JackQAQ-byte** [comment]
No, I have another example from my published page (second brain). 
![image](https://user-images.githubusercontent.com/66677431/93031857-92e50f80-f660-11ea-9473-340ebd768512.png)
![image](https://user-images.githubusercontent.com/66677431/93031869-a42e1c00-f660-11ea-8d2d-573c47696971.png)
![image](https://user-images.githubusercontent.com/66677431/93031885-bb6d0980-f660-11ea-9db6-c053269b888b.png)


As you can see, 
I inserted a dendron logo and it works fine in the markdown preview, but doesn't works on the github page.

**Comment by kevinslin** [comment]
there needs to be a / in front of assets

**Comment by JackQAQ-byte** [comment]
I updated the page with the `/` (it reloaded) and didn't worj

**Comment by JackQAQ-byte** [comment]
I found a way to insert image (finally) 
using `<img src="link to image">`
But this only works for online images, hope you can find a way to fix the local images usage in Dendron, thanks

**Comment by JackQAQ-byte** [comment]
Solved! 
add    `assetsPrefix: "repo-name" ` in your `dendron.yml` file
thanks Kevin!

**Comment by osadi** [comment]
Hello,
This doesn't seem to work if the image link is a reference, like so:

```
![][an-image]
[an-image]: /assets/images/an-image.png
![][a-second-image]
[a-second-image]: (/assets/images/a-second-image.png)
```

even with `assetsPrefix` set. Locally and in Site: Preview mode `[an-image]` works, but not `[a-second-image]`
