### ISSUE TITLE
npx dendron publish build returns TypeError: Cannot read properties of undefined (reading '4')

### ISSUE THREAD

**Issue by james-mcallister** [dendronhq/dendron#1966]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Running `npx dendron publish build` from the root of my dendron workspace results in the following error: TypeError: Cannot read property '4' of undefined

## To Reproduce

Following instructions in the [dendron common](https://wiki.dendron.so/notes/2340KhiZJWUy31Nrn37Fd/) docs.
1. From the root of the dendron workspace run `npm init -y`.
2. Run `npm install @dendronhq/dendron-cli`.
3. Run `npx dendron publish init`.
    - The .next directory is created and has a bunch of stuff in it.
4. Run `npx dendron publish build`.
5. The command fails. Here is the output:  
```
error {"stack":"TypeError: Cannot read property '4' of undefined\n    at table (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/handlers/table.js:28:17)\n    at one (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/one.js:37:51)\n    at all (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/all.js:16:14)\n    at root (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/handlers/root.js:10:41)\n    at one (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/one.js:37:51)\n    at toHast (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/index.js:122:14)\n    at transformer (/Users/james/Projects/dendron/node_modules/remark-rehype/index.js:41:12)\n    at wrapped (/Users/james/Projects/dendron/node_modules/trough/wrap.js:25:19)\n    at next (/Users/james/Projects/dendron/node_modules/trough/index.js:57:24)\n    at done (/Users/james/Projects/dendron/node_modules/trough/wrap.js:55:16)","message":"Cannot read property '4' of undefined"}

TypeError: Cannot read property '4' of undefined
    at table (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/handlers/table.js:28:17)
    at one (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/one.js:37:51)
    at all (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/all.js:16:14)
    at root (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/handlers/root.js:10:41)
    at one (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/one.js:37:51)
    at toHast (/Users/james/Projects/dendron/node_modules/mdast-util-to-hast/lib/index.js:122:14)
    at transformer (/Users/james/Projects/dendron/node_modules/remark-rehype/index.js:41:12)
    at wrapped (/Users/james/Projects/dendron/node_modules/trough/wrap.js:25:19)
    at next (/Users/james/Projects/dendron/node_modules/trough/index.js:57:24)
    at done (/Users/james/Projects/dendron/node_modules/trough/wrap.js:55:16)
```

## Expected behavior

I am new to this, so I suppose I expected the build command to build the necessary assets to subsequently run export.

## Screenshots

None

## Desktop (please complete the following information)

- OS: macOS 12.0.1
- Browser: Safari
- Version: 15.1

## Additional context

N/A

## Dendron Log file

Will provide if needed.

**Comment by jonathanyeung** [comment]
Hi @james-mcallister - thanks for filing the issue. 

The callstack seems to indicate that maybe there's an issue with parsing one of your notes during the publishing step. 

We should do a better job of reporting which note had an issue to improve the debugging process - but in the meantime, I _think_ the callstack indicates it's trying to parse a markdown table.  Do you have any notes w/ tables in them? If so, can you try to temporarily remove it - you should be able to add `published: false` into the frontmatter of that note, for example:

```yaml
---
id: DkFX6BfDyjYTZuRj7FZsZ
title: '2021-11-29'
desc: ''
updated: 1640192567697
created: 1638151295267
published: false
---

## Note with Table in it.
``` 

After removing the note (or notes - may need some trial and error), can you retry the publish step, see if it works.  If it does, would you mind sharing with us what the note looked like, and we can try to investigate the parsing issue.  Thanks!

**Comment by james-mcallister** [comment]
Thank you for the reply. It was an issue with one of the tables in my notes.

For some more information, I created my tables by highlighting a block of text and converting to a markdown table by selecting `Add Table with Header` from the right-click menu, and then I put a block anchor underneath the table separated by a new line. Example:  
```
### Role Variables

Name | Type | Default | Description
-----|------|---------|------------
nginx_cache_name | string | "static_cache" | The name of the cache when using the `proxy_cache` directive.
nginx_keys_cache_size | string | "256m" | The size in memory where nginx can cache its keys. The keys are pointers to cached files at `nginx_cache_location`.
nginx_cache_inactive_time | string | "1d" | Length of time to wait for cached access for a file before it is evicted.
nginx_cache_max_size | string | "128g" | The size of the cache on disk
nginx_wiki_site_root | string | "/var/www/wiki" | The directory where wiki files will be stored.
nginx_cache_location | string | "/var/nginx/cache" | The directory for the nginx cache.

^variables-table
```

Removing the block anchor solved the problem. It should also be noted that the preview did not render, so this is my mistake. The documentation on [block anchors](https://wiki.dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c/#block-anchor) places the whole-table anchor on the same line as the last line of the table instead of on a new line and that worked for me.

Thanks again. This can be probably be closed.
