### ISSUE TITLE
File with subcategory that starts with 'md' does not show up in the Tree View properly

### ISSUE THREAD

**Issue by rickbsgu** [dendronhq/dendron#1972]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

As an example, for the category 'medical', the following subcategory files might be named thusly:

- medical.doctor.md
- medical.mdanderson
- medical.md-anderson.md

'medical.doctor' is fine and lists in the Tree View properly.  However, the other two will list as 'medical', treating the subcategory as a '.md' file suffix.

## To Reproduce

Reproduce the hierarchy above.

## Expected behavior

Tree View should list 'mdanderson' in the first case and 'md-anderson' in the next case.

Instead, it shows 'medical'.

## Suggested Fix

Fix should be easy - just check the string length past the '.' to the end of the string for a fixed length of 2 when building the Tree View.

**Comment by rickbsgu** [comment]
Well, I cloned this to see if I could fix it quickly.

No dice.  That's a hell of a big codebase.  I need a dev guide, minimally.

Otherwise, I'll just have to wait until you all can fix this.

**Comment by jonathanyeung** [comment]
@rickbsgu - thanks for filing the issue and giving it a go with the fix. We are in the process of cleaning up our dev docs, but you can find what we have now here: https://docs.dendron.so/

We'll add this to our backlog.

**Comment by Harshita-mindfire** [comment]
Hi, this has been fixed with Dendron v0.82. Please let us know if it continues to happen, otherwise, this issue will close in a few days.
