### ISSUE TITLE
Plant UML

### ISSUE THREAD

**Issue by aglucky** [dendronhq/dendron#1973]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [ x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ x] Publish - External Site Publish
- [x ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Need PlantUML support in addition to mermaid

## Describe the solution you'd like ##

Integrating PlantUML

## Describe alternatives you've considered ##

Mermaid uml but it meh.

**Comment by SR--** [comment]
This seems to be a triplicate of https://github.com/dendronhq/dendron/issues/1884 and https://github.com/dendronhq/dendron/issues/1279

**Comment by jonathanyeung** [comment]
@aglucky - thanks for filing the suggestion.  Let's track with https://github.com/dendronhq/dendron/issues/1279 as @SR-- mentioned.  Will close as dupe.
