### ISSUE TITLE
Wikilinks (backlinks) is corrupted (view color and rename change) if there's too much text visible on the screen

### ISSUE THREAD

**Issue by voothi** [dendronhq/dendron#1976]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Hi! Does anyone have such a problem with Wikilinks?
Displays invalid Wikilinks, but all is worked on command Go To. 
In White and Orange Notes Backlink to this Note is missing.
And after Dendron rename White and Orange Notes, they do not change here.
image from chat 
![image](https://user-images.githubusercontent.com/9587340/147372020-95ce4ab3-c432-4c07-a2fa-5198a046d716.png)

SeriousBug 
Could you make sure you are on the latest version of VSCode & Dendron? We had that problem in an older version but it should be fixed with the latest

I
The problem is reproduced by 
version v0.74.0, v0.73.1, v0.73.0, v0.72.0. 
In version v0.71.0 works at half. 
In version  v0.70.0 everything works, the problem is not reproduced on the same Note.

SeriousBug confirmed the error:
SeriousBug — (20211224)
I can reproduce the error, it looks like it happens if there's too much text visible on the screen (for example, if I zoom in links start working,  but if I zoom out they break).

Thanks!

## To Reproduce

look
`gif (process in dynamic)`
below

1. Create Note with one valid wikilink.
2. Fill in description wikilink either charachters (I fill Cyrillic chars in UTF-8 in my example) while will not become wikilink in another color (invalid dendron wikilinks - orange, white, etc.). Check the switching between each VSCode tabs.

## Screenshots
process
state1->add '1' to the end of description wikilink->jump to another tab and return->state2

state1
![image](https://user-images.githubusercontent.com/9587340/147371756-b57dc065-931c-4565-b30c-547fb57deb66.png)
state2
![image](https://user-images.githubusercontent.com/9587340/147371787-e304cfce-4a60-48f1-83ec-24fa7aef70e5.png)

gif (process in dynamic)
![20211224231310-animation-test-note-wikilink-size-cyrillic-name-тестирование](https://user-images.githubusercontent.com/9587340/147371729-12efcc72-fdde-48c3-9d4a-87623d32a6ab.gif)

## Desktop (please complete the following information)

Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.3.9600

dendron.dendron
v0.74.0

## Additional context

Chat discord 
Private correspondence with SeriousBug — Today (20211224 GMT 20:34)
- https://discord.com/channels/@me/923999228479549481

Question 
Does anyone have such a problem with Wikilinks?
- https://discord.com/channels/717965437182410783/923942196217020446

## Dendron Log file
Private correspondence with SeriousBug — Today (20211224 GMT 20:34)

**Comment by voothi** [comment]
file from gif demo
[20211029093632-ясно-лайв.20211224220029-тест-29-викилинков.md](https://github.com/dendronhq/dendron/files/7775150/20211029093632-.-.20211224220029-.-29-.md)

**Comment by voothi** [comment]
Hi!
In v0.77.1
The problem intensified
![image](https://user-images.githubusercontent.com/9587340/149082477-0fb7f4f3-e501-4f37-a44e-9adf9d4ab8ed.png)

**Comment by SeriousBug** [comment]
Sorry about that, I'll try to fix this issue for the next release.

**Comment by SeriousBug** [comment]
I don't think the fix made it to this release, sorry. It definitely will be on the next release though, it's already merged. I'll let you know when it's fixed.

**Comment by ryan-p-randall** [comment]
Just wanted to thank @voothi for mentioning this in the Discord and documenting it here! I've been seeing this behavior as well but couldn't reliably reproduce it.

And thank you to @SeriousBug for working on the fix!

When I encounter this problem, it doesn't just change the highlight color. As shown below, it also breaks any text decorations from a todo note (like due date or status). Please let me know if I should file a separate bug for that.
<img width="388" alt="Screen Shot 2022-01-20 at 9 01 35 PM" src="https://user-images.githubusercontent.com/850915/150463646-0adf4487-7edd-44f6-b835-4b0fac186bc1.png">
<img width="388" alt="Screen Shot 2022-01-20 at 9 01 28 PM" src="https://user-images.githubusercontent.com/850915/150463631-5d653c86-d6fd-4c8b-aeaa-bc93145c745e.png">

I just noticed that the note with working text decorations is 264 lines long, while the note with broken ones is 293 lines long. As soon as I cut the broken one to 227 lines long, the text decorations from the todo note reappeared at the top of the note. So I'm pretty sure the behavior I'm seeing is also somehow related to the note length.

**Comment by SeriousBug** [comment]
@ryan-p-randall That definitely sounds like the same issue. You can also test it out by zooming in a little (Hold Ctrl then press +), at which points the decorations update.

The fix will be out with the next release luckily!

**Comment by Binly42** [comment]
Sometimes/Usually, for me, the highlight for tags (in source editor of note) also fail, i.e. just rendered as plain text.

Not sure whether concerning...

**Comment by SeriousBug** [comment]
@Binly42 The bug would affect that as well. It should be fixed with the next release.

**Comment by SeriousBug** [comment]
Hi @Binly42 @ryan-p-randall @voothi 

The fix for this issue is now released with Dendron 0.79. Sorry for the delay!

Let us know if this keeps happening after updating. Otherwise this issue will automatically close in a few days.

**Comment by voothi** [comment]
@SeriousBug 
Hi! 
This work in v0.79.0! 
Thanks!
