### ISSUE TITLE
Typo in VaultConvert.ts

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#1991]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Only a tiny issue, but currently when converting to a remote vault from a local vault, the message `Converting vault to local` is printed instead of 
`Converting vault to remote`

https://github.com/dendronhq/dendron/blob/3a42ab78416019b716b842c08de247e7df22376c/packages/plugin-core/src/commands/VaultConvert.ts#L174-L192

## To Reproduce

1. Add a new local vault
2. Convert to remote
3. Watch notifications

## Expected behavior

The message should align to what is being done.

## Desktop (please complete the following information)

- OS: Windows 11
- Dendron Version: v0.74.0

## Additional context

None

## Dendron Log file

N/A

**Comment by jonathanyeung** [comment]
Thanks @rlh1994 - good catch!

Let me know if you'd like to submit a code change.  Otherwise we can also handle it.

**Comment by rlh1994** [comment]
Sorry yeah @jonathanyeung done that now, I was originally going to raise something else/more complex then realised I was wrong - a string change I can do myself!
