### ISSUE TITLE
Bug: Image Markdown fails with spaces and caps in name of file

### ISSUE THREAD

**Issue by peanutputter** [dendronhq/dendron#200]
Bug: when creating markdown image using the link markdown syntax with relative paths ex: /assets/images/someFile.jpg it works if NO spaces are used in the title(programming technique) BUT FAILS if spaces are used for non-programmers in naming their files For Example: a regular user expectation for naming their files use spaces and caps (/assets/images/This is how I want to name this file.jpg) This is where the image markdown syntax fails.

**Comment by ScriptAutomate** [comment]
Related: https://github.com/dendronhq/dendron/issues/2228
