### ISSUE TITLE
Issue with moving non-leaf notes between vaults; broken links, stub flags in non-stubs

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#2003]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I'm not entirely sure if this is truly a bug vs an issue with the way I am using multi-vaults.

When moving a note to another vault (but keeping the same name), if this note is not a leaf and instead leaves a stub (no file but in hierarchy) in the first vault, this causes ![[...]] type links to fail and [[...]] style links in the preview to create a new file in the first vault on click (ctrl+ent in the note itself asks which vault you want to select the note from).

When all notes in that hierarchy are moved so that there is no stub file, the links all work correctly again, however if you have leave some children notes then all links to the parent need to be prefixed with `wsRoot://vault2/` manually. The good news is if a note link does use this prefix, any subsequent moves all correctly the pointing.

The second part of this bug is if you move a note from one vault into a stub-note of another vault (this might be the same issue if you rename a note to the name of a stub, I did not think to test this), then that note gains a `stub: true` flag in the frontmatter when it actually contains details.

## To Reproduce

0. Have a workspace with 2 vaults.
1. In vault1 create `note_to_embed`, `note_to_embed.leaf`, `summary_note`.  Put some random text in the first 2 files.
2. In `summary_note` put ![[note_to_embed]] and [[note_to_embed]]
3. Go to note_to_embed and use the `Move Note` command, move this note (with the same name) into vault2
4. **Issue1:** Run the `Reload Index` command, in the Preview of `summary_note` you will see a `Error Rendering note reference for note_to_embed` message. The link will also by default in the preview take you to a create a new note from the (now) stub that exists in vault1. You have to manually go and correct these links to be `wsRoot://vault2/note_to_embed` if you want them to work.
5. Now repeat step 2 but with `note_to_embed.leaf` instead, which also removes the stub note in vault1, reload the index and all links now work correctly.
6. Move `note_to_embed.leaf` back into vault1, reload index
7. **Issue2:** note the frontmatter of `note_to_embed`, run the `Move Note`  command and move it back to vault1, reload index. The frontmatter for this note now contains the `stub: true` which given it contains the random text we placed above is not true, I assume this was caused my moving a note into the place of an existing stub note.

## Expected behavior

I expect when I move the parent note to another vault and leave children notes in the first that the links to the parent would be updated correctly to point to the note in the new vault not the stub note in vault1. I would then secondarily expect (although this would be a lot harder) that when all child notes have been removed from vault 1 such that no stub exists, the final move (or a doctor command?) would simplify the links to remove the vault prefix.

I expect when moving a note into the place of a stub note in another vault, the note would not gain a stub flag.

## Screenshots

![image](https://user-images.githubusercontent.com/8260415/147661853-a687c8a4-ddac-4660-af26-25ea676163b2.png)

## Desktop (please complete the following information)

- OS: Windows 8.1
- Version: Dendron 0.75.0, VSCode 1.60.2

**Comment by kevinslin** [comment]
This is the current behavior but we'll be fixing this in January. The reason that you have notes that are labelled `stub` is due to how [permanent ids](https://wiki.dendron.so/notes/2fe96d3a-dcf9-409b-8a09-fdaa5a664433.html#permanent-ids) work when publishing.

Since Dendron encourages refactoring, all notes are published using their ids. This presents a problem when combined with [stubs](https://wiki.dendron.so/notes/c6fd6bc4-7f75-4cbb-8f34-f7b99bfe2d50.html#stubs) which are virtual notes dendron creates when you create a hierarchy where some of the parents don't exist.

This is because stubs have a random id generated everytime and if you wanted to publish a stub, it would not have a permanent id.

Our initial solution was to write stubs to disk with the `stub: true` flag, but this causes all sorts of problems like the one you're raising now. In January, we'll be removing the `stub` field altogether and never writing it to disk.
