### ISSUE TITLE
CONTIBUTING link on website home page 404'd

### ISSUE THREAD

**Issue by tallguyjenks** [dendronhq/dendron#2024]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Link on [website home](https://wiki.dendron.so/) titled `CONTIBUTING` points to this [URL](https://github.com/dendronhq/dendron/blob/master/docs/CONTRIBUTING.md)

This URL 404's

## To Reproduce

1. Go to https://wiki.dendron.so/
2. Click on `CONTIBUTING`
3. See error

## Expected behavior

go to `CONTIBUTING.md`

## Screenshots

![image](https://user-images.githubusercontent.com/29872822/147843971-83c5df97-b9b2-4480-a8d9-3de71d08958b.png)

## Desktop (please complete the following information)

N/A

## Additional context

N/A

## Dendron Log file

N/A

**Comment by Harshita-mindfire** [comment]
Thanks @tallguyjenks for the bug report. I can repro this one. 
Also, we manage our documentation issues/PR in [dendron-site](https://github.com/dendronhq/dendron-site) repository :) .
Adding @ScriptAutomate for FYI
