### ISSUE TITLE
Dendron's Fork of Markdown Preview Enhanced -- Allow Live Code Execution

### ISSUE THREAD

**Issue by tallguyjenks** [dendronhq/dendron#2028]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Not a problem per se but it would be nice to be able to use a single markdown previewer to show the code execution results from code blocks in the dendron previewer.

## Describe the solution you'd like ##

Because the dendron previewer also shows the backlinks and in general is more geared towards dendron's use it would be nice to combine the other features from the upstream extension into dendron's fork. 

In obsidian the Dataview plugin makes it easy to query your notes and their metadata and display tables of query results, i got some shells scripts setup to query data for particular notes and their metadata for when they were last edited which i can use in my monthly review notes, but having these code blocks executing automatically in the previewer as I'm reading the note would be an awesome addition.

## Describe alternatives you've considered ##

Toggling between the upstream extension and the dendron fork but its tedious, just running the VS Code task to put output into the terminal but its not as nice as an all in one

### dendron preview

![image](https://user-images.githubusercontent.com/29872822/147891272-4b6a8cea-7cf0-49c8-b777-18f5c54e6451.png)

### upstream preview

![image](https://user-images.githubusercontent.com/29872822/147891276-58c1ea15-6f2b-4f7e-a0b7-270bc79ef669.png)

### VSCode task

![image](https://user-images.githubusercontent.com/29872822/147891282-0669e1af-835f-4a33-b344-9951318f3584.png)

**Comment by Harshita-mindfire** [comment]
Thanks @tallguyjenks for the enhancement request.

**Comment by aleksey-rowan** [comment]
Hey, @tallguyjenks, Dendron is no longer using Markdown Preview Enhanced for Markdown rendering and switched over to its own rendering engine. If you would like to suggest adding live code execution to the new preview, please, open an new issue.
