### ISSUE TITLE
Unable to preview/delete notes, and see them in tree view or graph

### ISSUE THREAD

**Issue by NahomBefekadu** [dendronhq/dendron#2030]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

A file was created in the workspace that worked previously, you could find it in the tree. But after opening the workspace again, you'll find the the notes added previously do not show up in the tree/graph view and you are not able to preview your notes like the other notes in your workspace.

When tying to delete the problem file error pops up stating cannot read property as shown in screenshot.

## To Reproduce

1. Create a file from root
2. exit workspace
3. go back to workspace and check if created file shows up in preview or tree view.
4

## Expected behavior

For the files previously created to show up in note preview, tree view and graph view.

## Screenshots
![image](https://user-images.githubusercontent.com/58083518/147893576-1a0aaba8-f18a-4f0f-9901-c7517add191f.png)

![image](https://user-images.githubusercontent.com/58083518/147894156-996956c8-b9e4-48ad-ac7f-8becc677226d.png)

## Desktop (please complete the following information)

- OS: [Windows 11]
- Browser: [e.g. chrome ]
- Version: [e.g. 22]

## Additional context

I have not been able to reproduce this error again, so you might not be able to reproduce it as well, my workaround to this is to d recreate different files with different name and copy what i wrote over.

## Dendron Log file
[dendron.log](https://github.com/dendronhq/dendron/files/7800044/dendron.log)
Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Hello @NahomBefekadu, Thanks for reporting the issue. In Dendron, `root` note is a special note that comes with every Dendron vault.  It is used as the parent of all hierarchies. We don't advise that you create a hierarchy from it.
