### ISSUE TITLE
Import markdown from Obsidian <hr>'s and front matter issues

### ISSUE THREAD

**Issue by tallguyjenks** [dendronhq/dendron#2031]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [x] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When importing notes from obsidian the horizontal rules i have in the document which are valid markdown `---` are replaced by `* * *` which was not desired behavior.

Also after import the yaml front matter that was already in the note from obsidian was not elegantly dealt with.

## To Reproduce

follow the standard documented example for importing a markdown pod from obsidian. Did the exact steps Kevin walks through.

## Expected behavior

The document is recognized by dendron, gets a unique ID and is added to the Index and is, therefore, able to be used within Dendron, which does occur but all of the original YAML front matter is left in the document, it is neither deleted, kept, or overwritten, etc. its just kind of shoved down and retained and it means each document needs to be cleaned.

## Screenshots

![image](https://user-images.githubusercontent.com/29872822/147894556-94771e64-dbeb-45e0-b337-a9d41e73ecc8.png)

## Desktop (please complete the following information)

- OS: MacOS BigSur 11.6
- Browser: Brave
- Version: ??

## Additional context

there needs to be a better way of handling the imported YAML front matter, like if there are fields that match standard fields in dendron then keep those keys and values or convert the values to a format that dendron can use and then get info or an option in the import config file on what to do with the yaml that doesn't match, like for me i just wanted all the old yaml deleted.

## Dendron Log file

N/A

**Comment by Harshita-mindfire** [comment]
Thanks @tallguyjenks for reporting the issue.

Dendron currently overrides any YAML frontmatter with dendron's frontmatter(which falls under your current requirement), I was able to reproduce the case where the frontmatter data is shoved down. This is possible if in the original file the frontmatter is not wrapped in YAML like below. 

```yml
---
publish: true
aliases: 
created: 2021-12-12
updated: 2021-01-01
---
```
Could you please check if this solves your problem?
Also, there's another ongoing issue #2018 to import obsidian metadata.

**Comment by tallguyjenks** [comment]
my imported markdown file were wrapped in the standard `<hr>`'s for a yaml section but i noticed that the `created` and `updated` keys didn't have their values changed to the dendron datetime format from have i had which was ISO8601 format

**Comment by Harshita-mindfire** [comment]
Dendron does not support any existing YAML metadata on import, for now. Do you mind uploading the original markdown file(if there is no sensitive data in it), so that I can check what is wrong?

**Comment by tallguyjenks** [comment]
[asyncio.md](https://github.com/dendronhq/dendron/files/7803606/asyncio.md)
this is the original

**Comment by Harshita-mindfire** [comment]
I see, Thanks @tallguyjenks for sharing. In your file the top content is: 
```YAML
---
created: 2022-01-01 2158
updated: 2022-01-02 1659
---
💻️/Python/Library
publish: true
aliases:
created: 2021-12-21 1257
updated: 2022-01-01 2151
---
```
Keeping this as context, Dendron considers only the below metadata as Frontmatter and replaces it with Dendron's frontmatter. The rest of it is a plain string for dendron and it shoves it down accordingly.
```YAML
---
created: 2022-01-01 2158
updated: 2022-01-02 1659
---
```
Your issue coincides with two existing issues,
1. Importing metadata: issue #2018
2. Updating note body( hr `---` to `***` while parsing markdown): issue #1608 

Can we track it with those issues?

**Comment by tallguyjenks** [comment]
@Harshita-mindfire sounds good to me :)

**Comment by Harshita-mindfire** [comment]
Thanks! closing this one.
