### ISSUE TITLE
Include support for footnotes in dendron markdown previewer

### ISSUE THREAD

**Issue by tallguyjenks** [dendronhq/dendron#2033]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

problem is that footnotes are not supported in the dendron markdown previewer

## Describe the solution you'd like ##

work with the footnotes extension that already exists to allow footnote support in rendered markdown docs

## Describe alternatives you've considered ##

the external extension only works in default display

## Additional context ##

![image](https://user-images.githubusercontent.com/29872822/147898561-92673cd8-25dc-4b3f-8368-cb8108162ce6.png)

**Comment by Harshita-mindfire** [comment]
Thanks @tallguyjenks for the issue. Footnotes are supported in dendron preview :
```markdown
Content [^1]

[^1]: Hi! This is a footnote
```
Attaching an image for reference.
![image](https://user-images.githubusercontent.com/84971366/147955402-024bb7f8-dc02-4862-bc19-20fdd1d2e6d4.png)

**Comment by tallguyjenks** [comment]
ah okay, i think i just had the syntax wrong then, apologies and thank you!

**Comment by Binly42** [comment]
The jumping seems that not supported yet though...
