### ISSUE TITLE
Multi-vault - confirmVaultOnCreate not triggering vault selection when new note is created.

### ISSUE THREAD

**Issue by Chisomo-Chiweza** [dendronhq/dendron#2042]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [X] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Setting `confirmVaultOnCreate` to `true` does not trigger prompt to choose which vault to put note in when creating new note.

## To Reproduce

1. Open `dendron.yml` file in workspace (more visible in file system), or using the Command Palette select `Dendron: configure (yaml)`'
2. In file, scroll down to  commands and set `confirmVaultOnCreate:` to `true`
3. Reload VSCode and try to create new Dendron note
4. See how there is no prompt to choose the vault in which to store new note and if you continue to create the note, it is stored in the default vault. 

## Expected behavior

A prompt asking you which vault to store your new note in upon setting `confirmVaultOnCreate` to `true`.

## Screenshots

**This screenshot shows how my config has `confirmVaultOnCreate` set to `true`**

![Screenshot from 2022-01-04 20-36-39](https://user-images.githubusercontent.com/64413744/148107654-679519df-4d44-4a2e-9c24-5718178a283d.png)

**This one shows how creating a new note does not show any prompt as to where the new note should be**

![Screenshot from 2022-01-04 20-37-15](https://user-images.githubusercontent.com/64413744/148107673-66cfb125-5445-4774-a175-3177e549e8d6.png)

**This screenshot shows how the created note gets saved in the default vault `journal` rather than letting me choose to put it in the vault `engineering`**

![Screenshot from 2022-01-04 20-38-33](https://user-images.githubusercontent.com/64413744/148107712-e7ccad44-0e13-4f21-8d19-52af5c9ef1c6.png)

## Desktop (please complete the following information)

- OS: Ubuntu
- Browser: Brave Browser
- Version: Ubuntu version 21.10 Brave Browser version 96.1.33.106

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/7809649/dendron.log)

**Comment by Harshita-mindfire** [comment]
Thanks @Chisomo-Chiweza for reporting the bug. I can repro this one. We'll let you know when this is fixed.

**Comment by Chisomo-Chiweza** [comment]
Awesome

**Comment by JayAchar** [comment]
@Chisomo-Chiweza I had the same problem and saw this [response](https://github.com/dendronhq/dendron/issues/1570#issuecomment-949723773) in another open issue. Toggling the button in the look-up bar seemed to fix my problem albeit temporarily.

**Comment by Harshita-mindfire** [comment]
Hey @Chisomo-Chiweza, checking if this is still an issue?
