### ISSUE TITLE
Template variables creating single-digit numbers for day and month

### ISSUE THREAD

**Issue by tsnieman** [dendronhq/dendron#2045]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When using [the example provided on the template variables docs](https://wiki.dendron.so/notes/861cbdf8-102e-4633-9933-1f3d74df53d2/#template-variables), a date such as `2021.1.4` is produced rather than the documented `2021.01.04`

## To Reproduce

1. Create a template
2. Fill it with something like: `{{ CURRENT_YEAR }}.{{ CURRENT_MONTH }}.{{ CURRENT_DAY }}` (per the [aforementioned example](https://wiki.dendron.so/notes/861cbdf8-102e-4633-9933-1f3d74df53d2/#template-variables))
3. Use the template
4. Date is `2021.1.4`

## Expected behavior

I expect a two-digit day & month, (per the [aforementioned example](https://wiki.dendron.so/notes/861cbdf8-102e-4633-9933-1f3d74df53d2/#template-variables)):
```md
CURRENT_MONTH: The month as two digits (example '02')
CURRENT_DAY: The day of the month as two digits (example '08')
```

## Screenshots

![image](https://user-images.githubusercontent.com/595711/148147726-3273d575-d29a-4aa7-8f9a-ecb201072d75.png)

## Desktop (please complete the following information)

- OS: [e.g. iOS] ubuntu
- Browser: n/a
- Version: Dendron v0.76.0

## Additional context

n/a

## Dendron Log file

n/a

**Comment by kevinslin** [comment]
Thanks for the catch, we'll get on this right away!

**Comment by kevinslin** [comment]
this has been fixed. heads up that the template variable syntax has changed -> https://wiki.dendron.so/notes/GelEQPZrSgr3CK9y10Nrg.html#template-variable-replacement
