### ISSUE TITLE
Question about Seed that Keeps Getting Updated with Remote Content.

### ISSUE THREAD

**Issue by sahil48** [dendronhq/dendron#2073]
## Proposal

I was experimenting with the seed feature in Dendron. I saw that a seed was made for XKCD comics. Seeds like these would keep on updating. Is there any way for Dendron to keep fetching notes added to the seed from where it was downloaded and adding it. For example, what if a seed was an RSS feed? You would keep getting articles created for new links added, which you can reference from your knowledge base. Existing material downloaded should be editable as the user desires.

## Existing Open Source Material on the subject (if any)

N/A

**Comment by kevinslin** [comment]
Yeah - there is. We are currently focusing on the basic publishing experience and some workspace improvements. We have plans on updating seeds from source but will probably be middle of this year before that happens
