### ISSUE TITLE
Folder Seed

### ISSUE THREAD

**Issue by sahil48** [dendronhq/dendron#2078]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [X] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [X] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [X] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##
Making it easier to reference notes and attachments

## Describe the solution you'd like ##

Add seed for that monitors a folder on your computer. When a file is added, a note will be created for that file with same name as the file name with a link to that file. This way, when a file is added to the vault or an external folder, instead of having to copy and paste it, a note will already be available for it, which can be renamed and referenced like any other dendron file.

In the vault, it would also be nice to be able to have a setting when the name of the corresponding dendron file it was mapped to is renamed, the attachment is renamed with the same name. That way, when you view the vault folder from another application (ex. edit a word document in the vault with Microsoft Word) and sort the files by name, you can search for them similar to how you search your hierarchy in dendron.

## Describe alternatives you've considered ##

None

## Additional context ##

N/A.

**Comment by kevinslin** [comment]
We have an issue for that -> synchronization pods. see https://github.com/dendronhq/dendron/issues/732
no ETA for it yet but could you add any suggestions and feature requests there?

**Comment by sahil48** [comment]
Will do, thanks.
