### ISSUE TITLE
Different Prioritizations for Notes Presented in Lookup Search Results

### ISSUE THREAD

**Issue by sahil48** [dendronhq/dendron#2087]
## Please select if your request is either something new or an enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [X] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

My tendency is not to delete past notes I have taken. Eventually, they had run their course and utility or were incorrect ideas I had. Some notes may hold a greater importance now compared to other notes

## Describe the solution you'd like ##

Some metadata 0, 1, 2, 3 for ranking files in lookups and searches.

* 0 means delist the note from search
* 1 means rank lower in search results
* 2 means standard ranking
* 3 means rank higher in search results

## Describe alternatives you've considered ##

Remove the note from the tree, but not delete it from file system.
Include ranking in filename.

## Additional context ##

N/A

**Comment by kevinslin** [comment]
lookup ordering is not configurable at the moment and is fuzzy so setting a custom order would be brittle. for old notes, have you considered adding them to a new hierchy? for example, I will create multiple versions of files when I write: https://www.kevinslin.com/notes/BQ2AkZPAnTlAqeFC.html#multiple-versions

so in your case, it might look like the following
```
idea
idea.v1
idea.v2
...
```

**Comment by sahil48** [comment]
I Actually was thinking about that! I guess you **copy** the note to idea.v1 so that the backlinks don't get affected.

At the very least, I think a flag allowing notes to be excluded from the search, like v1 and v2 would be useful. Hopefully on-and-would not affect the fuzzy search.

**Comment by kevinslin** [comment]
i think search filter is a great idea. mind creating a new issue and related it to this one? then i'll close out this one.

if you copy the note, the `create date` will not be retained but you can manually replace the `updated` field in the frontmatter
