### ISSUE TITLE
Hover over Header to copy a link to that header in preview and published Notes

### ISSUE THREAD

**Issue by sahil48** [dendronhq/dendron#2088]
## Please select if your request is either something new or an enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [X] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [X] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I like to link to a section of a document very frequently. This is not so convenient when previewing documents

## Describe the solution you'd like ##

Many documentation sites make it easy to copy a link to a header. It's very handy!

https://docs.erpnext.com/docs/v13/user/manual/en/accounts

![image](https://user-images.githubusercontent.com/6100774/148571006-7ee7a610-b023-4530-a86f-4561fd698caa.png)

Another example:

https://codesavory.com/basepress/knowledge-base/features/single-or-multi-kb/

![image](https://user-images.githubusercontent.com/6100774/148576405-f98037be-368d-466b-993a-484447f48aeb.png)

## Describe alternatives you've considered ##

Highlight the text and click copy link to highlight in browsers like Microsoft Edge.

## Additional context ##

N/A

**Comment by kevinslin** [comment]
yep, we're planning on supporting this soon! currently being tracked in #314
