### ISSUE TITLE
Show Tags in the Tree View

### ISSUE THREAD

**Issue by sahil48** [dendronhq/dendron#2090]
## Please select if your request is either something new or an enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [X] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Tags are notes but do not show up in the tree view.

## Describe the solution you'd like ##

Since tags are notes, I would like them to show in the tree view and knowledge graph and lookups. Maintaining a separation makes it difficult to enhance ideas in notes added in the tag hierarchy. It would also be more obvious to new users that tags are shorthand for notes in the tag "namespace".

## Describe alternatives you've considered ##

N/A

## Additional context ##

N/A

**Comment by kevinslin** [comment]
tags should show up in the tree view. if not, that's a bug. do you have a screenshot of where its not showing up? sometimes you might have created tags in a separate vault and the tree view groups notes by vault

**Comment by sahil48** [comment]
Please see screenshot below. I used Dendron: Goto Note to create it. Until then, did not have any tags or tag hierarchy created in this vault.

![image](https://user-images.githubusercontent.com/6100774/148580837-d806e3bd-ccfc-435b-82b6-215e1345134c.png)

**Comment by kevinslin** [comment]
how did you create the tag? 

was it [[tags.foo]] and then go to note or `#foo` and then go to note?

**Comment by sahil48** [comment]
It was just `#foo` and then go to note.

**Comment by kevinslin** [comment]
got it. able to reproduce. we'll have someone take a look at this!
