### ISSUE TITLE
issue initializing Dendron when opening my local workspace

### ISSUE THREAD

**Issue by nukedbit** [dendronhq/dendron#2107]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When vs code open my workspace i get the following error message

issue initializing Dendron
{"line":1,"column":8,"vslsStack":[{},{},{},{},{},{},{}]}

## To Reproduce

1. on my workspace i just open vscode

## Expected behavior

No error message

## Desktop (please complete the following information)

- OS: MacOS m1
- Version: Monterey

## Dendron Log file

The above error can be seen on the last logs lines

    {"level":30,"time":1641759873160,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
    {"level":30,"time":1641759873222,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/Users/XXXXXX/Library/Application Support/Code/logs/20220109T210802/exthost1/dendron.dendron","extensionPath":"/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0","extensionUri":"/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0","workspaceFile":"/Users/XXXXXX/Dendron/dendron.code-workspace","workspaceFolders":["/Users/XXXXXX/Dendron/work-vault","/Users/XXXXXX/Dendron/mysecondbrain","/Users/XXXXXX/Dendron/vault"]}
    {"level":30,"time":1641759873222,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
    {"level":30,"time":1641759873222,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
    {"level":30,"time":1641759873222,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"telemetry initializing"}
    {"level":30,"time":1641759873222,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"using existing id"}
    {"level":30,"time":1641759873224,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
    {"level":30,"time":1641759873237,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.76.0","previousWorkspaceVersion":"0.76.0","previousGlobalVersion":"0.75.0","extensionInstallStatus":"UPGRADED"}
    {"level":30,"time":1641759873240,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
    {"level":30,"time":1641759873240,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
    {"level":30,"time":1641759873241,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"telemetry initializing"}
    {"level":30,"time":1641759873241,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"using existing id"}
    {"level":30,"time":1641759873241,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","msg":"Telemetry is disabled? false"}
    {"level":30,"time":1641759873241,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","msg":"Segment Residual Cache Path is at undefined"}
    {"level":30,"time":1641759873253,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
    {"level":30,"time":1641759873253,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"telemetry initializing"}
    {"level":30,"time":1641759873253,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"using existing id"}
    {"level":30,"time":1641759873253,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","msg":"Telemetry is disabled? false"}
    {"level":30,"time":1641759873254,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","msg":"Segment Residual Cache Path is at /Users/XXXXXX/Library/Application Support/Code/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
    {"level":30,"time":1641759873254,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
    {"level":30,"time":1641759873261,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"_activate","workspaceInstallStatus":"NO_CHANGE","currentVersion":"0.76.0","previousWorkspaceVersion":"0.76.0","previousGlobalVersion":"0.75.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"redhat.vscode-yaml","version":"1.2.2","active":false}],"vaults":[{"fsPath":"work-vault","remote":{"type":"git","url":"git@xxxxx:xxxx/work-vault.git"},"name":"work-vault"},{"fsPath":"mysecondbrain","remote":{"type":"git","url":"git@xxx:xxx/mysecondbrain.git"},"name":"mysecondbrain"}]}
    {"level":30,"time":1641759873263,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"execServer","state":"enter"}
    {"level":30,"time":1641759873264,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"execServer","state":"post:exec.node"}
    {"level":30,"time":1641759873616,"pid":19297,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
    {"level":30,"time":1641759873616,"pid":19297,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
    {"level":30,"time":1641759873616,"pid":19297,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"telemetry initializing"}
    {"level":30,"time":1641759873616,"pid":19297,"hostname":"XXXXXXs-MacBook-Pro.local","name":"SegmentClient","msg":"using existing id"}
    {"level":30,"time":1641759873631,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"execServer","state":"message","message":"53860"}
    {"level":30,"time":1641759873631,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":19297}
    {"level":30,"time":1641759873631,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"startServerProcess","msg":"post-start-server","port":53860,"durationStartServer":394}
    {"level":30,"time":1641759873634,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"logger","ctx":"FileStorageV2","wsRoot":"/Users/XXXXXX/Dendron","vaults":[{"fsPath":"work-vault","remote":{"type":"git","url":"git@xxxxxx:xxxxx/work-vault.git"},"name":"work-vault"},{"fsPath":"mysecondbrain","remote":{"type":"git","url":"git@git.xxxx.host:xxx/mysecondbrain.git"},"name":"mysecondbrain"}],"level":"info"}
    {"level":30,"time":1641759873635,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
    {"level":30,"time":1641759873635,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
    {"level":30,"time":1641759873836,"pid":19297,"hostname":"XXXXXXs-MacBook-Pro.local","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":"work-vault","remote":{"type":"git","url":"git@xxxxxx:xxxxx/work-vault.git"},"name":"work-vault"},"imports":[]}
    {"level":30,"time":1641759873837,"pid":19297,"hostname":"XXXXXXs-MacBook-Pro.local","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":"mysecondbrain","remote":{"type":"git","url":"git@xxxxxxx:xxxx/mysecondbrain.git"},"name":"mysecondbrain"},"imports":[]}
    {"level":30,"time":1641759873937,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":188}
    {"level":30,"time":1641759873937,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
    {"level":30,"time":1641759873937,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
    {"level":30,"time":1641759873938,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
    {"level":30,"time":1641759873939,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
    {"level":30,"time":1641759873940,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
    {"level":30,"time":1641759873940,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
    {"level":30,"time":1641759873941,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
    {"level":30,"time":1641759873941,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
    {"level":30,"time":1641759873942,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
    {"level":30,"time":1641759873943,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
    {"level":30,"time":1641759873945,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
    {"level":30,"time":1641759873947,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"togglePluginActiveContext","state":"togglePluginActiveContext: true"}
    {"level":30,"time":1641759873947,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":706}
    {"level":50,"time":1641759873950,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","line":1,"column":8,"vslsStack":[{},{},{},{},{},{},{}],"stack":"SyntaxError: Unexpected end of JSON input\n\tat j (/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0/dist/extension.js:8:232774)\n\tat H (/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0/dist/extension.js:8:232965)\n\tat J (/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0/dist/extension.js:8:233457)\n\tat parse (/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0/dist/extension.js:8:234134)\n\tat t.readJSONWithCommentsSync (/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0/dist/extension.js:2:167962)\n\tat Function.checkAndMigrateLookupKeybindingIfExists (/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0/dist/extension.js:8:3216206)\n\tat Fi (/Users/XXXXXX/.vscode/extensions/dendron.dendron-0.76.0/dist/extension.js:8:3350551)","type":"Error","msg":"Unexpected end of JSON input"}
    {"level":50,"time":1641759873951,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"showInitProgress","msg":"issue initializing Dendron"}
    {"level":30,"time":1641759874110,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
    {"level":30,"time":1641759874111,"pid":19264,"hostname":"XXXXXXs-MacBook-Pro.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}

**Comment by kevinslin** [comment]
This looks like your workspace file has badly formatted json. can you confirm whether the json in your `dendron.code-workspace` is formatted correctly?

**Comment by greglamb** [comment]
In case anyone else encounters this issue, I resolved it by removing ~/Library/Application Support/Code/User/keybindings.json which only contained "// Empty"
