### ISSUE TITLE
dendron publish export --noBuild hangs indefinitely after completing export

### ISSUE THREAD

**Issue by LukeCarrier** [dendronhq/dendron#2108]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

`dendron publish export --noBuild` seems to hang indefinitely after completing the export -- the spinner keeps on spinning:

```console
$ npx dendron publish export --noBuild
[snipping lots of normal output]
⠋ info  - using build directory: /Users/lukecarrier/Code/lukecarrier/brain/.next/.next
⠹ info  - Copying "static build" directory
info  - No "exportPathMap" found in "/Users/lukecarrier/Code/lukecarrier/brain/.next/next.config.js". Generating map from "./pages"
info  - Launching 7 workers
info  - Exporting (0/2)
info  - Copying "public" directory
⠋ info  - Exporting (2/2)
⠸ Export successful. Files written to /Users/lukecarrier/Code/lukecarrier/brain/.next/out
⠴ 
⠙ 
⠧ 
⠹ 
⠹ ^C⏎
```

Omitting the `--noBuild` option works. Is this as simple as moving the `spinner.stop()` call out of the `else` branch?

Discovered during testing of dendronhq/dendron-site#352.

## To Reproduce

1. Run `npx dendron publish init`
2. Run `npx dendron publish export --noBuild`, and observe that it never completes
3. Run `dendron publish export` and confirm it does complete 

## Expected behavior

`--noBuild` should terminate successfully.

## Screenshots

N/A

## Desktop (please complete the following information)

- OS: macOS 12.1
- Browser: N/A
- Version: N/A

## Additional context

N/A

## Dendron Log file

N/A

**Comment by kevinslin** [comment]
Thanks for the catch! This is fixed in https://github.com/dendronhq/dendron/pull/2109 and will be shipped this tuesday!
