### ISSUE TITLE
If you embed a note link into itself you create an endless loop and hang preview

### ISSUE THREAD

**Issue by ghost** [dendronhq/dendron#2126]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

If you embed a note link into itself you create an endless loop and hang preview

## To Reproduce

@kevins8: (I know the issue so you don’t need detailed repro steps)

## Expected behavior

It should be prevented

## Screenshots

none

## Desktop (please complete the following information)

- OS: Chrome OS
- Browser: chrome
- Version: 97

## Additional context

none

**Comment by kevinslin** [comment]
yep, this is a bug. thanks for reporting!

**Comment by aleksey-rowan** [comment]
Hey, @rzd-test, the nesting of references is limited to 3 now and it shouldn't crash the preview anymore. Could you please check if you still encounter this issue in the latest version of Dendron?

**Comment by bitdryvr** [comment]
How do I make sure that I am using the correct version of Dendron?

**Comment by bitdryvr** [comment]
bitdryvr is the new name for rzd-test
