### ISSUE TITLE
Search result link jumps to top of page

### ISSUE THREAD

**Issue by HopperTech** [dendronhq/dendron#2144]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I have several longer notes. I have noticed that when that note is not open and I click on the search results, or use the open definitions feature, the cursor will jump to the top of the page.  If the note is already open then the clicking on the results link will take me to the found line in the note. 

## To Reproduce

1. Create a longer (>30 lines) note with some search term towards the bottom of the note
2. Search for the term 
3. Click on the resulting link. - This will work as expected, staying on the found line
4. Reload the window 
5. Search for the term again
6. Click on the resulting link - The cursor will be at the top of the note just under the frontmatter

Note: Reloading does not always immediately cause the issue, but once the issue begins on a note it is consistent from that point on. I was also able to reproduce this issue by copying and pasting the same text into a new note. At first the search link works correctly, but eventually the issue occurs. I have not been able to identify a trigger for when the issue begins.

## Expected behavior

When clicking on a search result, or using the open definition function, the new window should stay on the found line.

## Desktop (please complete the following information)

- OS: [e.g. iOS] Windows
- Browser: [e.g. chrome, safari] VSCode 1.63.2
- Dendron Version: [e.g. 22]   0.77.1

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/7855972/dendron.log)

**Comment by SeriousBug** [comment]
Thanks for reporting this issue, I can reproduce it.

**Comment by HopperTech** [comment]
Tested and works as expected.  Thank you
