### ISSUE TITLE
Tag at end of sentence in parentheses gets ")" as part of the tag

### ISSUE THREAD

**Issue by viddo** [dendronhq/dendron#2148]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When writing a sentence and a tag and adding a ")" to end sentence with parentheses it becomes part of the tag.

## To Reproduce

1. Write a sentence like `this (with parentheses and a tag #example)` 

## Expected behavior

`#example` should be converted to a link to the tag, without the additional ")".

## Desktop (please complete the following information)

- OS: Mac OS Monterey version 12.1 (latest at time of writing)
- VSCode version: Version: 1.64.0-insider
- Dendron version: v0.77.1

**Comment by SeriousBug** [comment]
Thanks for reporting the issue! Since you mentioned interest in fixing this, I'll give you a bit of time to attempt a fix. Otherwise we'll pick the issue up whenever possible.

**Comment by rlh1994** [comment]
The interesting thing with this issue I've just found is it's inconsistent in punctuation - for example it captures `#todo)` as a full tag, but `#todo?` it only capture the `todo` part of as the tag name. 

| Symbol | Added to tag?                      |
|--------|------------------------------------|
| `      | N                                  |
| ¬      | Y                                  |
| !      | N                                  |
| "      | N                                  |
| £      | Y                                  |
| $      | Y                                  |
| %      | Y                                  |
| ^      | Y                                  |
| &      | Y                                  |
| *      | Y                                  |
| (      | Y                                  |
| )      | Y                                  |
| -      | Y (expected)                       |
| _      | Y (expected)                       |
| +      | Y                                  |
| =      | Y                                  |
| {      | Y                                  |
| }      | Y                                  |
| [      | N                                  |
| ]      | N                                  |
| @      | N                                  |
| '       | N                                  |
| ;      | N                                  |
| :      | N                                  |
| #      | N                                  |
| ~      | N                                  |
| \      | Y                                  |
| (vertical pipe)      | N                                  |
| <      | N                                  |
| >      | N                                  |
| ,      | N                                  |
| .      | Y (only with text after, expected) |
| ?      | N                                  |
| /      | Y                                  |

**Comment by viddo** [comment]
@rlh1994 Yeah, that's controlled by a regexp check of punctuation marks. See: https://github.com/dendronhq/dendron/blob/9d9579cdab773131a5c8e0b1d6e130262d6a8164/packages/engine-server/src/markdown/remark/hashtag.ts#L21 

BTW, I have put up  #2182 to fix `()` specifically.
