### ISSUE TITLE
Mobile Logo Issue

### ISSUE THREAD

**Issue by aglucky** [dendronhq/dendron#2159]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Title text on mobile version of published site is messed up when there's not a logo

## To Reproduce
Publish site with github actions guide without a logo and view on mobile

## Expected behavior

Title text should e on one line in title bar
## Screenshots

![image](https://user-images.githubusercontent.com/37425558/149384065-4c5298ff-6bf8-4a45-ad29-6b883cdab759.png)
## Desktop (please complete the following information)

- OS: [ iOS]
- Browser: [safari, brave]
- Version: [idk]

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment]
Thanks for the bug report, I can reproduce the issue. We'll pick this up as soon as we can.

**Comment by ScriptAutomate** [comment]
More info - I can confirm that this seems to happen on mobile rendering of sites that aren't using a logo. Examples:
- https://wiki.dendron.so/ (uses logo, renders as expected)
- https://blog.dendron.so/ (doesn't use a logo, has similar rendering issue)
