### ISSUE TITLE
Ctrl+Shift word select is broken on Win 10

### ISSUE THREAD

**Issue by GalaticRailroad** [dendronhq/dendron#216]
Trying to use the ctrl+shift combination on Win10 is broken.  The message "Cannot read property 'length' of undefined" keeps coming up and the cursor doesn't move and nothing is selected.

**To Reproduce**
1. Type a sentence.
2. Try to select text using ctrl+shift.

**Expected behavior**
I should be able to select text using this method as sometimes I want to select subsentences quickly.

**Screenshots**
![image](https://user-images.githubusercontent.com/3080407/93685505-be9f3580-fa64-11ea-93cd-9b240b86ddf9.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Visual Studio Code
 - Version 1.29.1

**Additional context**

** Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by Emaro** [comment]
For me the `Ctrl + Shift` is broken as well (Windows 10), but I don't get the warning. Instead, it switches between open editors. Would prefere the native behaviour though.

**Comment by kevinslin** [comment]
if you go into the keybindings, can you paste a screenshot of what is using that shortcut right now?  https://dendron.so/notes/c8e99b84-8a5a-42d3-838d-3d5cdebf32e5.html

**Comment by kevinslin** [comment]
Ping if they are any updates on this?

**Comment by GalaticRailroad** [comment]
![image](https://user-images.githubusercontent.com/3080407/94096863-019d3800-fdda-11ea-972e-d8d015de6057.png)
There is nothing in the file, there are no keybinds set for ctrl + shift in the VSCode settings.

**Comment by Emaro** [comment]
I do not have custom shortcuts set either, but dendron overwrites the default shortcuts:

![image](https://user-images.githubusercontent.com/25137789/94809752-58ff6180-03f3-11eb-9cbe-8c7bec2b68f7.png)

**Comment by kevinslin** [comment]
Update on this (and apologies for the long delay). I think this is the case of the [sibling navigation command](https://dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#go-next-sibling) overriding the builtin shortcut in windows. We'll be updating the defaults but in the meanwhile, you can follow the instructions [here](https://dendron.so/notes/c8e99b84-8a5a-42d3-838d-3d5cdebf32e5.html#add-reset-and-remove) to remove the shortcuts

**Comment by kevinslin** [comment]
This has been fixed in 0.19
