### ISSUE TITLE
logo url doesn't take `assetsPrefix` into account

### ISSUE THREAD

**Issue by invakid404** [dendronhq/dendron#2161]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Basically the title. If `assetsPrefix` is not /, logo URL must have that prefix as well, but it doesn't.

## To Reproduce

1. Publish your Dendron notes somewhere, where the path will be something different from / (e.g. GitHub pages in a repo with a name, which doesn't match the default domain).
2. Set `site.logo` in `dendron.yml`.
3. Logo is missing, due to the URL incorrectly ignoring the `assetsPrefix` value.

## Expected behavior

The `assetsPrefix` value must be appended to the `logoUrl`.

## Screenshots

![image](https://user-images.githubusercontent.com/38114607/149396315-27e41c99-f38c-4864-ac45-5d27a463cf0e.png)

## Desktop (please complete the following information)

- OS: Funtoo Linux 1.4
- Browser: Vivaldi 5.0.2497.35
- Version: Dendron 0.76.0

## Additional context

N/A

## Dendron Log file

N/A

**Comment by SeriousBug** [comment]
Thanks for the bug report, we'll try to fix this ASAP.

**Comment by SeriousBug** [comment]
This issue has now been fixed with Dendron 0.79. Please let us know if you continue to have problems, otherwise this issue will automatically close in a few days.

**Comment by invakid404** [comment]
@SeriousBug I can confirm it works now.
