### ISSUE TITLE
Error initializing dendron: {}

### ISSUE THREAD

**Issue by Emaro** [dendronhq/dendron#217]
**Describe the bug**
When I open the dendron workspace, three notifications pop up:

> Dendron is active

> error initializing dendron: {}

> {"ctx":"query","err":"{\"message\":\"gray-matter engine \\\"id: d40cc1b3-e716-4049-bb9e-493a15887bdf\\\" is not registered\",\"stack\":\"Error: gray-matter engine \\\"id: d40cc1b3-e716-4049-bb9e-493a15887bdf\\\" is not registered\\n\\tat e.exports (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:80840)\\n\\tat e.exports (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:302:1068)\\n\\tat c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:16864\\n\\tat Object.h [as default] (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:17124)\\n\\tat Object.t.mdFile2NodeProps (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:29903)\\n\\tat t.FileParser.toNode (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:60523)\\n\\tat c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:61933\\n\\tat Array.map (<anonymous>)\\n\\tat t.FileParser.parse (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:61849)\\n\\tat l.files2Notes (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:56668)\\n\\tat l._getNoteAll (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:57085)\\n\\tat l.query (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:57975)\\n\\tat h.query (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:52612)\\n\\tat h.init (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:50015)\\n\\tat processTicksAndRejections (internal/process/task_queues.js:94:5)\\n\\tat async o.execute (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:77729)\\n\\tat async c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:11:80760\\n\\tat async K.reloadWorkspace (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:11:86486)\"}"}

The dendron tree view stays empty and the lookup command only suggests creating a new note, ignoring any existing notes.

I tested version 0.11.4, 0.11.5 and 0.11.9, the issue is present in all of those. I created the dendron workspace yesterday without any issues.

**To Reproduce**
1. Open the dendron workspace.

**Expected behavior**
Only a notification that dendron is active and all baisc features working.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version
   - VS Code: 1.49.1
   - Dendron: 0.11.9

**Dendron Log file**
```
{"level":50,"time":1600595791602,"pid":8688,"hostname":"User-PC","name":"dendron","ctx":"query","err":"{\"message\":\"gray-matter engine \\\"id: d40cc1b3-e716-4049-bb9e-493a15887bdf\\\" is not registered\",\"stack\":\"Error: gray-matter engine \\\"id: d40cc1b3-e716-4049-bb9e-493a15887bdf\\\" is not registered\\n\\tat e.exports (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:80840)\\n\\tat e.exports (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:302:1068)\\n\\tat c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:16864\\n\\tat Object.h [as default] (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:17124)\\n\\tat Object.t.mdFile2NodeProps (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:29903)\\n\\tat t.FileParser.toNode (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:60523)\\n\\tat c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:61933\\n\\tat Array.map (<anonymous>)\\n\\tat t.FileParser.parse (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:61849)\\n\\tat l.files2Notes (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:56668)\\n\\tat l._getNoteAll (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:57085)\\n\\tat l.query (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:57975)\\n\\tat h.query (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:52612)\\n\\tat h.init (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:283:50015)\\n\\tat processTicksAndRejections (internal/process/task_queues.js:94:5)\\n\\tat async o.execute (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:17:77729)\\n\\tat async c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:11:80760\\n\\tat async K.reloadWorkspace (c:\\\\Users\\\\User\\\\.vscode\\\\extensions\\\\dendron.dendron-0.11.4\\\\dist\\\\extension.js:11:86486)\"}"}
```

**Comment by kevinslin** [comment]
can you find the note with the following id using vscode regular search? d40cc1b3-e716-4049-bb9e-493a15887bdf

this error appears because the frontmatter of that note is invalid.

**Comment by Emaro** [comment]
It seems like this file is missing (do I interpret correctly that there should be a file with ` d40cc1b3-e716-4049-bb9e-493a15887bdf` in the name?). Should I reinitialize the workspace? And if I'd do so, can I do that in the current directory or would my existing notes be deleted?

**Comment by kevinslin** [comment]
This error is saying that a file with the id of `d40cc1b3-e716-4049-bb9e-493a15887bdf` has bad frontmatter. you can fix this by opening the file and either fixing it or deleting it. another solution is to initialize a new workspace on a new path

**Comment by Emaro** [comment]
Oh, I could fix the file. I think it would be good, if dendron does not break from one incorrect markdown file.

Anyway, thanks for your help and your work to make note taking better!
