### ISSUE TITLE
Image relative path changed when publish

### ISSUE THREAD

**Issue by tuubui811812** [dendronhq/dendron#2174]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Images relative path was "assets/images/myimage.png" or "./assets/images/myimage.png" are displaying fine.

But the site published, azure static apps in my case, the images location moved 1 level up so the relative path should changed to "../assets/images/myimage.png" to work.

I think this's because of the publish site structure:
/site
/site/assets
/site/assets/images => images here
/site/notes              => markdown file here

## To Reproduce

1. Create markdown with image relative path (1) to "assets/images/<any_image>" and another image with relative path (2) to "../assets/images/<any_image>"
2. In locally, image with relative path (1) was fine, path (2) was crashed.
3. Publish site
4. Browse published site
5. The images with relative path (1) was crashed, path (2) was fine.

## Expected behavior

Images should displayed for locally and published site as well.
The second relative path, which is the "assets" folder at the same level with vault folders may be better, because when we have many vaults the "assets" folders are merged on publishing as well.

**Comment by SeriousBug** [comment]
Could you make sure that the `assetsPrefix` is set in `dendron.yml`? I think in your case it should be set to `/site`. I can also help diagnose the issue if you can share more about your workspace.

Relevant docs: https://wiki.dendron.so/notes/5ca2fe99-0abc-413d-aa06-50f9a66e13e0/#my-image-isnt-showing-up

**Comment by tuubui811812** [comment]
> Could you make sure that the `assetsPrefix` is set in `dendron.yml`? I think in your case it should be set to `/site`. I can also help diagnose the issue if you can share more about your workspace.
> 
> Relevant docs: https://wiki.dendron.so/notes/5ca2fe99-0abc-413d-aa06-50f9a66e13e0/#my-image-isnt-showing-up

I can now publish to azure static apps with the option `assetsPrefix` set in `dendron.yml`.
```
site:
    siteUrl: <static web app URL>
    copyAssets: true
    assetsPrefix: ../
```

Thanks to @SeriousBug
