### ISSUE TITLE
numbering with no text are squashed together in the preview

### ISSUE THREAD

**Issue by imalightbulb** [dendronhq/dendron#2178]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

numbering with no text are squashed together in the preview

## To Reproduce

1. create a number list with no text

## Screenshots

For example, the following markdown text:
```md
### Amazing things that happened today

1.
2.
3.
```

becomes this:
![image](https://user-images.githubusercontent.com/66677431/149612981-b48c11f4-d8b1-4276-84b2-441ac416bf3c.png)

## Desktop (please complete the following information)

- OS: Arch Linux 
- Browser: Brave
- Version: 0.77.1

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment]
Thanks for the report, we'll try to fix this soon.

**Comment by SeriousBug** [comment]
Hi, this has been fixed with Dendron 0.80. Please let us know if it continues to happen, otherwise this issue will close in a few days.
