### ISSUE TITLE
Adding Unlinked References to the Backlinks Tab similarTo Obsidian and Roam

### ISSUE THREAD

**Issue by peanutputter** [dendronhq/dendron#219]
As I understand, you use the Search function to find unlinked references to a word/phrase within a note.  Since there is a backlinks tab, is there a roadmap to see unlinked references to a note that may be a tag/keyword title like Obsidian and Roam?

Kevin suggested I add to new feature suggestion.  Thanks

**Comment by kevinslin** [comment]
Thanks for the feature request. Currently blocked by issue 234 so we're probably looking at an end of october/september ship date for this

**Comment by imalightbulb** [comment]
Was about to propose a feature request and yes I think this is a great feature to include in dendron.
Maybe we can make it in the sidebar like the current "backlinks" section? 
and what it does is continuing scanning file names (or titles) and see those who have not link to the file you're working on

**Comment by hikchoi** [comment]
This has been implemented and shipped with v51.
