### ISSUE TITLE
Scratch keyboard shortcut conflicts with defaults

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2200]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings

## Describe the bug

The keybinding for creating a scratch note is cmd+shift+s which [is also the default for save-as](https://github.com/codebling/vs-code-default-keybindings/blob/d6873157d1a5076c9d347df28e479ddf77e74b46/macos.keybindings.json#L1012).

This means the keybinding doesn't work on dendron install (at least on macOS).

**Comment by SeriousBug** [comment]
Thanks for adding the report.

@hikchoi Would it be possible to add a migration for keyboard shortcuts where we change the scratch note shortcut if the user:
- hasn't remapped it to another shortcut already
- hasn't remapped the default "save as" shortcut already
If the user has done neither, then this shortcut is basically unusable and I think it would be safe to remap the shortcut then. If that's hard/impossible, we can also just document this issue in the wiki.

**Comment by hikchoi** [comment]
The default keybinding for `Create Scratch Note` has been changed to avoid conflict with `Save as`.

Please see the [changelog](https://wiki.dendron.so/notes/50kdbcwwda3gphjhccb0e5t/#2022-09-13) for more.
Let us know if you have have any pending concerns regarding this issue.
