### ISSUE TITLE
Move note leads to broken images

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2202]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings

## Describe the bug

If a note is moved between vaults, any images in the note are not moved, and their link is not updated, so they do not work after the note has been moved, they show in the preview as a broken image link.

## To Reproduce

1. Create a note
2. Paste an image into it (or add an image any way you like)
3. Move the note to a new vault
4. Show the preview
5. Note that the image does not appear

## Expected behavior

You expect to see the image. Either by the image being moved between vaults (more complicated) or by the note being updated so that its asset url points to the original vault.

## Context

Edit: A cross vault link doesn't work for an image like `dendron://vault-name/assets/images/...` but a relative link does work in my preview:

    ![](dendron://../../vault-name/assets/images/2022-01-18-17-38-07.png)

**Comment by SR--** [comment]
Maybe provide an option to copy, move or update links for all and/or each asset?

**Comment by SeriousBug** [comment]
I believe publishing merges all images into the same folder. If that's correct, I think the preview should replicate the same behavior by looking for the image in all vaults.

For Dendron Team: we already have some code to do exactly this, check the Goto Note code or message me if you need help locating it.

**Comment by SR--** [comment]
This presumes that all vaults are there in one workspace. But you can have a workspace with only one vault. For example, because this is the advised way to publish a single vault. Or for other reasons. I think it should be possible to manage where the assests are flexibly.

**Comment by chmac** [comment]
Following up on what @SR-- said, I have multiple vaults and they're used in different contexts. Each one is a separate git repository. The dendron magic urls are cool, but they won't work in other contexts. I expect to use my vaults to run all kinds of other tools against, be that outside-of-dendron publishing, web based task management UI, etc. So personally, the cross vault stuff isn't a good solution for me. In fact, it would be a terrible solution as it would make it appear like images "work" when from my perspective they are actually "broken".

The copying / moving assets would be great. I guess it's a little complex to figure out if the asset is used in multiple locations, etc, but I guess dendron already does this kind of interconnected refactoring already, so hopefully it's not too big an issue.

**Comment by SeriousBug** [comment]
Related to #525

**Comment by aleksey-rowan** [comment]
> Related to #525

I think #525 is an exact duplicate and we should close one if favour of the other.

**Comment by aleksey-rowan** [comment]
Hi, @chmac, I'm going to close this one as a duplicate in favour of #525. If you think that any parts of the discussion here are relevant and should be preserved, please, repost them under the linked issue.
