### ISSUE TITLE
Dendron Tree View changes sort after note rename

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2209]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After renaming a note, the sort order of stubs in the Dendron Tree View changes. The move from the bottom of the list to being sorted in the list along with the rest of the domains.

## To Reproduce

1. Create a note hierarchy including multiple stubs
  - You need to have stubs and notes as a child of a top level domain
  - eg: `a.a.md`, `a.b.md`, `a.c.a.md`, `a.c.b.md`, `a.c.c.md`, `a.d.md`, `a.e.a.md`, `a.e.b.md`, `a.f.md`, `a.g.md`
1. Open the Dendron Tree View, observe the sort order
  - `a.c` and `a.e` should appear at the bottom of the list
1. Rename a note with the command "Dendron: Rename Note"
  - Change the note's hierarchy, eg rename `a.g.md` above to `a.c.g.md`
1. Wait for the tree view to update, note the sort order
  - `a.c` will now be between `a.b` and `a.d`, etc

## Expected behavior

Sort order should be consistent.

## Screenshots

See comments for screenshots.

**Comment by chmac** [comment]
@hikchoi Yes, the "Dendron Tree View", although in my UI it's only called "Tree View", while I see in that link that it's called "Dendron Tree View"...

<img width="271" alt="Screenshot 2022-01-19 at 18 15 01" src="https://user-images.githubusercontent.com/690997/150180949-d957ed86-115d-4c54-a61a-6e4093d2f206.png">

Also note that my "tags" are not positioned first as per your point 1.

The behaviour I saw was that the sort order would change. Okay, it just happened again, so now I can post a screenshot. I hope you can see what's going on in the screenshot. I blanked out the names, leaving the first letters so you can see the sort order. What you see in the lower half of the screenshot are all stubs. They are all at the very bottom of the tree. Maybe that's because their frontmatter `title` is `undefined`? But at other times I've seen them sorted in alphabetical order, so even though `Foo` is a stub, it still shows after E and before G. I can't get it to switch at the moment, so I can't post a screenshot of the other behaviour right now, but I'll keep an eye on it and post a screenshot when I see it again.

<img width="276" alt="Screenshot 2022-01-19 at 18 17 28" src="https://user-images.githubusercontent.com/690997/150181323-93f604d8-7b95-437b-b2a8-4f5c0241154e.png">

**Comment by chmac** [comment]
Aha, I figured it out. After I rename a note, now the sort order is different. Here's another screenshot.

<img width="94" alt="Screenshot 2022-01-19 at 18 23 12" src="https://user-images.githubusercontent.com/690997/150182413-626ed92b-d729-441b-905c-6a6036e5ebe2.png">

I will change the issue title and update the description now.

**Comment by hikchoi** [comment]
Thank you for the prompt response! I can't reliably reproduce this myself, but it definitely doesn't seem to be working as intended.

@SeriousBug I noticed you have recently worked on the sorting issue in the tree view. Could you take a look?

**Comment by chmac** [comment]
It could be related to moving notes into new hierarchies. I've been doing that a lot recently having just imported all my notes. I'm filing stuff away all the time. I'm not 100% sure, I'll try to investigate further, but that's my suspicion right now.

**Comment by hikchoi** [comment]
Hey @chmac 

We fixed various issues with the tree view recently and I can't seem to reproduce the sort order inconsistencies in the tree view now. Could you try it out again and let us know if you still have outstanding issues?

**Comment by chmac** [comment]
Thanks for the update, I'm happy that the issue has been resolved, if I find it again or other related issues I'll open a new ticket. 👍
