### ISSUE TITLE
Lookup suggestion tab completion

### ISSUE THREAD

**Issue by adrianduke** [dendronhq/dendron#221]
**Is your feature request related to a problem? Please describe.**
When I want to add a new entry to an existing schema using lookup, typing out the full schema boilerplate whilst it's being suggested is an unoptimised experience. E.g. `projects.github.people.dwaynejohnson` - `projects`, `github` and `people` are all known ahead of time, I only want to fill out `dwaynejohnson`. Lookup is suggesting `projects` when I type `pro`, `github` when I type `projects.gi` and `people` when I type `projects.github.p`.

**Describe the solution you'd like**
Tab completing the autosuggest entries, e.g. `pro<Tab>gi<Tab>p<Tab>dwaynejohnson` to enter `projects.github.people.dwaynejohnson` using the top suggestion at each <Tab> point would suffice.

**Describe alternatives you've considered**
No alternatives considered.

**Comment by kevinslin** [comment]
Thanks for the feature request.

Currently, vscode doesn't allow us to do tab complete inside the quickinput widget. We're exploring alternative ways to get around this by either using a custom editor view or webview to do queries moving forward. We're currently in the middle of our LSP migration (see issue 234) which is taking most of the bandwidth. We'll probably be looking to implement this around end of October/September.

**Comment by nkamath** [comment]
Looks the same as #490

**Comment by kpathakota** [comment]
Yep, closing.
