### ISSUE TITLE
Bug: Tree View contains out of date hierarchy

### ISSUE THREAD

**Issue by KevinCaseiras** [dendronhq/dendron#224]
**Describe the bug**
Minor bug, but was causing me some confusion as a new user.

When deleting the only/last note in a hierarchy, the hierarchy is still displayed in the Dendron Tree View even though there are no notes in it. The hierarchy will be removed when I restart VS Code.

**To Reproduce**
1. Create a brand new nested hierarchy that you don't have any notes under. i.e. `foo.bar.foobar`.
2. Delete `foo.bar.foobar` by executing the `Dendron: Delete Note` command.

Notice that the `foo.bar` hierarchy still exists in the Tree View even though there are no files in it. Also `foo.bar.md` does not exist, and `foo.md` does not exist.

**Expected behavior**
The entire `foo` hierarchy should be removed from the Tree View. This does happen, but only once I restart VS Code.

**Desktop**
Version: v0.12.0

**Comment by kevinslin** [comment]
Thanks for the bug report. We currently leave notes as a stub after you delete it meaning it stays inside the hierarchy even if its not in the files. This will be fixed for the next patch release early next week

**Comment by kpathakota** [comment]
Confirmed this no longer repros. Closing
