### ISSUE TITLE
Links in Note Preview add a ".html" to the link when clicked

### ISSUE THREAD

**Issue by alejoar** [dendronhq/dendron#2243]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

If a note contains a link like so:
```
[[Google|https://www.google.com]]
```

Clicking the link on the note preview will attempt to open `https://www.google.com.html/` in the browser.

## To Reproduce

1. Create new note with the following content: `[[Google|https://www.google.com]]`
2. Open the note preview and click on the link

## Expected behavior

Clicking on the link opens the correct URL.

## Desktop (please complete the following information)

- OS: macOS Monterey 12.1
- Browser: Chrome 97.0.4692.71
- Version: v0.78.0

**Comment by hikchoi** [comment]
Thank you for the report

The wikilink syntax is intended for notes within the workspace, not external links. If you wish to write a link to an external url, you should be using the standard markdown link.

i.e. `[Google](https://www.google.com)`

This does raise a point on checking for a url-like string inside a wikilink and giving the users a proper warning message.

Let me know if you have other reasons for not using the standard markdown link syntax. If you wish, you could also amend this issue to give a proper warning about the wikilinks usage so we could track it as an item.

This issue will automatically close in 4 days if there are no further comments.

**Comment by alejoar** [comment]
Thank you for the clarification.

Closing this since it is not necessarily a bug.
