### ISSUE TITLE
Automatically change Title: header when using Dendron: Rename Note to mirror new filename

### ISSUE THREAD

**Issue by oolonek** [dendronhq/dendron#225]
**Is your feature request related to a problem? Please describe.**

I was expecting that the Title: header would change automatically when using the Dendron : Rename File function

**Describe the solution you'd like**

Title: header mirrors by default the dendron note Filename (the lowest hierarchy).
Eventually let the possibility to have a Title different from the lowest hierarchy filename, but this should be achieved by changing the Title: field in the header manually, not the other way round.

**Describe alternatives you've considered**

Renaming by hand

**Comment by kevinslin** [comment]
Thanks for the feature request. The way we'll implement this is probably with a dropdown when you select the rename/refactor command. This is because some people use custom titles for names that differ from the filename so this would overwrite that.

**Comment by konrad-jamrozik** [comment]
Just adding my +1 to this feature request :)

**Comment by kevinslin** [comment]
This has just been released in the 0.17 update :)
