### ISSUE TITLE
Fix links to a note when renaming from the Code workspace's context menu

### ISSUE THREAD

**Issue by LukeCarrier** [dendronhq/dendron#2255]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When renaming note files via the Workspace pane's context menu (right click on a filename), Dendron doesn't rewrite links to the renamed note as it would if the "Rename Note" command were used.

This feels like a stumbling block that will confuse users new to Dendron and who know their way around Visual Studio Code.

## Describe the solution you'd like ##

Is it possible for us to somehow observe the file rename and rewrite links in the same way we do in "Rename Note"?

## Describe alternatives you've considered ##

- Warning users about it during the tutorial.
- Disabling the rename action in the context menu for Dendron notes.

## Additional context ##

Originally raised by seadude#7058 [in Discord](https://discord.com/channels/717965437182410783/735365126227493004/934156150847447071)

**Comment by hikchoi** [comment]
> Disabling the rename action in the context menu for Dendron notes.

I believe it is not possible to hide VSCode's built in commands in the context menu, but we can contribute a context menu item that will grab the file name and use it as if the user triggered `Dendron: Rename Note`.

We could also possibly watch the rename operation and run the necessary updates.

Pinging @Harshita-mindfire for contextual UI improvements.

**Comment by Harshita-mindfire** [comment]
Previously we had a `Dendron: Rename Note` in the Workspace pane's context menu (right-click on a filename) but now we support renaming the references of the file on vscode built-in rename. See [discord comment](https://discord.com/channels/717965437182410783/735365126227493004/934476826129088513)
