### ISSUE TITLE
Templates auto-applied by the note's name

### ISSUE THREAD

**Issue by LegendL3n** [dendronhq/dendron#2257]
## Please select if your request is either something new or an enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [X] Lookup - Dendron's Lookup Command

## Describe the solution you'd like ##

Create a template with something like a "noteName", which would be automatically applied when creating a note with that name. (in any stub)

This would help since not only could I use the lookup feature to create a note based on a template, but it would also be automatically applied.

**Comment by hikchoi** [comment]
Thank you for the request.

We currently support templating by adding schemas or using `Dendron: Insert Note`. See: https://wiki.dendron.so/notes/861cbdf8-102e-4633-9933-1f3d74df53d2/

Would these be sufficient for your usecase?

**Comment by LegendL3n** [comment]
Yes I know, this is more of an improvement than a new feature itself,
basically have it be automatically applied to a note, depending on its name.

For instance creating a note named "todo", would apply the "todo" template.
(configurable whether or not to do this, in the template)
