### ISSUE TITLE
CLI does not report invalid commands

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2300]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features
- [ ] CLI

## Describe the bug

Running `dendron foo` does not produce any output nor an error.

## Expected behavior

Given that `foo` is not a valid dendron command, I expect an error to be output.

## Additional context

This bit me because I was mistyping `note` as `notes`. That's how I noticed that there's no output and no errors.

**Comment by kevinslin** [comment]
You're right, this is not great UX. Adding this to our backlog as a good first task for newcomers

**Comment by flammehawk** [comment]
I could take a try at it.

1. Create Help command
2. Create a Default Command that falls back to the Help command
3. Add some fluff to the default command when a nonexisting command gets called. 

If I have the go-ahead for this tell me please here or on Discord.

**Comment by kevinslin** [comment]
has been fixed as of 0.107
