### ISSUE TITLE
"Insert note" to insert frontmatter from template

### ISSUE THREAD

**Issue by abunavas** [dendronhq/dendron#2311]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Not a problem, just enhancement. 

## Describe the solution you'd like ##

When inserting note, it will be useful to insert the frontmatter also

## Describe alternatives you've considered ##

Obviously, I can use schemas, but (for now) it's too confusing for me. :-(

**Comment by kevinslin** [comment]
Adding this to our backlog as a good first task for newcomers

**Comment by aleksey-rowan** [comment]
The community has selected this issue as this week's [CROP](https://wiki.dendron.so/notes/tayowNP4tMvcqH7AraoQ4/) winner. 🎉

**Comment by bpathakota** [comment]
Looks like this is complete, can we mark this as closed? @kevinslin @aleksey-rowan

**Comment by aleksey-rowan** [comment]
@bpathakota, yeap, this is done. I can confirm that frontmatter is being inserted as well. Note that the `insert note` command got replaced by the [`Apply Template`](https://wiki.dendron.so/notes/ftohqknticu6bw4cfmzskq6/) command.

@abunavas, could you please check if the new command is working the way you expect?
