### ISSUE TITLE
New installation fails to open tutorial page

### ISSUE THREAD

**Issue by asward** [dendronhq/dendron#2317]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

New installation of dendron v0.79.0 fails to open the tutorial page. Manually opening (ctrl+shft+p 
'Dendron: Launch Tutorial') throws a toast error in vscode.

"{"errno":-4058,"syscall":"open","code":"ENOENT","path":"c:\\Users\\{username}\\.vscode\\extensions\\dendron.dendron-0.79.0\\assets\\dendron-ws\\vault\\welcome.html"}"

## To Reproduce

1. Open VS Code
2. Open Extensions Browser to dendron
3. Click 'Install'
4. Wait patiently for tutorial page that never comes
5. ctrl+shft+p 'Dendron: Launch Tutorial'
6. Error toast popup and no tutorial page shown

## Expected behavior

Per wiki the 'Welcome to Dendron' page should be shown, allowing me to initialize a workspace for dendron. 

https://wiki.dendron.so/notes/678c77d9-ef2c-4537-97b5-64556d6337f1/

## Screenshots

N/A

## Desktop (please complete the following information)

- OS: Win10
- Browser: VSCode 
- Version (vscode): 1.63.2
- Version (dendron): 0.79.0

## Additional context

It appears that the 'assets' folder from the path in the error json does not exist. I rolled back versions and found that 0.71.0 is the latest version to function correctly.

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7974067/dendron.log)

**Comment by Harshita-mindfire** [comment]
Thanks @asward for reporting the bug! 
I am unable to repro this. Ideally, for production stage, the path should be `$HOME/$VSCODE_DIR/{path-to-app}/dist/..`. 
Could you please confirm if this is the behavior for latest dendron version as well?

**Comment by muz3** [comment]
installed 0.83 the latest release, tried to open Launch tutorial, and received the same issue report.
