### ISSUE TITLE
Sync Preview

### ISSUE THREAD

**Issue by rgoshen** [dendronhq/dendron#2324]
## Please select if your request is either something new or an enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [X] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I would like to see for the preview to sync with the Markdown view.  

## Describe the solution you'd like ##

So when you scroll down, both sync scroll.

## Describe alternatives you've considered ##

none

## Additional context ##

none

**Comment by aleksey-rowan** [comment]
This issue is already tracked in #1978. Closing as duplicate. Please, upvote and post any additional details there.
