### ISSUE TITLE
Add warning about VSCodium on macOS potentially being slow

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2342]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I found VSCodium through dendron's web site. I installed dendron into VSCodium and figured I would keep my notes separate from my code by using one for each. But after a month or suffering thinking dendron was slow, I finally switched to VSCode instead and realised that it's blazing fast, it was VSCodium that was slowing me down this whole time.

## Describe the solution you'd like ##

Add a small warning somewhere next to the VSCodium recommendation with a link to this issue:

https://github.com/VSCodium/vscodium/issues/718

## Describe alternatives you've considered ##

None

## Additional context ##

I guess this could be a quick & easy change to add a note somewhere, it doesn't seem like a huge priority as it only affects some macOS users apparently.

**Comment by Harshita-mindfire** [comment]
Thanks @chmac for the suggestion and for highlighting your pain points. 
Pinging @ScriptAutomate for visibility.

**Comment by xmailla** [comment]
Hello,

as far as I can tell, I don't feel any slowdown on a daily basis either on my Mac or on my desktop computer.
I am running latest VSCodium, and try to stay up-to-date (1.69 here)

**Comment by chmac** [comment]
I have personally switched back to VSCodium for dendron and I also think these performance issues have been fixed. I'll close this issue now as it seems the underlying problem has been solved.
