### ISSUE TITLE
Feature Request: Ability to add Daily Journal Note via Dendron CLI

### ISSUE THREAD

**Issue by nbbaier** [dendronhq/dendron#2385]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I'd like to be able to create a Daily Journal Note while working in Terminal so I don't need to context switch to VSCode to create one.

## Describe the solution you'd like ##

Ideally, I would love functionality added to the Dendron CLI so that it would be possible to create a daily journal note exact same result as running the "Create Daily Journal Note" in VSCode. 

## Describe alternatives you've considered ##

I've used (for example) ```dendron note lookup --query "daily.journal.2022.02.10"``` but this doesn't seem to generate the note with the same type of metadata as the VSCode command 

## Additional context ##

None.

**Comment by aleksey-rowan** [comment]
Thanks for the request! It looks like this is a duplicate and a similar request is already tracked in #770. I'll close this issue, but please feel free to upvote and leave comments in the linked issue.
