### ISSUE TITLE
Quality of Life Improvements v0

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#239]
# Quality of Life Improvements (QoL) v0

## Goals

Dendron is many things but easy to use it is not quite (yet). 

## Details

Make Dendron easy to onboard (even for non-technical users) and smooth some of the rough edges. 

## Tasks
- [ ] create an easy schema builder
- [ ] interactive tutorial?
- [ ] collect feedback from the community

## Next
- TBD

## Links
- [project docs](https://dendron.so/notes/c4cb56af-ec13-4e57-aede-eb341e870736.html)
- [issues](https://github.com/dendronhq/dendron/labels/pro.qol-v0)

**Comment by CptnGreen** [comment]
Hello! Great tool you are working on.

I've learned about Dendron right after Org-roam project for Emacs (in search of a cloud-less alternative to Notion). 

It seems like Dendron and Rog-roam are mostly equivalent in their functionality, but Dendron has several advantages:
- it is being built upon VSCode which is easier to use and easier to deploy on different devices than Emacs
- it uses Markdown (and Yaml) which is much more popular than Org syntax

Back to the topic - I think you should emphasize lookup functionality - it is one of the main tools in Dendron but I've found it only after watching the onboarding video-session.

I think you should also consider adding import from org functionality (using Pandoc for instance) and may be import from Notion in future (when they fully release their API)

**Comment by gour** [comment]
> Hello! Great tool you are working on.
> 
> I've learned about Dendron right after Org-roam project for Emacs (in search of a cloud-less alternative to Notion).
> 
> It seems like Dendron and Org-roam are mostly equivalent in their functionality, but Dendron has several advantages:

I'm trying to decide between Dendron/Org-roam/Neuron, but, although Dendron seems to be great pacakge, imho, it has one *disadvantage*...

>     * it is being built upon VSCode which is easier to use and easier to deploy on different devices than Emacs

Yeah, I know that VSCode is great etc., but it's not open-source, so I'd prefer that Dendron would be editor-agnostic, like e.g. [Neutron](https://neuron.zettel.page/).

**Comment by micharris42** [comment]
@gour, it takes a bit of looking to find on the website, but Dendron and all of its components are available on the Open VSX Registry:

[Dendron.Topics.Open VSX](https://wiki.dendron.so/notes/9134f160-31a6-4ab0-a640-1fce466f9526.html)

While not completely editor agnostic, Dendron should run on all of the VS Code compatible editors.

If you would prefer to go without VS Code, there is the fully Open Source VSCodium. Or, if you like to live dangerously, you could try one of the more esoteric editors, such as the Onivim 2 alpha.

**Comment by gour** [comment]
> If you would prefer to go without VS Code, there is the fully Open Source VSCodium. 
I do not have problem with the license, but with the fact which company is behind it. ;)

> Or, if you like to live dangerously, you could try one of the more esoteric editors, such as the Onivim 2 alpha.

Yes, I have licence for Onivim2, but Dendron does not work with it - installation error. The problem is that Oni2 does not have (yet) support for VSCode's webview.

So, although, I admit, Dendron is beautiful package, I'll go with Emacs/org-roam.

**Comment by kpathakota** [comment]
@gour - I do see that onivim is trying to get to full support for VS Code extension API so hopefully Dendron will work on there soon! 

That said, this issue has outlived it's value and is too vague/off topic. Closing.
