### ISSUE TITLE
Wildcard references with headers should skip notes without matching headers

### ISSUE THREAD

**Issue by SeriousBug** [dendronhq/dendron#2406]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When using a wildcard reference with a header (for example `![[daily.journal.*#meeting]]`), the notes that don't have matching headers are included in the render with the error message "anchor meeting not found".

This makes it hard to find only matching notes because there may be many notes in the hierarchy but few that match the header.

## Describe the solution you'd like ##

Instead, the notes that don't have matching headers should be skipped. Perhaps a message could be included to note that there are other notes that are in the hierarchy but don't match the header.

## Describe alternatives you've considered ##

The queries RFC would also solve this problem, but it's a harder syntax to use.

**Comment by CollinsPeriodLee** [comment]
When using the wildcard reference `![[daily.journal.2022.*#new-thoughts,1]]`, there is an error reported in the preview panel 
![image](https://user-images.githubusercontent.com/22069889/153740082-673dd2c9-18c9-4858-abaf-53c35abe02fa.png)
since I don't have a file named as `daily.journal.2022.01.md`.

**Comment by jonathanyeung** [comment]
Tracking with [[Wildcard References with Headers Should Skip Notes without Matching Headers|dendron://private/task.2022.02.14.wildcard-references-with-headers-should-skip-notes-without-matching-headers]]

**Comment by aleksey-rowan** [comment]
There is already an open (very old) issue referring to the same behaviour: https://github.com/dendronhq/dendron/issues/363

**Comment by aleksey-rowan** [comment]
@SeriousBug, is it okay to close this as a duplicate of #363?

**Comment by SeriousBug** [comment]
Ah good catch, thanks! I'll go ahead and close this.
