### ISSUE TITLE
Airtable Export Pod reads tags that are in body

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#2410]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [x] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

A tag that's in the body of a note is read when exporting the note to Airtable.

## To Reproduce

1. Create a task note
2. Add correct tags that are defined in the source map. (e.g. `scope.workspace`)
3. Add any dummy hashtag in note (e.g. `scope.fake`)
4. Airtable Export Pod will result in an error because the dummy hashtag.
5. In addition, the error message toast contains a very unreadably formatted error message

## Expected behavior

Airtable Export Pod only looks at frontmatter tags when mapping them into Airtable

## Screenshots

![image](https://user-images.githubusercontent.com/1219789/153805760-ecc1dfb2-f4a4-4a72-8af2-e693b3bf86cd.png)

## Desktop (please complete the following information)

- OS: Mac
- Version: nightly 0.81.2

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

```
{"level":50,"time":1644816336241,"pid":95479,"hostname":"hikchois-Mac-mini.local","name":"dendron","msg":"Finished Airtable Export. 0 records created; 0 records updated. Error encountered: {\"payload\":[{\"message\":\"Error during Airtable Export. Insufficient permissions to create new select option \\\"\\\"kind.fake\\\"\\\"\",\"name\":\"DendronError\",\"status\":\"unknown\",\"payload\":\"[{\\\"fields\\\":{\\\"DendronId\\\":\\\"oHOo9AsSzalDGBJuxURwu\\\",\\\"Name\\\":\\\"Findincompatibleextensions Is Slow on Large Workspaces\\\",\\\"Notes\\\":\\\"\\\\n## Summary\\\\n`findIncompatibleExtensions` is slow on large workspaces.\\\\n## Details\\\\n\\\\n## Example\\\\n\\\\n## Tasks\\\\n\\\\n## Lookup\\\\n\\\\n#kind.fake\\\",\\\"Owner\\\":\\\"hikchoi\\\",\\\"Creator\\\":\\\"hikchoi\\\",\\\"PR\\\":\\\"\\\",\\\"Scope\\\":\\\"scope.workspace\\\",\\\"Issue\\\":\\\"\\\",\\\"Size\\\":\\\"size.small\\\",\\\"Kind\\\":[\\\"kind.fake\\\"],\\\"Sprint.Tag\\\":\\\"sprint.active\\\",\\\"Pri

... 

truncated for brevity
```

**Comment by Harshita-mindfire** [comment]
Sure, The error log has the correct format of error. Will look into this.

**Comment by kevinslin** [comment]
this isn't actually an error though. when we export tags, the pod **should** read all tags. or if its not, its something we should discuss the behavior for in [[Standard Src Field Mapping for All Pods|dendron://private/task.2022.01.23.standard-src-field-mapping-for-all-pods]]

**Comment by hikchoi** [comment]
> this isn't actually an error though. when we export tags, the pod **should** read all tags. or if its not, its something we should discuss the behavior for in [[Standard Src Field Mapping for All Pods|dendron://private/task.2022.01.23.standard-src-field-mapping-for-all-pods]]

I would argue that it ___should not___.

The existence of frontmatter tags gives an affordance that says: _"here is where you should put all the tags"_.

Then the counter question as a user would be, _"why would tags in the body be mapped when I have explicitly set my tags in the frontmatter?_

Wouldn't it be better to explicitly state in the frontmatter that I want these tags to be used in the source field mapping rather than looking at all tags in the NoteProps?

Consider this case:

I have a task note. It's a fictional task to refactor my notes. I jot down some ideas for how to organize tags for my personal notes.
I have set some tag to categorize this task in frontmatter.

Some of my sentences in this note will look like this:

- _#scope.recipe is too big of a catchall. I should make this better_
- _The number of notes with #scope.undefined is getting out of hands. I need to give them a proper scope!_
- _These notes should not be in #scope.finance: [...]_

Should these use of hashtags be mapped to Airtable?

It's a made up case, but it illustrates my point: 

As-is, the success of export depends on the integrity of all the tags used in the note body, if any of the tag is entirely or partially part of the source field mapping defined by the pod. This limitation (or the lack of) is steer the user to write a note in a certain way that is not obvious, but the feature that is forcing the user to do so has no part in aiding the creation of note content.

With the export pod defining source field mapping, I am basically now blocked from using those tags in my body if I don't want this to happen. 

This goes for both valid, existing tags and non-existent ones as well.

- If it's a tag that is srcFieldMapped, and a singleTag field, it will hit an error because I already have one in frontmatter and just mentioned it again in the body.
  - e.g. try adding this sentence to any of our tasks: `Maybe we can do X here, but this would be out of scope. Let's create a new task to follow up. as a #sprint.next item.`. It won't if this task note itself already has a sprint tag in frontmatter.

- If it's a tag that doesn't exist yet, you can't even mention them if it's under any tag hierarchy that has been source field mapped. because Airtable doesn't know about these tags and refusing them.

One could argue that I can just escape the hashtag or just not make it a tag (just use wikilinks). That is indeed one solution, but it's not zero-cost. and it leaves the users wondering. It's preventing me from writing notes in a certain way.

**Comment by kevinslin** [comment]
I think thats also valid but this is where the RFC for `[[Standard Src Field Mapping for All Pods|dendron://private/task.2022.01.23.standard-src-field-mapping-for-all-pods]]` comes in

I think there is value in supporting both cases.  The way we can support that with frontmatter mapping is by limiting the scope in the "to" filed

```yml
# pull tags from anywhere in the note
Scope: {to: "all", type: "multiSelect", filter: "tags.scope.*"}
# pull tags from the frontmatter
Scope: {to: "fm.tags", type: "multiSelect", filter: "tags.scope.*"}
# pull tags from the body
Scope: {to: "body", type: "multiSelect", filter: "tags.scope.*"}
# pull tags from a specific section in the body
Scope: {to: "body#section1", type: "multiSelect", filter: "tags.scope.*"}
```

**Comment by hikchoi** [comment]
Is there a discussion thread for the RFC out? If so, I can mention this issue there to continue the discussion but close this issue since we've established this is intended behavior as-is.

**Comment by Harshita-mindfire** [comment]
Created [discussion thread](https://github.com/dendronhq/dendron/discussions/2431) for [Standard Src Field Mapping for All Pods] (https://github.com/dendronhq/dendron-docs/blob/main/vault/rfc.44-standard-src-field-Mapping-for-all-pods.md) RFC.

**Comment by hikchoi** [comment]
closing this as it's not a bug. I've copied my comments to the discussion thread so it can continue.
