### ISSUE TITLE
Calendar View and Tree View isn't updated after deleting a journal note 📅

### ISSUE THREAD

**Issue by pcgeek86** [dendronhq/dendron#2421]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Calendar View and Tree View are not updated when notes are deleted. Calendar still shows white days even after deleting the daily notes. Tree view shows hierarchy for daily journal notes, even if all of them have been deleted from the repository. 

These two components need to be updated more frequently.

![image](https://user-images.githubusercontent.com/466713/153950427-75c55006-7506-4a53-bb7c-16c4f68033fa.png)
![image](https://user-images.githubusercontent.com/466713/153950833-292e3f6b-741b-4c0d-a58d-c516c127f7de.png)

## To Reproduce

1. Click on a day in the Calendar to generate a new daily note
2. Delete the newly created note file
3. Observe that the Calendar day is still white, indicating that a note exists for that day
3. Click the plus sign in the Tree View to create a new daily note
4. Delete the newly created note file
5. Observe that the hierarchy still exists for the year-month-day that the note was created for

## Expected behavior

Tree View: Hierarchy should accurately reflect daily notes that actually exist, and should not show Tree View child items for daily notes that do not exist.

Calendar View: Days that do not have a daily note should not be white.

**Comment by jonathanyeung** [comment]
Thanks @pcgeek86! - we've been working on some refactoring work that should improve the UI reliability, which has update issues across our views.  We'll add the cases you highlighted to our verification steps upon completion of that work.

Tracking internally via [[Views Miss Updates on Journal Note Deletion|dendron://private/task.2022.02.15.views-miss-updates-on-journal-note-deletion]]

**Comment by hikchoi** [comment]
Hey @pcgeek86 

We've ironed out some bugs that happen when deleting a note, and now the tree view correctly removes the deleted tree nodes. Please let us know if you are still experiencing this issue.
