### ISSUE TITLE
Add Pinned/permanent note preview

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#2437]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Currently it is not possible to keep a specific note open as a preview while navigating other notes.

## Describe the solution you'd like ##

An option to pin/keep the preview of a specific note, and navigate to other notes without it changing (then be able to open a second note preview for those other notes if required).

## Describe alternatives you've considered ##

Screenshot, publish, click back to note.

**Comment by SeriousBug** [comment]
Thanks for the suggestion, I think this would be very useful. This will take quite a bit of work as we can only have 1 preview open for Dendron right now.

**Comment by kevinslin** [comment]
this is now released as of v107 :)
