### ISSUE TITLE
Horizontal Lines are Not Rendered on Published Site

### ISSUE THREAD

**Issue by joshuajeschek** [dendronhq/dendron#2438]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Publish.  External Site Publish

## Describe the bug

When using publish, horizontal lines created with either `---` or `***` are not rendered.

## To Reproduce

1. Create a horizontal line in a note using `---` or `***`
2. dendron publish in some way
3. look at the published note: no line to be found

## Expected behavior

A horizontal line should be rendered, when using `---` and `***`

## Screenshots

![image](https://user-images.githubusercontent.com/64850647/154355307-1370af68-5b55-484a-9e67-f0bf4b14ba87.png)
code and preview in VSCode

![image](https://user-images.githubusercontent.com/64850647/154354970-0565e1de-6cc7-4e28-b218-a65a82839301.png)
published site

## Desktop (please complete the following information)

- OS: /
- Browser: chrome
- Version: /

## Additional context

checkout the published site here: https://tuc.jeschek.eu/notes/8VGVHPyWPBwWq8fwQCTVy/#trick-questions - there should be a horizontal line after "trick questions"

**Comment by SeriousBug** [comment]
I can reproduce this issue, it looks like a bug with our publishing theme. It's an easy fix so I'll fix this immediately, thanks for the report!

**Comment by SeriousBug** [comment]
This has now been fixed in Dendron 0.83. Please let us know if the issue persist, otherwise this will automatically close in a few days.

**Comment by joshuajeschek** [comment]
Tried out 0.83, works perfectly! Thanks!
