### ISSUE TITLE
VSCode error notification "Cannot read property 'title' of undefined" when actively typing/editing in any document

### ISSUE THREAD

**Issue by SotoDucani** [dendronhq/dendron#2451]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When actively typing or editing a document, a error notification will continuously pop up with the text "Cannot read property 'title' of undefined". The notification will rapidly continue to pop up and refresh as typing continues, and stop when typing no longer continues. This behavior persists through restarting VSCode, clearing the dendron cache file, and reloading the index as described in the Troubleshooting page of the wiki.

I've also taken some time to dig through my files to see if I broke any of the frontmatter unintentionally, however I haven't been able to find anything.

## To Reproduce

1. Find a Dendron workspace that exhibits the issue. I only use one work-related workspace heavily that's showing the problem. Other personal workspaces have not as of yet shown the issue.
2. Open up any document and begin typing.
3. Error notifications will begin to populate in VSCode

## Expected behavior

No error notifications are populated.

## Screenshots

![image](https://user-images.githubusercontent.com/8963875/154712546-84754134-ef03-443c-98ba-13c2b0d73d5e.png)

## Desktop (please complete the following information)

- OS: Windows 10 20H2
- Browser: Chrome
- Version: 97.0.4692.71

### VSCode version info
Version: 1.60.2 (system setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Dendron version: v0.82.0

## Dendron Log file

[ServerLogs.txt](https://github.com/dendronhq/dendron/files/8098414/ServerLogs.txt)
[WorkspaceSettings.txt](https://github.com/dendronhq/dendron/files/8098415/WorkspaceSettings.txt)
[ClientLogs.txt](https://github.com/dendronhq/dendron/files/8098416/ClientLogs.txt)
[Dendron.txt](https://github.com/dendronhq/dendron/files/8098421/Dendron.txt)

**Comment by aleksey-rowan** [comment]
I'm getting these notification all the time as well and just ignore them since nothing seems to be really breaking.

**Comment by SotoDucani** [comment]
Yep good point to call out I forgot. Same thing here, I'm not noticing any negative impact from this.

**Comment by joshuajeschek** [comment]
I managed to reproduce this by copying and pasting a note in the file explorer side panel, and then deleting it again (not through lookup and "delete node")

at first I thought it was because of using the file explorer panel, but that wasn't the case. The note I was copying and deleting **had the same ID** as another note, which seemed to mess up something, my guess is the cache

my suggestion would be to make it more obvious if a note has the same ID, for example with an inline error message at the id line, as well with an easy fix (with the light bulb symbol in vscode)

Maybe you guys could check for duplicate IDs as well :) @aleksey-rowan @SotoDucani

**Comment by joshuajeschek** [comment]
Oh and by the way, it impacted me negatively, I could not delete another note through "delete node", these were my error notifications:
![image](https://user-images.githubusercontent.com/64850647/154762300-e87e5210-cc9a-49a5-934a-b1686587bcf0.png)
the first one occured when deleting the copied file, the second one when trying to delete another note through "delete node".

**Comment by SeriousBug** [comment]
Thanks for the reports, I'll make sure to figure out this issue!

**Comment by raeyulca** [comment]
I encountered this issue as well.
In checking the error logs, there was no lines matching `"level":50` as outlined [here](https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe/#check-the-logs)
In my case, I had a file with the name formatted `foo.bar..baz`; this was also preventing the tree view from loading.

**Comment by jgmpjgmp** [comment]
I have this issue as well. Possibly coincidentally, my Tree View is broken, but I otherwise don't see negative effects.

**Comment by SeriousBug** [comment]
Hi, I don't see any error messages in the logs uploaded. If someone else sees this error, could you please get the logs immediately after the error and upload that?

**Comment by SotoDucani** [comment]
@SeriousBug So those were taken pretty close to the issue happening. Is there some sort of lower level debug setting I could force logging into and see if I get anything of value? I'm afraid nobody else is going to have any explicit errors either.

**Comment by SeriousBug** [comment]
@SotoDucani You can set the debug level in the VSCode settings to get more information, although an error message should always appear in the logs: https://wiki.dendron.so/notes/19a0ea9d-7292-4a68-bc6f-ffd462a54bc5/#dendronloglevel

Did you restart VSCode after the issue by any chance? Dendron doesn't keep the logs before restarts, that would explain why it was missing in the logs.

**Comment by jgmpjgmp** [comment]
The error was constant with any typing, so it should have shown after any restart. However, the lack of TreeView display and this may actually be related. Though TreeView has been a problem for months, and these errors only started very recently, adding the `enableWebUI: true` to the YAML config fixed both.

**Comment by SeriousBug** [comment]
Thank you very much for the testing, and glad it works now!

@jgmpjgmp @raeyulca Could you also try enabling Tree View V2 with this config example? It goes in the `dev:` section of the config.

```yaml
dev:
    enableWebUI: true
```

**Comment by raeyulca** [comment]
@SeriousBug I have tested this.. The result is that all tabs in the tree view collapse when viewing a note with two successive periods in its name. However, the error message no longer appears.

**Comment by SeriousBug** [comment]
We have recently made changes to the tree view, including a lot of bug fixes. Is anyone still experiencing this error? I haven't been able to reproduce it since those changes.

@raeyulca I've tried putting two successive periods in the name of a note, with recent fixes that actually seems to function correctly.

**Comment by jgmpjgmp** [comment]
When I upgraded to 0.94.0, I noticed that Tree View moved, but it’s still empty for me.

For what it’s worth:

  1.  Show Note Graph
     *   produces the message (regardless how long Dendron’s been up):
still connecting to engine. please try again in a few moments...

     *   I noted that Dendron Doctor showed 'Dendron Markdown Links' as installed and incompatible. Uninstalling it gave the launch message: 'Dendron Markdown Links' is recommended for this repository. Do you want to install? I installed and maybe the version that had been installed was old, or maybe uninstalling and reinstalling fixed the problem. It now works okay (though Doctor still identifies it as incompatible?!)
  1.  I know that there’s now a check for duplicate note IDs, and at launch I began seeing:
Notes Links to Dendron Resources in Vault-JP-Dendron-Notes and Dendron.Links to Dendron Resources in Vault-JP-Dendron-Notes have duplicate IDs.
(Formatting may make the message more intuitive!) I fixed the IDs, but that didn’t fix Tree View

  1.  On launch, when I click on the Dendron Activity Bar icon, I still get the Cannot read properties of undefined (reading 'fname'). I confirmed that, as in https://github.com/dendronhq/dendron/issues/2786, starting a tutorial enables the Tree View for the tutorial workspace.

Thanks,
JP / JGMPJGMP
