### ISSUE TITLE
Broken link and wrong text in some ToC entries

### ISSUE THREAD

**Issue by cconrad** [dendronhq/dendron#2456]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I noticed that we have a heading in the [Dendron FAQ](https://wiki.dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558/) with the text "What can I do with the root note?", where "root" is inline code. This renders correctly on the page, but the entry in the table of contents reads "What can I do with the note?" (text content within inline code is missing).

In addition, the ToC link is broken, I assume that different logic is used to generate the `href` attribute of the `a` element in the ToC than what is used to generate the `id` attribute of the `h1` element in the main content.

This made me test some other weird/special cases, and while I was unable to generate broken links in other ways, I discovered that the characters "-" and "_" are not rendered in ToC entries either - see table below.

## To Reproduce

1. Insert the Markdown from the second column of the table below in a note.
1. Publish the page.
1. Compare the main content with the ToC entries.

| Test name   | Markdown                     | HTML in main content                                                   | HTML in ToC (actual result)                                      | Expected result                                                  |
|-------------|------------------------------|------------------------------------------------------------------------|------------------------------------------------------------------|------------------------------------------------------------------|
| Inline code | ``# Test1 `inlinecode` End`` | `<h1 id="test1-inlinecode-end">Test1 <code>inlinecode</code> End</h1>` | `<a href="#test1--end">Test1  End</a>`                           | `<a href="#test1-inlinecode-end">Test1 inlinecode End</a>`       |
| Hyphen      | `# Test2 - (hyphen) End`     | `<h1 id="test2---hyphen-end">Test2 - (hyphen) End</h1>`                | `<a href="#test2---hyphen-end">Test2   (hyphen) End</a>`         | `<a href="#test2---hyphen-end">Test2 - (hyphen) End</a>`         |
| Underscore  | `# Test3 _ (underscore) End` | `<h1 id="test3-_-underscore-end">Test3 _ (underscore) End</h1>`        | `<a href="#test3-_-underscore-end">Test3   (underscore) End</a>` | `<a href="#test3-_-underscore-end">Test3 _ (underscore) End</a>` |

## Expected behavior

See the expected result for each test case in the right-most column "Expected result" of the table above.

## Screenshots

![image](https://user-images.githubusercontent.com/584491/154810674-75c25b3a-b3f5-4208-babf-8394cafe0767.png)

## Desktop (please complete the following information)

- Versions (all that apply to bug):
  - Dendron CLI: 0.82.0

**Comment by SeriousBug** [comment]
Thanks for the report! This is a bug in how the titles are generated in published sites, we'll make sure to fix this.

For Dendron team: The code in `DendronTOC.tsx` tries to reverse the anchor slugs to get the title text, but that's not a reversible process. We should instead add the full text of the header to the anchors when they are parsed (AnchorUtils.headerText), and use that in the frontend.
