### ISSUE TITLE
Refactor Hierarchy error in multi-vaults context

### ISSUE THREAD

**Issue by ychen01** [dendronhq/dendron#2462]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When applying `Dendron: Refactor Hierarchy` to a side vault  
get `vault not found` or `error while running command: Request failed with status code 500`

## To Reproduce

1. Create a new workspace using `Dendron: initialize workspace`
2. Create a side vault **inside** the base vault folder,  using `Dendron: Vault Add` -> `local ` -> `path: vault2` -> `name: vault2`
3. Create a note in the `vault2` vault, named `vault2.someone`
4. Apply `Dendron: Refactor Hierarchy` -> `vault2` to `test`
3. Refactor works properly after `reload index` or reopen the workspace.
2. Create another side vault **outside** the base vault folder,  using `Dendron: Vault Add` -> `local ` -> `path: ../shared` -> `name: shared`
3. Create a note in the `shared` vault, named `person.someone`
4. Apply `Dendron: Refactor Hierarchy` -> `person` to `friend`
5. Error message "**_vault not found_**"

## Expected behavior

Refactor works as in the single vault context

## Screenshots

error messages reported above

## Desktop (please complete the following information)

- OS: Windown 10
- Versions (all that apply to bug):
  - Dendron Extension: 0.82.0
  - VS Code version: 1.64.2
  - Dendron CLI: not installed

## Additional context

N/A

## Dendron Log file

```
{"level":50,"time":1645478111247,"pid":12500,"hostname":"XXXXXXXX","name":"dendron","ctx":"dendron.refactorHierarchy:run","error":{"name":"DendronError","status":"unknown","payload":"{\"wsRoot\":\"c:\\\\Users\\\\myself\\\\Documents\\\\workspace\\\\main\",\"fsPath\":\"c:\\\\Users\\\\myself\\\\Documents\\\\workspace\\\\shared\",\"vaults\":[{\"fsPath\":\"vault2\",\"name\":\"vault2\"},{\"fsPath\":\"../shared\",\"name\":\"shared\"},{\"fsPath\":\"vault\"}],\"normPath\":\"..\\\\shared\",\"msg\":\"no vault found\"}"}}
```

**Comment by SeriousBug** [comment]
Thanks for the report! I was able to reproduce the issue. The problem is "Vault Add" doesn't seem to handle relative paths correctly cross platform. Since you are on Windows, I believe you needed to use `..\shared` instead for the path.

You can also fix this issue now by configuring Dendron (`Dendron: Configure (yaml)` command), finding `shared` under vaults, and fixing the path. It will look like this when fixed:
```yaml
    vaults:
        -
            fsPath: ..\shared # this is the line to fix
            name: shared
        -
            fsPath: vault2
            name: vault2
        -
            fsPath: vault
```

Could you let me know if that fixes the issue for you?

**Comment by ychen01** [comment]
> Could you let me know if that fixes the issue for you?

Yes! this fixes my problem.  
This was my bad: I should enter `path: ..\shared` at the step 6...
But since the vault addition was successful, I didn't suspect the path pb initially.
Then I was trying to manually change the separator in config files, but the changes were not effective for some reasons..
Thank you for the answer 🙏
