### ISSUE TITLE
Lookup: Missing space between note title and vault name

### ISSUE THREAD

**Issue by cconrad** [dendronhq/dendron#2467]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

In the lookup, in a multi-vault setup, there is no space at all between the note title and the vault name.

## To Reproduce

1. Have a multi-vault setup
2. Have some notes
2. Open lookup

## Expected behavior

It would look better if there was some space between the note title and the vault name.

## Screenshots

![image](https://user-images.githubusercontent.com/584491/155130311-99560b12-50db-4188-b99c-cd52145c79f5.png)

## Desktop (please complete the following information)

- OS: Windows 11
- Browser (if with published websites; include version): Edge
- Versions (all that apply to bug):
  - Dendron Extension: 0.82.0
  - VS Code version: 1.64.2

**Comment by hikchoi** [comment]
Thank you for the suggestion. I'll see if I can sneak this in for next week's release 😄

**Comment by saifahn** [comment]
Is this still an issue that needs work? I'd like to give it a shot if so :)

**Comment by hikchoi** [comment]
> Is this still an issue that needs work? I'd like to give it a shot if so :)

@saifahn
Sure. we always welcome contributions 😄
This should be a one-line fix in `DNodeUtils.enhancePropForQuickInput`

I apologize for folks who are waiting for this. I meant to pick this up but must have slipped my mind.

**Comment by kevinslin** [comment]
has been fixed as of 0.107
