### ISSUE TITLE
Katex not working in Publish

### ISSUE THREAD

**Issue by joshuajeschek** [dendronhq/dendron#2470]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Publish.  External Site Publish

## Describe the bug

The newest update seems to have broken publish.
(`publish.enableKatex` is set to `true`)
Clear example is the wiki page about math: [Math(Wiki)](https://wiki.dendron.so/notes/b1919663-cc48-4054-b0cf-4b26fe444907/)

## To Reproduce

1. Write some inline or block math
2. publish the site with 0.83.0
3. see that it hasn't been rendered

## Expected behavior

Katex should be rendered correctly as math

## Screenshots

Extreme example:
![image](https://user-images.githubusercontent.com/64850647/155229767-c00cb9be-757d-48b9-b56d-f4668473ba2a.png)

## Desktop (please complete the following information)

- OS: ubuntu
- Browser (if with published websites; include version): chrome
- Versions (all that apply to bug):
  - Dendron Extension: /
  - VS Code version: /
  - Dendron CLI: 0.83.0

**Comment by hikchoi** [comment]
Thank you for the report. I can reproduce this. We'll let you know when this gets resolved 🙏🏼

**Comment by joshuajeschek** [comment]
fixed in the newest release. Thanks!
