### ISSUE TITLE
Katex fonts not included in extension.

### ISSUE THREAD

**Issue by novelhawk** [dendronhq/dendron#2477]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [X] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The extension doesn't include Katex fonts in its release, this leads to incorrect rendering of mathematical expressions (See #1747).

I believe this line is supposed to copy the font folder to the build output but it doesn't seem to be present on my local installation of the extension. Katex css file expects the `fonts` folder to be inside the `css\themes` folder (as it's loaded from `dark.css` or `light.css`)

https://github.com/dendronhq/dendron/blob/67a84c9185cb3def45cc83d5921158b308d9c404/packages/common-assets/scripts/buildStyles.js#L70

I'm not sure if the fonts were removed manually (to decrease extesion size?) but it breaks Katex so I'm assuming this is a bug.

**Comment by hikchoi** [comment]
Thank you for reporting.
We also have a regression where Katex isn't rendering properly when published, and I think this has to be related to that as well. 

I'll let you know when the fix for this gets pushed.

**Comment by hikchoi** [comment]
This issue has been resolved with v85. Please let us know if there are still outstanding concerns related to this issue.

I will mark this to automatically close in 4 days if there are not further comments.
