### ISSUE TITLE
Copy button in markdown code block in publishing

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#2497]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When I have to copy code I have to use my mouse to drag across the text and THEN either right click and copy or press some keyboard keys, instead of just clicking one simple button.

## Describe the solution you'd like ##

A copy button as part of the code blocks (or option to make a specific block type have a copy button), just like github natively supports, i.e.

```python
print('Here is some random code')
```

## Describe alternatives you've considered ##

Clicking and highlighting the text, ctrl+c

**Comment by hikchoi** [comment]
Thank you for the suggestion. We'll track this in our backlog and get back to you.

**Comment by flammehawk** [comment]
Is the React component for the Notes the same for preview and publish?

If so it could be added to that through CSS and an Eventhandler for the Code Element.

I would be open to doing that. @hikchoi

**Comment by hikchoi** [comment]
@flammehawk 

> Is the React component for the Notes the same for preview and publish?
> 
> If so it could be added to that through CSS and an Eventhandler for the Code Element.
> 
> I would be open to doing that. @hikchoi

for publishing, notes are statically generated and loaded here: https://github.com/dendronhq/nextjs-template/blob/main/components/DendronNotePage.tsx

and for preview notes are rendered here: https://github.com/dendronhq/dendron/blob/master/packages/dendron-plugin-views/src/components/DendronNotePage.tsx

you may have to handle the click event separately for the preview.

**Comment by flammehawk** [comment]
@hikchoi 
Wouldn’t https://github.com/dendronhq/dendron/blob/master/packages/common-frontend/src/components/DendronNote.tsx be a better place to add it to? since that gets included and used in Preview as well as Publish.

**Comment by hikchoi** [comment]
@flammehawk 

Yes you are correct that that is the common component. but if you look at the component it is getting the rendered note content as a prop and wrapping it. Notice that there isn't a trivial way at this point to add a copy button. I guess you _could_ take the `noteContent` prop, slice it up and insert buttons where it should be, but again, non-trivial and a bit out of scope of this particular component in my opinion.

the note content (html) are actually getting rendered by the engine.
I haven't put much thought to this, but I imagine this would be done through a unified plugin where a markdown code block would be transformed into html. during the process you would want to add the button.

For a similar example: see how we are adding block anchors https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/markdown/remark/blockAnchors.ts#L106:L106
