### ISSUE TITLE
refactoring has a problem with mixed-case filenames

### ISSUE THREAD

**Issue by robothor** [dendronhq/dendron#250]
**Describe the bug**
I have a file that I can't rename or refactor:
- the file is called `weekly.journal.W39.md`
- I tried to both refactor the hierarchy and rename the note through the `Dendron: XXX` commands
- I get an error at the bottom of the screen: `"weekly.journal.W39 not found"

**To Reproduce**
1. create a note with mixed-case, e.g. `lang.C`
2. Try to rename the note with the `Dendron: Rename Note` command
3. See error

**Expected behavior**
I expect to be able to rename the note

**Desktop (please complete the following information):**
VSCode info

```
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z (1 day ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Dendron Log file**
```
{"level":50,"time":1601749753173,"pid":3780,"hostname":"Matts-MacBook-Pro.local","name":"dendron","msg":"weekly.journal.W39 not found"}
{"level":50,"time":1601750470610,"pid":3780,"hostname":"Matts-MacBook-Pro.local","name":"dendron","msg":"lang.C not found"}
```

**Comment by kevinslin** [comment]
Thanks for reporting this. We'll have this fixed for the upcoming release next week!

**Comment by Harshita-mindfire** [comment]
Hi @robothor , apologies for addressing this too late, but it seems to be fixed in the latest versions of Dendron. Checking if this is still an issue?
