### ISSUE TITLE
Reveal current note in the tree view

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2500]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When I'm in a note, and I want to see it's sibling notes, navigating through the tree view is annoying and takes time.

## Describe the solution you'd like ##

Just like the "File: Reveal Active File in Sidebar" command, but for the dendron tree view.

## Describe alternatives you've considered ##

None

**Comment by jonathanyeung** [comment]
I do really like the 'Reveal in Side Bar' Command in VS Code, I was also thinking it'd be handy to have something similar for Tree View - we can take it into consideration.

We do navigate to the opened note in tree view, but it's hampered by existing bugs we have with Tree View and it doesn't work reliably. 

One mitigation you can do for sibling notes is to use the VS Code breadcrumb feature - I've come to rely on it for my own workflows:

![image](https://user-images.githubusercontent.com/3203268/156124383-2d142dbd-4071-4c20-b510-232fceb86a59.png)

**Comment by chmac** [comment]
@jonathanyeung Aha, took me a second to see what you meant, but that's excellent. There's even a `Focus Breadcrumbs` command which makes keyboard based navigation a breeze. Thanks a lot, that's a awesome tip.

**Comment by hikchoi** [comment]
We now have a command that focuses on the tree view: `Dendron: Focus on Tree View View`.

We also worked on fixing a lot of bugs that caused the tree view to not focus the active node.

Can you give it a try and let us know if you have any other outstanding concerns?

**Comment by chmac** [comment]
@hikchoi Thanks for the follow up, I'm seeing all the `Dendron: Focus on ...` commands, nice. 👍
