### ISSUE TITLE
AutoComplete: Enable Auto complete during rename. 

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2503]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Auto complete does not work during rename.

## Describe the solution you'd like ##

Make auto complete work during note rename. 

## Describe alternatives you've considered ##

Manually entering the rename. 

## Additional context ##

Auto complete currently works during look up. However, during rename (which looks very much like lookup) 'Tab' does not trigger auto complete functionality.

**Comment by aleksey-rowan** [comment]
@nickolay-kondratyev, there is already an issue opened about this problem https://github.com/dendronhq/dendron/issues/405. I'm going to close this one as a duplicate; please, upvote or leave a comment in the linked issue.
