### ISSUE TITLE
dendron-cli doesn't include latest migrationVersion (0.83.0 / 0.84.0)

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#2516]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The latest `dendron-cli` should provide a path to migrate to the latest `dendron.yml` config (`version: 5` from either `0.83.0` or `0.84.0`). It currently does not. I think these releases have provided new `preview:` and `publishing:` config sections.

## To Reproduce

1. Install latest `dendron-cli`
2. Run `npx dendron dev show_migrations`
3. See that some migration versions have been removed, and also that latest migration versions are not included

```bash
18:33 $ npx dendron --version
0.84.0
18:33 $ npx dendron dev show_migrations
======Available Migrations======

Make note of the version number and use it in the run_migration command

e.g.)
> dendron dev run_migration --migrationVersion=0.64.1

---------------------------------------------
version          | description
---------------------------------------------
0.55.2           | migrate note lookup config
0.51.4           | migrate scratch config
0.47.1           | migrate journal config
0.46.0           | update cache
---------------------------------------------
```

`run_migration` also doesn't have other available options (`[choices: "0.55.2", "0.51.4", "0.47.1", "0.46.0"]`):

```bash
19:00 $ npx dendron dev run_migrations --help
dendron dev <cmd>

commands related to development of Dendron

Positionals:
  cmd  a command to run
      [string] [required] [choices: "generate_json_schema_from_config", "build",
      "bump_version", "publish", "sync_assets", "prep_plugin", "package_plugin",
    "install_plugin", "enable_telemetry", "disable_telemetry", "show_telemetry",
                                             "show_migrations", "run_migration"]

Options:
  --version           Show version number                              [boolean]
  --help              Show help                                        [boolean]
  --wsRoot            root directory of the Dendron workspace
  --vault             name of vault
  --quiet             don't print output to stdout
  --upgradeType       how to do upgrade
                              [choices: "major", "minor", "patch", "prerelease"]
  --publishEndpoint   where to publish              [choices: "local", "remote"]
  --extensionTarget   extension name to publish in the marketplace
                                                 [choices: "dendron", "nightly"]
  --fast              skip some checks
  --migrationVersion  migration version to run
                               [choices: "0.55.2", "0.51.4", "0.47.1", "0.46.0"]
```

## Expected behavior

Latest migration versions should be available.

## Desktop (please complete the following information)

- OS: Pop!_OS 21.10
- Versions (all that apply to bug):
  - Dendron CLI: `0.84.0`

**Comment by hikchoi** [comment]
`0.84.0` won't have a migration entry but there should be one for `0.83.0` (which is when the publishing namespace migration happened). I'll get this fix in before the early seed snap.

**Comment by hikchoi** [comment]
@jonathanyeung Just letting you know that I've already created a task note for this. I'll add it this week's oncall note so you don't make a duplicate task.
