### ISSUE TITLE
Reference anchor shows up the in preview but it's not supposed to

### ISSUE THREAD

**Issue by Non-J** [dendronhq/dendron#2531]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When trying to reference an item of a list, the anchor used for reference shows up in the preview. See the attached screenshot below.

## To Reproduce

1. Create a new note.
2. Write the markdown as shown in the screenshot. 
3. Show the preview
4. See the problem

## Expected behavior

The anchor shouldn't show up in the preview, or at least be styled differently so as not to be confused with the actual content.

## Screenshots

![image](https://user-images.githubusercontent.com/45286033/156861928-5980cf61-2df7-4b46-850c-29d9cbe155f1.png)

## Desktop (please complete the following information)

- OS: Windows
- Browser (if with published websites; include version): N/A
- Versions (all that apply to bug):
  - Dendron Extension: v0.84.0
  - VS Code version: v1.65.0
  - Dendron CLI: N/A

## Additional context

I've asked this on discord where I've been told this is a regression and to submit a bug report.

https://discord.com/channels/717965437182410783/735365126227493004/949277439371141191

## Dendron Log file

https://gist.github.com/Non-J/88f00e03876b0f2c2e4645ab48be9b7e

**Comment by jonathanyeung** [comment]
Thanks for the suggestion @Non-J.

**Comment by SeriousBug** [comment]
Hi, this should be fixed in Dendron 0.86. Please let us know if it continues to happen after you update, otherwise this issue will automatically close in a few days.

**Comment by Non-J** [comment]
Yes, this issue has been fixed in the latest version. Thank you.
