### ISSUE TITLE
GoToSiblingCommand

### ISSUE THREAD

**Issue by akhiln28** [dendronhq/dendron#2533]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When I tried go to sibling from command palette, I got the following error. 

GoToSiblingCommand: You found a bug! We didn't think this could happen but you proved us wrong. Please file the bug here -->  https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= We will put our best bug exterminators on this right away!

## To Reproduce

1. Import pod -> markdown (import markdown files with folder hierarchy)
2. Try sibling navigation

## Expected behavior

Sibling navigation should work.

## Desktop (please complete the following information)

- OS: [e.g. iOS] MacOS Monterey
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by jonathanyeung** [comment]
Thanks @akhiln28 for the report - would you mind also including the output of the Dendron Logs in the bug? 

` Dev:Dendron: Open Logs` > paste output.

**Comment by akhiln28** [comment]
After I got the error I deleted the files imported using import pod. Again I tried reproducing the bug by importing the using import pod, but this time I am getting this message "One is the loneliest number. This node has no siblings :(" even though the current has a sibling. Please find the logs. 
[dendron.log](https://github.com/dendronhq/dendron/files/8196724/dendron.log)

**Comment by jonathanyeung** [comment]
Thanks for the extra info @akhiln28, the logs are helpful.  I'll duplicate this issue to this one: https://github.com/dendronhq/dendron/issues/1907
