### ISSUE TITLE
Tree View is Empty

### ISSUE THREAD

**Issue by jgmpjgmp** [dendronhq/dendron#2534]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
My Tree View section is completely empty. After reading other issues, I searched for notes with double dots in the title (none) and for reloaded index. without any change. Problem has actually affected me for several months.

I am also seeing the "Cannot read property 'title' of Undefined error (https://github.com/dendronhq/dendron/issues/2451) 

## To Reproduce

Sorry - unknown

## Desktop (please complete the following information)

- OS: Windows 10
- Versions (all that apply to bug):
  - Dendron Extension: 0.84.0
  - VS Code version: 1.65.0

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
[Log.txt](https://github.com/dendronhq/dendron/files/8199622/Log.txt)

**Comment by jgmpjgmp** [comment]
No journal files (for better or for worse)

**Comment by SeriousBug** [comment]
This will likely be solved with #2528.

**Comment by jonathanyeung** [comment]
Hi @jgmpjgmp - are you using Tree View V1 or V2? 

Tree View V1 is the default setting, but if your `dendron.yml` file (command to open is `Dendron: Configure (yaml)` ) has this in it, then it's V2:

```yaml
dev:
    enableWebUI: true
```

**Comment by jgmpjgmp** [comment]
It was V1. Adding the enableWebUI: true fixed it -- showing the treeview. Thanks!

**Comment by jonathanyeung** [comment]
Glad that V2 is working for you - however, let's leave this issue open as the fix that @SeriousBug  mentioned above only applies to V1, and V1 should be working as well.

**Comment by SeriousBug** [comment]
@jonathanyeung On that matter, do you know when the V1 tree view will be dropped (or V2 will become default)? Are there missing features we're waiting on?

**Comment by jonathanyeung** [comment]
> @jonathanyeung On that matter, do you know when the V1 tree view will be dropped (or V2 will become default)? Are there missing features we're waiting on?

I don't think we have any missing features (although I can think of some reasons why users may prefer v1 over v2), but we also haven't discussed a migration plan yet.  I suspect that the vast majority of our users are using v1 and not v2.

**Comment by jgmpjgmp** [comment]
Unfortunately, this fix stopped working. I migrated to a new machine (installed VSCode on the new machine, then Dendron, then copied my MD file tree across). The Tree View is now empty (but no error) when enableWebUI: true and empty with “Cannot read properties of undefined (reading ‘fname’)” error when enableWebUI: false.

**Comment by jonathanyeung** [comment]
@jgmpjgmp - appreciate your patience here.  We've actually changed our decision and decide to actually stick with _V1_ and deprecate _V2_ of tree view. 

On that though - we're actively investigating a few issues right now related to this and testing a few fixes that we're targeting in the next 1-2 releases. Let's loop back when they fixes are out and see.

**Comment by jgmpjgmp** [comment]
This was resolved by upgrading to 0.95.1 !

**Comment by SeriousBug** [comment]
Glad it works!
