### ISSUE TITLE
Cannot install on VS Code 1.44.2.

### ISSUE THREAD

**Issue by fabraz** [dendronhq/dendron#2544]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Dendron was working and after a VS Code reboot, it stopped working.

When trying to reinstall the last version of Dendron, I got the following message:

Unable to install 'dendron.dendron' extension because it is not compatible with the current version of VS Code (version 1.44.2).

## To Reproduce

1. Go to VS Code extensions
2. Lookup for Dendron
3. Click install

## Expected behavior

Plugin installation.

## Desktop (please complete the following information)

- OS: MacOS
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version: version 1.44.2.
  - Dendron CLI:

**Comment by Harshita-mindfire** [comment]
Hi @fabraz , Dendron installation now requires a minimum VS Code version of 1.58

**Comment by fabraz** [comment]
Hi @Harshita-mindfire!
I've managed to install in version 1.65.1. 
What I've found strange was installing and using the previous version and it had worked until this morning.
Anyway, thanks for your prompt answer!
