### ISSUE TITLE
Links to new Markdown Files not operative in Jekyll site

### ISSUE THREAD

**Issue by richardkaplan** [dendronhq/dendron#255]
If I use the Dendron workspace as a test and then add additional Markdown notes, I can create links from other notes in the vault to the new notes while browsing in Visual Studio Code.

However if I think use Jekyll to create either a local preview or a Github website, in either of those cases I get a 404 error with the same links.

Perhaps relevant - the new files I create do not have visible YAML metadata at the top.   Might that be the cause of this?  If so, how do I create the YAML for a new note?

**Comment by richardkaplan** [comment]
![image](https://user-images.githubusercontent.com/6059733/95039873-f979ae00-069f-11eb-9ded-13c6a2808ea6.png)

All of the links work within Visual Studio Code.  The links to the new files however give 404 errors on the Jekyll created pages.

**Comment by kevins8** [comment]
For new files, did you create them outside of Dendron? If so, you'll need
to run `Dendron: reload index` for them to show up

**Comment by richardkaplan** [comment]
Thank you

They were created within Dendron

I did reload the index - Jekyll now gives several not found errors.  The 404 errors also continue as above. Any thoughts?

![image](https://user-images.githubusercontent.com/6059733/95110006-61b1a980-070b-11eb-8d81-bd651ac2d811.png)

**Comment by richardkaplan** [comment]
If we don't know the solution to the above - could you clarify how to add a new page within VSC so it is indexed properly?  can I use the "New file" icon?

Moreover - is there any way to add YAML data to a file that does not have it?

**Comment by kevins8** [comment]
1. you can create notes using lookup (
https://dendron.so/notes/a7c3a810-28c8-4b47-96a6-8156b1524af3.html#creating-notes
)
2. to add yaml data to files, you can run "Dendron: Doctor" and it will
fixup all your files

**Comment by richardkaplan** [comment]
solved. - thanks
