### ISSUE TITLE
Lookup stops working properly after pressing tab

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2550]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After pressing the tab key in the lookup box it stops working properly.

## To Reproduce

1. Create notes `foo.foo`, and `foo.bar` (without having a `foo`)
2. Open lookup
3. Type `fo` and press tab
4. Now type `.baz` 
5. Note that your lookup now reads `foo.baz` yet the stub `foo` is still selected in the drop down list and "Create new" is not auto selected
    1. EDIT: Also note that the dropdown still shows `foo.foo` and `foo.bar` while if you had typed `foo.baz` without using tab completion the drop down would only show "Create new" as no existing notes match your filter
6. Try selecting "Create new" and observe that you're prompted to select a vault even if you have the "automatically create in the same vault as currently" option set

I'm not sure exactly what's going on, but I've noticed it a few times in different contexts, mostly when trying to auto complete and create new notes in existing hierarchies. It seems like things start to behave differently after the tab completion.

## Expected behavior

In the example above, I expect to be able to tab complete parts of existing hierarchies, type a new suffix, and then press enter to create a new note with that name.

**Comment by Harshita-mindfire** [comment]
Thanks @chmac for reporting the issue. I can repro it. It seems lookup is only considering the value that is populated with pressing `Tab`, and everything typed after it is ignored. We will let you know once this is fixed 🙏

**Comment by aleksey-rowan** [comment]
Would this be related to or a duplicate of 2579?

- https://github.com/dendronhq/dendron/issues/2579

**Comment by chmac** [comment]
I think #2579 is a duplicate of this.

**Comment by kevinslin** [comment]
should be fixed when #2623 is shipped next week

**Comment by aleksey-rowan** [comment]
Hi, @chmac, the fix for this has shipped in [0.88](https://wiki.dendron.so/notes/9bc92432-a24c-492b-b831-4d5378c1692b/#fix-3). Could you please double check if this is resolved for you? Thanks!

**Comment by chmac** [comment]
Delighted to report this appears to be fixed for me! 🧡
