### ISSUE TITLE
Could Dendron embed mp4 file?

### ISSUE THREAD

**Issue by aQuaYi** [dendronhq/dendron#256]
Obsidian could embed mp4 file as ![[xxx.mp4]]

But Obsidian's vim plugin is not good.

So dendron can  embed mp4 is the best thing.

Could it?

**Comment by kevinslin** [comment]
It doesn't auto convert links but you can use html to embed mp4s right now. have you tried the following snippet?

```
<audio controls="controls">
  <source type="audio/mp3" src="filename.mp3"></source>
  <source type="audio/ogg" src="filename.ogg"></source>
  <p>Your browser does not support the audio element.</p>
</audio>
```

**Comment by kevinslin** [comment]
Closing this for now. Feel free to re-open if you wanted to follow up on this

**Comment by aQuaYi** [comment]
@kevinslin thanks for your reply.
