### ISSUE TITLE
Restore the selective publishing option at the line level

### ISSUE THREAD

**Issue by oolonek** [dendronhq/dendron#2566]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Previously there was an option to selectively omit a line in a Dendron note from publishing. This was a very convenient feature in order to safely publish or version notes containing sensitive passwords, logs sshkeys etc.

## Describe the solution you'd like ##

Restore this feature.

## Describe alternatives you've considered ##

Having the entire note unpublished.

**Comment by oolonek** [comment]
After discussion in Discord with @SeriousBug  the feature I remembered was html based commenting as below.
My feature request is thus no longer required. I keep it open just to add these line to the current selective publishing documentation.

```
Publish this line
<!-- not this line -->
And this line
```

**Comment by Harshita-mindfire** [comment]
Thanks for the suggestion @oolonek. We will update the publishing documentation to include selective publishing.
