### ISSUE TITLE
"Engine not initialized"

### ISSUE THREAD

**Issue by richardkaplan** [dendronhq/dendron#257]
In VSC on Mac, what causes "Engine not initialized" when trying the Build Pod command?

Jekyll is installed and shows "Bundle complete"

![image](https://user-images.githubusercontent.com/6059733/95227370-08f61580-07cc-11eb-9e1a-7caa8b73f38a.png)

**Comment by kevinslin** [comment]
usually this means that you didn't open dendron as a vscode workspace. can you run 'dendron: open log' and paste the output here?

**Comment by richardkaplan** [comment]
solved - thanks
