### ISSUE TITLE
Create New does not show after auto complete is used to complete something

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2588]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After auto complete is used to actually auto complete and then the input is partially or fully erased, `CreateNew` does not show up anymore.

## To Reproduce

1. Activate lookup
2. Actually use autocomplete it on some note that exists (by pressing tab)
3. Then modify the input (without de-activating lookup), such that Create new is expected to show. 

## Expected behavior

* Expected: `Create new ` shows up again
* Actual: `Create new` is not shown. 

## Screenshots
Create New is not shown after auto complete is used. 
<img width="1041" alt="Screen Shot 2022-03-17 at 10 13 02 AM" src="https://user-images.githubusercontent.com/4050134/158856605-36cc569a-97b3-4e37-9221-2718c3204e2b.png">

## Desktop (please complete the following information)

- OS: MacOS 11.6.3

- Versions (all that apply to bug):
  - Dendron Extension: 0.86.1
  - VS Code version: 1.65.2

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
ah - we'll have the guy that implemented autocomplete look at it :P

thanks for report, will add to backlog!

**Comment by nickolay-kondratyev** [comment]
Yea totally ok pointing finger at that guy :)

**Comment by aleksey-rowan** [comment]
> Yea totally ok pointing finger at that guy :)

At the office, we always "blame" our students from previous year 😊 You should get yourself some students, Kevin :)

**Comment by aleksey-rowan** [comment]
This could be also related to 

- https://github.com/dendronhq/dendron/issues/2550

There is a whole slew of new issues involving autocomplete in lookup.

**Comment by Harshita-mindfire** [comment]
This should be fixed after v88 of Dendron. Please post here if not, otherwise, this issue will auto close in 3 days.
