### ISSUE TITLE
.md domains don't render properly in preview

### ISSUE THREAD

**Issue by personjerry** [dendronhq/dendron#2594]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Links ending in .md don't render properly in the preview panel. Might affect other uncommon domains too.

## To Reproduce

1. Put this in a note: `[[https://www.obsidian.md/]]`
2. View Markdown Preview
3. In preview, see link to `https://www.obsidian` instead of `https://www.obsidian.md/` (and indeed clicking the link takes you to the incorrect address)

## Expected behavior

In preview, see a link to `https://www.obsidian.md/`

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
thanks for this. @SeriousBug do we actually formally support wiki links to urls? it looks like it works but I don't know if we document or intentionally planned on supporting this?

**Comment by SeriousBug** [comment]
We don't actually support using URLs in wikilinks. It does work in most cases, but there are a few known issues like this.

I'd suggest using a regular markdown link instead, like `[text for the link](https://example.md)`.

Fixing these bugs to add support wouldn't be too difficult though, it already largely works.
