### ISSUE TITLE
Make menu items ordinary links on published site; enable right click -> open in new tab

### ISSUE THREAD

**Issue by fnurl** [dendronhq/dendron#2615]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I usually open links in new tabs. However, this is not possible with the menu implementation of the published Dendron sites. The pages seem to have unique URL:s so why not let the menu items link to those pages?

## Describe the solution you'd like ##

Right click on menu item on published Dendron site, be able to open link in new tab etc.

## Describe alternatives you've considered ##

N/A

## Additional context ##

N/A

**Comment by SeriousBug** [comment]
Thanks for catching that, it looks like published sites are using buttons instead of links. Will make sure to fix this so it uses links.

**Comment by SeriousBug** [comment]
Hi! Dendron now uses links instead of buttons in the nav bar with 0.90. Please let us know if you experience any problems after updating and rebuilding your website.
