### ISSUE TITLE
"Create New" is not automatically selected during lookup

### ISSUE THREAD

**Issue by fnurl** [dendronhq/dendron#2616]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After using autocomplete (pressing Tab) in the lookup text field, Dendron no longer automatically selects "Create new" if the typed note does not exist.

## To Reproduce

1. Trigger lookup.
2. Auto-complete to parent note title.
3. Add child name.
4. Pressing enter goes to the found parent note.

## Expected behavior

Step 4 should create a new note.

## Screenshots

https://user-images.githubusercontent.com/106794/159711497-423d3f5e-c66c-4386-bb17-738fe005cc0a.mp4

## Desktop (please complete the following information)

- OS: macOS 12.1
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.86.1
  - VS Code version: 1.65.2
  - Dendron CLI: N/A

## Additional context

N/A

## Dendron Log file

N/A

**Comment by fnurl** [comment]
> Could you please check if linked issue describe your problem?

Yes, I believe my issue addresses the same problem. I guess I just searched for autocomplete and did not find the ones you referenced :)

**Comment by aleksey-rowan** [comment]
Great, thank you for checking! Please, upvote or leave a comment in the linked issue to show you interest in the issue.
