### ISSUE TITLE
Visualize notes and hierachies as Mindmap

### ISSUE THREAD

**Issue by ewatch** [dendronhq/dendron#264]
**Is your feature request related to a problem? Please describe.**
It's always helpful to visualize knowledge in different ways. The treeview is nice but there could be away to browse knowledge a little bit more in depth and in and isolated way of topics.

**Describe the solution you'd like**
The solution for the missing visualization would be to visualize files and even hierachies as mindmaps.
These hierachies could even be browsable mindmaps.
https://markmap.js.org is a really nice solution which could be integrated as a command to be applied on a note or hierachie

**Additional context**
When creating knowledge I though it would be helpful to visualize the knowledge myself with a mindmap and then searched for solutions how markdown could be converted to a mindmap.

**Comment by kevinslin** [comment]
Thanks for the feature request! This is something we'll definitely be implementing since mindmaps are a very natural extension of dendron's hierarchies. October is already [filled with existing work](https://dendron.so/notes/6e4c4f61-80a3-46fa-9ad3-04b99d9e9695.html#epics) but I will slot this in for a November feature :)

**Comment by kevinslin** [comment]
Updating this ticket with link to [proposal](https://dendron.so/notes/533857a4-3dcb-478e-9877-5ab7f94ed6e6.html)  from @huwm

**Comment by kpathakota** [comment]
#615 should cover what's being asked in this issue. @ewatch - looks like there's no a vs code extension for markmap so we're closer than before! https://marketplace.visualstudio.com/items?itemName=gera2ld.markmap-vscode. 

Closing for now unless there's something else being asked for here.
