### ISSUE TITLE
Dendron Tree view is not visible in VS Code OSS in Linux (Manjaro)

### ISSUE THREAD

**Issue by rdndas** [dendronhq/dendron#2642]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Dendron Tree view is not visible in Code OSS

## To Reproduce

1. Open VS Code OSS
2. Initialize a Dendron workspace 
3. Expected: On the explorer bar, there is a Dendron Tree view
4. Actual: No Dendron Tree view available in the explorer side bar. Also there is no option to add it to the view from the explore more options menu.

## Expected behavior

Able to view the Dendron tree view on the Explorer pane.

## Screenshots

![image](https://user-images.githubusercontent.com/1344443/160253551-0c23e636-2db8-4fba-aa33-0bc51c57dfeb.png)

![image](https://user-images.githubusercontent.com/1344443/160253604-a2bb392b-6890-4cc6-a14f-3709aae2592c.png)

## Desktop (please complete the following information)

- OS: Manjaro
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: v 0.87.0
  - VS Code version: Code OSS (1.651
            Version: 1.65.1
            Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
            Date: 2022-03-08T18:39:38.183Z
            Electron: 13.6.9
            Chromium: 91.0.4472.164
            Node.js: 14.16.0
            V8: 9.1.269.40-electron.0
            OS: Linux x64 5.16.16-arch1-1-surface

![image](https://user-images.githubusercontent.com/1344443/160253651-0c71f805-52d3-48ad-914f-ef42635807ae.png)

## Additional context

This is the OSS version of Code downloaded from pacman distribution and not from Microsoft's website.
-

## Dendron Log file

```

{"level":30,"time":1648320974733,"pid":4498,"hostname":"w1nl1n","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1648320974793,"pid":4498,"hostname":"w1nl1n","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/home/rdndas/.config/Code - OSS/logs/20220326T135611/exthost1/dendron.dendron","extensionPath":"/home/rdndas/.vscode-oss/extensions/dendron.dendron-0.87.0","extensionUri":"/home/rdndas/.vscode-oss/extensions/dendron.dendron-0.87.0","workspaceFile":"/home/rdndas/Dendron/dendron.code-workspace","workspaceFolders":["/home/rdndas/Dendron/vault"]}
{"level":30,"time":1648320974793,"pid":4498,"hostname":"w1nl1n","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1648320974793,"pid":4498,"hostname":"w1nl1n","name":"SegmentClient","msg":"user telemetry setting: disabled by command"}
{"level":30,"time":1648320974794,"pid":4498,"hostname":"w1nl1n","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1648320974795,"pid":4498,"hostname":"w1nl1n","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.87.0","previousWorkspaceVersion":"0.76.0","previousGlobalVersion":"0.87.0","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1648320974810,"pid":4498,"hostname":"w1nl1n","name":"SegmentClient","msg":"user telemetry setting: disabled by command"}
{"level":30,"time":1648320974810,"pid":4498,"hostname":"w1nl1n","name":"dendron","msg":"Telemetry is disabled? true"}
{"level":30,"time":1648320974811,"pid":4498,"hostname":"w1nl1n","name":"dendron","msg":"Segment Residual Cache Path is at /home/rdndas/.config/Code - OSS/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
{"level":30,"time":1648320974811,"pid":4498,"hostname":"w1nl1n","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1648320974812,"pid":4498,"hostname":"w1nl1n","name":"migration","migrations":[["0.83.0",["migrate config"]]]}
{"level":30,"time":1648320974812,"pid":4498,"hostname":"w1nl1n","name":"logger","ctx":"applyMigrationChange","name":"migrate config"}
{"level":30,"time":1648320974826,"pid":4498,"hostname":"w1nl1n","name":"logger","msg":"creating backup","backupPath":"/home/rdndas/Dendron/.backup/config/dendron.2022.03.26.135614813.migrate-configs.yml","pathToBackup":"/home/rdndas/Dendron/dendron.yml"}
{"level":30,"time":1648320974826,"pid":4498,"hostname":"w1nl1n","name":"logger","msg":"ensureBackupDir"}
{"level":30,"time":1648321635112,"pid":4498,"hostname":"w1nl1n","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1648321635117,"pid":4498,"hostname":"w1nl1n","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1648321635140,"pid":4498,"hostname":"w1nl1n","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}

```

**Comment by SeriousBug** [comment]
Hi, I can't seem to be able to reproduce this problem.

![image](https://user-images.githubusercontent.com/1008124/160454974-42601d5c-1575-4baf-9b62-af436268d269.png)

It seems to be fully missing in your screenshot. A few questions:
- Does other Dendron features like lookup (Ctrl+L) work?
- Does it work with a new workspace ("Dendron: Initialize Workspace" command)?
- Is there any chance you could have dragged the tree view into a new container, like this:

![image](https://user-images.githubusercontent.com/1008124/160455386-715d264c-8755-4ae2-a1b4-2b5be00bf46c.png)

**Comment by rdndas** [comment]
Sorry. It was an issue with the vault that I had opened. Looks like there was an existing vault. I opened a fresh vault and it works fine.
