### ISSUE TITLE
Wrong preview/linking when hierarchy segment starts with "md"

### ISSUE THREAD

**Issue by gbieging** [dendronhq/dendron#2644]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When creating a link to a note and one of the hierarchy segments starts with "md" the preview shows the link with only the part before that segment, clicking it also opens a note with only the fast part as the name.

## To Reproduce

1. Open a note
2. Write a link with a ".md" somewhere (e.g.: [[lorem.ipsum.mdolor.sit.amet]])
3. Open preview
5. Click link
6. Wrong note opens

## Expected behavior

The full link name to appear and clicking to go to the correct note

## Screenshots

![image](https://user-images.githubusercontent.com/14062649/160456209-38f70988-eb0c-4ef2-b584-5164196f8d53.png)

## Desktop (please complete the following information)

- OS: Windows
- Browser: N/A
- Versions (all that apply to bug):
  - Dendron Extension: 0.87.0
  - VS Code version: tested with 1.63.2 and 1.65.2
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment]
Thanks for reporting this problem, I can reproduce it. We'll fix this as soon as possible.

**Comment by aleksey-rowan** [comment]
A very similar issue was reported last, but it was closed as it referred to using external links inside a wiki link:

- https://github.com/dendronhq/dendron/issues/2594

Also linking two tangentially-related issues that were fixed before (they both involve having `md` in filename):

- https://github.com/dendronhq/dendron/issues/1972
- https://github.com/dendronhq/dendron/issues/856

**Comment by gbieging** [comment]
I've found two more details that might be relevant: 
- ctrl-clicking the link in the edit pane works correctly; 
- deleting a note created by clicking the broken link gives a warning that the link needs to be updated

**Comment by Harshita-mindfire** [comment]
This should be fixed after Dendron v0.92. Feel free to comment here if that is not the case.
