### ISSUE TITLE
Publishing does not respect local /assets/ folder

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2646]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Images from the `assets/` folder within the repo do not get published.

## To Reproduce

1. create repository with `/assets/` folder that contains an image
2. Add an image to `/assets` folder
3. Link to the image from a note
4. Make sure the image is visible within preview.
5. Publish Dendron.

## Expected behavior

Expected: Images are visible within the published site.
Actual: Images are not visible within the published site.

**Comment by SeriousBug** [comment]
Hi,

Dendron expects the `assets` folder to be inside your vault. Could you try if that works?

Your workspace root is the folder containing `dendron.yml`.
Inside that, you should have a folder named `vault`, and you may have others as well if you have a multi-vault setup. You'll want `assets` inside of that folder.
