### ISSUE TITLE
why a custom Dendron Markdown Preview Enhanced

### ISSUE THREAD

**Issue by StefanoCecere** [dendronhq/dendron#265]
why do you install a custom version of shd101wyy.markdown-preview-enhanced ?
many of us have already the original version installed.. did you modify it?

**Comment by kevinslin** [comment]
The reason we needed to fork shd101wyy.markdown-preview-enhanced is to support Dendron specific features like [note references](https://dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c.html). We'll be updating the configuration in a future release to live under a different namespace so it won't conflict if you have an existing version installed
