### ISSUE TITLE
Code syntax not displayed on my preview notes

### ISSUE THREAD

**Issue by Saadchr** [dendronhq/dendron#2664]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [X] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

My code syntax on my preview notes are not rendering. It seems that css has some trouble to load correctly since the upload of VSCode to 1.66

## To Reproduce

1-On dendron md file, write:
```python
def function(x):
    print(x)
```
2-Show preview

## Expected behavior

The code should be displayed correctly

## Screenshots

<img width="1121" alt="CleanShot 2022-03-31 at 12 30 11@2x" src="https://user-images.githubusercontent.com/74289775/161055075-a7aa7693-1f7f-4051-a57b-871c0029dc55.png">

## Desktop (please complete the following information)

- OS: MAC OS
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.88
  - VS Code version:1.66
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by hikchoi** [comment]
Thanks for creating the issue. We had a chat in Discord.

Since this is resolved by reverting the VSCode version, I'll mark this to automatically close in 4 days.
