### ISSUE TITLE
Lookup & Auto complete: lookup does not do full search after completion is used.

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2666]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Auto complete does not appear to invoke search across all notes after Tab completion is used.

## To Reproduce

Create a new workspace with the following notes:
```
aaa-1.aaaa-2
aaa-1
hi-1
```

1. Activate lookup
2. Type `hi` use Tab to auto complete to `hi-1`
3. With lookup still active:
4. Erase the lookup prompt to look like ``
5. Within the same lookup session type:
6. `a`

## Expected behavior: See all notes matching `a`
```
aaa-1.aaaa-2
aaa-1
```
## Actual Behavior: only `aaa-1` is shown.
```
aaa-1
```

## Screenshots
<img width="867" alt="Screen Shot 2022-03-31 at 2 35 00 PM" src="https://user-images.githubusercontent.com/4050134/161153194-0bd52ab9-9f4f-4b88-8965-bc742c8d5c90.png">

## Desktop (please complete the following information)

- OS: macOS 11.6.4 
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.88.0
  - VS Code version: 1.66.0
  - Dendron CLI:

**Comment by hikchoi** [comment]
Hey @nickolay-kondratyev I can reproduce this. Thanks for the issue 🙂

**Comment by Harshita-mindfire** [comment]
Hi @nickolay-kondratyev, this should be fixed after v0.88 of dendron. Checking if this is still an issue?

**Comment by nickolay-kondratyev** [comment]
@Harshita-mindfire I don't think I am running into this anymore so I from my perspective it is fixed. Thank you!

**Comment by kevinslin** [comment]
:)
