### ISSUE TITLE
Floating node dots in Note Graph

### ISSUE THREAD

**Issue by LamentConfiguration** [dendronhq/dendron#2680]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When viewing the Note Graph for a very new vault where all the notes were created properly using the lookup tool, there are "floating nodes" that replicate the created nodes visible in the "full graph view". The properly connected nodes will open the associated note properly. The floating nodes do not open the note.

## To Reproduce

I am not 100% sure, a similar problem occurred when doing the "Getting Started" tutorial for me.

## Expected behavior

No floating nodes.

## Screenshots

![image](https://user-images.githubusercontent.com/15186074/161456313-feb095e3-0291-4073-8752-e67bcecfc1de.png)

## Desktop (please complete the following information)

- OS: [e.g. iOS] - Windows 10
- Browser (if with published websites; include version): [e.g. chrome, safari] - Not Applicable.
- Versions (all that apply to bug):
  - Dendron Extension: v0.88.0
  - VS Code version: 1.65.2
  - Dendron CLI:  - Not Applicable.

## Additional context

EEEEEEEK! Phantom nodes!

## Dendron Log file
[dendron.log](https://github.com/dendronhq/dendron/files/8405952/dendron.log)

Attached

**Comment by LamentConfiguration** [comment]
Closing and re-starting vscode solved this problem, not sure if reloading will do the same.

**Comment by LamentConfiguration** [comment]
Upon further fiddling around with things. Parts of the preview like "backlinks" aren't updated without a restart of vscode. I've still yet to test if reloading works.

**Comment by hikchoi** [comment]
Hey @LamentConfiguration, thank you for the report. This is likely because the note graph isn't picking up the up to date workspace state. We'll let you know when this gets fixed.

@Harshita-mindfire any progress on this matter? Would the move to event emitters solve this?

**Comment by LamentConfiguration** [comment]
Small update - Reloading VSCode does fix the problem (avoiding a full restart).

**Comment by Harshita-mindfire** [comment]
Hello @LamentConfiguration , we made some changes in version 0.89 of Dendron to sync the graph with the latest changes from workspace. Let us know if this issue is still appears.

**Comment by bitdryvr** [comment]
I am unsure of the proper etiquette to reopen an issue, but I am getting this today. Here are some screenshots to confirm.

![Screenshot 2022-09-22 00 01 19](https://user-images.githubusercontent.com/38570156/191663003-72df45f2-91a3-40f4-9179-0a98681fa14c.png)

![Screenshot 2022-09-22 00 01 57](https://user-images.githubusercontent.com/38570156/191663411-1672ced8-071d-40c1-a46a-f20cff8b21e9.png)

This is on the Linux subsystem on an 8 GB Chromebook. VSCode is fairly recent at version 1.71.1. The orphan dots are from the tutorial originally, but moved them into my own vault. The orphans do not open the note when selected, but their evil twins in the actual connected graph.

**Comment by Harshita-mindfire** [comment]
Hey @bitdryvr, thanks for reporting, we can reopen this right here itself. Also can try Reloading your window and see if the issue still persists?

**Comment by bitdryvr** [comment]
I restarted VSCode and got this error when trying to the node graph: 

"Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.."

There is an update for VSCode. I am going to apply it and restart the machine before trying it all again.

**Comment by bitdryvr** [comment]
Sorry, I ended up making 2 changes and also restarted the machine entirely and now the graph displays correctly. The changes were:
- update to VSCode v 1.71.2
- restarted machine
- after reboot, start VSCode again
- this time, dendron reported two notes with duplicate IDs
- open those two notes, one at a time, and recreated the ID using Note Doctor
- showed the node graph and it looked OK

**Comment by bitdryvr** [comment]
The graph now is much simpler than before the changes and restart. Previously it struck me as too complex and even included some loops. Now it appears much simpler...

![Screenshot 2022-09-22 01 36 14](https://user-images.githubusercontent.com/38570156/191675432-0744e237-7cac-4513-89fb-9d19b41c804b.png)

**Comment by Harshita-mindfire** [comment]
glad it worked out. Feel free to reopen this incase it is still an issue.

**Comment by bitdryvr** [comment]
Any clue as to which of my multiple actions solved it? Again, sorry it was not a cleaner troubleshooting experience.

**Comment by Harshita-mindfire** [comment]
The note graph reflects the engine state. Sometimes, the graph gets out of sync with the engine, the best bet is to try reloading the workspace to sync it again.
