### ISSUE TITLE
Show Preview leads to an error about not being able to register service workers

### ISSUE THREAD

**Issue by paramsingh** [dendronhq/dendron#2694]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Show preview does not render the preview. Instead an error is shown.

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

## To Reproduce

1. Open any note
3. CTRL + Shift + P "Show Preview"
5. See error

## Expected behavior

Should show the preview of the note instead.

## Screenshots

![Screenshot from 2022-04-05 22-36-08](https://user-images.githubusercontent.com/1837631/161811757-16f19749-c2a3-4f10-a4f7-cb990236c7c8.png)

## Desktop (please complete the following information)

- OS: [e.g. iOS]: Ubuntu 20.04

- Versions (all that apply to bug):
  - Dendron Extension: v0.78.0

  - VS Code version: 1.66.0

## Dendron Log file

https://gist.github.com/paramsingh/dcc27cfcc98d10b058f898905f7c098d

**Comment by jonathanyeung** [comment]
Hi @paramsingh - thanks for reporting the issue.  The version you're on v.0.78.0 is a bit stale - can you update Dendron to the latest (v 0.89.0) as of today and see if the issue is still happening?

**Comment by paramsingh** [comment]
Hey @jonathanyeung , thanks for looking into this. I've upgraded to the latest dendron and I still get the same issue :(

**Comment by paramsingh** [comment]
Here are the logs with the latest version: https://gist.github.com/paramsingh/8d5690d961a85326b36e39fe03dd6271

**Comment by jonathanyeung** [comment]
Hi @paramsingh - this kind of message indicates that it's more likely a VS Code issue as opposed to a Dendron issue unfortunately.  Take a look here: https://github.com/microsoft/vscode/issues/122951 - seems like they're scheduling a fix soon?

Does VSCode's built in markdown preview work (you can run the command `Markdown: Open Preview`), or do you get a similar issue?

**Comment by paramsingh** [comment]
Thanks for the pointers @jonathanyeung , it does seem like it was the editor's fault. A restart of the computer seems to have fixed this! Sorry for the trouble and thanks again for the help! I'll close this.

**Comment by jonathanyeung** [comment]
> Thanks for the pointers @jonathanyeung , it does seem like it was the editor's fault. A restart of the computer seems to have fixed this! Sorry for the trouble and thanks again for the help! I'll close this.

No problem - glad the problem has been resolved!
