### ISSUE TITLE
Export pod command shows incorrect placeholder text in prompt

### ISSUE THREAD

**Issue by onwijsbegeerte** [dendronhq/dendron#270]
**Describe the bug**
When using `Dendron: Export pod` placeholder test shows import placeholder text

**To Reproduce**
1. `CMD + shift + p` 
1. Search Dendron: Export pod command
2. Press enter
3. Placeholder text say's "choose pods to import"

**Expected behavior**
Placeholder text should say "choose pod to export"

**Screenshots**
<img width="518" alt="Screen Shot 2020-10-16 at 17 16 32" src="https://user-images.githubusercontent.com/10326855/96276647-92c78f00-0fd3-11eb-9064-a63000d39ab6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 0.12.9

**Comment by kevinslin** [comment]
opps, great catch! just pushed out 0.12.10 but will have this in the next release!

**Comment by kevinslin** [comment]
fixed in 0.13.2
