### ISSUE TITLE
Dendron documentation has some hard to read diagrams

### ISSUE THREAD

**Issue by lexthanthree** [dendronhq/dendron#2725]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features
- [x] Documentation

## Describe the bug

Dendron documentation has some hard to read diagrams

## To Reproduce

go to https://docs.dendron.so/notes/jtHIVXVpyHwRiq3tJBbfq/
look for the sequence diagram for `add a new command`

## Expected behavior

Should be easy to read

## Screenshots

![Screen Shot 2022-04-10 at 9 16 12 PM](https://user-images.githubusercontent.com/43601654/162670374-c7841419-c57c-46b5-a50f-36a9cf1fadae.png)

## Desktop (please complete the following information)

- Browser chrome

**Comment by jonathanyeung** [comment]
Thanks for reporting @lexthanthree - I think the original author of the doc was working with it in VSCode in a dark mode editor.  I've updated the background color to a more neutral tone that can work with both light and dark themes.
