### ISSUE TITLE
siteUrl, assetPrefix aren't prepended to links on dendron publish export

### ISSUE THREAD

**Issue by stevefan** [dendronhq/dendron#2726]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

On a machine without vscode or a dendron extension, I'm trying to use:

`npx dendron publish export`

to generate a static html site. After the build process concludes, my site does not have the appropriate siteUrl or assetPrefix prepended to html links.

## To Reproduce

In the bash shell:
1. npm i @dendronhq/dendron-cli@latest (0.89)
2. copy over dendron.yml and code-workspace files to workspace root
3. cd $dendron_workspace_root
4. npx dendron publish init
5. npx dendron publish export (generates a next site)
6. copy .next/out/* into html served folder (see the bug, css has wrong path, links don't work, etc.)

## Expected behavior

A published and working site with links that include the siteUrl and assetPrefix.

## Desktop (please complete the following information)

- OS: arch
- any browser 
- Versions (all that apply to bug):
  - Dendron Extension: NA
  - VS Code version: NA
  - Dendron CLI: 0.89

## Additional context

Workspace root has a dendron.yml and code-workspace copied over from my machine with vscode and dendron installed which generated said files for this particular vault I'm trying to publish. 

**dendron.yml VERSON 5, publishing section**
publishing:
siteUrl: [https://site.com/]
assetPrefix: [/~user]
enableFMTitle: true
enableNoteTitleForLink: true
enableMermaid: true
enablePrettyRefs: true
enableKatex: true
copyAssets: true
siteHierarchies: - root
writeStubs: false
siteRootDir: docs
seo: 
title: Dendron
description: Personal Knowledge Space
github: enable
EditLink: true
editLinkText: Edit this page on GitHub
editBranch: main
editViewMode: tree
enableSiteLastModified: true
enableFrontmatterTags: true
enableHashesForFMTags: false
enableRandomlyColoredTags: true
enablePrettyLinks: true 

## Dendron Log file

NA(?), using CLI

**Comment by jonathanyeung** [comment]
Thanks for reporting @stevefan - we are tracking.

**Comment by kevinslin** [comment]
hey @stevefan are you still seeing this issue? this should have been fixed
