### ISSUE TITLE
Mistake in documentation example regarding Folding in md.

### ISSUE THREAD

**Issue by dmytro-shapovalov** [dendronhq/dendron#2729]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

There is an example of Folding feature in the [docs](https://wiki.dendron.so/notes/ba97866b-889f-4ac6-86e7-bb2d97f6e376/#folding). The markdown in the extended section isn't recognized and stays raw. It is because of the two spaces marked with the arrow on my screenshot.

## To Reproduce

1. Go to https://wiki.dendron.so/notes/ba97866b-889f-4ac6-86e7-bb2d97f6e376/#folding
2. Expand the section in the example.
3. Observe raw markdown.

## Expected behavior

The markdown in the section should be rendered as well as the markdown outside the section.

## Screenshots

![image](https://user-images.githubusercontent.com/35997118/162757626-03df57ef-e093-45ca-b5bf-1a9aebbe7a6e.png)

**Comment by jonathanyeung** [comment]
Sharp eye @dmytro-shapovalov - thanks for pointing this out.  I've fixed the example and added a quick note about the whitespace gotcha: https://wiki.dendron.so/notes/ba97866b-889f-4ac6-86e7-bb2d97f6e376/#folding
