### ISSUE TITLE
no such file or directory, open 'rendererLog'

### ISSUE THREAD

**Issue by bs** [dendronhq/dendron#277]
**Describe the bug**
When I enter [Developer: Toggle Keyboard Shortcuts Troubleshooting](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings) from the Command Palette and then press a key, I see a continuous stream of:

`[2020-10-18 21:52:53.387] [renderer4] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'`

in the console. This seems to be along the same lines as [this bug](https://github.com/shardulm94/vscode-trailingspaces/issues/22).

**Desktop (please complete the following information):**
 - OS: macOS (Catalina)
 - Browser Firefox

**Additional context**
<3

** Dendron Log file**
Can dm you the logs if need-be!

**Comment by kevinslin** [comment]
thanks for digging into this. will take a look and try to resolve today if it is the same as the bug you linked to

**Comment by kevinslin** [comment]
so did some digging. i remember seeing these issues but don't see them anymore. if you debug Dendron with `Run Extension --disable extensions`, do you still see this issue?

**Comment by bs** [comment]
Mysteriously, they are gone now for me, with extensions enabled. 👻
