### ISSUE TITLE
Note Graph is messy

### ISSUE THREAD

**Issue by cong-han** [dendronhq/dendron#2775]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
![image](https://user-images.githubusercontent.com/85374314/163673052-0b42ba10-d293-4a70-a12b-fba64622440b.png)
why the note graph is messy like this?

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Hi @cong-han the `Full Note Graph` displays connection to all the notes in the workspace. You can toggle to `Show Local Graph` which displays a graph of your current note and immediate neighbors. In the top left of graph lives the graph filter view. This UI element contains information about the graph and various filtering options.
You can zoom in and zoom out to see more details about the note. More info [here](https://wiki.dendron.so/notes/587e6d62-3c5b-49b0-aedc-02f62f0448e6/)

**Comment by harvastum** [comment]
I assume that @cong-han dislikes the inconsistency in graph edges angles. The graph drawing algorithm could definitely use an upgrade. See https://en.wikipedia.org/wiki/Force-directed_graph_drawing
