### ISSUE TITLE
Browse Note doesn't work with Gitea

### ISSUE THREAD

**Issue by KucharczykL** [dendronhq/dendron#2776]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When using the command `Dendron: Browse Note`, the URL is incorrect when using Gitea. The URL difference demonstrated on an unrelated file:

GitHub: `$DOMAIN/$USER/$REPOSITORY/blob/$BRANCH/$FILE`
Gitea: `$DOMAIN/$USER/$REPOSITORY/src/branch/$BRANCH/$FILE`

## To Reproduce

1. Open a note
2. Bring up the Command Palette with Ctrl+Shift+P
3. Search for and use the `Dendron: Browse Note` command

## Expected behavior

The URL should correctly open.

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: v0.90.0
  - VS Code version: 1.62.2
  - Dendron CLI: 0.90.0

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Thanks @KucharczykL for the bug report

**Comment by kevinslin** [comment]
closing in favor of #2777
