### ISSUE TITLE
Tuning "canonical" formatting options

### ISSUE THREAD

**Issue by LukeCarrier** [dendronhq/dendron#278]
**Is your feature request related to a problem? Please describe.**
A few Dendron operations such as note renames and hierarchy refactorings convert source notes to Dendron's "canonical" representation. This format isn't documented outside of Dendron's source code, and it's not currently configurable to match different formats.

**Describe the solution you'd like**
The ability to configure some formatting options in `dendron.yml` would be great. Off the top of my head:

* Insert blank line under headings?
* Insert blank line under frontmatter?
* Indentation format
	* Indent type (spaces, tabs)
	* Indent size
* Bulleted list character (`-`, `*`)

Where there's overlap, I'd appreciate a 1:1 mapping to the corresponding [EditorConfig](https://editorconfig.org/) options.

**Describe alternatives you've considered**
Documenting the existing canonical format would help us remain consistent with it.

**Additional context**
[Discord thread](https://discord.com/channels/717965437182410783/748936364283920495/767804976625221633)

**Comment by kevinslin** [comment]
This is a great suggestion and I've been waiting for someone to bring it up. I've done a little writeup about how formatting works today and what it takes to change it. 


# Formatting Settings

Dendron currently will auto-format notes during `Rename` and `Refactor` operations when links inside a note need to be replaced.

The formatting options are defined [here](https://dendron.so/notes/849ee8ee-05a5-47bf-b44d-d7c257117bc4.html#renaming-a-note).

These are [rough notes](https://dendron.so/notes/849ee8ee-05a5-47bf-b44d-d7c257117bc4.html#flow) of how formatting gets called during rename

To make this customizable, the following changes need to be made:

- [ ] update the [DendronConfig type definition](https://github.com/dendronhq/dendron/blob/master/packages/common-all/src/types.ts#L405:L405)
- [ ] update [config defaults](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/config.ts#L42:L42)
- [ ] pass in formatting options from the [plugin](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/commands/RenameNoteV2a.ts#L137:L137)
- [ ] accept formatting args in the [server](https://github.com/dendronhq/dendron/blob/master/packages/api-server/src/routes/note.ts#L38:L38)
- [ ] accept formatting args in the [engine](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/enginev2.ts#L249:L249)
- [ ] accept it when [replacing links](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/topics/markdown/utilsv2.ts#L85:L85)
- [ ] accept it in [remark pipeline](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/topics/markdown/utilsv2.ts#L41:L41)


When all this is done, we can add tests that the formatting behavior works
- [ ] [engine tests](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/__tests__/enginev2.spec.ts#L652:L652)
- [ ] [plugin test](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/test/suite-integ/RenameNoteV2.test.ts#L157:L157)

The above changes are for `Rename`. `Refactor` calls rename in a loop so changing rename should update refactor as well.

**Comment by kevinslin** [comment]
As you can see, there ends up being quite a number of places to change. @LukeCarrier let me know if this is something that you are interested in taking on. An easier place to start might be to make formatting configurable and implementing the `lint --fix` option in the `dendron-cli`  https://github.com/dendronhq/dendron/issues/279

**Comment by kpathakota** [comment]
I think this is a good mid size task with a lot of impact. Do you agree @kevinslin?

**Comment by kevinslin** [comment]
Yep!

**Comment by kevinslin** [comment]
this issue has been fixed (we no longer format notes). closing :)
