### ISSUE TITLE
Received message "GoToSiblingCommand: You found a bug! "

### ISSUE THREAD

**Issue by HopperTech** [dendronhq/dendron#2780]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
I believe this is related to lookup, I was using the keyboard shortcut Ctrl + Shift + [ to navigate to a sibling, and received this error message. I tried the command again and it worked. I have attached my dendron.log file

## To Reproduce

IDK
But I have attached the log file below

## Desktop (please complete the following information)

- OS: Windows
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.90.0
  - VS Code version: 1.67.0-insider
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

[dendron.log](https://github.com/dendronhq/dendron/files/8505795/dendron.log)

**Comment by Harshita-mindfire** [comment]
Thanks @HopperTech for the issue and logs. I'll duplicate this issue to this one: https://github.com/dendronhq/dendron/issues/1907
