### ISSUE TITLE
Dendron snippets do not work on encrypted hard drive

### ISSUE THREAD

**Issue by Aodhagan** [dendronhq/dendron#2799]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Dendron snippets do not work when the Dendron workspace is on an encrypted hard drive 

## To Reproduce

1. Encrypt a hard drive - I used Windows Bitlocker and a USB drive
2. Create a new workspace using dendron "initialise workspace" in an empty directory on the encrypted USB drive
3. Create a new note - test snippets (they work!)
4. Restart computer
5. access encrypted USB drive by entering password
6. Using vscodium open Dendron workspace, create a new note and try to use a snippet - does not work!

## Expected behavior

Snippets should work

## Desktop (please complete the following information)

- OS: [e.g. iOS] Windows 10
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.91
  - VS Code version: VSCodium 1.66.2
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by Aodhagan** [comment]
As an update, this same problem occurs for me in both VSCode and VSCodium. When I use the command pallette to open up a folder that is defined as a dendron workspace I get the "Dendron is active" popup in VSCode/VSCodium. However snippets dont work although other aspects of the Dendron do work e.g., dendron look up etc.

If I then open up the command pallette and execute "Dendron Change Workspace" and then select the same Dendron workspace folder, Dendron is re-initialised and the snippets work. This occurs for me in both VSCode and VSCodium and is unrelated to whether the workspace folder is in an encrypted hard drive are not (apologies but my initial incomplete testing suggested that it was).

**Comment by kevinslin** [comment]
can you do the following?
1. run `>insert snippet` and make sure your snippet is still there
2. run `>toggle keyboard shortcuts troubleshooting` and tell me what you see when you try to autocomplete a code snippet

**Comment by Aodhagan** [comment]
Apologies, haven't replied up to now as I cannot replicate the issue for the past couple of days. When the above problem occurred it was as if the Dendron Snippets did not exist (despite Dendron being active). There was no error reported in the `toggle keyboard shortcuts troubleshooting` either. Perhaps I will close this issue and I will open another one if the problem re-occurs. 

Apologies for the inconvenience and thank you for the great software! I'm really enjoying using it and is my first attempt at PKM it feels like a real game changer. Thanks again!
