### ISSUE TITLE
Automatic capitalization of titles when created from [[wiki-links]]

### ISSUE THREAD

**Issue by agichim** [dendronhq/dendron#281]
**Is your feature request related to a problem? Please describe.**
Implement automated capitalization of `Heading 1` when creating a new `.md` file from a [[wiki-link]].

**Describe the solution you'd like**
1. Write a [[wiki-link]] and when holding ALT or ALT + CLICK on the content inside the double square brackets it create a new `.md` file with the `title` automatically capitalized. 

**Describe alternatives you've considered**
The extensions that currently allows the above is Markdown Note `kortina.vscode-markdown-notes`.
It works by holding ATL + CLICK on the content inside the double square brackets. See .gif below.

**Additional context**
When Dendrons extensions are active this functions doesn't work. Ideally would be if the automatic capitalization would work in the `title` in the Schema.

![image](https://user-images.githubusercontent.com/51931067/96580738-a6733e00-12d0-11eb-8141-7c4645f53e67.png)

See .gif of this working. Where nouns are capitalized and the rest of the words are not. I don't know what module/framework that extension uses for capitalization.
![dendron-capitalization](https://user-images.githubusercontent.com/51931067/96580560-6318cf80-12d0-11eb-9759-5bd2a56828ba.gif)

**Comment by agichim** [comment]
Additional request:

With Dendron extensions enabled when holding ALT and hovering the cursor over the wiki-link it create a new `.md` file with the Schema and with a Heading 1. The Heading 1 should be subject to the same capitalization function.

**Comment by kevinslin** [comment]
Thanks for the request. Will add this as a configurable option when creating a new note

**Comment by kevinslin** [comment]
this has been implemented now a few versions ago. closing
