### ISSUE TITLE
Allow tag hierarchy to aggregate backlinks

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2810]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Allow finding notes (using backlinks) that are tagged with all the children of the tag note.

### Example
Let's say a tag is used as `#ai` = Action item. Which refers to general action item. 

However, if tag hierarchy is used it can be specified as `#ai.jon`. Or further subdivision `#ai.developers.jon` , `#ai.marketing.emily`. Now if you go to `#ai` it would be nice to see all notes that were tagged with either:

* plain `#ai` to fin all notes that were tagged with `#ai` or `#ai.marketing` or `#ai.marketing.emily` 
*  `#ai.marketing` to find all notes with `#ai.marketing` or `#ai.marketing.emily` 

To not interfere with current behavior this can be a configuration. However, I think this behavior is very intuitive and the configuration should be set to `true` for aggregating backlinks of tagged sub hierarchies. 

We can see how this use case is quite general for better organization of information by tagging. And partially adds support for secondary tree organization.

## Describe alternatives you've considered ##

There really isn't one for this use case, as far as I understand. 

## Additional context ##

The implementation would require collecting all the backlinks of all the notes in the subhierarchy of the `tags` note that is currently being operated upon.

**Comment by kevinslin** [comment]
currently, the way you could do it is by doing a ctrl+f on `#ai`. but it's definitely not ideal. we will add it as a crop :)

**Comment by nickolay-kondratyev** [comment]
`CTRL+F` is quite useful fallback in the current state, for many use cases. 

Do you know if there is way to customize VSCode `CTRL+F` to auto exclude `.dendron.cache.json` file contents (without having to type in the file in `exclude` box. 
<img width="824" alt="Screen Shot 2022-04-22 at 6 27 10 PM" src="https://user-images.githubusercontent.com/4050134/164859380-5eab3fb9-a5df-447e-837a-8f41eb6ce0fe.png">

**Comment by aleksey-rowan** [comment]
@nickolay-kondratyev, you can exclude `cache` in your settings (user or workspace):

```json
    "search.exclude": {
        "*.cache.*": true,
    },
```

**Comment by aleksey-rowan** [comment]
This tag aggravation sounds a bit like another issue asking to include note descendants into backlinks:

- https://github.com/dendronhq/dendron/issues/212

Is this related? If so, maybe both could be solved by a common approach.

**Comment by aleksey-rowan** [comment]
Closing as duplicate in favour of 

- https://github.com/dendronhq/dendron/issues/212
