### ISSUE TITLE
Include note titles in the lookup indexing

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2813]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Dendron is designed to have shorthands for the note hierarchy names. However, the titles of the notes are often expanded and give much more human readable names ->  **Make the note look up take into account the note titles to allow for more comprehensive look up results.**

For example when I come into someone else knowledge base and search for `typescript  build` if that person followed the Dendron suggested practice of short-handing Dendron top level hierarchies I would actually get 0 results since that person would likely shorthanded TypeScript to `ts` and his hierarchy for the note I was looking for looks along the lines of `l.ts.build` while it seems very reasonable to see `l.ts.build` to show up in the lookup results for `typescript build` (due to note titles being `Programming Languages.Typescript.Build` in the outlined example) 

## Describe the solution you'd like ##

Include titles of the note into the fuseJS lookup index. 

To avoid having the `titles` overpowering note name lookups. Another index can be used which includes the titles. While the original index only contain note names. The results from the second index (index which includes note file names and note titles) would have lower priority than the results from the first index. 

## Describe alternatives you've considered ##

Using VSCode search...

**Comment by kevinslin** [comment]
this is similar to #1198 and #394. closing in favor of #394
