### ISSUE TITLE
Preview Collapsible view does not appear to support images

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2814]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Using images in collapsible markdown syntax does not appear to support images. 

## To Reproduce

Add image into collapsible markdown syntax, render dendron preview. 

```
<details>
<summary>How to Open Terminal</summary>
  
![img](/assets/images/Screen_Shot_2022-04-22_at_8.18.21_PM.png){width: 500px}
</details>
```

## Expected behavior

Image is shown in preview one the collapsible section is expanded. 

## Screenshots

<img width="835" alt="Screen Shot 2022-04-22 at 8 21 43 PM" src="https://user-images.githubusercontent.com/4050134/164873276-e398c536-468b-4085-ba8f-a73f4d58d52d.png">

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.91
  - VS Code version:
  - Dendron CLI:

**Comment by nickolay-kondratyev** [comment]
Adding another space appears to fix the issue. 

```
<details>
<summary>How to Open Terminal</summary>
  

![img](/assets/images/Screen_Shot_2022-04-22_at_8.18.21_PM.png){width: 500px}
</details>
```

**Comment by kevinslin** [comment]
thanks for the report. i believe this is because we parse <detail>...</detail> as a raw HTML block so mixing and matching markdown inside of HTML might not be easily supported. will do some digging here

**Comment by nickolay-kondratyev** [comment]
Possibly just adding documentation that extra line needs to be used might be give the 80/20 for now.

**Comment by kevinslin** [comment]
Added a link to this in the docs: https://github.com/dendronhq/dendron-site/commit/d302b4ee265688a4cba5abc47594ced2dc2d0741

Thanks for providing the workaround!
