### ISSUE TITLE
As a user, I want a clear indication if my sync succeeded or not

### ISSUE THREAD

**Issue by avhb** [dendronhq/dendron#2816]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Context: I am using a workspace with a remote vault (hosted on github)

When I am syncing my remote vaults using the Dendron: Workspace: Sync command. I see a notification that says: "tried pulling 1 and pushing 1 repo", I find this to be too ambiguous (especially the word "tried")? I'm always in doubt if it actually succeeded or not.

## Describe the solution you'd like ##

 A better way (imo) would be to clearly print that the push/pull succeeded or not. That way I can see at a glance if my notes are synced or not.

Example: "Sync succeeded, pulled x repos (updated ... files), pushed y repos (updated ... files)."

## Describe alternatives you've considered ##

minimal work: just remove the word "tried" and rephrase a bit, it casts doubt.

## Additional context ##

![image](https://user-images.githubusercontent.com/66175168/165148443-bcf95aca-b9d8-48a5-8203-6733fbcabd02.png)

**Comment by avhb** [comment]
want to fix this myself if possible, first time contributer, I already cloned the repo, created a branch, and committed locally, but I am unable to push my branch and create a PR, probably due to permission issues

**Comment by SeriousBug** [comment]
Hey @avhb, looks like we missed your reply! If you are still interested in contributing, what you want to do is fork this repository (there's a fork button at the top, on the main page of the repo). You'll then push your changes to your own repo, and send a pull request. Github has instructions here: https://docs.microsoft.com/en-us/learn/modules/contribute-open-source/3-contribute

**Comment by kevinslin** [comment]
closing now. thanks @avhb for the fix :)
