### ISSUE TITLE
Publishing: Change the naming of published 'Children' pages to something that is intuitive to non-dendronite

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#2824]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I showed a published Dendron website to one of my friends, and the first things she said "`Children` what do you mean by children?" (Referring that she thought it was literal 'Children' meaning in her mind instead of Child Notes) 

## Describe the solution you'd like ##

Rename "Children" heading for child notes to something that is intuitive to non Dendron initiate :)

Something like "Sub pages" comes to mind. 

## Describe alternatives you've considered ##

Alternative modify the output of publishing.

**Comment by SR--** [comment]
I agree, causes confusion here too. It is especially confusing if the note content deals with children. :)

**Comment by Harshita-mindfire** [comment]
Hey @nickolay-kondratyev , This is configurable with the `hierarchyDisplayTitle` config under publishing namespace.
Click [here](https://wiki.dendron.so/notes/fJtzFwKpMU9hrYBBvwTcY/) for more info.
