### ISSUE TITLE
Onboarding on dendron is a nightmare

### ISSUE THREAD

**Issue by cognominal** [dendronhq/dendron#2830]
I have seen the videos. I am sold. But I am stuck too.

Attempting to create a vault on an existing .git repo results in an unhelpful message :

![image](https://user-images.githubusercontent.com/16176/165367804-f9bc4b28-54f3-4f5a-afbd-67896f0ffc8f.png)

Suggestions :

Makes  ⌘l  more a main entry point for beginners.
It should also be used to create a vault.

Vault creation error should be more explicit even only for the sake of
dendron developers. You would have better bug reports than this one.

**Comment by SeriousBug** [comment]
Hi, sorry you're hitting problems on onboarding!

Could you share more information on how you got this error? It seems that VSCode can't find Dendron commands at all, so the error is happening before Dendron does anything. We'd love to diagnose and fix this issue.

We also offer one-on-one onboarding sessions if you'd like to join one. We can work through solving this issue, and helping you get started. You can see details here: https://wiki.dendron.so/notes/e8d6241e-1708-4bde-bd3d-93b440a1eaad/

**Comment by cognominal** [comment]
More information to come. Here is a start.

I have dendron working correctly  when initialized on an otherwise empty folder.
I got it failing as indicated on existing  unrelated workspaces with many folders.
I have yet to try to initialize dendron when vscode is opened on a folder without existing workspace.

**Comment by SeriousBug** [comment]
Thank you. Here are a few things that would be good to know:

- What operating system is this on? (Windows, Mac, Linux)
- Which version of VSCode are you using? I think it's VSCode insider, is it updated to the latest?
- Which version of Dendron do you have installed? You can see this by clicking on it on Dendron in the extensions panel.

I just tried creating workspaces and didn't get this error, so knowing how and what kind of system the error happened on would be helpful.

**Comment by cognominal** [comment]
Today I got a message about some sort of corruption and asking me to reinstall vscode insiders. I did and dendron seems to work but I had no time to experiment further.
I will keep you posted if the problem reappears.
