### ISSUE TITLE
publish showing broken images when 'assets' dir is not preceded by '/' in image location

### ISSUE THREAD

**Issue by lexthanthree** [dendronhq/dendron#2860]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When linking to an image with `![](assets/image_name.png)` the image is broken (classic broken image icon) when the site is published. replacing the image tag with `[](/assets/image_name.png)` causes the image to appear

## To Reproduce

1. manually add an image to the assets folder
2. in a note link to the image as `![](assets/image_name.png)`
3. publish the notebook
4. go to the page and see the image is broken

## Expected behavior

Image should render

## Screenshots

Can't screenshot from a work computer sorry :(

## Desktop (please complete the following information)

- OS: MacOS 12.3.1
- Browser (if with published websites; include version): Chrome

**Comment by SeriousBug** [comment]
Thanks for the report, I identified the issue and I'm working on a fix. I'll let you know when this is fixed.

**Comment by taranlu-houzz** [comment]
I think I just ran into this issue as well. As far as I know, I am using the latest version of Dendron and Dendron cli.

**Comment by SeriousBug** [comment]
@taranlu-houzz The fix I mentioned is out now as well, please try publishing again after updating Dendron CLI. Let us know if you continue to have any issues with the image links.
