### ISSUE TITLE
Paste Image on macos 12.3.1 pasting the png icon instead of the png itself

### ISSUE THREAD

**Issue by lexthanthree** [dendronhq/dendron#2861]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Copying an image on macos and pasting it pastes a literal png icon in the assets directory

## To Reproduce

1. open finder
2. select png
3. copy png
4. go to dendron note
5. ctrl+p paste image
6. go to assets and see that a png icon has been pasted instead of the image

## Expected behavior

The image should be the one that was copied to the clipboard

## Screenshots

Can't exfiltrate data from a work computer easily if i can repro this on my personal computer i will update with screenshot

## Desktop (please complete the following information)

- OS: Macos Monteray 12.3.1
- Versions (all that apply to bug):
  - Dendron Extension: 0.92.1 (i think this is correct its latest as of 4/29/2022)
  - VS Code version: latest as of 4/29/2022 (dont have access to specific version numbers now but if relevant i will retrieve them)

**Comment by kevinslin** [comment]
Are you sure you are copying the image vs the file of the image? See this loom video: https://www.loom.com/share/fc938aaa7a7e433a9d5413114ee11f3e

The first case, I right click the image and click `copy image`. In the second case, I right click the file and copy the file.

**Comment by lexthanthree** [comment]
let me try this out. I have been copying the image file i have never seen this distinction matter before to the point that i didn't even know there was a difference. I will try this out tomorrow and get back to you

**Comment by lexthanthree** [comment]
I finally figured out the best workflow on this (though it could be improved probably Ill make a suggestion at the end)

The best solution here is to do a ! then use the paste file tool in dendron, this allows me to easily import images and display them.

What would be a nice future thing is if paste file coudl identify common image extensions and prepend the ! when pasting

**Comment by kevinslin** [comment]
yep, this also works. the `!` will embed the image. will close this out for now
