### ISSUE TITLE
"Cloning NextJS template..." Seems to be stuck in loop?

### ISSUE THREAD

**Issue by macaodhj** [dendronhq/dendron#2864]
Hello,

I am trying to publish my Dendron workspace using the [Quickstart guide](https://wiki.dendron.so/notes/e5st4LFLtIwwbQmC6JBaF/). I have followed everything step by step, as best I could. When I reach the command **npx dendron publish init** I get a long message followed by "Cloning NextJS template..." with a rotating bar just to the left of this. This final command seems to be stuck in a loop and doesn't end. Any ideas what is happening and how I can fix this?

Here is the long message I get after running **npx dendron publish init** 
![image](https://user-images.githubusercontent.com/85526357/166233810-73a2aa77-e75c-49c9-93fc-9f4b7da46a09.png)

This is the windows location of my workspace (so I believe):
![image](https://user-images.githubusercontent.com/85526357/166233870-f44180ff-8b1b-48e0-b83b-fd58f8730a14.png)

Thanks.

**Comment by SeriousBug** [comment]
Hi, do you have `git` installed? It's required to clone the template. You can install it through [Git for Windows](https://gitforwindows.org/).

**Comment by macaodhj** [comment]
Thank you, that worked.
