### ISSUE TITLE
Dendron .dendron.ws file keeps getting corrupted which prevents dendron from opening the workspace properly

### ISSUE THREAD

**Issue by lexthanthree** [dendronhq/dendron#2869]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Workspace fails to start with pop error `{}` (empty brackets)
Dendron fails to start completely

## To Reproduce

I am not sure it happens on each startup for me (could be related to me running the cli to build my static assets?)
Look in `.dendron.ws` 
notice: `{"version": "dendron-cli", ....}`
replace with `{"version": "0.92.1", ....}`
Save and exit: dendron will now work

## Expected behavior

Dendron starts up and the .dendron.ws file is valid

## Desktop (please complete the following information)

- OS: macos monteray
- Versions (all that apply to bug):
  - Dendron Extension: 0.92.1
  - VS Code version: 1.66.2(universal)
  - Dendron CLI: npx dendron --version reports `0.92.1`

**Comment by SeriousBug** [comment]
Just found the source of this error, I'll try to get a fix out as soon as possible. Thanks for filing the bug report.

**Comment by SeriousBug** [comment]
This bug has been fixed with Dendron 0.94. Please let us know if you continue having issues with it.
