### ISSUE TITLE
Dendron Doctor -> removeStubs resulting in 'no data' prompt

### ISSUE THREAD

**Issue by vmasrani** [dendronhq/dendron#2880]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ x ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I'm trying to remove all empty notes, but get a 'no data' error message when running Doctor -> remove stubs

## To Reproduce

1. Run `Dendron Doctor` from command palette 
2. Select `removeStub`
3. See error

## Expected behavior

I expected all my empty notes to be deleted

## Desktop (please complete the following information)
macOS Big Sur
Version 11.6.5
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor 2.2 GHz Quad-Core Intel Core 17
Memory 16 GB 1600 MHz DDR3
Startup Disk Macintosh HD
Graphics Intel Iris Pro 1536 MB
Serial Number C02VJ1F7G8WN

- Dendron v0.93.0
- VS Code Version: 1.66.2

## Dendron Log file

{"level":30,"time":1651700140453,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","msg":"pre-execute"}
{"level":30,"time":1651700140467,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"DoctorCommand:execute","msg":"pre:Reload"}
{"level":50,"time":1651700140479,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","error":{"name":"DendronError","status":"unknown","payload":"{}"}}
{"level":30,"time":1651700143442,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1651700143442,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700143444,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/vmasrani/dev/phd/dendron/vault/thesis.md"]}
{"level":30,"time":1651700143448,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700143449,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/vmasrani/dev/phd/dendron/vault/thesis.md"}
{"level":30,"time":1651700143538,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":12,"diagnosticsLength":0}}
{"level":30,"time":1651700143720,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":12,"diagnosticsLength":0}}
{"level":30,"time":1651700148684,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","msg":"pre-execute"}
{"level":30,"time":1651700148695,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"DoctorCommand:execute","msg":"pre:Reload"}
{"level":50,"time":1651700148702,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","error":{"name":"DendronError","status":"unknown","payload":"{}"}}
{"level":30,"time":1651700152044,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"NoteLookupCommand:gatherInput","msg":"enter"}
{"level":30,"time":1651700152044,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"LookupControllerV3:new","msg":"enter"}
{"level":30,"time":1651700152045,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"prepareQuickPick","msg":"enter"}
{"level":30,"time":1651700152045,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"prepareQuickPick","msg":"exit"}
{"level":30,"time":1651700152046,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"showQuickPick","msg":"enter"}
{"level":30,"time":1651700152046,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:pre"}
{"level":30,"time":1651700152047,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"thesis","justActivated":true}
{"level":30,"time":1651700152048,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"thesis","profile":1,"cancelled":false}
{"level":30,"time":1651700152048,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"enter"}
{"level":30,"time":1651700152048,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"exit"}
{"level":30,"time":1651700152049,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"showQuickPick","msg":"exit"}
{"level":30,"time":1651700152161,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"thesis","justActivated":false,"prevQuickpickValue":"thesis"}
{"level":30,"time":1651700152162,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"thesis","profile":0,"cancelled":false}
{"level":30,"time":1651700152547,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"f","justActivated":false,"prevQuickpickValue":"thesis"}
{"level":30,"time":1651700152551,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1651700152552,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":4}
{"level":30,"time":1651700152554,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"f","profile":7,"cancelled":false}
{"level":30,"time":1651700152875,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"fran","justActivated":false,"prevQuickpickValue":"f"}
{"level":30,"time":1651700152878,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1651700152878,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1651700152882,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"fran","profile":6,"cancelled":false}
{"level":30,"time":1651700153005,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"frank","justActivated":false,"prevQuickpickValue":"fran"}
{"level":30,"time":1651700153009,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1651700153009,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1651700153010,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"frank","profile":4,"cancelled":false}
{"level":30,"time":1651700153805,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"NoteLookupProvider:onDidAccept","quickpick":"frank"}
{"level":30,"time":1651700153810,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.lookupNote:run","msg":"pre-execute"}
{"level":30,"time":1651700153810,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"enter"}
{"level":30,"time":1651700153883,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1651700153884,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700153886,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/vmasrani/dev/phd/dendron/vault/thesis.frank-comments.md"]}
{"level":30,"time":1651700153888,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700153889,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/vmasrani/dev/phd/dendron/vault/thesis.frank-comments.md"}
{"level":30,"time":1651700153890,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"thesis.frank-comments"}
{"level":30,"time":1651700153894,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"LookupControllerV3:onHide","msg":"exit"}
{"level":30,"time":1651700153894,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"exit"}
{"level":30,"time":1651700153894,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.lookupNote:run","msg":"post-execute"}
{"level":30,"time":1651700153949,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1651700154064,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"exit","fname":"thesis.frank-comments"}
{"level":30,"time":1651700154127,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1651700154557,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1651700154558,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700154559,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/vmasrani/dev/phd/dendron/vault/thesis.md"]}
{"level":30,"time":1651700154563,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700154563,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/vmasrani/dev/phd/dendron/vault/thesis.md"}
{"level":30,"time":1651700154635,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":12,"diagnosticsLength":0}}
{"level":30,"time":1651700154882,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":12,"diagnosticsLength":0}}
{"level":30,"time":1651700161811,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","msg":"pre-execute"}
{"level":30,"time":1651700161820,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"DoctorCommand:execute","msg":"pre:Reload"}
{"level":50,"time":1651700161827,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","error":{"name":"DendronError","status":"unknown","payload":"{}"}}
{"level":30,"time":1651700506932,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","msg":"pre-execute"}
{"level":30,"time":1651700506947,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"DoctorCommand:execute","msg":"pre:Reload"}
{"level":50,"time":1651700506958,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","error":{"name":"DendronError","status":"unknown","payload":"{}"}}
{"level":30,"time":1651700554157,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1651700554159,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700591257,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/vmasrani/dev/phd/dendron/vault/thesis.md"]}
{"level":30,"time":1651700591263,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700591264,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/vmasrani/dev/phd/dendron/vault/thesis.md"}
{"level":30,"time":1651700591335,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":12,"diagnosticsLength":0}}
{"level":30,"time":1651700591525,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":12,"diagnosticsLength":0}}
{"level":30,"time":1651700595031,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","msg":"pre-execute"}
{"level":30,"time":1651700595049,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"DoctorCommand:execute","msg":"pre:Reload"}
{"level":50,"time":1651700595056,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.doctor:run","error":{"name":"DendronError","status":"unknown","payload":"{}"}}
{"level":30,"time":1651700604635,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1651700604635,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1651700604649,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1651700604722,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1651700604722,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700604724,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/vmasrani/Library/Application Support/Code/logs/20220503T163022/exthost1/dendron.dendron/dendron.log"]}
{"level":30,"time":1651700604727,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1651700604729,"pid":1413,"hostname":"dhcp-128-189-64-44.ubcsecure.wireless.ubc.ca","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"dendron.log"}

**Comment by vmasrani** [comment]
Great thanks!

**Comment by Harshita-mindfire** [comment]
This should be fixed with Dendron v0.96. Feel free to comment here if that's not the case.

**Comment by vmasrani** [comment]
Great,  thanks for the fast turnaround time! It's working on my end, with the exception of it deleting all my tags notes which are supposed to be empty. Is there a way to get it to skip all notes starting with `tags.*`?

**Comment by Harshita-mindfire** [comment]
Ideally `Doctor: Remove Stubs` removes all the stubs irrespective of the hierarchy of notes.
