### ISSUE TITLE
Hybrid Hierarchy and free text search

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#2885]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When searching on a dendron site currently there are two options; either search for a specific note by text in the note name/hierarchy,  or use `?` to allow for free text searching within the notes themselves. Sometimes I want to mix these are I know I want to search for some text but only within a specific hierarchy (or sub-hierarchy) of my notes. For example I may want to search only within a `latest` hierarchy for documentation or something like that.

## Describe the solution you'd like ##

A more advanced search capability, at least to be able to define a hierarchy to search `?` style within (maybe using `+`?), but possibly also include the ability to exclude certain hierarchies using `-` , specific text search using `"` etc. similar to google searches. For larger sites this could basically allow better discoverability without having to split up the sites into multiple publishings.

## Describe alternatives you've considered ##

Search and scroll.

## Additional context ##

To be honest not actually sure I fully understand the search engine methodology as is e.g. if I search `?yellow bicycle' does it search for that specific phrase, or either word anywhere in the note (does it prioritise those that are that exact phrase first?) so it may be that some of this is already possible.

**Comment by hikchoi** [comment]
Thank you for the suggestion. We'll keep this in mind when we work on the search capabilities :)
