### ISSUE TITLE
Dendron stopped working after upgrade

### ISSUE THREAD

**Issue by ric03uec** [dendronhq/dendron#2897]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Recently dendron upgraded to v0.93.0 once I restarted VSCode. Post upgrade, dendron fails to initialize.

## To Reproduce

1. upgrade dendron to v0.93.0

## Expected behavior

After upgrading, all features should work as expected (and some bugs should magically get fixed :D  ) 

## Screenshots

![image](https://user-images.githubusercontent.com/1110988/167529938-821512a3-7074-45f5-977b-befe33ce723e.png)
![image](https://user-images.githubusercontent.com/1110988/167529973-c452d65a-1d13-4caa-ae4d-8729a6f99bb1.png)

## Desktop (please complete the following information)

- Versions (all that apply to bug):
  - Dendron Extension: v0.93.0
  - VS Code version: 1.66.2
  - Dendron CLI: 0.93.0
  - Chromium: 98.0.4758.109
  - Node.js: 16.13.0
  - V8: 9.8.177.11-electron.0
  - OS: Linux x64 5.4.0-109-generic

## Dendron Log file

```
{"level":30,"time":1652149504909,"pid":513266,"hostname":"crossbow","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1652149504979,"pid":513266,"hostname":"crossbow","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/home/devashish/.config/Code/logs/20220509T135638/exthost1/dendron.dendron","extensionPath":"/home/devashish/.vscode/extensions/dendron.dendron-0.93.0","extensionUri":"/home/devashish/.vscode/extensions/dendron.dendron-0.93.0","workspaceFile":"/home/devashish/workspace/aartwo/dendron.code-workspace","workspaceFolders":["/home/devashish/workspace/aartwo/ric03uec","/home/devashish/workspace/aartwo"]}
{"level":30,"time":1652149505004,"pid":513266,"hostname":"crossbow","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1652149505004,"pid":513266,"hostname":"crossbow","name":"SegmentClient","msg":"user telemetry setting: enabled by migration"}
{"level":30,"time":1652149505004,"pid":513266,"hostname":"crossbow","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1652149505004,"pid":513266,"hostname":"crossbow","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1652149505004,"pid":513266,"hostname":"crossbow","name":"SegmentClient","msg":"anonymous id","anonymousId":"8f7b6264-659d-4c3c-b3b3-c57121e24d2a"}
{"level":30,"time":1652149505009,"pid":513266,"hostname":"crossbow","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1652149505079,"pid":513266,"hostname":"crossbow","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.93.0","previousGlobalVersion":"0.92.1","extensionInstallStatus":"UPGRADED"}
{"level":50,"time":1652149505119,"pid":513266,"hostname":"crossbow","name":"dendron","stack":"TypeError: Invalid Version: dendron-cli\n    at new u (/home/devashish/.vscode/extensions/dendron.dendron-0.93.0/dist/extension.js:8:2729430)\n    at e.exports (/home/devashish/.vscode/extensions/dendron.dendron-0.93.0/dist/extension.js:8:2733718)\n    at Object.e.exports [as gt] (/home/devashish/.vscode/extensions/dendron.dendron-0.93.0/dist/extension.js:8:2734126)\n    at ma (/home/devashish/.vscode/extensions/dendron.dendron-0.93.0/dist/extension.js:8:3234640)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","type":"Error","msg":"Invalid Version: dendron-cli"}
{"level":30,"time":1652149543863,"pid":513266,"hostname":"crossbow","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1652149543863,"pid":513266,"hostname":"crossbow","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1652149543876,"pid":513266,"hostname":"crossbow","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
```

**Comment by clarkttfu** [comment]
+1

Version: 1.67.0
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:14:47.100Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0

**Comment by hikchoi** [comment]
Sorry about the inconvenience @ric03uec and @clarkttfu. This is a regression on our end.

Please do the following:
1. Go to your workspace root
2. find the file `.dendron.ws`
3. delete it
4. reload VSCode

This should fix the issue immediately. Also, a fix has been published with v94 that will prevent this from happening in the future.

**Comment by hikchoi** [comment]
I've marked this to automatically close in 3 days if there are no other outstanding concerns. If you are still experiencing this, please leave a comment. Otherwise, feel free to close it or leave it open until it automatically closes.

**Comment by ric03uec** [comment]
that worked, closing this. thanks for the quick response!

**Comment by clarkttfu** [comment]
> 

Build 0.94 did not help, but deleting .dendron.ws worked.

**Comment by irishandyb** [comment]
I encountered this issue after the upgrade to 0.94.0.

I just opened #2917 but have closed it as a duplicate of this ticket.

Deleting the .ws file did resolve the issue but it did happen in 94.
