### ISSUE TITLE
Rendering refs: use note title instead of filename?

### ISSUE THREAD

**Issue by prurph** [dendronhq/dendron#290]
**Is your feature request related to a problem? Please describe.**
I would prefer that a block reference with Dendron links show those links as titles instead of filenames. Example:

Say I have a root like `house` and then I have documents related to it in `house.doc`, like `house.doc.mortgage` `house.doc.inusrance`. I would like to do:

```markdown
// root house.md file

# House
## Documents
((ref: [house.doc]]#doc,1))

// house.doc.md
# Doc
[[Mortgage|house.doc.mortgage]]
[[Insurance|house.doc.insurance]]
```

With the expectation that in the root file preview I see *Mortgage* and *Insurance*. Instead I see `house.doc.mortgage.md` and `house.doc.insurance.md`.

**Describe the solution you'd like**
Render Dendron link titles in refs.

**Describe alternatives you've considered**
Make it configurable somehow? It's unclear to me why the current behavior is useful (you could simply omit the title if you wanted this).

Bolder alternative: add some sort of glob ref that automatically adds Dendron links by glob pattern on a page, like `((ref: house.doc.*))`. What I'm really desiring is an inline reference to a set of child notes on a page without having to fire up a separate search editor. 

**Additional context**
Yay for Dendron!

**Comment by kevinslin** [comment]
Thanks for the issue. Title is a good idea. Will add this as a configurable option in the config.

**Comment by elementh** [comment]
This just happened to me too, I'd add that links should work inside references, but maybe it's just me :)

Thanks!

**Comment by kevinslin** [comment]
this is now shipped in the latest release. https://wiki.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f48.html#usefmtitle
