### ISSUE TITLE
VSCode extension install failure 😞 

### ISSUE THREAD

**Issue by fvlasie** [dendronhq/dendron#2910]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

VSCode extension will not install. When offered the option to download manually I get an error back in JSON (see attached)
## To Reproduce

1. Go to https://marketplace.visualstudio.com/items?itemName=dendron.dendron
2. Click on 'Install'
3. In VSCode click 'Install'
4. Click 'Download Manually' when the install error shows.
5. The browser opens with the attached message displayed.

## Expected behavior

Extension should install or download.

## Desktop (please complete the following information)

- OS: MacOS
- Browser (if with published websites; include version): any
- Versions (all that apply to bug):
  - Dendron Extension: 0.94.0
  - VS Code version: 1.23.0
  - Dendron CLI:

[vspackage.json.zip](https://github.com/dendronhq/dendron/files/8672470/vspackage.json.zip)

**Comment by hikchoi** [comment]
VSCode seems to be rate limiting with the number of download request on your end. Did you by any chance download while on a public network that is shared between many machines? (or corporate proxy).

Can you try downloading while on a different network and see if this resolves the issue?

Otherwise, extension authors don't have much control over how the VSCode marketplace works, so you may want to report this issue to VSCode directly: https://github.com/microsoft/vscode

**Comment by SeriousBug** [comment]
Another option would be to manually download from the Open VSX Registry. You can then drag and drop the `.vsix` file into the extensions bar to install it. You would have to manually update it later though, so you might want to solve the problem first. See the download button here: https://open-vsx.org/extension/dendron/dendron

**Comment by fvlasie** [comment]
Thanks for the feedback. I will see what the vscode people say.
