### ISSUE TITLE
Sidebar help and feedback links only open once

### ISSUE THREAD

**Issue by EngineerFaunce** [dendronhq/dendron#2932]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Clicking a link in the 'Help and Feedback' section opens the page in a browser, but if I click the same link again it does not work. If I click another link or the empty area and then the original link again it works.

## To Reproduce

1. Open the Dendron sidebar
2. Expand the 'Help and Feedback' section
3. Click on a link (opens the page)
4. Click on the same link again (second tab does not open)

## Expected behavior

Clicking on the link more than once should open multiple tabs.

## Screenshots

![image](https://user-images.githubusercontent.com/16312436/168813424-cda08b8c-efab-4370-ba5e-2df456a4518c.png)

## Desktop (please complete the following information)

- OS: Windows 10
- Browser (if with published websites; include version): Firefox 100.0 (64-bit)
- Versions (all that apply to bug):
  - Dendron Extension: 0.94.0
  - VS Code version: 1.67.1
  - Dendron CLI: 0.94.0

**Comment by Harshita-mindfire** [comment]
Hi @EngineerFaunce, thanks for reporting the issue. Looking at the code, it appears this is the expected behavior.

@jonathanyeung I see that the Help and feedback panel detect change through [onDidChangeSelection](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/features/HelpFeedbackTreeview.ts#L96:L96) and will open link based on the selection. Do you have any inputs to add here?

**Comment by Harshita-mindfire** [comment]
This should be fixed with Dendron v0.100 Feel free to comment here if that's not the case.
