### ISSUE TITLE
Possible to hide/show dendron tree view/backlinks panes via workspace settings?

### ISSUE THREAD

**Issue by prurph** [dendronhq/dendron#295]
I'd like to always show the backlinks and dendron tree views in the explorer for my dendron workspace, but not my other workspaces. Unfortunately when I right click → toggle them off in another workspace, it removes them from my dendron one as well.

Is there a setting that controls these? I did see [this](https://github.com/dendronhq/dendron/blob/c7a177632dac350a03bb54e84a7e590614cf3dda/packages/plugin-core/package.json#L36) and tried stuff like `explorer.dendronTreeView.visible` and `explorer.dendronTreeView.visibility` in my `settings.json` but it doesn't seem like these are valid settings.

I understand there are commands to focus them, but what I'd like to do is hide/show them from the entire view (i.e. have per-workspace settings for these checkboxes):

![image](https://user-images.githubusercontent.com/6109531/97083306-0de50280-15dd-11eb-8d4f-404653a4219b.png)

Thanks!

**Comment by kevinslin** [comment]
As far as I know, VSCode doesn't offer the ability to toggle treeviews on a per workspace setting (happy to be corrected on this). 

We have an issue to show a [dedicated backlink window](https://github.com/dendronhq/dendron/issues/237) as a pane instead of a tree view. We could also do the same for tree view. Plus have a shortcut to easily bring up these panes. I realize this isn't quite what you wanted but it's probably the closest we can get at this point.

**Comment by prurph** [comment]
Totally understandable—I haven’t found anything to suggest VSCode offers this either. This is a very minor annoyance at worst; I think overall the experience with them as editor panes is great.

I can’t wait to hear how you’re planning to monetize dendron this so I can give you some money for this awesome product! 💸

**Comment by kevinslin** [comment]
One alternative that works well for me is to keep different versions of vscode specific for dendron. you can see the discord thread [here](https://discordapp.com/channels/717965437182410783/735365126227493004/769935222380691466). copied verbatim below in case you don't use discord

```
my setup:
- I keep 3 versions of vscode (vscode, vscode insider, vscodium)
- I have a mac so I usually have two windows of each version running at any time 
    - i'm running on mac so i can toggle between windows using `cmd+~`
- each vscode version also has a custom keyboard shortcut which I've configured using alfred

- vscode versions:
    - vscode: used for coding
    - vscode insider: two windows, one focused on dendron specific notes and one for personal notes
        - both windows use the same vault but different workspaces (this is because vscode does not let you have multiple windows open to the same workspace)
        - because you can define a custom path (https://dendron.so/notes/401c5889-20ae-4b3a-8468-269def4b4865.html) for your vault, you can still point two workspaces to the same vault
    - vscodium: two windows, one focused on https://dendron.so documentation (use as reference as well as to update) and another for an alternate workspace i'm working on (eg. https://aws.dendron.so)

the idea here is that I can access any note in any workspace using at most, two keyboard shortcuts.
```

**Comment by kevinslin** [comment]
as for monetization, Dendron will be coming out of preview in November, at which point we will launch our Environmentalist Plan :evergreen_tree:. This is a monthly subscription to support the development of Dendron. Environmentalist will get a special badge on Discord, priority email/discord access to the development team, and stickers! 

long term, we will also be developing server side additions like private hosting/sharing as well as managed end2end sync. you can read about that [here](https://dendron.so/notes/d892da5f-3667-4bfe-a8ba-e5ea3da4eb72.html) :)
