### ISSUE TITLE
Expose HTTP request from hooks

### ISSUE THREAD

**Issue by Maarrk** [dendronhq/dendron#2964]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

If I want to use external data in a hook, I need to run an executable with execa. This makes the hook dependent on external files and is harder to maintain and share.

## Describe the solution you'd like ##

I'd like it to be a popular, well documented library, to easily find what to do in all edge cases. Definitely needs to support both GET and POST, setting Content-Type, these kinds of things. This would be needed for [JSON RPC](https://www.jsonrpc.org/specification), which I think makes a lot of sense for these integrations.

For the user interface, I would like this to be added to hook arguments in the template:

```js
/**
 @params wsRoot: string, root of your current workspace
 @params note: Object with following properties https://github.com/dendronhq/dendron/blob/master/packages/common-all/src/types/foundation.ts#L66:L66
 @params NoteUtils: utilities for working with notes. [code](https://github.com/dendronhq/dendron/blob/master/packages/common-all/src/dnode.ts#L323:L323)
 @params execa: instance of [execa](https://github.com/sindresorhus/execa#execacommandcommand-options)
 @params fetch: function for HTTP requests with [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)
 @params _: instance of [lodash](https://lodash.com/docs)
 */
module.exports = async function ({ wsRoot, note, NoteUtils, execa, fetch, _ }) {
```

## Describe alternatives you've considered ##

I tried `wget` and `curl`, but on windows it's such a mess to set the options, that I gave up. Besides even if I did, the hook wouldn't work on my other machines with a different OS.

One could also write custom command line executables to get what they need using execa, but that requires considerably more work and a bit of skill.

## Additional context ##

For me the immediate use for this feature would be improving integration with Zotero (academic reference manager) a lot. Let's say you create a note referencing a paper and it [automagically fills with abstract and authors](https://youtu.be/aYnxZ5-XDUs) to find it easily later.

**Comment by kevinslin** [comment]
thanks for the feature request. we've been talking about this internally as well. going to add this as a backlog item as well as a crop candidate
