### ISSUE TITLE
Caching for `Next.js` in GitHub actions workflow does not use correct key

### ISSUE THREAD

**Issue by taranlu-houzz** [dendronhq/dendron#2967]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I am running into an issue with getting the caching for `Next.js` to work via the GitHub actions workflow. Basically, it seems to be in a situation where during the first run, the cache will be generated with a key that does not include the hashes (since `Next.js` has not been initialized yet). I end up getting a cache with a key like this: `Linux-nextjs--`.

It is possible that something else with my setup/workflow is causing this issue (I have needed to tweak the workflow from the example to get things working because of my dir structure), but based on the order of the steps in the example workflow, I would think this would be an issue there too.

## To Reproduce

1. Follow the publishing tutorial: https://wiki.dendron.so/notes/FnK2ws6w1uaS1YzBUY3BR
2. Check the key for the cache after the workflow run.

NOTE: I am assuming this would also happen if following the tutorial, since my setup is a little different.

## Expected behavior

I think what is happening makes sense, and it seems to be a bit of a chicken-and-egg problem. Ideally, the cache key would be generated correctly. It seems like maybe some branching logic could be added to the workflow.

## Desktop (please complete the following information)

- OS: macOS
- Browser: Chrome Version 101.0.4951.64 (Official Build) (x86_64)
- Versions (all that apply to bug):
  - Dendron Extension: v0.95.1
  - VS Code version: 1.67.2
  - Dendron CLI: 0.87.0

## Additional context

I think this might be related to the change made to accommodate this issue: https://github.com/dendronhq/dendron/issues/2355

**Comment by kevinslin** [comment]
thanks for the submission. will investigate!

**Comment by kevinslin** [comment]
Did some digging, you're right - the current gh action instructions will cause you to run the action 3x before the cache keys are populated. I've updated the instructions to fix this - tldr: move the `Initialize or pull nextjs template` job **before** the `Restore Next cache` job. Diff of updated instructions as well as more detailed explanation of whats happening here: https://github.com/dendronhq/dendron-site/commit/22da103ca62993a5b06e039a7b546d0d88c771f3

Can you try this out and let me know if it fixes your issue?

**Comment by taranlu-houzz** [comment]
@kevinslin Hmm, so, that will generate the cache with the correct key, but since the cache is now being read after the step that initializes `next.js`, doesn't that mean that it will still clone down everything each time (since `.next` wouldn't exist yet at that point)? The `.next` dir is being ignored due to the pattern in `.gitignore`.

**Comment by kevinslin** [comment]
nope, because we use a github action to save the .next dependencies (see below). this is independent of the gitignore
there are two caches we are restoring. the first cache restore (pasted below) restores all the node dependencies. the second cache restore caches the results of `next export`

```ts
      - name: Restore Node modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            .next/*
            !.next/.next/cache
            !.next/.env.*
          key: ${{ runner.os }}-dendronv2-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}
```

**Comment by taranlu-houzz** [comment]
@kevinslin Ah, okay, right, that makes sense. As I was tweaking the script, I had removed the `.next` stuff from that step because it looked like it would be grabbing more than just the `.next/node_modules/*` which makes the name "Restore Node modules cache" confusing (is that correct, or am I misunderstanding what all is being cached in that step?).
