### ISSUE TITLE
Optional desc front matter key

### ISSUE THREAD

**Issue by dionysuzx** [dendronhq/dendron#2971]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

## Describe the solution you'd like ##

I want the desc key to be an optional front matter attribute because I don't use it.

**Comment by aleksey-rowan** [comment]
Hi, @dweisiger, thank you for the request!

I'm going to link a discussion you started on the same topic as it explains why optional frontmatter keys could be desiriable:

- https://github.com/dendronhq/dendron/discussions/2912#discussioncomment-2734015

**Comment by kevinslin** [comment]
yeah, lets consolidate it there. i think it'll make sense to make this configurable (eg. show minimal frontmatter). `id` is the only truly required one though `title` is a dependency of many options. we'll probably start by making `updated` and `created` optional and proceed from there
