### ISSUE TITLE
After upgrade to newest version, got "bad path" when I try create today note

### ISSUE THREAD

**Issue by wind13** [dendronhq/dendron#3003]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After upgrade to newest version, got "bad path" when I try create today note.

## To Reproduce

1. Upgrade newest version from 0.82.x
2. Upgrade VSCode also.
3. Try shortcut "Ctrl + Shift + I", got error: "bad path", and cannot create new note.

## Expected behavior

Should create note success, no error display.

## Screenshots

![image](https://user-images.githubusercontent.com/1387020/170851164-a44de6b8-dc96-4c28-bd97-1d11408856e6.png)

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by kevinslin** [comment]
can you paste the output of diagnostics report? hard to work with just this
