### ISSUE TITLE
Unpublished/Private pages -links rendered in published page to be customisable

### ISSUE THREAD

**Issue by AshSimmonds** [dendronhq/dendron#3007]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Any link to a page which in the front-matter is tagged as `publish: false` is rendered to the published referencing page from hardcoded formatting. Colour `brown`; suffix `(Private)`; links to `wiki.dendron.so/notes/hfyvYGJZQiUwQaaxQO27q.html`; no `id` or `class` attributes.

## Describe the solution you'd like ##

More control over what is rendered to the page. At a minimum stop-gap measure adding an `id` and/or `class` attribute so that vault owners can easily enough modify some basic aesthetics via CSS etc.

**Comment by SeriousBug** [comment]
This has been fixed with Dendron 0.99, private links will now have a class on them and won't have a hardcoded color. Please make sure to update both your CLI and template if you are running publishing locally. Let us know if you continue to have issues.

**Comment by rlh1994** [comment]
@SeriousBug I think the merge has covered the colour component but we still want to be able to customise the suffix and the destination of the link itself? I am happy to create another issue but feels cleaner to keep it in this one?

**Comment by SeriousBug** [comment]
@jlongo @rlh1994 I think that should be a different issue, this was just about theming.
