### ISSUE TITLE
Inline math while publishing notes 

### ISSUE THREAD

**Issue by rhaynes74** [dendronhq/dendron#302]
Currently, block math mode is supported while publishing or exporting notes.  It would be great to have inline math supported using the inline math delimiters set in the markdown enhanced preview settings.

**Comment by kevinslin** [comment]
Thanks for the suggestion. Will add this to the publishing, probably, sometime in November will be the rough timeline!

**Comment by kevinslin** [comment]
This is now supported :)

**Comment by rhaynes74** [comment]
Thanks!
