### ISSUE TITLE
Minor problems with PR instructions for new contributors

### ISSUE THREAD

**Issue by Maarrk** [dendronhq/dendron#3024]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

- Some parts of the [community PR template](https://gist.github.com/kevinslin/5d1a6663638259e7dbd33b01975cc00f) are unclear and/or outdated. [see also the comments there](https://gist.github.com/kevinslin/5d1a6663638259e7dbd33b01975cc00f?permalink_comment_id=4122828#gistcomment-4122828)
  - There is no "commit style" section in the [current Commiting Code note](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e/#commit-style), according to @SeriousBug it's outdated
- The linked [Test note](https://docs.dendron.so/notes/FfyL5dSzFwX1iseI56oYy/#run-all-tests) refers to a script `dendron/bootstrap/scripts/testAll.sh` which I don't see in the repo anymore
  - according to @kevinslin the current way is `yarn ci:test:cli`

## To Reproduce

1. Start a new PR
2. Follow instructions for a first time contributor

## Expected behavior

Updated documentation, unfortunately I don't know enough about testing setup to suggest more concrete changes

## Desktop (please complete the following information)

- OS: not relevant, but windows 10 at the moment
- Browser (if with published websites; include version): Firefox 101
- Versions (all that apply to bug):
  - Dendron Extension: 0.97
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by kevinslin** [comment]
took a long time but finally got around to updating the public pr checklist!
