### ISSUE TITLE
Copy Note Link straight from navigator (Cmd+L on macOS) menu

### ISSUE THREAD

**Issue by jamesb93** [dendronhq/dendron#303]
**Is your feature request related to a problem? Please describe.**
I constantly want to make references between notes using Note Links. The Note Link command is very quick for getting the note link, but it requires navigating away from the note you were in in the first place.

**Describe the solution you'd like**
It would be great if you could use the system Copy command to copy a note link from any highlighted result in the Cmd+L navigation GUI.

**Describe alternatives you've considered**
I tend to open the note, bring the command palette up and run copy note from there.

**Additional context**
This is the GUI I am referring to which would be great to be able to copy from.

![image](https://user-images.githubusercontent.com/13281862/97198166-6ca9a800-17a6-11eb-9a5f-a855ed87fb62.png)

**Comment by seedublancaster** [comment]
I love this idea.  I had not even thought of that potential feature, but I can absolutely understand and agree with how useful this would be.

**Comment by kevinslin** [comment]
I'm thinking of the following interface where instead of ok, you can click copy. It will also be a way of bulk opening notes in Dendron. Thoguhts?

![Fullscreen_10_27_20__7_11_AM](https://user-images.githubusercontent.com/409321/97317179-c4d4be80-1827-11eb-9b8a-322406cb923e.jpg)

**Comment by jamesb93** [comment]
I'm a little uncertain on your interface proposition.

My ideal interface would be entirely keyboard navigated and be primarily focused on extracting the note link. To me that looks like you are selecting lines within a document. This is outside the original scope of what I propose but I see how this would be interesting too. At that point though I would probably step into the document to find what I needed and then draw up the right invocation from the command palette. I do like the idea of check boxing and being able to wrangle multiple files together and then hit paste. That makes the action of copying note links from Cmd+L extensible toward a variety of approaches.

**Comment by kevinslin** [comment]
Sorry, missed this reply. I just took a screenshot of another extension I was using - the idea was to highlight the checkboxes. Just launched a version of copy link in 0.15: https://dendron.so/notes/ad270a7d-2aed-4273-8319-eb6536e38b29.html#copywikilink

Let me know what you think :)

**Comment by kevinslin** [comment]
Closing this for now since Dendron now supports copying note links. Feel free to re-open if there was something we missed :)
