### ISSUE TITLE
Would it be possible to create a standalone vscode extension for filename based tree and graph view ?

### ISSUE THREAD

**Issue by akharrou** [dendronhq/dendron#3051]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I love the tree view and graph view that are generated based on the name of files and the hierarchy made out of it. In fact, i love it so much that I would love to be able to use it in other projects outside my dendron workspaces. so my request is:

Would it be possible to create a standalone vscode extension for just that chunk of functionality, decoupled from dendron ?

## Describe alternatives you've considered ##

I have seen graph view extensions, but dendron's graph view does it based on file naming scheme hierarchy which is the more sensical approach to viewing complicated projects imo, instead of just by links.

and i have not seen tree view extensions like dendron's

**Comment by SeriousBug** [comment]
Hi Akharrou! That would be an interesting idea, although I don't think we have any plans to build something like that. The graph view has a lot of Dendron-specific features at the moment.

If someone would like to build something like this, Dendron is open source and available under an AGPL license. It should be possible for someone to isolate the graph code and create a new extension with it. It's not something we're planning to do ourselves.
