### ISSUE TITLE
Migrating from Zim Desktop

### ISSUE THREAD

**Issue by Philippe-Collignon** [dendronhq/dendron#306]
Hello, I'm a Zim user for a while .. (https://zim-wiki.org/)
I'm thinking about moving to dendron but need to migrate my knowledge base.
Zim is "wiki based" and stores text files in folders.  
I could convert wiki to markdown and flatten the folders in x.y.z.md files.
What about dendron header (id, ..) do you have some hints to migrate from other tools ?

**Comment by kevinslin** [comment]
Dendron has a [markdown pod](https://dendron.so/notes/13c4a608-0a32-4c62-9c7e-2b7f9f2d18bf.html) that lets you import markdown notes that are currently stored in folders. Can you see if that helps? Caveat that right now, it doesn't convert folder based wiki-links to dendron based wiki links (that's coming in a week!)

**Comment by phcollignon** [comment]
Thank for the hints.  I have looked a little bit more at dendron.  Congrats .. amazing tool ! As Zim you focus on easy hierarchies ..
Is there any way to include a pdf file of any other document link inside a note (as you can do for images ?)
Just a remark, in Zim the assets are part of the hierarchy, maybe more structured that all flatten in assets folder if you want to search for them aftewards without notes ..
If I migrate to dendron, I will write some code to automate hierarchy and links convertion (and share if it is useful of course)

**Comment by kevinslin** [comment]
Dendron's markdown pod will import everything under the `src` directory that you specify. Any non-md files will be moved under `assets` and a link will be generated to that file inside the dendron note that was generated for the original folder. 

If you have links to a pdf file inside a note, Dendron will leave that alone. We have an action item to convert folder-based-links to dendron-links during import, we should also do the same for any assets that were linked. 

As for assets being part of the hierarchy --> that's intriguing. This was my plan currently for assets. 


dendron has a logical tree view that shows your notes as if they were folders: https://dendron.so/notes/f7ebd4aa-8ba7-4bc5-bd00-a1efc5315f07.html#dendron-tree-view

in the future, it'll be possible to drag and drop files to this tree view. when you drop a file into a note, it will be added as a link inside the note. it will also be visible as a file in the tree view

so this view will show both your dendron notes as well as any external files that you've attached to the notes
this should help with the normal case of "I want to dump a file into a folder"

would this cover your use case or would you also want to lookup assets by their path?

**Comment by phcollignon** [comment]
> Dendron's markdown pod will import everything under the src directory that you specify.
Thanks. I missed that feature. Maybe it should be more documented .. or added in "the trail"

> in the future, it'll be possible to drag and drop files to this tree view. when you drop a file into a note, it will be added as a link inside the note. it will also be visible as a file in the tree view

This is exactly how Zim Desktop works !! .. nothing can be more efficient !

**Comment by phcollignon** [comment]
Zim has a markdown export.
I was able to import the zim export as a markdown pod but before I had to rename the .markdown to .md extensions.

The folder hiearchy of zim is mapped the the hierarchy of dendron !

The last issue is that all the links to markdown and non-markdown files are broken .. 
I could write a small script to update the markdown links but not the non-markdown as they are imported in the assets with an unknown uuid ..

**Comment by kevinslin** [comment]
We just released 0.15 with an update to the markdown import pod. it will also convert wiki-links with imports. you might have already solved this issue at this point but if not, that might help :)

Feel free to re-open this is something else comes up
