### ISSUE TITLE
Descriptions of children of a schema do not get reproduced in the opened note

### ISSUE THREAD

**Issue by HeuFui** [dendronhq/dendron#308]
## Is it a bug? Or a non-yet implemented feature?

From what  I could understand, the description of a schema is passed on to the resulting note obeying to that schema. However, if said schema has children, and children do also have descriptions, children's descriptions are not passed on to their resulting notes. 

### How to to Reproduce
1. Open new note based on schema with children which, in turn, have descriptions.
2. On the resulting note, the description field is empty.

### Expected behavior
The expectation is that the children's description gets passed on to the new note based on said schema.

**Comment by kevinslin** [comment]
Could you paste a sample schema just to help me understand and reproduce?

**Comment by kpathakota** [comment]
@HeuFui - I think we need an example to understand this better, I don't think this is actionable at this time.
