### ISSUE TITLE
Robust exporting to plain markdown directories

### ISSUE THREAD

**Issue by alexkreidler** [dendronhq/dendron#309]
I've been trying Dendron for a day and like it so far. However, the most important feature for me is robust exporting to a plain markdown. In fact, it would be great to convert Dendron dotted file names into the proper directory structure. This would then allow for using Dendron for:
- generating docs sites using Docusaurus or other tools
- using Pandoc and bibtex for outputting articles w/ works cited lists, etc

I very much like this design
```yaml
site:
  siteHierarchies: [home, blog, books]
  siteRootDir: docs
  config:
    books:
      publishByDefault: false
```

But unfortunately, the Markdown Publish pod as it exists now simply exports the current file to the clipboard, and doesn't even translate links properly. [This](https://hastebin.com/rugobofeqo.md) is the output I got running on `dendron.md` (see the links in the same non-standard format as the input: `[[quickstart | dendron.quickstart.md]]`) In fact I can't tell if it transformed the input at all.

However, Foam does the following:
```markdown
- do at least 3 of the comms from yesterday [[2020-09-22]]

[//begin]: # "Autogenerated link references for markdown compatibility"
[2020-09-22]: 2020-09-22 "2020-09-22"
[//end]: # "Autogenerated link references"
```

Best of luck with everything!

**Comment by OlavStornes** [comment]
I assume this could be related (or a detailed subtask) of #210?

**Comment by kevinslin** [comment]
@alexkreidler thanks for the issue. We are planning on building in export functionality via the [markdown pod](https://dendron.so/notes/13c4a608-0a32-4c62-9c7e-2b7f9f2d18bf.html). Exports will create a folder directory structure, convert wiki-links and note-references to the plain markdown equivalent (if you run `Dendron: Publish Pod` with markdown, you will get a sense of what the output will look like)

**Comment by kevinslin** [comment]
@OlavStornes this task is just dealing with exports, #210 is a more comprehensive task to work with folder hierarchies within dendron

**Comment by kpathakota** [comment]
This is the same as #541 where we're collecting more improvements to the Markdown pod export functionality.
