### ISSUE TITLE
`--help` text does not match full list of arguments for CLI commands

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3093]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The `--help` text for some CLI commands doesn't seem to be populated with all flags that are available within the command itself. The main one I've noticed this on is `publish` which seems to have a `--target`,`--yes-`, and `--sitemap` options but these aren't shown within the `--help` output. There may be others in other commands but I noticed these when comparing the existing docs to the new ones I am currently writing (https://github.com/dendronhq/dendron-site/pull/531) to standardise cli docs formats. 

## To Reproduce

`npx dendron publish --help`

https://github.com/dendronhq/dendron/blob/d34bff98a8ec2fb5f249c90a366f6eb5d6b39cb3/packages/dendron-cli/src/commands/publishCLICommand.ts#L81

## Expected behavior

I would think that all flags would be shown in the help output/

## Desktop (please complete the following information)

  - Dendron CLI: 0.97

## Additional context

Once any additional flags are added these will need to be added to the docs as well.

**Comment by Harshita-mindfire** [comment]
This should be fixed after Dendron v.101. Feel free to ping here if that's not the case

**Comment by rlh1994** [comment]
Yep seems to be now!
