### ISSUE TITLE
Allow for note embed end wildcard to take header level requirement

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3095]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I often want to include a whole section of a note between two same level headers, I currently can do this using `![[demo.note#first-2s:#second-h2]]` but I have to manually specify the second header name, and if this is at the end of a note there is no way for me to do this and I just have to include to the end of the note, which is fine but if I add a new h2 level below this my embedded note now has this extra in as well, and there's no real way to check for this except checking every backlink.

## Describe the solution you'd like ##

An extension of the `![[demo.note#first-2s:#*]]` syntax to allow me to specify the level of the next header I want to embed to.

**Comment by jonathanyeung** [comment]
Thanks @rlh1994 - there was a discussion / bug a long while back where we were discussing modifying how a single header reference would work (I can't find the link anymore unfortunately).  

In that proposal, `![[demo.note#first-h2]]` would only show the contents of the first-h2 section, all the up to the subsequent h2 level header, or the end of the note.  For creating a ref from header FOO to the end of the note, we would use some wildcard syntax. I think this proposal better aligns with what user's want to do.  Maybe this is a good time to revisit that discussion.

**Comment by rlh1994** [comment]
@jonathanyeung Yeah that makes sense, I suppose now it's also a balance of how it would change existing notes. Is it worth me starting a new actual `discussion` in the repo (as I can't find it either)?

**Comment by kevinslin** [comment]
this is something that's been on my mind too. i have a partially completed draft rfc for it [here](https://github.com/dendronhq/dendron-docs/blob/main/notes/rfc.47-better-note-references.md#L13:L13)

@rlh1994 if you feel inclined, your welcome to bring the RFC over the finish line (at this point, just filling out goals/context/tradeoffs) and starting a discussion on it.

**Comment by rlh1994** [comment]
@kevinslin Sure I can take a look at getting it finished maybe this weekend.

**Comment by rlh1994** [comment]
https://github.com/dendronhq/dendron/discussions/3136

Discussion for the idea

**Comment by rlh1994** [comment]
@kevinslin I'd say this is pretty much closed now, maybe a way to migrate still but the core of this issue is pretty much available so I'll close this issue

**Comment by kevins8** [comment]
Ack - thanks for cleaning this one!
