### ISSUE TITLE
Allow custom link to be applied to private note links

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3105]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

All links to private notes are currently linked to the dendron explanation of a private note (wiki.dendron.so/notes/hfyvYGJZQiUwQaaxQO27q.html). It would be useful to have a way to configure what this links to.

## Describe the solution you'd like ##

A config option in the publishing section of the yaml to define what private note links link to. 

## Additional context ##

Extension of the request in #3007

**Comment by jlongo** [comment]
To have the possibility of configuring the link it's great too... the original unpublished page (the one on dendron site) can be the default one, but inside of the published result

**Comment by jonathanyeung** [comment]
Thanks @rlh1994 for the suggestion
