### ISSUE TITLE
Show note graph not showing the graph

### ISSUE THREAD

**Issue by thealokkr** [dendronhq/dendron#3112]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## To Reproduce

1. Go to 'command palette'
2. Click on 'show note graph'
3. Message is shown - "still connecting to engine.."

## Expected behavior
Note graph should be shown
## Screenshots
![image](https://user-images.githubusercontent.com/7398429/174485234-a89b5ef0-e2b2-4c4c-920b-8cbe0e329c11.png)

## Desktop (please complete the following information)

- OS: [e.g. iOS] MACOS Monterery
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.99
  - VS Code version: 1.68
  - Dendron CLI:

## Dendron Log file
[dendron.log](https://github.com/dendronhq/dendron/files/8935674/dendron.log)

**Comment by jonathanyeung** [comment]
Hi @thealokkr - can you check if you have the 'Markdown Links' extension also installed, and if so, uninstall it, reload your workspace, and try the graph view again? 

Markdown links is now deprecated and is built-in to Dendron, so it's no longer needed.

**Comment by thealokkr** [comment]
It did the trick. Closing the bug. Thanks and appreciate the help
