### ISSUE TITLE
Notes opened from the dendron tree view are replaced with blank notes

### ISSUE THREAD

**Issue by huwm** [dendronhq/dendron#312]
After upgrading to v0.13.4 of Dendron, notes with capital letters in the filename that are opened in the tree view are deleted and replaced with a new blank note. This does not affect notes with all-lower-case filenames.

**To Reproduce**

1. Open Dendron v0.13.4.
2. Open/Create then open a note with capital letters in the file name ie "000 Index" from the dendron tree view panel.
3. Clicking the note repeatedly will generate a new note each time.

**Expected behavior**
The original note should not be replaced by a blank note and instead just open the original note.

- OS: Mac OS X
- Dendron v0.13.4
- VSCode 1.50.1

**Comment by kevinslin** [comment]
thanks for the issue. this was fixed in 0.13.5!
