### ISSUE TITLE
Error when exporting `dendron.users.issues` config to airtable because of quotes in frontmatter

### ISSUE THREAD

**Issue by bpathakota** [dendronhq/dendron#3131]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [x] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When there are quotes in the frontmatter for fields that I don't fill out (not-required fields), and try to export the user issue to airtable, I get an error. I have to backspace on all the quotes and then export. The default template for issues comes with the quotes.

## To Reproduce

1. Create a note under issue.journal hierarchy
2. Fill out required fields
3. Leave quotes (from template) for other frontmatter fields
4. Run airtable `Export Pod`
5. See error

## Expected behavior

Issue gets exported to airtable without backspacing on quotes in frontmatter

## Screenshots

![issue error message](https://user-images.githubusercontent.com/99723590/175102050-2f34b62b-31fc-4bd7-8de0-b01af907d782.png)
![issue export successful](https://user-images.githubusercontent.com/99723590/175103324-a3ab0054-9bd6-4b2d-b763-9ba6ea94647c.png)

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

{"level":30,"time":1655919921299,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.exportPodv2:run","msg":"pre-execute"}
{"level":30,"time":1655919921301,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.exportPodv2:run","msg":"post-execute"}
{"level":30,"time":1655919921310,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.airtableexport:run","msg":"pre-execute"}
{"level":30,"time":1655919921330,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.airtableexport:run","msg":"post-execute"}
{"level":30,"time":1655919922349,"pid":21632,"hostname":"X1XO-B","name":"dendron","msg":"0 notes updated"}
{"level":50,"time":1655919922350,"pid":21632,"hostname":"X1XO-B","name":"dendron","msg":"Finished Airtable Export. 0 records created; 0 records updated. Error encountered: {\"payload\":[{\"message\":\"Error during Airtable Export. The choice  for field Cause does not exactly match with an existing option. Please check what values are allowed in Airtable\",\"name\":\"DendronError\",\"status\":\"unknown\",\"payload\":\"[{\\\"fields\\\":{\\\"Name\\\":\\\"Howto Add Remote Vault to Different Machine\\\",\\\"DendronId\\\":\\\"ixwhcfobibej1xy5omdgltp\\\",\\\"Resolution\\\":\\\"\\\\n\\\",\\\"Archive\\\":false,\\\"Scope\\\":[\\\"rec4HYy6raEZ6Kzgr\\\"],\\\"Feature\\\":[\\\"recPt3Iz33sZvYlIe\\\"],\\\"Cause\\\":\\\"\\\",\\\"Type\\\":\\\"howto\\\",\\\"Status\\\":\\\"not-started\\\",\\\"PriorityV2\\\":\\\"\\\",\\\"Fname\\\":\\\"issue.journal.2022.06.22.howto-add-remote-vault-to-different-machine\\\",\\\"Issue\\\":\\\"\\\"}}]\",\"innerError\":{\"error\":\"INVALID_MULTIPLE_CHOICE_OPTIONS\",\"message\":\"Insufficient permissions to create new select option \\\"\\\"\\\"\\\"\",\"statusCode\":422}}],\"errors\":[{\"name\":\"DendronError\",\"status\":\"unknown\",\"payload\":\"[{\\\"fields\\\":{\\\"Name\\\":\\\"Howto Add Remote Vault to Different Machine\\\",\\\"DendronId\\\":\\\"ixwhcfobibej1xy5omdgltp\\\",\\\"Resolution\\\":\\\"\\\\n\\\",\\\"Archive\\\":false,\\\"Scope\\\":[\\\"rec4HYy6raEZ6Kzgr\\\"],\\\"Feature\\\":[\\\"recPt3Iz33sZvYlIe\\\"],\\\"Cause\\\":\\\"\\\",\\\"Type\\\":\\\"howto\\\",\\\"Status\\\":\\\"not-started\\\",\\\"PriorityV2\\\":\\\"\\\",\\\"Fname\\\":\\\"issue.journal.2022.06.22.howto-add-remote-vault-to-different-machine\\\",\\\"Issue\\\":\\\"\\\"}}]\",\"innerError\":{\"error\":\"INVALID_MULTIPLE_CHOICE_OPTIONS\",\"message\":\"Insufficient permissions to create new select option \\\"\\\"\\\"\\\"\",\"statusCode\":422}}],\"message\":\"Error during Airtable Export. The choice  for field Cause does not exactly match with an existing option. Please check what values are allowed in Airtable\"}"}
{"level":30,"time":1655919925910,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":{"stack":"YAMLSyntaxError: Missing closing 'quote\n    at Object.t.createError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2376568)\n    at Object.t.transformError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2389737)\n    at t.parse (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2382132)\n    at t.parseFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:215128)\n    at t.decorateFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:342430)\n    at y (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:338507)\n    at c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339407\n    at Function.visitAsync (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:422379)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async t.runAllDecorators (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339343)","message":"Missing closing 'quote","name":"YAMLSyntaxError","source":"id: ixwhcfobibej1xy5omdgltp\ntitle: Howto Add Remote Vault to Different Machine\ndesc: ''\nupdated: 1655919231856\ncreated: 1655918993987\ntags:\n  - scope.common.workspace\n  - feature.vaults\narchive: false\nissueType: howto\ncause: '\ndue: ''\nupstream: ''\nstatus: not-started\nghIssueUrl: ''\npriorityv2: ''","position":{"start":{"offset":225,"line":11,"column":8},"end":{"offset":297,"line":16,"column":15}}}}}
{"level":30,"time":1655919926118,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":4,"diagnosticsLength":0}}
{"level":30,"time":1655919926537,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":{"stack":"YAMLSyntaxError: Missing closing 'quote\n    at Object.t.createError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2376568)\n    at Object.t.transformError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2389737)\n    at t.parse (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2382132)\n    at t.parseFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:215128)\n    at t.decorateFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:342430)\n    at y (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:338507)\n    at c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339407\n    at Function.visitAsync (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:422379)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async t.runAllDecorators (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339343)","message":"Missing closing 'quote","name":"YAMLSyntaxError","source":"id: ixwhcfobibej1xy5omdgltp\ntitle: Howto Add Remote Vault to Different Machine\ndesc: ''\nupdated: 1655919231856\ncreated: 1655918993987\ntags:\n  - scope.common.workspace\n  - feature.vaults\narchive: false\nissueType: howto\ncause: \ndue: '\nupstream: ''\nstatus: not-started\nghIssueUrl: ''\npriorityv2: ''","position":{"start":{"offset":231,"line":12,"column":6},"end":{"offset":295,"line":16,"column":15}}}}}
{"level":30,"time":1655919926719,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":4,"diagnosticsLength":0}}
{"level":30,"time":1655919927192,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":{"stack":"YAMLSyntaxError: Missing closing 'quote\n    at Object.t.createError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2376568)\n    at Object.t.transformError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2389737)\n    at t.parse (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2382132)\n    at t.parseFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:215128)\n    at t.decorateFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:342430)\n    at y (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:338507)\n    at c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339407\n    at Function.visitAsync (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:422379)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async t.runAllDecorators (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339343)","message":"Missing closing 'quote","name":"YAMLSyntaxError","source":"id: ixwhcfobibej1xy5omdgltp\ntitle: Howto Add Remote Vault to Different Machine\ndesc: ''\nupdated: 1655919231856\ncreated: 1655918993987\ntags:\n  - scope.common.workspace\n  - feature.vaults\narchive: false\nissueType: howto\ncause: \ndue: \nupstream: '\nstatus: not-started\nghIssueUrl: ''\npriorityv2: ''","position":{"start":{"offset":242,"line":13,"column":11},"end":{"offset":293,"line":16,"column":15}}}}}
{"level":30,"time":1655919927335,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":4,"diagnosticsLength":0}}
{"level":30,"time":1655919927788,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":4,"diagnosticsLength":0}}
{"level":30,"time":1655919927914,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":4,"diagnosticsLength":0}}
{"level":30,"time":1655919928251,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":{"stack":"YAMLSyntaxError: Missing closing 'quote\n    at Object.t.createError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2376568)\n    at Object.t.transformError (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2389737)\n    at t.parse (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:8:2382132)\n    at t.parseFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:215128)\n    at t.decorateFrontmatter (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:342430)\n    at y (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:338507)\n    at c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339407\n    at Function.visitAsync (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:422379)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async t.runAllDecorators (c:\\Users\\bpath\\.vscode\\extensions\\dendron.nightly-0.99.5\\dist\\server.js:2:339343)","message":"Missing closing 'quote","name":"YAMLSyntaxError","source":"id: ixwhcfobibej1xy5omdgltp\ntitle: Howto Add Remote Vault to Different Machine\ndesc: ''\nupdated: 1655919231856\ncreated: 1655918993987\ntags:\n  - scope.common.workspace\n  - feature.vaults\narchive: false\nissueType: howto\ncause: \ndue: \nupstream: \nstatus: not-started\nghIssueUrl: \npriorityv2: '","position":{"start":{"offset":288,"line":16,"column":13},"end":{"offset":289,"line":16,"column":14}}}}}
{"level":30,"time":1655919928462,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":4,"diagnosticsLength":0}}
{"level":30,"time":1655919929626,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"c:\\Repos\\org-work\\org-workspace\\dendron-users\\notes\\issue.journal.2022.06.22.howto-add-remote-vault-to-different-machine.md","reason":"Manual","msg":"enter"}
{"level":30,"time":1655919929631,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveNote","match":["updated: 1655919231856","1655919231856"],"msg":"update activeText editor"}
{"level":30,"time":1655919929642,"pid":19768,"hostname":"X1XO-B","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":2,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1655919929976,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1655919930078,"pid":19768,"hostname":"X1XO-B","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":2,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1655919930091,"pid":19768,"hostname":"X1XO-B","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":2,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1655919930208,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1655919930605,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1655919931849,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1655919942302,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.exportPodv2:run","msg":"pre-execute"}
{"level":30,"time":1655919942303,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.exportPodv2:run","msg":"post-execute"}
{"level":30,"time":1655919942309,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.airtableexport:run","msg":"pre-execute"}
{"level":30,"time":1655919942320,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.airtableexport:run","msg":"post-execute"}
{"level":30,"time":1655919943309,"pid":19768,"hostname":"X1XO-B","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":2,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1655919943505,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1655919943506,"pid":21632,"hostname":"X1XO-B","name":"dendron","msg":"1 notes updated"}
{"level":30,"time":1655919943589,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":4,"diagnosticsLength":0}}
{"level":30,"time":1655919943780,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1655919944473,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1655919948146,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1655919948147,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1655919948267,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1655919948604,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Repos\\org-work\\org-workspace\\seeds\\dendron.dendron-site\\vault\\tags.scope.internal.md","c:\\Repos\\org-work\\org-workspace\\org-private\\notes\\s.airtable.sop.connect-to-airtable.md"]}
{"level":30,"time":1655919948604,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1655919948605,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Repos\\org-work\\org-workspace\\seeds\\dendron.dendron-site\\vault\\tags.scope.internal.md","c:\\Repos\\org-work\\org-workspace\\org-private\\notes\\s.airtable.sop.connect-to-airtable.md","c:\\Users\\bpath\\AppData\\Roaming\\Code\\logs\\20220620T101722\\exthost2\\dendron.nightly\\dendron.log"]}
{"level":30,"time":1655919948608,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1655919948611,"pid":21632,"hostname":"X1XO-B","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"dendron.log"}

**Comment by Harshita-mindfire** [comment]
This should be fixed with the recent update to Airtable. Feel free to message here if that is not the case.
