### ISSUE TITLE
Nested unordered bullets aren't rendering properly in preview

### ISSUE THREAD

**Issue by cquick01** [dendronhq/dendron#3139]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Notes with nested unordered bullets don't render properly.

## To Reproduce

Markdown code to reproduce behavior

```markdown
1. Test number 1
2. Test number 2
    - Test sub-bullet 1
        - Test sub-sub-bullet 1
    - Test sub-bullet 2
    - Test sub-bullet 3
3. Test number 3
```

## Expected behavior

Expected to render with nested bullets.

Dillinger
![image](https://user-images.githubusercontent.com/72400253/175325732-58c1ace2-fc84-4c81-9749-4065909003f2.png)

## Screenshots

VSCode Dendron Preview (dark theme)
![image](https://user-images.githubusercontent.com/72400253/175325543-b32f8682-2617-4817-a500-a25c7cdf7591.png)

VSCode Dendron Preview (light theme)
![image](https://user-images.githubusercontent.com/72400253/175325908-76e82a0e-eabd-4bae-a860-80faf98e7e64.png)

## Desktop (please complete the following information)

- OS: Windows 10, but it's connecting to Ubuntu 22.04 running on WSL2 as a remote.
- Browser (if with published websites; include version): N/A
- Versions (all that apply to bug):
  - Dendron Extension: v0.100.1
  - VS Code version:
    - Version: 1.68.1 (user setup)
    - Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
    - Date: 2022-06-14T12:48:58.283Z
    - Electron: 17.4.7
    - Chromium: 98.0.4758.141
    - Node.js: 16.13.0
    - V8: 9.8.177.13-electron.0
    - OS: Windows_NT x64 10.0.19044
  - Dendron CLI: I think N/A?

## Dendron Log file

[dendronlog.txt](https://github.com/dendronhq/dendron/files/8968362/dendronlog.txt)

**Comment by Harshita-mindfire** [comment]
Thanks @cquick01 for reporting the issue. I can repro it. We will let you know once this gets fixed 🙏

**Comment by cquick01** [comment]
@Harshita-mindfire, thanks for looking into it!

If it helps, I did notice that the separate [Dendron Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=dendron.dendron-markdown-preview-enhanced) extension does work as expected.

![image](https://user-images.githubusercontent.com/72400253/175552856-9f0527df-75dd-4791-a25f-055f0ad244dd.png)

I'm unsure if there are any features that won't work as it was last updated almost a year ago, but for now it seems to get the job done. Hopefully the default previewer in Dendron can still get fixed so it works out of the box.

**Comment by Harshita-mindfire** [comment]
Dendron Markdown Preview Enhanced is deprecated and no longer supported though, keep that in mind in case you hit any issues.
