### ISSUE TITLE
Need to reload VScode to have new backlinks show in preview

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3143]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When you add a link to a note, the note that is referenced when previewed does not show the new backlink in the `backlinks` section of the preview (but does correctly show it in the dendron sidebar). Reloading the index does not work, only a reload of the VSCode window (either developer: reload window or a close and open)

## To Reproduce

1. Create a new note, fill it with some links to other new notes
2. Create the new notes from here and open the preview of them 
3. See there is no backlinks in the preview
4. Reload VScode
5. Preview the new notes, a backlink is now listed.

## Expected behavior

Preview will display correct backlinks without needing to reload vscode

## Desktop (please complete the following information)

- OS: Tested on windows and linux
- Versions (all that apply to bug):
  - Dendron Extension: 0.100
  - VS Code version: 1.68.1
  - Dendron CLI: N/A

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Thanks @rlh1994 for reporting the issue. I can repro it. We will let you know once this gets fixed 🙏
