### ISSUE TITLE
Font in Graph view

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dendronhq/dendron#3148]
## Please select if your request is either something new or an enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [X] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Please, for the love of God, no comic sans

**Comment by Harshita-mindfire** [comment]
Hey @sschneider-ihre-pvs, Thanks for the feedback 🙏.
We have three themes for graph view which can be toggled using the [graph theme filter](https://www.loom.com/share/f2c53d2a5aeb48209b5587a3dfbb1015). You can also use custom styles for graphs, Click [here](https://wiki.dendron.so/notes/587e6d62-3c5b-49b0-aedc-02f62f0448e6/#custom-styling) to read more about this.

**Comment by sschneider-ihre-pvs** [comment]
doesn't seem to work
![image](https://user-images.githubusercontent.com/86342787/175525118-01c07137-bb25-4ccb-8105-ba83dab4fb19.png)

**Comment by sschneider-ihre-pvs** [comment]
in the panel view not even the color is correct
![image](https://user-images.githubusercontent.com/86342787/175525378-0e57bf11-586e-4489-a725-96500cc9e920.png)

**Comment by Harshita-mindfire** [comment]
For custom css to apply, you would want to close and reopen the view/panel.
Looks like the font-family is still cursive, can you change that to `font-family: Sans-serif;` and see if that meets your requirements?

**Comment by sschneider-ihre-pvs** [comment]
Does not change anything

**Comment by Harshita-mindfire** [comment]
Hey @sschneider-ihre-pvs , can you share the steps you are performing. The custom CSS does apply for me. : https://www.loom.com/share/b2965227ff994265a5fd7866cbc7cb10

**Comment by sschneider-ihre-pvs** [comment]
but
