### ISSUE TITLE
Create an H1 title that is the same as the note title when creating a new note

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#315]
## Context

Currently when creating a new note via lookup, Dendron will generate frontmatter but no additional content inside the note.

For many people, its useful to create a h1 header with the same convention as the note title

## Proposal

Add an option to create an h1 title that is the same as the note frontmatter title. This should be turned on by default with an option of disabling this behavior.

## Details

- add new config to `plugin-core/src/constants.ts`
- use `> Run Task: gen:config` to update `package.json` with new configuration
- new note creation behavior is defined [here](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/components/lookup/LookupControllerV2.ts#L241:L241)
    - you'll want to update `note.body` so that it has a `# {note.title}` if `dendron.newNoteTitle` is set to `fmTitle`
- New Configuration:
    - key: `dendron.newNoteTitle`
    - type: enum
    - options: 
        - off
        - fmTitle: same as frontmatter title

**Comment by seedublancaster** [comment]
Started hacking away at this.  I am sure we can discuss real-time later on via zoom.  I do have some further questions.

**Comment by mgielda** [comment]
Question - wouldn't it be nicer if you were able  be able to refer to the note's title in the metadata via some macro? I am so tempted to just put

# {note.title} in the markdown. (instead of putting the current name and then having to maintain it when the name changes...)

**Comment by kevinslin** [comment]
Yep, that would be nicer. It would be a more involved change since it involves changing the preview extension. That will be a good next task following this one

**Comment by kevinslin** [comment]
@mgielda we ended up going the metadata route. its now possible and will be enabled by default in 0.25 to use the frontmatter title as the h1 title. see docs [here](https://dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f48.html#usefmtitle)
