### ISSUE TITLE
Root backlink not working

### ISSUE THREAD

**Issue by aglucky** [dendronhq/dendron#3156]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Backlinks from the root page do not properly link back to the root.

## To Reproduce

Add a link to a note on the root page. Click on the backlink on the page link is to.

## Expected behavior

Backlink should link to the root instead of not found page.

## Screenshots

[Example](https://glucknotes.com/notes/ipjj98ie54pho326xznoosj/)

## Desktop (please complete the following information)

- OS: IOS
- Browser (if with published websites; include version): safari
- Versions (all that apply to bug):
  - Dendron Extension: latest
  - VS Code version: latest
  - Dendron CLI: latest 

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Hey @aglucky , Is this still an issue? Can't repro in the example link provided now.
