### ISSUE TITLE
Show Notes Graph is not opening the graph view

### ISSUE THREAD

**Issue by shivayan-bora** [dendronhq/dendron#3160]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I have version v0.100.1 installed for Dendron and v0.6.20 of Dendron Markdown Links. I am not able to open the Graph view and it consistently shows the message:

still connecting to engine. please try again in a few moments...

## To Reproduce

1. Install the above mentioned versions of Dendron and Dendron Markdown Links.
2. Go to the Command Palette and Search for Show Note Graph and select it.
3. You will consistently find the error: `still connecting to engine. please try again in a few moments...`

## Expected behavior

The graph view should open up.

## Screenshots

![image](https://user-images.githubusercontent.com/23340497/176131894-f7c112fe-f734-486b-9712-1105d0f84b86.png)

## Desktop (please complete the following information)

- OS: Windows 10 Enterprise
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: v0.100.1
  - VS Code version: 1.68.1
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here
[DendronLogs.log](https://github.com/dendronhq/dendron/files/8999131/DendronLogs.log)

**Comment by Harshita-mindfire** [comment]
Hi @shivayan-bora, can you check if you have the 'Markdown Links' extension also installed, and if so, uninstall it, reload your workspace, and try the graph view again?

Markdown links is now deprecated and is built-in to Dendron, so it's no longer needed.

**Comment by shivayan-bora** [comment]
Ok it works. My bad I thought the Markdown Links provided separate functionality.
