### ISSUE TITLE
Allow using regex captured groups in hierarchy refactoring

### ISSUE THREAD

**Issue by rasmuse** [dendronhq/dendron#317]
**Is your feature request related to a problem? Please describe.**

When refactoring the hierarchy, I would like to be able to use regex groups in the replacement string.

My use case for today was to rename existing journal and scratch notes, where starting with v0.13.5 dates are formatted with periods yyyy.mm.dd instead of dashes yyyy-mm-dd. Renaming all the existing scratch and journal entries would be a breeze if I could replace `daily\.journal\.(\d{4})-(\d{2})-(\d{2})` by `daily.journal.$1.$2.$3`.

(Of course, using named groups could be useful, too. That would probably come for free when implementing numbered groups.)

**Describe the solution you'd like**

Refactor hierarchy
Match pattern: `daily\.journal\.(\d{4})-(\d{2})-(\d{2})`
Replace pattern: `daily.journal.$1.$2.$3`

**Describe alternatives you've considered**

The present problem can be easily solved using e.g. `rename` and `sed` or whatever, since the pattern `daily.journal.[bla bla]` cannot be confused with anything else in my case. But in more general cases this path would be dangerous or difficult.

**Comment by kevinslin** [comment]
Thanks for the issue request. Will get this on the november milestone items

**Comment by rasmuse** [comment]
Quick update. Looking through the issues on this tracker I stumbled across #116 which looks like @kevinslin had the same idea already a few months ago. If the two issues are duplicates one could be closed, and voila, you have one issue less to worry about :)

**Comment by kevinslin** [comment]
You are right :)

I'm spending some time doing issue grooming this week. This takes one thing off our plate!
