### ISSUE TITLE
Question: How to disable analytics & telemetry

### ISSUE THREAD

**Issue by xiaolangkong** [dendronhq/dendron#3170]
Hi there, I am very eager to use Dendron, but I was looking through the code and saw analytics, like from Google and AWS.  Is there a way to disable all analytics, telemetry, reporting, tracking, sentry, etc.?

Thanks in advance!

**Comment by kevinslin** [comment]
Yep. See https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c#how-to-opt-out-of-data-collection
