### ISSUE TITLE
Template variables are not being replaced during schema match

### ISSUE THREAD

**Issue by HopperTech** [dendronhq/dendron#3171]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The template variable replacements have recently stopped working. (i.e. <%= CURRENT_YEAR %>
But when I change to the Handlebar template the replacements work again.

The problem is that this abruptly stopped working and I had to break flow to troubleshoot. In researching I discovered the handlebar template option, but the enableHandlebarTemplates is not set to true in the configuration. 

## To Reproduce

Try using the older Schema variables. 

## Expected behavior

For a feature that is still in the documentation to not abruptly change. I can see the benefit of using the Handlebar templating, but the sudden break of a feature was disruptive to normal usage of Dendron. 

## Desktop (please complete the following information)

- OS: Windows
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: v0.101.0
  - VS Code version: 1.69.0-insider
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by HopperTech** [comment]
I did just discover in my work workspace that the yaml upgrade did add the enableHandlebarTemplates: false. 

not sure why my personal workspace did not upgrade correctly. In the future I would suggest using an opt-in approach for new features instead of opt-out.  

Appreciate your consideration.

**Comment by kevinslin** [comment]
Hey, we had a deprecation notice for this a few weeks ago > https://wiki.dendron.so/notes/14h6ul847l9o4ve0rlfshcs#deprecated

apologies if this caused confusion, we have a manual migration guide [here](https://wiki.dendron.so/notes/rwr5bosqp16r3mv5sgnlvl4)

**Comment by HopperTech** [comment]
Thanks Kevin, missed that update
