### ISSUE TITLE
Ability to remove excess assets

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3172]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I may often insert images into notes that I later either replace or delete the note entirely, but I don't often at the time want to go through the note to find which (if any) assets were in it and delete those as well.

## Describe the solution you'd like ##

Some kind of doctor command that would review the files in the asset folder and identify any that aren't used within any notes, then the option to remove or keep these (individually). 

## Describe alternatives you've considered ##

Delete assets and hope nothing breaks.

**Comment by aleksey-rowan** [comment]
Hi, @rlh1994, thank you for the request. This has already been submitted previously, so I'll close this one as a duplicate:

- https://github.com/dendronhq/dendron/issues/650

Please upvote or comment on the linked issue.
