### ISSUE TITLE
Receiving "engine not set" when attempting to Lookup notes

### ISSUE THREAD

**Issue by jtich** [dendronhq/dendron#318]
**Describe the bug**
I'm receiving "engine not set" when attempting to Lookup notes. It seems the engine is undefined.

**To Reproduce**
1. Open VSCode
2. cmd+L
3. Get "engine not set" prompt in bottom right corner.

**Desktop (please complete the following information):**
 - OS: macOS v10.15.5
 - Version: 1.50.1
 - Electron: 9.2.1
 - Node.js: 12.14.1

**Comment by kevinslin** [comment]
Can you run `> Dendron: Open Logs` and send me the output? (note: write now the logs are a little verbose and might contain the note contents. if you have sensitive notes, I suggest you strip that out before hand).

**Comment by jtich** [comment]
All good -- I missed the "Open Workspace" prompt for `dendron.code-workspace` in the bottom-right and mistakenly assumed VS Code would auto-open the workspace file.
