### ISSUE TITLE
Templates get reapplied if previous application is immediately undone

### ISSUE THREAD

**Issue by hateyouinfinity** [dendronhq/dendron#3185]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Templates whose application is immediately undone get erroneously applied the next time "Dendron: Apply Template" is used.

## To Reproduce

1. Use "Dendron: Apply Template" command
2. Undo and save (ctrl-z ctrl-s)
3. Use "Dendron: Apply Template" command
4. Template applied in step 1 is applied alongside template from step 3

Seems to only happen if nothing is typed between steps.
## Expected behavior

Step 4 in [To Reproduce](#to-reproduce) should not re-apply template from step 1.

## Screenshots

[Reproduction GIF](https://i.imgur.com/x4PFVfn.gif)

## Desktop (please complete the following information)

- OS: Windows
- Browser (if with published websites; include version): N/A
- Versions (all that apply to bug):
  - Dendron Extension: v0.101.0
  - VS Code version: 1.68.1
  - Dendron CLI: N/A

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by kevinslin** [comment]
thanks for the issue, can reproduce. will take a look
