### ISSUE TITLE
If workspace.enableUserTags is false, Dendron Doctor still flags @usertags with findBrokenLinks when user notes don't exist

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#3202]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When setting `workspace.enableUserTags` to `false` in `dendron.yml`, it works as expected in the workspace UI. Though, if I run Dendron Doctor's `findBrokenLinks` command, it still gets flagged as an expected enabled user tag.

## To Reproduce

1. Create a workspace
2. Set `workspace.enableUserTags` to `false`
3. Reload window
4. Create a note that contains `@test` within it
5. Run `Dendron: Doctor` -> `findBrokenLinks`

## Expected behavior

If `workspace.enableUserTags` to `false` in `dendron.yml`, that Dendron Doctor ignores it when finding broken links. This may also impact hashtag functionality if `workspace.enableHashTags` is set to `false` too (I haven't tested this).

## Desktop (please complete the following information)

- OS: Pop!_OS 22.04
- Versions (all that apply to bug):
  - Dendron Extension: `v0.102.0`
  - VS Code version: `1.68.1`
  - Dendron CLI: Untested with CLI

**Comment by kevinslin** [comment]
hmm, does this repro reliably? for some reason unable to get this to repro, see https://www.loom.com/share/8ad0ae01c991428fbc4056dfb03fafc6
