### ISSUE TITLE
Dendron cannot load at startup

### ISSUE THREAD

**Issue by rmporsch** [dendronhq/dendron#3203]
Issue Type: <b>Bug</b>

I experience a time out

```
2022-07-07 17:26:07.133] [exthost] [info] ExtensionService#_doActivateExtension dendron.dendron, startup: false, activationEvent: '*'
[2022-07-07 17:26:44.273] [exthost] [info] Extension host terminating: renderer closed the socket
[2022-07-07 17:26:44.278] [exthost] [error] An error occurred when deactivating the extension 'dendron.dendron':
[2022-07-07 17:26:44.278] [exthost] [error] DendronError: no native workspace
```

Extension version: 0.102.0
VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|64.00GB (0.95GB free)|
|Process Argv|--crash-reporter-id 4e24138d-363a-40c2-81ff-c172361bbbb5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdc:30486549

```

</details>

**Comment by kevinslin** [comment]
hmm, do you have something that blocks localhost? that's usually the cause of this, see https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe#dendron-is-stuck-on-loading

**Comment by rmporsch** [comment]
Can confirm it was related to my VPN. Thanks a lot for the suggestion.
