### ISSUE TITLE
Enable use of schema+template in doctor and site generation

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3206]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When notes are generated using the Doctor createMissingLinkedNotes (either cli or command palette), or as stub notes within a published site, these notes are always generated as empty - even those covered by a schema+template. If you create one of these notes via Note Lookup the template is applied.

_I haven't tried creating the note via the cli individually to see if that generates the note with the template_

## Describe the solution you'd like ##

Note generation, both via doctor commands and as required for publishing, follow templates that are provided within the schema of that note. Potentially a flag/option to enable this.

## Describe alternatives you've considered ##

Creating all notes manually via Note Lookup, or possible looping over CLI calls if that would work.

## Additional context ##

I understand templates are often used to then add more information to, but given the growing features of templates e.g. handlebars, this feels like something it would be powerful to add.

I think this also becomes something that's required to really support #2454

**Comment by kevinslin** [comment]
thanks for the issue. we don't currently support this but makes sense as a feature request. will add it as a crop candidate
