### ISSUE TITLE
Using Doctor createMissingLinkedNotes or findBrokenLinks on tags

### ISSUE THREAD

**Issue by Mjvolk3** [dendronhq/dendron#3213]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I always write tags when I am taking notes, but there is no note created. This prevents the tags from being found in either autocomplete or lookup.

## Describe the solution you'd like ##

Use Doctor to generate tags notes with using either createMissingLinkedNotes or findBrokenLinks command.

## Describe alternatives you've considered ##

I haven't considered any alternative.

## Additional context ##

None.

**Comment by kevinslin** [comment]
adding this as a crop candidate. thanks for the submission!

**Comment by aleksey-rowan** [comment]
Hey, @Mjvolk3, there is already an open issue addressing the creation of tag pages: 

- https://github.com/dendronhq/dendron/issues/580

It's not an exact duplicate, but if you think it's close enough, would you consider closing this one and upvoting/commenting on the linked issue to make for a cleaner backlog?

**Comment by Mjvolk3** [comment]
I think #580 and #1391 pretty much cover it so I will close and 👍 the others
