### ISSUE TITLE
Extend enableNoteTitleForLink for children/backlinks 

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3214]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Currently [enableNoteTitleForLink](https://wiki.dendron.so/notes/nISb8ctZKwMj7ya4U2GxW/) set to `false` works for links within the body of the note, but for backlinks and children presented at the bottom of a published page these just have the titles (or at least the final chunk of the note name).

## Describe the solution you'd like ##

The flag to either make the same change to backlinks and/or children in the footer, or another flag to do the same for these, when this is set to false.

**Comment by kevinslin** [comment]
makes sense. adding this to our backlog
