### ISSUE TITLE
Extensions fail to spawn subprocess

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#3227]
Type: <b>Bug</b>

## Repro
1. install [dendron](https://marketplace.visualstudio.com/items?itemName=dendron.dendron) using latest insider build
1. get error on startup

## Details
It looks there's been a regression when spawning a new shell in the latest insiders build.
Dendron (our vscode plugin), spawns a separate process to help index files. This is now failing with the following trace
```js
'DendronError: disconnect
	at ChildProcess.<anonymous> (/Users/kevinlin/code/dendron/packages/api-server/lib/utils.js:172:24)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at finish (node:internal/child_process:902:14)
	at processTicksAndRejections (node:internal/process/task_queues:78:11)'
```

Error is being thrown [here](https://github.com/dendronhq/dendron/blob/release/0.103.0/packages/api-server/src/utils.ts#L191).
Tried switching to `child_process.spwan` which results in the same issue.

Our users are seeing the same issue in the latest insider, see [Receiving "disconnect" message  · Issue #3212 · dendronhq/dendron](https://github.com/dendronhq/dendron/issues/3212).
I can confirm that launching dendron without spawning a separate process works as expected.

I also tried setting `ELECTRON_RUN_AS_NODE` prop as mentioned in https://github.com/microsoft/vscode/issues/151012 but looks like this is a different issue(?)

Extension version: 0.102.1
VS Code version: Code - Insiders 1.70.0-insider (Universal) (3104db414c8fedcf6e4493f14da7df0b7413853a, 2022-07-08T05:16:29.757Z)
OS version: Darwin arm64 20.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 8|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 7166093e-0237-4db6-8bce-100c1927035d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506

```

</details>

**Comment by newbieof410** [comment]
I run into the same issue. The dendron extensions can not start up and log says "failed to spawn a subshell". But it was working fine last week.

What I have tried but not work:
- installing earlier versions of vscode and dendron
- starting a new workspace
- restarting computer

What else might be the problem?

Extension version: v0.114.0
VSCode version: 1.72.0
OS: Darwin arm64 21.6.0

logs: [dendron.log](https://github.com/dendronhq/dendron/files/9734953/dendron.log)

**Comment by newbieof410** [comment]
I don't know why but this is working now. Thanks anyway
