### ISSUE TITLE
As a user, I'd like to visit a dendron link, and have the note highlighted in the expanded sidebar view

### ISSUE THREAD

**Issue by dweisiger** [dendronhq/dendron#3240]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## To Reproduce

1. Go to a dendron published site
2. Navigate to some note
3. Copy the link to that note to a new tab
4. Notice that the sidebar is not expanded 

## Expected behavior

When I visit a link to a dendron published site, the note should be highlighted in the left sidebar, with the sidebar expanded out.

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by dweisiger** [comment]
@Harshita-mindfire did you fix this? i am not seeing the error anymore. by the way if you did, thank you SO much, this makes our experience a lot better.

**Comment by Harshita-mindfire** [comment]
Hey @dweisiger, yeah. This is fixed with Dendron  v0.105.
