### ISSUE TITLE
Headered note refs do not work for headers with comments

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3242]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When using a noteref such as ![[a.note.here#introduction]] this does not work when the header within the `a.note.here` note has comments after it (see below).

## To Reproduce

1. create a note `demo.note-with-header`
2. Populate `demo.note-with-header` with the following
    ```markdown
    blah
    ## intro <!-- Mandatory -->
    more text
    ```
4. new note, `demo.note-with-ref`
5. Populate `note-with-ref` with `![[demo.note-with-header#intro]]` (or copy header ref from the note)
6. See anchor not found error in preview
7. Delete mandatory comment from `demo.note-with-header`
8. See note ref now works

## Expected behavior

Note ref would either work with the comment, or require the comment as part of the ref, currently neither work.

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.103
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by hikchoi** [comment]
Thank you for the report. I can reproduce this. We'll let you know once this gets resolved!
