### ISSUE TITLE
Graph neighbour depth buttons do not work

### ISSUE THREAD

**Issue by patchworquill** [dendronhq/dendron#3246]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Graph panel neighbour depth buttons (up and down arrow) do not work.

## To Reproduce

1. Go to 'Graph Panel'
2. Click on 'Up Arrow' or 'Down Arrow'
3. Nothing Happens

## Expected behavior

Expected behaviour is the graph increases or decreases neighbor degree. Standard graph has 1 degree -- direct connections only -- showing. I would expect the graph to show 

## Desktop (please complete the following information)

- OS: Windows Edition	
      Windows 10 Pro
      Version	21H2
      Installed on	‎3/‎30/‎2021
      OS build	19044.1766
      Experience	Windows Feature Experience Pack 120.2212.4180.0
- Versions (all that apply to bug):
  - Dendron Extension: v0.103.0
  - VS Code version: 1.68.1
    - Version: 1.68.1 (user setup)
    - Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
    - Date: 2022-06-14T12:48:58.283Z
    - Electron: 17.4.7
    - Chromium: 98.0.4758.141
    - Node.js: 16.13.0
    - V8: 9.8.177.13-electron.0
    - OS: Windows_NT x64 10.0.19044

  - Dendron CLI: N/A

## Additional context

This bug also occurred on my Macbook running macOS, but I haven't recorded the build and version details. 

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here
{"level":30,"time":1657814650460,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657814650460,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657814650460,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["c:\\Users\\kadte\\AppData\\Roaming\\Code\\logs\\20220714T085924\\exthost3\\dendron.dendron\\dendron.log"]}
{"level":30,"time":1657814650496,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"CalendarView:openTextDocument","uri":"c:\\Users\\kadte\\AppData\\Roaming\\Code\\logs\\20220714T085924\\exthost3\\dendron.dendron\\dendron.log","msg":"not in workspace"}
{"level":30,"time":1657814650496,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657814650501,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"GraphPanel(side):openTextDocument","uri":"c:\\Users\\kadte\\AppData\\Roaming\\Code\\logs\\20220714T085924\\exthost3\\dendron.dendron\\dendron.log","msg":"not in workspace"}
{"level":30,"time":1657814658265,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1657814658265,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657814658277,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["k:\\Personal Files\\Patrick Wilkie\\Logs\\vault\\daily.journal.2022.07.14.md"]}
{"level":30,"time":1657814658312,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"CalendarView:openTextDocument","msg":"refresh note","note":{"fname":"daily.journal.2022.07.14","id":"ojm1lr1irkvuaur926xb8hd","children":[],"vault":{"fsPath":"vault"},"parent":"jkkwlff2tlqifiew9kpd4fd"}}
{"level":30,"time":1657814658313,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1657814658315,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"GraphPanel(side):openTextDocument","msg":"refresh note","note":{"fname":"daily.journal.2022.07.14","id":"ojm1lr1irkvuaur926xb8hd","children":[],"vault":{"fsPath":"vault"},"parent":"jkkwlff2tlqifiew9kpd4fd"}}
{"level":30,"time":1657814658318,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"k:\\Personal Files\\Patrick Wilkie\\Logs\\vault\\daily.journal.2022.07.14.md"}
{"level":30,"time":1657814658391,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1657814664801,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1657814664801,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1657814664801,"pid":40904,"hostname":"Kadtec-13","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}

**Comment by hikchoi** [comment]
Thank you for the report! I can reproduce this.

We'll let you know when this gets fixed 🙏🏼

**Comment by Harshita-mindfire** [comment]
This should be fixed after Dendron v0.104. Feel free to ping here if that is not the case.
