### ISSUE TITLE
Spaces seem to be ignored when using inline code in headings

### ISSUE THREAD

**Issue by taranlu-houzz** [dendronhq/dendron#3247]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The rendering for inline code in headings seems to ignore whitespace before and after the code snippet when rendering the markdown.

## To Reproduce

Make a new note with content like this:

```markdown
---
id: d2tvmc9d759dc7e0xirxmwg
title: Setup Artist Workstation
desc: "Notes on setting up Windows workstation for artists."
updated: 1657835032368
created: 1657834623330
---

## Install `node.js`

## Install `node.js`

- Install node.js
- Install `node.js`

## Install `node.js` or maybe `something else` doop
```

Both the preview in VSCode and the published site seem to exhibit the same issue.

## Expected behavior

The whitespace should be preserved.

## Screenshots

![image](https://user-images.githubusercontent.com/52425255/179091387-25786cda-a0fb-4c00-9e83-486bd4006a16.png)

## Desktop (please complete the following information)

- OS: macOS
- Browser (if with published websites; include version): Chrome
- Versions (all that apply to bug):
  - Dendron Extension: v0.103.0
  - VS Code version: 1.69.1
  - Dendron CLI: 0.102.1

## Additional context

Pretty sure this was working before some of the most recent updates (maybe about a month ago?).

**Comment by hikchoi** [comment]
Thank you for the issue. I can reproduce this. We'll notify you here when it gets resolve.

**Comment by namjul** [comment]
This has been fix with https://github.com/dendronhq/dendron/pull/3525 and release here https://wiki.dendron.so/notes/9qwkfmnftzlj6f0oqi2wj35/
