### ISSUE TITLE
Outline panel lists the headings in alphabetical order rather than the actual order of occurrence in the note.

### ISSUE THREAD

**Issue by rishabhsagar** [dendronhq/dendron#325]
**Describe the bug**
Outline panel lists the headings in alphabetical order rather than the actual order of occurrence in the note.

**To Reproduce**
1. Create a new note
2. Create a H1 level title called Test Title
3. Create a H2 level title called Zulu Title nested under Test Title
4. Create a H2 level title called Beta Title nested under Test Title
5. Create a H2 level title called Alpha Title nested under Test Title

In the Outline Panel, notice that the L2 titles are listed in alphabetical order (Alpha, Beta and Zulu); instead of Zulu and Beta and Alpha (the order in which titles actually appear in the note).

**Expected behavior**
In the outline panel, the order of titles should be
Test Title
    Zulu Title
    Beta Title
    Alpha Title

**Screenshots**
![Document_Screenshot](https://user-images.githubusercontent.com/1045092/97968488-9b330e80-1db6-11eb-887e-f098feae4438.png)
![Outline_Screenshot](https://user-images.githubusercontent.com/1045092/97968491-9c643b80-1db6-11eb-9e0a-92a4fd3b3e02.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - IDE [VSCode version September 2020 (version 1.50)]
 - Dendron Extension [v0.14.0]

**Comment by kevinslin** [comment]
You can change that via the three little dots next to outline. See instructions [here](https://dendron.so/notes/401c5889-20ae-4b3a-8468-269def4b4865.html#change-the-sorting-order-in-the-outline-panel)

**Comment by rishabhsagar** [comment]
Thanks, this works.
