### ISSUE TITLE
Support gitlab pages target in dendron publish command

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3256]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Currently it is possible to set the output to the correct folder for a github pages site using the `--target` flag in the `dendron publish export` command, but not gitlab pages.

## Describe the solution you'd like ##

An option in this flag for gitlab.

## Additional context ##

I'm pretty sure it should just be adding a new branch to the `switch` statement in the below function that accepts gitlab and instead of `docs` the folder is instead `public`, and wherever converts from flags to the calls, but I don't know how to add all the tests and everything else that would be required to do this contribution.

https://github.com/dendronhq/dendron/blob/4132cd35eb76bc2a19f5a8e0309cee755e9bf42e/packages/dendron-cli/src/commands/publishCLICommand.ts#L286-L327

**Comment by hikchoi** [comment]
Thank you for the suggestion!
