### ISSUE TITLE
Making Dendron Form-idable

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#327]
## Context

Currently, the way Dendron does inputs is via raw YAML. This is not the most human friendly interface. 

## Proposal

Use forms to provide a nice UI plus realtime validation when users are working with Dendron. 

- [x] Configure Dendron Command
    - will bring up a webview to edit `dendron.yml`
- [x] Support viewing Dendron Config 
    - web view that shows `dendron.yml` as a form
- [x] Support writing to Dendron Config 
    - be able to persist changes in `dendron.yml`
- [x] Add validation for form 
    - [ ] research whether we should use [formik](https://formik.org/) alongside antd form

## Details

Dendron has a next.js server that will be used alongside a webview to render nice UIs for Dendron. 

Ideally, we want to use [formik](https://formik.org/) for validation and [antd forms](https://ant.design/components/form/) to render. If formik looks like overkill or redundant with the basic validation within atnd, then we can drop that requirement

## Breadcrumbs

Some useful resources to get started

- building and starting the server: https://dendron.so/notes/7cdd9a74-8b8f-4564-906b-c963bed34273.html
- type definitions for `dendron.yml` config: https://github.com/dendronhq/dendron/blob/master/packages/common-all/src/types.ts#L44:L44
- documentation for config: https://dendron.so/notes/ffa6a4ba-5eda-48c7-add5-8e2333ba27b4.html

## Notes

To get started, I would focus on being able to import and build Dendron and having a basic form interface generated from `dendron.yml`.

To get started, I would hardcode a sample config. We will be adding an API to write/read to it ~1week.

**Comment by tsnieman** [comment]
Interested in contributing to this feature.

First chunk of this work looks like this for me:

- [x] ~~Get dev server running~~ 2020.11.09 :heavy_check_mark: 
- [ ] make a new Next page that had some placeholder forms on it. I haven't used AntD and want a little exposure there.
- [ ] (learn how to) create command to open server webview
- [ ] wire up `dendron.yml` to the webview for proper form rendering

**Comment by tsnieman** [comment]
This new Chrome extension might also be useful for debugging Formik :bookmark: https://github.com/petrenkoVitaliy/formik-devtools

**Comment by kevinslin** [comment]
Sweet. If it turns out to be helpful, can you add it to the docs for
`dendron-cli`:
https://dendron.so/notes/7cdd9a74-8b8f-4564-906b-c963bed34273.html?

**Comment by tsnieman** [comment]
I've [got a basic `formik` + `antd` experiment glued together in my local `dendon-next-server`](https://discord.com/channels/717965437182410783/748936364283920495/776688210540625950).

i'll flesh out actual form elements with `antd`, [basing the fields on the dendron configuration docs](https://www.dendron.so/notes/ffa6a4ba-5eda-48c7-add5-8e2333ba27b4.html) (and [type definitions for `dendron.yml`](https://github.com/dendronhq/dendron/blob/04da4c119531d8158c8d16b4b16f2e846b98259f/packages/common-all/src/types.ts#L44:L44)) in an upcoming sesh.

i suspect we'll want something like https://github.com/jannikbuschke/formik-antd to handle the bindings between the `antd` and `formik` (i've just manually plumbed them for my test).

**Comment by kevinslin** [comment]
closing this issue with the launch of dendron 0.18 :)
