### ISSUE TITLE
Link previews // Pretty URLs

### ISSUE THREAD

**Issue by tmladek** [dendronhq/dendron#329]
**Is your feature request related to a problem? Please describe.**
A significant portion of my notes is composed of briefly annotated URLs. My workflow right now is that I just paste the URL in a note, then write the comment below, but the bare URL is a bit ugly, and it can be quite difficult to tell at a glance what it contains. It's not as bad when the URL follows a reasonable format (https://example.com/posts/how-i-solved-my-note-taking-woes), but oftentimes that's not the case (https://twitter.com/tweeter/status/15246681041231653377).

**Describe the solution you'd like**
One solution that might be nice is to add an (optional) link preview feature to the Markdown preview sidebar, and pop up a box below the URL with some basic [Open Graph](https://ogp.me/) metadata. This would take care of the vast majority of social media posts, and a great deal of other documents too. The OG format is easy enough to parse (provided there's a HTML parser available), but one issue that I see is that it incurs a couple additional requests on each preview and I'm not sure how that would work out once the underlying document would start updating.

Alternatively, there would be no need for a whole "infobox", but just replacing the URL with the title of the page (either by `<title>` or Open Graph) would go a long way.

Another solution would be to add a command that inserts the URL in the format I described above, but as an "already baked-in" markdown snippet. This may not reside in core Dendron and could exist in a separate extension - as of now though, I wasn't able to find any VS Code extension with this functionality.

**Describe alternatives you've considered**
I checked the VS Code extension Marketplace, and I could not find an extension that matches either of the above proposed solutions.

I could of course just copy and paste the title manually below the URL, but I feel that goes a bit against the kind of frictionless UX that I love Dendron for.

Thanks for your consideration!

**Comment by kevinslin** [comment]
thanks for the feature request! i think having this makes sense and i appreciate that you took the time to list out specific solutions. 

based on the various implementations, i'm leaning towards being able to insert the url in a **pretty** format. 

one of the dendron [principles](https://dendron.so/notes/7fcebd7d-6411-4c9d-8baf-65629dc018a1.html#interoperability) is interoperability so having the entirety of the information in the text is preffered. 

this could be done as a separate command (eg. `Pretty URL`) and as an automatic formatting option when you're editing a document. 

going to mark this as a `good first task` and schedule it as a December milestone item if no one gets to this beforehand :)

**Comment by kevinslin** [comment]
Changes to make:
- create `Dendron: Paste Link` command
- should read link from clipboard and attach metadata from open graph
    - use the following package to get open-graph data: https://www.npmjs.com/package/open-graph-scraper

**Comment by hydrosquall** [comment]
Currently looking into this :)

**Comment by tmladek** [comment]
Very cool, thanks a lot! Could I ask to re-open the issue though? The opengraph stuff I mentioned doesn't seem to be implemented yet... Or did you decide against including it?

**Comment by kevinslin** [comment]
ah, you mean wrapping this as a div object with pictures, metadata and all? i might have mis-understood this to mean just the title. if so can you post a new issue ideally with a preview of what you'd like the output to look like?

**Comment by tmladek** [comment]
Well, not necessarily *all* that, I imagine some may consider it clutter; but `<og:description>` for instance is often quite useful too, I think. It's a question though, whether to split this into `PasteLink` and `PasteLinkDetailed`, add a menu, or neither of these... I'll put it in the issue if I come up with something, thanks :)

**Comment by kevins8** [comment]
I think we'll add it to the paste link command and give people an option to
toggle how much detail they want :)
