### ISSUE TITLE
Import Pod fails importing some of my content.

### ISSUE THREAD

**Issue by rogue2971** [dendronhq/dendron#3295]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [X] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Import Pod fails to import a large folder.

## To Reproduce

1. I filled in an import pod(path, vault and 'noAddUUID: true').
2. I tried to import the root folder(around 5 gigabytes, 40k markdown files), instead I got 2 errors, the one on the screenshot, and 'error while running command: EBUSY: resource busy or locked'.
3. I repeated that a few times, changing the import pod arguments and trying subfolders instead.
4. I managed to import a portion of my markdown content from Obsidian.

## Expected behavior

All folders being successfully imported.

## Screenshots

![image](https://user-images.githubusercontent.com/67639784/180808753-511824cb-16a9-449e-b023-ae1323cf927c.png)

## Desktop (please complete the following information)

- Windows x64 (not WSL): [e.g. iOS]
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

//removed after issue was closed

**Comment by jonathanyeung** [comment]
Thanks @rogue2971 for providing the detailed info and logs -unfortunately, nothing is popping out as the clear issue from what I can see so far. 

This kind of issue is likely caused when a particular note (or notes) has some syntax that trips up our parser.  We have a backlog item to better report to the user which note(s) are causing the issue, but unfortunately right now there's not a good methodology to figure out which ones are problematic.  The only way right now is to do trial and error and import subsections of your notes one group at a time.  Sounds like you've already tried that, but it obviously isn't very scalable for your 40K notes :/

**Comment by rogue2971** [comment]
Ok, I thought so, I was going to clean up them anyways, had too much functionality put in notes. Thanks then, I am going to learn the docs and functionality first, so I can use it on notes, that I've managed to import, so I close this issue.
