### ISSUE TITLE
Broken images in dendron local nextjs server

### ISSUE THREAD

**Issue by dweisiger** [dendronhq/dendron#3296]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I have a path `![][/assets/images/foo.png` When I run the site locally with dendron publish dev, i see that the image links are broken. If I provide an alt text, it just shows the alt text and a broken image icon.

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by jonathanyeung** [comment]
Thanks @dweisiger for reporting the issue. 

From the Discord chat - it sounded like when you did the publish to the actual site, the images are working, it's just during local host testing that the images don't work? 

Something that comes to mind for this kind of discrepancy is maybe different versions of dendron-cli being used, which handles the bulk of the publishing logic.  Can you check the version of dendron-cli you have installed locally and upgrade it to the latest to see if the issue still happens?  (> version 100 should generally be ok)

in a command prompt:
> `dendron --version`

To upgrade:
> `npm install @dendronhq/dendron-cli@latest`
