### ISSUE TITLE
Toggle Preview doesn't toggle preview off when focus is on the preview itself

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#3309]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
When a note preview is open and the focus is on the note preview itself, `Dendron: Toggle Preview` tries to find a note from the active editor, fails to find it, and displays an error toast message instead of closing the note preview.

## To Reproduce

1. Open a note
2. Using `Dendron: Toggle Preview` to toggle the preview on
3. Change editor focus to note preview
4. Use `Dendron: Toggle Preview`

## Expected behavior
`Dendron: Toggle Preview` sees the already open and focused preview and closes it instead of looking for an active note.

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Thanks @hikchoi for the bug report. can repro

**Comment by Harshita-mindfire** [comment]
This should be fixed with Dendron v0.106. Feel free to re-open if not the case

**Comment by hikchoi** [comment]
thanks. seems to be fixed
