### ISSUE TITLE
Use note title for wiki link names

### ISSUE THREAD

**Issue by mgielda** [dendronhq/dendron#334]
**Is your feature request related to a problem? Please describe.**

First up, congrats on a cool app! I started using Dendron and so far my single issue with it (after getting the hang of it) is that the metadata is not used more widely, especially for one important thing: named Wiki links. It would be so cool if a Wiki link got its "title" as what is displayed in the preview, and not a whole hierarchy - "something.foo.bar.Baz is cool", but "Baz is cool".

Would make this much more natural inline in text, if your concept is somewhere deep in a hierarchy but it's also a topic you might want to mention in a sentence.

**Describe the solution you'd like**

It would be great if either a) the behaviour by default would be for the link to use the title or b) there could be simple way to make this happen, like some special character before the name (e.g. a dot - [[.something.foo.bar.Baz]])

**Describe alternatives you've considered**

Naming everything explicitly, but this is such a pain in the neck. Especially when you rename things, change titles etc - it would be so cool to keep everything consistent by just using the metadata item which we already have.

**Comment by mgielda** [comment]
(of course I might be getting something wrong and it's already possible to do this, but I have not seen it)

**Comment by kevinslin** [comment]
thanks for the input! using the last part in the wiki link makes a lot of sense. 

for implementation, I like both your suggestions and think it makes sense to have both. Instead of a `.`, I might just have a `|` without a alias default to title `[[|something.foo.bar.Baz]]`. 

our november backlog is quite full at the moment but I've put this us a December milestone unless someone gets to it ahead of me :)

**Comment by ljantzen** [comment]
I like this, but I'd prefer if the frontmatter title was used instead of the last part of the wiki-link.

**Comment by kevinslin** [comment]
that would be something we could configure. eg. `dendron.defaultAlias: title|leafOfHierarchy`

**Comment by mgielda** [comment]
Thanks for the positive feedback :) Actually, I think the frontmatter title indeed is the best option for what to show. That;s what I had in mind but I didn't make myself clear. That would kind of make the frontmatter title much more useful.

Of course having a config for this does not hurt - indeed some people might even prefer the current behavior! But I'd make the frontmatter title the deafult, because that's what people expect in Wiki-like frameworks normally.

**Comment by kevinslin** [comment]
this is now implemented as a dendron option :)

https://dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f48.html#usenotetitleforlink
