### ISSUE TITLE
The ability to render a single note to pdf with only few clicks

### ISSUE THREAD

**Issue by jonschoning** [dendronhq/dendron#3351]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [ x ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ x ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

Dendron appears to be targeting rendering an entire website of notes to html.  While this is an interesting use case, it's currently very hard to get a pdf of a single note, to send in an email or share with colleagues.  This reduces it's appeal as a note taking application for meetings or for one-off items.  

The ability to render a single note to pdf with only few clicks would greatly expand the use cases for dendron.  

(Separately managing and keeping pandoc configured correctly isn't an ideal solution).

**Comment by kevinslin** [comment]
thanks for the feature request. this is actually been requested before in https://github.com/dendronhq/dendron/issues/1698 - will close this so we can dedup in one master ticket. meanwhile, could you 👍 the linked ticket? we use this as a signal when prioritizing features

**Comment by joelnitta** [comment]
Can this be reopened if it has not actually been fixed? I would like this feature as well.
