### ISSUE TITLE
List the recently updated/added notes on a page in published site

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3358]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I don't know when pages on a site have been updated with new information or changes.

## Describe the solution you'd like ##

An option on the root page potentially to show a list of the latest updated/created notes for users to be able to see what might be new or updated. 

## Describe alternatives you've considered ##

Keeping the page manually updated.

## Additional context ##

This becomes really useful when the site is shared with multiple people or is a standard reference site, and is something often used when I'm using confluence.

**Comment by hikchoi** [comment]
Thanks for the feature request.
This has been mentioned a few times and I agree this would be a useful feature. We'll keep track of this and let you know if we make any progress!
