### ISSUE TITLE
"error initializing notes","payload":"{\"message\":\"parse non ref not implemented

### ISSUE THREAD

**Issue by regoje** [dendronhq/dendron#336]
**Describe the bug**
Dendron doesn't load (tree is empty, "Starting Dendron..." message shows forever, lookup cannot create new note)

**To Reproduce**
* Happens on start, but not sure how to reproduce the condition
* Must be something in my notes, but I don't know exactly what

**Screenshots**
![Screenshot from 2020-11-11 16-07-36](https://user-images.githubusercontent.com/1166932/98787787-e7c3bd00-243a-11eb-8ce1-7fffad741b96.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu

** Dendron Log file**
e: Removed logs with my username.

**Comment by regoje** [comment]
So, figured it out. 

The issue was that one my notes had a part that looked like this:

![Screenshot from 2020-11-11 16-28-54](https://user-images.githubusercontent.com/1166932/98787880-0924a900-243b-11eb-9be1-9b8d656a09af.png)

**Comment by kevinslin** [comment]
The issue is because Dendron uses `(( ... ))` for [note refs](https://dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c.html). we are also planning on expanding this syntax for other functions in the future. 

did you have `((` instead of `[[` before when the error was thrown?

**Comment by regoje** [comment]
Those are (( -- they just look similar to [[ because of the font so that's
probably the cause.

I fixed it by wrapping the code in ```

**Comment by kevinslin** [comment]
got it. yeah, that's expected behavior. we're going to make the parser more lenient by not throwing the error during initialization but rendering it during preview moving forward.
