### ISSUE TITLE
Unable to initialize engine

### ISSUE THREAD

**Issue by ryepesg** [dendronhq/dendron#337]
**Describe the bug**

**To Reproduce**
1. Trying to open vscode in the Dendron workspace never finished, and non of the commands work (e.g: Error: Unable to resolve non-existing file)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Version 10.15.7

** Dendron Log file**

{"ctx":"ReloadIndex.execute","error":{"name":"RequestError","message":"Error: Invalid protocol: localhost:","cause":{},"error":{},"options":{"url":"http://localhost:64533/api/workspace/initialize","qs":{},"body":{"uri":"/Users/yepesr/Dendron","config":{"vaults":["/Users/yepesr/Dendron/vault"]}},"json":true,"method":"POST","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}},"msg":"unable to initialize engine"}

{"level":30,"time":1605131757343,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1605131757376,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"/Users/user/Library/Application Support/Code/logs/20201112T085555/exthost1/dendron.dendron","extensionPath":"/Users/user/.vscode/extensions/dendron.dendron-0.15.0","extensionUri":{"$mid":1,"fsPath":"/Users/user/.vscode/extensions/dendron.dendron-0.15.0","path":"/Users/user/.vscode/extensions/dendron.dendron-0.15.0","scheme":"file"},"storagePath":"/Users/user/Library/Application Support/Code/User/workspaceStorage/8b93c91ee5ca332a22e0450c90a0691f/dendron.dendron"}
{"level":30,"time":1605131757377,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1605131757377,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.15.0","migratedGlobalVersion":"0.15.0","previousGlobalVersion":"0.14.0","previousWsVersion":"0.0.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"equinusocio.vsc-material-theme","version":"33.0.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":false},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.2","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.8","active":false},{"id":"dendron.dendron-markdown-notes","version":"0.0.17","active":false},{"id":"github.github-vscode-theme","version":"1.1.5","active":false}],"workspace":"/Users/user/Dendron/vault"}
{"level":30,"time":1605131757388,"pid":7912,"hostname":"REDACTED","name":"dendron.server","ctx":"launch","msg":"exit","port":64692,"LOG_DST":"/Users/user/Library/Application Support/Code/logs/20201112T085555/exthost1/dendron.dendron/dendron.server.log","lvl":"info"}
{"level":30,"time":1605131757388,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"_activate","msg":"post-start-server","port":64692}
{"level":30,"time":1605131757414,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":50,"time":1605131757422,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"ReloadIndex.execute","error":{"name":"RequestError","message":"Error: Invalid protocol: localhost:","cause":{},"error":{},"options":{"url":"http://localhost:64692/api/workspace/initialize","qs":{},"body":{"uri":"/Users/user/Dendron","config":{"vaults":["/Users/user/Dendron/vault"]}},"json":true,"method":"POST","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}},"msg":"unable to initialize engine"}
{"level":30,"time":1605131801519,"pid":7912,"hostname":"REDACTED","name":"dendron","ctx":"execute","opts":{}}

**Comment by kevinslin** [comment]
hmm, do you have a non-standard network settings? Dendron starts a local server and what this log is indicating is that it is unable to connect to it.

**Comment by ryepesg** [comment]
Hi Kevin, thanks a lot for your reply. It was indeed a problem with the proxy I am using. The error went away when I lunched vscode from a terminal without http_proxy /  https_proxy environment variables. Closing the issue now, keep up the great work!
