### ISSUE TITLE
Command: Set Task Status does nothing

### ISSUE THREAD

**Issue by samuelxyz** [dendronhq/dendron#3378]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Command: Set Task Status updates the `updated` property in the frontmatter of the task note, but does not change the `status` property of the task note.

## To Reproduce

1. Open a task note or place your cursor in a wikilink pointing to a task note
2. Run command `Dendron: Set Task Status`
3. Select one of the status options
4. The status in the frontmatter of the task note does not change.

## Expected behavior

The status in the frontmatter of the task note changes.

## Desktop (please complete the following information)

- OS: Windows 11 Home 10.0.22000
- Browser (if with published websites; include version): [e.g. chrome, safari] N/A
- Versions (all that apply to bug):
  - Dendron Extension: v0.107.2
  - VS Code version: 1.70.0
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

[dendron.log](https://github.com/dendronhq/dendron/files/9302907/dendron.log)

**Comment by samuelxyz** [comment]
Update: I discovered that this was only happening in one specific task note, and fixed itself after reloading the window.

**Comment by hikchoi** [comment]
Thank you for the report and update. Do let us know if you run into this again.
