### ISSUE TITLE
Case-insensitive alphabetization

### ISSUE THREAD

**Issue by ryan-p-randall** [dendronhq/dendron#3418]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

It always surprises me when the alphabetization of notes in the Tree View sorts capital letters before lowercase letters. I would expect the tree view's alphabetization to be case-insensitive.

<img width="295" alt="Dendron's tree view showing Alphabet, Aack, and App" src="https://user-images.githubusercontent.com/850915/185281331-06028037-4201-473f-b013-76e631302cf0.png">

As the screenshot above shows, the current alphabetization logic will sort `ALPHABET` before `Aack` or `App`. 

This becomes a problem when I want notes to be sorted purely by the alphabet, while also having note whose titles are abbreviations or all-caps.  

For instance, if I wanted to have a note about `De La Soul` and one about `DMX` in a published website, right now DMX would be sorted above De La Soul. Similarly, `NYU` would be sorted above `New School` in a set of notes about universities in New York City.

## Describe the solution you'd like ##

I think that the alphabetization logic should entirely ignore capitalization. It's excellent that the tree view will display a note's title as it's written in the YAML header, but I'd prefer that it not affect the sort order.

## Describe alternatives you've considered ##

Alternately, perhaps there could be a setting that allows users to switch between the current behavior and case-insensitive alphabetization.

For a very small set of notes, `nav_order` could be used to change the order how the notes are displayed. However, I think this would be cumbersome to use just to emulate case-insensitive alphabetization.

## Additional context ##

N/A

**Comment by jonathanyeung** [comment]
@ryan-p-randall - so do you prefer DMX or De La Soul? 

Jokes aside - a fix for this should go out in the next release or two: https://github.com/dendronhq/dendron/pull/3420

**Comment by ryan-p-randall** [comment]
It looks like case-insensitive alphabetization is working, as of v0.109.1!  

Now with `title: DMX`, that note sorts after notes with `title: De La Soul` and `title: Del the Funky Homosapien`.

<img width="328" alt="Dendron Tree View with correct alphabetization" src="https://user-images.githubusercontent.com/850915/186792120-9c2cc36b-ee73-4452-999b-cad93776f559.png">

Thanks everyone!
