### ISSUE TITLE
"Error with parsing some schemas during initialization" on clean install

### ISSUE THREAD

**Issue by konrad-jamrozik** [dendronhq/dendron#342]
**Describe the bug**
Upon clean install by following the quickstart instructions from dendron.so, when Dendron workspace is opened for the first time, the following error pops up in lower-right: "Error with parsing some schemas during initialization".

**To Reproduce**
1. Install Dendron via https://marketplace.visualstudio.com/items?itemName=dendron.dendron
2. In VS Code, Ctrl+Shift+P, then "Dendron: Initialize Workspace"
3. Now Dendron Workspace VS Code starts, showing the error in bottom right.

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/4429827/99143156-252d7380-2610-11eb-8d87-c44f421ef69d.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows, Version 2004 (OS Build 19041.630)

**Additional context**
I chose a path located in my OneDrive as Dendron workspace. Unlikely this is related, but mentioning just in case.

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/5540387/dendron.log)

**Comment by kevinslin** [comment]
Thanks for catching. This is a regression with our current set of starter documents. Will be fixed this weekend!

**Comment by kevinslin** [comment]
This has been fixed in Dendron 0.16
