### ISSUE TITLE
Publishing: assets are still copied to output directory even if `copyAssets=false`

### ISSUE THREAD

**Issue by bj0** [dendronhq/dendron#3425]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

If you set `copyAssets=false` in the publishing config, all of the vault assets are still copied to `.next/out/assets`.

The documentation for `copyAssets` is here: https://wiki.dendron.so/notes/rdlj5swXCOyaIqdk98f93

## To Reproduce

add `copyAssets=false` to the publishing config, and execute `npx dendron publish export`.

## Expected behavior

No assets in the output directory.

## Desktop (please complete the following information)

- OS: Ubuntu
- Browser (if with published websites; include version): n/a
- Versions (all that apply to bug):
  - Dendron Extension: 0.108.0
  - VS Code version: 1.70.1
  - Dendron CLI: 0.108.0

**Comment by Harshita-mindfire** [comment]
This should be fixed after Dendron v0.111. Feel free to ping here if that is not the case.
