### ISSUE TITLE
Publishing: `siteHierarchies` copies all notes to output directory

### ISSUE THREAD

**Issue by bj0** [dendronhq/dendron#3426]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The documentation suggests that adding a hierarchy to `siteHierarchies` in the publishing config should publish only that hierarchy (or set of added hierarchies).  The published output, however, contains a `.next/out/data` directory that contains all the notes in the vault.  

The generated index correctly only shows the hierarchy listed in the config, but the output directory should *not* contain a copy of all notes in a vault.  For someone who uses a single vault for everything, this could expose private notes.

The documentation is here: https://wiki.dendron.so/notes/8Qpabm7YvMzxJ7Xs5uFU9/

## To Reproduce

Add a hierarchy to `siteHierarchies` and run `npx dendron publish export`.

## Expected behavior

Only notes from the exported hierarchy should be included in the output directory.

## Desktop (please complete the following information)

- OS: Ubuntu
- Browser (if with published websites; include version): n/a
- Versions (all that apply to bug):
  - Dendron Extension: 0.108.0
  - VS Code version: 1.70.1
  - Dendron CLI: 0.108.0

**Comment by jonathanyeung** [comment]
Thanks @bj0 for flagging this.  We should fix this issue, but until then we should at least flag it in our documentation that the current behavior will put the notes in the `out` dir.

**Comment by Harshita-mindfire** [comment]
This should be fixed after Dendron v0.111. Feel free to ping here if that is not the case.
