### ISSUE TITLE
Dendron Markdown preview stopped recognizing links even though all Dendron extensions are installed

### ISSUE THREAD

**Issue by konrad-jamrozik** [dendronhq/dendron#343]
**Describe the bug**
Observe in the screenshot below that the links in the markdown preview do not render properly, even though I have all Dendron extensions installed.

**To Reproduce**
Hard to say what exactly what I did, but I believe the problem appeared once I have uninstalled the "Material Theme" extension. Before that the links were good.

**Expected behavior**
Links rendering properly.

**Screenshots**

The problem when at first observed, after I uninstalled Material Theme:
![image](https://user-images.githubusercontent.com/4429827/99143764-efd75480-2614-11eb-815a-f7386005216d.png)

and here is how it looks after my failed attempt at fixing by reinstalling all Dendron extensions and reinitalizing workspace:
![image](https://user-images.githubusercontent.com/4429827/99143832-928fd300-2615-11eb-80aa-091553f728d9.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows, Version 2004 (OS Build 19041.630)

**Additional context**
I made several attempts at fixing the problem, all of which failed.
- Disable all Dendron extensions, reload VS code, enable the extensions.
- Delete Dendron workspace and re-initialize.
- Uninstall all Dendron extensions, delete Dendron workspace, restart VS Code, re-install Dendron, re-initialize workspace.

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/5540412/dendron.log)

Note: this is the log I got after full extension reinstall and reinitializing workspace. Links still broken.

**Comment by kevinslin** [comment]
It looks like you are using the regular vscode markdown preview. This is a common issue since there's currently no way for us to disable the builtin preview. See [this](https://dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#why-cant-i-click-the-checkbox) for instructions on fixing

**Comment by konrad-jamrozik** [comment]
@kevinslin thank you, that fixes it. Some extra hints for anybody reading this:

**Do** use the `Dendron: Show Preview` command:
![image](https://user-images.githubusercontent.com/4429827/99155930-702ba300-2671-11eb-9c2b-0047ef0bddd4.png)

Alternatively, on Windows, **do** use, Ctrl+K, V:
![image](https://user-images.githubusercontent.com/4429827/99155972-d57f9400-2671-11eb-81fc-53a72de9464c.png)

**Do not** use `Open Preview` from context menu, as this is the normal, broken preview:
![image](https://user-images.githubusercontent.com/4429827/99155910-33f84280-2671-11eb-85bd-1ec236273a60.png)

One thing that was bothering me in the initial setup is that once I made everything dark theme, I was not sure how to change the Dendron preview theme. I found it here:

![image](https://user-images.githubusercontent.com/4429827/99155945-981b0680-2671-11eb-864c-a0d7e9906ccf.png)
