### ISSUE TITLE
Lookup Note Creation does not Respect Title Case

### ISSUE THREAD

**Issue by HeuFui** [dendronhq/dendron#344]
**Describe the bug**
You're creating a new note through lookup. You carefully type its title using Title Case (sometimes it's the name of a person or author). When said note is created, the title case isn't respected in this new note's title.

This is not a big problem _per se_. Typing Something Like This and getting 'Typing something like this' is not so bad. It's worse when you have as title the name of a person or author. For instance, when you create a new with something like 'Georg Wilhelm Friedrich Hegel's Science of Logic circularity' and get as its title 'Georg wilhelm friedrich hegel's science of logic circularity', it becomes, well, weird.

Example:
![1](https://user-images.githubusercontent.com/7608736/99144970-74dc6100-2649-11eb-8074-7bda04d3576d.png)

![2](https://user-images.githubusercontent.com/7608736/99144975-802f8c80-2649-11eb-99d6-5c4e80dd1e6f.png)

**To Reproduce**
1. Go to lookup;
2. Create a new note with Title Case;
3. Check new note's title.

**Expected behavior**
What's expected is that the casing used during the note creation is respected in the title of the new note.

**Comment by kevinslin** [comment]
Thanks for the issue. Will be adding it to this months backlog!

**Comment by kevinslin** [comment]
shipped in 0.20
