### ISSUE TITLE
Ability to see backlink's descendants when viewing backlinks

### ISSUE THREAD

**Issue by tsnieman** [dendronhq/dendron#345]
**Is your feature request related to a problem? Please describe.**
if i'm looking at backlinks for `foo`, i'd like a way to see all descendants like `foo.bar`, `foo.bar.buzz`, etc references as well.

**Describe the solution you'd like**
When viewing the backlinks panel (or #237/window), an ability to see `foo` (exact backlinks) AND `foo.**` (exact backlinks + all descendants)

**Describe alternatives you've considered**
n/a

**Additional context**
Discord convo: https://discord.com/channels/717965437182410783/749641193322971238/777213399049437255

**Comment by gereleth** [comment]
Is this asking for the same thing as #212?

**Comment by kevins8** [comment]
You're right! I'm triaging issue's this week so will be merging this as a
dup and pushing this back up the prioritization list

**Comment by kevinslin** [comment]
closing in favor of #212
