### ISSUE TITLE
Can't create scratch notes

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#346]
**Describe the bug**
I cannot create scratch notes. I can choose one for creation but then nothing happens.

**To Reproduce**
1. In a newly installed vcsodium with dendron installed via vsix on Windows
2. Click on 'Strg+L'
3. Choose the scratch note icon
4. Lookup bar shows new scratch note name
5. Click on 'Create New'

**Expected behavior**
A new scratch note is created
**Screenshots**
![grafik](https://user-images.githubusercontent.com/3171330/99155195-071a4e80-26b6-11eb-94eb-2ade1a863ce9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Dendron 0.15.2

**Additional context**

** Dendron Log file**
Please 
[Scratch.log](https://github.com/dendronhq/dendron/files/5541330/Scratch.log)
attach the output of `>Dev:Dendron: Open Logs` here

**Comment by konrad-jamrozik** [comment]
Same issue here.

**Comment by konrad-jamrozik** [comment]
Same issue. I can create normal notes, but I cannot create scratch or journal notes. I attach logs after my unsuccessful attempt at creating journal note, by clicking on the blue area as seen here:

![image](https://user-images.githubusercontent.com/4429827/99157677-02d33e80-2680-11eb-8ce1-c8d2ef95aef3.png)

[dendron.log](https://github.com/dendronhq/dendron/files/5541505/dendron.log)

I also tried to attach server log, by [following these](https://www.loom.com/share/a05b0cf597b44e579b77ad76e3af4c07) instructions, but the server logs do not appear in the popup menu:

![image](https://user-images.githubusercontent.com/4429827/99157697-31e9b000-2680-11eb-9c3e-ebb52ef8e8bb.png)

**Comment by Bassmann** [comment]
Creating journal notes works for me

**Comment by kevinslin** [comment]
@konrad-jamrozik 
can you try this latest build of dendron and see if the issue still persists? if it does - there is a lot more logging in this build so attach the output of `Open Logs` to this build again and we should see what the problem is.

https://artifacts-prod-artifactb7980f61-19orqnnuurvwy.s3.amazonaws.com/publish/dendron-0.15.3-alpha.1.vsix

- instructions to install: https://dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#manual-install

**Comment by konrad-jamrozik** [comment]
@kevinslin I tried the alpha:

![image](https://user-images.githubusercontent.com/4429827/99161320-011c7180-26a6-11eb-880b-cc0d1504ec51.png)

I got "Something went wrong" error:

![image](https://user-images.githubusercontent.com/4429827/99161325-0974ac80-26a6-11eb-8d19-cd540894daa8.png)

Logs here:

[dendron.log](https://github.com/dendronhq/dendron/files/5541742/dendron.log)

**Comment by kevinslin** [comment]
okay, this is great. can you try this build and confirm whether the issue is still there?

**Comment by konrad-jamrozik** [comment]
It worked! Now I can make journal, scratch and normal notes. Thanks @kevinslin for quick turnaround! :)

**Comment by kevinslin** [comment]
Glad that we worked it out. Thanks for reporting :)

**Comment by Bassmann** [comment]
Works for me too. @kevinslin thanks a lot for the fast fix!
