### ISSUE TITLE
When run in Windows 10, Obsidian import creates only documents from 'root' directory

### ISSUE THREAD

**Issue by spacejunky** [dendronhq/dendron#348]
## Description
On Windows importing an Obsidian Vault (via markdown import pod) does not import documents from anything except the top level 'root' directory.

## To Reproduce
1. Create fresh Obsidian vault, one document in root, one in subfolder
2. Initialise fresh dendron vault
3. Configure import pod
4. Execute import
5. Observe that document from subfolder is not imported

## Expected behavior
Expected import of document from sub-folder with appropriate hierarchy file name.

### Obsidian Vault supposed to be imported
![image](https://user-images.githubusercontent.com/1111893/99183261-b6990480-273a-11eb-8c23-0eff51c60b92.png)

### Dendron vault after import (also showing log file)
![image](https://user-images.githubusercontent.com/1111893/99183309-04157180-273b-11eb-9ef2-df7c52e9754a.png)

## versions
 - OS: Windows 
![image](https://user-images.githubusercontent.com/1111893/99183392-ac2b3a80-273b-11eb-8ef4-c2299c177bab.png)

- VSC
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

- Dendron 0.15.0

## Additional context
Import works as expected when run in Crostini/Chromeos

## Dendron Log file
Log file shown in dendron screenshot above

**Comment by kpathakota** [comment]
Can no longer repro this. @spacejunky - let me know if you still see it and please reopen with fresh logs.
