### ISSUE TITLE
Tree view shows nothing after adding the dendron site seed

### ISSUE THREAD

**Issue by HenryC-3** [dendronhq/dendron#3487]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

-   [ ] Workspace. VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
-   [ ] Lookup. Dendron's Lookup Command
-   [x] Views. Dendron Preview, Tree View, Side Panels in the UI
-   [ ] Schema. Dendron Schemas
-   [ ] Pod. Data import from / export to Dendron
-   [ ] Publish. External Site Publish
-   [ ] Markdown. Markdown features, such as syntax support and features

## Describe the bug

Dendron tree view shows nothing after adding the dendron-site seed.

## To Reproduce

-   This behavior can be reproduced in dendron `0.109.1` and `0.110`
-   the vault used in this section: [dendron-vault at tree-view-bug](https://github.com/HenryC-3/dendron-vault-initialized/tree/tree-view-bug)
-   the seed used in this section: dendron-site

1. add the dendron-site seed to the vault

## Expected behavior

Dendron tree view shows the hierarchy 

## Screenshots

-   after adding dendron-site seed in version 0.110 
<img width="1413" alt="c74a0aaeff3b696855ad38079a76338c5588cb68446aee64ecfda67dfb21d238" src="https://user-images.githubusercontent.com/41246463/188296553-dc95ab99-6d8f-421a-a8e2-771f6ffbb9df.png">

<img width="1475" alt="f15ea0472791122dcdee067feffa9cad3f9ab0bea9e4b04275ef965a9da93f8b" src="https://user-images.githubusercontent.com/41246463/188296152-ec901f5b-03fe-49ec-a696-33611198af55.png">

-   after adding dendron-site seed in version 0.109 
<img width="1413" alt="4315640a4eebb0677c6f92dabb3b2ddb0686d3fcb14f098c3366bf7182fcc119" src="https://user-images.githubusercontent.com/41246463/188296148-ece9ac25-1b71-4cac-b531-cf8e8f192b75.png">

## Desktop (please complete the following information)

-   OS: MacOS
-   Browser (if with published websites; include version): [e.g. chrome, safari]
-   Versions (all that apply to bug):
    -   Dendron Extension: 0.110 or 0.109.1
    -   VS Code version: 1.71.0
    -   Dendron CLI: 0.107.0

## Dendron Log file
[dendron.log](https://github.com/dendronhq/dendron/files/9483795/dendron.log)

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by kevinslin** [comment]
can reproduce. thanks for the issue, we'll update this ticket when we have a fix merged

**Comment by kevinslin** [comment]
fix is merged and should come out in the next release :)

**Comment by kevinslin** [comment]
this should be fixed now. @HenryC-3 do you still see this after the latest release?
