### ISSUE TITLE
markdown.experimental.updateLinksOnFileMove.enabled

### ISSUE THREAD

**Issue by mrienstra** [dendronhq/dendron#3507]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

The `markdown.experimental.updateLinksOnFileMove.enabled` setting was released in the [August 2022 version (1.71) of Visual Studio Code](https://code.visualstudio.com/updates/v1_71#_markdown-link-update-on-file-move-and-rename).

>With this new experimental setting enabled, VS Code will automatically update links and images in Markdown when files are moved or renamed in the VS Code Explorer:
>
>This new behavior can be enabled using the `markdown.experimental.updateLinksOnFileMove`.enabled setting. You can control the types of files affected using `markdown.experimental.updateLinksOnFileMove.externalFileGlobs`.

I haven't tested it yet, but I can imagine this new setting might clash with [Dendron: Rename Note](https://wiki.dendron.so/notes/g0iqmyiyxje6ndjmecshb8b/), though I'd imagine very few people will be affected if so.

## Describe the solution you'd like ##

It seems wise to keep an eye on `updateLinksOnFileMove`, in the near future it may no longer be "experimental" (though I have no idea how long that process generally takes).

## Describe alternatives you've considered ##

When (if) it becomes a full-fledged setting, some possibilities:

1. Inform users that they shouldn't enable it, if it clashes with Dendron.
2. Detect when it is enabled, and:
  A) Warn the user and / or
  B) Disable the part of `RenameNoteCommand` that fixes wikilinks
3. Alter Dendron to rely on VS Code's `updateLinksOnFileMove` -- maybe it'll be a better implementation in some way, and doing so would simplify Dendron, meaning fewer possible sources of bugs / devs can focus efforts on other features.

**Comment by hikchoi** [comment]
Thank you for the heads up. @mrienstra 

To my knowledge, VSCode's markdown features are only dealing with what  CommonMark specifies, so wikilinks (not standard markdown) are not part of what they update.

It also seems like the behavior is hooked with VSCode's rename command, and Dendron's rename command is independent of what the built-in rename does.

We haven't done any extensive tests to make sure everything is safe, so I'll keep this open until we figure that out. You are welcome to close the issue if you wish of course; we will still keep an eye out for potential clashes.
