### ISSUE TITLE
Add support for a key binding to insert a hyperlink

### ISSUE THREAD

**Issue by konrad-jamrozik** [dendronhq/dendron#352]
**Is your feature request related to a problem? Please describe.**
Inserting hyperlinks (`[]()`) is cumbersome.

**Describe the solution you'd like**
I would like to be able to select some text, say, "foo", press a key binding for inserting a hyperlink, and make Dendron automatically decorate the text with `[foo]()`, with cursor positioned inside the parentheses. 
This is the behavior Microsoft solutions have under Ctrl+K, like OneNote, Outlook, Azure DevOps wiki. They call it "Insert Hyperlink".

**Describe alternatives you've considered**
I am currently using `md-shortcut.toggleLink` from https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts, as explained on Discord here: https://discord.com/channels/717965437182410783/742532267058004098/777702310431817769

**Additional context**
N/A

**Comment by kevinslin** [comment]
Dendron comes bundled with the markdown shortcuts extension. You can trigger a hyperlink with `Markdown Shortcuts: Toggle Hyperlink`. This can be bound to a custom keyboard shortcut. We can also do a better job of documenting this :)

**Comment by konrad-jamrozik** [comment]
Hah, that would explain why I have seen duplicates of the commands in the context menu. Thanks for clarification :) @kevinslin I'll leave it to you if you want to keep this issue open to keep track of the documentation work, or if to close it.

**Comment by kpathakota** [comment]
@kevins8 - were you thinking this is just a documentation task or can we set a preference to the the usual "ctrl/cmd + k" shortcut by default?

**Comment by kevinslin** [comment]
just a documentation task

**Comment by kpathakota** [comment]
https://wiki.dendron.so/notes/3472226a-ff3c-432d-bf5d-10926f39f6c2.html#markdown-links
