### ISSUE TITLE
Toggle search in published site via a hotkey / keybinding

### ISSUE THREAD

**Issue by dionysuzx** [dendronhq/dendron#3534]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Yes, I have to click the search bar to search in Dendron published site or use a third party extension like vimium. 

## Describe the solution you'd like ##

I want to be able to toggle search with, for example, "command + k" on the Dendron published site. Look at https://www.nushell.sh/ for a great example at what I'm looking for. Specifically I need to be able to toggle the search and ESC out. The keybind should be obvious and on the UI so the user knows how to use it naturally, and should be able to read the operating system (command for mac, etc.). 

## Describe alternatives you've considered ##

N/A

## Additional context ##
Screenshots of desired solution:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/13951458/190724472-d11887bd-2841-4b42-8fab-c2ad16e80aab.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/13951458/190724579-1d805d52-57b8-4547-b7bb-1751394ddb72.png">

**Comment by jonathanyeung** [comment]
Thanks for the suggestion @d1onys1us. @Harshita-mindfire - maybe something to consider if we can incorporate it as part of the work around changing the site lookup bar.
