### ISSUE TITLE
"Dendron: Show Note Graph" throws an error

### ISSUE THREAD

**Issue by konrad-jamrozik** [dendronhq/dendron#354]
**Describe the bug**
After I run the command `Dendron: Show Note Graph`, instead of seeing the graph, I get an error:
![image](https://user-images.githubusercontent.com/4429827/99205158-836f6900-276c-11eb-997f-c506e90bb697.png)

**To Reproduce**
1. Run `Dendron: Show Note Graph` or `Dendron: Reload Graphs`.
2. Observe the error (the same for both cases).

**Expected behavior**
To see the graph view in step 2, for `Show Note Graph`.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows, Version 2004 (OS Build 19041.630)

**Additional context**
This is my `root.md`:

```
---
id: 9994522b-bf55-4583-bfb3-f9cb5949076b
title: Root
desc: ''
updated: 1605492005428
created: 1605484949703
---
# Welcome to Dendron

This is the root of your dendron vault. If you decide to publish your entire vault, this will be your landing page. You are free to customize any part of this page except the frontmatter on top. 
````

This is my `root.schema.yml`:
```
version: 1
imports: []
schemas:
  - id: root
    children: []
    title: root
    parent: root
```

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/5543660/dendron.log)
[dendron.server.log](https://github.com/dendronhq/dendron/files/5543661/dendron.server.log)

**Comment by kevinslin** [comment]
@konrad-jamrozik this is because of the recent changes we made to give root nodes unique ids instead of a hard coded default. will be fixed either today or tomorrow. also, kudos on all the bug finding this past week 😅 🐛 🔨

**Comment by kevinslin** [comment]
This is now fixed in dendron-markdown-links  v0.6.16. if you reload your vscode workspace, you should be automatically upgraded. will close this ticket after you confirm that its working :)

**Comment by konrad-jamrozik** [comment]
@kevinslin it works now! I reported another bug: #359. Thanks for the bug cather role! Glad to help :)

**Comment by kevinslin** [comment]
Awesome, just responded to the issue there. Also, you've now earned the Taxonomist role for correcting my typos 😅
