### ISSUE TITLE
Unknown Error when trying to export NextJS site

### ISSUE THREAD

**Issue by ericthomas1** [dendronhq/dendron#3545]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

1. Following the instructions [here]()
2. Installed the lates `dendron-cli`
3. Ran the command `npx dendron publish init`

```
PS C:\Users\me\Documents\Dendron> npx dendron publish init
� checking if .next directory exists.
� .next directory exists
� updating NextJS template.
� failed to update next NextJS template working copy (Error: fatal: not a git repository (or any of the parent directories): .git
); cloning fresh
- {"level":50,"time":1663623712800,"pid":1256,"hostname":"mycomp","name":"publish <cmd>","stack":"TypeError: fs_extra_1.default.rm is not a function\n    at Function.removeNextPath (C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\@dendronhq\\dendron-cli\\node_modules\\@dendronhq\\pods-core\\lib\\builtin\\NextjsExportPod.js:80:34)\n    at PublishCLICommand._removeNextPath (C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\@dendronhq\\dendron-cli\\lib\\src\\commands\\publishCLICommand.js:345:48)\n    at PublishCLICommand.init (C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\@dendronhq\\dendron-cli\\lib\\src\\commands\\publishCLICommand.js:283:28)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","type":"Error","msg":"fs_extra_1.default.rm is not a function"}
unknown error [object Object]
```

Hangs here

## To Reproduce

See above

## Expected behavior

A static site based on my copious notes would be generated.

## Desktop (please complete the following information)

- OS: Windows 10
- Browser (if with published websites; include version): Chrome
- Versions (all that apply to bug):
  - Dendron Extension: 9/13/2022 06:32:37
  - VS Code version: 1.71.2
  - Dendron CLI: 0.112.1

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here
- Has `hostname` and `User`. Not for public.

**Comment by jonathanyeung** [comment]
Thanks for filing @ericthomas1 - we'll investigate.

**Comment by Harshita-mindfire** [comment]
Hey @ericthomas1, the `failed to update next NextJS template working copy (Error: fatal: not a git repository (or any of the parent directories): git` info message is displayed when you have an exiting `next-js template` in your workspace (.next folder) and it does not have a .git folder inside(.next/.git). 
Dendron then removes the existing `.next` folder and clones a fresh template. Unfortunately, I can't repro the `fs.rm is not a function error`, 
![image](https://user-images.githubusercontent.com/84971366/191260903-05b6c532-4d02-44ca-9371-221ee7bb5c43.png)

Can you try deleting the `.next` folder manually and then run `npx dendron publish init` again?

**Comment by ericthomas1** [comment]
Thank you. It appears that I was on VPN when attempting first time. It blocked the outbound request. Deleted the .next dir, tried off VPN, that worked.
