### ISSUE TITLE
Unable to use ` type text in note title

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#3557]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When the title of the note in the front matter is surrounded by `s the text is not rendered as a `code` the same way it is if specified in any other header you place into the note.

## To Reproduce

1. Create a note
2. Set the title in the front matter to `word`
3. See it renders the ` explicitely.

## Expected behavior

It would render the same way it does if you type `` # `word` `` in your note

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.113
  - VS Code version:
  - Dendron CLI:

## Additional context

I have tried escaping, quotes, backslashes, more backticks, etc.

**Comment by Harshita-mindfire** [comment]
Thanks @rlh1994 for the bug report.
