### ISSUE TITLE
Lookup Note Creation only creates note in first vault

### ISSUE THREAD

**Issue by cldwalker** [dendronhq/dendron#356]
Hi,
Thanks for this exciting note app! I'm filing a bug report but maybe this is an enhancement request?

Cheers, Gabriel

**Describe the bug**
With two vaults in my workspace, dendron's and a personal one, lookup note creation only creates notes in the first vault. This is surprising when creating notes for schemas that are only in the personal vault.

**To Reproduce**
1. Have two vaults, dendron's "vault" and then a personal vault e.g. "my-vault" in my case
2. Define the following schema in my-vault:
 ```yml
version: 1
imports: []
schemas:
  - id: app
    title: app
    parent: root
```
3. Create a `app.X` note from lookup where X can be any name
4. Observe the note end up in dendron's vault instead of my-vault

**Expected behavior**
Expect a note to be created in the vault that has its schema.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: osx 10.13.1
 - Browser: n/a. In vscode
 - Version: 16

**Additional context**
As a workaround I can remove the dendron vault to have just one vault. Unfortunately this means removing/adding a 2nd vault each time I want to create a note in a 2nd vault which isn't a good experience.

** Dendron Log file**
n/a

**Comment by kevinslin** [comment]
Lookup for multi-vault will create new notes in the same vault as the current opened file. To create a note in vault2, first open a note inside vault2(by default, `root` will be created for each vault that you add).
We'll be adding the ability to manually specify a vault in upcoming releases.

**Comment by cldwalker** [comment]
@kevinslin Thanks! That works great. Would you like me to document this in https://www.dendron.so/notes/45cfb9f2-46cf-4f67-a41e-834818fbd06e.html#use-cases or some other document?

**Comment by kevinslin** [comment]
if you could add that to the docs, that would be great!
[under lookup](https://dendron.so/notes/24b176f1-685d-44e1-a1b0-1704b1a92ca0.html#lookup) would be the best place to add it. 
[here](https://dendron.so/notes/b58801fc-43a9-4d42-a58b-eabc3e8538cb.html) are instructions on contributing to the docs

thanks! 🙏
