### ISSUE TITLE
Clicking on any internal link in the doc site (apart from the TOC) reloads the page

### ISSUE THREAD

**Issue by vibl** [dendronhq/dendron#3570]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

In all the pages of https://wiki.dendron.so/, clicking on a link within a page reloads the entire page.

Note that this does not happen when clicking on links in the TOC.

## Desktop (please complete the following information)

- OS: Kubuntu 22.04
- Browser (if with published websites; include version): Chrome and Firefox, both latest
- Versions: whichever https://wiki.dendron.so/ uses

**Comment by alefteris** [comment]
I think this might be a duplicate of #3300 ?

**Comment by Harshita-mindfire** [comment]
Yep. Thanks for highlighting

**Comment by vibl** [comment]
Just so you know, the bug has not been solved on https://wiki.dendron.so/

The github action that closed this issue might be a little too trigger happy :-)

**Comment by Harshita-mindfire** [comment]
@vibl, this looks like a duplicate of https://github.com/dendronhq/dendron/issues/3300. Can we track this issue with #3300 instead?

**Comment by vibl** [comment]
Yes, sure :-)
