### ISSUE TITLE
"Show Note Graph" window has title "Notepropsv2 Links"

### ISSUE THREAD

**Issue by tsnieman** [dendronhq/dendron#358]
**Describe the bug**
The note graph window title is "Notepropsv2 Links"

**To Reproduce**
1. Use the "Dendron: Show Note Graph"
2. Look at title of the newly-opened note graph window

**Expected behavior**
It should say "Note graph" or something. I don't remember what it used to say, but it wasn't "Notepropsv2 Links" haha.

**Screenshots**
![Screenshot from 2020-11-16 18-12-45](https://user-images.githubusercontent.com/595711/99337738-b16daf80-2837-11eb-8f9b-e544fec43175.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] VSCode
 - Version [e.g. 22] 0.16.0

**Additional context**
Tried to hunt it down in the source for a few minutes but :shrug: couldn't find it.

** Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

n/a

**Comment by kevins8** [comment]
That's because I haven't pushed the latest code 😅
Just pushed and also corrected the title with v0.6.17 of dendron markdown
links
