### ISSUE TITLE
Option to remove the "book" icon from notes which have applied schema

### ISSUE THREAD

**Issue by andrey-jef** [dendronhq/dendron#3598]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

How to get rid of the “book” icon (for notes which have schema) in the left sidebar on a published page or in tree-view on Dendron-Vscode? This icon made the indentation of nodes’ name looking not in order.

## Describe the solution you'd like ##
An option to disable this "book" icon for notes which have applied schema, in both
- left sidebar of a published page and
- tree view in Vscode Dendron 

## Describe alternatives you've considered ##

N/A

## Additional context ##

N/A

**Comment by kevinslin** [comment]
we're working on this. should be removed in the next release

**Comment by aleksey-rowan** [comment]
@andrey-jef, the schema icon was removed in the [0.115](https://wiki.dendron.so/notes/r6440eigzebewsv6shlhid7/#everything-else) release. There is no config option though--it's just gone.
