### ISSUE TITLE
Installation error: "dendron.welcome.md" missing

### ISSUE THREAD

**Issue by LucasD3** [dendronhq/dendron#361]
**Describe the bug**
It appears that with version 0.16, the welcome note has been changed. I did a fresh installation on Mac, and got the following error message:

{"errno":-2,"syscall":"open","code":"ENOENT","path":"/Users/lucas/.vscode/extensions/dendron.dendron-0.16.0/assets/dendronWS/vault/dendron.welcome.md"}

The problem is that "dendron.welcome.md" does not exist. So, it appears that, with version 0.16, "dendron.md" should be opened, rather than "dendron.welcome.md".

**To Reproduce**
1. Do a fresh installation of the dendron VS Code extension on a clean MacOS
2. Error will appear 

**Expected behavior**
The welcome text should open

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Version 0.16

**Comment by kevins8** [comment]
Thanks for the update. Just pushed 0.16.1 to address this!
