### ISSUE TITLE
Removing default theme from "Initialize Workspace"

### ISSUE THREAD

**Issue by Larandar** [dendronhq/dendron#362]
**Is your feature request related to a problem? Please describe.**
As a regular VS-Code user (most of my workday) I find the "Initialize Workspace" command changing the theme currently configured to "Github Light" is hard on the eyes essentially at night.

I feel like a theme is mater of taste and should not be changed by an extension unless it's explicitly a theme.

**Describe the solution you'd like**
- Not having `workbench.colorTheme` in the generated "dendron.code-workspace"

**Describe alternatives you've considered**
- Having a prompt when initializing asking you what theme to choose (a suggested light and dark theme pair, and no change), but as I said a theme is a question of taste and therefore what would be pleasing for one may not be for others
- Having a "welcome to your workspace" screen that invites you to set a theme and other customizations on the first open (same objection)
- Only set a theme if the current global theme is the default one for users that never customized their installations, but maybe one like the default theme.

 **Additional context**
IMO setting `workbench.colorTheme` in a workspace setting is weird, I want as much as possible to have global settings that I don't need to set in different workspaces. I am curious if people have a different theme per workspace? I'm almost of the philosophy that only setting *strickly necessary* for a given workspace should be placed here.

**Comment by DanielHZhang** [comment]
I agree that dendron should be agnostic with theming and respect the global theme that is already applied. I would go even further to say that the dendron extension bundle should not include the `Github Theme` extension, as it would be uninstalled anyway by those who prefer other themes.

**Comment by flammehawk** [comment]
Yes, this is such a huge thing. If dendron was standalone it can gladly come with its own themes but as it stands a theme should not be forced on me by Dendron.

**Comment by kevinslin** [comment]
That's fair. Will update the defaults to not include the color theme for the next release.

**Comment by kevinslin** [comment]
This has been completed in a past release
