### ISSUE TITLE
Task Status Not Visible in Note Refs

### ISSUE THREAD

**Issue by RenStrike** [dendronhq/dendron#3628]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [X] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Note Refs no longer show Tasks Status correctly in Preview.

## To Reproduce

1. Create a Task Note
2. Link to it in Note A
3. Reference Note A in Note B
4. Notice the Preview for Note B does not show a checkbox for the Task Link in the Note A Reference.

## Expected behavior

Task Note should show Status in Note References.

## Screenshots
How it looks currently:
![image](https://user-images.githubusercontent.com/16402677/193955509-3ea3ef3a-ce52-4fae-b12e-704c4e7ff205.png)

How it should look:
![image](https://user-images.githubusercontent.com/16402677/193955564-18b1cb94-e2c5-4f17-a1d1-f88f71ce5ae0.png)

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: v0.114.0
  - VS Code version: 1.71.2
  - Dendron CLI:

## Dendron Log file
[dendron.log](https://github.com/dendronhq/dendron/files/9711734/dendron.log)

**Comment by samuelxyz** [comment]
#3578

**Comment by hikchoi** [comment]
Thank you for the report @RenStrike,
and @samuelxyz for linking the issue.

@RenStrike looks like #3578 is a duplicate issue. Please let us know if there are additional concerns outside what #3578 is describing, and let us know here in the thread? (or alternatively, you could close this and comment in the existing issue so we can track the issue at one place)
