### ISSUE TITLE
[Bug] Minimap gets turned off by default at VSCode launch

### ISSUE THREAD

**Issue by iterating** [dendronhq/dendron#366]
**Describe the bug**
At every new launch of VSCode, the workspace setting to show the minimap keeps being reset to "off".

**To Reproduce**
1. Turn on minimap
2. Close VSCode
3. Relaunch VSCode. After Dendron initializes, the minimap disappears

**Expected behavior**
Respecting the user setting to keep the minimap on

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest

**Additional context**
Minimap is useful for visually navigating *in* a note just as the graph view is useful for visually navigating all the notes.

**Comment by kevins8** [comment]
Hey John,

Thanks for the update. That settings comes as a default workspace settings
but you're right, it should respect the user presets. Will be updating it
for this weeks release!

**Comment by kevinslin** [comment]
this has been updated
