### ISSUE TITLE
Fuse threshold is not set in published Next.js export

### ISSUE THREAD

**Issue by vibl** [dendronhq/dendron#3668]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Fuse threshold is not set in published Next.js export.

As a consequence, the threshold is Fuse's default (0.6), which is very high and pollutes the search results.

This line:

https://github.com/dendronhq/dendron/blob/11364f8a10c580f8225162d6be0c79c3a647ab92/packages/nextjs-template/utils/fuse.ts#L42

Should be instead:
```js
        setFuse(createFuseNote(notes, { threshold: 0.1 }, value));
```

**Comment by jonathanyeung** [comment]
Thanks @vibl for finding this issue.  @namjul - can you take this one up?
