### ISSUE TITLE
Wikilink to Heading ID

### ISSUE THREAD

**Issue by prurph** [dendronhq/dendron#369]
Forgive me if this is already possible--it wasn't mentioned in the docs and I tried every syntax I could think of to no avail.

**Is your feature request related to a problem? Please describe.**
Often I want to link to a specific header in another note, but don't want to transclude the content with a ref because that would increase the length and scope of the note linking to it.

**Describe the solution you'd like**
Support a syntax like `[[Humble Wikilink Title|my.dendron.note]](#my-heading-id)` which links to:

```
// my.dendron.note.md

## Link Here {#my-heading-id}
```

This is consistent with the markdown [extended syntax for heading ids](https://www.markdownguide.org/extended-syntax#heading-ids).

To complement this, Dendron could ignore heading ids in its own ref syntax. This would dovetail elegantly with the Markdown export pod because wikilinks could be translated from `[[wikilink]]` to `[relative-link]` just like they are now, and the heading ids would just work.

**Comment by kevinslin** [comment]
@prurph this will be possible in this week's release. we'll be announcing relative links :)

the syntax is `[[Humble Wikilink Title|my.dendron.note#my-heading-id]]`

depending on how the wind turns, we might also adopt the extended syntax at some point. dendron will reformat links on export/publish so the differences shouldn't be too much of a concern but I like how wiki-links would just work with your proposal.

**Comment by prurph** [comment]
Thanks! I see this has made it in. One problem with the current syntax is it seems to be incompatible with the extended syntax for heading ids AFAICT. If you have a heading id the extra hashtag appears to prevent Dendron from parsing the relative portion of the link.

**Comment by kevinslin** [comment]
You're right. We'll be adding a fix to the preview to fix this.

Moving forward and when possible, Dendron will try to stay to `CommonMark`
spec for syntax. That being said, many of the features we have (eg. block
based note references) have no common mark equivalent and this is only
going to grow in the future.

We'll recommend folks use the markdown pod (
https://dendron.so/notes/13c4a608-0a32-4c62-9c7e-2b7f9f2d18bf.html) in
order to use either individual notes or all their notes to common mark in
the future.

**Comment by kevinslin** [comment]
the preview has just been fixed to render relative links in 0.21. at this point, this should be feature complete so i'm going to close out the issue. feel free to ping if something else comes up
