### ISSUE TITLE
[nit] calendar view hard to read in light mode

### ISSUE THREAD

**Issue by allibell** [dendronhq/dendron#3692]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

In VS Code, the calendar view has white text - at least in the year toggle, month toggle, and adjacent days to Today in the grid - that is unreadable in a light color theme.

## To Reproduce

1. In VS Code, set the `Workbench: Color Theme` to a light theme (e.g. "GitHub Light Default")
2. Return to the Dendron editor with Calendar view open
3. Observe unreadable text in year toggle, month toggle, and adjacent days to Today

## Expected behavior

All the text in Calendar view should be readable in light mode

## Screenshots
![image](https://user-images.githubusercontent.com/25647843/196743464-fef21c5b-a074-4134-af9f-58795d455d40.png)
![image](https://user-images.githubusercontent.com/25647843/196743501-e18474b4-9bb6-4241-acd1-a046b592643a.png)

## Desktop (please complete the following information)

- OS: MacOS Monterey
- Versions (all that apply to bug):
  - Dendron Extension: v0.115.1
  - VS Code version: 1.72

## Additional context

~N/A, just a little nit~
EDIT:  In my OS settings, I use "Auto" appearance (General > Appearance > Auto) and "Night Shift" (Displays > Night Shift).  In case you are having trouble repro-ing, you might try fiddling with those settings.

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/9822236/dendron.log)

**Comment by kevinslin** [comment]
we're actually updating our calendar themes at the moment (they haven't seen love in a while). @namjul is working on it this week so we'll be sure to address this!

**Comment by namjul** [comment]
This should get fixed with https://github.com/dendronhq/dendron/pull/3765
