### ISSUE TITLE
Titles not displayed correctly in published site

### ISSUE THREAD

**Issue by ccamara** [dendronhq/dendron#3694]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After updating next-js,  the theme has changed and titles have now a weird alignment/layout. 
Instead of being aligned to the left, there's a white space which is actually filled with an icon to get the heading's link (see screenshot: 

![Dendron](https://user-images.githubusercontent.com/706549/196933540-c657ab87-9ff0-4a6c-a3a7-bfa01242b4cb.png)

## To Reproduce

1. Update nextjs template following official documentation: https://wiki.dendron.so/notes/cToymvsc33870ctRFeBA8/
2. Deploying a site

## Expected behavior

Titles should be aligned to the left

## Screenshots

See above.

## Desktop (please complete the following information)

- OS: MacOS
- Browser (if with published websites; include version): Firefox 105.0.3 , Chrome  106.0.5249.119
- Versions (all that apply to bug):
  - Dendron Extension: 0.115.1
  - VS Code version: 1.72.2
  - Dendron CLI: 0.112.0

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by Harshita-mindfire** [comment]
Thanks @ccamara for reporting the bug.  We are looking into this.
Recently, we updated the link icon to appear on the right side (see [here](https://wiki.dendron.so/)). Looks like there is an issue with the template. Adding @namjul for visibility.

**Comment by namjul** [comment]
@ccamara do you use custom styles in your published site? 

Maybe can you provide a screenshot of the part of the broken area from the html pov. You can do that if you right-click on the wrongly aligned text and select "inspect" it opens up the dev-tools and it selects the underlining html structure of that part. You  than again right-click into that and select "expand recursively" and than take a screen-shot from that.

**Comment by ccamara** [comment]
@namjul , I'm afraid I do not use any custom style yet (probably not until #3695 gets integrated).

This is the html code:

```html
<h1 id="dendron"><a aria-hidden="true" class="anchor-heading icon-link" href="#dendron"></a>Dendron</h1>
<p>This knowledge base is generated using Dendron. This guide explains what dendron is, what makes it so special (why are we using it) and how to use it.</p>
<h2 id="what-is-dendron"><a aria-hidden="true" class="anchor-heading icon-link" href="#what-is-dendron"></a>What is dendron?</h2>
<p>Dentron is an Free/Libre OpenSource Knowledge Management System (KMS) (or also called "Second Brain") built as a VSE Code/VS Codium addon. In some ways it is similar to other, more popular, KMS such as Obsidian, Evernote..., but with unique features (see below).</p>
<p>From <a href="https://www.dendron.so/about">Dendron's website</a>:</p>
<blockquote>
<p>What makes Dendron powerful is its ability to let users organize their information in a way that's most useful to them. Dendron takes many of the affordances developers are used to in code, like abstractions (<a href="https://wiki.dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c.html">note references</a>), <a href="https://wiki.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#refactor-hierarchy">refactoring</a>, and <a href="https://wiki.dendron.so/notes/a7c3a810-28c8-4b47-96a6-8156b1524af3.html">symbol lookup</a> and applying it to general knowledge.</p>
<p><strong>Our mission is to help humans manage any amount of information and we are doing so by making managing information more like managing code.</strong>  </p>
</blockquote>
<p>In order to store and retrieve information, Dendron is based in the following principles (see <a href="https://wiki.dendron.so/notes/7fcebd7d-6411-4c9d-8baf-65629dc018a1/">official documentation</a>)</p>
<h2 id="why-is-it-useful"><a aria-hidden="true" class="anchor-heading icon-link" href="#why-is-it-useful"></a>Why is it useful?</h2>
...
```

**Comment by Harshita-mindfire** [comment]
@ccamara Can you try updating the dendron-cli version to the latest `115.1` in your package.json present at the root of your workspace and see if the issue persists?

**Comment by namjul** [comment]
@ccamara thank you for providing the html code. It show that it still renderes the old html structure. Currently its not clear why that is happening. @Harshita-mindfire so maybe its just that the used cli was still the old but already used new code from the other Dendron packages.

**Comment by SR--** [comment]
For me, updating CLI does not fix the issue. The site is published using GitHub Actions.

**Comment by SR--** [comment]
Fixed it by setting CLI version to "*" in package.json
________________________________
