### ISSUE TITLE
Wildcard in Reference matches same file itself

### ISSUE THREAD

**Issue by triplem** [dendronhq/dendron#3732]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I would like to create a monthly review to the journal. To do this, I have added the following reference to my template:

```
![[daily.journal.2022.07.*]]
```
Unfortunately this seems to also include the file itself (which is named daily.journal.2022.07.review. 

I guess, that inclusion of the file itself in a wildcard reference does not make any sense to me.

## To Reproduce

Use a wildcard reference which references the file itself as well.

## Expected behavior

A wildcard reference should not reference itself.

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by hikchoi** [comment]
Thank you for the report.
While I don't think it is a bug (`*` reference is doing what it is expected to do), I understand the need to do a pattern matching that is more specific than a simple wildcard in your use case.

My interim suggestion is to put your reviews in a separate hierarchy, or use the note `daily.journal.2022.07` itself as a review note, but I understand that that is not what you are going for and we need to support these use cases.

Could you create a separate feature request to support a more fine-grained pattern in the references? (or just convert this issue to a feature request?)

**Comment by triplem** [comment]
please see: #3743.
