### ISSUE TITLE
Running "dendron publish dev" results in infinite loading site

### ISSUE THREAD

**Issue by HenryNguyen5** [dendronhq/dendron#3746]
- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Running "dendron publish dev" results in infinite loading site. `dendron publish export` works fine.

## To Reproduce

1. Use dendron tutorial workspace
2. Run `npx @dendronhq/dendron-cli publish dev`
3. Try to navigate to `localhost:3000`
4. Site loads forever

## Expected behavior

The dev version of the site should load fine.

## Desktop (please complete the following information)

- OS: Linux dev 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:04:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
- Browser: chrome, but curl also will fail
- Versions (all that apply to bug):
  - Dendron CLI: 0.116.1, 0.115.1

**Comment by brentjanderson** [comment]
I'm seeing the same thing on Mac. 👍

**Comment by brentjanderson** [comment]
Just ran `git bisect` against [the NextJS template](https://github.com/dendronhq/nextjs-template) and it looks like something was introduced in commit [7236786](https://github.com/dendronhq/nextjs-template/commit/7236786298afb84363fb42a1f9effbf667d2bbf0) that started causing this issue. Rolling back to an earlier version of the NextJS template fixed it for me:

```
cd .next
git checkout -- .
git checkout 0333e1a70f7ebf9076163878cc33bde31ae9aa7a
npm i
cd ..
```

I think it would be more accurate to say this is a bug on the NextJS template itself, not in Dendron per se.

**Comment by jonathanyeung** [comment]
Thanks for reporting the issue - I'll investigate.

**Comment by kevinslin** [comment]
There was an issue with the version of nextjs we were using (12.3.0). we made a [fix](https://github.com/dendronhq/dendron/pull/3756) to update to the latest. You can get the latest version by following the [upgrade process](https://wiki.dendron.so/notes/cToymvsc33870ctRFeBA8)

Please let us know if you continue seeing issues (this issue will auto-close in 3 days). If this fixed the issue, simply react with a 🎉 emoji (otherwise this thread will re-open)

**Comment by jonathanyeung** [comment]
The latest version of NextJS template should have a fix for this issue.
