### ISSUE TITLE
Math is not suported well for publishing

### ISSUE THREAD

**Issue by zhanghanduo** [dendronhq/dendron#380]
## Describe the bug
When publishing my notes on Dendron-Jekyll with mathjax enabled, I found the math equations are not rendered well:
1. Does not support inline math
2. Cannot recognize most Latex operations and accents like "\mathbf", "\times", "\in" etc.

### Local preview
   
![](https://cdn.discordapp.com/attachments/735365126227493004/781366735931572234/unknown.png)

  ### Published view
   
 ![](https://cdn.discordapp.com/attachments/735365126227493004/781366769377476678/unknown.png)

## Desktop:
 - OS: Ubuntu 18.04 and Windows 10
 - Browser chrome and edge
 - Version Dendron 0.17

**Comment by kevinslin** [comment]
Thanks for the update. So inline math is not supported on publishing at this moment. As for the latex syntax, can you also share the raw markdown that you used to render this?

**Comment by zhanghanduo** [comment]
When I am copying the raw markdown code I found an interesting fact:
The raw markdown code fragment in the vault is:
`$$
\mathbf{d}_{ij} = F_{ij}, \mathbf{d}\in{\mathbb{R}^n}
$$`
However, after I run the "build pod" command, the generated pod in docs becomes:
` $$
  \\mathbf{d}_{ij} = F_{ij}, \\mathbf{d}\\in{\\mathbb{R}^n}
  $$
`
That's the reason the equations were not rendered correctly. After I manually correct them, they can be rendered well.

**Comment by kpathakota** [comment]
This looks like a small issue with the build pod script - correct if necessary @kevinslin

**Comment by kevinslin** [comment]
This is now been fixed with the new build site command.
