### ISSUE TITLE
Markdown Highlight Syntax not working in published Github page

### ISSUE THREAD

**Issue by imalightbulb** [dendronhq/dendron#381]
**Is your feature request related to a problem? Please describe.**
Markdown highlighting syntax works in preview but not when published, ex: `==highlighted text==`

**Describe the solution you'd like**
show the same highlighting in published github pages, like in the markdown preview

Dendron Markdown Preview:
![image](https://user-images.githubusercontent.com/66677431/100311363-90048480-2fea-11eb-8b3c-c3d630142754.png)

Published Github Page:
![image](https://user-images.githubusercontent.com/66677431/100311385-9bf04680-2fea-11eb-828d-008bfcfea802.png)

**Describe alternatives you've considered**

-

**Additional context**
Thanks!

**Comment by kevinslin** [comment]
Thanks for the request. The jekyll template we're using doesn't support the highlighting syntax.

**Comment by aleksey-rowan** [comment]
Hey, @imalightbulb, I'm going to close this one as a duplicate of 

- #1393 

I realize that this is an older issue, but the duplicate has more information. Please, upvote or leave a comment on the linked issue.
