### ISSUE TITLE
Daily note shortcut only works with .md file open

### ISSUE THREAD

**Issue by ms3056** [dendronhq/dendron#382]
**Describe the bug**
With no files open in VSCODE the create daily note shortcut does not create and open a new daily note. 

**To Reproduce**
1. Open VSCODE
2. Wait for Dendron plugin to load
3. Close all open files
4. Click Control+Shift+I
5. Nothing happens

**Expected behavior**
I would like a new daily note to be created when no files are open and I click control shift I

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 
[dendron.log](https://github.com/dendronhq/dendron/files/5605359/dendron.log)

 - Browser: Edge
 - Version: Dendron version 0.17.1, Windows Version 10, Edge version 87

**Additional context**

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by flammehawk** [comment]
Probably related to #374

**Comment by kpathakota** [comment]
Yeah, just repro'd this. I can't even see logs generated when I try the daily note shortcut without an open file. 
i.e. when a file is open I see this line: 
`{"level":30,"time":1619359059775,"pid":24112,"hostname":"CHeXPS","name":"dendron","ctx":"CreateDailyJournal","journalName":"journal","fname":"daily.journal.2021.04.25"}`

But when a file is not open, this never occurs in the logs.

**Comment by kpathakota** [comment]
Actually, figured this out - it's due to the `when` clause of the shortcut. We default to `editorFocused` but if you remove that clause, cmd+shift+i/ctrl+shift+i will work as you like: 

![image](https://user-images.githubusercontent.com/1484475/115996426-dba07600-a5fc-11eb-809b-743746c35eb1.png)

**Comment by flammehawk** [comment]
This should be changed in the defaults then, I would guess.

**Comment by kevins8** [comment]
Nice catch. This will be included in Monday's release!
