### ISSUE TITLE
Spelling Error in Refactor Hierarchy Dialog

### ISSUE THREAD

**Issue by ms3056** [dendronhq/dendron#383]
**Describe the bug**
In Refactor Hierarchy I attempted to refactor a note that would have resulted in a duplicate file name. The result told me as such, but the word "would" was spelled "woudle" - image attached. 

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
![spelling](https://user-images.githubusercontent.com/23712700/100420148-42ab1480-30c9-11eb-9f15-0f8e865023c5.png)

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
thanks for the heads up. will fix it in this weekends release :)

**Comment by kevinslin** [comment]
this has been fixed
