### ISSUE TITLE
Rename command isn't working (possibly multi-vault)

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#385]
**Describe the bug**
Rename command not working with multi-vault

**To Reproduce**
1. Try to rename a note. 

**Expected behavior**
Note should be renamed. 

**Screenshots**
Get an error about the notes.foreach not being available. 

**Desktop (please complete the following information):**
 - MacOS

**Additional context**

**Dendron Log file**
[renamebug.log](https://github.com/dendronhq/dendron/files/5606563/renamebug.log)

**Comment by kpathakota** [comment]
Possibly the same as https://github.com/dendronhq/dendron/issues/338

**Comment by iterating** [comment]
I'm reproducing this bug in Windows 10.
[dendron.log](https://github.com/dendronhq/dendron/files/5614743/dendron.log)

**Comment by kevins8** [comment]
Yep, this isn't as much as a bug as a feature that's not yet supported for
multivault. This will be addressed in today's 0.18 release

**Comment by kevinslin** [comment]
This has been resolved with the later releases
