### ISSUE TITLE
Extension host consumes high cpu while idle

### ISSUE THREAD

**Issue by 10kc-emilyk** [dendronhq/dendron#3863]
Type: <b>Bug</b>

The extension host consumes ~80% cpu on one core consistently while idle. After indexing, this should drop down, rather than continuously churn.

Extension version: 0.119.0
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 8, 10|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id c6f93df7-c0f6-4605-a496-9451bffeb076|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by hikchoi** [comment]
Hi @10kc-emilyk, could you please edit the issue using the given templates (https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title=)?

The stats you provided are for bug reporting on vscode, and not their extensions. It's hard for us to use this information to pinpoint what is going on.

Dendron offloads most of the heavy lifting to a locally running server in your machine, so indexing isn't happening in the extension host. 
I suspect something else is going on.

Could you provide the extension logs? (from `Dendron:dev: Diagnostic reports` and `Dendron:dev: Open Log`)

**Comment by 10kc-emilyk** [comment]
Yeah, i ended up cleaning up my dendron workspace and the issue resolved itself. I dont know the original cause.
