### ISSUE TITLE
Integrate with Quarto

### ISSUE THREAD

**Issue by gwenwindflower** [dendronhq/dendron#3872]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [x] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##
There are a couple big recurring feature requests I've seen in Dendron the past couple months:
- queries
- interactive code snippet blocks

I think integration with [Quarto](https://quarto.org/) would solve both of these and open up a horizon of other features really robustly, without taxing the Dendron team beyond the integration piece.

## Describe the solution you'd like ##
If Dendron could create and lookup .qmd Quarto files, and incorporate Quarto's render step in its Preview, you would be able to write interactive code right in Dendron. You could also introspectively query your notes in those blocks! Full literate programming within the brilliant Dendron hierarchal-graph hybrid system. 

There would additionally probably need to be a pod to export to Quarto so the interactive pieces could function on publish as well.

## Describe alternatives you've considered ##

Dendron could build these interactive code features and a query system themselves, but this would be arduous. Not only that, but the more proprietary the solution, the harder it will be to adopt for users. Opting to integrate with a tool that's already solving these problems seems like a win-win.

## Additional context ##
Here's an example of a Quarto .qmd file in my home vault to help demo what the `Run cell` functionality would like.
![Screenshot 2022-12-25 at 14 32 11](https://user-images.githubusercontent.com/91998347/209481334-90a0b645-1c00-43ae-855d-2881daf8af77.png)

**Comment by brentjanderson** [comment]
I think this is a marvelous idea - I'd not seen Quarto before, but it seems like a powerful way to extend Dendron's capabilities without having to duplicate a lot of work.

**Comment by guillaumegilles** [comment]
### I agree!
[Quarto](https://quarto.org/docs/get-started/hello/vscode.html) is built on top of R markdown and is an awesome update. It would turn our notes into beautiful chunks of notebooks.
