### ISSUE TITLE
Notes Graph doesn't show up

### ISSUE THREAD

**Issue by denisdifazio** [dendronhq/dendron#391]
**Describe the bug**
When trying to open the notes' graphical view using the command "Dendron: Show Note Graph" a message shows up saying "still connecting to engine. please try again in a few moments..." and nothing happens.

**To Reproduce**
1. Open a Dendron's workspace
2. Execute the command "Dendron: Show Note Graph"

**Expected behavior**
Graph to be opened after "Dendron: Show Note Graph" command execution

**Screenshots**
![image](https://user-images.githubusercontent.com/11673757/101197614-1ea78000-3641-11eb-9b5c-f5694b0a6ba7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Dendron 0.18.0

**Comment by kevins8** [comment]
Dendron starts a local server that the graph extension tries to connect to.
If you open up the graph immediately on initialization, you will see that
message. You'll need to close the graph window and open it again to get the
window to disappear. It's not the most intuitive design and we're working
on making it better😅

**Comment by denisdifazio** [comment]
> You'll need to close the graph window and open it again to get the
> window to disappear.

Indeed, thanks Kevin
