### ISSUE TITLE
Display Backlinks on Note Page

### ISSUE THREAD

**Issue by theianjones** [dendronhq/dendron#393]
**Is your feature request related to a problem? Please describe.**
For the dendron Jekyll theme, it would be nice to have the option of displaying the backlinks on the page as we do in Dendron itself. Being able to configure this to the users liking would be excellent.

**Describe the solution you'd like**
When a note links to the current note that you are viewing, some contextual information on the current not displaying the backlinks is helpful when exploring your own or someone else's knowledge graph.

[Heres an example](https://zacjones.dev/egghead): 

![image](https://user-images.githubusercontent.com/4407263/101282929-c50c9600-37a5-11eb-90fe-f36c63e76de7.png)

**Describe alternatives you've considered**
There are a lot of backlinks in Dendron it self or Roam Research. Just simple links displaying the pages that link to it.

**Additional context**
Here's an example implementation in [@maximevailancourt's digital garden jekyll template](https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/master/_plugins/bidirectional_links_generator.rb)

**Comment by kpathakota** [comment]
This has shipped and is available if you publish recently.
