### ISSUE TITLE
Need capability to move an entire hierarchy from one vault to another

### ISSUE THREAD

**Issue by joehays** [dendronhq/dendron#3960]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I'm always frustrated when I have an entire hierarchy of files to move from one vault to the next and I have to do them one at a time.

## Describe the solution you'd like ##

I'd like the `Move Note` command to optionally recursively move all children files to another vault. 

## Describe alternatives you've considered ##

Or, update `Refactor` to work between vaults.

**Comment by aleksey-rowan** [comment]
I believe this is a duplicated of an older issue: https://github.com/dendronhq/dendron/issues/3513

Could you please check and if it is a duplicate, close this one and possible add your comment to the already existing one?

**Comment by joehays** [comment]
@djradon,
Wouldn't you lose the benefit of links getting remapped appropriately if I went around Dendron and used the OS to move the files?

**Comment by joehays** [comment]
@aleksey-rowan
Indeed it is a duplicate of #3513. Closing this one out. Good catch!
