### ISSUE TITLE
Choose vault for new note in a multi-vault environment

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#398]
**Is your feature request related to a problem? Please describe.**
Currently a new note is created in the same vault as the currently open note. Thus I need to pay attention the current vault when adding notes.

**Describe the solution you'd like**
I'd like to be asked for the vault to use for a new note from the currently defined vaults. The current vault should be the default. In addition I'd like to have a config option to turn this behavior off.

**Describe alternatives you've considered**
Be more mindful of the currently active vault :)

**Comment by kevinslin** [comment]
shipped in 0.20
