### ISSUE TITLE
confusion about license

### ISSUE THREAD

**Issue by LifeCANvs** [dendronhq/dendron#3983]
At the bottom of the Dendron readme, it states "Dendron is distributed under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3.
See LICENSE and NOTICE for more information."
However, that linked license.md contains " Apache License Version 2.0", which is also the license linked for Dendron on the VisualStudio Marketplace at https://marketplace.visualstudio.com/items?itemName=dendron.dendron

So it would probably be a good idea for someone to clear up this ambiguity...

**Comment by wookiefriseur** [comment]
Looks like this was taken care of in #3975

**Comment by LifeCANvs** [comment]
> Looks like this was taken care of in #3975

Thanks, so it is Apache 2.0 licensed now, and I see the readme has also been updated to confirm this 😄
