### ISSUE TITLE
How to use dendron with current workspace

### ISSUE THREAD

**Issue by curtbushko** [dendronhq/dendron#40]
Hello!

I use a single workspace in vscode for all of my projects.  How would I get dendron to work with that?  Would have to add the dedron settings to settings.json?  If so, what would it be?

Thanks!

**Comment by kevinslin** [comment]
You can follow the instructions [here](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.cook.md). Note that it currently requires that you rename your `*.code-workspace` file to `dendron.code-workspace`. If renaming the file is a blocker, we have an issue to make it configurable [here](https://github.com/dendronhq/dendron/issues/41)

**Comment by kevinslin** [comment]
fixed in 790ef503225e5b18a78e3e62e847ba8b2adfd8d0

**Comment by kravtsovd** [comment]
@kevinslin  He Kevin, it looks like this link "You can follow the instructions [here.](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.cook.md)" doesn't work only more. 
Do you have current instructions on how to use the current workspace?
