### ISSUE TITLE
Matching requires unique files for lower nodes

### ISSUE THREAD

**Issue by ms3056** [dendronhq/dendron#407]
**Describe the bug**
Consider the following shcema:

work.notes.2020.12.15.meeting w/Bob
work.training.2020.12.15.leadership
work.team.kevin.2020.12.15.quarterly review

In order to have the tree recognize every node and sub-node I had to have unique DATE.YML files for each sub-node. I would LIKE to have ONE date.yml file and use it as a child for ANY sub-node. 

The workaround is described in the attached image. 

![image](https://user-images.githubusercontent.com/23712700/102291240-10812a00-3f86-11eb-9d64-089dcd830d33.png)
![image](https://user-images.githubusercontent.com/23712700/102291277-2131a000-3f86-11eb-91b1-9b4de577eacf.png)

Each date_n.yml is the same and looks like this:
![image](https://user-images.githubusercontent.com/23712700/102291321-39a1ba80-3f86-11eb-92b5-189fd30daa76.png)

The resulting tree is full of matches:
![image](https://user-images.githubusercontent.com/23712700/102291395-5ccc6a00-3f86-11eb-9b58-29085f1d171e.png)

**Comment by kevinslin** [comment]
we now support the [pattern](https://wiki.dendron.so/notes/c5e5adde-5459-409b-b34d-a0d75cbb1052.html#pattern) property which allows you to match multiple notes with a globbing pattern
