### ISSUE TITLE
Markdown Tables and Wikilinks

### ISSUE THREAD

**Issue by Stedag** [dendronhq/dendron#408]
When writing tables, there is a collision of wiki link and markdown syntax. This prevents autocomplete dialog and linting. Wikilinks do not resolve within the table and adding a pipe in the wikilink will be read as a cell delimiter. There is another issue #269  open regarding tables in markdown preview, but this issue has to do with auto completion in dendron in addition to rendering complications.

### To reproduce
Open a markdown file in dendron and confirm that autocomplete is functional
Write a table such as:
```
|simple table column 1| column 2|
|--|--|
|[[example link... does not experience autocompletion| and display text get's shifted to next cell]]| next cell gets dropped|
```
output

simple table column 1 | column 2
-- | --
[[example display link text...| and wikilink text get's shifted to next cell]]

This is not urgent. There are other ways to present this data. It would be nice to use tables in the future though.

**Comment by Stedag** [comment]
# Update
Autocomplete suddenly works again regardless of context within the document
Still, parsing of wikilinks is still not allowing alternate link text. If someone wants to publish a table with links within a dendron vault, they may want to use the url with uuid. It would save time for people with similar objectives to find a fix for wikilinks. For now I would call this an **enhancement** issue rather than a bug issue.

**Comment by aleksey-rowan** [comment]
There is a duplicate issue referring to the same problem: https://github.com/dendronhq/dendron/issues/110 

I'm going to close this one (even though it's older), as the linked issue has more information.
