### ISSUE TITLE
Markdown preview doesn't render

### ISSUE THREAD

**Issue by tmsss** [dendronhq/dendron#409]
First of all, congratulations on this extension! I'm having a problem with the command "Dendron: Show preview". It behaves erratically and most of the time I get a "still connecting to the engine" message from the Dendron Markdown Preview extension and the preview doesn't render at all. I'm on Ubuntu 18.04.

Thanks!

**Comment by kevinslin** [comment]
Thanks for the issue. The next time you get the issue, can you also attach the logs from the app to the issue? See here for instructions: https://dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#logs-from-previous-session

**Comment by tmsss** [comment]
Hi @kevinslin thanks for your time to answer. I finally understood what was going on, I had the directory wrong on dendron.yml fsPath. It is working now.
