### ISSUE TITLE
Make Dendron not install "GitHub Theme" extension on every update

### ISSUE THREAD

**Issue by denisdifazio** [dendronhq/dendron#411]
**Is your feature request related to a problem? Please describe.**
Whenever there is a new version of Dendron available on VSCode, it automatically installs the extension GitHub Theme. Since I don't use it, I have to manually uninstall it every time.

**Describe the solution you'd like**
I don't know if it is possible, but create a setting where the user can opt-out from GitHub Extension installation.

**Describe alternatives you've considered**
Fully remove GitHub Theme extension from Dendron's Extension Pack.

**Comment by flammehawk** [comment]
This is probably a leftover from #362 where the workspace was initialized with the github light theme.

**Comment by kevinslin** [comment]
Thanks for the request. There's no reason for this extension to be bundled anymore and we'll remove it with the next release

**Comment by kevinslin** [comment]
This has been fixed in 0.21
