### ISSUE TITLE
Add snippet capability to templates

### ISSUE THREAD

**Issue by ms3056** [dendronhq/dendron#413]
**Is your feature request related to a problem? Please describe.**
I'd like to have snippet capability in templates. 

In the template file I would like to add snippets such as date:
`Date: {{$CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE $CURRENT_HOUR:$CURRENT_MINUTE}}`

**Comment by aleksey-rowan** [comment]
@ms3056, This should be possible now with [Template Variable Replacement](https://wiki.dendron.so/notes/GelEQPZrSgr3CK9y10Nrg/#template-variables).

I know this is a very old issue, but if you are still using Dendron, does the above help with your request?
