### ISSUE TITLE
Ref link is not updated after renaming the referred note

### ISSUE THREAD

**Issue by wuchichou** [dendronhq/dendron#414]
**Describe the bug**
When I rename a note with `Dendron: rename note` command, the note is changed to the new name, but the ref link is not updated to the new name.

**To Reproduce**
1. Two new files, one is "test.md", the other is "test.note1.md".
2. In "test.md" file, refer "test.01.md" file with reference link `((ref: [[test.note1]]))`
3. Change "test.note1.md" filename to "test.note2.md"
4. The ref link is still  `((ref: [[test.note1]]))` in "test.md"

**Expected behavior**
What I want is when I make changes in step 3, the ref link in "test.md" file is updated to `((ref: [[test.note2]]))`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Both Windows 10 and MacOS
 - Browser: Microsoft edge 
 - Version 87.0.664.66

**Additional context**

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kpathakota** [comment]
Can no longer repro this, @wuchichou - feel free to reopen with fresh logs if you're still seeing this.
