### ISSUE TITLE
Use new markdown parser when publishing Markdown

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#417]
## Context

We made an update to how Dendron parses markdown but they are a bunch of places where we still use the old md parsing toolchain 

## Proposal
- replace the parser used for markdown publishing [here](https://github.com/dendronhq/dendron/blob/master/packages/pods-core/src/builtin/MarkdownPod.ts#L240:L240)
- [new parser](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/markdown/utils.ts#L89:L89 )
- example usage [here](https://github.com/dendronhq/mume/blob/master/src/markdown-engine.ts#L2949:L2949)
- add test cases [here](https://github.com/dendronhq/dendron/blob/master/packages/pods-core/src/builtin/__tests__/MarkdownPod.spec.ts#L10:L10)

**Comment by hikchoi** [comment]
Looks like you already swapped out the parser here while doing the pairing session :smile: : https://github.com/dendronhq/dendron/commit/c73f6647adb8c5e3b21aab049989d44745448a39#diff-061146d73ca415bb58ed56495fe5d04ee9fb665cd8f86930e6f893139d6de3db

Should I go ahead and add additional tests with the rest of the `ENGINE_HOOKS` or do you think the basic one there should be sufficient?

**Comment by kevinslin** [comment]
heh, you're right. I would say add a few more tests and we can call it
good 😅
Meanwhile, you can check the github issues for other good first tasks when
you feel up for the next one:
https://github.com/dendronhq/dendron/labels/size.small
