### ISSUE TITLE
Create Note via CLI

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#418]
## Context

Should be able to use cli to add notes

```
dendron-cli create-note --wsRoot {root} --vault {vault} {name} {content} 

dendron-cli note create --wsRoot . --vault vault1 hello "hello world"
dendron-cli note delete --wsRoot . --vault vault1 hello "hello world"
dendron-cli note delete --wsRoot . --vault vault1 hello "hello world"
```

**Comment by ognjenio** [comment]
Hi, 

I've a script that I use for quick adding notes. I can run the following from the terminal:

`d -u https://www.yankodesign.com/2021/03/30/this-sustainable-home-made-from-air-concrete-is-fireproof-waterproof-diy-friendly/ -t 'New title' -a 'tag1, tag2' -c 'Content' -p 'resources.articles'`

`-u` is URL
`-t` is title
`-a` are tags comma separate
`-c` is content
`-p` is path

If URL is present then the rest are not compulsory. If it isn't then title is compulsory. 

If the URL is present and the title isn't then the title will be the slug of the link, that is the part between the last two /

If the URL is present a `source: <url>` attribute will be added to the front matter.

If the title is present it will be converted to underscore.

Tags are comma separated and will be appended at the end of the file: `[[#tag1|tag.tag1]]`

Content will be pasted. 

The Dendron path is where the file will be stored. So in the example above it'll be `resources.articles.new-title.md`

And I have a default path set (`resources.articles`) so I can run just `d -u https://www.yankodesign.com/2021/03/30/this-sustainable-home-made-from-air-concrete-is-fireproof-waterproof-diy-friendly/` for instance.

Gist: https://gist.github.com/ognjenio/1935b4e3b81bd7412d4849e2ed875866
