### ISSUE TITLE
Backlinks and Ref includes

### ISSUE THREAD

**Issue by flammehawk** [dendronhq/dendron#419]
**Describe the bug**
Reference Includes are not listed in the Backlinks Pane. 

**To Reproduce**

-Create 2 Notes:
    - test
    - test2
- Put a Ref include of test2 into test
- Open test2 and open the backlink pane
- Currently it is empty

**Expected behavior**
The Ref include should be listed under Backlinks since it is a form of a link.

**Screenshots**
![image](https://user-images.githubusercontent.com/57394581/102764114-e90dd100-437a-11eb-8882-8531481a28f8.png)

**Desktop (please complete the following information):**
- VSCode version: 1.52.1
- Dendron version: 0.20.0

**Additional context**
Clean and fresh initialized vault

**Comment by kpathakota** [comment]
@flammehawk - I know this is a super old issue so sorry for the late response but I can no longer repro this. Closing. Please reopen if you think there's something else here.
