### ISSUE TITLE
Better markdown-preview Button UI

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#42]
## Context

Currently, there's two markdown preview button's that show up when focusing on a markdown file: one is the default built in by vscode, the other is from Dendron. Currently, there's no way to hide the button from vscode. We have an open issue to vs-code about this [here](https://github.com/microsoft/vscode/issues/102908)

## Research and Prior Work
- override `window.registerCustomEditorProvider`
  - vscode builtin markdown is created using a `CustomEditor`
  - blocked: can't register multiple custom providers with same type
- use `window.on*|workspace.on*` method to figure out when default markdown preview launches
  - blocked: custom editor doesn't show up in window.on* or workspace.on* methods
- use [vscode-custom-css](https://github.com/be5invis/vscode-custom-css) to override css
  - hacky and will cause vscode to complain that `vscode is corrupted`

## Proposal
- research additional means to resolve button ui issue

**Comment by caseydierking** [comment]
Hey @kevinslin are we waiting then for vscode to implement a solution that doesn't throw an error? Is there more work to be done on this? This is something I'd like to help move forward if possible

**Comment by aleksey-rowan** [comment]
This is done. There is special `Dendron: Show preview` toolbar button now.
