### ISSUE TITLE
Latex in Markdown Preview Broken

### ISSUE THREAD

**Issue by FrancoB411** [dendronhq/dendron#424]
**Describe the bug**
As of the latest VScode update, latex rendering in Markdown Preview Enhanced is broken

**To Reproduce**
1. `cat > test.md` then paste `# Probability $\cap$ Statistics` and type `control c` to create test file
2. Open the file in VsCode and Click the Markdown Preview Enhanced Icon
3. You should see the Actual pic below
4. Install Pandoc and parse that file `pandoc test.md -s --mathjax -o test.html && open test.html`
5. When browser opens you should see latex rendering properly like the expected pic below

**Expected behavior**
Latex should render properly, for example, the cap symbol in `test.md`, but it does not. 

**Screenshots**
Expected
![Screen Shot 2020-12-26 at 1 13 15 PM](https://user-images.githubusercontent.com/320623/103156954-2d82dd80-477c-11eb-8197-eb5d41f225c1.png)

Actual
![Screen Shot 2020-12-26 at 1 01 34 PM](https://user-images.githubusercontent.com/320623/103157027-0c6ebc80-477d-11eb-9049-26bfb23510fe.png)

**Desktop (please complete the following information):**
VsCode
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 wk ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Dendron Log file**
{"level":30,"time":1609005112929,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1609005112939,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron","logLevel":"info","extensionPath":"/Users/franco/.vscode/extensions/dendron.dendron-0.21.0","extensionUri":{"$mid":1,"fsPath":"/Users/franco/.vscode/extensions/dendron.dendron-0.21.0","path":"/Users/franco/.vscode/extensions/dendron.dendron-0.21.0","scheme":"file"},"storagePath":"/Users/franco/Library/Application Support/Code/User/workspaceStorage/7fbb629df4efaf03258241407eedda10/dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/dendron.code-workspace","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/dendron.code-workspace","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1609005112941,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1609005112943,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","usePrettyRefs":true}},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1609005113127,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","files.autoSave":"onFocusChange","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on"},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","github.github-vscode-theme"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1609005113136,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.21.0","migratedGlobalVersion":"0.21.0","previousGlobalVersion":"0.20.0","previousWsVersion":"0.21.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"equinusocio.vsc-material-theme","version":"33.1.2","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.13","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.17","active":false},{"id":"github.github-vscode-theme","version":"1.1.5","active":false}],"vaults":[{"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault"}]}
{"level":30,"time":1609005113137,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"startServeer","logLevel":"info"}
{"level":30,"time":1609005113190,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"_activate","msg":"post-start-server","port":58264}
{"level":30,"time":1609005113249,"pid":31460,"hostname":"francombp.local","ctx":"FileStorageV2","wsRoot":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes","vaultsv3":[{"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault"}]}
{"level":30,"time":1609005113249,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1609005114506,"pid":31460,"hostname":"francombp.local","ctx":"FileStorageV2","wsRoot":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes","vaultsv3":[{"fsPath":"vault"}]}
{"level":30,"time":1609005114967,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1609005114967,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1609005114967,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1609005114968,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1609005114968,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1609005114968,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1609005114969,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1609005114970,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"activateWorkspace","stage":"dev","msg":"enter"}
{"level":30,"time":1609005114974,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1609005114975,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"_activate","msg":"fin startClient"}
{"level":30,"time":1609005114975,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.21.0","previousVersion":"0.21.0"}
{"level":30,"time":1609005114975,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1609005115871,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1609005202827,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609005300881,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"h:run","msg":"pre-execute"}
{"level":30,"time":1609005300883,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"DoctorCommand:execute","msg":"pre:Reload"}
{"level":30,"time":1609005300883,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1609005301168,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1609005301180,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1609005301330,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1609005301331,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"h:run","msg":"post-execute"}
{"level":30,"time":1609005301347,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1609005301590,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1609005302000,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/dendron.welcome.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/dendron.welcome.md","scheme":"file"}}
{"level":30,"time":1609005302056,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"dendron.welcome","msg":"exit"}
{"level":30,"time":1609005584774,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609006625515,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1609006625516,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1609006625545,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1609006625813,"pid":31460,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","external":"file:///Users/franco/Library/Application%20Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","path":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","scheme":"file"}}

**Comment by kevinslin** [comment]
Thanks for the update! This was just fixed in an update today. If you reload markdown preview, you should get the new one (v0.10.15  of dendron-markdown-preview-enhanced)

**Comment by FrancoB411** [comment]
Updated to v0.10.15 and Latex is rendering now. Nice! 
Should I close this or do you usually do it?

**Comment by kevinslin** [comment]
I usually do it after the weekly release (one coming out today). If you get
to it before me, then all good too :)
