### ISSUE TITLE
Add remote vault via https fails without error (likely due to SSH not setup)

### ISSUE THREAD

**Issue by jamesbeldock** [dendronhq/dendron#427]
**Fatal Error when adding Remote Vault (custom location) when git repo is password-protected (private)**
It does not appear possible to add repositories which require user authentication from Git before accessing using `https://`. A long error is produced (see below) 

**To Reproduce**
1. Add Vault > Custom
2. Enter URL to a private (password-protected) repo
3. Get error below

**Expected Behavior**
Either:
A. Give useful error that private repos are not supported _or_
B. (Ideally) Support authentication and access to private repos

**Error Returned**

`{"ctx":"v:run","err":{"status":"unknown","msg":"","payload":"{\"msg\":\"Cloning into 'homeservers'...\\nfatal: could not read Username for 'https://github.com': Device not configured\\n\",\"stack\":\"Error: Cloning into 'homeservers'...\\nfatal: could not read Username for 'https://github.com': Device not configured\\n\\n\\tat t.GitExecutorChain.onFatalException (/Users/j/.vscode/extensions/dendron.dendron-0.21.0/dist/extension.js:676:124765)\\n\\tat t.GitExecutorChain.<anonymous> (/Users/j/.vscode/extensions/dendron.dendron-0.21.0/dist/extension.js:676:124643)\\n\\tat Generator.throw (<anonymous>)\\n\\tat s (/Users/j/.vscode/extensions/dendron.dendron-0.21.0/dist/extension.js:676:123607)\\n\\tat runMicrotasks (<anonymous>)\\n\\tat processTicksAndRejections (internal/process/task_queues.js:94:5)\"}"}}`

**Desktop (please complete the following information):**
 - OS: OS X 11.1
 - VS Code Version: 1.52.1; Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523; Date: 2020-12-16T16:30:02.420Z

**Comment by kpathakota** [comment]
@jamesbeldock  - sorry for the late response. Did you ever get this working? You will need to follow the instructions for connecting to Github with SSH: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh before your terminal has access to the private github repos. 

We *should* improve this error messaging (will leave this ticket open for that).
