### ISSUE TITLE
Dendron Markdown Preview Rendering Ordered and Unordered lists nested in Data Definitions inconsistently

### ISSUE THREAD

**Issue by FrancoB411** [dendronhq/dendron#429]
**Describe the bug**
When rendering Ordered lists nested inside data definitions, Dendron Markdown Preview Enhanced does not line up the numbers properly. 

Rendering Unordered lists nested inside data definitions, Dendron Markdown Preview Enhanced renders a code block instead of an unordered list.

The desired behavior would be the behavior in the previous version of Dendron Markdown Preview Enhanced which rendered properly aligned nested ordered and unordered lists inside data definitions.

**To Reproduce**
1. Create at `test.md` file from the sample text in the additional context section below
2. Rendering with Dendron Markdown Preview Enhanced should resemble the screenshot `example render` below
3. The second and third lists are misaligned, and the unordered list is rendered as code block instead of `ul`.

**Expected behavior**
Ordered and unordered lists nested in data definitions should render as lists, and be properly aligned.

NOTE: Pandoc does not do this consistently, so in this case Dendron actually had better behavior before the upgrade introduced the regression.

**Screenshots**
Example Render:
![Screen Shot 2020-12-28 at 12 31 22 AM](https://user-images.githubusercontent.com/320623/103191916-c280f600-48a4-11eb-8d96-32d131a6a3e5.png)

**Desktop (please complete the following information):**
Dendron Markdown Preview Enhanced v0.10.15
VsCode
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 wk ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Additional context**
`test.md` sample text file:

```
Left Aligned Ordered List
1. Item 1 
2. Item 2 
3. Item 3 
   1. Sub Item 1

Nested in Data Definition Ordered List
  ~ 1. Item 1 
    2. Item 2 
    3. Item 3 
       1. Sub Item 1

Nested in Data Definition Unordered List
  ~ * Item 1 
    * Item 2 
    * Item 3 
      * Sub Item 1
```

**Dendron Log file**
{"level":30,"time":1609130201204,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1609130201220,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron","logLevel":"info","extensionPath":"/Users/franco/.vscode/extensions/dendron.dendron-0.21.0","extensionUri":{"$mid":1,"fsPath":"/Users/franco/.vscode/extensions/dendron.dendron-0.21.0","path":"/Users/franco/.vscode/extensions/dendron.dendron-0.21.0","scheme":"file"},"storagePath":"/Users/franco/Library/Application Support/Code/User/workspaceStorage/7fbb629df4efaf03258241407eedda10/dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/dendron.code-workspace","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/dendron.code-workspace","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1609130201224,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1609130201231,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","usePrettyRefs":true}},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1609130204333,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","files.autoSave":"onFocusChange","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on"},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","github.github-vscode-theme"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1609130204339,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.21.0","migratedGlobalVersion":"0.21.0","previousGlobalVersion":"0.20.0","previousWsVersion":"0.21.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"equinusocio.vsc-material-theme","version":"33.1.2","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.15","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.17","active":false},{"id":"github.github-vscode-theme","version":"1.1.5","active":false}],"vaults":[{"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault"}]}
{"level":30,"time":1609130204340,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"startServeer","logLevel":"info"}
{"level":30,"time":1609130204359,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"_activate","msg":"post-start-server","port":51532}
{"level":30,"time":1609130204361,"pid":80768,"hostname":"francombp.local","ctx":"FileStorageV2","wsRoot":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes","vaultsv3":[{"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault"}]}
{"level":30,"time":1609130204362,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1609130204394,"pid":80768,"hostname":"francombp.local","ctx":"FileStorageV2","wsRoot":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes","vaultsv3":[{"fsPath":"vault"}]}
{"level":30,"time":1609130205638,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1609130205638,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1609130205639,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1609130205640,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1609130205640,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1609130205641,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1609130205642,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1609130205644,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"activateWorkspace","stage":"dev","msg":"enter"}
{"level":30,"time":1609130205651,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1609130205651,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"_activate","msg":"fin startClient"}
{"level":30,"time":1609130205652,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.21.0","previousVersion":"0.21.0"}
{"level":30,"time":1609130205652,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1609130313570,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","reason":1,"msg":"enter"}
{"level":30,"time":1609130313572,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1609013795755"],"msg":"update activeText editor"}
{"level":30,"time":1609130314780,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609130314907,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"probability-statistics","msg":"exit"}
{"level":30,"time":1609130796976,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","reason":1,"msg":"enter"}
{"level":30,"time":1609130796980,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1609130313571"],"msg":"update activeText editor"}
{"level":30,"time":1609130798402,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609130798593,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"probability-statistics","msg":"exit"}
{"level":30,"time":1609131982675,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609131991130,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1609131991130,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1609131991163,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1609131991352,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","external":"file:///Users/franco/Library/Application%20Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","path":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","scheme":"file"}}
{"level":30,"time":1609132200834,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609132239595,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","reason":1,"msg":"enter"}
{"level":30,"time":1609132239597,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1609130796979"],"msg":"update activeText editor"}
{"level":30,"time":1609132241426,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609132241742,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"probability-statistics","msg":"exit"}
{"level":30,"time":1609132555127,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","reason":1,"msg":"enter"}
{"level":30,"time":1609132555129,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1609132239596"],"msg":"update activeText editor"}
{"level":30,"time":1609132556821,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609132557031,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"probability-statistics","msg":"exit"}
{"level":30,"time":1609132599726,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609132632860,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","reason":3,"msg":"enter"}
{"level":30,"time":1609132632862,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1609132555128"],"msg":"update activeText editor"}
{"level":30,"time":1609132634747,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609132634911,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"probability-statistics","msg":"exit"}
{"level":30,"time":1609133115571,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","reason":3,"msg":"enter"}
{"level":30,"time":1609133115585,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1609132632860"],"msg":"update activeText editor"}
{"level":30,"time":1609133117633,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609133117823,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"probability-statistics","msg":"exit"}
{"level":30,"time":1609133494970,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","reason":3,"msg":"enter"}
{"level":30,"time":1609133494979,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1609133115584"],"msg":"update activeText editor"}
{"level":30,"time":1609133498173,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609133498294,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"probability-statistics","msg":"exit"}
{"level":30,"time":1609133895533,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","external":"file:///Users/franco/Google%20Drive/CS%20Curriculum/Notes/Dendron%20Notes/vault/probability-statistics.md","path":"/Users/franco/Google Drive/CS Curriculum/Notes/Dendron Notes/vault/probability-statistics.md","scheme":"file"}}
{"level":30,"time":1609133902165,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1609133902165,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1609133902188,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1609133902355,"pid":80768,"hostname":"francombp.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","external":"file:///Users/franco/Library/Application%20Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","path":"/Users/franco/Library/Application Support/Code/logs/20201226T125147/exthost1/dendron.dendron/dendron.log","scheme":"file"}}

**Comment by kpathakota** [comment]
Same comment as #428. I think we should consider in #643 to support this case. @FrancoB411 - could you provide some more details on data definitions? A quick google isn't helping me find more about this ~ syntax.

**Comment by FrancoB411** [comment]
Sure! Take a look at the [Php markdown extra docs on data lists](https://michelf.ca/projects/php-markdown/extra/#def-list)

That behavior seems to be the least surprising because html already supports block level elements in lists.

**Comment by aleksey-rowan** [comment]
@FrancoB411, when you enable the [V2 preview](https://github.com/dendronhq/dendron/issues/428#issuecomment-1043694326), could you please check if the lists are still rendered inconsistently?
