### ISSUE TITLE
Ctrl + hover creates a note, it should only create one on Ctrl + Click

### ISSUE THREAD

**Issue by generic-user** [dendronhq/dendron#430]
**Describe the bug**
Ctrl + hover creates a note, it should only create one on Ctrl + Click

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a note, 
2. Paste an image in it
2. Hover it while ctrl is pressed
3. watch the note being created

**Expected behavior**
Just show the preview of the asset, do not create a note.

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser n/a
 - Version [0.21]

**Comment by tsnieman** [comment]
I believe the `Doctor` command also creates blank notes; whatever the decision is for this issue, I think `Doctor` 's behaviour should be consistent.

**Comment by kevinslin** [comment]
Thanks for the report. Images are great but fake image notes are not. We'll take care of it for the new years release!

@tsnieman as for Doctor, Doctor used to create blank notes but it shouldn't anymore. Let me know if that's not the case

**Comment by buxel** [comment]
I think this also broke my workflow with the draw.io extension. 

Previously i was able to create a link to an non-extisting .dio.png file and following the link, it would open the editor. 
Right now, when i CTRL+Click on that link, i get directed to a .dio.png.md file, obviously without the drawio editor loaded. 

Example link:  `![](/assets/images/diagram.dio.png)`
Ctrl+Click creates: `/assets/images/diagram.dio.png.md`

**Comment by generic-user** [comment]
Would it be possible to make a toggle to disable the feature until you have a final fix? This is getting really tedious to undo the changes on each commit. :cold_sweat:

![image](https://user-images.githubusercontent.com/1516035/105512058-ee8b6d80-5cd0-11eb-9146-add53baa2388.png)

😉 Thanks in advance

**Comment by kevinslin** [comment]
Yes! That much I can do!

**Comment by kevinslin** [comment]
So turns out the fix to not go to definition was pretty simple. This should be fixed now @generic-user

**Comment by generic-user** [comment]
Thanks, seems to work fine now! 👍

**Comment by kpathakota** [comment]
As discussed in discord, looks like this is only mitigated by the setting 
```dendron.yml
<!--configs-->
noAutoCreateOnDefinition: true
```

More details here: 
https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#noautocreateondefinition

**Comment by buxel** [comment]
@kpathakota the section you mentioned is currently partially missing.

I'm also not sure if this is supposed to work for my workflow.

Previously i was able to create a link to an non-extisting `.dio.png` file and following the link by CTRL+Click, it would create the file and open the editor (draw.io integration). 
Example link:  ![](/assets/images/diagram.dio.png)

I understood that dendron's behavior has changed and uses it's own "goto note" command now.
But even with that, i'm not able to create a new file when following a link to a non-existing file. I tried so far:
1. create link to new diagram, e.g. ![](/assets/images/diagram.dio.png)
2. use the Dendron: goto note command -> note does not exist error
3. try ctrl+click -> nothing happens
4. try F12 -> "no definition found" error

is there any way to make my workflow work again? it is cumbersome to manually create empty .dio.png files in the assets folder before linking to them.
