### ISSUE TITLE
Improve the import pod feature for import Hugo/Hexo etc.

### ISSUE THREAD

**Issue by wind13** [dendronhq/dendron#432]
**Is your feature request related to a problem? Please describe.**
I am trying to use import pod to move the Hugo markdown into Dendron, 90% works well.

But there is some problem of the metadata:

- tags missing
- date changed
- description empty
- title changed

**Describe the solution you'd like**

What I guess is the import pod script does not handle the metadata, just replace it.

What I'd like to be:

- keep tags
- keep description
- keep title, or change to Dendron title also okay, if it matters.
- change date to number but keep the origin time.

**Describe alternatives you've considered**

**Additional context**

**Comment by dixonge** [comment]
I found a similar issue importing .md files with a lot of YAML from previous use with Eleventy. I ended up dragging and dropping them into Dendron, then running Doctor. This will *add* and slightly modify some YAML, but it leaves the rest of it intact.

**Comment by kevins8** [comment]
Thanks for the issue & comments. Import pod has traditionally been used on
plaintext markdown. Will make these additions either this week or next

**Comment by aleksey-rowan** [comment]
@wind13, @dixonge, as of [0.80](https://wiki.dendron.so/notes/2pRvTG91s3JFlLFhJz3H4/?utm_source=dendron&utm_medium=email), import pod functionality [supports existing metadata](https://wiki.dendron.so/notes/f23a6290-2dec-45dc-b616-c218ee53db6b/#importfrontmatter).

Could you please check if this helps to solve the problem you are running into?
