### ISSUE TITLE
error creating a new page / new daily journal with the hot key

### ISSUE THREAD

**Issue by Newman5** [dendronhq/dendron#433]
**Describe the bug**
https://www.screencast.com/t/GpBGsBUiIFG5
I get an error when I try to create a new page / daily journal with the command hot key.

**To Reproduce**
1. Go to my last note
2. Click on the hotkey for new daily note
{"ctx":"h:run","err":{"status":"unknown","msg":"","payload":"{\"msg\":\"engine not set\",\"stack\":\"Error: engine not set\\n at F.getEngine (c:\\\\Users\\\\R-tech\\\\.vscode\\\\extensions\\\\dendron.dendron-0.22.0\\\\dist\\\\extension.js:11:77231)\\n at Function.genNoteName (c:\\\\Users\\\\R-tech\\\\.vscode\\\\extensions\\\\dendron.dendron-0.22.0\\\\dist\\\\extension.js:11:110263)\\n at h.gatherInputs (c:\\\\Users\\\\R-tech\\\\.vscode\\\\extensions\\\\dendron.dendron-0.22.0\\\\dist\\\\extension.js:897:33628)\\n at h.run (c:\\\\Users\\\\R-tech\\\\.vscode\\\\extensions\\\\dendron.dendron-0.22.0\\\\dist\\\\extension.js:11:102081)\\n at processTicksAndRejections (internal/process/task_queues.js:94:5)\\n at c:\\\\Users\\\\R-tech\\\\.vscode\\\\extensions\\\\dendron.dendron-0.22.0\\\\dist\\\\extension.js:11:78107\"}"}}

**Expected behavior**
I was expecting a new daily journal file to be created and opened in the editor window

**Screenshots**
https://www.screencast.com/t/GpBGsBUiIFG5

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - VS code version - 1.52.1 [screenshot](https://www.screencast.com/t/bsOPgxlx)
 - Version 0.22.0

**Additional context**

**Dendron Log file**
[dendron.log](https://github.com/dendronhq/dendron/files/5752009/dendron.log)

**Comment by Newman5** [comment]
Here is the update.  I uninstalled the Dendron extension and it seemed to clear up for a bit, but now its back.  

I get an alert message that says 'Still initializing. Please close this window and try again after Dendron has been initialized'  The Source is Dendron Markdown Preview Enhanced (extension).  I was trying to open the preview.

I'll keep digging

**Comment by Newman5** [comment]
I think I have two workspace files going.  Could having two 'Dendron.code-workspace' files be a problem?  To be honest, I'm not really sure what the VS Code Workspace concept is or does.

**Comment by Newman5** [comment]
I removed all the extensions and both the 'Dendron.code-workspace' files and folders.  I saved the vault files, in case I can use them again.  (They weren't important notes)

And it's working again!

**Comment by kevinslin** [comment]
Hey, sorry for the delay in response. Seems like you got it worked out. Workspaces were likely the culprit. You can see more about it [here](https://dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html)
