### ISSUE TITLE
publish V2 throws error locally 

### ISSUE THREAD

**Issue by ric03uec** [dendronhq/dendron#434]
**Describe the bug**
when running the publish command mentioned in docs: https://dendron.so/notes/861e4e48-dcc5-4813-a695-8940ba6e64d3.html#setup, 

**To Reproduce**
1. build site using instructions in [docs](https://dendron.so/notes/861e4e48-dcc5-4813-a695-8940ba6e64d3.html#setup)

**Expected behavior**
site should be built locally and available on localhost:8080

**Screenshots**
![image](https://user-images.githubusercontent.com/1110988/103324183-1f8ec000-49fb-11eb-87ed-b098faeaa5a1.png)
.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: firefox
 - Dendron: 0.22.0
 - Nodejs: v14.15

**Comment by kevins8** [comment]
This is one fo the known regressions from the eleventy publishing - we use
prism behind the scenes and it doesn't support all syntaxes. Will take a
look at adding dot.

**Comment by ric03uec** [comment]
makes sense. looking forward to the fix. i'll revert to using publishing v1 for the time being. thanks!

**Comment by ric03uec** [comment]
is there a way to reduce the compile time for v1 publishing on local system. Its ridiculously long for me right now ~30 mins using `bundle exec jekyll serve --incremental` command for about 500 notes

![image](https://user-images.githubusercontent.com/1110988/103467782-5d475d80-4d07-11eb-960f-fecece7961ef.png)

**Comment by kevins8** [comment]
The long compile time was the reason why we're switching to eleventy. I've
noticed the same for http://kevinslin.com/ (around 450 pages). The new 11ty
publishing publishes everything in ~11s. We will have the prism thing fixed
by Monday so you should be able to switch over at that point

**Comment by ric03uec** [comment]
this is fixed with 0.23.0 release. 
thanks @kevins8 for the quick response!!
