### ISSUE TITLE
Published gifs not rendering

### ISSUE THREAD

**Issue by olivercrask** [dendronhq/dendron#435]
**Describe the bug**
Images seem to render fine when published, but gifs do not.

**To Reproduce**

Add a gif using the following syntax and then publish
![](assets/images/AThrillingGif.gif)

**Expected behavior**
gif images would render on the published webpage

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu Budgie 20.04
 - Browser: Firefox
 - Version: 22

**Comment by kevinslin** [comment]
GIFS should work. See example [here](https://dendron.so/notes/f9540bb6-7a5a-46db-ae7c-e1a606f28c73.html#dendron-create-daily-journal-note). What syntax are you using?
