### ISSUE TITLE
Published table of contents Z-A

### ISSUE THREAD

**Issue by olivercrask** [dendronhq/dendron#438]
**Describe the bug**
Table of contents ordering is reversed when comparing to the ordering in the sidebar. Not the case on dendron.so, but is for my own published page.

**To Reproduce**
Publish a vault

**Expected behavior**
I would expect ordering in the side bar to match the ordering in the table of contents

**Screenshots**
Dendron.so:
![image](https://user-images.githubusercontent.com/36341776/103447981-a907f180-4c8a-11eb-8e56-011bcedb6bee.png)

My own dendron site:
![image](https://user-images.githubusercontent.com/36341776/103447996-e3718e80-4c8a-11eb-968a-9fefd42b0d3b.png)
(Applies to every hierarchy)

Desktop (please complete the following information):

    OS: Linux Ubuntu Budgie 20.04
    Browser: Firefox
    Version: 22

**Comment by kevins8** [comment]
We did some updates to the nav ordering to make it consistent in both
places. Make sure you're using the latest version of @dendronhq/11ty
(1.22.6)

Docs for nav ordering here:
https://dendron.so/notes/5f23182f-2936-4790-8d04-00bd502df723.html

**Comment by olivercrask** [comment]
Resolved with 11ty publishing :)
