### ISSUE TITLE
Adding front matter after the fact

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#44]
**Is your feature request related to a problem? Please describe.**
I usually create new pages as placeholder links and then navigate to them but then I'm sad that there's no front matter (even though I don't use the front matter yet). 

**Describe the solution you'd like**
Ideally when I navigate to the page via dendron, the front matter will be added for me. 

**Describe alternatives you've considered**
I would accept just having a shortcut to add the front matter (so I might be missing a simple way to do this). 

**Additional context**

**Comment by kevinslin** [comment]
Currently, Dendron will create the frontmatter when you create a file via [lookup](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.topic.lookup.md). It will not create the frontmatter when you navigate via a link or when you create the file manually. 

Created an issue to create frontmatter when navigating links [here](https://github.com/dendronhq/dendron/issues/45). For existing notes, will be adding a tune up command that will add frontmatter to notes that don't have it. Progress tracked in #46

Currently, Dendron doesn't do much with the [frontmatter](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.topic.frontmatter.md) besides showing titles on the graphs so it's okay if you don't have frontmatter on every note.

**Comment by kevinslin** [comment]
this has now been shipped in dendron 0.4.2. see documentation [here](https://www.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#doctor)
