### ISSUE TITLE
Preview for links not rendering correctly

### ISSUE THREAD

**Issue by ms3056** [dendronhq/dendron#442]
**Describe the bug**
Links of the form [[work.note.2021.01.05.meeting wPaul]] are not rendering in preview correctly. The issue is there is a space in the filename which seems to be the problem. Only the last part of the link is a "link" (see attached image). 

**To Reproduce**
1. Create a link with a space in it
2. Hit preview

**Expected behavior**
I expect the entire link to be an active link. 

**Screenshots**
![image](https://user-images.githubusercontent.com/23712700/103594622-8e5ca380-4f3c-11eb-89ba-94d67d7a7f40.png)

**Comment by aleksey-rowan** [comment]
@ms3056, Dendron is no longer using Markdown Preview Enhanced for Markdown rendering. The V2 preview is automatically enabled for newly initialized workspaces/vaults. For an existing one, add `enablePreviewV2: true` under `dev` in your `dendron.yml`.

```yml
// dendron.yml
dev:
    enablePreviewV2: true
```

The issue you are describing seems to have been resolved in the new preview. Could you please check if it works for you as well?
