### ISSUE TITLE
Provide FoldingRange for frontmatter

### ISSUE THREAD

**Issue by wjbuys** [dendronhq/dendron#446]
**Is your feature request related to a problem? Please describe.**
The front matter at the top of every note is usually not relevant to reading the note. Especially when I have many short notes open (like you'd do in Obsidian), the frontmatter takes up most of the note's window:

![image](https://user-images.githubusercontent.com/31602/103824779-6bf48400-5029-11eb-9ca4-7efac83a47f0.png)

**Describe the solution you'd like**
I'd like to fold the front matter; optionally by default (like VS Code does for Java imports). It looks like it should be pretty straightforward for the Dendron extension to implement a [FoldingRangeProvider](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider) that supports this.

**Comment by kevins8** [comment]
Hey Jacob,

Thanks for the issue. Your right about the frontmatter taking up space. Our
backlog is pretty full at the moment so this might be a February task
unless someone else picks it up first.

**Comment by hikchoi** [comment]
Okay, this seems like somethiing that I would like to use as well. Will try to tackle this feature :+1:

**Comment by kevinslin** [comment]
This was shipped in 0.29. thanks @hikchoi 
Splitting the auto folding frontmatter into a separate issue #489 489
