### ISSUE TITLE
Title-ize wiki links option for publishing

### ISSUE THREAD

**Issue by theianjones** [dendronhq/dendron#448]
**Is your feature request related to a problem? Please describe.**
I want my [[wiki.links]] to renders as their not titles when I run `npx dendron-cli buildSiteV2 --wsRoot .  --stage prod`

**Describe the solution you'd like**

When theres is a link discovered, say: `[[terms.ddd.event-storming]]`. I want the rendered link in my 11ty site to be the title of the note: `Event Storming`.

Seems like this could also apply to the markdown preview as well.

**Describe alternatives you've considered**
We can alias links, but this gets a little tedious. I don't mind looking at the hierarchy when I'm editing my notes.

**Comment by kevinslin** [comment]
this is now released in 0.26 :) 

https://dendron.so/notes/f5d459b0-01ea-4bd2-bb8b-ed7f7f7a8e0c.html
