### ISSUE TITLE
Issues with \ in Enhanced Preview

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#450]
**Describe the bug**
Using \ to escape symbols is not working properly with the enhanced preview. This was addressed with version 0.9.3 according to Issue #156, however this no longer seems to be the case with version 0.10.19.

**To Reproduce**
1. Type \$ into the text area.
2. Open the enhanced preview.
3. The $ symbol is not rendered properly. 

**Expected behavior**
That using \ to escape symbols should have them render properly in the enhanced preview.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/76890677/104680507-06099b80-56be-11eb-8dbe-ea05c339e9a6.PNG)
![Capture2](https://user-images.githubusercontent.com/76890677/104680522-10c43080-56be-11eb-8ce9-df7381234170.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: NA
 - Version: Dendron 0.24.0 and Dendron Markdown Preview Enhanced 0.10.19

**Comment by micharris42** [comment]
An update to this issue:

As of the newest versions, Dendron 0.26.1 and Dendron Markdown Preview Enhanced 0.10.22, using \ to escape **single instances** of a symbol no longer appears to be necessary. 

In the example above, the lone $4.99 will now render correctly in the preview with or without the use of \ to escape.

However, when **multiple instances** of a symbol are used (such as the other four lines in the example above), they are still not rendered correctly in the preview.

Thank you.

**Comment by kpathakota** [comment]
Yeah, this still repros. We *are* looking at replacing this entire component soon, so this will be an issue we could use some help on.

**Comment by aleksey-rowan** [comment]
Hey, @micharris42, Dendron has since moved away from using MPE for Markdown rendering and uses a different engine. The new preview is automatically enabled for newly initialized workspaces/vaults. For an existing one, add `enablePreviewV2: true` under `dev` in your `dendron.yml`.

```yml
// dendron.yml
dev:
    enablePreviewV2: true
```

The only reference in the docs to this setting that I could find is here: https://wiki.dendron.so/notes/Tf4vuVLV3rSdpzD8la9FP/#preview-v2-enhancements

Could you please check if the issues you are describing are still present in the new preview?

**Comment by micharris42** [comment]
You win the prize for this one, @aleksey-rowan. I had completely forgotten this issue. Fairly confident this could have been closed after the new preview was introduced, but for the sake of certainty ran the same test as above:

![Capture1](https://user-images.githubusercontent.com/76890677/156825998-59315360-fbc2-479e-a75c-edc068b7199b.PNG)

![Capture2](https://user-images.githubusercontent.com/76890677/156826010-8e4abba3-3d14-4983-bca7-ff4fb974fd5a.PNG)

I do not think the \ character can be used to escape symbols with the new preview. Possibly that might need to be addressed at some point, but marking this issue as closed.
