### ISSUE TITLE
[Proposal] Issue labeling automation

### ISSUE THREAD

**Issue by flammehawk** [dendronhq/dendron#451]
## Context

Github Issues and automation of labeling.

## Proposal

My Proposal would be to add https://github.com/github/issue-labeler as a Workflow to the repo and adjust the Issue templates accordingly. 

The changes to the templates would include adding a checklist of affected areas to the template and if one of the boxes gets checked it should add a corresponding label to the issue. 

I offer myself to implement these changes, just assign the issue to me and maybe leave a list of requests of what should be included in the checklist, else I will try to use common sense in designing the Checklists.

**Comment by kevinslin** [comment]
That's a great suggestion. Would be great to have this and having people use the checkbox would be a great initial triaging steps.

For checklist, whatever we end up using should also be reflected in our triage [doc](https://dendron.so/notes/1e6c8b49-ef88-4e79-b2df-e9d614c38a53.html). 

Maybe `area` and bug/feature as the first two fields? Oh, and auto-apply a `status.triage-needed` for all new tasks. 

Will assign this to you. Let me know if you need additional permissions (I think you can also submit a pull request in the meantime for template changes).

**Comment by flammehawk** [comment]
So I started on it and established some of the rules already.

See the linked Pull Request for it.

It means we would need some additional labels here on Github, those I can't create. 

If you have any requests on how to handle the Pod/Seed requests please tell me. I currently would add the lable area Pod / Seed and the `type.request` to them.

**Comment by kevinslin** [comment]
Thanks for getting on this. The rules look good. It would be good to further elaborate on each area in parenthesis (maybe with a link to the [triage doc](https://dendron.so/notes/1e6c8b49-ef88-4e79-b2df-e9d614c38a53.html). For pod/seed, we can label them with the right `area` and put the type as `feature`

**Comment by flammehawk** [comment]
Okay will add these things. 

But first will update the triage docs accordingly when I got some time on hand, could be next weekend depending on free time.
