### ISSUE TITLE
A support for Mermaid code publishing

### ISSUE THREAD

**Issue by oolonek** [dendronhq/dendron#454]
**Is your feature request related to a problem? Please describe.**

I and some others would be interesting in an improved management of diagrams in Dendron. 
The mermaid markup is flexible and well handled, also with the Dendron Markdown Enhanced plugin https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams?id=mermaid
However such diagrams do not get publish

**Describe the solution you'd like**

A way to publish mermaid (or alternative diagram markup) using the dendron publishing functions.

**Describe alternatives you've considered**

Displaying the diagram in the .md preview, screenshot, copy pasting the image.

Many thanks !

**Comment by flammehawk** [comment]
If I understand it correctly you want a way to register something with Dendron publishing that handles Named Codeblocks?

**Comment by oolonek** [comment]
Well if this was possible it would be even better and much more generic ! 
Do you mean that this way it would be possible to publish any correctly displayed local codeblocks ? 
Such as these for example https://open-vsx.org/extension/mathpix/vscode-mathpix-markdown ? 

If this was doable of course ! 🚀

**Comment by flammehawk** [comment]
Well if it was build In the generic way I Mentioned.
 
Others could write the Providers for the named Codeblocks.  Meaning @kevinslin  could focus on core functionality and would only need to provide the ways to register these things + maybe a way to install these Plugins. 

That way It could be really extensible and maybe it could even be used to provide the preview with additions that are not part of dendron.

**Comment by kevinslin** [comment]
this is now supported in 0.26  :)

https://dendron.so/notes/f5d459b0-01ea-4bd2-bb8b-ed7f7f7a8e0c.html
