### ISSUE TITLE
Cannot create 

### ISSUE THREAD

**Issue by Jan-Jan** [dendronhq/dendron#455]
**Describe the bug**

**To Reproduce**
1. press Ctrl+Shift+L
2. enter "resources.map"
3. See error "schemas can only be one level deep"

**Expected behavior**
Create a file "resources.map.md"

**Desktop (please complete the following information):**
 - OS: ubuntu
 - VSCode 1.52.1
 - Dendron 0.24.0

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

Not an option

**Comment by kevins8** [comment]
Are you trying to create a note or a schema? For notes, use `CTRL+L` .
CTRL+SHIFT+L creates schemas (
https://dendron.so/notes/c5e5adde-5459-409b-b34d-a0d75cbb1052.html) which
as the error indicated, can only be one level deep

**Comment by kevinslin** [comment]
closing for now. feel free to re-open if its still an issue
