### ISSUE TITLE
Show Note Graph should should progress bar when initializing

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#456]
## Context

Currently, there is no progress bar which makes the extension appear non-functional

## Proposal

Add a progress bar

**Comment by flammehawk** [comment]
Do I understand it correctly that the webview should show some form of loding indicator?

**Comment by kevinslin** [comment]
Yep. This is just adding a progress indicator like the one [here](
https://github.com/dendronhq/markdown-links/blob/f00d1f0cc821d67f84c803ffd091eafb6a49b59d/src/dendron/ShowSchemaCommand.ts#L47-L47).
Thought it would be a good first task for folks.

**Comment by hikchoi** [comment]
picking this up as it's a good excuse to look into the graph viz code 🙂
