### ISSUE TITLE
Needing to use mouse while refactoring hierarchies

### ISSUE THREAD

**Issue by Stedag** [dendronhq/dendron#460]
This is a low priority enhancement. I only started refactoring several hierarchies today and it's certainly faster than shuffling files!

When I use ```Dendron: Refactor Hierarchy```, once the confirmation dialog comes up I can't just "jump" into it. I have to use my mouse to select proceed.

I reproduced on vscode and codium on Windows 10 with Dendron 0.25.2.

Also, it may be safer to have the ```cancel``` option ahead of the ```proceed``` option. Personally I'd rather use time tabbing over ```cancel``` rather than mousing over to ```proceed```

**Comment by kevinslin** [comment]
Thanks for the issue. This was something that was introduced by the upgrade to 1.51 of vscode. Need to investigate why this started happening but it might be a few weeks before I can get to this

**Comment by hikchoi** [comment]
Tried my hands at debugging this issue.

I think the webview that opens up is somehow hijacking the focus from the quick pick dialog, or maybe never gave up focus when the quick pick was opened.

I can confirm that focus works correctly if I comment out [this line](https://github.com/dendronhq/dendron/blob/f708a4775d2c07de9861ff67afb4ff81a84d1075/packages/plugin-core/src/commands/RefactorHierarchyV2.ts#L164), but that's pretty much the extent of my knowledge of vscode extension internals (and dendron plugin-core) for the time being.

I see a few [issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+webview+focus) on the vscode Github repo about webview stealing focus undesirably, but I can't seem to find something that's similar to our problem.

I'll report back if I find something else worth sharing while I play around with the plugin code 😃

**Comment by aleksey-rowan** [comment]
Hey, @Stedag, this issue got fixed about a month ago, but it looks like it wasn't included in the release notes. You can see the PR here:

- https://github.com/dendronhq/dendron/pull/3152

Please, check if the issue is resolved for you in the latest version of Dendron.
