### ISSUE TITLE
title in daily notes vs. journal notes

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#461]
**Describe the bug**
In newly created daily notes the title is just the day (e.g. "23") instead of the whole date (e.g. "2021-01-23")

**To Reproduce**
1. initialize a new empty workspace
2. Use the following settings: 
    "dendron.dailyJournalDomain": "daily",
    "dendron.defaultJournalAddBehavior": "childOfCurrent",
    "dendron.defaultJournalName": "journal",
3. Create a new daily note using `Crtl-Shift+I`. The new file `daily.journal.2021.01.23.md` has the title '23'
4. Create an arbitrary note say `test.md`
5. Create a new journal note using `Crtl+Shift+J`. The new file `test.journal.2021.01.23`has the title '2021-01-23'

**Expected behavior**
Both types of journal notes should have the complete date as title

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - VSCodium Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-17T10:38:46.981Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
 - Dendron Version 0.25.3

**Dendron Log file**
{"level":30,"time":1611430184639,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1611430184672,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"c:\\Users\\Bassmann\\AppData\\Roaming\\VSCodium\\logs\\20210123T202512\\exthost1\\dendron.dendron","logLevel":"info","extensionPath":"c:\\Users\\Bassmann\\.vscode-oss\\extensions\\dendron.dendron-0.25.3","extensionUri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\.vscode-oss\\extensions\\dendron.dendron-0.25.3","_sep":1,"path":"/c:/Users/Bassmann/.vscode-oss/extensions/dendron.dendron-0.25.3","scheme":"file"},"storagePath":"c:\\Users\\Bassmann\\AppData\\Roaming\\VSCodium\\User\\workspaceStorage\\19c69e69d7a44ab3822047b7602422fa\\dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\dendron.code-workspace","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/dendron.code-workspace","path":"/c:/Users/Bassmann/Dendron-dates/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault","path":"/c:/Users/Bassmann/Dendron-dates/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1611430184674,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1611430184676,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"vault"}],"useFMTitle":true,"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","usePrettyRefs":true,"title":"Dendron"}},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1611430184733,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","files.autoSave":"onFocusChange","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on"},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","github.github-vscode-theme"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1611430184749,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.25.3","migratedGlobalVersion":"0.25.3","previousGlobalVersion":"0.24.1","previousWsVersion":"0.0.0","platform":"win32","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"equinusocio.vsc-material-theme","version":"33.1.2","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.19","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.19","active":false},{"id":"github.github-vscode-theme","version":"1.1.5","active":false}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1611430184749,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"startServer","logLevel":"info"}
{"level":30,"time":1611430184761,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"_activate","msg":"post-start-server","port":20725}
{"level":30,"time":1611430184764,"pid":4000,"hostname":"myPC","name":"logger","ctx":"FileStorageV2","wsRoot":"c:\\Users\\Bassmann\\Dendron-dates","vaultsv3":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1611430184772,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1611430184832,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1611430184832,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1611430184832,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1611430184833,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"postReloadWorkspace","msg":"preUpgrade: new wsVersion"}
{"level":30,"time":1611430184833,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"h:run","msg":"pre-execute"}
{"level":30,"time":1611430184833,"pid":4000,"hostname":"myPC","name":"UpgradeSettingsCommand","ctx":"Upgrade:execute"}
{"level":30,"time":1611430184843,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WorkspaceConfig:update","vscodeDir":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\.vscode","snippetChanges":{}}
{"level":30,"time":1611430184843,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"Upgrade:execute","newConfig":{"extensions":{},"settings":{"add":{},"errors":{}},"snippetChanges":{}}}
{"level":30,"time":1611430184843,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"Upgrade:execute","badExtensions":[]}
{"level":30,"time":1611430184843,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"h:run","msg":"post-execute"}
{"level":30,"time":1611430184844,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"postReloadWorkspace","msg":"postUpgrade: new wsVersion","previousWsVersion":"0.0.0","newVersion":"0.25.3"}
{"level":30,"time":1611430185348,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1611430185348,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1611430185348,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1611430185349,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"activateWorkspace","stage":"dev","msg":"enter"}
{"level":30,"time":1611430185351,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1611430185351,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"_activate","msg":"fin startClient"}
{"level":30,"time":1611430185351,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.25.3","previousVersion":"0.25.3"}
{"level":30,"time":1611430185351,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1611430192600,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1611430192601,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","opts":{"flavor":"note"},"msg":"enter"}
{"level":30,"time":1611430192603,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","profile":2,"msg":"postCreateController"}
{"level":30,"time":1611430192603,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","profile":2,"msg":"post:extractRange"}
{"level":30,"time":1611430192604,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","msg":"enter","cleanOpts":{"ignoreFocusOut":true}}
{"level":30,"time":1611430192606,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":1,"msg":"post:createQuickPick"}
{"level":30,"time":1611430192606,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"post:createProvider"}
{"level":30,"time":1611430192608,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerBehavior","activeButtons":[{"iconPathNormal":{"id":"find-selection"},"iconPathPressed":{"id":"menu-selection"},"type":"selectionExtract","pressed":true,"title":"Selection Extract","canToggle":true,"opts":{"title":"Selection Extract","iconOff":"find-selection","iconOn":"menu-selection","type":"selectionExtract"}}]}
{"level":30,"time":1611430192609,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","profile":8,"msg":"post:show"}
{"level":30,"time":1611430192611,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"","source":"updatePickerBehavior:normal"}
{"level":30,"time":1611430192614,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"","source":"updatePickerBehavior:normal","profile":3,"cancelled":false}
{"level":30,"time":1611430192614,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"post:updatePickerBehavior"}
{"level":30,"time":1611430192616,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"post:provide"}
{"level":30,"time":1611430192616,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"exit"}
{"level":30,"time":1611430192616,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1611430193975,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"t","source":"onValueChange"}
{"level":30,"time":1611430193976,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430193982,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430193985,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":8}
{"level":30,"time":1611430193985,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"t","source":"onValueChange","profile":10,"cancelled":false}
{"level":30,"time":1611430194178,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"te","source":"onValueChange"}
{"level":30,"time":1611430194178,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430194182,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430194184,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":6}
{"level":30,"time":1611430194184,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"te","source":"onValueChange","profile":6,"cancelled":false}
{"level":30,"time":1611430194361,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"tes","source":"onValueChange"}
{"level":30,"time":1611430194362,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430194362,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430194365,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1611430194365,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"tes","source":"onValueChange","profile":3,"cancelled":false}
{"level":30,"time":1611430194575,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test","source":"onValueChange"}
{"level":30,"time":1611430194576,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430194576,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430194579,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":2}
{"level":30,"time":1611430194579,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test","source":"onValueChange","profile":3,"cancelled":false}
{"level":30,"time":1611430194776,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.","source":"onValueChange"}
{"level":30,"time":1611430194776,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430194777,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430194779,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1611430194780,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.","source":"onValueChange","profile":4,"cancelled":false}
{"level":30,"time":1611430195643,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.m","source":"onValueChange"}
{"level":30,"time":1611430195643,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430195644,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430195646,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1611430195647,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.m","source":"onValueChange","profile":4,"cancelled":false}
{"level":30,"time":1611430195840,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.md","source":"onValueChange"}
{"level":30,"time":1611430195840,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430195841,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430195843,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1611430195843,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.md","source":"onValueChange","profile":3,"cancelled":false}
{"level":30,"time":1611430196895,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onDidAcceptSingle","msg":"enter","value":"test.md","opts":{"flavor":"note"},"noteOverrides":{},"selectedItems":[{"fname":"Create New","id":"29d9ad42-3b81-4f7e-974f-824a34238b69"}],"activeItems":[{"fname":"Create New","id":"29d9ad42-3b81-4f7e-974f-824a34238b69"}]}
{"level":30,"time":1611430196895,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode"}
{"level":30,"time":1611430196896,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"createNewPick","value":"test.md"}
{"level":30,"time":1611430196897,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"create normal node"}
{"level":30,"time":1611430196898,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"post:maybeAddSchema"}
{"level":30,"time":1611430196899,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"pre:checkNoteExist"}
{"level":30,"time":1611430196899,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"pre:pickerOnCreate"}
{"level":30,"time":1611430196901,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"pre:engine.write","uri":{"$mid":1,"path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.md","scheme":"file"}}
{"level":30,"time":1611430196924,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"engine.write"}
{"level":30,"time":1611430197191,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.md","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault/test.md.md","path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.md","scheme":"file"}}
{"level":30,"time":1611430197197,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"VaultWatcher:onDidCreate","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.md","_sep":1,"path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.md","scheme":"file"}}
{"level":30,"time":1611430202518,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"showDocAndHidePicker","msg":"showTextDocument","fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.md"}
{"level":30,"time":1611430202540,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"refreshTree"}
{"level":30,"time":1611430204205,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"f:run","msg":"pre-execute"}
{"level":30,"time":1611430204207,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"daily.journal.2021.01.23","mode":"note","vault":{"fsPath":"vault"}},"msg":"enter"}
{"level":30,"time":1611430204334,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\daily.journal.2021.01.23.md","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault/daily.journal.2021.01.23.md","path":"/c:/Users/Bassmann/Dendron-dates/vault/daily.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430204345,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"daily.journal.2021.01.23","mode":"note","vault":{"fsPath":"vault"}},"msg":"exit"}
{"level":30,"time":1611430204346,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"f:run","msg":"post-execute"}
{"level":30,"time":1611430204346,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"VaultWatcher:onDidCreate","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\daily.journal.2021.01.23.md","_sep":1,"path":"/c:/Users/Bassmann/Dendron-dates/vault/daily.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430204455,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"refreshTree"}
{"level":30,"time":1611430211390,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.md","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault/test.md.md","path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.md","scheme":"file"}}
{"level":30,"time":1611430213055,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1611430213055,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","opts":{"noteType":"journal","flavor":"note"},"msg":"enter"}
{"level":30,"time":1611430213057,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","profile":1,"msg":"postCreateController"}
{"level":30,"time":1611430213057,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","profile":1,"msg":"post:extractRange"}
{"level":30,"time":1611430213057,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","msg":"enter","cleanOpts":{"ignoreFocusOut":true}}
{"level":30,"time":1611430213058,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":0,"msg":"post:createQuickPick"}
{"level":30,"time":1611430213058,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":1,"msg":"post:createProvider"}
{"level":30,"time":1611430213059,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerBehavior","activeButtons":[{"iconPathNormal":{"id":"find-selection"},"iconPathPressed":{"id":"menu-selection"},"type":"selectionExtract","pressed":true,"title":"Selection Extract","canToggle":true,"opts":{"title":"Selection Extract","iconOff":"find-selection","iconOn":"menu-selection","type":"selectionExtract"}},{"iconPathNormal":{"id":"calendar"},"iconPathPressed":{"id":"menu-selection"},"type":"journal","pressed":true,"title":"Create Journal Note","canToggle":true,"opts":{"title":"Create Journal Note","iconOff":"calendar","iconOn":"menu-selection","type":"journal"}}]}
{"level":30,"time":1611430213059,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupCommand:execute","profile":4,"msg":"post:show"}
{"level":30,"time":1611430213061,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"test.md.journal.2021.01.23","source":"updatePickerBehavior:journal"}
{"level":30,"time":1611430213061,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1611430213067,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":1,"msg":"post:updatePickerBehavior"}
{"level":30,"time":1611430213068,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":1,"msg":"post:provide"}
{"level":30,"time":1611430213069,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"LookupControllerV2:show","profile":1,"msg":"exit"}
{"level":30,"time":1611430213069,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1611430213074,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1611430213074,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":13}
{"level":30,"time":1611430213075,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"test.md.journal.2021.01.23","source":"updatePickerBehavior:journal","profile":14,"cancelled":false}
{"level":30,"time":1611430215039,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onDidAcceptSingle","msg":"enter","value":"test.md.journal.2021.01.23","opts":{"flavor":"note"},"noteOverrides":{"title":"2021-01-23"},"selectedItems":[{"fname":"Create New","id":"a11a5301-960c-4b6d-b61c-f2b312604ec7"}],"activeItems":[{"fname":"Create New","id":"a11a5301-960c-4b6d-b61c-f2b312604ec7"}]}
{"level":30,"time":1611430215039,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode"}
{"level":30,"time":1611430215040,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"createNewPick","value":"test.md.journal.2021.01.23"}
{"level":30,"time":1611430215041,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"create normal node"}
{"level":30,"time":1611430215042,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"post:maybeAddSchema"}
{"level":30,"time":1611430215042,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"pre:checkNoteExist"}
{"level":30,"time":1611430215043,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"pre:pickerOnCreate"}
{"level":30,"time":1611430215044,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"pre:engine.write","uri":{"$mid":1,"path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430215062,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"onAcceptNewNode","msg":"engine.write"}
{"level":30,"time":1611430215171,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.journal.2021.01.23.md","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430215180,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"showDocAndHidePicker","msg":"showTextDocument","fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.journal.2021.01.23.md"}
{"level":30,"time":1611430215190,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"VaultWatcher:onDidCreate","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.journal.2021.01.23.md","_sep":1,"path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430215305,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"refreshTree"}
{"level":30,"time":1611430334610,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\AppData\\Roaming\\VSCodium\\User\\settings.json","_sep":1,"external":"vscode-userdata:/c%3A/Users/Bassmann/AppData/Roaming/VSCodium/User/settings.json","path":"/C:/Users/Bassmann/AppData/Roaming/VSCodium/User/settings.json","scheme":"vscode-userdata"}}
{"level":30,"time":1611430417929,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.journal.2021.01.23.md","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430421641,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\daily.journal.2021.01.23.md","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault/daily.journal.2021.01.23.md","path":"/c:/Users/Bassmann/Dendron-dates/vault/daily.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430560457,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\Dendron-dates\\vault\\test.md.journal.2021.01.23.md","_sep":1,"external":"file:///c%3A/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","path":"/c:/Users/Bassmann/Dendron-dates/vault/test.md.journal.2021.01.23.md","scheme":"file"}}
{"level":30,"time":1611430699012,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1611430699013,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1611430699030,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1611430699184,"pid":4000,"hostname":"myPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Bassmann\\AppData\\Roaming\\VSCodium\\logs\\20210123T202512\\exthost1\\dendron.dendron\\dendron.log","_sep":1,"external":"file:///c%3A/Users/Bassmann/AppData/Roaming/VSCodium/logs/20210123T202512/exthost1/dendron.dendron/dendron.log","path":"/c:/Users/Bassmann/AppData/Roaming/VSCodium/logs/20210123T202512/exthost1/dendron.dendron/dendron.log","scheme":"file"}}

**Comment by kevinslin** [comment]
you're right - this is a bug. will fix this week!

**Comment by kevinslin** [comment]
fixed in 0.27
