### ISSUE TITLE
Add Day of the Week to the Epoch Timestamps

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#468]
**Is your feature request related to a problem? Please describe.**
For Journal notes and others for which the date is an important factor, it would be useful to have the additional context of the day of the week included with the "created" and "updated" frontmatter.

**Describe the solution you'd like.**
At the moment, the epoch timestamps are presented as such:

1612190405514 (Feb 1, 2021, 9:40 AM)

This could be changed to include the day of the week, such as: 

1612190405514 (Mon, Feb 1, 2021, 9:40 AM)

**Describe alternatives you've considered**
Alternatively, a user could look up the associated day of the week manually using an epoch converter website, or, as suggested on the Dendron site, install the timestamp converter extension. Both of these options seem a waste however, as Dendron already converts the majority of its epoch timestamps to a human readable format. 

Thank you.

**Comment by kevinslin** [comment]
Thanks for the feature request. Adding it to our backlog!

**Comment by hikchoi** [comment]
Could this be something that can be configurable in `dendron.code-workspace`? Looks like the text decoration is created by turning the epoch timestamp into a LocaleString with Luxon.

In any case, I'll grab this issue. If you feel like it's better to expose the configuration to the workspace settings, I could do that as well.

Let me know @kevinslin

**Comment by kevinslin** [comment]
Yes it can. I'm okay with having this as a default and we can add a
configuration at a later point if people want it. Feel free to grab this :)

**Comment by hikchoi** [comment]
#479 adds a configurable human readable timestamp decoration, but the closest option to displaying day of week is to use `DATE_MED_WITH_WEEKDAY`, which will show the day of week but not show the time of day.

I can see later on we can make users provide their own date formatting. But for now, I hope this is good enough for the person who opened this issue :)

**Comment by micharris42** [comment]
Held off on replying until the change(s) made it to release. This works fine for my original request. 

I do think it is a shame that `DATETIME_MED_WITH_WEEKDAY` is not an option, but I assume this is a Luxon issue and not a Dendron issue. 

@kevinslin, @hikchoi, thank you both.
