### ISSUE TITLE
Allow user to choose port number for publish/preview.

### ISSUE THREAD

**Issue by brimwats** [dendronhq/dendron#469]
**Is your feature request related to a problem? Please describe.**

I have a webserver running yunohost.org and it uses the 8080 port, so publish site will not work for me. 

This is reproducible to some extent
0. have a server using port 8080
1. fresh install of vscodium, no addons
2. installed dendron 
3. downloaded test vault

**Describe the solution you'd like**
Publish should skip to an open port like Hugo does, or we should be able to pick a port for it. 

**Describe alternatives you've considered**
N/A (there aren't any other options in my case).

**Comment by mandarvaze** [comment]
I saw that environment variable `ELEV_PORT` is used some place, but 8080 is hardcoded at other places.

I tried setting ELEV_PORT` and running dev server using `dendron-cli` but it didn't work (At least the message on the terminal says 8080)

**Comment by kevinslin** [comment]
Yeah, this is why this is in the feature request stage. We need to be consistent about using that everywhere at which point we can close this ticket 😅

**Comment by kevinslin** [comment]
this is now possible in 0.38.0 :) 

https://wiki.dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#previewport

**Comment by bonnebulle** [comment]
Hello
Sorry to re-open this.
I follow the wiki instructions by adding "previewPort: 8999" into my config file (dendron.yml)
But it not fully change the port (some ressources keep using 8080)
.
I need to use an other port than 8080 (used by a Nginx project)
Maybe you can help, 
Thanks

**Comment by kpathakota** [comment]
@bonnebulle - no worries, I've opened up a bug-type issue for you, could you add the details you need to that? #705
