### ISSUE TITLE
move note command should not have vault selector if just one vault

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#470]
The [move note](https://dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#move-note) command will prompt you every time to select a vault. This should only happen in multi-vault workspaces.

**Comment by hikchoi** [comment]
Was just about to pick up this issue, but I found a problem with moving scratch notes.
Seems to work for notes that are not scratch notes.

will open a separate issue for it.

**Comment by kevinslin** [comment]
Leaving some additional context. To make the vault selector go away, [this portion](https://github.com/dendronhq/dendron/blob/dev-kevin/packages/plugin-core/src/commands/MoveNoteCommand.ts#L52:L56) of code should preset the `VaultSelectButton` to `false` if there aren't multiple vaults.

You can check for vaults using `getWS().config.vaults`
