### ISSUE TITLE
Support for multi-level schemas

### ISSUE THREAD

**Issue by alexisargyris** [dendronhq/dendron#48]
**Is your feature request related to a problem? Please describe.**
I attempted to set up a two-level schema like so:
![image](https://user-images.githubusercontent.com/1640855/88152747-24aa4080-cc0d-11ea-86b3-2522219d2edc.png)
and got the error message displayed above. The message goes away if the second level is removed.

**Describe the solution you'd like**
Support for multi-level schemas.

**Comment by kevinslin** [comment]
you're right. this is a bug right now with the way schemas are parsed. will be pushing outa fix for this later today

**Comment by kevinslin** [comment]
if you upgrade to the latest version (0.3.39), this should be fixed. can you confirm? 

fyi, you don't need the `parent` field in any entry besides `test1` when you're specifying a child of the `root`. everything else will be parsed by Dendron by following the children field

**Comment by alexisargyris** [comment]
Ttried this. Unfortunately, cant get it to work:

![image](https://user-images.githubusercontent.com/1640855/88328000-78617a80-cd30-11ea-81f0-06b46b1ebcbb.png)

**Comment by alexisargyris** [comment]
After deleting everything and re-initializing on a fresh directory it works!
