### ISSUE TITLE
Option to fold frontmatter automatically

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#489]
## Context

Frontmatter takes up space and some people don't use them

## Proposal

Option to make frontmatter fold automatically

**Comment by wjbuys** [comment]
(I still want this feature, bad stalebot!)

**Comment by kevins8** [comment]
Sorry Jacob, stale bot is only supposed to apply to issues that are
unclear. This is still part of our backlog!

**Comment by xypnox** [comment]
Additionally, When the editor opens with a new file created via lookup, the cursor remains in the start of the frontmatter and I have to navigate at the bottom to start writing. It would be better if the cursor was placed after the frontmatter when a new file was opened. I think this should also be doable for existing files but is more relevant for new files.
