### ISSUE TITLE
After Release 0.29, Dendron Markdown Preview Enhanced (Extension) still failing to load

### ISSUE THREAD

**Issue by kdjamesrd** [dendronhq/dendron#493]
Following message when attempting to use Markdown Preview Enhanced: 

Still initializing. Please close this window and try again after Dendron has been initialized.  Source: Dendron Markdown Preview Enhanced (Extension)

I started using Dendron in Release 0.28.  This function was working for a while, then something happened where it became inoperable.  Finally, after many uninstalls, (to include VSCode itself), got it to work.  Was told that it would be fixed in Release 0.29.  When I fired up Release 0.29 on Tuesday, it was broken again.

Without seeing how my links are actually rendering, this has become a show-stopper for me.

Please help.

**Comment by kevinslin** [comment]
can you run the `> Diagnostics Report` command and paste the output?

**Comment by kdjamesrd** [comment]
Thank you for your response.

I am not that familiar with VS Code and need instructions on how to run the diagnostics report.

The little buttons at the left corner of the screen, all indicate “no problems” after attempting to open the Enhanced Markdown Previewer, if that is any indication of anything.

I will need instructions as to what steps I should do (and in what order) to set up the scenario where I open one of my notes, and then click on the Enhanced Viewer.  What do I do next to capture the diagnostics?

Thank you

Ken

PS.  I see you are in the Spokane WA area.  I live down the road in College Place, WA (next door to Walla Walla).

**Comment by kdjamesrd** [comment]
I believe I have found, via the command pallet, the Diagnostic Report.

However, the symptoms have now changed.  The icon for the Enhanced Markdown Preview seems to be slightly dimmed in comparison to the other preview icon to the right of it.  And when the Enhanced Markdown icon is clicked, the pane opens blank, and there is no message at the bottom about Dendron not being initialized.  The Enhanced Markdown Preview pain is totally blank, it does not render the note.

I have attached a zip file of the Dendron workspace I have been experimenting in.  The actual file that I have been opening to test the Enhanced Markdown Preview is: RECIPES.Desserts.Pies.Cream Pies.Chocolate Cream Pie.md

Here is the contents of the Diagnostic Report:

{"ctx":"f:run","err":{"status":"unknown","msg":"","payload":"{\"msg\":\"ENOENT: no such file or directory, open '/Users/KDJ_MBP/Library/Application Support/Code/logs/20210219T203757/exthost1/dendron.dendron/dendron.server.log'\",\"stack\":\"Error: ENOENT: no such file or directory, open '/Users/KDJ_MBP/Library/Application Support/Code/logs/20210219T203757/exthost1/dendron.dendron/dendron.server.log'\\n\\tat Object.openSync (fs.js:466:3)\\n\\tat Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)\\n\\tat Object.readFileSync (fs.js:368:35)\\n\\tat Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)\\n\\tat f.execute (/Users/KDJ_MBP/.vscode/extensions/dendron.dendron-0.29.0/dist/extension.js:661:66425)\\n\\tat f.run (/Users/KDJ_MBP/.vscode/extensions/dendron.dendron-0.29.0/dist/extension.js:9:102930)\\n\\tat processTicksAndRejections (internal/process/task_queues.js:97:5)\\n\\tat async /Users/KDJ_MBP/.vscode/extensions/dendron.dendron-0.29.0/dist/extension.js:9:78209\\...


On Feb 19, 2021, at 1:55 PM, KENNETH JAMES <kdjamesrd@msn.com<mailto:kdjamesrd@msn.com>> wrote:

Thank you for your response.

I am not that familiar with VS Code and need instructions on how to run the diagnostics report.

The little buttons at the left corner of the screen, all indicate “no problems” after attempting to open the Enhanced Markdown Previewer, if that is any indication of anything.

I will need instructions as to what steps I should do (and in what order) to set up the scenario where I open one of my notes, and then click on the Enhanced Viewer.  What do I do next to capture the diagnostics?

Thank you

Ken

PS.  I see you are in the Spokane WA area.  I live down the road in College Place, WA (next door to Walla Walla).



On Feb 19, 2021, at 12:05 PM, Kevin Lin <notifications@github.com<mailto:notifications@github.com>> wrote:



can you run the > Diagnostics Report command and paste the output?

**Comment by kevinslin** [comment]
Hmm, it looks like you're not in an active Dendron workspace. Can you make sure the workspace file is [open](https://dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#engine-not-initialized)?

**Comment by kdjamesrd** [comment]
I am new to VSCode as a Markdown editor - I have so much to learn.  Apparently there are subtle differences between a “folder” and a “workspace.”  That folder I was using that I had zipped to you doesn’t have a file in it called “dendron.code-workspace.”  Not sure how that happened.

But I just did make a brand new workspace by using the Command Pallet Dendron: Initialize Workspace.  In it I added a new test file with a LaTex formula, and it rendered correctly with the Enhanced Markdown Preview.  So there must be something with my setup of workspaces and I need to just start afresh with clean new ones.

Thank you for your advice.

Ken

**Comment by kevinslin** [comment]
Yeah, vscode is a beast with many moving parts. Let me know if this ended up working out for you or if you still have issues.

**Comment by kdjamesrd** [comment]
Thank you. Another lesson learned - make certain you are working in an open workspace!

KDJ

Sent from my iPhone

On Feb 23, 2021, at 8:23 AM, Kevin Lin <notifications@github.com> wrote:

﻿

Yeah, vscode is a beast with many moving parts. Let me know if this ended up working out for you or if you still have issues.

**Comment by kpathakota** [comment]
@kdjamesrd - going to close this one out since it's  been a while and looks like the issue has been resolved.
