### ISSUE TITLE
Remove vault doesn't remove entry from payload in dendron.yml

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#505]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug

I played with adding and removing vault and noticed that new vaults get added to 
```
duplicateNoteBehavior:
        action: useVault
        payload:
``` 
but nor removed when I delete the vault

## To Reproduce

1. Add a new local vault with `Vault Add`
2. Check that the new vault is added ot the list under payload in `dendron.yml`
3. Remove the vault
4. The entry is still present

## Expected behavior

The vault should be removed from the paylod list once it is removed

## Desktop (please complete the following information)

- OS: Win 10
- VSCode 1.53.2
- Dendron 0.30

**Comment by kevinslin** [comment]
Yep, this is a bug. Also a good first issue. Thanks for reporting! Will fix this in a week if no one else claims it by then (cough: @hikchoi )

**Comment by hikchoi** [comment]
I'll have a look tomorrow 🙃
