### ISSUE TITLE
Automatically convert name to sausage case when creating a new note

### ISSUE THREAD

**Issue by ognjenio** [dendronhq/dendron#510]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

Chose Misc. since I'm not entirely sure how this would be categorized.

## Describe the solution you'd like ##

When using lookup and selecting to create the new note the entered text should be (optionally?) converted to sausage-case.

For example, if the user enters:

```ideas.This is a new idea that I just pasted```

The note created would be:

```ideas.this-is-a-new-note-that-i-just-pasted.md```

## Describe alternatives you've considered ##

Today's workaround is to download a [separate extension](https://dendron.so/notes/401c5889-20ae-4b3a-8468-269def4b4865.html#automatically-convert-casing-on-a-note) to do this.

**Comment by kpathakota** [comment]
This is now working. @ognjenio - let me know if you think there's still work to do here.
