### ISSUE TITLE
Subscription link on Contribute financially is not clickable

### ISSUE THREAD

**Issue by flashblaze** [dendronhq/dendron#511]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Subscription link on Contribute financially: https://dendron.so/notes/125c990b-6fe7-4ada-a65f-44cbde8b33f0.html#financially
is not clickable. It is clickable on *Go to text* which leads to this page: https://dendron.so/notes/abda4d2a-d8a2-4dd6-8ea0-4a5661fa13c1.html

## To Reproduce

1. Go to https://dendron.so/notes/125c990b-6fe7-4ada-a65f-44cbde8b33f0.html#financially
2. Click on *here*
3. Not clickable

## Expected behavior

*here* should be clickable link redirecting to https://accounts.dendron.so/account/subscribe

## Desktop (please complete the following information)

- OS: Windows 10
- Browser Firefox Developer Edition, Brave
- Version FF: 87.0b3, Brave: 88

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
Thanks for the issue. This is because of the css elements we're currently applying to render a reference. We'll be switching over to styled iframes that should remove this issue.

**Comment by kpathakota** [comment]
Should be fixed when we convert to Unified preview/NextJS -> #643. Still repro.

**Comment by kevinslin** [comment]
this is fixed now
