### ISSUE TITLE
Article link "It's not you it's your knowledge base" on Features page is not working

### ISSUE THREAD

**Issue by hamsternik** [dendronhq/dendron#513]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The link [It's not you it's your knowledge base](https://www.kevinslin.com/organizing/its_not_you_its_your_knowledge_base/) on the "Dendron/Features" page is not available right now.

The page reports next error message
```json
NoSuchKeyThe specified key does not exist.kevinslin/default/organizing/its_not_you_its_your_knowledge_base/Z14KK4YTGMKM5TQSuERSCNXqu7jKJJidPqGRhKZgond/QBxopKVlbdwFRTd7MiHd/k38FpMcga8vwE7YN71uzJ6WzEU=
```

## To Reproduce

1. Go to https://dendron.so/notes/4bb85c39-d8ac-48ad-a765-3f2a071f7bc9.html
2. Click on `this blog post` external link in the first paragraph.
3. See error (error text attached above).

## Expected behavior

The external link [this blog post](https://www.kevinslin.com/organizing/its_not_you_its_your_knowledge_base) should works and opens article page. Unless it's not a valid resource, please remove the link.

## Screenshots

<img width="1668" alt="Screenshot 2021-03-01 at 3 58 36 PM" src="https://user-images.githubusercontent.com/4441804/109507052-ffd15200-7aa6-11eb-8671-054533cc0af1.png">

## Desktop (please complete the following information)

- OS: macOS 11.2.2
- Browser: Safari
- Version 14.0.3

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
Just fixed! Thanks for pointing this out. 

By the way, if you are on our [discord](https://discord.gg/AE3NRw9), feel free to ping me your handle since this earns you the [taxonomist role](https://dendron.so/notes/7c00d606-7b75-4d28-b563-d75f33f8e0d7.html) 😇
