### ISSUE TITLE
Dendron auto-formats workplace settings file on startup

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#524]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Misc (Choose this if your not sure)

## Describe the bug

Dendron auto-formats workplace settings (`dendron.code-worspace`) on startup using rules which are not consistent with my local prettier settings and the formatting of this file flip-flops generating needless commits.

## To Reproduce

1. Open workplace settings (JSON view).
2. Add a couple of blank lines in between some settings.
3. Reload the window.
4. Observe that after Dendron starts, blank lines are removed.

## Expected behavior

I don't think there is a need for Dendron to format workspace settings file. If this required, Dendron should respect the default formatter settings (`.prettierrc` file for example).

## Desktop (please complete the following information)

- OS: Win 10x64
- Version 0.31.1

**Comment by kpathakota** [comment]
@aleksey-rowan - I think we should track this under #572 and we'll need to fix them together. Closing this as duplicate.
