### ISSUE TITLE
Open Preview of Linked Note instead of markdown file

### ISSUE THREAD

**Issue by Gargoth** [dendronhq/dendron#528]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [x] UI
- [x] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Whenever I click a linked note from the preview, it opens the .md file of the linked note. This switches the tab from the preview to the opened .md file which isn't the behavior newcomers expect.

## Describe the solution you'd like ##

It would be convenient if clicking a linked note from the preview would open the preview of the linked note instead of opening its .md file. 

Thanks!

**Comment by aleksey-rowan** [comment]
I believe it used to work before as you describe. Here's a video where Kevin describes his PARA setup and clicks a preview link which opens correctly inside the preview instead of opening an `.md` as it does now: https://youtu.be/vrhBNGMJQwE?t=92

**Comment by flammehawk** [comment]
Well it does open the md file and the preview changes from the "note" it was showing to the Preview of the newly opend note in the linked video.

What I think is asked for is a way to open a new Preview to the `side` without opening the Md file from it, if the File already exists.

**Comment by aleksey-rowan** [comment]
I think @Gargoth is referring to the following behaviour where a link clicked in the preview editor group opens an `.md` file in the same editor group, instead of opening it in the source group and updating the preview tab like in the video I mentioned:

![](https://i.imgur.com/M1PJDDc.gif)

**Comment by af4jm** [comment]
this is one of the things that's always confused me about Dendron... other extensions add support to the built-in preview for features such as Mermaid diagrams, TO DO lists, etc. why does Dendron swap out the entire preview just to add wikilink support???

**Comment by aleksey-rowan** [comment]
I believe there are already plans to replace MPE: https://wiki.dendron.so/notes/17c61d62-f92e-4002-b8fe-9c05686e4bf9.html#why

**Comment by af4jm** [comment]
hmm... I think what I'm going to do is uninstall MPE & install Markdown Wiki-links preview ... clicking the wikilinks doesn't actually do anything (which I suspect is a bug), but sinec it uses the default preview, it stays pinned on restarts, and when changing vaults (I just discovered this morning that if you open a note in another vault, MPE unpins itself)... the whole next.js thing seems silly as well, the whole idea of being a VSCode extension is to use an existing working editor

I'm not worried about it though, as long as my notes are in a MD wiki format, they'll be portable with minimal conversion (if Dendron moves in a direction I don't want to go)... I very much like what I'm seeing (except for all the bugs in MPE, but like I said, I'm hitting pause on that piece, at least for now)

**Comment by kpathakota** [comment]
@Gargoth - sorry for the late weigh-in here but this should be possible with a simple settings change: 
> Markdown-preview-enhanced: Single Preview

Make sure to *uncheck* that setting. If you don't, it will default to only opening the editor and leaving the preview. If you uncheck it, it'll keep opening previews for each link you click. Hope that helps, let me know if you think there needs to be anything else done here.
