### ISSUE TITLE
Refactoring a hierarchy resets dendron.yml, resetting previously configured vaults

### ISSUE THREAD

**Issue by iterating** [dendronhq/dendron#529]
Refactoring a hierarchy resets dendron.yml, resetting previously configured vaults

## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Refactoring a hierarchy resets dendron.yml, resetting previously configured vaults

## To Reproduce

Add several vaults
Create a hierarchy within a vault
Refactor.rename a hierarchy

## Expected behavior

The hierarchy is refactor.renamed without changing the dendron.yml list of vaults

## Screenshots

Before refactor: 
![image](https://user-images.githubusercontent.com/6834401/110680922-1013bc00-818e-11eb-8a31-41a6a00b218f.png)
After Refactor:
![image](https://user-images.githubusercontent.com/6834401/110681006-29b50380-818e-11eb-8116-de7943215f7e.png)

## Desktop (please complete the following information)

- OS: Windows 10
- Version: 10.0.19042 Build 19042

## Dendron Log file

[2021.3.10.error.refactor→changed dendronyml.log](https://github.com/dendronhq/dendron/files/6118205/2021.3.10.error.refactor.changed.dendronyml.log)

**Comment by kpathakota** [comment]
@iterating - this was happening a while ago before we added multi-vault support to refactor. Now, it shouldn't be doing this (hasn't happened to me in ages). Could you let me know if this is still happening for your specific configuration?
