### ISSUE TITLE
Using a link alias inside a table breaks the link and adds new column

### ISSUE THREAD

**Issue by Gargoth** [dendronhq/dendron#531]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [x] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Using link aliases when linking notes includes the pipe character ('|'), which makes it incompatible with tables. Instead of making an alias for the link, it will instead create a new column when placed inside a table, breaking both the table and the link.

## Describe the solution you'd like ##

It would be great if links inside tables can be detected which would stop the pipe character from making a new column. An alternative solution would be to have an alternate way of creating link aliases which does not include the use of the pipe character so that it does not conflict with the markdown syntax for tables. Thanks and best of luck!

## Additional context ##

![image](https://user-images.githubusercontent.com/51285956/110745594-73791900-8276-11eb-928a-2c36c9f7fc65.png)

**Comment by kevinslin** [comment]
Thanks for the issue. This is in our backlog and is a dup of #408 so will close this in favor of that. pleas upvote that issue to help me prioritize :)
