### ISSUE TITLE
<a> textwrap

### ISSUE THREAD

**Issue by maxkrieger** [dendronhq/dendron#535]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Long links don't wrap around page size in the rendered vault, resulting in overflowed horizontal space.

## To Reproduce

Make a really long link, publish it, resize browser window.

## Expected behavior

Links wrap around and make a newline.

## Fix

The `just-the-docs` CSS applies
```css
.main-content a {
...
  white-space: nowrap;
}
```

Disabling this line in the inspector fixes the issue. Not sure if there's a reason it was there in the first place. Another CSS rule one could try to override this is `word-wrap: break-word`.

**Comment by kevinslin** [comment]
Thanks for the digging. This fix will go out in tomorrows release :)

**Comment by kevinslin** [comment]
has been shipped in 0.33
