### ISSUE TITLE
 Renaming/refactoring note hierarchies edge cases

### ISSUE THREAD

**Issue by maxkrieger** [dendronhq/dendron#536]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Not sure if this is reproducible but it's happened twice for me: refactor hierarchy doesn't apply the refactor to the "parent" note. So for regex `x\.parent` ->  `grandparent.parent`:  `parent.A`, `parent.B`, `parent.C` get changed to `grandparent.parent.A,B,C` but parent itself isnt changed to grandparent.parent. Instead, a new note called grandparent.parent is created, and the original parent is kept in-place.

in outline form:
- x
  - parent
    - A
    - B
    - C
- grandparent

turns into
- x
  - parent
- grandparent
  - (BLANK) parent
    - A
    - B
    - C

(this is where a direct manipulation hierarchy UI would be handy, I do these sorts of hierarchy refactors a lot as my ontology expands)

---

ALSO

if I make a page `test`, then rename it to `foo.test`, I'd expect `foo` to be created as well if it didn't already exist. It isn't (at least according to cmd-L), and when I try to create it (cmd-L, foo, enter), it throws an error:
```"ctx":"parseTree","err":{"status":"unknown","msg":"","payload":"{\"msg\":\"no childNote found: 1bfac82f-d187-4591-a654-eef2d587ee0f, current note: 940ad93a-2b54-497e-ab18-335879950834\",\"fullDump\":```

**Comment by kpathakota** [comment]
Hi @maxkrieger - sorry for the delay. I wasn't able to repro this completely though I do see some of the same rough edges you did.  

For me - going from test -> foo.test didn't create  foo (and didn't recognize it as a stub). However, I was able to manually create it no problem. 

Also the direct manipulation for refactor worked fine. I think what you're doing is okay but the regex you specified will make sure you don't catch the parent (you've got the \. which is checking for a period). I just modified it so it's `parent -> grandparent.parent` and it did the right thing and refactored the parent as well. 

Let us know if you're still running into these issues.
