### ISSUE TITLE
Lists with more than one level in a referenced note display as only one level in the referencing note.

### ISSUE THREAD

**Issue by absconditus87** [dendronhq/dendron#537]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug

I have a new problem in that lists with more than one level in a referenced note display as only one level in the referencing note.

For example,

- level 1
    - level 2
- level 1
    - level 2

in the referenced note would display as:

- level 1
- level 2
- level 1
- level 2

in the referencing note.

## Expected behavior

A bullet list like:

- level 1
    - level 2
- level 1
    - level 2

in a note, should display like

- level 1
    - level 2
- level 1
    - level 2

when referenced, and not like

- level 1
- level 2
- level 1
- level 2

## Desktop (please complete the following information)

- OS: Windows 10

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kpathakota** [comment]
@absconditus87 - I just took a look at this and it's no longer repro'ing. Could you let me know if you're still seeing the issue on your end?
