### ISSUE TITLE
Site preview doesn't pick up changes made until vs code is restarted

### ISSUE THREAD

**Issue by Neurrone** [dendronhq/dendron#539]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The site preview command doesn't appear to pick up changes made since the last time the site was previewed until a full restart of vs code.

## To Reproduce

1. Create a new workspace
2. Use the site preview command and check that the site opens at localhost:8080. In particular, go to the quickstart link under the root note and notice that the dendron.welcome.md doesn't appear as a child at the bottom because of the `nav_exclude: true` in the frontmatter
3. Click cancel on the notification to cancel the preview. Now, comment out `nav_exclude: true` in dendron.welcome.md and save the file
4. Run the site preview command again, and go to the quickstart page. Notice that its child did not get listed even though the frontmatter has already been updated
5. Restart Vs Code and reopen the workspace. Run the site preview command again and this time, the child gets listed correctly.

## Expected behavior
Running site preview always renders based off the latest state of the workspace

## Desktop (please complete the following information)

- OS: Windows 10 2004
- Browser Firefox
- Version 86

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by Neurrone** [comment]
A more straithgforward way to reproduce this is to simply add more text to an existing note. Cancel the preview then rerun the command to see that the preview does not reflect the changed note until a Vs Code restart

**Comment by kpathakota** [comment]
Note that the referenced issue (#640) Also has logs.

**Comment by bachmeil** [comment]
This may or may not help identify the bug, but there's a better workaround than constantly restarting VSCode.

1\. In a terminal: `dendron buildSite --serve true`

2\. Leave that running. Make a change and rebuild the site inside the VSCode terminal - I set it up as a task for convenience. `dendron buildSite --wsRoot [dir]`.

3\. You can then preview the updated site by reloading it in the browser.

This approach must build the site differently than the Site Preview command.

**Comment by bachmeil** [comment]
> This approach must build the site differently than the Site Preview command.

After looking at the source, they site seems to be built the same either way. The difference is that my command uses the eleventy server but the Dendron site preview uses [the server in here](https://github.com/dendronhq/dendron/tree/master/packages/api-server).

**Comment by kevinslin** [comment]
Closing since this refers to our legacy publishing. please re-open a new issue if this still applies in our new publishing stack: https://github.com/dendronhq/dendron/issues/645
