### ISSUE TITLE
Wiki link navigation

### ISSUE THREAD

**Issue by alexisargyris** [dendronhq/dendron#54]
**Describe the bug**
Navigate to wiki links fails.

**To Reproduce**
1. Select one of the available options in the wiki links popup.
2. It gets inserted with the ".md" extension.
3. Attempt to navigate to the referenced file.
4. Dendron looks for file "xxx.md.md", fails to find it and offers to create it.

**Expected behavior**
Navigate to the referenced file.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 83

**Comment by kevinslin** [comment]
This has been updated in the latest version of Dendron (0.3.44). If you upgrade now, links will be created without the extension. Also, piped wiki links `[[foo | bar.md]]` will now work as expected :)
