### ISSUE TITLE
Markdown Export Pod

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#541]
## Context

Dendron recently launched the ability to [export to plain markdown](https://wiki.dendron.so/notes/13c4a608-0a32-4c62-9c7e-2b7f9f2d18bf.html#export). This is still an experimental feature and we are collecting feedback on how to best implement this. 

## Proposal

This issue is to collect feedback and additional usecases for the export feature. Please reply in the comments in the following format:

## Sample Feedback
- Feature: Support exporting assets 
- Use cases: GitBook, Typora, etc.

**Comment by buxel** [comment]
- Feature: control what is exported, similar to publishing
- Use cases: i'd like to publish parts of my vault to our team's DevOps Wiki
