### ISSUE TITLE
Support for arguments in dendron commands

### ISSUE THREAD

**Issue by vicrdguez** [dendronhq/dendron#544]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the solution you'd like ##

Something that will be really useful to unleash more workflows and avoid friction with Dendron would be the possibility of creating new shortcuts with Dendron commands that can accept **arguments**. This will allow for example the following.
- I'm on `customer1.meetings` and I want to start a new date-formatted note to write during a meeting.
  - I hit a keyboard shortcut and I create an scratch/journal note under that hierarchy, ending up with something like `customer1.meetings.2021.3.15`
- I'm on an arbitrary note and I come up with an Idea or just someone pings me up on chat to remember something.
  - I hit a keyboard shortcut and a new scratch note is created under the `scratch` hierarchy, ending up with `scratch.2021.3.15`

Another thing this could be applicable is for the _selection extract_ and _selection to link_ features, so you can have different keybindings for each of them depending on what do you want. 

## Additional context ##
An example of the config I mean. This is a keybinding configured for the **wichKey** extension:
```json 
    {
      "key": "s",
      "name": "Search...",
      "type": "bindings",
      "bindings": [
        {
          "key": "T",
          "name": "Todos",
          "type": "command",
          "command": "search.action.openNewEditor",
          "args": {
            "query": "(- \\[ \\] \\w+)",
            "triggerSearch": true,
            "focusResults": true,
            "regexp": true,
            "contextLines": 0
          }
        }
      ]
    },
```
With this I can trigger vscode search for all my open todos, and jump directly to the results to navigate them with a single binding

**Comment by kevinslin** [comment]
Thanks for the issue. Will add it to our backlog.

**Comment by kpathakota** [comment]
This has been implemented: https://wiki.dendron.so/notes/ad270a7d-2aed-4273-8319-eb6536e38b29.html#value
