### ISSUE TITLE
Hash sign for tag does not appear in Preview

### ISSUE THREAD

**Issue by kzilla-git** [dendronhq/dendron#549]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [x] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Hash sign for tag **does not** appear in the Markdown Preview Enhanced as shown in the attached files.

![image](https://user-images.githubusercontent.com/12721315/111499614-203d1580-8711-11eb-9c38-39afb10e7ea2.png)
![image](https://user-images.githubusercontent.com/12721315/111499637-259a6000-8711-11eb-9ea8-81049a251bde.png)

## To Reproduce

1. Create a tag with a label.
2. Open Markdown Enhanced Preview window.

## Expected behavior

A hash sign show appear before the tag label in the Preview window.

## Desktop (please complete the following information)

- OS: [Windows 10]
- Browser [Chrome]
- Version [Dendron version 0.33.0]

**Comment by kpathakota** [comment]
Is this a place we can simplify when moving to the unified preview (#643). Not sure what the scoping would be on this one @kevins8

**Comment by AleksueiR** [comment]
The hash sign does appear in V2 preview. Since V1 preview is being deprecated, I think this could be closed.

**Comment by aleksey-rowan** [comment]
The hash sign does appear in V2 preview. Since V1 preview is being deprecated, I think this could be closed.
