### ISSUE TITLE
Dendron is fucking great. (Testimonial, not sure what title should I put lol)

### ISSUE THREAD

**Issue by imalightbulb** [dendronhq/dendron#551]
# Testimonial

As one of the cofounder of The Productivists and a note taking tool hunter, I found it hard to control myself to not get my hand dirty in front of new shiny tools. I was frequently changing my tools without a fixed workflow in the early days of stepping into the productivity and note taking world, it is just great to see that so many cool guys are building tools to make knowledge management a pleasure and more efficient. I met Dendron at the time that I was in a chaos state using different note taking apps like Roam, Obsidian, Evernote, etc and had been sticking with it for a couple months now. I have also tried other tools meanwhile as well but eventually I always turn my head back to Dendron.

Dendron is: 
- [x] open source
- [x] build your own workflow
- [x] write, store and publish
- [x] good community and support 
- [x] cool guys in the core team
 
which suits my taste (**a lot**). So to speak, working my notes inside dendron is a pleasure as well. Dislike other note taking apps, in Dendron both hierarchy and linking is provided and you can combine them according to your likings. Referencing to [this article](https://nesslabs.com/how-to-choose-the-right-note-taking-app) from Nesslabs, Dendron fits both **Gardeners** and **Librarians** by combining the power of _hierarchy, linking and publishing_. Garderners can just ignore the hierarchy and do the linking while Librarians can focus on the hierarchy through the naming of the notes with each hierarchy separated by periods `.` . The `C-l` lookup feature is absolutely great too. If you are in between both categories (like me), then Dendron is definitely your first choice for hybrid workflows. 

Publishing notes is a pleasure as well (finally) by [managed publishing](https://wiki.dendron.so/notes/ae4a0c98-e2ea-47e0-8a20-016eba3424be.html) and you can directly publish your notes after hosting them on github (of course you can make it private too I think) instead of rewriting them and publish them as a website. **Everyone can build their second brain or wiki.**

I store everything in Dendron now and I know it's secure and they're simply plain text markdown files so no one knows (and cares) if I store anything personal or not. Although Dendron is not perfect (yet) and have some room of improvement, it suits my needs personally and these issues will eventually be solved by cool guys in the team or in the open source community. 

If you think Dendron is interesting, just give it a try and start building your second brain.
 
That's all I want to say and I apologize for the profanity in the title if you feel offended. This is my first time writing testimonial btw, thanks and feel free to let me know if it's too lengthy lol @kevins8.  

Lightbulb, Student and Researcher.

**Comment by tallguyjenks** [comment]
HAHA i love your exhuberance @imalightbulb 🤣

**Comment by kpathakota** [comment]
Lol incredible energy @imalightbulb. Love it. Updated testimonials:  https://wiki.dendron.so/notes/89bbe884-9cab-48fd-8cca-393754d18487.html

**Comment by imalightbulb** [comment]
Thanks guys! 
@kpathakota it has been created [here](https://wiki.dendron.so/notes/4ad7ee77-86c3-4a01-a525-14e7d7f8acad.html) so I'll maybe create a pull request to delete it

**Comment by kpathakota** [comment]
Oh good catch - fixed.
