### ISSUE TITLE
Dendron.Is.Powerfully.Unique

### ISSUE THREAD

**Issue by tallguyjenks** [dendronhq/dendron#552]
# Testimonial

Dendron stood out to me after a good explanation from the founder, the dot notation hierarchies is a unique approach to appeal to both camps of freeform and rigid hierarchical organization of information. It's a very powerful concept I've barely scratched the surface with but see application opportunities in a variety of more rigid contexts such as business, and government.

Great work!

Bryan Jenks, Information Technology Associate, Covered California, @tallguyjenks

**Comment by kpathakota** [comment]
Much appreciated @tallguyjenks - updated testimonials: https://wiki.dendron.so/notes/18610562-e4a0-4730-b15f-0d3f84eea105.html
