### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by chrisjm** [dendronhq/dendron#555]
# Testimonial

We're always looking for feedback and stories on how our users are using Dendron. 
If Dendron has helped you, please consider submitting a testimonial and help us grow 🌱

I've been using Dendron exclusively for my daily journal and notetaking since last week. Now that I've learned about PARA and figured out the hierarchy that best works for me, I'm absolutely loving it! It's making me feel better about getting things out of my head and organized in a way so that I can easily find them again. While it took me a couple of days to figure out the best workflow and transfer my past notes, I'm now moving faster and able to create, update, and find notes quickly.

Chris J Mears, Software Engineer, Carevoyance, @chrisjm

**Comment by kpathakota** [comment]
Thanks a bunch @chrisjm! Updated in testimonials: https://wiki.dendron.so/notes/02d6e57d-e097-428c-8564-72a943fcf38e.html
