### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by matthewbellringer** [dendronhq/dendron#556]
# Testimonial

I've been using Dendron for a few months now and I'm hugely impressed. It's a great idea and Kevin's developing new features for it all the time. It has an active, engaged community and is growing rapidly. I really appreciate the open philosophy behind it, having got stuck in far too many proprietary note-taking systems in the past. I'm using it not only to organise my private notes but to publish on the internet (https://iaq.matthewbellringer.com) and to collaborate with others.

There's a bit of a learning curve, but if you're used to VS Code and Markdown it's not too steep. It's very easy to get started though, like any tool, you'll want to dedicate a bit of time to getting the most out of it.

Matthew Bellringer, Social Innovationist and Founder, Meaningbit LTD.

**Comment by kpathakota** [comment]
Thanks @matthewbellringer! - updated the testimonials page - https://wiki.dendron.so/notes/fe51b6a5-b0ac-4b8e-9045-2de4f1f8db11.html
