### ISSUE TITLE
Came to tinker, stayed to garden.

### ISSUE THREAD

**Issue by buxel** [dendronhq/dendron#559]
# Testimonial

We're always looking for feedback and stories on how our users are using Dendron. 
If Dendron has helped you, please consider submitting a testimonial and help us grow 🌱

Dendron has given me the opportunity to have a one-stop place for all my notes, random thoughts and project planning right where i feel at home - in VSCode. To anyone feeling overwhelmed by planning and structuring everything from the start: just don't. Simply start noting down things that are important to you and patterns will emerge. Refactoring is easy.

Kevin is such a welcoming and open-minded guy and his professionalism and transparency in handling Dendron impressed me greatly. 9 out of 10 feature suggestions i had after using Dendron for a while, he already had in mind or even planned for a milestone.

I use Dendron mostly to manage multiple projects to keep track of meeting notes, TODOs, planned features and sharing all of this with my colleagues.

Chris Na, Tinkerer/Software Architect

**Comment by kevins8** [comment]
Thank you for the kind words Chris :)
Have included your testimonial here:
https://wiki.dendron.so/notes/c8c2dda3-cce1-4ecd-828b-f24cc2e8002a.html

**Comment by kpathakota** [comment]
Landing page updated. Thanks Chris!
