### ISSUE TITLE
Design Backlink Support

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#57]
## Context

When creating new notes in Dendron, it's useful to automatically create backlinks between the newly created note and the original note. This issue is to propose and gather feedback on auto backlinking newly created notes.

## Scope

There are multiple points at which Dendron can create a backlink. A few examples below:
- during Lookup when creating a new note
- when using `[[wiki-links]]` to go to a note that does not exist
- when creating a [journal note](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.topic.special-notes.md#journal-note)
- when creating a [scratch note](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.topic.special-notes.md#scratch-note)

## Backlink Creation

Backlinks can be created in a few different ways and in a few different places:
- How
    - 1. manually copying a link (link copied to clipboard)
    - 2. add a link to the frontmatter
    - 3. add a link to the end of the document in a special `# Links` section
    - 4. add a link to the current position in the document
- Where
    - A. adding a link to the [domain](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.concepts.md#domain) of the current hierarchy
    - B. adding a link to the current note
    - C. adding a link to a entirely new domain

## Proposal

Note that numbers and letters will be used as abbreviations. `eg: (2, A) = automatically add link to the frontmatter to the domain of the current hierarchy`

### loookup
- default: nothing
- configurable override:
    - (1)
    - (2, [A|B|C])
    - (3, [A|B|C])

### wiki-links
- default: nothing (a link is already created by nature of having a wiki-link in the original note)
- configurable override:
    - (1)
    - (2, [A|C])
    - (3, [A|C])

### journal note
- default: (1)
- configurable override:
    - (2, [A|B|C])
    - (3, [A|B|C])

### scratch note
- default: 
    - if text is selected, turn text into a link
    - otherwise, (4, B)
- configurable override:
    - (2, [A|B|C])
    - (3, [A|B|C])

**Comment by alexisargyris** [comment]
This is a matter strongly dependent on the use case(s) each user has in mind. Personally, I favour the least automation possible and making it very clear that an automation is actually in place whenever deciding to go for it. Why? During the last few months a new notes management app/framework appears almost weekly. Some contain just one good idea, while others not even that. Still, there are already 4-5 options of considerable sophistication (note: free for personal use all of them, currently). So, given that, what's the point of one more open source attempt? Here are some suggestions:

- Data ownership (i.e. no cloud uploading)
- Configurability (i.e. no bloatware, load only the features that are of interest) 
- Control (i.e. provide users with all necessary information and tools but only minimum hand holding)

As a result, I vote for prioritizing the development of the underlying, core functionality (e.g. schemas, variables, wiki/back links, tags, etc) and letting users free to decide if they need automations and/or higher-level features such as tables of contents, journal notes, etc.

**Comment by kevinslin** [comment]
That's fair. The reason we rolled back the auto-backlinking was because it was too closely tied to a particular workflow. As for your points about **data ownership, configurability, and control**, we are on the same page :) 

As for priorities, that's laid out in our [roadmap](https://github.com/orgs/dendronhq/projects/1). We also now have a [roadmap channel](https://discord.gg/HzkFcs) in the Dendron discord to discuss prioritization.

**Comment by kpathakota** [comment]
We have backlink support in Dendron built into the pane. Closing this old issue out.
