### ISSUE TITLE
Feature Request/Idea - Visual Note Hierarchy

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#570]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [X] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [X] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [X] Hierarchy
- [X] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

This is less of a request and more of an idea, as I am not sure how best this might be achieved in Dendron, or if it is even something worth pursuing. That said, I do not think the idea entirely without merit, and thought there was no harm in at least putting it out there for consideration.

Dendron is "The **hierarchical** note taking tool that **grows** as you do!", and though it does include tools to edit hierarchies by level, there are less tools to view the structure of a vault on the whole. At present, the only two ways to "see" a vault's hierarchy in its entirety are the "Dendron Tree View" and the "Show Note Graph" command. The Tree View is locked to the Action Bar and cannot be expanded. It is also static in how it presents its content and does not allow for customization. The Graph View provides the "20,000 foot view of the structure", but unfortunately it struggles more the larger the vault grows. There is no way to focus in on particular branches, and because of how the graph arranges itself, unrelated hierarchies can be presented next to one another even without any actual links between their content.

The idea I would like to put forward is that Dendron have the option to view a vault's hierarchical structure as a structured hierarchy. Possibly this could be achieved through a rework of the Graph View, or through the introduction of a new feature, something along the line of a "Show Note Hierarchy" command. A very rudimentary implementation of this option would be to have the Tree View or something like it open in its own tab. This could then be expanded upon with something like a "Show Note Hierarchy [level of hierarchy]" command, to allow users to focus on whichever level they need to work with. An even greater expansion—if possible—would be to have note previews in this view, in the same manner as with wiki links. Users would then be able to very quickly "view" all of the notes on a particular level. 

(Now that I am taking the time to write all of this out, such functionality would also grant Dendron the capabilities of a simple outliner.)

I realize the suggestions above are all geared much more towards viewing hierarchies than editing them, but I do think this would be in service of Dendron's principle of "retrieval over insertion". As someone who has spent years feeling as though he was making notes, then throwing them in a bin never to be seen or used again, this was my main draw to Dendron. 

Possibly all of what I have suggested can already be achieved with Dendron's current toolkit, and I am simply too much of a clod to have realized. I have only been using Dendron as my primary note taking tool for the past two months now, and I am hardly an expert with the extension or VS Code. Still, it has cost me nothing but time to write this up, and if all that comes of this issue is another Dendron user telling me how all of this is already doable and explaining what I have missed, then I will still consider that a win. 

Thank you for your time.

**Comment by kpathakota** [comment]
I don't think what your asking for can be done with the current setup. I really like the idea of structuring the graph view so that like-elements are organized closer together (as opposed to now...). Also seems like you'd want #107 since that involves a performance improvement for graph view.

**Comment by micharris42** [comment]
Funnily enough, I gave a listen to episode 620 of the TWiT podcast "FLOSS Weekly" today. The week after they had Kevin on, they had Jeremy Ruston, the creator of TiddlyWiki, and because it had only been a week, they asked if he was familiar with Dendron. And his response was quite interesting:

>Dendron includes the graph feature that is very popular in Roam, which is—the old ones amongst us all remember the Brain from, again that's a 2005 period. Roam is a different era, it doesn't do that hyperbolic stuff quite the same, but it's very much the same idea and I feel that that is a—it's something that we have quite a primal desire to see, so a lot of us see our thoughts as little blobs of things with links in between them and we'd like to see those links. I actually am firmly of the opinion that lines and box diagrams are cognitively useless, unless they've been manually laid out. So that, all I'm saying, if you take twenty-five nodes and the computer lays them out, obviously thinking about not crossing lines or something, our eyes, trained on the savanna of Africa thousands of years ago, all we see are the patterns. So we see three things lined up and we think that there's a relationship between them, but that's just an artifact of the layout diagram. So I feel that that kind of extraneous structure that human brains can't help seeing just overwhelms any insight that you would get from that sort of graphical view. So my own feeling is more that the way to experience those links is not by standing back and seeing a graph, but it's by traveling through them. So I'm more interested in that kind of—so TiddlyWiki goes to a lot of trouble that there is a mode; if you put it into zoom, in story view mode, when you click on the link it actually, the thing you're on zooms out and it turns out that the word you clicked on turns into the title of the thing that you clicked on. So I'm interested in that sort of smooth transition to make it feel like the information is always there and you're uncovering it, sort of thing. And that I think is very different then this sort of, this God-like view where you're looking down on the railway track and you're seeing—let's say my personal notes have thousands of entries and there's no conceivable graph that could give me any insight into it. You'd get more insight searching for random words to be honest. 

My poor ability to transcribe aside, I think this would have been a very different issue if I had had the above in mind when I wrote it up. That my desire for a "Visual Note Hierarchy" is one born of the stone age part of my brain rather shines a new light on the whole thing. 

Obviously, Dendron should not be trying to ape TiddlyWiki, but I do think Jeremy makes a good point here, and as the Dendron graph view is still in its early days, now is exactly the time to make sure it does not fall into the trap he describes.

**Comment by kpathakota** [comment]
Yes, this actually reinforces my thinking too that a fully described graph-view (where each note-link is visualized) is not super useful (possibly just aesthetically pleasing). A hierarchical view which makes it easy to see how you've got things arranged and maybe re-arrange things could be really interesting. Closing for now
