### ISSUE TITLE
schema graph doesn't work

### ISSUE THREAD

**Issue by af4jm** [dendronhq/dendron#571]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

the command to open the schema graph always errors, it does not open

## To Reproduce

Issue command to open schema graph, receive error shown in Screenshots section below

## Expected behavior

schema graph should open

## Screenshots

![image](https://user-images.githubusercontent.com/849948/112413899-70127280-8cf7-11eb-886f-271552a7a235.png)

## Desktop (please complete the following information)

- OS: Windows
- Version latest (1.54.3 & 0.34)

## Additional context

I tried removing my second vault & restarting VSCode, and the issue still occurs, so it seems unrelated to multi-vault

## Dendron Log file

this one shows in the extension log, not the Dendron log...

[2021-03-24 23:10:24.023] [exthost] [error] TypeError: Cannot read property 'forEach' of undefined
	at parseGraphV2 (c:\Users\jfm\.vscode\extensions\dendron.dendron-markdown-links-0.6.19\dist\extension.js:293:3111)
	at c:\Users\jfm\.vscode\extensions\dendron.dendron-markdown-links-0.6.19\dist\extension.js:293:2713
	at Array.map (<anonymous>)
	at p.<anonymous> (c:\Users\jfm\.vscode\extensions\dendron.dendron-markdown-links-0.6.19\dist\extension.js:293:2678)
	at Generator.next (<anonymous>)
	at o (c:\Users\jfm\.vscode\extensions\dendron.dendron-markdown-links-0.6.19\dist\extension.js:293:1669)
	at processTicksAndRejections (internal/process/task_queues.js:97:5) dendron.showSchemaGraph

**Comment by ryan-p-randall** [comment]
I'm also getting the same `Command 'Dendron: Sync Schema Graph' resulted in an error (Running the contributed command: 'dendron.syncSchemaGraph' failed.)` message.  

I'm using Dendron 0.35 on Mac 10.14.16, in VSCode 1.54.3. Not sure if this is in any way related to issue #592 but I think they started happening around the same time.

**Comment by kpathakota** [comment]
This looks like the windows specific path bug @kevinslin. Did you try reloading the index afterwards @ryan-p-randall - did that fix it or it persisted?

**Comment by ryan-p-randall** [comment]
Since I first noticed that error, I've reloaded the index, tried Dendron Doctor, reloaded the window, closed & reopened VSCode entirely, restarted my computer, etc… and I still get that error. I actually don't know if I've ever had the note graph work—I first tried it only about a week ago!

`Sync Schema Graph` and `Show Schema Graph` both give me that error. But I can use `Sync Note Graph` and `Show Note Graph` without any errors.

**Comment by khramoff** [comment]
I'm unable to use all of the following: `Sync Note Graph`, `Sync Schema Graph`, `Show Note Graph`, `Show Schema Graph`.
I'm using Manjaro, along with VS Codium.

Versions:
VS Codium: 1.54.3
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.26-1-MANJARO
Dendron: 0.38.0 
Dendron Markdown Links: 0.6.19.

Are there any updates or workarounds?

**Comment by kpathakota** [comment]
Yeah, I'm going to chalk this up to the whole system needing an overhaul soon. We're funneling most of these in through #615 (there is talk of switching how we store graph data + how we visualize). Tagging this as duplicate and closing. I'm able to repro this as well (I think it's once you hit a certain notes threshold and performance issues start.
