### ISSUE TITLE
Dendron should not rewrite files when it's reading them

### ISSUE THREAD

**Issue by af4jm** [dendronhq/dendron#572]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug

Dendron writes a lot of files that it should only be reading...

1. On launch it rewrites the code snippets & workspace files (and ignores .editorconfig & VSCode settings while doing so)
2. When the Doctor modifies a files front matter (either in the UI or from the command line), it also parses and reformats the entire MD file, often breaking the Markdown in the process (I've seen it wrap pieces of a bullet list in ```, it changes indenting, removes escapes which, in some of my MD files, breaks external links)

the only place this works correctly is updating the "updated" field in front matter

On launch, workspace & snippet files should be read, not written to... if a setting needs to be added due to an extension update, it should be added at the end without touching the formatting of the rest of the file

When YAML is edited, the Markdown should NOT be parsed, everything after the `---` that ends the frontmatter should be read & written as a single string (in other words, if I diff a file from the Doctor's changes, it should be impossible for there to ever be any differences outside of the front matter)

## Desktop (please complete the following information)

- OS: Windows
- Version latest 1.54.3 & 0.33 (but I've been noticing this behavior since I started using Dendron, which was 0.31)

**Comment by aleksey-rowan** [comment]
Partial duplicate: https://github.com/dendronhq/dendron/issues/524

**Comment by aleksey-rowan** [comment]
> Dendron currently will auto-format notes during Rename and Refactor operations when links inside a note need to be replaced

from https://github.com/dendronhq/dendron/issues/278#issuecomment-712453136

**Comment by kevinslin** [comment]
this is fixed with 0.46 release
