### ISSUE TITLE
Better onboarding UX

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#574]
We need to make it easier for a new person to use Dendron. Possibly: 
- Pre-populate common use cases. 
- Better onboarding docs? 
- A notes-based tutorial? Something like Scrivener?

**Comment by kpathakota** [comment]
Decided to ask a question when someone downloads Dendron "Is this your first time using Dendron? Would you like to go through a guided tutorial.": 
- If yes, link them to the note https://wiki.dendron.so/notes/784b8d5e-58eb-4e3e-98b0-8ed1690abc74.html
- If no, just the quickstart guide.

**Comment by snuup** [comment]
I just installed Dendron, looks pretty tasty to me, but have to second that the "Quick Start" just is no Quick Start. 

Quickstart should be a demo of creating a simple knowledge base.

Lets see, maybe I find the time to do that.
