### ISSUE TITLE
Paste file (similar to paste image)

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#575]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Something I do often but encounter friction with is adding a new asset and linking to it immediately after. My current workflow is to paste the file into my assets folder and then type out the asset link wherever I want to reference it but this can be a bit laborious even with autocomplete when there's many files with similar names.

## Describe the solution you'd like ##

The paste image workflow should work for the generic paste file: https://wiki.dendron.so/notes/a91fd8da-6895-49fe-8164-a17acd8d9a17.html#copy--paste

**Comment by ddbrierton** [comment]
Ah, I searched before but didn’t find this ticket when I created #697. In that ticket though I sketched out a slightly different approach to the one described here — I hope it might be given some consideration ...

**Comment by kevins8** [comment]
Thanks for the ticket. We're planning on enabling this as a drag and drop
feature in our new tree view. See the work in progress rfc here:
https://wiki.dendron.so/notes/ba8cf4c5-6254-4eca-8072-8001ca5afda7.html

**Comment by kevinslin** [comment]
shipped in v43
