### ISSUE TITLE
Heading References with footnotes doesn't work

### ISSUE THREAD

**Issue by xypnox** [dendronhq/dendron#577]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [x] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Copying reference of a header with a footnote breaks for me.

For example for the header

```md
## Notes from Introduction to Zettelkasten [^1]
```

The broken reference is:
`![[thoughts.note-taking.zettelkasten#notes-from-introduction-to-zettelkasten-1,1:#*]]`

The manually edited reference that correctly works in the preview is: 
`![[thoughts.note-taking.zettelkasten#notes-from-introduction-to-zettelkasten,1:#*]]`

## To Reproduce

1. Create a reference link of a header with footnote. 
2. Paste the reference in another note.
3. The preview doesn't work.

## Expected behavior

The link should either remove the footnote section or the preview should detect the footnote and show the link correctly.

## Screenshots

This is the header with the footnote:
![2021-03-26-Fri-14-57_ns056697205](https://user-images.githubusercontent.com/25076171/112612556-1029e200-8e45-11eb-99aa-8fbb55db4538.png)

And the broken link generated with `Ctrl+Shift+R`:

![2021-03-26-Fri-14-57_ns402093051](https://user-images.githubusercontent.com/25076171/112612621-22a41b80-8e45-11eb-9f79-b8e575eb0302.png)

## Desktop (please complete the following information)

- OS: Linux, Manjaro
- Dendron Version: 0.34.0 

## Dendron Log file

Logs: https://gist.github.com/xypnox/f9b60f07370094330d5d5939b9f3d450

**Comment by kevinslin** [comment]
hmm, the reason your seeing this issue is because we do a slug match based on the header element. the footnote is a different element so it doesn't match on that. i think the proper behavior is to only copy the header element when generating the link

**Comment by kevinslin** [comment]
closing this in favor of #591 591
