### ISSUE TITLE
Dendron: Create Daily Journal Note' resulted in an error (command 'dendron.createDailyJournalNote' not found

### ISSUE THREAD

**Issue by jeffabailey** [dendronhq/dendron#578]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ X ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

I'm unable to create a daily journal file.

## To Reproduce

1. Cmd-Shift-P
2. Choose Dendron: Create Daily Journal Note
3. See the error below.

## Expected behavior

A new journal file to be created.

## Screenshots

![image](https://user-images.githubusercontent.com/776901/112662303-c1645400-8e14-11eb-9ae3-e5b1084886e0.png)

## Desktop (please complete the following information)

- OS: macOS
- Browser Chrome
- Version 10.14.6 (18G8012)

## Additional context

It was working fine in the past.

I already tried uninstalling and reinstalling the extension.

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

I get this error when trying to run this command.

![image](https://user-images.githubusercontent.com/776901/112662709-3cc60580-8e15-11eb-8768-81d860b81d85.png)

**Comment by jeffabailey** [comment]
Actually, no commands are working. I tried the lookup command, and it's also failing.

**Comment by jeffabailey** [comment]
I tried downgrading the Dendron extension, and it's still failing.

I ran it on a Windows machine, and it's working without issue.

Does it appear that the local state for dendron is broken since other extensions are working without issue?

**Comment by jeffabailey** [comment]
I created this directory and it's now loading after seeing this error.

**Error:**

```
abstractExtensionService.ts:718 Activating extension 'dendron.dendron' failed: ENOENT: no such file or directory, open '/Users/<Username>/Library/Application Support/Code/logs/20210310T143420/exthost1/dendron.dendron-markdown-links/dendron.log'.
```

**Remediation**

mkdir -p '/Users/<Username>/Library/Application Support/Code/logs/20210310T143420/exthost1/dendron.dendron-markdown-links'

Reload VSCode

It's working now, but it's a mystery as to why this would happen.

Could it be from user sync settings?

**Comment by kevinslin** [comment]
Hmm, this is strange. Usually you get that error because your not in a workspace (eg. https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#engine-not-initialized). can you run `>Diagnostics Report` and paste the output if you see this again?

**Comment by jeffabailey** [comment]
Yes, if I see the error again I'll run that command and paste the output.

**Comment by kpathakota** [comment]
HI Jeff, let us know if you're still seeing (otherwise this issue will auto-close in 7 days).
