### ISSUE TITLE
Syntax highlighting does not recognize Wiki-styled links.

### ISSUE THREAD

**Issue by gjroelofs** [dendronhq/dendron#579]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [x] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The textmate grammar file does not recognize the `[[<wiki-link]]` format and thus does not properly support syntax highlighting/coloring for it.

## To Reproduce

Create a note with a wiki-styled link, enable `Developer: Inspect Editor tokens and scope`, then over over the relevant syntax to see that the wiki-links aren't properly detected.

![image](https://user-images.githubusercontent.com/398630/112663211-d5ca4000-8e58-11eb-9f32-ef04733d072c.png)
Incorrect parsing.

## Expected behavior

I exped the wiki-styled links to be recognized as a separate scope, with the enclosing brackets marked as a beginning & ending scope for those links.

![image](https://user-images.githubusercontent.com/398630/112663258-e67ab600-8e58-11eb-80fa-fc3069d6eaa2.png)
Correct parsing of the links.

## Desktop (please complete the following information)

- OS: Windows 10 x64
- Version - Dendron 0.34.0

**Comment by gjroelofs** [comment]
Markdown Notes, with GPL v3, provides a syntax implementation which could be used as the basis for this: https://github.com/kortina/vscode-markdown-notes/blob/master/syntaxes/notes.tmLanguage.json

**Comment by kevinslin** [comment]
Thanks for the issue. Will be doing another sweep of our grammar files

**Comment by kevinslin** [comment]
this should be fixed in v52 of Dendron. please post here if not, otherwise this issue will auto close in 3 days
