### ISSUE TITLE
Option to remove Children links from root pages

### ISSUE THREAD

**Issue by cybermails** [dendronhq/dendron#581]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Currently, you can specify the name of the Children links in published sites by modifying the following configuration,
hiearchyDisplayTitle
    default: Children

However, it is not possible to disable showing the Children links altogether.

## Describe the solution you'd like ##
A config. option to turn off showing Children links altogether would be good to have.

**Comment by Harshita-mindfire** [comment]
Hello @kzilla-git This should be configurable with `enableHierarchyDisplay` config under publishing namespace. By default, this is set to true. Setting this to false will remove the Children links. Click [here](https://wiki.dendron.so/notes/H9PVMguPOuZ001tNYczlh/) for more info
