### ISSUE TITLE
Wildcard note ref causes formatting issues in lists of second and subsequent notes

### ISSUE THREAD

**Issue by nbartzokas** [dendronhq/dendron#582]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [X] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When a wildcard ref is used and its referenced notes contain lists, the second and subsequent notes will render incorrectly. The same can occur without wildcards, when two or more note refs occupy neighboring lines with no blank lines between. The formatting issue occurs in the second or any subsequence note, in each note's first list. If the incorrectly rendered markdown preview is converted to HTML, it shows a closing `</ul>` tag occurring too soon, before all the `<li>` tags are listed.

## To Reproduce

1. Create two notes, for example `todo.projectA` and `todo.projectB`
2. In each note, create a list with 3 items
3. In a new note, e.g. `list_all_todos`, use the wildcard reference `![[todo.*]]`
4. In the preview for this note, the list in `todo.projectB` will render incorrectly

## Expected behavior

All pretty refs should render bulleted lists the same way.

## Screenshots

![image](https://user-images.githubusercontent.com/220913/112674880-d5bc4700-8e3c-11eb-9f6e-cc97951f1ef1.png)

## Desktop (please complete the following information)

- OS: Windows 10.0.19042 Pro
- VS Code 1.54.3
- Dendron 0.34.0

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
Yep, reproduced. Added to the backlog

**Comment by kpathakota** [comment]
This should be tackled with #643 (Unified Markdown preview).

**Comment by aleksey-rowan** [comment]
This doesn't seem to be happening in the V2 preview:

![image](https://user-images.githubusercontent.com/79934725/150710986-89cd8128-be88-4eb5-a419-8bb4ccccdc1b.png)

@nbartzokas could you please check if this is still an issue for you?
