### ISSUE TITLE
Include original hierarchy text in "Enter replace prefix" input box

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#583]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

- The `Refactor Hierarchy` command prefills the input box for hierarchies to match (when you have an active note opened), but gives you a blank input box for the next step.
- Unless you are starting with a completely arbitrary file name, you have some kind of hierarchy already going on with your notes.
- maybe you only want to refactor a subdomain
  - with a deep enough hierarchy, you are prone to make a typo and create a completely new branch of hierarchy.
- maybe you want to change the name of the leaf node.
  - you have nothing prefilled so you have to remember what the entire hierarchy string was, which is sometimes not that intuitive.

## Describe the solution you'd like ##

Pass the exact match string that the user started with in the command to the next input box where the user decides how it's going to be refactored.

## Describe alternatives you've considered ##
Keep it as is and just remember to select the match string and copy before proceeding to the next step

## Additional context ##

Illustration of the to-be case and why I think it is better to prefill the replace prefix input box:

case 1

1. I made a scratch note on productivity, but I didn't mean to do this. I wanted it in another domain.
![image](https://user-images.githubusercontent.com/1219789/112715179-3bceca00-8f22-11eb-8539-82a47fc6ff8a.png)

2. Replace prefix is already filled with the same hierarchy string.
![image](https://user-images.githubusercontent.com/1219789/112715324-e3e49300-8f22-11eb-9cc9-c57177bef13d.png)

3. I can navigate to the start of the text and fix the domain I want it to be in
![image](https://user-images.githubusercontent.com/1219789/112715364-14c4c800-8f23-11eb-8412-1bc91302465e.png)

case 2

1. I have a hierarchy of notes on different kinds of house plants I own.
![image](https://user-images.githubusercontent.com/1219789/112715404-5b1a2700-8f23-11eb-85f5-ecb1573ed07b.png)

2. I realize I need a more generic domain above `plants` so that I can take notes on tools and other miscellaneous that are related to plants but does not directly relate to a specific plant. I want to call it `botany`.
Since the `replace prefix` box is already filled with the string I'm starting from, I can just add domain inbetween `cerebrarium` and `plants`
![image](https://user-images.githubusercontent.com/1219789/112715498-d24fbb00-8f23-11eb-9863-c8ed004158e1.png)

3. Actually, I changed my mind. I want the domain to be `horticulture`. 
Easy! because I'm starting with `cerebrarium.botany.plants`, I can simply select `botany` and change it to `horticulture`.
![image](https://user-images.githubusercontent.com/1219789/112715562-370b1580-8f24-11eb-80f3-69befc581f95.png)

**Comment by kpathakota** [comment]
@hikchoi - great suggestion. I think it's a good community feature/an easy one to knock out.
