### ISSUE TITLE
Plugin looking for a (now) non-exsistent vault that isn't and wasn't in the workspace

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#585]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug
- I have a test vault that I initialized and used outside of my normal everyday vault. (The test vault is used when for dendron dev purposes)
  - It is in a separate location and does not share the workspace with my vault that I actually use.
- This test vault does not exist anymore, but I did get same errors when it existed.

Since 0.34 I intermittently see errors about the test vault not existing when I'm in my normal vault.

**Note that the error and diagnostics below are captured after my test vault has been removed.**

Error: 
>{"ctx":"d:run","err":{"status":"unknown","msg":"","payload":"{\"msg\":\"Cannot read property 'vault' of undefined\",\"stack\":\"TypeError: Cannot read property 'vault' of undefined\\n\\tat Function.getPathV4 (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:365:96855)\\n\\tat /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:100:186912\\n\\tat async B.pauseWatchers (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:76637)\\n\\tat async d.run (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:103556)\\n\\tat async /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:79775\\n\\tat async S._executeContributedCommand (/Users/hikchoi/Desktop/dendron-test/pvis.app/Contents/Resources/app/out/vs/workbench/serv...

<details>
<summary>Diagnostics </summary>
<p>
  ```
  # Plugin Logs
  {"level":30,"time":1616916097526,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
  {"level":30,"time":1616916097568,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/user-data/logs/20210328T094639/exthost1/dendron.dendron","logLevel":"info","extensionPath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0","extensionUri":{"$mid":1,"fsPath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0","path":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0","scheme":"file"},"storagePath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/user-data/User/workspaceStorage/b2372a0d485bd70a8a4f90469fd94856/dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/dendron.code-workspace","external":"file:///Users/hikchoi/Cerebrarium/dendron.code-workspace","path":"/Users/hikchoi/Cerebrarium/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault","external":"file:///Users/hikchoi/Cerebrarium/vault","path":"/Users/hikchoi/Cerebrarium/vault","scheme":"file"},"name":"vault","index":0}]}
  {"level":30,"time":1616916097569,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
  {"level":30,"time":1616916097577,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"}},"configMigrated":false,"msg":"read dendron config"}
  {"level":30,"time":1616916102422,"pid":15173,"hostname":"HikBookPro.local","name":"connector","ctx":"EngineConnector:init","msg":"enter","opts":{}}
  {"level":30,"time":1616916102423,"pid":15173,"hostname":"HikBookPro.local","name":"connector","ctx":"EngineConnector:createServerWatcher","msg":"enter","opts":{}}
  {"level":30,"time":1616916102437,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","dendron.defaultJournalAddBehavior":"childOfCurrent","dendron.defaultScratchAddBehavior":"childOfCurrent","files.autoSave":"onFocusChange","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.quickSuggestions":{"other":true,"comments":false,"strings":true},"editor.suggest.showSnippets":true,"editor.tabCompletion":"on","workbench.editor.showTabs":true,"breadcrumbs.enabled":false,"dendron.defaultLookupCreateBehavior":"selectionExtract","editor.suggest.snippetsPreventQuickSuggestions":false,"telemetry.enableTelemetry":false,"markdown-preview-enhanced.previewTheme":"none.css","markdown-preview-enhanced.codeBlockTheme":"atom-dark.css","markdown-preview-enhanced.renderRefWithOutline":false,"pasteImage.path":"${currentFileDir}/assets/images"},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}},"wsConfigMigrated":{},"msg":"read wsConfig"}
  {"level":30,"time":1616916102443,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.34.0","migratedGlobalVersion":"0.34.0","previousGlobalVersion":"0.33.0","previousWsVersion":"0.34.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.30","active":true},{"id":"dendron.dendron-markdown-links","version":"0.6.19","active":false},{"id":"github.github-vscode-theme"}],"vaults":[{"fsPath":"vault"}]}
  {"level":30,"time":1616916102444,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"startServer","logLevel":"info"}
  {"level":30,"time":1616916102450,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","msg":"post-start-server","port":51054}
  {"level":30,"time":1616916102452,"pid":15173,"hostname":"HikBookPro.local","name":"logger","ctx":"FileStorageV2","wsRoot":"/Users/hikchoi/Cerebrarium","vaultsv3":[{"
  ---
  :30,"time":1616938968281,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"project log|projects.pachypus-prep","mode":"note"},"msg":"enter"}
  {"level":30,"time":1616938968331,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","external":"file:///Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","path":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","scheme":"file"}}
  {"level":30,"time":1616938973281,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
  {"level":30,"time":1616938973567,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
  {"level":30,"time":1616938973570,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
  {"level":30,"time":1616938978326,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"d:run","msg":"pre-execute"}
  {"level":30,"time":1616938978327,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"Operculicarya Pachypus|cerebrarium.botany.plants.operculicarya.pachypus","mode":"note"},"msg":"enter"}
  {"level":30,"time":1616938978355,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/cerebrarium.botany.plants.operculicarya.pachypus.md","external":"file:///Users/hikchoi/Cerebrarium/vault/cerebrarium.botany.plants.operculicarya.pachypus.md","path":"/Users/hikchoi/Cerebrarium/vault/cerebrarium.botany.plants.operculicarya.pachypus.md","scheme":"file"}}
  {"level":30,"time":1616938983528,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","external":"file:///Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","path":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","scheme":"file"}}
  {"level":30,"time":1616938992648,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","external":"file:///Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","path":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","scheme":"file"}}
  {"level":30,"time":1616939003665,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-prep.md","reason":1,"msg":"enter"}
  {"level":30,"time":1616939003666,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1616938887217"],"msg":"update activeText editor"}
  {"level":50,"time":1616939007173,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"d:run","err":{"type":"r","message":"","stack":"Error: \n\tat d.run (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:103712)\n\tat async /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:79775\n\tat async S._executeContributedCommand (/Users/hikchoi/Desktop/dendron-test/pvis.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:103766)","status":"unknown","msg":"","payload":"{\"msg\":\"Cannot read property 'vault' of undefined\",\"stack\":\"TypeError: Cannot read property 'vault' of undefined\\n\\tat Function.getPathV4 (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:365:96855)\\n\\tat /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:100:186912\\n\\tat async B.pauseWatchers (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:76637)\\n\\tat async d.run (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:103556)\\n\\tat async /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.34.0/dist/extension.js:9:79775\\n\\tat async S._executeContributedCommand (/Users/hikchoi/Desktop/dendron-test/pvis.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:103766)\"}"}}
  {"level":30,"time":1616939040961,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"f:run","msg":"pre-execute"}
  {"level":30,"time":1616939040962,"pid":15173,"hostname":"HikBookPro.local","name":"dendron","ctx":"execute","opts":{}}
  ---
  # Server Logs
  ersion":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"}}}}
  GET /api/config/get?ws=%2FUsers%2Fhikchoi%2FCerebrarium 200 0.863 ms - 450 - 2
  {"level":30,"time":1616939002860,"pid":15173,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"config","msg":"get:enter"}
  {"level":30,"time":1616939002861,"pid":15173,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"config","msg":"get:ext","resp":{"error":null,"data":{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"}}}}
  GET /api/config/get?ws=%2FUsers%2Fhikchoi%2FCerebrarium 200 2.174 ms - 450 - 2
  POST /api/note/update 200 0.420 ms - 14 - 1196
  {"level":30,"time":1616939003716,"pid":15173,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"config","msg":"get:enter"}
  {"level":30,"time":1616939003729,"pid":15173,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"config","msg":"get:ext","resp":{"error":null,"data":{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"}}}}
  GET /api/config/get?ws=%2FUsers%2Fhikchoi%2FCerebrarium 200 16.836 ms - 450 - 2
  {"level":30,"time":1616939003980,"pid":15173,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"config","msg":"get:enter"}
  {"level":30,"time":1616939003980,"pid":15173,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"config","msg":"get:ext","resp":{"error":null,"data":{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"}}}}
  GET /api/config/get?ws=%2FUsers%2Fhikchoi%2FCerebrarium 200 0.649 ms - 450 - 2
  POST /api/note/getByPath - - ms - - - 136
  # Dendron Confg
  {"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"}}
  # Port
  51054
  ```
</p>
</details>

## To Reproduce

Not entirely sure if this is reproducable, but

1. set up and initialize a dendron vault.
2. set up another vault in a different location.
3. wait for the intermittent error to happen...?
4. try deleting the one you don't care about.
5. wait for the error again.

## Expected behavior

It doesn't happen.

## Desktop (please complete the following information)

- OS: MacOS Big Sur 11.0.1

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

omitting since this bumps the lenght of this issue over the max allowed characters 😄

**Comment by kevinslin** [comment]
this is because we have filewatchers that check if you add files outside of dendron and tries to index it. i've added checks in the latest release to only do this for files that are in dendron. let me know if you still see this issue

**Comment by hikchoi** [comment]
> this is because we have filewatchers that check if you add files outside of dendron and tries to index it. i've added checks in the latest release to only do this for files that are in dendron. let me know if you still see this issue

So far so good! let's give it a few more days and I'll let you know

**Comment by hikchoi** [comment]
It has happened again today, and I need to apologize for the inaccurate information given in this issue :(

This has nothing to do with the test vault I've created in a separate instance of VSCode. I have mistaken the path `dendron-test` for that test vault but in fact this path is where my portable installation of VSCode resides.

So to clarify, this is happening within one isolated instance of VSCode and Dendron.

<details>
<summary>Here is the diagnostics</summary>
<p>
# Plugin Logs
{"level":30,"time":1617502395034,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1617502395079,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/user-data/logs/20210331T070104/exthost1/dendron.dendron","logLevel":"info","extensionPath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0","extensionUri":{"$mid":1,"fsPath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0","path":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0","scheme":"file"},"storagePath":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/user-data/User/workspaceStorage/b2372a0d485bd70a8a4f90469fd94856/dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/dendron.code-workspace","external":"file:///Users/hikchoi/Cerebrarium/dendron.code-workspace","path":"/Users/hikchoi/Cerebrarium/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault","external":"file:///Users/hikchoi/Cerebrarium/vault","path":"/Users/hikchoi/Cerebrarium/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1617502395080,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1617502395089,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"},"initializeRemoteVaults":true},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1617502395115,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","dendron.defaultJournalAddBehavior":"childOfCurrent","dendron.defaultScratchAddBehavior":"childOfCurrent","files.autoSave":"onFocusChange","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.quickSuggestions":{"other":true,"comments":false,"strings":true},"editor.suggest.showSnippets":true,"editor.tabCompletion":"on","workbench.editor.showTabs":true,"breadcrumbs.enabled":false,"dendron.defaultLookupCreateBehavior":"selectionExtract","editor.suggest.snippetsPreventQuickSuggestions":false,"telemetry.enableTelemetry":false,"markdown-preview-enhanced.previewTheme":"none.css","markdown-preview-enhanced.codeBlockTheme":"atom-dark.css","markdown-preview-enhanced.renderRefWithOutline":false,"pasteImage.path":"${currentFileDir}/assets/images","workbench.editor.closeOnFileDelete":true},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1617502395132,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.35.0","migratedGlobalVersion":"0.35.0","previousGlobalVersion":"0.34.0","previousWsVersion":"0.35.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.30","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.19","active":false},{"id":"github.github-vscode-theme"}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1617502395133,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"startServer","logLevel":"info"}
{"level":30,"time":1617502395148,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"_activate","msg":"post-start-server","port":59386}
{"level":30,"time":1617502395150,"pid":31986,"hostname":"HikBookPro.local","name":"logger","ctx":"FileStorageV2","wsRoot":"/Users/hikchoi/Cerebrarium","vaultsv3":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1617502395151,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1617502400159,"pid":31986,"hostname":"HikBookPro.l
---
:"EngineConnector:tryToConnect","port":59386,"msg":"enter"}
{"level":30,"time":1617502403176,"pid":31986,"hostname":"HikBookPro.local","name":"connector","ctx":"EngineConnector:tryToConnect","msg":"connected","info":{"version":"0.35.0"}}
{"level":30,"time":1617502403176,"pid":31986,"hostname":"HikBookPro.local","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"checking for engine"}
{"level":30,"time":1617502403176,"pid":31986,"hostname":"HikBookPro.local","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"found engine"}
{"level":30,"time":1617502403176,"pid":31986,"hostname":"HikBookPro.local","name":"connector","ctx":"EngineConnector:initEngine","msg":"enter","port":59386}
{"level":30,"time":1617502419418,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"d:run","msg":"pre-execute"}
{"level":30,"time":1617502419418,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"projects.pachypus-rooting","mode":"note"},"msg":"enter"}
{"level":30,"time":1617502419482,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-rooting.md","external":"file:///Users/hikchoi/Cerebrarium/vault/projects.pachypus-rooting.md","path":"/Users/hikchoi/Cerebrarium/vault/projects.pachypus-rooting.md","scheme":"file"}}
{"level":30,"time":1617502422181,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/archive.projects.pachypus-prep.md","external":"file:///Users/hikchoi/Cerebrarium/vault/archive.projects.pachypus-prep.md","path":"/Users/hikchoi/Cerebrarium/vault/archive.projects.pachypus-prep.md","scheme":"file"}}
{"level":30,"time":1617502426783,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/cerebrarium.botany.plants.operculicarya.pachypus.md","external":"file:///Users/hikchoi/Cerebrarium/vault/cerebrarium.botany.plants.operculicarya.pachypus.md","path":"/Users/hikchoi/Cerebrarium/vault/cerebrarium.botany.plants.operculicarya.pachypus.md","scheme":"file"}}
{"level":30,"time":1617502463448,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/inbox.md","external":"file:///Users/hikchoi/Cerebrarium/vault/inbox.md","path":"/Users/hikchoi/Cerebrarium/vault/inbox.md","scheme":"file"}}
{"level":30,"time":1617502463480,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/Users/hikchoi/Cerebrarium/vault/cerebrarium.thoughts.md","external":"file:///Users/hikchoi/Cerebrarium/vault/cerebrarium.thoughts.md","path":"/Users/hikchoi/Cerebrarium/vault/cerebrarium.thoughts.md","scheme":"file"}}
{"level":50,"time":1617502539430,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"d:run","err":{"type":"r","message":"","stack":"Error: \n\tat d.run (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist/extension.js:9:103742)\n\tat async /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist/extension.js:9:79725\n\tat async S._executeContributedCommand (/Users/hikchoi/Desktop/dendron-test/pvis.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:103766)","status":"unknown","msg":"","payload":"{\"msg\":\"Cannot read property 'vault' of undefined\",\"stack\":\"TypeError: Cannot read property 'vault' of undefined\\n\\tat Function.getPathV4 (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist/extension.js:365:96855)\\n\\tat /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist/extension.js:100:186143\\n\\tat async B.pauseWatchers (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist/extension.js:9:76557)\\n\\tat async d.run (/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist/extension.js:9:103586)\\n\\tat async /Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist/extension.js:9:79725\\n\\tat async S._executeContributedCommand (/Users/hikchoi/Desktop/dendron-test/pvis.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:103766)\"}"}}
{"level":30,"time":1617502598610,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"f:run","msg":"pre-execute"}
{"level":30,"time":1617502598610,"pid":31986,"hostname":"HikBookPro.local","name":"dendron","ctx":"execute","opts":{}}
---
# Server Logs
{"level":30,"time":1617502395148,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"launch","msg":"exit","port":59386,"LOG_DST":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/user-data/logs/20210331T070104/exthost1/dendron.dendron/dendron.server.log","root":"/Users/hikchoi/Desktop/dendron-test/code-portable-data/extensions/dendron.dendron-0.35.0/dist"}
{"level":30,"time":1617502399645,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"WorkspaceController:init","msg":"enter","uri":"/Users/hikchoi/Cerebrarium"}
{"level":30,"time":1617502399649,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"FileStorageV2","wsRoot":"/Users/hikchoi/Cerebrarium","vaultsv3":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1617502399650,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"initSchema","msg":"enter"}
{"level":30,"time":1617502399651,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"initSchema","msg":"enter"}
{"level":30,"time":1617502399727,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"initSchema","schemaFiles":["cerebrarium.schema.yml","root.schema.yml"]}
{"level":30,"time":1617502399727,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"parse","msg":"enter","fpaths":["cerebrarium.schema.yml","root.schema.yml"],"vault":{"fsPath":"vault"}}
{"level":30,"time":1617502399738,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"initNotes","msg":"enter"}
{"level":30,"time":1617502399738,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"initNotes","msg":"enter"}
{"level":30,"time":1617502400153,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"WorkspaceController:init","msg":"finish init","uri":"/Users/hikchoi/Cerebrarium"}
POST /api/workspace/initialize 200 513.490 ms - 134575 - 77
POST /api/workspace/sync 200 1.893 ms - 134575 - 35
{"level":30,"time":1617502403173,"pid":31986,"hostname":"HikBookPro.local","name":"dendron.server","ctx":"NoteController:info","msg":"enter"}
GET /api/note/info 200 2.024 ms - 29 - 2
POST /api/workspace/sync 200 1.428 ms - 134575 - 35
POST /api/note/getByPath - - ms - - - 90
# Dendron Confg
{"version":1,"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["cerebrarium"],"siteRootDir":"docs","usePrettyRefs":true,"gh_edit_repository":"https://github.com/hikchoi/cerebrarium","logo":"vault/assets/images/2020-12-20-14-44-18.png","siteFaviconPath":"vault/assets/images/favicon.ico","siteUrl":"https://cerebrarium.garden","githubCname":"cerebrarium.garden","title":"cerebrarium","author":"hikchoi"},"initializeRemoteVaults":true}
# Port
59386
</p>
</details>

**Comment by kevinslin** [comment]
got it, thanks for the update. the release we're putting out tomorrow has more logs on the getPath issue that a few users are now encountering which should shed light on this. in the meanwhile, can you confirm whether this also happens if you open this workspace from a non-portable installation?

**Comment by hikchoi** [comment]
I haven't encountered this issue since. I think it's safe to close this issue for now :)
