### ISSUE TITLE
todo display isn't quite right

### ISSUE THREAD

**Issue by af4jm** [dendronhq/dendron#587]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [x] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

for to do lists, the check box should display in place of the bullet, and the text should be aligned exactly as if it were a bullet list... but enhanced preview renders a bullet list, with the checkbox at the start of the text

the functionality works, it just displays in a VERY ugly way... compare the screenshot (from enhanced preview) below, with the list of areas above

![image](https://user-images.githubusercontent.com/849948/112770855-b832dd00-8ff6-11eb-9989-f0d7aa6e057e.png)

**Comment by kevinslin** [comment]
hey @af4jm - can you confirm if you are using the regular vscode preview or enhanced preview? the screenshot looks like regular preview. dendron preview should auto-hide the bullet

**Comment by af4jm** [comment]
that was definitely in enhanced preview, my standard preview just shows a bullet then `[ ]` because I don't have an extension for that right now... and yeah, that's what I thought too

**Comment by kevinslin** [comment]
apologies for delay, can you copy and paste the raw markdown in the issue to help us reproduce?

**Comment by kpathakota** [comment]
@af4jm - I can't repro this myself. Could you please add your raw markdown? My markdown is usually like this: 
- [ ] Todo1 
- [ ] Todo2 
- [ ] Todo3

**Comment by micimize** [comment]
I see this as well on `v0.119.0` on ubuntu kinetic

![image](https://user-images.githubusercontent.com/8343799/225965971-163795df-415a-4f3a-a17b-4c01aa093e8b.png)
