### ISSUE TITLE
Support strict hierarchies through schema

### ISSUE THREAD

**Issue by pavkum** [dendronhq/dendron#588]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##
As of now schema's don't enforce strict hierarchies. They are required when multiple people are collaborating to keep the clutter out.

## Describe the solution you'd like ##
schema could take a new parameter called *strict* which defaults to false. If set to true, one wouldn't be able to create notes outside of the schema definition

## Describe alternatives you've considered ##
No solution as of now. Manual work is required to correct the notes.

## Additional context ##
NA

**Comment by kevinslin** [comment]
Writing here to add a strict schema proposal that we are currently considering

This introduces a mechanism for schemas to affect note creation.

```yml
workspace:
  schema:
    noteCreationBehavior: smart|strict|none
    
```

Values:
- noteCreationBehavior
  - values:
    - smart: enforce on note creation if a schema exists for the given hierarchy
    - strict: enforce on note creation for all hierarchies (if schema doesn't exist, note creation will fail)
    - none: never enforce on note creation

**Comment by kevinslin** [comment]
opened up a tracking issue in #2454
