### ISSUE TITLE
Filters to generate TOCs and lists

### ISSUE THREAD

**Issue by iilyak** [dendronhq/dendron#590]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the solution you'd like ##

The [Tiddlywiki](https://tiddlywiki.com/) supports notion of a filter and view to render the result. The filters allow to assemble arbitrary hierarchies. The need for different hierarchies is coming from the idea that it is impossible to come up with a unified hierarchy. Because every person has different opinion on where certain thing belong. Therefore strictly hierarchical point of view doesn't work in the team environment. Tiddlywiki uses custom fields which can be added to note metadata. Then these fields are used in filters to construct lists and hierarchies. The filters can be recursive. This allows to construct hierarchies of arbitrary depth. For example [kin filter](https://tiddlywiki.com/static/Kin%2520filter%2520operator%2520by%2520bimlas.html) allow generation of a family tree. Multiple hierarchies allow the user to construct different views on the same dataset of notes. You can define different views:
- by date
- by project
- by subject
- by feature

this flexibility allows tiddlywiki to be used as a generic framework to implement different solutions:
- [kanban board](https://ibnishak.github.io/Tesseract/projects/tekan/Tekan.html)
- [roam alternative](https://tiddlyroam.org/)
- [getting things done](http://gsd5.tiddlyspot.com/)
- todo managers
- issue trackers
- habit trackers
- technically it allows [network data model](https://en.wikipedia.org/wiki/Network_model) proposed before relational model was invented

However to be fair the filter syntax in Tiddlywiki is extremely inconsistent and very hard to learn. I think Dendron would benefit from implementing a concept similar to filters by combining three things:

- arbitrary metadata in yaml (or json) front matter
- query syntax based on either [JMESPath](https://jmespath.org/) or [GraphQL](https://graphql.org/)
- ability to define templates using any of the templating engines which has access to structures returned by query evaluation

Currently it is unclear how to achieve multiple hierarchies in Dendron and dynamic lists and hierarchies not yet possible.

**Comment by kpathakota** [comment]
A little bit of this is in #209 and another little bit is in #152. I'll close as duplicate and we'll track getting an extensible query language together as a larger project.
