### ISSUE TITLE
Unable to use triple-backtick code blocks in a template.

### ISSUE THREAD

**Issue by codefriar** [dendronhq/dendron#595]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug

I attempted to create a template for a schema that included a triple tilde, markdown compatible code block. This causes a generic VSCode error to appear asking em to check the dendron logs. Digging into the logs it shows that it can't find the template. The template file does exist, as template.blog.md

## To Reproduce

Create the following template as `template.blog.md`

```
---
id: a8e826ff-9910-4d5b-b61a-50297dc928b1
title: Boolean
desc: ''
updated: 1617209928011
created: 1617050784432
---

## Tweet Summary

> If you were to sum up your blog post in a Tweet, what would it be? Example: “Boost security and gain new insight into how users interact with your Salesforce app by enabling real-time event monitoring.” This can be rough; it greatly helps the blog team to effectively promote your post!

# Title

## Intro

> Why should the reader read your post? What’s in it for them? The first paragraph of the blog post answers these questions: What is the post about?, Why should I care?, and What can I do with this information?
j
### Subheading 1

> Visual?

### Subheading 2

> Visual?

### Subheading 3

> Visual?

### Conclusion

> Visual?

## About The Author
```
<code>public inherited sharing Kevin {
    public static String pronouns = 'he/him';
    public static Double startedWithSalesforceAtApiLevel = 11.0;
    public static String[] interests = ['Apex', 'Testing', 'iOS SDK', 'Generics', 'Metaprogramming'];
    public static String funFact = 'Has two daughters he\'s training to take over the world.';
    public static String twitterHandle = '@Codefriar'; 
}</code>
```

```
Note: GFMd may not render that correctly, but the key bit is that there is a triple-tilde code block at the very bottom. 

Next, create the following schema file as `blog.schema.yml`

```yml
version: 1
schemas:
  - id: blog
    desc: blog namespace
    parent: root
    namespace: true
    template:
      id: template.blog
      type: note
```

Finally, use cmd-l and attempt to create the note 'blog.foo' 

## Expected behavior

It should create the new note per schema, and template. The template should include the code block - properly formatted as a triple-tilde block.

## Screenshots

<img width="1811" alt="Screen Shot 2021-03-31 at 11 51 53 AM" src="https://user-images.githubusercontent.com/642589/113200314-26191780-9236-11eb-8843-0e9f204167ed.png">

## Desktop (please complete the following information)

- OS: Mac OS Big Sur 11.2.3
- Browser: ... n/a 
- Version: Dendron - latest

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/6239014/dendron.log)

**Comment by flammehawk** [comment]
@codefriar question does it work with the triple backtick ``` code block?

**Comment by codefriar** [comment]
@flammehawk - My apologies. I wrote triple-tilde, but what I meant was triple backtick. I'll update the issue.

**Comment by codefriar** [comment]
@flammehawk I tried to put the template in question in the initial issue, but github markdown didn't render the ``` within ``` correctly, so it looks odd. But if the template contains a code block delimitated with ``` dendron throws the error above.

The use case here, is with my blog post template. All my blog posts end with a 'about me' section, and I cheekily present the 'about me' section as a json block.

**Comment by flammehawk** [comment]
So I just tried to reproduce this error but got no luck I don't have a problem.

So I looked at what you provided again and noticed a difference between the screenshot and the shared schema of you.
The schema you shared had the 
```yaml
template:
 id: template.blog
```
but your screenshot has: 
```yaml
template:
 id:blog.template
```
making it understandable that it does not get found.

**Comment by kpathakota** [comment]
+1 @flammehawk, I tried repro'ing this too and can't. A template with a code block is working fine. Closing the issue. @codefriar - please reopen if you're still seeing this/you've got updated troubleshooting steps we can try.
