### ISSUE TITLE
Automatically generate index files

### ISSUE THREAD

**Issue by ognjenio** [dendronhq/dendron#596]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

It's sometimes useful to have a list of all the notes under a hierarchy. That way, you can add additional notes, put them in a specific order, or group them under headings. 

## Describe the solution you'd like ##

In order to accomplish that, it would be good if Dendron could automatically generate index files. 

There are potentially two ways to accomplish this:

1. Creating a note with `index` as the last part of the name. eg. `resources.articles.index.md` would be an index of all notes undex `resources.articles.` hierarchy. 
2. Adding `index: true` in the front matter. 

### Additional requirements

The existing content of the file should be preserved. 

There would be no duplicate note links. 

Notes that aren't already in the index would be added in the same place. Either all at the top or all at the bottom. 

#### Potential further improvements

Ability to make an index auto updating. For example by setting: `autoupdate_index: true` in the front matter

Ability to exclude a note from an index. For example by setting `exclude_from_index: true` in the front matter.

Ability to set an index either as deep (this hierarchy and all sub-hierarchies) or shallow (this exact hierarchy). 

Possibly the ability to set a pattern for files to be included: for instance `index_match: house` would only include notes with `house` in the name.

I lean towards keeping settings in the front matter rather then in Dendron.

### Script I use

For reference, here is the script that I currently use. It preserves content, puts new notes on top and doesn't duplicate notes.

It doesn't automatically update, but does have a command to update all. 

I'm still working on excluding and deep/shallow switches (yet).

https://gist.github.com/ognjenio/764c6810c179fd21fa07e82d9dac3f4e

**Comment by kpathakota** [comment]
#292 seems to be the same issue.

**Comment by kpathakota** [comment]
Closing this for now. @ognjenio - let me know if the linked issue is different (or comment on that one with your feedback).

**Comment by ognjenio** [comment]
Seems to have been copied to #603
