### ISSUE TITLE
Quickly store and open "attachments" associated with notes

### ISSUE THREAD

**Issue by alexrkopp** [dendronhq/dendron#597]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [X] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [X] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

My notes are often a hybrid of plain text (markdown), images, and other documents (PDFs, spreadsheets, etc.). There is a already a pretty quick workflow associated with embedding images that exist on the clipboard (e.g. screenshots), however I would love a similar process where I can attach and quickly link to arbitrary files within Dendron.

## Describe the solution you'd like ##

The ideal solution, for me, would allow me to very quickly associate files with my Dendron notes, have them copied into the Note hierarchy, and be able to reference them quickly (autocomplete?) from within a note.

**Comment by kpathakota** [comment]
Same as #575
