### ISSUE TITLE
Autocompletion recommendation window not showing up

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#600]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [X] Misc (Choose this if your not sure)

## Describe the bug

When using dendron manually triggering the autocomplete with `Strg + Space` works, but not when just typing. Tab completion works though. 

## Expected behavior

I'd expect dendron to show at least the snippets when typing. 

## Desktop

- OS: Win10
- Version: vscode 1.55, dendron 0.35.0

## Dendron Log file
```
{"level":30,"time":1617451242831,"pid":69488,"hostname":"Alpha","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\funnym0nk3y\\Desktop\\dendron_test\\vault\\test.md","_sep":1,"external":"file:///c%3A/Users/funnym0nk3y/Desktop/dendron_test/vault/test.md","path":"/c:/Users/funnym0nk3y/Desktop/dendron_test/vault/test.md","scheme":"file"}}
{"level":30,"time":1617451247298,"pid":69488,"hostname":"Alpha","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\funnym0nk3y\\AppData\\Roaming\\Code\\logs\\20210403T135002\\exthost1\\dendron.dendron\\dendron.log","_sep":1,"external":"file:///c%3A/Users/funnym0nk3y/AppData/Roaming/Code/logs/20210403T135002/exthost1/dendron.dendron/dendron.log","path":"/c:/Users/funnym0nk3y/AppData/Roaming/Code/logs/20210403T135002/exthost1/dendron.dendron/dendron.log","scheme":"file"}}
{"level":30,"time":1617451247329,"pid":69488,"hostname":"Alpha","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"c:\\Users\\funnym0nk3y\\Desktop\\dendron_test\\vault\\test.md","reason":3,"msg":"enter"}
{"level":30,"time":1617451247331,"pid":69488,"hostname":"Alpha","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1617451210728"],"msg":"update activeText editor"}
{"level":30,"time":1617451248029,"pid":69488,"hostname":"Alpha","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"c:\\Users\\funnym0nk3y\\Desktop\\dendron_test\\vault\\test.md","_sep":1,"path":"/c:/Users/funnym0nk3y/Desktop/dendron_test/vault/test.md","scheme":"file"}}
{"level":30,"time":1617451248033,"pid":69488,"hostname":"Alpha","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"test","msg":"exit"}
```

**Comment by kevinslin** [comment]
this is usually due to workspace settings. we set auto complete of snippets to be off by default due to feedback from users who find it distracting. you can re-enable it by updating the following setting: https://wiki.dendron.so/notes/9eca1992-7540-4d9d-97fb-328b27748b2c.html#cant-autocomplete-snippets-inline

**Comment by funnym0nk3y** [comment]
Well, I have exactly that setting in my workspace settings set to true. That's the reason I filed this bug report.

**Comment by kevinslin** [comment]
Hmm, we don't do anything that interferes with auto-complete. can you check
if you have extensions like markdown all in one installed? They've been
causes of completion issues in the past

**Comment by funnym0nk3y** [comment]
I have nothing enabled but the extensions linked to dendron (snippet maker, paste image, shortcuts, links, preview enhanced).

**Comment by funnym0nk3y** [comment]
Well, I solved it with adding 

```json
"[markdown]": {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": true
},
```

to my workspace settings file. Somehow it got deactivated...
