### ISSUE TITLE
Add website link to Github repo

### ISSUE THREAD

**Issue by noraj** [dendronhq/dendron#605]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

No.

## Describe the solution you'd like ##

Please add the link to the website (https://www.dendron.so/) on the Github repo.

## Describe alternatives you've considered ##

N/A

## Additional context ##

![image](https://user-images.githubusercontent.com/16578570/113515512-41a55a80-9575-11eb-858f-fc3165b01fe7.png)
![image](https://user-images.githubusercontent.com/16578570/113515525-541f9400-9575-11eb-84ad-ac4806b2ddee.png)
![image](https://user-images.githubusercontent.com/16578570/113515542-67cafa80-9575-11eb-80b0-0f2ef1ccfb17.png)

**Comment by kevinslin** [comment]
Thanks for the tip. Just added :)
