### ISSUE TITLE
Problems running on Theia

### ISSUE THREAD

**Issue by xeor** [dendronhq/dendron#606]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug

Problem runing dendron initialize workspace on Theia. Getting the same error as in https://github.com/eclipse-theia/theia/issues/8752. `TypeError: c.default.Uri.joinPath is not a function`

## To Reproduce

1. Build using Theia
2. Try to initialize workspace

## Expected behavior

Not hitting this error

## Additional context

Discussed on Discord https://discord.com/channels/717965437182410783/748936364283920495/828347171010379786

## Dendron Log file

```
info: {"ctx":"A:run","msg":"pre-execute"}
info: {"ctx":"SetupWorkspaceCommand extends BaseCommand","rootDir":"/Users/xeor/Dendron3","skipOpenWs":false}
error: {"ctx":"A:run","err":{"status":"unknown","msg":"","payload":"{\"msg\":\"c.default.Uri.joinPath is not a function\",\"stack\":\"TypeError: c.default.Uri.joinPath is not a function\\n    at A.execute (/Users/xeor/Temp/dendron-theia/theia-apps/theia-electron/plugins/dendron/extension/dist/extension.js:736:71386)\\n    at async A.run (/Users/xeor/Temp/dendron-theia/theia-apps/theia-electron/plugins/dendron/extension/dist/extension.js:9:103586)\\n    at async /Users/xeor/Temp/dendron-theia/theia-apps/theia-electron/plugins/dendron/extension/dist/extension.js:9:79725\"}"}}

```

**Comment by kevinslin** [comment]
Hey @xeor , any updates on Theia compatibility since we fixed the `joinPath` issue?

**Comment by xeor** [comment]
I got it running now after that fix, thanks.. I'm investigating the next problem tho, but I'm new to Theia, so using some time fiddling around :) I'm closing this issue. Will there be a good idea to create some new labels for which editor in use? `editor.vscodium`, `editor.theia`, and so on?

**Comment by kevinslin** [comment]
no need. just file it as a feature request and we’ll look into it
