### ISSUE TITLE
"error reading file" when creating reference to empty file

### ISSUE THREAD

**Issue by skrider** [dendronhq/dendron#609]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [X] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When attempting to render a reference to an empty file, "error reading file" is shown instead

## To Reproduce

1. Create an empty file
2. Use ctrl shift r to copy reference to it
3. Paste in another test file

## Expected behavior

Plaintext error message to be shown

## Desktop (please complete the following information)

- OS: [Windows]
- Version [latest]

## Dendron Log file

[message.txt](https://github.com/dendronhq/dendron/files/6262086/message.txt)

**Comment by kevinslin** [comment]
Thanks for submitting. This is a great starter issue for anyone that wants to contribute to Dendron :)

**Comment by kevinslin** [comment]
This will be fixed with #1156

**Comment by kevinslin** [comment]
this should be fixed in v56 of Dendron. please post here if not, otherwise this issue will auto close in 3 days
