### ISSUE TITLE
Strange title-case behavior on "exotic" names

### ISSUE THREAD

**Issue by xeor** [dendronhq/dendron#610]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Misc (Choose this if your not sure)

## Describe the bug

It looks like the parser that makes the `title` key in the frontmatter section is a little buggy when it comes to exotic characters like norwegian æ, ø and å. Seams like the parser things it's a space after each of the character.

## To Reproduce

1. Make a note (or rename an existing), as long as the `title` field will get generated
2. Write in a test-name, like "aaøøbbææccååaøbøcød å æ ø øl lø åå aå åa"
3. Notice that the `title` generated will be "AaøøBbææCcååaøBøCøD å æ ø øL Lø åå aå åA"

## Expected behavior

The title field should be as the top item, not the bottom:
* Aaøøbbææccååaøbøcød å æ ø øl Lø åå aå åa
* AaøøBbææCcååaøBøCøD å æ ø øL Lø åå aå åA

## Desktop (please complete the following information)

- OS: osx
- Version: v0.36.2

## Additional context

I see no problems with other fields and the mentioned characters.

**Comment by xeor** [comment]
https://github.com/vercel/title/issues/33 is for the same bug, there was a PR, but it got stale

**Comment by kevins8** [comment]
This is because we are using the `vercel/title` package to do
capitalization so this is likely the same issue

https://www.npmjs.com/package/title

**Comment by xeor** [comment]
yes.. I'm looking into that issue..

I'm actually not sure what I will use the `title` field for at all.. It generally feels redundant. Can it be optional maybe? Or maybe an option to just use the filename (minus .md)?

**Comment by kevinslin** [comment]
you can turn it off via configuration: https://wiki.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f48.html#usefmtitle

**Comment by kevinslin** [comment]
Ah, miscommunication on my part. This removes the title from the preview
(we use the title as an automatic h1 header). The fm title remains the same

**Comment by kpathakota** [comment]
It seems like we can continue to use the vercel issue to track this one. Low pri since you don't *need* to use this title and can just use an H1 header at the top of a note anyway for preview. @xeor - good to close?

**Comment by xeor** [comment]
Yea, let's close this :)
