### ISSUE TITLE
Site preview fails

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#611]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When trying to view the site preview, I first get asked if I want to update the dependencies, which fails then with the attached error message.

## To Reproduce

1. `Strg+Shift+P`
2. Site Preview
3. Update dependencies

## Error message

```
{"ctx":"d:run","err":{"status":"unknown","msg":"","payload":"{\"msg\":\"Command failed with ENOENT: npm install --save @dendronhq/dendron-11ty@1.36.0\\nspawn npm ENOENT\\nDer Befehl \\\"npm\\\" ist entweder falsch geschrieben oder\\r\\nkonnte nicht gefunden werden.\",\"stack\":\"Error: Command failed with ENOENT: npm install --save @dendronhq/dendron-11ty@1.36.0\\nspawn npm ENOENT\\nDer Befehl \\\"npm\\\" ist entweder falsch geschrieben oder\\r\\nkonnte nicht gefunden werden.\\n\\tat i (c:\\\\Users\\\\Michael\\\\.vscode\\\\extensions\\\\dendron.dendron-0.36.2\\\\dist\\\\extension.js:439:203527)\\n\\tat o (c:\\\\Users\\\\Michael\\\\.vscode\\\\extensions\\\\dendron.dendron-0.36.2\\\\dist\\\\extension.js:439:203698)\\n\\tat ChildProcess.e.emit (c:\\\\Users\\\\Michael\\\\.vscode\\\\extensions\\\\dendron.dendron-0.36.2\\\\dist\\\\extension.js:439:203839)\\n\\tat Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)\"}"}}
```

## Desktop 
- OS: Win10
- Browser: Firefox
- Version: vscode 1.55; dendron 0.36.2

**Comment by funnym0nk3y** [comment]
Please delete this issue, made a mistake.

**Comment by tolikkostin** [comment]
@funnym0nk3y  how did you resolve the issue?
I faced the same problem.

**Comment by funnym0nk3y** [comment]
You need to install node.js separately. I somehow thought it can use a node installation inside of vscode

**Comment by tolikkostin** [comment]
@funnym0nk3y thank you! It helped
