### ISSUE TITLE
Create a new note after typing a long name takes a while

### ISSUE THREAD

**Issue by ognjenio** [dendronhq/dendron#612]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

Note creation

## Describe the bug

When a long note name is typed, it takes a few seconds for it to be created. 

## To Reproduce

1. Ctrl + L
2. Type (don't paste) a note that's ~100 characters long
3. Press Enter to create a new note
4. Will have to wait for a few seconds

## Logs

The full name of the note typed is `random-random-anotherlongnomtenameanotherlongnotenameanotehrnotenamelongnotenamelongnotenamelongnoename`

Logs (attached) seem to indicate that this is a slow down because once of auto-complete still querying for notes. 

Line 494 is the first time that's it's completed: 1617856977988

Between `onDidAcceptSingle` (:496) and `showDocAndHidePicker` (:566) at 1617856978528 is just 540ms

`l:run","msg":"post-execute"` (:596) however is at 1617856986565 which is 8.5s which is what actually seems to happen. 

## Desktop (please complete the following information)

- OS: Ubuntu 20.04
- Dendron Version: 0.36.2

## Dendron Log file

[slow-note-creation.log](https://github.com/dendronhq/dendron/files/6276104/slow-note-creation.log)

## Video 

(I press Enter immediately after I stop typing)

https://user-images.githubusercontent.com/1166932/113970740-f7b8bf00-9869-11eb-802d-10bd08f91c1d.mp4

**Comment by kevinslin** [comment]
Thanks for the report. This is usually due to some pathological cases when matching suggestions to schemas. Putting this as a high priority item for this month

**Comment by kpathakota** [comment]
@ognjenio - can confirm this still occurs despite last week's performance improvements. I think it's worth taking a look and seeing what the thresholds are. Unfortunately, once you hit this, it feels like VSCode is hosed (locked up for a minute or so).

**Comment by kevinslin** [comment]
This is being investigated this week as part of lookup improvements

**Comment by kevinslin** [comment]
this should be fixed in v56 of Dendron. please post here if not, otherwise this issue will auto close in 3 days
