### ISSUE TITLE
Frontmatter definition for custom URL Slug

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#618]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Every page has a generic URL when published. 

## Describe the solution you'd like ##

I'd like slugs in the URL to describe the content better and make the URL nicer to share. We could include this as an optional field in the frontmatter so it could look something like this

```
---
id: 34836da4-0794-4997-bb82-846e24d59e15
title: "2021-04-13"
desc: ""
updated: 1618297971788
created: 1618297908667
slug: "a-note"
---

```
URL would then be <published URL>/a-note.html

## Describe alternatives you've considered ##

Could use tiny URL or some other generation tool but that defeats the purpose of having easily shareable links by default.

**Comment by kevinslin** [comment]
Created a issue for a more general solution [here](https://github.com/dendronhq/dendron/issues/620)

**Comment by kpathakota** [comment]
Closing duplicate
