### ISSUE TITLE
"Go down" command doesn't work at the root level

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#619]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When triggered at the root level, the "[Go down](https://wiki.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#go-down)" command opens lookup for `root` which matches only itself (unless there are other notes with "root" in the names).

## To Reproduce

Steps to reproduce the behaviour:

1. Create some notes
2. Open `root`
3. Press `Ctrl + Shift + 🔽`
4. Observe the lookup trying to match `root`

## Expected behaviour

"Go down" command should match direct children of the root.

## Screenshots

![image](https://user-images.githubusercontent.com/79934725/114557677-e68bfb80-9c37-11eb-9664-ef64960ae340.png)
**Hierarchies**

![image](https://user-images.githubusercontent.com/79934725/114557710-ef7ccd00-9c37-11eb-9602-f874cca99ed9.png)
**"Go Down" Lookup**
## Desktop (please complete the following information)

- OS: Win 10x64
- Dendron: 0.37.0

## Additional context

This is probably related to the `root` hierarchy being implicit for all the notes in a vault.

**Comment by kevinslin** [comment]
Thanks for the update.  `root` is a special case. adding to backlog
