### ISSUE TITLE
buildSiteV2 fails if you have a note that has no content

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#626]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [x] Publishing
- [x] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

`npx dendron-cli buildSiteV2 --wsRoot .  --stage dev --serve` fails when I have a note that has no content in it.

## To Reproduce

1. Create a note, but do not add any content to it.
2. run `npx dendron-cli buildSiteV2 --wsRoot .  --stage dev --serve`
3. This will fail with: 
```
Error writing templates: (more in DEBUG output)
> Having trouble writing template: /Users/hikchoi/Cerebrarium/build/site/notes/403.html

`TemplateWriterWriteError` was thrown
> error reading file, /Users/hikchoi/Cerebrarium/vault/cerebrarium.dev.web.design.test.md, file:./_includes/includes/note.liquid, line:2

`RenderError` was thrown
> error reading file, /Users/hikchoi/Cerebrarium/vault/cerebrarium.dev.web.design.test.md

... (truncated for brevity)
```
## Expected behavior

Renders and publishes an empty note

## Desktop (please complete the following information)

- OS: MacOS Big Sur 11.0.1

## Additional context

I suspect this has something to do with publishing stub notes. Just a guess.

**Comment by kpathakota** [comment]
Possibly a good first issue to look at/root cause @hikchoi cc: @kevinslin

**Comment by hikchoi** [comment]
Just sat down to fix this issue myself.
This is a user error: `npx` was pointing to an outdated `dendron-cli` and `dendron-11ty`.
So I had a wrong impression of what `npx` was doing and also didn't think to look at my dependencies.

I wasn't able to repro this on a fresh workspace / vault with the exact same notes as my personal one, so I don't think there's anything to fix here other than my outdated dependencies 😅 

```
{
  "scripts": {
    "dendron-cli": "dendron-cli"
  },
  "license": "CC BY 4.0",
  "dependencies": {
    "@dendronhq/dendron-11ty": "^1.37.0",
    "@dendronhq/dendron-cli": "^0.28.2"
  }
}
```

I did believe running `Dendron: Site Preview` would update `@dendronhq/dendron-11ty` and `@dendronhq/dendron-cli` though. I may have 1. forgot to push `package.json` to remote or 2. just forgot to update again.
