### ISSUE TITLE
In multi-vault setting daily journal files get created in the current vault

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#628]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug

Creating a neew daily note should ask for the vault to create it in if `lookupConfirmVaultOnCreate: true` is set

## To Reproduce

1. Open a file in one of the vaults
2. Click `Ctrl-Shift+i`
3. the new daily note is created in the same vault as the currently open vault

## Expected behavior

I expect after step 2 to be able to select the vault in which the note is created similar to journal or scratch notes

## Desktop (please complete the following information)

- OS: Windows 10
- VSCode: 1.55.2
- Dendron: 0.37.0

**Comment by kpathakota** [comment]
Yes, +1 can repro this as well. Not expected behavior for this configuration.

**Comment by kpathakota** [comment]
Shipped with v47
