### ISSUE TITLE
Graph View is Loading Slowly

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#630]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [X] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The Graph View is loading slowly. I presently have 3051 files and 3050 links. 

For the purposes of this issue, I timed the loading process: it took 1 minute and 19 seconds to populate with my notes and links, then an additional 51 seconds before I could interact with it, for a total of 2 minutes and 10 seconds to load. 

## To Reproduce

1. Run "Dendron: Show Note Graph" command.
2. The Notes Link tab opens empty, lists 0 files and 0 links.
3. After an extended period, the Graph View populates, but cannot be interacted with.
4. After a second period of waiting, the Graph View becomes usable.

## Expected behavior

That running the command opens the Graph View ready to be used.

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: NA
- Version: VSCodium 1.55.2, Dendron 0.37.0, Dendron Markdown Links 0.6.19

## Dendron Log file

{"level":30,"time":1618443171632,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1618443171726,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"f:\\VSCodium Portable\\data\\user-data\\logs\\20210414T193234\\exthost1\\dendron.dendron","logLevel":"info","extensionPath":"f:\\VSCodium Portable\\data\\extensions\\dendron.dendron-0.37.0","extensionUri":{"$mid":1,"fsPath":"f:\\VSCodium Portable\\data\\extensions\\dendron.dendron-0.37.0","_sep":1,"path":"/F:/VSCodium Portable/data/extensions/dendron.dendron-0.37.0","scheme":"file"},"storagePath":"f:\\VSCodium Portable\\data\\user-data\\User\\workspaceStorage\\6ce6f8b7d9ec26e73bc29cc7ebab8560\\dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"f:\\Dendron\\dendron.code-workspace","_sep":1,"external":"file:///f%3A/Dendron/dendron.code-workspace","path":"/f:/Dendron/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault","_sep":1,"external":"file:///f%3A/Dendron/vault","path":"/f:/Dendron/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1618443171729,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1618443176572,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","config":{"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","useFMTitle":true,"usePrettyRefs":true},"version":0,"initializeRemoteVaults":true},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1618443244061,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:init","msg":"enter","opts":{}}
{"level":30,"time":1618443244061,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:createServerWatcher","msg":"enter","opts":{}}
{"level":30,"time":1618443244179,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","files.autoSave":"off","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on","markyMarkdown.statisticStatusBarItem":"Words","explorer.sortOrder":"modified"},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","github.github-vscode-theme"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]},"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links"]},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1618443244220,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.37.0","migratedGlobalVersion":"0.37.0","previousGlobalVersion":"0.36.2","previousWsVersion":"0.37.0","platform":"win32","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.30","active":true},{"id":"dendron.dendron-markdown-links","version":"0.6.19","active":false},{"id":"github.github-vscode-theme"}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1618443244221,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"startServer","logLevel":"info"}
{"level":30,"time":1618443244238,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","msg":"post-start-server","port":63836}
{"level":30,"time":1618443244240,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"logger","ctx":"FileStorageV2","wsRoot":"f:\\Dendron","vaultsv3":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1618443244272,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1618443288310,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:_connect","portCreated":3373865674955,"wsActivation":1618443244180}
{"level":30,"time":1618443288311,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:_connect","msg":"initFromExistingFile","port":63836}
{"level":30,"time":1618443288312,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:tryToConnect","port":63836,"msg":"enter"}
{"level":30,"time":1618443288583,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1618443288583,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1618443288583,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1618443288585,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1618443288585,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1618443288588,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1618443288865,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1618443288871,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"activateWorkspace","stage":"dev","msg":"enter"}
{"level":30,"time":1618443288879,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1618443288880,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","msg":"fin startClient"}
{"level":30,"time":1618443288880,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.37.0","previousVersion":"0.37.0"}
{"level":30,"time":1618443288880,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1618443288996,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:tryToConnect","msg":"connected","info":{"version":"0.37.0"}}
{"level":30,"time":1618443288996,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"checking for engine"}
{"level":30,"time":1618443288996,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"found engine"}
{"level":30,"time":1618443288996,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:initEngine","msg":"enter","port":63836}
{"level":30,"time":1618443289066,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1618443326216,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"h:run","msg":"pre-execute"}
{"level":30,"time":1618443326216,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"root","mode":"note","vault":{"fsPath":"vault"}},"msg":"enter"}
{"level":30,"time":1618443326408,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\root.md","_sep":1,"external":"file:///f%3A/Dendron/vault/root.md","path":"/f:/Dendron/vault/root.md","scheme":"file"}}
{"level":30,"time":1618443326413,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"root","mode":"note","vault":{"fsPath":"vault"}},"msg":"exit"}
{"level":30,"time":1618443326413,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"h:run","msg":"post-execute"}
{"level":30,"time":1618443331464,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443331464,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443331468,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443331469,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443343750,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"f:\\Dendron\\vault\\root.md","reason":1,"msg":"enter"}
{"level":30,"time":1618443343754,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1616381801109"],"msg":"update activeText editor"}
{"level":30,"time":1618443344595,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\root.md","_sep":1,"path":"/f:/Dendron/vault/root.md","scheme":"file"}}
{"level":30,"time":1618443344601,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"root","msg":"exit"}
{"level":30,"time":1618443347365,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443347366,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443347370,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443347371,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443347558,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443347558,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443347560,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443347560,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443347785,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443347786,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443347793,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443347793,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443348347,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443348348,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443348350,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"f:\\Dendron\\vault\\root.md"}
{"level":30,"time":1618443348350,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1618443355856,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"f:\\Dendron\\vault\\root.md","reason":1,"msg":"enter"}
{"level":30,"time":1618443355859,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1618443343752"],"msg":"update activeText editor"}
{"level":30,"time":1618443356543,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\root.md","_sep":1,"path":"/f:/Dendron/vault/root.md","scheme":"file"}}
{"level":30,"time":1618443356551,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"root","msg":"exit"}
{"level":30,"time":1618443380412,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.14.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.14.md","path":"/f:/Dendron/vault/journal.2021.04.14.md","scheme":"file"}}
{"level":30,"time":1618443405985,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\index.bookshelf.md","_sep":1,"external":"file:///f%3A/Dendron/vault/index.bookshelf.md","path":"/f:/Dendron/vault/index.bookshelf.md","scheme":"file"}}
{"level":30,"time":1618443408927,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.14.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.14.md","path":"/f:/Dendron/vault/journal.2021.04.14.md","scheme":"file"}}
{"level":30,"time":1618443443019,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.14.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.14.md","path":"/f:/Dendron/vault/journal.2021.04.14.md","scheme":"file"}}
{"level":30,"time":1618443573245,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.14.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.14.md","path":"/f:/Dendron/vault/journal.2021.04.14.md","scheme":"file"}}
{"level":30,"time":1618443669103,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.14.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.14.md","path":"/f:/Dendron/vault/journal.2021.04.14.md","scheme":"file"}}
{"level":30,"time":1618443672513,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.14.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.14.md","path":"/f:/Dendron/vault/journal.2021.04.14.md","scheme":"file"}}
{"level":30,"time":1618444374772,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.14.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.14.md","path":"/f:/Dendron/vault/journal.2021.04.14.md","scheme":"file"}}
{"level":30,"time":1618444398675,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"l:run","msg":"pre-execute"}
{"level":30,"time":1618444398676,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1618444398724,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"l:run","msg":"post-execute"}
{"level":30,"time":1618444398879,"pid":5112,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\VSCodium Portable\\data\\user-data\\logs\\20210414T193234\\exthost1\\dendron.dendron\\dendron.log","_sep":1,"external":"file:///f%3A/VSCodium%20Portable/data/user-data/logs/20210414T193234/exthost1/dendron.dendron/dendron.log","path":"/f:/VSCodium Portable/data/user-data/logs/20210414T193234/exthost1/dendron.dendron/dendron.log","scheme":"file"}}

**Comment by flammehawk** [comment]
You might want to look at this [RFC](https://wiki.dendron.so/notes/c998c642-a748-4f77-9285-cfec35330251.html) corresponding to the Overall handling of the Graph performance is one part of it.

**Comment by kevinslin** [comment]
Thanks for the update. Yeah, we'll be redoing the graph view in the summer time. @kpathakota is working on creating a timeline to give you an idea when some of the major items will launch. You can see the current roadmap here: https://github.com/orgs/dendronhq/projects/1

**Comment by micharris42** [comment]
Thank you. Now that it has been pointed out to me, I see this is already covered by #107.

I apologize for the duplicate issue.
