### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by mandolyte** [dendronhq/dendron#631]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Describe the bug

1. At https://wiki.dendron.so/notes/d758fe38-558c-4f20-a091-cac146a781cb.html#backlinks, s/your/you're/
2. At https://wiki.dendron.so/notes/d758fe38-558c-4f20-a091-cac146a781cb.html#note-references, s/principals/principles/; note, this is correct in the information, but not in the note titles.

**Comment by flammehawk** [comment]
Greetings, and thank you for telling us about them; you can edit the information yourself; on the bottom of the linked page, you find the option to edit it on GitHub.

**Comment by kpathakota** [comment]
+1 @flammehawk. @mandolyte - feel free to ping me on Discord (@kpats#8761) if you need help with the pull request - should be really straightforward, you don't even need to pull the code down and can do the whole operation directly in Github.

**Comment by kpathakota** [comment]
Thanks for the catch @mandolyte - fixed: https://github.com/dendronhq/dendron-site/commit/17c535b368e84e8412bf50a5b576fa87470a7d9a
