### ISSUE TITLE
Something went wrong while initializing workspace. 

### ISSUE THREAD

**Issue by Erza123** [dendronhq/dendron#632]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [x] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
Did you have any particular issue in mind?

**Comment by Erza123** [comment]
After I install Dendron, when i want to initalize dendron workspace, an error shows up saying this: 
something went wrong. please submit a bug report to https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= with the output of `Dendron: Open Log`

**Comment by kpathakota** [comment]
@Erza123 - could you run the Dendron: Open Log command and attach the output to this issue? You should be able to get it via the VS Code command bar (Cmd/Ctrl + Shift + P) and then typing in "Dendron: Open Log".
