### ISSUE TITLE
Site Preview not updating unless VSCode is closed and reopened. 

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#640]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Preview is not updating unless VSCode is quit and then restarted 

## To Reproduce

1. Start a site preview. 
2. Make changes to a page
3. Refresh site preview (even try stopping preview process and restarting in vscode)

## Expected behavior

4a. Site preview should reload with changes. 

## Desktop (please complete the following information)

- OS: Windows
- Browser: Edge
- Version 37.0

## Dendron Log file

[site-preview-not-updating.log](https://github.com/dendronhq/dendron/files/6331188/site-preview-not-updating.log)

**Comment by flriancu** [comment]
@kevinslin I think this is similar to #539

**Comment by kpathakota** [comment]
Yup, you're right. Closing this as a duplicate.
