### ISSUE TITLE
Tutorial for publishing not working as described

### ISSUE THREAD

**Issue by flriancu** [dendronhq/dendron#645]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When following the steps in the official [tutorial for publishing](https://wiki.dendron.so/notes/861e4e48-dcc5-4813-a695-8940ba6e64d3.html), I get different results:

- The `dendron.welcome.md` is not in the left sidebar
- The image links are not well-formed
- The official documentation is not up-to-date (the Github settings layout has changed)

## Screenshots

- [missing file in the sidebar](https://user-images.githubusercontent.com/8483893/115157020-c329dc00-a08f-11eb-9dcd-53a5c44550e1.png)
- [file is found when searching](https://user-images.githubusercontent.com/8483893/115157055-e2c10480-a08f-11eb-9778-08282566a3fc.png)
- [image is not rendered](https://user-images.githubusercontent.com/8483893/115157069-f10f2080-a08f-11eb-8a89-6828c3911ee8.png)
- [image URL is not well-formed](https://user-images.githubusercontent.com/8483893/115157099-084e0e00-a090-11eb-8677-eb3028d5faf3.png)

## Desktop (please complete the following information)

- OS: Windows
- Browser: Chrome
- Version: 37

**Comment by kevinslin** [comment]
This is the legacy publishing tutorial. Are you still seeing this issue in our new publishing guide? https://wiki.dendron.so/notes/4ushYTDoX0TYQ1FDtGQSg.html
