### ISSUE TITLE
No graph commands available

### ISSUE THREAD

**Issue by mprimi** [dendronhq/dendron#646]
This wiki page has instructions to open the graph views:
https://wiki.dendron.so/notes/587e6d62-3c5b-49b0-aedc-02f62f0448e6.html

But **I don't see any of the graph commands** (like `Dendron: Show Schema Graph`)
Everything is up to date, Dendron is v0.37.0, active and working fine in every other aspect.

![Screen Shot 2021-04-16 at 7 34 07 PM](https://user-images.githubusercontent.com/6885259/115099588-d7cd6f00-9eeb-11eb-868d-4c96cfc35823.png)

May this be a bug?

P.S. Great project. 👏 🙂

**Comment by mprimi** [comment]
It's happening consistently for me (i.e. across VS restarts, vault reload, etc).

If you want to investigate I'm happy to provide logs or anything else you need.

**Comment by kevins8** [comment]
Do you have `Dendron: Markdown Links` extension installed?

**Comment by flammehawk** [comment]
That is expected and you may want to give the following [RFC: Graph Rework](https://wiki.dendron.so/notes/c998c642-a748-4f77-9285-cfec35330251.html) a read. There are Plans to improve the Graph view and you are free to contribute to the discussion about it.
