### ISSUE TITLE
New commands don't seem to work

### ISSUE THREAD

**Issue by alexisargyris** [dendronhq/dendron#65]
**Describe the bug**
Combination of `Doctor` and `Build Pod` doesn't seem to work.

**To Reproduce**
1. Run `Initialize Workspace` to make our life easier
2. Run `Doctor` to ensure everything is in order
3. Run `Build Pod` to export the folder's contents

**Expected behavior**
Access the exported material in the "docs" folder. 

**What actually happened**
I got a success notification but the "docs" folder was not created and I failed to find the exported vault anywhere.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 84

** Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

[dendron.log](https://github.com/dendronhq/dendron/files/4999485/dendron.log)

**Comment by herop** [comment]
Just my 2cents:
- Did you pay attention to messages?
- Mine said - correctly - that some files where missing

**Comment by alexisargyris** [comment]
Thanks for your reply. Yes, I hope I did. It was for that reason that I ended up initializing the workspace and running the `doctor` command, to fix missing file messages. Did you try on Win too or Mac?

**Comment by herop** [comment]
> Thanks for your reply. Yes, I hope I did. It was for that reason that I ended up initializing the workspace and running the `doctor` command, to fix missing file messages. Did you try on Win too or Mac?

Windows10 like you.
Please try again with the window reload I mentioned above.

**Comment by kevinslin** [comment]
hmm, there doesn't seem anything obvious from the logs and I was able to do the build from a clean vault as well as an existing one on windows 10. note that the `docs` folder will be created inside `dendron.rootDir` and not inside your vault. 
this is my file tree after running build-pod:

```
kevinslin@WSAMZN-SD8N2AGI MINGW64 ~/Dendron-alpha
$ ls
dendron.code-workspace  dendron.yml  docs  vault
```

**Comment by alexisargyris** [comment]
Ah, that was the problem. I was looking inside the vault. Thanks!
