### ISSUE TITLE
Refactoring changes title

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#656]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When refactoring the title of a note gets changed. 

## Expected behavior

I'd expect that refatoring preserves the title. For example some titles have spaces or start with a capital letter one added when creating the note. That all gets shmushed. 

## Desktop (please complete the following information)

- vscode: 1.55.2
- dendron: 0.38.0

**Comment by kevinslin** [comment]
Hmm, do you have an example? Refactoring follows the same convention as rename - if the title is the same as what Dendron would autogenerate (kebab-case capitalized), then refactor will change the title as well. Otherwise, it (should) preserve the existing title

**Comment by funnym0nk3y** [comment]
Unfortunately not, but I tried it with another file: 

`Frobeniusmatrix -> frobeniusmatrix` when changing the file hierarchy `mathematik.frobeniusmatrix -> mathematik.lineareAlgebra.frobeniusmatrix`

**Comment by kpathakota** [comment]
I'm not sure that's unexpected. I thought we wouldn't preserve capitalization especially if it's in camel case. @funnym0nk3y - are you still seeing this affect you often?

**Comment by funnym0nk3y** [comment]
I avoided refactoring recently because I didn't want to mess with my files and  transitioned to the recommended kebab-case.

**Comment by kpathakota** [comment]
Try as I might I cannot repro this behavior. Might've been fixed in a recent update, but not sure. @funnym0nk3y, I'd say the behavior is a bug if it continues to repro for you (I literally tried that frobenius -> linearAlgebra example and all the casing stayed just fine). Closing out.
