### ISSUE TITLE
Improve refactoring

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#657]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

At first I'm creating my notes pretty high in the hierarchy as I don't know how they are linked when learning a new topic. Then I want to group them together. 

## Describe the solution you'd like ##

I'd like to regroup files like that:

```
maths.permutationmatrix -> maths.linearalgebra.permutationmatrix
maths.frobeniusmatrix ->maths.linearalgebra.frobeniusmatrix
```

Currently this is only possible for each note seperatly. I'd like to search for `*matrix` and move everything one level deeper. 

## Additional context ##

If it is possible, I'd like to suggest to add it to the documentation.

**Comment by kpathakota** [comment]
+1 I like this idea too. This will help structure to *emerge* for Dendron. Will add this though the timeline is a little up in the air so if anyone else is able to pick this up, please do.

**Comment by funnym0nk3y** [comment]
I just found out, that through a more or less complex way it is possible to match the example above with `[^.]*matrix`, but I have not found a way to use the matched sequence in the replace string.

**Comment by telenieko** [comment]
Wouldn't adding support for regex capture groups cover this use case, and many others?

See [this example refactoring a journal hierarchy](https://regexr.com/68hn5):
![image](https://user-images.githubusercontent.com/10505/139484948-87f41dcd-0fbc-4550-8ebe-90843a99c4b9.png)

Or [this example refactoring a recipe tree](https://regexr.com/68ho0) from ingredient oriented to type oriented:
![image](https://user-images.githubusercontent.com/10505/139485668-9359998c-e1d9-42e1-87ea-2e9c4c842140.png)


(got here searching precisely about capture group support)

**Comment by aleksey-rowan** [comment]
Hey, @funnym0nk3y, the refactor functionality now has [full regex support](https://wiki.dendron.so/notes/srajljj10V2dl19nCSFiC/#refactor-hierarchy) including capture groups and it's possible to do what you were asking about.

I'll mark this issue to close in four days. Leave a comment if you have any problems and it will stay open.
