### ISSUE TITLE
Refactoring messes with math notation

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#661]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When refactoring dendron messes with math syntax as it escapes each TeX macro with a backslash. This breaks all formulae. 

## Expected behavior

To don't mess with math code.

**Comment by aleksey-rowan** [comment]
This is probably related to Dendron re-formatting markdown of refactored notes. Related: https://github.com/dendronhq/dendron/issues/278#issuecomment-712453136 and https://github.com/dendronhq/dendron/issues/572

**Comment by kevinslin** [comment]
Yeah, it is. Closing in favor of #572
