### ISSUE TITLE
`Dendron: Goto Note` fails on one link, but `Goto Definition` works

### ISSUE THREAD

**Issue by spex66** [dendronhq/dendron#662]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Discord discussion where @kevins8 confirmed reproduction and issue in code:
https://discord.com/channels/717965437182410783/735365126227493004/835200978579619860

## To Reproduce

1. Portable VSCode only Dendron
2. lookup `doc dendron.topic.refs` in last chapter (see below)
3 the publish link shows a preview on hover and with `Dendron: Goto Note` or `Goto Definition` jumps to the target
2. the configuration link shows a preview on hover too, but `Dendron: Goto Note` responds with an error message popup: "selection is not a valid link", but it works in rendered-preview when clicking the rendered link which opens `dendron.topic.publishing.configuration.md`

```
## Publishing

When you [[publish|dendron.topic.publishing]] a note with a note reference, Dendron will embed the content of the reference in the page. If the content is part of a published page as specified by the publishing [[configuration|dendron.topic.publishing.configuration]], dendron will include a link to the page. If not, Dendron will embed the content without a link. If the referenced content is not publishable (eg. `published: false` set on frontmatter), dendron will generate a custom [[404 link|dendron.topic.publishing.features#selective-publication]]
```
## Expected behavior

Both ways to follow a link should work

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
this has been shipped
