### ISSUE TITLE
Support for headers/block references autocompletion on wikilinks

### ISSUE THREAD

**Issue by gjroelofs** [dendronhq/dendron#663]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

At the moment autocompletion is supported for notes when constructing a wikilink. 
However, autocompletion of (header) block levels is not. 
This causes a jarring interruption during a workflow where one wants to create a reference to a specific header.

## Describe the solution you'd like ##

I would like autocompletion of a wikilink, once a note is selected and `#` is inserted, to switch to autocompletion of the headers on that page, resulting in a valid block reference once selected.

## Describe alternatives you've considered ##

I have tried following the recommended workflow with the hotkey that creates a block reference to the currently selected block. However, this requires me to switch to the relevant page, find the relevant header manually, and use the reference hotkey and switch back - which takes me out of the flow of writing a note.

**Comment by kpathakota** [comment]
We should consolidate this + #175  + #262 and do a much-needed "auto-complete improvements" project. Might be a little bit larger RFC but makes sense to deliver them all together. 

For now, marking as help-needed until we resource the project.

**Comment by aleksey-rowan** [comment]
This is done.
