### ISSUE TITLE
Right-hand navigation menu: Local table of contents / TOC of a note in NextJS published site

### ISSUE THREAD

**Issue by ScriptAutomate** [dendronhq/dendron#667]
> **NOTE:** _This is a migrated issue. Original issue was opened in a now-archived repo: https://github.com/dendronhq/dendron-11ty/issues/11_

## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)
  - **This is related to the Dendron 11ty theme**
  
## Is your feature request related to a problem? Please describe ##

When on a page, there is no local table of contents / TOC to help navigate a large page. This means that the user is stuck needing to ctrl+f for anchors/headers on the page.

## Describe the solution you'd like ##

One of my favorite implementations of this:

- https://pradyunsg.me/furo/contributing/workflow/

Because even on a mobile view, there still remains a right-hand nav drop-down for local TOC.

For other examples of how others have approached this UI/navigation problem, in these docsets you'll see the TOC of the local page and all the anchors on the right-hand side:

- https://docs.docker.com/get-started/
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html
- https://www.docsy.dev/docs/adding-content/content/

## Describe alternatives you've considered ##

I'm not sure, perhaps a TOC auto-generated and/or prepended to the content of a note at the top of a page?

**Comment by kpathakota** [comment]
+1, loved that first implementation: https://pradyunsg.me/furo/contributing/workflow/

I think we need to go one further and make our publishing capabilities more hackable/configurable so you can have a right-side context menu if you want.

**Comment by ScriptAutomate** [comment]
This has been implemented in the latest release!
- https://github.com/dendronhq/dendron/pull/1428
- [Docs from Dendron Wiki](https://wiki.dendron.so/notes/SsMGHoFVgyBdydzI5mn78/#table-of-contents)
