### ISSUE TITLE
Add extension Context during activation

### ISSUE THREAD

**Issue by flammehawk** [dendronhq/dendron#672]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [X] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Currently, Dendron Commands are mostly bound to the condition of editorFocus, which still leads to problems if we are not inside a dendron Workspace, making the commands error. 
Additionally, the command palette is cluttered with dendron commands even when no dendron Workspace is active. 

## Describe the solution you'd like ##

Using a custom [when context](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context) can provide a Possible solution to this by setting a Context during activation like `dendron.active`. 

Which can be used in the keybindings with `dendron:active` enabling a command only when dendron is active. 

We may further restrict additional Commands based on the open Filetype in preparation for Standalone vaults embedded inside a normal coding project.

This Context should be used inside the default Keybindings and inside the contribution point for the Command Palette. See the [vscode docs here](https://code.visualstudio.com/api/extension-guides/command#controlling-when-a-command-shows-up-in-the-command-palette) 

## Describe alternatives you've considered ##

An alternative could be to provide better Error messages.

**Comment by kevinslin** [comment]
This is a great idea especially since we already use context in a few places to set views (eg. https://github.com/dendronhq/dendron/blob/dev-kevin/packages/plugin-core/src/_extension.ts#L391:L391). 

Will make the update this week

**Comment by flammehawk** [comment]
I may also recommend using the enablement feature to make sure for commands that require a link to be selected for them to be only be enabled when a link is selected.

**Comment by amirography** [comment]
just a useless annoying +1

**Comment by kevinslin** [comment]
shipped with 0.40 :slight_smile:
