### ISSUE TITLE
Potential lookup improvements 

### ISSUE THREAD

**Issue by ognjenio** [dendronhq/dendron#674]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, **lookup**, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I've noticed that I've entirely stopped using lookup for lookup and just use it for creating notes. The VSCode quick open is better.

Some examples:

### The order of words

For instance, if you have a note called `notes.dendron-improvements`

If you type `dendron.notes` Dendron wont find the note but VSCode will.

### Space

I often find myself typing space instead of `-` and that doesn't work.

### Another example I can't quite explain. 

Real example. I've a note called: `resources.articles.other-things-you-re-allowed-to-do`
Here, lookup does not find it if you enter `allowed`. But `things-you` does find it. 

Similarly, `improvements` does not find `notes.dendron-improvements`.

I haven't figured out a pattern here. VSCode does find the files in both cases.

### No autocomplete

Given the hierarchy I instinctively press tab often expecting it to autocomplete.

### > doesn't activate actions

In VSCode quick open typing > brings up the actions. It might be a good idea if lookup could do that as well.

**Comment by aleksey-rowan** [comment]
This could be related to https://github.com/dendronhq/dendron/issues/136 or https://github.com/dendronhq/dendron/issues/494.

**Comment by flammehawk** [comment]
I would add to the Improvements the possibility to navigate the buttons in the lookup per keyboard. Currently, it's pretty hard, and if you enter the button row through tabbing, you have the problem of needing to still hover with the mouse over the buttons since you can't know which button does what.

**Comment by kpathakota** [comment]
+1 We should look at this as part of improving the base experience. FWIW, I use lookup for everything but based on your comment started playing around with quick open and ... it's really great. We will need to copy shamelessly from it and build it into lookup so you don't have two different ways of creating and looking up notes.

**Comment by kevinslin** [comment]
@ognjenio we improved the fuzzy search in lookup for v44. give it a go and please let us know if you're still experiencing similar issues: https://wiki.dendron.so/notes/72812fcd-3626-42d3-9d17-1f13f15431f3.html
