### ISSUE TITLE
Use of Frontmatter ID

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#681]
## Please Select if your Request is Either something new or an Enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [X] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [X] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

At the moment, the ID key of an individual note's frontmatter does not serve Dendron's note-taking purposes. To my understanding, as best informed by the documentation, the ID is used by Dendron when publishing to establish the URL. The frontmatter ID seems to play a very important role in publishing, but not much else outside of that. 

This request is similar to issue #620, but looks at it from the opposite direction.

## Describe the solution you'd like ##

There are two ways to change this that seem apparent to me:

Option 1) Make the frontmatter ID more usable in the note-taking phase. Give users the option to generate their own IDs, and make it possible to find notes based on their unique ID. That said, I am not sure what form this would take. Random strings are good for creating unique identifiers, but are not particularly human usable.

Option 2) Remove the ID from the frontmatter and the note-taking phase entirely. Instead, have the URL generated when the user decides to publish their vault(s). This would probably make the goal of "Friendly Titles for Permanent URLs" easier to achieve as well.

## Describe alternatives you've considered ##

Possibly there is a purpose that the frontmatter ID serves outside of publishing. If that is the case though, it is not made clear in Dendron's documentation. Updates to the [Features page](https://wiki.dendron.so/notes/2fe96d3a-dcf9-409b-8a09-fdaa5a664433.html#permanent-ids) and/or [Frontmatter page](https://wiki.dendron.so/notes/ffec2853-c0e0-4165-a368-339db12c8e4b.html) should be made as appropriate.

**Comment by kpathakota** [comment]
Thanks for pointing this out @micharris42. I'm thinking this is mostly a documentation related task - we use the frontmatter UUID so that we can index all your notes and have the index stay valid even if the file names change so it's a little bit of required implementation seeping out into the CX. Like you said, the friendly note URLs will be much nicer for publishing.

**Comment by shorty25h0r7** [comment]
+1 for micharris42's Option 1 -- I imagine this would make zettelkasten folks happy.

**Comment by kpathakota** [comment]
PR to fix documentation: https://github.com/dendronhq/dendron-site/pull/91

**Comment by micharris42** [comment]
Embarrassed to say I let this one get away from me. The Frontmatter page has been updated with the line:

"This identifier is used for two things: (1) generating unique URLs when notes are published and (2) ensuring each note in the index is unique."

Which makes clearer the purpose of the ID field during the note-taking phase. Marking this issue as Closed.
