### ISSUE TITLE
Backlinks Panel Has Stopped Working

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#682]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [X] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The Backlinks Panel has stopped working. The section remains empty, regardless of whether there are backlinks or not. I have tried restarting VSCodium and the issue persists.

## To Reproduce

1. Open a document for which there are backlinks.
2. The Backlinks Panel remains empty,

## Expected behavior

That the Backlinks Panel list backlinks.

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: NA
- Version: VSCodium 1.55.2, Dendron 0.39.1

## Dendron Log file

{"level":30,"time":1619741625277,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1619741625327,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logPath":"f:\\VSCodium Portable\\data\\user-data\\logs\\20210429T201325\\exthost1\\dendron.dendron","logLevel":"info","extensionPath":"f:\\VSCodium Portable\\data\\extensions\\dendron.dendron-0.39.1","extensionUri":{"$mid":1,"fsPath":"f:\\VSCodium Portable\\data\\extensions\\dendron.dendron-0.39.1","_sep":1,"path":"/F:/VSCodium Portable/data/extensions/dendron.dendron-0.39.1","scheme":"file"},"storagePath":"f:\\VSCodium Portable\\data\\user-data\\User\\workspaceStorage\\6ce6f8b7d9ec26e73bc29cc7ebab8560\\dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"f:\\Dendron\\dendron.code-workspace","_sep":1,"external":"file:///f%3A/Dendron/dendron.code-workspace","path":"/f:/Dendron/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault","_sep":1,"external":"file:///f%3A/Dendron/vault","path":"/f:/Dendron/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1619741625329,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1619741625332,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1619741625333,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1619741630363,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","config":{"vaults":[{"fsPath":"vault"}],"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","useFMTitle":true,"usePrettyRefs":true},"version":0,"initializeRemoteVaults":true},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1619741630541,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","files.autoSave":"off","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on","markyMarkdown.statisticStatusBarItem":"Words","explorer.sortOrder":"modified"},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","github.github-vscode-theme"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]},"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links"]},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1619741630623,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.39.1","migratedGlobalVersion":"0.39.1","previousGlobalVersion":"0.39.0","previousWsVersion":"0.39.1","platform":"win32","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.30","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.20","active":false},{"id":"github.github-vscode-theme"}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1619741630624,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"startServer","logLevel":"info"}
{"level":30,"time":1619741630640,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","msg":"post-start-server","port":54639,"durationStartServer":5310}
{"level":30,"time":1619741630644,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"logger","ctx":"FileStorageV2","wsRoot":"f:\\Dendron","vaultsv3":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1619741630698,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1619741726600,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"logger","ctx":"parseSchemaModuleOpts","fname":"root","root":{"fsPath":"vault"},"imports":[]}
{"level":30,"time":1619741733912,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:init","msg":"enter","opts":{}}
{"level":30,"time":1619741733913,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:createServerWatcher","msg":"enter","opts":{}}
{"level":30,"time":1619741734049,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":103343}
{"level":30,"time":1619741734049,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1619741734049,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1619741734050,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1619741734051,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1619741734051,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1619741734054,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1619741734570,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1619741734587,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1619741734595,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1619741734596,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":109251}
{"level":30,"time":1619741734597,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.39.1","previousVersion":"0.39.1"}
{"level":30,"time":1619741734597,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1619741736397,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1619741736975,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:_connect","portCreated":3373865674955,"wsActivation":1619741630542}
{"level":30,"time":1619741736977,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:_connect","msg":"initFromExistingFile","port":54639}
{"level":30,"time":1619741736977,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:tryToConnect","port":54639,"msg":"enter"}
{"level":30,"time":1619741736994,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:tryToConnect","msg":"connected","info":{"version":"0.39.1"}}
{"level":30,"time":1619741736994,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"checking for engine"}
{"level":30,"time":1619741736994,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"found engine"}
{"level":30,"time":1619741736994,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"connector","ctx":"EngineConnector:initEngine","msg":"enter","port":54639}
{"level":30,"time":1619741743161,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\index.bookshelf.md","_sep":1,"external":"file:///f%3A/Dendron/vault/index.bookshelf.md","path":"/f:/Dendron/vault/index.bookshelf.md","scheme":"file"}}
{"level":30,"time":1619741758697,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.29.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.29.md","path":"/f:/Dendron/vault/journal.2021.04.29.md","scheme":"file"}}
{"level":30,"time":1619741759881,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\index.bookshelf.md","_sep":1,"external":"file:///f%3A/Dendron/vault/index.bookshelf.md","path":"/f:/Dendron/vault/index.bookshelf.md","scheme":"file"}}
{"level":30,"time":1619741841248,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.29.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.29.md","path":"/f:/Dendron/vault/journal.2021.04.29.md","scheme":"file"}}
{"level":30,"time":1619741842155,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\index.bookshelf.md","_sep":1,"external":"file:///f%3A/Dendron/vault/index.bookshelf.md","path":"/f:/Dendron/vault/index.bookshelf.md","scheme":"file"}}
{"level":30,"time":1619741894027,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2019.09.22.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2019.09.22.md","path":"/f:/Dendron/vault/journal.2019.09.22.md","scheme":"file"}}
{"level":30,"time":1619741895315,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\journal.2021.04.29.md","_sep":1,"external":"file:///f%3A/Dendron/vault/journal.2021.04.29.md","path":"/f:/Dendron/vault/journal.2021.04.29.md","scheme":"file"}}
{"level":30,"time":1619741897081,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\index.bookshelf.md","_sep":1,"external":"file:///f%3A/Dendron/vault/index.bookshelf.md","path":"/f:/Dendron/vault/index.bookshelf.md","scheme":"file"}}
{"level":30,"time":1619742076506,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\Dendron\\vault\\index.bookshelf.md","_sep":1,"external":"file:///f%3A/Dendron/vault/index.bookshelf.md","path":"/f:/Dendron/vault/index.bookshelf.md","scheme":"file"}}
{"level":30,"time":1619742091107,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"l:run","msg":"pre-execute"}
{"level":30,"time":1619742091107,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1619742091135,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"l:run","msg":"post-execute"}
{"level":30,"time":1619742091340,"pid":7104,"hostname":"DESKTOP-5S6FAKL","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"f:\\VSCodium Portable\\data\\user-data\\logs\\20210429T201325\\exthost1\\dendron.dendron\\dendron.log","_sep":1,"external":"file:///f%3A/VSCodium%20Portable/data/user-data/logs/20210429T201325/exthost1/dendron.dendron/dendron.log","path":"/f:/VSCodium Portable/data/user-data/logs/20210429T201325/exthost1/dendron.dendron/dendron.log","scheme":"file"}}

**Comment by kevins8** [comment]
Hmm, we had an issue in 0.39 where we weren't properly caching backlinks.
Can you `rm .dendron.cache.json`? This should fix the issue.
