### ISSUE TITLE
4

### ISSUE THREAD

**Issue by Shamil-Ibragimov** [dendronhq/dendron#691]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by hikchoi** [comment]
closing this as this also seem to be mistakenly submitted? (like #690 )
