### ISSUE TITLE
CTRL + t but no timestamp

### ISSUE THREAD

**Issue by ericthomas1** [dendronhq/dendron#693]
This is probably an easy one and I'm just missing something but...

**When I attempt to use `CTRL+t` to insert a timestamp, the search bar opens to some kind of markdown search.**
 
![image](https://user-images.githubusercontent.com/42788729/117039411-98f63200-acbd-11eb-824d-68a6d78e4530.png)

**I looked in my Keyboard Shortcuts, but it appears only `CTRL+SHFT+t` (CTRL + capital "t") is mapped:**

![image](https://user-images.githubusercontent.com/42788729/117039590-cd69ee00-acbd-11eb-99c5-fb93bc89e9c2.png)

How do I use `CTRL+t` in Dendron to insert a timestamp?

**Comment by kevins8** [comment]
CTRL+t timestamp, that isn't supported by Dendron. Do you mean the `-t`
snippet that enters the timestamp?

**Comment by ericthomas1** [comment]
Thanks for the reply. I was mistaken. Just went ahead and created my own snippet. 

**For anyones benefit:**

```
"Timestamp": {
            "prefix": "stime",
            "body": [
                "${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}-08:00",
            ],
            "description": "New timestamp"
        },
```
