### ISSUE TITLE
LaTeX not rendering properly

### ISSUE THREAD

**Issue by RafaelCotrim** [dendronhq/dendron#694]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug

LaTeX functions are not properly rendered in version 0.10.31. It has no problem rendering normal text and symbols, but anything that starts with `\` is not converted into the appropriate math visuals. For example, $\sum$ is rendered as *sum* instead of ∑.

## To Reproduce

1. Create a vault
2. Write any valid LaTeX containing an element that starts with `\`
3. Display on the markdown preview

## Expected behavior

LaTeX elements containing `\` should be rendered properly.

## Screenshots

Current behavior:
![image](https://user-images.githubusercontent.com/46679150/117041056-74707900-ad02-11eb-8859-5c80191f4559.png)

Expected behavior (working in version 0.10.30):
![image](https://user-images.githubusercontent.com/46679150/117041411-d16c2f00-ad02-11eb-9910-fb9eed8f20e6.png)

## Desktop (please complete the following information)

- OS: Windows 10 
- Browser chrome

## Dendron Log file

{"level":30,"time":1620147655794,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1620147655876,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logPath":"c:\\Users\\rafin\\AppData\\Roaming\\Code\\logs\\20210504T145222\\exthost1\\dendron.dendron","logLevel":"info","extensionPath":"c:\\Users\\rafin\\.vscode\\extensions\\dendron.dendron-0.40.1","extensionUri":{"$mid":1,"fsPath":"c:\\Users\\rafin\\.vscode\\extensions\\dendron.dendron-0.40.1","_sep":1,"path":"/c:/Users/rafin/.vscode/extensions/dendron.dendron-0.40.1","scheme":"file"},"storagePath":"c:\\Users\\rafin\\AppData\\Roaming\\Code\\User\\workspaceStorage\\64bffb97e454d49d73f213bdb88be7c0\\dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"c:\\Users\\rafin\\source\\repos\\Worldbuild-vscode\\dendron.code-workspace","_sep":1,"external":"file:///c%3A/Users/rafin/source/repos/Worldbuild-vscode/dendron.code-workspace","path":"/c:/Users/rafin/source/repos/Worldbuild-vscode/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"c:\\Users\\rafin\\source\\repos\\Worldbuild-vscode\\vault","_sep":1,"external":"file:///c%3A/Users/rafin/source/repos/Worldbuild-vscode/vault","path":"/c:/Users/rafin/source/repos/Worldbuild-vscode/vault","scheme":"file"},"name":"vault","index":0}]}
{"level":30,"time":1620147655881,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1620147655891,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1620147655892,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1620147656199,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"vault"}],"useFMTitle":true,"useNoteTitleForLink":true,"noAutoCreateOnDefinition":true,"noLegacyNoteRef":true,"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","usePrettyRefs":true,"title":"Dendron","description":"Personal knowledge space","duplicateNoteBehavior":{"action":"useVault","payload":["vault"]}},"initializeRemoteVaults":true},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1620147665905,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"vault"}],"settings":{"dendron.rootDir":".","files.autoSave":"onFocusChange","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on","spellright.language":["en"]},"extensions":{"recommendations":["dendron.dendron-paste-image","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","github.github-vscode-theme"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1620147665915,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.40.1","migratedGlobalVersion":"0.40.0","previousGlobalVersion":"0.39.1","previousWsVersion":"0.40.0","platform":"win32","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.30","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.20","active":false},{"id":"github.github-vscode-theme","version":"4.1.1","active":false}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1620147665917,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"startServer","logLevel":"info"}
{"level":30,"time":1620147665932,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"_activate","msg":"post-start-server","port":56092,"durationStartServer":10051}
{"level":30,"time":1620147665936,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"logger","ctx":"FileStorageV2","wsRoot":"c:\\Users\\rafin\\source\\repos\\Worldbuild-vscode","vaultsv3":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1620147665937,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1620147666306,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:init","msg":"enter","opts":{}}
{"level":30,"time":1620147666306,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:createServerWatcher","msg":"enter","opts":{}}
{"level":30,"time":1620147666557,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":249}
{"level":30,"time":1620147666557,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1620147666558,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1620147666558,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1620147666559,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"postReloadWorkspace","msg":"preUpgrade: new wsVersion"}
{"level":30,"time":1620147666560,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"h:run","msg":"pre-execute"}
{"level":30,"time":1620147666560,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"UpgradeSettingsCommand","ctx":"Upgrade:execute"}
{"level":30,"time":1620147666615,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"WorkspaceConfig:update","vscodeDir":"c:\\Users\\rafin\\source\\repos\\Worldbuild-vscode\\vault\\.vscode","snippetChanges":{}}
{"level":30,"time":1620147666615,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"Upgrade:execute","newConfig":{"extensions":{},"settings":{"add":{},"errors":{}},"snippetChanges":{}}}
{"level":30,"time":1620147666615,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"Upgrade:execute","badExtensions":[]}
{"level":30,"time":1620147666615,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"h:run","msg":"post-execute"}
{"level":30,"time":1620147666616,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"postReloadWorkspace","msg":"postUpgrade: new wsVersion","previousWsVersion":"0.40.0","newVersion":"0.40.1"}
{"level":30,"time":1620147666639,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1620147666639,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1620147666642,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1620147666645,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1620147666647,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1620147666648,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":10760}
{"level":30,"time":1620147666648,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.40.1","previousVersion":"0.40.0"}
{"level":30,"time":1620147666648,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1620147666648,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"new version","version":"0.40.1","previousVersion":"0.40.0"}
{"level":30,"time":1620147669321,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:_connect","portCreated":1620147665939,"wsActivation":1620147665905}
{"level":30,"time":1620147669323,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:_connect","msg":"initFromExistingFile","port":56092}
{"level":30,"time":1620147669323,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:tryToConnect","port":56092,"msg":"enter"}
{"level":30,"time":1620147669353,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:tryToConnect","msg":"connected","info":{"version":"0.40.1"}}
{"level":30,"time":1620147669353,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"checking for engine"}
{"level":30,"time":1620147669353,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"found engine"}
{"level":30,"time":1620147669353,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"connector","ctx":"EngineConnector:initEngine","msg":"enter","port":56092}
{"level":30,"time":1620147685841,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\rafin\\source\\repos\\Worldbuild-vscode\\vault\\test.md","_sep":1,"external":"file:///c%3A/Users/rafin/source/repos/Worldbuild-vscode/vault/test.md","path":"/c:/Users/rafin/source/repos/Worldbuild-vscode/vault/test.md","scheme":"file"}}
{"level":30,"time":1620147701024,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"c:\\Users\\rafin\\source\\repos\\Worldbuild-vscode\\vault\\test.md","reason":3,"msg":"enter"}
{"level":30,"time":1620147701026,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","match":["updated: 1620147529748"],"msg":"update activeText editor"}
{"level":30,"time":1620147701692,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"c:\\Users\\rafin\\source\\repos\\Worldbuild-vscode\\vault\\test.md","_sep":1,"path":"/c:/Users/rafin/source/repos/Worldbuild-vscode/vault/test.md","scheme":"file"}}
{"level":30,"time":1620147701701,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"test","msg":"exit"}
{"level":30,"time":1620147814411,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"l:run","msg":"pre-execute"}
{"level":30,"time":1620147814411,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1620147814436,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"l:run","msg":"post-execute"}
{"level":30,"time":1620147814592,"pid":4240,"hostname":"LAPTOP-66IBOK8J","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\rafin\\AppData\\Roaming\\Code\\logs\\20210504T145222\\exthost1\\dendron.dendron\\dendron.log","_sep":1,"external":"file:///c%3A/Users/rafin/AppData/Roaming/Code/logs/20210504T145222/exthost1/dendron.dendron/dendron.log","path":"/c:/Users/rafin/AppData/Roaming/Code/logs/20210504T145222/exthost1/dendron.dendron/dendron.log","scheme":"file"}}

**Comment by funnym0nk3y** [comment]
I'm having this issue too. Updating to the latest version of vscode (1.56) and dendron (0.40.2) broke my Latex rendering with Mathjax and Katex.

**Comment by Mikcl** [comment]
Same issue here

**Comment by Mikcl** [comment]
The current version of Dendron works fine for me.

The error was in 'Dendron Markdown Preview Enhanced' v0.10.31. downgrading to v0.10.30 made it work.

**Comment by kpathakota** [comment]
Yup, this is repro'ing and downgrading to 10.30 has made it work for me too. Will look into what changed to figure out what's going on.

**Comment by kevinslin** [comment]
This has just been fixed in 10.32. Thanks for reporting the issue @RafaelCotrim

**Comment by kpathakota** [comment]
@all-contributors please add @RafaelCotrim for bug
