### ISSUE TITLE
Adding a template before adding the actual note breaks adding new notes

### ISSUE THREAD

**Issue by lsernau** [dendronhq/dendron#699]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug
Adding a template before adding the actual note the template points to leads to a hard error when the note is finally created. After that, no notes can be added without triggering the error. A full restart seems to be necessary to clear it.

## To Reproduce

1. Add a schema with a template pointing to a note that does not yet exist.
2. Try to create the note.
3. Error.

## Expected behavior

At the very least there should be a warning that you can't do this. Better would be having bad template references just do nothing.

## Desktop (please complete the following information)

- OS: Windows
- Browser: several! Not sure what to put here.
- Version: stable

## Dendron Log file

These logs contain a bunch of stuff about my filesystem I'd rather not have on a public forum. If reproing turns out to be nontrivial I'll go through it myself and figure out how to make it happen.

**Comment by lsernau** [comment]
Update: actually, doing this in the other order also causes a hard error. Basically I don't know how to use templates without causing an error.

**Comment by flammehawk** [comment]
Does this happen in a brand new vault? 

That could make it easier to repro since my existing Vault does not have the Error @lsernau

**Comment by lsernau** [comment]
Yes, for me anyway.

**Comment by flammehawk** [comment]
Do you have docker on your system installed?
If yes, you could create a Devcontainer for the dendron Workspace, open the workspace in the container, repro the error, and then create the diagnostic report, limiting the personal information inside the log. 
I could set up a basic repo to check out and reproduce your error.

**Comment by lsernau** [comment]
No Docker, unfortunately. But I'm finding that this is a pretty flaky repro for me as well. I've tinkered with it and I think I have a more specific repro:
1. create a new empty workspace.
2. copy-paste the attached schema file to replace root.schema.yml
3. create a note called "modules"
4. create a note called "modules.a"
5. create a note called "modules.a.methods"
6. reindex the workspace
7. Verify that typing "modules.a.methods" into the search bar shows the schema book icon. (If not re-reindex)
7. create a note called "modules.a.methods.b"
[root.schema.zip](https://github.com/dendronhq/dendron/files/6433355/root.schema.zip)

".
8. Error

**Comment by flammehawk** [comment]
Gotcha you need to remove the `.md` extension from the template then it works. @lsernau

**Comment by lsernau** [comment]
That only fixes the issue if I have created the template file already. If the template file does not exist, there's a hard error. To be clear, I'm OK with getting a message that tells me I've done something wrong in this case. But the current behavior is to direct me to file a bug. Sometimes it seems to crash the runtime and I have to restart it.

**Comment by Harshita-mindfire** [comment]
This functionality has been updated in the newer releases of Dendron. In the above-mentioned case, Dendron now displays a warning for template note not found. Feel free to ping here if it does not work in the latest release(v0.105).
