### ISSUE TITLE
Port number not changed completely by config

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#705]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug
Followed the wiki instructions by adding "previewPort: 8999" into my config file (dendron.yml)
it has not fully change the port (some resources keep using 8080)
.
I need to use an other port than 8080 (used by a Nginx project)

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kpathakota** [comment]
Filed on behalf of @bonnebulle, more details will be needed to figure out what's going on here (particularly log output).

**Comment by bonnebulle** [comment]
# My bug  aply to :
Misc (Choose this if your not sure) 
or pre-publishing (previewing)

# Description of my bug (problem)
I followed the wiki instructions by adding "previewPort: 8999" into my config file (dendron.yml)
it has not fully change the port (some resources keep using 8080)
## Contexte
I need to use an other port than 8080 (used by a Nginx project)

# To Reproduce
A. with default port 8080 (and no other app/service like nginx using this port)
1. Open a Dendron workspace 
2.  Wait extension loading
3. open Commande Palette > Dendron: Site Preview
4. loading popup (into Code), done
5. It openning my web browser (localhost:8080)
6. All is fine

B. The same but trying using an other port like 8999 (a free one too)
1.  I add `previewPort: 8999` into vault/dendron.yml and /dendron.yml like
...
site:
    previewPort: 8999
    copyAssets: true
...
2. I lanch previewing (like in A.) 
3. It openning my web browser (localhost:8080)  (like in A.) 
4. Some resources in the page not loading correctly (error with port 8999)
5. Of course the page localhost:8999 not showing the content...

![Dendron error screenshoot](https://vincent-bonnefille.fr/pj/private/dendron%20export%20port.png)

I check my ports with `netstat -tunlp | grep 8080`
`tcp6       0      0 :::8080                 :::*                    LISTEN      26782/codium`
8999 port output nothing

# OS 
Debian 10 aarch64
using Chrome / Chromium / Firefox (up to date)
Am using VSCodium v1.55.2

#Aditional contexte
I new on Dendron, I setting up.

# Debug parts

`
{"level":30,"time":1620469094836,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"buildSite","eleventyPath":"/home/pi/Dendron/node_modules/@dendronhq/dendron-11ty"}
{"level":30,"time":1620469094998,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"d:run","msg":"pre-execute"}
{"level":30,"time":1620469094999,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"SitePreviewCommand","msg":"enter"}
{"level":30,"time":1620469095002,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"buildSite","eleventyPath":"/home/pi/Dendron/node_modules/@dendronhq/dendron-11ty"}
{"level":50,"time":1620469095560,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"d:run","err":{"type":"r","message":"","stack":"Error: \n\tat d.run (/home/pi/.vscode-oss/extensions/dendron.dendron-0.40.2/dist/extension.js:9:104648)\n\tat processTicksAndRejections (internal/process/task_queues.js:97:5)\n\tat async /home/pi/.vscode-oss/extensions/dendron.dendron-0.40.2/dist/extension.js:9:79492\n\tat async S._executeContributedCommand (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106762)","status":"unknown","msg":"","payload":"{\"msg\":\"listen EADDRINUSE: address already in use :::8080\",\"stack\":\"Error: listen EADDRINUSE: address already in use :::8080\\n\\tat Server.setupListenHandle [as _listen2] (net.js:1313:16)\\n\\tat listenInCluster (net.js:1361:12)\\n\\tat Server.listen (net.js:1447:7)\\n\\tat Function.b.listen (/home/pi/.vscode-oss/extensions/dendron.dendron-0.40.2/dist/extension.js:558:4563)\\n\\tat /home/pi/.vscode-oss/extensions/dendron.dendron-0.40.2/dist/extension.js:670:79069\"}"}}`

`
{"level":30,"time":1620469099586,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/vault/dendron.md","path":"/home/pi/Dendron/vault/dendron.md","scheme":"file"}}
{"level":30,"time":1620469099617,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"dendron","msg":"exit"}
{"level":30,"time":1620469226515,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/vault/dendron.yml","external":"file:///home/pi/Dendron/vault/dendron.yml","path":"/home/pi/Dendron/vault/dendron.yml","scheme":"file"}}
{"level":30,"time":1620469237110,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/home/pi/Dendron/vault/dendron.yml","reason":3,"msg":"enter"}
{"level":30,"time":1620469243820,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/home/pi/Dendron/vault/dendron.yml","reason":3,"msg":"enter"}
{"level":30,"time":1620469286502,"pid":26782,"hostname":"raspberrypi","name":"dendron","msg":"server closed"}
{"level":30,"time":1620469286504,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"d:run","msg":"post-execute"}
{"level":30,"time":1620469301786,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/dendron.yml","external":"file:///home/pi/Dendron/dendron.yml","path":"/home/pi/Dendron/dendron.yml","scheme":"file"}}
{"level":30,"time":1620469317142,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/home/pi/Dendron/dendron.yml","reason":3,"msg":"enter"}
{"level":30,"time":1620469318406,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/home/pi/Dendron/dendron.yml","reason":3,"msg":"enter"}
{"level":30,"time":1620469324251,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/home/pi/Dendron/dendron.yml","reason":1,"msg":"enter"}
{"level":30,"time":1620469328265,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"d:run","msg":"pre-execute"}
{"level":30,"time":1620469328266,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"SitePreviewCommand","msg":"enter"}
{"level":30,"time":1620469328272,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"buildSite","eleventyPath":"/home/pi/Dendron/node_modules/@dendronhq/dendron-11ty"}
{"level":30,"time":1620469331767,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"VaultWatcher:onDidChange","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/vault/dendron.md","path":"/home/pi/Dendron/vault/dendron.md","scheme":"file"}}
{"level":30,"time":1620469332083,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"VaultWatcher:onDidChange","fname":"dendron","msg":"exit"}
{"level":30,"time":1620469381497,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/vault/dendron.yml","external":"file:///home/pi/Dendron/vault/dendron.yml","path":"/home/pi/Dendron/vault/dendron.yml","scheme":"file"}}
{"level":30,"time":1620469834537,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/build/site/assets/css/just-the-docs-default.css","external":"file:///home/pi/Dendron/build/site/assets/css/just-the-docs-default.css","path":"/home/pi/Dendron/build/site/assets/css/just-the-docs-default.css","scheme":"file"}}
{"level":30,"time":1620469871220,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/build/site/assets/js/just-the-docs.js","external":"file:///home/pi/Dendron/build/site/assets/js/just-the-docs.js","path":"/home/pi/Dendron/build/site/assets/js/just-the-docs.js","scheme":"file"}}
{"level":30,"time":1620470375908,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/vault/dendron.yml","external":"file:///home/pi/Dendron/vault/dendron.yml","path":"/home/pi/Dendron/vault/dendron.yml","scheme":"file"}}
{"level":30,"time":1620470391952,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"tasks","external":"output:tasks","path":"tasks","scheme":"output"}}
{"level":30,"time":1620470398386,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/vault/dendron.yml","external":"file:///home/pi/Dendron/vault/dendron.yml","path":"/home/pi/Dendron/vault/dendron.yml","scheme":"file"}}
{"level":30,"time":1620470581925,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/Dendron/.vscode/launch.json","external":"file:///home/pi/Dendron/.vscode/launch.json","path":"/home/pi/Dendron/.vscode/launch.json","scheme":"file"}}
{"level":30,"time":1620470788374,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1620470788377,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1620470788628,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1620470789374,"pid":26782,"hostname":"raspberrypi","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pi/.config/VSCodium/logs/20210508T120836/exthost1/dendron.dendron/dendron.log","external":"file:///home/pi/.config/VSCodium/logs/20210508T120836/exthost1/dendron.dendron/dendron.log","path":"/home/pi/.config/VSCodium/logs/20210508T120836/exthost1/dendron.dendron/dendron.log","scheme":"file"}}
`

**Comment by bonnebulle** [comment]
I nearly "fix it" by search-replace port 8080 in the extension file `~/.vscode-oss/extensions/dendron.dendron-0.40.2/dist/extension.js` (related to `process.env.ELEV_PORT`) 
It is a non real fix, I will search solutions arround `process.env.ELEV_PORT`
I noticed the links in my page are not correcly directed (still port 8080)

**Comment by kevinslin** [comment]
This setting currently only works when you run using the CLI: https://wiki.dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#previewport

**Comment by kevinslin** [comment]
Yeah, it is but I admit the documentation can be better. In any case, we'll
be supporting both by end of the week so it might not be an issue.

**Comment by kevinslin** [comment]
This is now fixed in 0.41
