### ISSUE TITLE
Create, delete, move notes/journal entries outside of Dendron (e.g. across machines)?

### ISSUE THREAD

**Issue by jfinken** [dendronhq/dendron#71]
**Describe the bug**
I'm dying for a replacement for my current note-taking/journaling system (MS OneNote online), which A) sucks in general, and B) dies under the weight of too many notes.

Your goals and Dendron resonate, I like VSCode integration (and all that it comes with, MD Preview Enhanced, vim, etc).  So these are more of questions than bug reports (and likely I am misusing Dendron).

Does Dendron support the creation and deletion of notes and journal entries via the filesystem (linux and macOS in my case)?  If I create, delete, move or rename a note or journal entry via the shell/filesystem, Lookup seems to get confused, can no longer traverse the Hierarchy, and simply doesn't find existing notes.  Even after I reload the index.

**To Reproduce Use-Case 1**
1. Create a New Journal Note
2. Rt-click on it via the VSCode Explore and Delete.  _OR_ just remove it via the filesystem.
3. `Ctrl-L` to Lookup.  It doesn't see any existing notes.  

**To Reproduce Use-Case 2: multiple machines + git**
1. Given I have multiple machines, I'd like like to use git + a private git remote and use Dendron notes/journal entries across these machines.  Is this an intended use case?  Better ideas on synchronizing Dendron notes/journal across machines?
2. Clone an existing Dendron-based workspace git repo to second machine (or even to a new path on the same machine)
3. Open this Dendron workspace in VSCode.  
4. `Ctrl-L` to Lookup.  It doesn't see any existing notes.  

I suspect whatever indexing system/data structures you're using under the VSCode hood doesn't like when things happen outside of Dendron.  

Thoughts?

**Desktop (please complete the following information):**
 
OS A):

    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.4 LTS
    Release:	18.04
    Codename:	bionic
    Window mgr:     i3

OS B):

    15-inch MBP
    macOS Mojave 10.14.4

VSCode version for OS A):

    Version:  1.47.2
    Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
    Date: 2020-07-15T18:22:15.161Z
    Electron: 7.3.2
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Linux x64 5.4.0-42-generic

VSCode version for OS B):

    Version: 1.47.3
    Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
    Date: 2020-07-23T13:08:29.692Z
    Electron: 7.3.2
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Darwin x64 18.5.0

**Comment by kevinslin** [comment]
Hey @jfinken

Thanks for using dendron and you're all good. I'm still working on updating the docs so if something is confusing, it's most likely something I can improve on my end 😅  

Also heads up that I'm doing optional 30min onboarding with new users to help folks get started. If you're interested, you can book a zoom slot [here](https://calendly.com/thence/meet).

### To Reproduce Use-Case 1
This is a known issue. Working on properly handling this case and will be fixed this week. Tracking issue https://github.com/dendronhq/dendron/issues/72

Current workaround is to run `Dendron: Reload Index` after deletion. 

### To Reproduce Use-Case 2: multiple machines + git

Yes, it is. The default workspace settings had it set to an absolute path pre 0.5 which is why it didn't work across git repositories. The default has now been updated. You can fix your existing setting by making the following changes in your `dendron.code-workspace` file:

- dendron indexes the first folder as the vault. make sure this is a relative path
```json
"folders": [
        {
            "path": "vault"
        },
    ],
```
- update `dendron.rootDir` to be relative
```json
"settings": {
    "dendron.rootDir": "."
}
```

**Comment by jfinken** [comment]
Many thanks for getting back to me @kevinslin .  After a fresh clone of my little `journal` repo, I've reloaded the index, `"path": "vault"` is set, as is the `"dendron.rootDir": "."`.  Still nothing on `Lookup`.  So I'm sure I'm messing up something.

```
$ tree journal/
journal/
├── dendron.code-workspace
├── dendron.yml
└── vault
    ├── backlog.journal.2020-07-28.md
    ├── backlog.journal.2020-08-03.md
    ├── dendron.schema.yml
    ├── root.md
    └── root.schema.yml

1 directory, 7 files
```
Thanks for the onboarding offer!  I'll take you up on it.  If a particular slot already has someone signed-up I'd be happy to try join that time if I can to save you time.  Thanks!

**Comment by kevinslin** [comment]
hmm, there doesn't seem to be anything wrong from looking at your journal. and do you have the latest dendron (5.0) installed on both operating systems? 

two things. if you run `Dev:Dendron: Open Logs`, you'll get a log file open on vscode. If you could attach the log after trying to do a lookup, that will help me debug. 

As for slots, these are meant to be one on one slots so its all good.

**Comment by kevinslin** [comment]
heads up that deleting notes outside of vscode has been fixed as of 0.5.4 :)

**Comment by kevinslin** [comment]
dendron 0.5.7 should have fixed this issue. can you confirm after you have a chance to upgrade?

**Comment by jfinken** [comment]
With 0.5.7, Lookup definitely seems better and/or fixed altogether.  Great work!

**Comment by kevinslin** [comment]
glad to hear it. closing issue then. feel free to issue more if you come across something :)
