### ISSUE TITLE
Some Chars Converted To Hex Representation After Performing `> Dendron: Refactor Hierarchy`

### ISSUE THREAD

**Issue by shorty25h0r7** [dendronhq/dendron#710]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Colons are converted to their unicode hex representation after performing a hierarchy refactor.

## To Reproduce

- Perform a hierarchy refactor with colons ":" in the note body. 
- The colon will be converted to "&#x3A;".

(This also occurs with emojis)

## Additional context

~~I'm not 100% sure if this is exactly what's going on -- I'm partly guessing based on my workflow.~~

**Comment by kpathakota** [comment]
Yes, this is a known issue #572. Dup'ing to that and closing this one. We will try to prioritize 572 asap.
