### ISSUE TITLE
Telemetry opt-out setting

### ISSUE THREAD

**Issue by SyrupThinker** [dendronhq/dendron#711]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Because only my `settings.json` is shared across VSCode installations, I need to opt out of telemetry on every system I use.
Additionally I already provide VSCode with a telemetry preference via the `telemetry.enableTelemetry` setting.

## Describe the solution you'd like ##

Dendron should respect the existing system for telemetry opt-out by using the [`isTelemetryEnabled API`](https://code.visualstudio.com/docs/getstarted/telemetry#_for-extension-authors).

It could provide an override, asking for explicit consent, to enable telemetry just for Dendron,
which would ideally be stored somewhere more persistent like `settings.json`.

## Describe alternatives you've considered ##

- Make telemetry opt-in, which goes against the documented rationale of making it opt-out
- Only add the opt-out to the `settings.json`, ignoring `isTelemetryEnabled`, which to me seems quite rude

## Additional context ##

My primary reason for disabling telemetry is, that I heavily dislike the collection of a UUID, as it reduces the anonymity of the data.

**Comment by kpathakota** [comment]
Thanks for reporting @SyrupThinker, will strive to include in next week's release.
