### ISSUE TITLE
Dendron Insert note link command

### ISSUE THREAD

**Issue by vicrdguez** [dendronhq/dendron#722]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##
Creating links is a crucial part on PKM, no difference in Dendron. In my opinion creating a wiki link is not very 
consistent yet:
- If you start writing and make a typo and delete a char, you loose completion 
- pressing `ctrl-space` brings back completion but starts completing from the last dot.

This makes linking more uncomfortable.

## Describe the solution you'd like ##

I Think a good solution could be having a _insertNoteLink_ command that uses the lookup for searching
the note you want without the completion caveats.

This could be extended to a two phase input where after asking for the link you get prompted for a label. 
This possibility will be configurable by an argument to the command (`promptForLabel: true|false`)

## Additional context ##

This is as well another approach for #702 and I think it could potentially solve #473 as well

**Comment by kpathakota** [comment]
This is an excellent idea. Tagging to the next milestone for now for discussion. I see a lot of value in reducing the friction of creating links.

**Comment by kevinslin** [comment]
delivered in v44!
