### ISSUE TITLE
Obsidian Import

### ISSUE THREAD

**Issue by fi0** [dendronhq/dendron#723]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug

After importing from an obsidian vault, the content of the imported all markdown files become `[object Promise]`.

## To Reproduce

Run `Dendron: import pod`
Configure the path
Run `Dendron: import pod` again

## Expected behavior

The original markdown content should be imported, instead of a promise.

## Desktop (please complete the following information)

- OS: mac
- Version: v41

**Comment by kpathakota** [comment]
Yeah, I'm running into a never-ending import on Windows. Will try this again on mac to see if I can repro this particular problem.

**Comment by mixszh** [comment]
Hello all

**Comment by mixszh** [comment]
Thanks Kevin

**Comment by kpathakota** [comment]
@mixszh - v43 is the current milestone (will ship next week). We plan on investigating/getting to the bottom of this issue.

**Comment by kevinslin** [comment]
this is now fixed in v43.1
