### ISSUE TITLE
Can't create new links

### ISSUE THREAD

**Issue by jn64** [dendronhq/dendron#726]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

According to [Getting Started](https://wiki.dendron.so/notes/d758fe38-558c-4f20-a091-cac146a781cb.html#creating-a-note-with-a-link), I should create new links by pressing F12. It does not work.

I assume F12 refers to VSCode default keybinding for _Go to Definition_ since F12 is not defined in the keybindings for Dendron or its recommended extensions.

## To Reproduce

1. Type `[[foo]]` (where `foo` is not the name of an existing note)
2. Move cursor inside brackets
3. Press F12
4. Message shown:
   > No definition found for 'foo'

## Expected behavior

New note should be created with name `foo` (and automatically opened?)

## Desktop (please complete the following information)

- OS: Fedora 33
- dendron.dendron-0.41.0

## Additional context

The Getting Started guide should not say "press F12" if it depends on the user's VSCode keybindings outside of Dendron. It should mention the name of the command that can be found in the command palette.

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kpathakota** [comment]
Yes, we'll update this. We've updated the default behavior recently (fixing #430). This should say use >Dendron: Goto Note (that should create the note). 

Thanks for the catch @jn64!

**Comment by kpathakota** [comment]
@all-contributors give @jn64 credit for catching a bug
