### ISSUE TITLE
Leave a trace on source note when using selectionExtract

### ISSUE THREAD

**Issue by vicrdguez** [dendronhq/dendron#737]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

When you use your daily note as the main entry point for capturing quick ideas
you might want to move that content to its own note so you can curate the concept and link it. For that matter
the `selectionExtract` option is very handy.

However (at least In my case) I loose track on where the idea was originated, or when I captured the information.

I think this is applicable to any kind of note, not just journals.

## Describe the solution you'd like ##

I think leaving a little trace in the source note showing where that content is now. Something simple like:
```markdown
moved to => ![[dest.note]]
```
If you revisit the source, you have all the context because the content is still there. and if you visit
the destination, you have the backlink pointing to where the idea was born.

This could be configurable (probably on a command basis if the support for arguments exist) for folks that
could find this not useful.

**Comment by kevinslin** [comment]
It's also a good first task that I'm happy to pair or spend time with people to go through 😇

**Comment by vicrdguez** [comment]
@kevins8 I would love to take this one or the other one you suggested on discord :) Some little guidance on where to look first would be nice!

**Comment by vicrdguez** [comment]
> +1 on this. It's a good option to have as a configuration. I think the default should be the current behavior (because you wouldn't necessarily want many links cluttering up the source note) but I could envision a workflow that works well with what's being asked for here. 

And yes I'm agree! if this become a thing should be configurable and  not the default

**Comment by hikchoi** [comment]
This is great. I use selectionExtract by default and I always have to go back to mark where the extraction was and the context switch always breaks my train of thought 😄  Can't wait for this to be pushed!

**Comment by kevinslin** [comment]
@vicrdguez realize I didn't respond to this. Let me know if your still interested.

[here](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/commands/RefactorHierarchyV2.ts#L61:L61) is where the code needs to be update

To get started on the development, you can follow the instructions in our [contribution guide](https://wiki.dendron.so/notes/81da87be-2d4e-47b5-a1d6-c0d647e1ab00.html#summary)

**Comment by Harshita-mindfire** [comment]
This should be fixed in v0.61 of Dendron. Please post here if not, otherwise this issue will auto close in 4 days.

**Comment by aleksey-rowan** [comment]
"Leave trace" behaviour is configurable thought the [`leaveTrace`](https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#leavetrace) config option.
