### ISSUE TITLE
Improve refactor preview

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#740]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

The refactor preview shows a list of notes that will be renamed and when file names are of different lengths it's very hard to visually confirm that resulting names are correct:

![](https://i.imgur.com/6tzindd.png)

```hml
<ul>
  <li>r.tech.js.md --&gt; r.tech.javascript.md</li>
  <li>r.tech.js.cook.md --&gt; r.tech.javascript.cook.md</li>
</ul>
```

## Describe the solution you'd like ##

Put the `before/after` values in a table instead of a list:

![](https://i.imgur.com/lBkUC8g.png)

```html
<table>
  <tr><td>r.tech.js.md</td><td>--></td><td>r.tech.javascript.md</td></tr>
  <tr><td>r.tech.js.cook.md</td><td>--></td><td>r.tech.javascript.cook.md</td></tr>
</table>
```

**Comment by kpathakota** [comment]
I <3 this idea. Should be a small one that maybe I can pick up myself in a few days. Marking as a community issue for now in case someone else gets to it.

**Comment by kevinslin** [comment]
For bystanders that are interesting in implementing, [here](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/commands/RefactorHierarchyV2.ts#L61:L61) is where the code needs to be update

To get started on the development, you can follow the instructions in our [contribution guide](https://wiki.dendron.so/notes/81da87be-2d4e-47b5-a1d6-c0d647e1ab00.html#summary)

**Comment by Harshita-mindfire** [comment]
This should be fixed in v57 of Dendron. Please post here if not, otherwise this issue will auto close in 4 days

**Comment by aleksey-rowan** [comment]
Works! Thank you @Harshita-mindfire
