### ISSUE TITLE
Random note

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#743]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I would like to have a way to open a random note from my vault, similar to how the Obsidian's [Random note](https://help.obsidian.md/Plugins/Random+note) command works.

## Describe the solution you'd like ##

A Dendron command to open a random note. 

## Describe alternatives you've considered ##

[vscode-memo](https://github.com/svsool/vscode-memo) extension has a "Open random note" command which seems to work fine on top of a Dendron vault, but using yet another extension for just this one feature is excessive.

## Additional context ##

Ideally, this command should be configurable to whitelist/blacklist certain hierarchies from which you do or do not want random notes to be picked up.

**Comment by vicrdguez** [comment]
+1 I think this is something great to have to re-discover knowledge in your notes

**Comment by kevinslin** [comment]
Think this is a great idea, especially with the addition of whitelisting/blacklisting
