### ISSUE TITLE
Horizontal split not working when passed as a command argument

### ISSUE THREAD

**Issue by vicrdguez** [dendronhq/dendron#747]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Using the `splitType` argument in a lookup keybinding just open the note normally

## To Reproduce

1. Create a lookup keybinding and pass the modifier: ` "splitType": "horizontal"`
2. Launch the lookup with the just created keybinding and open a note
3. The note opens in the same editor group instead on a new one

## Expected behavior
This modifier should open a note in another editor group

**Comment by kpathakota** [comment]
Yes, I can repro this too. I'm not sure exactly what needs to go in the config but I tried: 
- splitType: "horizontal"
- splitType: "Horizontal"
- splitType: true

horizontal should've worked looking at the code but ... yeah, we should fix this.

**Comment by hikchoi** [comment]
Once https://github.com/dendronhq/dendron/pull/1102 is shipped the issue should be fixed 🙂

**Comment by hikchoi** [comment]
This should be fixed in v55. please post here if not, otherwise this issue will auto close in 3 days
