### ISSUE TITLE
Markdown Preview Enhanced

### ISSUE THREAD

**Issue by generic-user** [dendronhq/dendron#748]
Hi, looks like there are some performance issues introduced that are not there in the original repository ... care to investigate?

### MPE

![image](https://user-images.githubusercontent.com/1516035/119227382-cf310f80-bb0d-11eb-8a9f-3bef57fad0f0.png)

### Dendron MPE

![image](https://user-images.githubusercontent.com/1516035/119227460-3e0e6880-bb0e-11eb-89f9-c2622de1e3c2.png)

**Comment by kpathakota** [comment]
We are planning on deprecating our usage of MPE soon - more details in #643. ~3s is bad but I think we can live with this while we do the migration over, what do you think @kevins8?

**Comment by aleksey-rowan** [comment]
Hi, @generic-user, dendron no longer uses MPE and has switched [to a native component to render the preview.](https://wiki.dendron.so/notes/Lnp1URddmWEWweyf/)

**Comment by generic-user** [comment]
OK, sounds great. I think we can close this issue then.
Thanks for the heads-up! 🎉
