### ISSUE TITLE
Error message when executing "Markdown Links: Show Graph" command

### ISSUE THREAD

**Issue by denisdifazio** [dendronhq/dendron#75]
**Describe the bug**
The message `'Markdown Links: Show Graph' resulted in an error (command 'markdown-links.reloadGraph' already exists` always appears after first execution of the command.
I don't know if this is a problem with [Markdown Notes](https://github.com/kortina/vscode-markdown-notes) or Dendron Markdown Notes

**To Reproduce**
1. Execute 'Show Graph' command
2. Close graph window
3. Execute same command again

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/11673757/89422629-f9931700-d70b-11ea-8feb-7d77389a4588.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.5.9

**Comment by kevinslin** [comment]
thanks for submitting the issue. just pushed a fix in Dendron Markdown Links v0.6.5. you can find upgrade instructions here: https://www.dendron.so/notes/21c1288a-6fb8-42f5-90c0-9b3cc7d872ad.html#bundled-extensions

**Comment by denisdifazio** [comment]
Awesome! The error is gone, thank you!
