### ISSUE TITLE
Custom Tree view sort order

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#750]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Easy sort pages. For example there are 3 pages:

js.vue-typescript.components.md
js.vue-typescript.intro.md
js.vue-typescript.setting-up.md

I'd like to see in Dendron Tree View this pages not in alphabetical order:
intro
setting up
components

I'd also like to see titles instead of full file names in tree view. 

## Describe the solution you'd like ##
- Tree view should support drag and drop sorting (and rename sorted order). 
- File titles should appear for currently active nodes (I think having the titles on *all* the nodes would create too much clutter).

**Comment by hikchoi** [comment]
Hey @kpathakota 

We now have a toggle between sort by title / filename
and the tree view also respects `nav_order` frontmatter.
I'll close this issue as what we have is a very close approximation of a resolution for this issue :)

I'll make note of the enhancement ideas for drag and drop support and labeling in a separate project: `[[06 Tree View UI Overhaul|dendron://private/proj.2022.06-tree-view-ui-overhaul]]`
