### ISSUE TITLE
Paste File when filenames contain non-URI-safe characters

### ISSUE THREAD

**Issue by ddbrierton** [dendronhq/dendron#765]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

If I copy the path name of a file called, for example, `John’s PhD Thesis.pdf` and then invoke Dendron’s Paste File command, the PDF is copied as-is to the assets folder and the following link is created in my Dendron note:

```md
[John’s PhD Thesis.pdf](assets/John’s PhD Thesis.pdf)
```

Unfortunately, due to the spaces in the file name this does not render as a link in the preview pane, instead the markdown is rendered literally. This may also cause problems (although I haven’t tested) during Site Build.

## Expected behavior

At the very least file names should be URL-escaped. However, as the behaviour of Paste File is modelled on Paste Image I think it would be more consistent and probably more robust to kebab-case the file name when it is copied into Dendron, and to prepend the date to the filename to protect against the possibility of adding two different documents with the same filename.

## Desktop (please complete the following information)

- OS: macOS 11.4
- Dendron Version: 0.43.0

**Comment by kevinslin** [comment]
This should be fixed in 0.43.1

**Comment by kpathakota** [comment]
@all-contributors add @ddbrierton for bug
