### ISSUE TITLE
All dendron commands fail with engine not initialized error

### ISSUE THREAD

**Issue by Neurrone** [dendronhq/dendron#769]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

After opening my Dendron workspace as per usual, all Dendron commands don't work. It was working just fine for me on the same repository yesterday.

## To Reproduce

1. Open dendron workspace
2. Attempt a command, such as rename note. I also noticed that ctrl+l does not bring up the lookup bar as per usual

## Expected behavior

Everything works as per usual

## Desktop (please complete the following information)

- OS: windows 10

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/6560904/dendron.log)

**Comment by kevinslin** [comment]
Based on the logs, it looks like the workspace is not active. Can you make sure that you opened up `dendron.code-workspace` as a workspace folder instead of a regular folder. see instructions here: https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe.html#run-dendron-inside-a-workspace

**Comment by Neurrone** [comment]
Yup, I've done that and in the title of the window, it also indicates that its opened as a workspace.

**Comment by Neurrone** [comment]
I've just tried and again and this time, I see something new in the logs:

```
{"level":30,"time":1622219509806,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","ctx":"EngineConnector:init","msg":"enter","opts":{}}
{"level":30,"time":1622219509807,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","ctx":"EngineConnector:createServerWatcher","msg":"enter","opts":{}}
{"level":30,"time":1622219512809,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","ctx":"EngineConnector:_connect","portCreated":1622119238620,"wsActivation":1622119238618}
{"level":30,"time":1622219512809,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","ctx":"EngineConnector:_connect","msg":"initFromExistingFile","port":36327}
{"level":30,"time":1622219512810,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","ctx":"EngineConnector:tryToConnect","port":36327,"msg":"enter"}
{"level":50,"time":1622219512818,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","name":"RequestError","message":"Error: connect ECONNREFUSED 127.0.0.1:36327","cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":36327},"error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":36327},"options":{"url":"http://localhost:36327/api/note/info","qs":{},"body":{},"json":true,"method":"GET","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"stack":"RequestError: Error: connect ECONNREFUSED 127.0.0.1:36327\n\tat new RequestError (/home/dickson/.vscode-server-insiders/extensions/dendron.dendron-markdown-preview-enhanced-0.10.32/node_modules/request-promise-core/lib/errors.js:14:15)\n\tat Request.plumbing.callback (/home/dickson/.vscode-server-insiders/extensions/dendron.dendron-markdown-preview-enhanced-0.10.32/node_modules/request-promise-core/lib/plumbing.js:87:29)\n\tat Request.RP$callback [as _callback] (/home/dickson/.vscode-server-insiders/extensions/dendron.dendron-markdown-preview-enhanced-0.10.32/node_modules/request-promise-core/lib/plumbing.js:46:31)\n\tat self.callback (/home/dickson/.vscode-server-insiders/extensions/dendron.dendron-markdown-preview-enhanced-0.10.32/node_modules/request/request.js:185:22)\n\tat Request.emit (events.js:315:20)\n\tat Request.onRequestError (/home/dickson/.vscode-server-insiders/extensions/dendron.dendron-markdown-preview-enhanced-0.10.32/node_modules/request/request.js:877:8)\n\tat ClientRequest.emit (events.js:315:20)\n\tat Socket.socketErrorListener (_http_client.js:469:9)\n\tat Socket.emit (events.js:315:20)\n\tat emitErrorNT (internal/streams/destroy.js:106:8)\n\tat emitErrorCloseNT (internal/streams/destroy.js:74:3)\n\tat processTicksAndRejections (internal/process/task_queues.js:80:21)","type":"Error","msg":"Error: connect ECONNREFUSED 127.0.0.1:36327"}
{"level":30,"time":1622219512818,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","ctx":"EngineConnector:tryToConnect","msg":"can't connect","error":{"name":"RequestError","message":"Error: connect ECONNREFUSED 127.0.0.1:36327","cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":36327},"error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":36327},"options":{"url":"http://localhost:36327/api/note/info","qs":{},"body":{},"json":true,"method":"GET","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}}
{"level":30,"time":1622219512818,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"connector","ctx":"EngineConnector:connectAndInit","msg":"checking for engine"}
{"level":50,"time":1622219513104,"pid":7291,"hostname":"DESKTOP-7M1ATDM","name":"dendron","ctx":"A:run","error":{"stack":"Error: error running command: engine not set\n\tat A.run (/home/dickson/.vscode-server-insiders/extensions/dendron.dendron-0.43.1/dist/extension.js:9:106446)\n\tat async /home/dickson/.vscode-server-insiders/extensions/dendron.dendron-0.43.1/dist/extension.js:9:81310\n\tat async _executeContributedCommand (/home/dickson/.vscode-server-insiders/bin/541a5d4fa70ab3095f23b28b88914e1f6a8f65c4/out/vs/server/remoteExtensionHostProcess.js:85:109054)","message":"error running command: engine not set","isComposite":false,"status":"unknown","payload":"{}","error":{}}}
```

It seems like its not able to connect to the port (I guess this is where the engine is supposed to listen at)

**Comment by kevinslin** [comment]
Ah, do you have something that is blocking localhost? Dendron starts a
local server in the background and the plugin connects to it to index
notes:
https://wiki.dendron.so/notes/c160ddce-edec-4f6e-841b-418d6030fa37.html

**Comment by Neurrone** [comment]
I don't see anything listening at port 36327. Is it possible the server never started somehow and hence it can't connect to it?

**Comment by Neurrone** [comment]
The mystery continues.

When I initialize a new Dendron workspace at a different folder, I am able to open the workspace and Dendron initializes as per usual.

Its only the previous workspace that I was using that Dendron refuses to initialize in, this seems like either a bug in Dendron itself, or something changed in my repository that is causing this failure.

As far as I can tell, there isn't anything in the .code-workspace file or the dendron yml that should be causing this.

**Comment by Neurrone** [comment]
🤦 I was spot on about something wrong with my workspace configuration. 

I was editing it manually to include vaults that I created but for some reason weren't being included in the workspace file. I missed a comma in the JSON definition. After fixing that syntax error, everything is working as expected.

Would it be possible to account for such errors to show some sort of alert? Or if not, adding this to the troubleshooting page could be useful in case someone else accidentally runs into this in the future.

**Comment by kevinslin** [comment]
Ah, that would do it. Yeah, this has happened before. Can you create a
separate ticket to issue a warning for this case? Feel free to link it to
this ticket for context

**Comment by Neurrone** [comment]
Thanks and sorry for the false alarm.

Created #772

**Comment by kevinslin** [comment]
All good, thanks for reminding me of the JSON issue with settings :)
