### ISSUE TITLE
Search box (in a dendron publish page, mobile view) disappeared when starting to type in

### ISSUE THREAD

**Issue by andrey-jef** [dendronhq/dendron#771]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Ive just encountered a glitch when searching for something in the wiki dendron on safari ios 14. 
When starting to type in the search field, the search box will disappear. 

## To Reproduce

1. Go to dendron wiki page using safari on ios 14.4.1 'https://wiki.dendron.so'
2. Click on 'hamburger menu top right'
3. Start typing into 'search box'
4. See error : search box disappear 

## Expected behavior

Search box stays afloat and suggested results should appear

## Screenshots

![image](https://user-images.githubusercontent.com/81280428/120000840-87a9f800-bfd3-11eb-927d-bca51cd3e4c3.png)

## Mobile (please complete the following information)

- OS: iOS 14.4.1
- Browser: safari
- Version: 

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
this should be fixed now. feel free to re-open if not the case
