### ISSUE TITLE
Minor issue with auto title from note name

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#774]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When creating my note with a filename containing a german "ä", "ü" or "ö" dendron capitalizes the following letter. 

Naming the note `abschätzung` results in the title `AbschäTzung`.

**Comment by Harshita-mindfire** [comment]
Hi @funnym0nk3y this seems to be working in latest Dendron versions. Checking if this is still an issue?

**Comment by aleksey-rowan** [comment]
This issues has been reported before (https://github.com/dendronhq/dendron/issues/1668) and should be fixed in versions after 0.71.0.
