### ISSUE TITLE
can't install dendron-cli

### ISSUE THREAD

**Issue by timDeHof** [dendronhq/dendron#776]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When going through the publishing tutorial, I can't run the command: npm install -g @dendronhq/dendron-cli@latest in the terminal. I get the following:
   npm ERR! code ETARGET
   npm ERR! notarget No matching version found for @dendronhq/dendron-11ty@^0.43.5-alpha.0.
   npm ERR! notarget In most cases you or one of your dependencies are requesting
   npm ERR! notarget a package version that doesn't exist.
   npm ERR! notarget 
   npm ERR! notarget It was specified as a dependency of '@dendronhq/dendron-cli'
   npm ERR! notarget 

   npm ERR! A complete log of this run can be found in:
   npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2021-05-31T12_59_38_293Z-debug.log 
## To Reproduce

1. Go to 'your vault'
2. Click on 'terminal'
3. type 'npm install -g @dendronhq/dendron-cli@latest'

## Expected behavior

installation of the dendron-cli

## Screenshots

![Screenshot 2021-05-31 093240](https://user-images.githubusercontent.com/2568193/120201703-bd2d2c00-c1f3-11eb-8e2a-1c27e600943e.png)
## Desktop (please complete the following information)

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] firefox
- Version [e.g. 22]  dendron 0.43.1

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/6570613/dendron.log)

**Comment by mocsa** [comment]
I experienced the same problem today.

**Comment by kpathakota** [comment]
@all-contributors add @timDeHof for bug

**Comment by kevinslin** [comment]
fixed in v44
