### ISSUE TITLE
Hierarchy Refactor inconsistencies

### ISSUE THREAD

**Issue by vicrdguez** [dendronhq/dendron#780]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug
Hi Team!

I was working with refactoring to make my notes more organized and I've found some inconsistencies when working with the refactor command.
context:

- I have a `kafka.connect.connector` hierarchy which has other child notes
- I have a `kafka.connect.connectors` hierarchy which has other child notes (I want to fix this inconsistencies)

What I want is to refactor this hierarchies to remove both `connector` and `connectors` and end up with just `kafka.connect.*`, of course I plan to do this in 2 steps, one for each hierarchy, not all of them in one shot

### Case 1

1. Launch hierarchy refactor in a child note
2. I specify the match as: `kafka.connect.connector`
3. In the next prompt I enter the replace string: `kafka.connect`
This is what the refactor window shows:
---

kafka.connect.connector.err.md --> kafka.connect.err.md
`kafka.connect.connectors.dev.md --> kafka.connects.dev.md`
kafka.connect.connector.cfg.confluent-topic-bootstrap-server.md --> kafka.connect.cfg.confluent-topic-bootstrap-server.md
`kafka.connect.connectors.rabbitmq.error.md --> kafka.connects.rabbitmq.error.md`
`kafka.connect.connectors.rabbitmq.err.value-must-be-of-type-byte.md --> kafka.connects.rabbitmq.err.value-must-be-of-type-byte.md`
kafka.connect.connector.sink.salesforce-bulk.err.bad-sinkrecord.md --> kafka.connect.sink.salesforce-bulk.err.bad-sinkrecord.md
kafka.connect.connector.sink.salesforce-bulk.err.invalid-bootstrap.md --> kafka.connect.sink.salesforce-bulk.err.invalid-bootstrap.md
kafka.connect.connector.sink.salesforce-bulk.err.json-converter-schema.md --> kafka.connect.sink.salesforce-bulk.err.json-converter-schema.md

---

I've highlighted the interesting ones: as you can see it takes the `.connectors` hierarchy as well and as a result I have `.connects` instead of just `connect`

### Case 2

To overcome Case 1, I try to specify the match more specifically:

1. Launch hierarchy refactor in a child note
2. I specify the match as: `kafka.connect.connector.` -> Note the "dot" at the end
3. In the next prompt I enter the replace string: `kafka.connect`
This is what the refactor window shows:

---

`kafka.connect.connector.err.md --> kafka.connecterr.md`
kafka.connect.connectors.dev.md --> kafka.connect.dev.md
`kafka.connect.connector.cfg.confluent-topic-bootstrap-server.md --> kafka.connectcfg.confluent-topic-bootstrap-server.md`
kafka.connect.connectors.rabbitmq.error.md --> kafka.connect.rabbitmq.error.md
kafka.connect.connectors.rabbitmq.err.value-must-be-of-type-byte.md --> kafka.connect.rabbitmq.err.value-must-be-of-type-byte.md
`kafka.connect.connector.sink.salesforce-bulk.err.bad-sinkrecord.md --> kafka.connectsink.salesforce-bulk.err.bad-sinkrecord.md`
`kafka.connect.connector.sink.salesforce-bulk.err.invalid-bootstrap.md --> kafka.connectsink.salesforce-bulk.err.invalid-bootstrap.md`
`kafka.connect.connector.sink.salesforce-bulk.err.json-converter-schema.md --> kafka.connectsink.salesforce-bulk.err.json-converter-schema.md`

---

In this case the notes in the `.connector` hierarchy are not correctly refactored, you can notice a missing dot. Surprisingly even specifying the final dot in the "match" prompt the refactor takes the `.connectors` notes and I'm not sure how but it deletes the _s_ and the final result is the correct one

### Case 3

1. Launch hierarchy refactor in a child note
2. I specify the match as: `kafka.connect.connector.` -> Note the "dot" at the end
3. In the next prompt I enter the replace string: `kafka.connect.` -> Note the "dot" at the end

This is what the refactor window shows:

---
kafka.connect.connector.err.md --> kafka.connect.err.md
kafka.connect.connectors.dev.md --> kafka.connect..dev.md
kafka.connect.connector.cfg.confluent-topic-bootstrap-server.md --> kafka.connect.cfg.confluent-topic-bootstrap-server.md
`kafka.connect.connectors.rabbitmq.error.md --> kafka.connect..rabbitmq.error.md`
`kafka.connect.connectors.rabbitmq.err.value-must-be-of-type-byte.md --> kafka.connect..rabbitmq.err.value-must-be-of-type-byte.md`
kafka.connect.connector.sink.salesforce-bulk.err.bad-sinkrecord.md --> kafka.connect.sink.salesforce-bulk.err.bad-sinkrecord.md
kafka.connect.connector.sink.salesforce-bulk.err.invalid-bootstrap.md --> kafka.connect.sink.salesforce-bulk.err.invalid-bootstrap.md
kafka.connect.connector.sink.salesforce-bulk.err.json-converter-schema.md --> kafka.connect.sink.salesforce-bulk.err.json-converter-schema.md

---
In this case notes in the `.connect` hierarchy are correctly formatted but the ones in `.connectors` get an extra "dot" tha it's not correct. Here I still don't understand why the `.connectors` hierarchy is matched, are the dots ignored for the match?

### Case 4
The last one, I promise:

1. Launch hierarchy refactor in a child note
2. I specify the match as: `kafka.connect.connector`
3. In the next prompt I enter the replace string: `kafka.connect.` -> Note the "dot" at the end
---

`kafka.connect.connector.err.md --> kafka.connect..err.md`
`kafka.connect.connectors.dev.md --> kafka.connect.s.dev.md`
`kafka.connect.connector.cfg.confluent-topic-bootstrap-server.md --> kafka.connect..cfg.confluent-topic-bootstrap-server.md`
`kafka.connect.connectors.rabbitmq.error.md --> kafka.connect.s.rabbitmq.error.md`
`kafka.connect.connectors.rabbitmq.err.value-must-be-of-type-byte.md --> kafka.connect.s.rabbitmq.err.value-must-be-of-type-byte.md`
`kafka.connect.connector.sink.salesforce-bulk.err.bad-sinkrecord.md --> kafka.connect..sink.salesforce-bulk.err.bad-sinkrecord.md`
`kafka.connect.connector.sink.salesforce-bulk.err.invalid-bootstrap.md --> kafka.connect..sink.salesforce-bulk.err.invalid-bootstrap.md`
`kafka.connect.connector.sink.salesforce-bulk.err.json-converter-schema.md --> kafka.connect..sink.salesforce-bulk.err.json-converter-schema.md`

---

In this last case, all the reformats are incorrect

## Expected behavior
Hierarchy refactor should be more deterministic and make more strict matching and replacing

**Comment by kpathakota** [comment]
@vicrdguez - you'll need to use the specific regex connector\. to match "connector." explicitly. Unfortunately the . character is treated as a wildcard by regex (so it also matches connectors). With this change, Case 3 should work.

**Comment by vicrdguez** [comment]
@kpathakota Oh I see, I though the lookup was using globs instead of regex. I was so focused on that that I didn't thought on regex as a solution.
This is working as expected then, sorry for open this useless bug 😅 . I'll close it
