### ISSUE TITLE
SVG image support in preview

### ISSUE THREAD

**Issue by fschrempf** [dendronhq/dendron#788]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

It's currently not possible to include SVG images and have them shown in the preview. This is probably more a missing feature or bug in the markdown renderer, so if this should be reported elsewhere, please let me know.

### Reproduce

1. Create a SVG file in `assets/images/`.
2. Add an image in a note `![Test](/assets/images/test.svg)`.
3. View the markdown preview.

### Result

![image](https://user-images.githubusercontent.com/34034373/120662542-883a0700-c489-11eb-98cf-2e643861ee8c.png)

## Describe the solution you'd like ##

Support for SVG images in the preview.

**Comment by kpathakota** [comment]
Yeah, we should make sure this is in scope for the NextJS based preview we're working on #643. Putting on the backlog.

**Comment by aleksey-rowan** [comment]
Hey, @fschrempf. Dendron has switched away from the MPE and is using [its own component to render the preview](https://wiki.dendron.so/notes/Lnp1URddmWEWweyf/) and what you are describing seems to work right now. Could you double check if you are still have the same problem?

```md
![](https://upload.wikimedia.org/wikipedia/commons/8/84/Example.svg)
```

**Comment by fschrempf** [comment]
@aleksey-rowan Thanks for the heads-up! I can confirm it works!
