### ISSUE TITLE
Can't get publishing to work on fresh install

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#798]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## To Reproduce

1. Initialize new repo
2. Follow the instructions to publish here: https://wiki.dendron.so/notes/9c6f600e-f1f3-423b-963a-c71bb081334c.html
3. The build site command errors out citing a missing dependency (just-the-docs-default.scss)

## Expected behavior
2a. expect preview to load

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

[dendron.log](https://github.com/dendronhq/dendron/files/6602974/dendron.log)
[dendron.server.log](https://github.com/dendronhq/dendron/files/6602975/dendron.server.log)

**Comment by ElliotPsyIT** [comment]
@kpathakota Thanks for including this issue.  Turned out I was using a version of Node below v12.  The dendron.so documentation indicated Node version of 0.12, which I misinterpreted.  Once I nvm'd to Node v12.0.0 the preview loaded.  My apologies, and thanks for the assistance!!

**Comment by kevins8** [comment]
Heads up that I've update the docs so future generations can learn from our
mistakes :)

**Comment by kpathakota** [comment]
Glad it worked @ElliotPsyIT!

**Comment by kpathakota** [comment]
@all-contributors please add @ElliotPsyIT for bug
