### ISSUE TITLE
Multi-Vault Support

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#8]
# Multi Vault Support

## Goals

Users should be able to initialize their workspace with multiple workspaces

## Details

This enables many use cases like keeping a private local only vault and a synced dropbox vault. 

## Tasks
- [ ] writeup design
- [ ] collect feedback
- [ ] implement

## Links
- [project docs](https://dendron.so/notes/45cfb9f2-46cf-4f67-a41e-834818fbd06e.html)
- [issues](https://github.com/dendronhq/dendron/labels/pro.multi-vault)

**Comment by kpathakota** [comment]
This has been shipped for a while.
