### ISSUE TITLE
Position cursor to end of file when a new note is created.

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#800]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##
Currently when you create a new note, the cursor is placed at the start of the active document. Frontmatter is already populated, so if you start typing right away this will break the frontmatter.

## Describe the solution you'd like ##
Place cursor at the end of file when a new note is created.

## Describe alternatives you've considered ##
The current workflow is to always hold <kbd>Page Down</kbd> after creating a new note. This is often forgotten and will break the flow.

## Additional context ##
I notice this happening a lot to me when I am creating a new journal entry and then using `Dendron: Insert Note` to carry over the last day's entry.

**Comment by SeriousBug** [comment]
This has been added in version `0.48`.
