### ISSUE TITLE
Tables in note ref are not properly rendered in preview

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#815]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug
A note ref  to a table doesn't render properly in the preview and multiple refs only show with newlines between them

## To Reproduce

1. Create two sample notes with a heading and a simple table in them
2. Create a new note which includes refs to the headers and 
3. Take a look at the preview

## Expected behavior

I expect the tables to show properly like it did until the last update (at least I notice it onyl now)

## Screenshots

See https://github.com/Bassmann/bug-free-fiesta which includes a sample and screenshots

## Desktop (please complete the following information)

- OS: Windows 10
- VsCode Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043
- Dendron 0.45, Dendron Markdown Preview 0.10.43

**Comment by kpathakota** [comment]
@Bassmann - I just tried this out in the latest version with your bug repro'ing vault and it *should* be fixed (there was a vscode changes so there were a lot of bugfixes we had to make to workaround them). Please let me know if it's still updating.

**Comment by Bassmann** [comment]
It's fixed, thanks a lot for the fast response!
