### ISSUE TITLE
Block Link doesn't work properly.

### ISSUE THREAD

**Issue by agichim** [dendronhq/dendron#817]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

[Block Links](https://wiki.dendron.so/notes/21bc1caa-d815-42db-bc16-27d6c16a3115.html#block-links) don't work properly.

Create a block link following the Dendron docs from the link above. Click on the block link in the preview, you should be taken to the referenced paragraph in the same `.md` file, but instead nothing happens. 

When holding CTRL and clicking on the block link in the editor you are taken to the beginning of the `.md` file and the typing cursor `|` is placed right a the beginning before the first `---` of the frontmatter.

When holding CTRL and hovering the cursor over the block link the small preview windows displays the UUID or `id` of the frontmatter and the whole document content. If hovering over the block link without holding CTRL the whole document content is displayed from the beginning of the document. 

## To Reproduce

1. In the same `.md` file place a few paragraphs
2. At the end of one paragraph place a block reference `^my-block`
3. Anywhere in the document place a block link referencing the block reference `[[#^my-block]]
4. Click on the block link in the preview (nothing happens)
   - Hold CTRL and hover over the block link (doesn't show the block reference)
   - Hold CTRL and click on the block link (it takes you to the beginning of the document)

## Expected behavior

1. Clicking on the block link in the preview should take you to the block reference.
2. Holding CTRL and hovering over the block link should show only the block reference in the small preview window.
3. Holding CTRL and clicking on the block link should take you to the block reference.

## Screenshots

![image](https://user-images.githubusercontent.com/51931067/121758144-1e200280-cb18-11eb-8560-39e076d3a593.png)
![image](https://user-images.githubusercontent.com/51931067/121758154-28da9780-cb18-11eb-9f64-4fb43f0d2775.png)

## Desktop (please complete the following information)

- OS: Windows 10. Ver. 2004 (Build 19041.985)
- Browser: Brave (not tested the block link and block reference in the published GH pages)
- Version → version of what software?

## Dendron Log file

Logs [here](https://cosmo.matemates.com/privatebin/?87858399f6805c3d#6eKAE4YxgDWVypeQzqZkgnEjfvW2dUciuD4syqRfGARZ)

**Comment by agichim** [comment]
**Update**

After a few hours the issue didn't happen anymore. Holding CTRL and hovering or clicking shows and takes you to the block reference. I did once `Dendron: Doctor` to fix frontmatter, but I can't tell if that helped to solve the issue.

**Comment by agichim** [comment]
I did `Dendron>Reload Index` a few times and it didn't worked. 

The second time I create a different Block Link, the issue persisted and when I did `Dendron>Reload Index` it was solved immediately.

**Comment by SeriousBug** [comment]
The fix for this has been shipped with v47.
