### ISSUE TITLE
Tree View Broken After Renaming Node With Additional Hierarchy

### ISSUE THREAD

**Issue by AJ-86** [dendronhq/dendron#818]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

After renaming a node with a new level of hierarchy, an error message ("Cannot read property 'title' of undefined) appears and the tree view is broken and displays blank.  

## To Reproduce

1. Create a hello.world note
2. Rename the note to hello.world.new.world 
3. Tree view no longer renders

## Expected behavior

Tree view should show the new hierarchy

## Screenshot

![Screenshot_80](https://user-images.githubusercontent.com/13300816/121762526-058c0880-cb69-11eb-82b5-8950374ab435.png)

## Desktop (please complete the following information)

- OS: Windows10
- Version: 0.45.2

## Dendron Log file

{"level":30,"time":1623465147065,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"MoveNoteCommand","opts":{"moves":[{"oldLoc":{"fname":"hello.world","vault":{"fsPath":"vault"}},"newLoc":{"fname":"hello.world.new.world","vault":{"fsPath":"vault"}}}],"useSameVault":true,"closeAndOpenFile":true}}
{"level":30,"time":1623465147151,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Andrew\\OneDrive\\Dendron\\vault\\hello.world.new.world.md","_sep":1,"external":"file:///c%3A/Users/Andrew/OneDrive/Dendron/vault/hello.world.new.world.md","path":"/c:/Users/Andrew/OneDrive/Dendron/vault/hello.world.new.world.md","scheme":"file"}}
{"level":30,"time":1623465147154,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"E:run","msg":"post-execute"}
{"level":30,"time":1623465147154,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1623465147218,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1623465147220,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"VaultWatcher:onDidCreate","uri":{"$mid":1,"fsPath":"c:\\Users\\Andrew\\OneDrive\\Dendron\\vault\\hello.world.new.world.md","_sep":1,"path":"/c:/Users/Andrew/OneDrive/Dendron/vault/hello.world.new.world.md","scheme":"file"},"msg":"paused"}
{"level":30,"time":1623465150157,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"MoveNoteCommand","msg":"exit"}
{"level":30,"time":1623465159136,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"c:run","msg":"pre-execute"}
{"level":30,"time":1623465159136,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1623465159164,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"c:run","msg":"post-execute"}
{"level":30,"time":1623465159238,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"c:\\Users\\Andrew\\AppData\\Roaming\\Code\\logs\\20210612T095107\\exthost1\\dendron.dendron\\dendron.log","_sep":1,"external":"file:///c%3A/Users/Andrew/AppData/Roaming/Code/logs/20210612T095107/exthost1/dendron.dendron/dendron.log","path":"/c:/Users/Andrew/AppData/Roaming/Code/logs/20210612T095107/exthost1/dendron.dendron/dendron.log","scheme":"file"}}
{"level":30,"time":1623465159239,"pid":8116,"hostname":"ANDREWPC","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","uri":"c:\\Users\\Andrew\\AppData\\Roaming\\Code\\logs\\20210612T095107\\exthost1\\dendron.dendron\\dendron.log","msg":"not in workspace"}

**Comment by kevinslin** [comment]
took a look. this should be fixed in the upcoming 0.47 release next monday

**Comment by 8brandon** [comment]
hmm, unfortunately 0.47 is giving me "Cannot read property 'name' of undefined", when I try to open a file from the Lookup command. 

Downgrading to 0.46 fixed this and it works again for me

**Comment by kpathakota** [comment]
@AJ-86 - this should be working now. Please provide updated details if you run into this on the latest version. 

@8brandon - are you still seeing this? We're using 0.47 and lookup seems to be working okay.
