### ISSUE TITLE
'Dev:Dendron:Doctor' remove all content from file

### ISSUE THREAD

**Issue by denisdifazio** [dendronhq/dendron#82]
**Describe the bug**
I don't know if I misinterpreted what is written on https://www.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#doctor or if it is a bug indeed. I thought doctor command would only add frontmatter if it is missing and not replace all content with it.

**To Reproduce**
1. Create new `.md` file
2. Write anything on it without adding a frontmatter
3. Save file
4. Execute `Dev:Dendron:Doctor`
5. Observe that all content is gone and replaced with a frontmatter

**Expected behavior**
File's content remains the same only with the addition of frontmatter

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.5.11

**Comment by kevinslin** [comment]
Looked into it and you're right, it is a bug! 

Doctor works with the files you had on disk when you first started Dendron which is why new file changes weren't picked up. Fixed this with the latest Dendron 0.5.12. Issue should be fixed now and deep apologies about the issue.

**Comment by denisdifazio** [comment]
No problem Kevin, I'm glad I helped. Keep up the great work!
