### ISSUE TITLE
Hover preview for note ref should only show reference

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#837]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

- Hover preview currently shows the whole note, should only show the reference area

**Comment by aleksey-rowan** [comment]
I haven't seen this being mentioned in release notes, but hover previews work like this already (showing only referenced content).

**Comment by aleksey-rowan** [comment]
Confirmed. It's done.
