### ISSUE TITLE
Broken frontmatter prevents Dendron from initializing

### ISSUE THREAD

**Issue by sagarbehere** [dendronhq/dendron#841]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

If a file in the vault has broken frontmatter, Dendron does not initialize successfully

## To Reproduce

1. Open an existing file in the vault
2. Introduce an extra : in the id block. If the line is `id: 829639dd-d027-46d3-bf59-fad32ab8b0a7` then change it to `id: : 829639dd-d027-46d3-bf59-fad32ab8b0a7`
3. Save the file. Quit VSCode. Start VSCode again.
4. See error "Issue initializing Dendron" (see attached screenshot)

## Expected behavior

Dendron initializes even if frontmatter is broken. Dendron then notifies the user that file(s) in question seem to have broken frontmatter. In general, unsanitized/incorrect user input in the form of poorly formatted files should not prevent Dendron from initializing.

## Screenshots

<img width="455" alt="Screen Shot 2021-06-18 at 4 38 48 PM" src="https://user-images.githubusercontent.com/1622959/122624382-c2dc9b80-d054-11eb-961f-b7ad4b170fb9.png">

## Desktop (please complete the following information)

- OS: macOS 10.15.7 Catalina
- Browser: n/a
- Version: n/a

## Additional context

N/A

## Dendron Log file
[dendron.log](https://github.com/dendronhq/dendron/files/6679674/dendron.log)

**Comment by sidwellr** [comment]
I had a similar issue today. For me the file dendron.topic.lookup.schemas.md had an extra ">" character in a link: "[[> Dendron: Reload Index|dendron.topic.commands]]"; removing the ">" allowed Dendron to initialize once again. (I don't know how the character got there.)

**Comment by SeriousBug** [comment]
With version `0.48`, both these issues should no longer crash Dendron's initialization.
