### ISSUE TITLE
Wiki Pages to be Updated Since Version 0.46

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#842]
## Please Select if your Request is Either something new or an Enhancement ##

- [X] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

Very small issue, bringing it to the team's attention. The following two wiki pages:

1. [Import](https://wiki.dendron.so/notes/f23a6290-2dec-45dc-b616-c218ee53db6b.html)
2. [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html)

Still reference UUID. As of Dendron 0.46 ([release notes](https://wiki.dendron.so/notes/rYFDLOe50uFcfetsuWiGg.html)), Dendron now  uses NanoID. The wiki pages should be updated to prevent confusion. 

Thank you.

**Comment by kpathakota** [comment]
THanks @micharris42 - will double check but I'm still pretty sure those two cases of UUIDs are correct. We default to NanoIDs for note IDs but the referenced notes are a little different.

**Comment by micharris42** [comment]
Thank you @kpathakota for the clarification. Seems I misunderstood. Marking this issue as closed.
