### ISSUE TITLE
Clean install misses dendron.md, maybe more

### ISSUE THREAD

**Issue by matchavez** [dendronhq/dendron#844]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Under 0.46, a "clean" installation does not include `dendron.md`

## To Reproduce

1. Do a clean install
2. Observe files

## Expected behavior

Installation should match tutorials.

## Desktop (please complete the following information)

- OS: MacOS 10.15
- v 0.46

**Comment by kpathakota** [comment]
Yes, good catch: https://wiki.dendron.so/notes/678c77d9-ef2c-4537-97b5-64556d6337f1.html 

That page needs to be updated since we've streamlined the getting started.

**Comment by kpathakota** [comment]
@all-contributors please add @matchavez for bug

**Comment by jonathanyeung** [comment]
This should be cleaned up now with the tutorial getting started experience. Thanks for the feedback!
