### ISSUE TITLE
Specific "name" in a URL previews the link as tag style

### ISSUE THREAD

**Issue by agichim** [dendronhq/dendron#849]
I opened a blank issue because this "bug" is too unique I think and perhaps not really that important to fix.

A subdomain on the UK Gov. website, specifically, only the part that makes the subdomain (not the whole URL) stylizes a link with a **tag** style. You can use this in any made up URL and it does the same, whether as a subdomain or main domain.

`find-and-update` → writing this as part of a URL makes it preview with tag style.

![image](https://user-images.githubusercontent.com/51931067/122892870-b2227300-d33d-11eb-9603-9ace5f34bf52.png)

Original website: https://find-and-update.company-information.service.gov.uk/

**Comment by agichim** [comment]
Here is another word `date` that causes a link to preview as Tag style 
![image](https://user-images.githubusercontent.com/51931067/123093464-a1e4c380-d423-11eb-9eb9-faefe7562442.png)

**Comment by agichim** [comment]
UPDATE:

The style doesn't persist when pushed to GitHub pages. This is good.
It does persist when exporting PDF (Prince) or HTML (offline). I haven't tested the other export options.

**Comment by kevinslin** [comment]
hmm, do you have custom css styling set in place? i'm having trouble reproducing this

**Comment by agichim** [comment]
I don't have custom CSS in place. But if I had it would have to be on that specific text, which would be odd, because by accident I ran into those "bugs" and even 2 of them, which is more odd. 

This is a new Dendron workspace and vault, from scratch, I didn't make any custom settings.

I'll try to reproduce it in a new workspace, from scratch but also try to clone my repo on my wife's computer where VSCodium and Dendron will be installed for the first time.

I'll let you know.

**Comment by kevinslin** [comment]
Sounds good. Your right, this is a really weird one. Really curious to see
if it repros
