### ISSUE TITLE
How to use Dendron across machines? 

### ISSUE THREAD

**Issue by SeaDude** [dendronhq/dendron#852]
Hello,

Is there a reference implementation of using Dendron across machines? I don't see one in the docs. Happy to contribute one if you can give me some leads on how to **best** accomplish it. 

**Example 1:**
- Create new git repo (?)
- Clone repo on multiple machines
- Add notes etc. on machine 1
- Git push 
- Read/edit/add notes on machine 2
- Repeat

**Example 2:**
- Have machine 1 with Dendron and Remote Desktop server setup
- When on machine 1 use Dendron as-is
- When on machine 2, RDP to machine 1 to use a single instance of Dendron

**Example 3:**
- I know there are [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) and [Remote Sharing](https://code.visualstudio.com/blogs/2017/11/15/live-share) tools in VS Code as well
- Not sure if these tools could somehow play a part

Any guidance is appreciated. 

Thank you

**Comment by teauxfu** [comment]
I found some of the information in the docs here to be useful; particularly the notes on adding a remote vault:
https://wiki.dendron.so/notes/6682fca0-65ed-402c-8634-94cd51463cc4.html

that's what I'm doing now, and it's working fine. The `>Dendron: Workspace: Sync` command is very convenient for syncing a particular vault (or many vaults) with a remote repo.

I struggle between using that, and wanting to just create the whole Dendron workspace inside a pre-existing repo. 
In particular, I miss being able to sync the config in `dendon.yml` and `.code-workspace` files, which are pretty important, but reasonably live one directory above a particular vault. 

also see this little tip in the faq
https://wiki.dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558.html#i-want-to-push-all-my-note-to-my-git-repository-periodically

**Comment by kevinslin** [comment]
Hey @SeaDude,

Apologies for the delayed response. There are many ways of setting up Dendron across machines and it depends on your use case and familiarity with git.

I wrote an initial draft of this in our documentation [here](https://wiki.dendron.so/notes/8d3c8142-7481-40da-9a5c-69a3d4bab697.html#using-dendron-across-machines). Let me know if its lacking in detail (and feel free to edit it directly)
