### ISSUE TITLE
0.47 issue on initial install, fixed by downgrading and upgrading

### ISSUE THREAD

**Issue by 8brandon** [dendronhq/dendron#857]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When using the Lookup command on Windows 10, VSCode, Devcontainer, using 0.47 version of Dendron, I am getting the following errors when trying to open a note using crtl+l Lookup. 

'Cannot read property 'name' of undefined'

Strangely, when I downgraded to 0.46, it worked, and continued working when I re-upgraded back to 0.47.

## Desktop (please complete the following information)

- OS: [e.g. iOS] Windows 10
- Version [e.g. 22] 0.47

**Comment by aleksey-rowan** [comment]
0.47 is supposed to add the following to the `dendron.yml` on upgrade (because of [a new feature](https://wiki.dendron.so/notes/25287595-96bb-410b-ab46-eb9a26b0e259.html#dendron-calendar-view)) but sometimes it doesn't work:
```yml
journal:
    dailyDomain: daily
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfDomain
```

As a workaround, you can manually add the above block to `dendron.yml`.

**Comment by kevinslin** [comment]
We updated our update script so this should no longer happen with 0.48
