### ISSUE TITLE
Inconsistent Behavior Between Wikilinks and Backlinks

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#863]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [X] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The behavior between wikilinks and backlinks is inconsistent for note titles in regards to capitalization. 

If a note (example.md) is linked to with the title capitalized ([[Example]]), hovering over the link will bring up the preview, and CTRL clicking will open the note. Both results indicate that the wikilink is recognized and that wikilinks are case insensitive. 

However, on the note itself, the link will not be recognized in the backlinks panel. To get the link to show up in the backlinks panel, the link must be edited to be case sensitive (either [[example]] or [[Example|example]]).

This behavior extends to longer titles: for example.test.trial.md, the wikilink [[Example.Test.Trial]] will work, but will not be recorded in the backlinks panel unless the capitalization is modified. 

## To Reproduce

1. Create a note, "example.md".
2. Create a link to the new note on another note with the title capitalized, [[Example]].
3. Hovering over the link will bring up the preview of example.md, and the link can be used to open the note. 
4. Returning to example.md however, no backlink will be recognized.
5. Return to the link and edit the capitalization (either [[example]] or [[Example|example]]).
6. The backlink will now be recognized.

## Expected behavior

That wikilinks and backlinks behave the same, with both case sensitive, or both case insensitive.

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: NA
- Version: Dendron 0.47.0

## Additional context

In writing, titles are capitalized, but file-naming conventions encourage all lowercase. This is less of an issue with longer titles (the above "example.test.trial.md" would probably be linked as follows: [[example.test.trial|Trial]]), but for one word titles, it is very easy for a user to think they have created a working link ([[Example]]) without realizing that it will not be recorded in the backlinks panel. 

Thank you.

**Comment by kpathakota** [comment]
@all-contributors please add @micharris42 for bug. Good catch!

**Comment by Harshita-mindfire** [comment]
This should be fixed in v0.70 of Dendron. Please post here if not, otherwise this issue will auto close in 4 days

**Comment by voothi** [comment]
@Harshita-mindfire 
Hi! 
I checked this issue. 
My problem solved! Backlinks in v0.70.0 now is worked. 
Many thanks!

**Comment by micharris42** [comment]
Seconded. Backlinks are being recognized regardless of capitalization.

Marking as Closed.
