### ISSUE TITLE
Calendar View not found 

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [dendronhq/dendron#873]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

https://wiki.dendron.so/notes/25287595-96bb-410b-ab46-eb9a26b0e259.html

Cannot launch calendar view on the latest vscode
there is no command to launch it

## Expected behavior

type a command to launch the calendar view

## Screenshots

![image](https://user-images.githubusercontent.com/40897360/123426638-3bfc6580-d5f6-11eb-8ea5-c3d6ae526c05.png)

![image](https://user-images.githubusercontent.com/40897360/123426719-56364380-d5f6-11eb-8709-8c0a79afc88a.png)

![image](https://user-images.githubusercontent.com/40897360/123427180-dceb2080-d5f6-11eb-8d13-8160c734d08e.png)

I don't know how to launch it, but find out the view id already there.

## Desktop (please complete the following information)

- OS:  windows 
- Version: vscode 1.57.1

**Comment by kevinslin** [comment]
You'll need to set [enableWebUi](https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#enablewebui) to true to access it

**Comment by FXTD-ODYSSEY** [comment]
Thanks a lot !~
