### ISSUE TITLE
Should 'Delete Node' be called 'Delete Note'?

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#874]
## Please select the area your Bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x ] Misc (Choose this if your not sure)

## Describe the bug

Is this command misnamed?

## Expected behavior

Expect this to be called Delete Note as Create Note, Rename Note.

## Desktop (please complete the following information)

- Version [e.g. 47]

**Comment by kpathakota** [comment]
Yes, I think we're trying to be too clever here :) Will definitely consider a rename. @jonathanyeung pointed out the same thing recently.
