### ISSUE TITLE
Local image not rendered in peek preview

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#876]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

A peek preview is shown but the image is not rendered

![image](https://user-images.githubusercontent.com/1008059/123539293-552f1e80-d77c-11eb-9b82-84728a6d826e.png)

## To Reproduce

1. Make a note and add an image.
2. Make another note and make a link to the first note.
3. Point to the link in the new note to see the peek preview.
4. The text is visible but the image is not.

## Expected behavior

Expect to see the locally stored image.

The path is: ![](/assets/images/2021-06-27-16-15-58.png)

## Desktop (please complete the following information)

- OS: Win
- Version [e.g. 47.1]

## Additional

Discussed with @SeriousBug on Discord.

**Comment by SeriousBug** [comment]
Local images within notes should now display in the hover preview with version 0.50.

**Comment by SR--** [comment]
It does not work for me in v50. There is not broken icon but I cannot see the image either. There is just an empty like. It looks OK in the preview.

**Comment by SR--** [comment]
And, actually, I see the broken icon in another note...

![image](https://user-images.githubusercontent.com/1008059/125391440-e0005200-e3e7-11eb-80c1-205491a13bb2.png)

**Comment by SeriousBug** [comment]
> And, actually, I see the broken icon in another note...

Could you show what that part of the previewed note looks like? (`![](/assets/...` part)

If you could also write the full path to the image file, that would help diagnose the issue. VSCode is picky about what it will show in the preview so we have to calculate the full path to the image, that might still be broken.

**Comment by SR--** [comment]
This is in the note:

`![](/assets/images/2021-06-16-15-53-43.png)`

This is in OS (Windows):

`C:\_Local Only\dennotes\brain\assets\images\2021-06-16-15-53-43.png`

It is visible in both standard and Dendrone preview.

**Comment by SeriousBug** [comment]
Could you also share the output from "Dendron:Dev: Diagnostic Report"? Please feel free to send it to SeriousBug on the Dendron discord via private message if you have any privacy concerns.

**Comment by SeriousBug** [comment]
I can't figure out what the issue could be from looking at the diagnostic report. I tried reproducing the issue myself, but I couldn't do so (on Linux). I am guessing that this is a Windows-only issue.

In the next version of Dendron, we'll collect some additional information for the diagnostic report. This should help us figure out why this is happening. I'll ask for the diagnostic report again once we have the next version released. Sorry for all the trouble, we'll get to the bottom of this! :slightly_smiling_face:

**Comment by SeriousBug** [comment]
Hi! Could you please update to Dendron 0.51 and try to recreate this issue? Once you see the broken link, please get the diagnostic report again and send it to me on Discord. The additional information we collect in the diagnostic report should allow me to fix this issue.
