### ISSUE TITLE
Refactor hierarchy does not consider uppercase

### ISSUE THREAD

**Issue by Tycholiz** [dendronhq/dendron#878]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [X] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When I try to refactor a hierachy `network.lan` to `network.LAN`, I get the following error
```
Error - Refactoring would overwrite files
The following files would be overwritten
network.lan.md --> network.LAN.md
network.lan.router.md --> network.LAN.router.md
network.lan.router.nat.md --> network.LAN.router.nat.md
network.lan.router.port-forwarding.md --> network.LAN.router.port-forwarding.md
network.lan.router.port-knocking.md --> network.LAN.router.port-knocking.md
network.lan.router.port-triggering.md --> network.LAN.router.port-triggering.md
```

As we can see in the following directory snapshot, there are no existing hierarchies with uppercase `LAN` 
![image](https://user-images.githubusercontent.com/39745457/123558675-652f0a00-d74c-11eb-805a-fef0fe9355d3.png)

## Desktop (please complete the following information)

- OS: MacOS Catalina 10.15.7
- Version v0.47.1

## Dendron Log file
```
info: {"ctx":"LookupCommand:execute","profile":1,"msg":"post:show"}
info: {"ctx":"updatePickerItems","msg":"enter","queryOrig":"","source":"updatePickerBehavior:normal"}
debug: {"ctx":"updatePickerItems","msg":"empty qs"}
info: {"ctx":"updatePickerItems","msg":"exit","queryOrig":"","source":"updatePickerBehavior:normal","profile":2,"cancelled":false}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"post:updatePickerBehavior"}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"post:provide"}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"exit"}
info: {"ctx":"u:run","msg":"post-execute"}
info: {"ctx":"v:run","msg":"pre-execute"}
info: {"ctx":"RefactorHierarchy:execute","opts":{"match":"network.lan","replace":"network.LAN"},"msg":"enter"}
info: {"ctx":"v:run","msg":"post-execute"}
info: {"ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"extension-output-#5","external":"output:extension-output-%235","path":"extension-output-#5","scheme":"output"}}
info: {"ctx":"WindowWatcher:onDidChangeActiveTextEditor","uri":"extension-output-#5","msg":"not in workspace"}
```

**Comment by Tycholiz** [comment]
yes I see now, only one file is created.

Is this something Dendron can workaround, or is it just something to live with?

**Comment by kevinslin** [comment]
Unfortunately its a file system issue. To fix this, you would need to remove the files and re-create them in lowercase. you might get away with refactoring twice, changing `Ian -> bob` and then `bob -> ian`

**Comment by Tycholiz** [comment]
Sounds good, thanks for the quick look!
