### ISSUE TITLE
Make autocomplete aware of vaults when suggesting notes for linking

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#887]
## Please Select if your Request is Either something new or an Enhancement ##

- [x ] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ x] Retrieve. Backlinks, references, graph view
- [x ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

When creating a wiki link the autocomplete does not differentiate between notes from different vaults, this can lead to confusion and incorrect entries.

## Describe the solution you'd like ##

Autocomplete should alert the user of the source vault, with the link from the current vault listed first.

## Additional ##

Adding this as suggested by @SeriousBug on Discord

**Comment by kpathakota** [comment]
@SeriousBug - could you add what other context you'd like for this and then we can decide whether to work on it immediately/backlog it etc. 

Is this something already in your wheelhouse since working on autocomplete? We've also moved away from vault-specific links (i.e. [[dendron://vault/note]] and are trying to keep things consistent by just linking [[note]].

**Comment by SR--** [comment]
The simplest would be to at least match the way it looks in Lookup where the name of the vault is in the brackets after the suggestion (from memory, I am away from a computer with dendron for a few days).

**Comment by SeriousBug** [comment]
Thanks for the feedback. I'll be working on this enhancement this month.

**Comment by SeriousBug** [comment]
Visual Studio Code 1.58 adds support for [displaying extra information with completion items](https://code.visualstudio.com/api/references/vscode-api#CompletionItemLabel), which is perfect to display the vault information. I'll suggest waiting until we start using that version for Dendron, and then we can take advantage of that feature to display vault names.

**Comment by SeriousBug** [comment]
All features relating to this are now live. Vault names should appear next to notes in autocomplete, and cross-vault links should get generated when needed. I wasn't able to get note previews during autocomplete working, but we will look into adding that feature later.

**Comment by SR--** [comment]
Great. Thanks
________________________________

**Comment by SeriousBug** [comment]
We should investigate if we can display the vault name next to all notes, not just the selection.

**Comment by SR--** [comment]
I wonder if the windows tabs could also have the vault name in brackets. It is confusing with multiple vaults and repeating topics. Of course, one could begin all file names in a vault with a vault labeld but this seems redundant.

**Comment by kevinslin** [comment]
this should be fixed in v54 of Dendron. please post here if not, otherwise this issue will auto close in 3 days

**Comment by SR--** [comment]
It works but only displays the vault of the selected note, not all notes. This is still helpful so if it is too hard to show for all, this is OK. However, what about the suggestion to display the vault in the tab title? This would also help.

**Comment by kevinslin** [comment]
that's a good suggestion. Could you open a separate tracking issue for that?

**Comment by SR--** [comment]
Split tab titles into a new issue as suggested: https://github.com/dendronhq/dendron/issues/1168

**Comment by kevinslin** [comment]
closing the vault suggestion ticket. will triage the tab title in separate ticket
