### ISSUE TITLE
Rename doesn't move child nodes

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#89]
**Describe the bug**
I used the rename command on a top-level node and the child nodes don't get renamed accordingly. 

**To Reproduce**
1. Rename a note

**Actual behavior**
2a. Note gets renamed but all the child notes remain with the old parent (that no longer exists). 

**Expected behavior**
2. Expect to see child notes also renamed (so that the heirarchy is preserved)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**

** Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here
[dendron.log](https://github.com/dendronhq/dendron/files/5048768/dendron.log)

**Comment by kevinslin** [comment]
fixed with 6.0.1 [release](https://github.com/dendronhq/dendron/blob/master/CHANGELOG.md#061-2020-08-11) :)
