### ISSUE TITLE
Merge Notes command

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#906]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [x] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I have instances where I want to merge notes. Perhaps one was a quick temporary effort and I want to combine it with a better developed one. Maybe I decided two notions belong together. If I paste the content into one of the two, and delete one of the notes, the links to it will be broken.

## Describe the solution you'd like ##

Implement a command Merge Notes that would:

1. take note 1 and paste its content at the end of note 2
2. delete note 1
3. refactor links to point to note 2

## Describe alternatives you've considered ##

One can do this via search/replace but this is slower

**Comment by teauxfu** [comment]
This could be useful, but I think the next-best workaround would be to use note [references](https://wiki.dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c.html)
Keeping links healthy should be a bit easier as the notes are more atomic this way, I think

**Comment by SR--** [comment]
Sure, possible in many cases. I am just looking at many notes taken in different situations that are all basically the same or are split opportunistically rather than logically. I want to merge them and then split them again as needed. Splitting is easy, merging is messy.

**Comment by kpathakota** [comment]
@SR-- interesting request, haven't heard of this before but I think this would make interesting new functionality.

**Comment by SR--** [comment]
Thanks for considering. Not a high-priority issues perhaps but is ideologically compatible with the dendron manifesto that promises to make organisational structures fungible.

**Comment by aleksey-rowan** [comment]
I would love to see this as well!

Another use case would be when you need to export a series of notes as a single file. Say you are writing a book and each chapter is a separate note and when you are done, you want to import it into some other tool to format and make a `.pdf` or an `.epub` out of it. It would be easier if you could merge the notes and export/copy-paste just a single file.

Evernote has a `Keep copy of original notes` option when merging notes which doesn't destroy the original sources. This would be very useful in the use case above. I guess, with this option, the links pointing to the original notes will stay that way and _shouldn't_ be repointed to the new, merged note.

**Comment by SR--** [comment]
Good point. Another example and related functionality comes to mind in the cases of teaching, or a reserach consultation, or a design/engineering project. If you want to give people an extract on a topic but the notes are not published, or the publishing is overwhelming for the target audience, you might want to give them a note by itself. But if the links are not functional, it might be constraining. So, one might want to import and merge the content of the links into this one note, with some control: all first order links, first and second order links, based on some filtering...

**Comment by nickolay-kondratyev** [comment]
Another use case that prompts this functionality when there are multiple people creating notes independently and the likelihood of them creating a duplicate notes that later would be needed to merge is decently high.

**Comment by aleksey-rowan** [comment]
This issue is featured in [this week's round](https://discord.com/channels/717965437182410783/739186036495876126/986810056773337168) of [CROP](https://wiki.dendron.so/notes/tayowNP4tMvcqH7AraoQ4/) voting on Dendron's Discord server.

**Comment by hikchoi** [comment]
This feature has been shipped with v109.

Please give it a try and give us feedback if you think it could be improved in any way.

There has been many discussion points in this thread that are not implemented yet, and we are keeping a reference of those for later enhancements.
