### ISSUE TITLE
Depth 1 headers and titles in Preview V2 are smaller than depth 2 headers

### ISSUE THREAD

**Issue by SeriousBug** [dendronhq/dendron#927]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

In Preview V2, depth 1 headers (`# header`) and the title of the note are rendered smaller than depth 2 headers (`## header`).

## To Reproduce

![](https://i.imgur.com/jpbHZrX.png)

## Expected behavior

Depth 1 headers and title should use a larger font size.

## Desktop (please complete the following information)

- OS: Linux
- Version: 0.49.0

**Comment by micharris42** [comment]
Issue with Header size(s) in the new preview seems to have been fixed with the most recent version of Dendron, 0.50.0.

This issue can probably be closed.
