### ISSUE TITLE
Notes with ids starting with `_` being broken on Github pages

### ISSUE THREAD

**Issue by andrey-jef** [dendronhq/dendron#945]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Notes with ids starting with `_ ` being broken on Github pages

## To Reproduce

1. Write a note in Dendron
2. Modify its id in frontmatter so that it has a starting `_` like this: `_FctbPTZZ4ti3R-ZgZTmM`
3. Use command `Dendron: Site Build`
4. Open the published GitHub Pages. You will see a `404 Page not found` instead of the expected note

## Expected behavior

You should see the note with its content instead of a `404 Page not found`

## Screenshots

Note rendered using `Dendron: Site Preview`

![dendron](https://user-images.githubusercontent.com/81280428/124990764-14b78680-e041-11eb-89ad-e595898276e7.jpg)

`404 Page not found` after using `Dendron: Site Build` and `Dendron: Workspace: Sync`

![dendron1](https://user-images.githubusercontent.com/81280428/124990767-15501d00-e041-11eb-8a73-34e85c35bb8f.jpg)

## Desktop (please complete the following information)

- OS: Win10
- Browser: Edge
- Version  91.0.864.64 

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment]
Dendron will no longer generate note id's that don't work on Github pages.

If you have any notes that have bad ids, please use the [fixFrontmatter Doctor command](https://wiki.dendron.so/notes/eea2b078-1acc-4071-a14e-18299fc28f47.html#actions).

**Comment by SeriousBug** [comment]
@andrey-jef Please let me know if you are still having trouble with this issue.
