### ISSUE TITLE
Link to a stub note opens empty file

### ISSUE THREAD

**Issue by xypnox** [dendronhq/dendron#953]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Opening a link to a stub: (Eg `[[scratch.abc]]` when `scratch.abc.def` is  present but `scratch.abc` has not been created yet) throws an error:

<img width="482" alt="Screenshot 2021-07-12 at 15 21 56" src="https://user-images.githubusercontent.com/25076171/125268137-09a47500-e325-11eb-98fa-dbf09f1b1d5e.png">

On clicking "Create file" it opens up an empty note without the dendron frontmatter.

## To Reproduce

1. Create `scratch.abc.def`
2. Click on the link `[[scratch.abc]]`
3. See error
4. Click on Create file
5. See empty file

## Expected behavior

An empty note with dendron frontmatter should be created

## Screenshots

Attached above^

## Desktop (please complete the following information)

- OS: MacOS
- VSCode: 1.57
- Version: 0.49.0

## Dendron Log file

Logs: https://gist.github.com/xypnox/2c0462d678590f7eb87158187a7997f4

**Comment by kpathakota** [comment]
@xypnox - I couldn't repro this myself and the logs don't seem to have errors (you should see something with "level":50 in there)(. Not sure if there's something here to look into here. Have you been able to repro this consistently?

**Comment by xypnox** [comment]
Yep it happens frequently, and I could reproduce this multiple times.

**Comment by hikchoi** [comment]
Are you still encountering this issue?
Clicking on the link should not create a new note. This isn't a feature that Dendron currently has.

If you have `noAutoCreateOnDefinition: true` set in `dendron.yml`, the only way to open a note is to use `Dendron: Goto Note`, which is bound to `ctrl + Enter`.
If you don't have that set in `dendron.yml`, `cmd + hover` or `F12` will trigger VSCode's `Go to Definition`.

In both cases if the note doesn't exist, Dendron creates a new note with the correct frontmatter.
Can you check if you are using other extensions that provides the wikilink click behavior?
