### ISSUE TITLE
"Copy Note Link" adds hash text to the header

### ISSUE THREAD

**Issue by af4jm** [dendronhq/dendron#958]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

I have a header that is also a wiki-link, e.g.

``` markdown
## [[DANIEL|bible.daniel]]
```

If I select part of that link & trigger "Dendron: Copy Note Link", it adds ` ^` then several random characters to the end of the header (& the link text in what is copied is the document Title instead of the header text)

Possibly related to #959 

## Desktop (please complete the following information)

- OS: Windows
- VSCode 1.58.0
- Dendron 0.49.0

**Comment by teauxfu** [comment]
Not sure if the behavior is intentional or not but I think the `^` and random characters are a block anchor for linking to that header specifically 
https://wiki.dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c.html#block-anchor

**Comment by af4jm** [comment]
yes it is... I assume that means Dendron's preview & publish strip those out? As someone using Dendron strictly as a PKM, meaning I'll never publish (for me, the P in PKM is personal & not public), I'm frustrated that the only places I render are in previews in VSCode, iOS, & Android (and Dendron preview v1 is so buggy I had to uninstall it in favor of the built in... might switch back if v2 gets CSS support)... or occasionally in git in my browser, and as much as I like the backlinks feature & Ctrl+L to jump to a link... having wikilinks instead of MD links & having 2000 files in a single folder both causes issues everywhere except VSCode (not to mention that autocomplete only works for [[filename]] and not for [[some text|filename]], which has to be all of my wikilinks because the single folder thing requires `prefix.` at the front of file names & I don't want to see those in preview... it's a trade-off either way & I know Dendron's got some some good stuff coming down the pipe

**Comment by SeriousBug** [comment]
This issue has been fixed with Dendron 0.52. Please let us know if you are still having issues.
