### ISSUE TITLE
"Copy Note Link" cuts off the header text at a wikilink

### ISSUE THREAD

**Issue by af4jm** [dendronhq/dendron#959]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

I have a header that includes wiki-link(s), e.g.

``` markdown
## Outline of [[1|bible.1_kings]] & [[2|bible.2_kings]] Kings
```

If I select part of that link & trigger "Dendron: Copy Note Link", the link I get ends `#outline-of`, cutting off at the wikilink instead of making a GitHub wiki compatible link

Possibly related to issue #958 

## Desktop (please complete the following information)

- OS: Windows
- VSCode 1.58.0
- Dendron 0.49.0

**Comment by SeriousBug** [comment]
This issue has been fixed with Dendron 0.52. Please let us know if you are still having issues.
