### ISSUE TITLE
Dead links in hook doc strings

### ISSUE THREAD

**Issue by jmezzacappa** [dendronhq/dendron#992]
I wasn't sure if the "bug report" template was the right choice for this, so apologies if it causes any confusion.

## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

It is not a bug that affects functionality, but there are invalid links in the hook template's doc strings.

## To Reproduce

Run the "Hook Create" command.

## Expected behavior

Basically the same as what already happens, but with valid links.

## Desktop (please complete the following information)

- OS: macOS
- Browser: VSCode?

## Additional context

These are the links: https://github.com/dendronhq/dendron/blob/f96701c2093ee82b7f0efd38ca819f141e9e3e47/packages/plugin-core/src/commands/CreateHookCommand.ts#L18-L19

The first one goes to a 404 page, and the second one points to a single line.

Also, I don't think the doc strings there are valid JSDoc syntax. Something like this would improve the experience in VSCode:

```javascript
/// <reference types="execa" />
/// <reference types="lodash" />

/**
 * @param {Object} param0 
 * @param {string} param0.wsRoot - ...
 * @param {Object} param0.note - ...
 * @param {Object} param0.NoteUtils - ...
 * @param {import('execa')} param0.execa - ...
 * @param {import('lodash')} param0._ - ...
 */
```

## Dendron Log file

N/A

**Comment by kevinslin** [comment]
confirmed. this will be fixed in the next release!

**Comment by kevinslin** [comment]
fixed!
